
@protocol UIGestureRecognizerDelegate;
@interface _UIActionSlider : UIControl <UIGestureRecognizerDelegate> {

    @"UIView" _contentView;
    @"UIView" _trackDodgeView;
    @"UIView" _trackBackgroundView;
    @"_UIBackdropView" _trackBlurView;
    @"UIView" _trackSolidView;
    @"_UIActionSliderKnob" _knobView;
    @"UIImageView" _knobImageView;
    @"UIView<_UIActionSliderLabel>" _trackLabel;
    @"UIPanGestureRecognizer" _slideGestureRecognizer;
    {CGPoint="x"d"y"d} _slideGestureInitialPoint;
    d _knobPosition;
    d _trackWidthProportion;
    BOOL _showingTrackLabel;
    BOOL _animating;
    q _style;
    q _textStyle;
    @"NSString" _trackText;
    @"UIFont" _trackFont;
    d _trackTextBaselineFromBottom;
    @"<_UIActionSliderDelegate>" _delegate;
    d _knobWidth;
    d _cachedTrackMaskWidth;
    @"_UIVibrantSettings" _vibrantSettings;
    {CGSize="width"d"height"d} _knobImageOffset;
    {CGSize="width"d"height"d} _trackSize;
    {UIEdgeInsets="top"d"left"d"bottom"d"right"d} _knobInsets;
}

 - (void) dealloc;
 - (void) setDelegate:(id)a;
 - (void) didMoveToWindow;
 - (void) layoutSubviews;
 - ({CGSize=dd}) sizeThatFits:({CGSize=dd})a;
 - (void) didMoveToSuperview;
 - (BOOL) isAnimating;
 - (void) setAnimating:(BOOL)a;
 - (id) _knobView;
 - (id) vibrantSettings;
 - (void) setVibrantSettings:(id)a;
 - (id) knobColor;
 - (void) setKnobColor:(id)a;
 - (void) _knobPanGesture:(id)a;
 - (id) initWithFrame:({CGRect={CGPoint=dd}{CGSize=dd}})avibrantSettings:(id)b;
 - (void) setCachedTrackMaskWidth:(d)a;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) knobRect;
 - (void) _makeTrackLabel;
 - (d) _knobWidth;
 - (d) _knobHorizontalPosition;
 - (d) _knobVerticalInset;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) _trackFrame;
 - (d) _knobMinXInset;
 - (id) trackText;
 - (d) trackTextBaselineFromBottom;
 - ({CGSize=dd}) trackSize;
 - (void) _hideTrackLabel:(BOOL)a;
 - (void) setTrackWidthProportion:(d)a;
 - (void) _showTrackLabel;
 - (void) updateAllTrackMasks;
 - (d) knobWidth;
 - ({UIEdgeInsets=dddd}) knobInsets;
 - (d) _knobMinX;
 - (d) _knobAvailableX;
 - (d) _knobMaxXInset;
 - (d) _knobMaxX;
 - (d) trackWidthProportion;
 - (id) trackFont;
 - (d) cachedTrackMaskWidth;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) trackTextRect;
 - (id) trackMaskPath;
 - (void) setMaskPath:(^{CGPath=})aonView:(id)b;
 - (id) trackMaskImage;
 - (void) setMaskFromImage:(id)aonView:(id)b;
 - (BOOL) isShowingTrackLabel;
 - (void) setShowingTrackLabel:(BOOL)a;
 - (void) setKnobPosition:(d)a;
 - (void) _slideCompleted:(BOOL)a;
 - (id) knobMaskPath;
 - (id) knobImage;
 - (void) setKnobImage:(id)a;
 - (void) setKnobImageOffset:({CGSize=dd})a;
 - (void) setTrackText:(id)a;
 - (void) setTrackFont:(id)a;
 - (void) setTrackSize:({CGSize=dd})a;
 - (id) trackLabel;
 - (void) setKnobWidth:(d)a;
 - (void) setKnobInsets:({UIEdgeInsets=dddd})a;
 - (void) openTrackAnimated:(BOOL)a;
 - (void) closeTrackAnimated:(BOOL)a;
 - ({CGSize=dd}) knobImageOffset;
 - (void) setTrackTextBaselineFromBottom:(d)a;
 - (id) slideGestureRecognizer;
 - (d) knobPosition;
 - (id) delegate;
 - (void) setBackgroundColor:(id)a;
 - (void) setTextStyle:(q)a;
 - (q) textStyle;
 - (q) style;
 - (id) initWithFrame:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - (id) backgroundColor;
 - (void) setStyle:(q)a;


@end
