
@protocol UICollectionViewDataSource, UICollectionViewDelegate, UIScrollViewDelegate;
@interface _UIAlertControllerView : UIView <UICollectionViewDataSource, UICollectionViewDelegate, UIScrollViewDelegate> {

    UIAlertController* _alertController;
    UIView* _roundedCornersView;
    UICollectionView* _actionCollectionView;
    _UIAlertControllerCollectionViewFlowLayout* _flowLayout;
    UILabel* _titleLabel;
    UILabel* _messageLabel;
    UILabel* _detailMessageLabel;
    UIView* _contentViewControllerContainerView;
    NSMutableArray* _actionViews;
    UIView<UIAlertControllerBackgroundView>* _backdropView;
    _UIAlertControllerShadowedScrollView* _contentScrollView;
    UIView* _contentScrollViewContentView;
    UIView* _contentView;
    UIView* _foregroundView;
    UIView* _dimmingView;
    _UIKeyboardLayoutAlignmentView* _keyboardLayoutAlignmentView;
    UIView* _keyboardLayoutAlignmentAvailableSpaceView;
    UIAlertControllerVisualStyle* _visualStyle;
    long long _layoutOrientation;
    BOOL _inPopover;
    BOOL _hasDimmingView;
    BOOL _showsCancelAction;
    BOOL _cancelActionIsDiscrete;
    BOOL _shouldHaveBackdropView;
    BOOL _alignsToKeyboard;
    NSMutableArray* _backdropViewConstraints;
    NSMutableArray* _dimmingViewConstraints;
    NSMutableArray* _dimmingViewForegroundViewTopConstraints;
    NSMutableArray* _dimmingViewForegroundViewBottomConstraints;
    NSMutableArray* _dimmingViewConstraintsForAlertStyle;
    NSMutableArray* _dimmingViewConstraintsForActionSheetStyle;
    NSMutableArray* _noDimmingViewConstraints;
    BOOL _hasCachedLargestActionDimension;
    {CGSize="width"d"height"d} _largestActionDimension;
    NSLayoutConstraint* _foregroundViewWidthConstraint;
    NSLayoutConstraint* _contentViewTopConstraint;
    NSLayoutConstraint* _contentViewBottomConstraint;
    NSLayoutConstraint* _titleLabelTopAlignmentConstraint;
    NSLayoutConstraint* _messageLabelTopAlignmentConstraint;
    NSLayoutConstraint* _detailMessageLabelTopAlignmentConstraint;
    NSLayoutConstraint* _contentViewControllerViewLeftConstraint;
    NSLayoutConstraint* _contentViewControllerViewRightConstraint;
    NSLayoutConstraint* _contentViewControllerViewTopConstraint;
    NSLayoutConstraint* _contentViewControllerViewBottomConstraint;
    NSLayoutConstraint* _contentScrollViewBottomConstraint;
    NSLayoutConstraint* _contentViewControllerContainerViewTopAlignmentConstraint;
    NSLayoutConstraint* _contentViewControllerContainerViewWidthConstraint;
    NSLayoutConstraint* _contentViewControllerContainerViewHeightConstraint;
    NSLayoutConstraint* _collectionViewTopAlignmentConstraint;
    NSLayoutConstraint* _centerXConstraint;
    NSLayoutConstraint* _centerYConstraint;
    NSLayoutConstraint* _widthConstraint;
    NSLayoutConstraint* _heightConstraint;
    NSLayoutConstraint* _collectionViewWidthConstraint;
    NSLayoutConstraint* _collectionViewHeightConstraint;
    NSLayoutConstraint* _collectionViewHorizontalAlignmentConstraint;
    NSLayoutConstraint* _discreteCancelActionViewTopConstraint;
    NSLayoutConstraint* _discreteCancelActionViewLeadingConstraint;
    NSLayoutConstraint* _discreteCancelActionViewWidthConstraint;
    NSLayoutConstraint* _discreteCancelActionViewHeightConstraint;
    NSLayoutConstraint* _backdropViewBottomConstraint;
    NSLayoutConstraint* _backdropViewRightConstraint;
}
 + (void) initialize;
 + (BOOL) _retroactivelyRequiresConstraintBasedLayout;

 - (void) _UIAppearance_setAlignsToKeyboard:(BOOL)a;
 - (void) _UIAppearance_setShouldHaveBackdropView:(BOOL)a;
 - (void) _UIAppearance_setShowsCancelAction:(BOOL)a;
 - (void) _UIAppearance_setHasDimmingView:(BOOL)a;
 - (void) _UIAppearance_setInPopover:(BOOL)a;
 - (id) title;
 - (void) dealloc;
 - (void) didMoveToWindow;
 - (id) _foregroundView;
 - (long long) collectionView:(id)anumberOfItemsInSection:(long long)b;
 - (id) collectionView:(id)acellForItemAtIndexPath:(id)b;
 - (id) _flowLayout;
 - (id) preferredFocusedItem;
 - (long long) tintAdjustmentMode;
 - (void) setTintAdjustmentMode:(long long)a;
 - (void) didMoveToSuperview;
 - (void) willMoveToSuperview:(id)a;
 - (void) setLayoutOrientation:(long long)a;
 - (id) message;
 - (id) contentViewController;
 - (id) _dimmingView;
 - (double) _idealWidth;
 - (id) widthConstraint;
 - (id) heightConstraint;
 - (BOOL) inPopover;
 - (id) _visualStyle;
 - (void) _actionsChanged;
 - (void) _propertiesChanged;
 - (void) _updateDefaultAction;
 - (void) setAlertController:(id)a;
 - (void) setHasDimmingView:(BOOL)a;
 - (void) setShouldHaveBackdropView:(BOOL)a;
 - (void) setAlignsToKeyboard:(BOOL)a;
 - (void) _setTitle:(id)a;
 - (void) _setMessage:(id)a;
 - (id) _attributedTitle;
 - (void) _setAttributedTitle:(id)a;
 - (id) _attributedMessage;
 - (void) _setAttributedMessage:(id)a;
 - (id) _attributedDetailMessage;
 - (void) _setAttributedDetailMessage:(id)a;
 - (void) _recomputeAlignedDescriptiveLabelTextWidth;
 - (void) _actionLayoutDirectionChanged;
 - (void) _setVisualStyle:(id)a;
 - (void) setCancelActionIsDiscrete:(BOOL)a;
 - (id) cancelAction;
 - (void) _removeContentViewController;
 - (void) _sizeOfContentViewControllerChanged;
 - (void) setShowsCancelAction:(BOOL)a;
 - ({CGSize=dd}) _contentViewControllerSize;
 - (id) alertController;
 - (void) _contentSizeChanged;
 - (id) actionDelimiterIndices;
 - (void) setInPopover:(BOOL)a;
 - (BOOL) collectionView:(id)acanFocusItemAtIndexPath:(id)b;
 - (BOOL) _hasTitle;
 - (BOOL) _hasMessage;
 - (void) _updateActionViewStyle:(id)a;
 - (void) _prepareViewsAndAddConstraints;
 - (void) _prepareForegroundView;
 - (void) _prepareContentView;
 - (void) _prepareContentScrollView;
 - (void) _prepareTitleLabel;
 - (void) _prepareMesssageLabel;
 - (void) _prepareDetailMessageLabel;
 - (void) _prepareContentViewControllerContainerView;
 - (void) _prepareActionCollectionView;
 - (void) _prepareDimmingView;
 - (void) _prepareKeyboardLayoutAlignmentViews;
 - (void) _applyViewConstraints;
 - (void) _applyTitleConstraints;
 - (void) _applyMessageConstraints;
 - (void) _applyDetailMessageConstraints;
 - (void) _applyContentViewControllerContainerViewConstraints;
 - (void) _prepareDimmingViewConstraints;
 - (void) _invalidateFlowLayout;
 - (BOOL) _buttonsAreTopMost;
 - (double) _labelHorizontalInsets;
 - ({CGSize=dd}) _sizeForLayoutWidthDetermination;
 - (BOOL) _horizontalLayoutCanUseFullWidth;
 - (double) _verticalLayoutWidth;
 - (double) _availableWidthForHorizontalLayout:(BOOL)a;
 - (BOOL) _wantsHorizontalActionSheet;
 - (long long) _numberOfActionsForCollectionView;
 - (double) _idealLayoutWidth;
 - (BOOL) hasDiscreteHorizontalCancelAction;
 - ({CGSize=dd}) _minimumSizeForAllActions;
 - (BOOL) _wantsHorizontalCollectionViewLayout;
 - ({CGSize=dd}) _itemSizeForHorizontalLayout:(BOOL)a;
 - (BOOL) _hasDetailMessage;
 - (BOOL) showsCancelAction;
 - (BOOL) cancelActionIsDiscrete;
 - (BOOL) _canLayOutActionsHorizontally;
 - (id) foregroundViewWidthConstraint;
 - (double) _layoutWidthForHorizontalLayout:(BOOL)a;
 - (void) setForegroundViewWidthConstraint:(id)a;
 - ({CGSize=dd}) _collectionViewSizeForHorizontalLayout:(BOOL)aitemSize:({CGSize=dd})b;
 - (id) collectionViewWidthConstraint;
 - (void) setCollectionViewWidthConstraint:(id)a;
 - (id) collectionViewHeightConstraint;
 - (void) setCollectionViewHeightConstraint:(id)a;
 - (id) collectionViewHorizontalAlignmentConstraint;
 - (void) setCollectionViewHorizontalAlignmentConstraint:(id)a;
 - (BOOL) shouldHaveBackdropView;
 - (id) backdropViewRightConstraint;
 - (void) setBackdropViewRightConstraint:(id)a;
 - (id) _cancelActionView;
 - (double) _marginBetweenContentAndDiscreteCancelAction;
 - (id) _bottomMostViewToAlignDiscreteCancelActionViewTo;
 - (id) discreteCancelActionViewTopConstraint;
 - (void) setDiscreteCancelActionViewTopConstraint:(id)a;
 - (id) discreteCancelActionViewLeadingConstraint;
 - (void) setDiscreteCancelActionViewLeadingConstraint:(id)a;
 - (id) discreteCancelActionViewWidthConstraint;
 - (id) discreteCancelActionViewHeightConstraint;
 - (id) titleLabelTopAlignmentConstraint;
 - (id) messageLabelTopAlignmentConstraint;
 - (id) contentViewControllerContainerViewTopAlignmentConstraint;
 - (id) contentScrollViewBottomConstraint;
 - (id) collectionViewTopAlignmentConstraint;
 - (id) backdropViewBottomConstraint;
 - (id) detailMessageLabelTopAlignmentConstraint;
 - (id) contentViewTopConstraint;
 - (id) contentViewBottomConstraint;
 - (void) setTitleLabelTopAlignmentConstraint:(id)a;
 - (void) setMessageLabelTopAlignmentConstraint:(id)a;
 - (void) setContentViewControllerContainerViewTopAlignmentConstraint:(id)a;
 - (void) setContentScrollViewBottomConstraint:(id)a;
 - (void) setCollectionViewTopAlignmentConstraint:(id)a;
 - (void) setBackdropViewBottomConstraint:(id)a;
 - (void) setDetailMessageLabelTopAlignmentConstraint:(id)a;
 - (BOOL) _hasDiscreteCancelAction;
 - (BOOL) hasDimmingView;
 - (void) setContentViewTopConstraint:(id)a;
 - (void) setContentViewBottomConstraint:(id)a;
 - (void) _updateConstraintConstants;
 - (BOOL) _shouldHaveCancelActionInCollectionView;
 - (id) _actionViewsForCollectionView;
 - (id) defaultAction;
 - (BOOL) _wantsHorizontalAlert;
 - (BOOL) _actionLayoutIsVertical;
 - (void) _updateStyleForIdiomChange:(BOOL)a;
 - (void) _updateLabelFontSizes;
 - (void) _updateLabelTextColor;
 - (void) _updateLabelMaximumLines;
 - (void) _updateVisualAltitude;
 - (void) _updateBackdrop;
 - (void) _updateCollectionViewForVisualStyleChange;
 - (void) _updateCornerRadius;
 - (void) _updateInsets;
 - (BOOL) _hasAttributedTitle;
 - (BOOL) _hasAttributedMessage;
 - (void) _prepareBackdropViewConstraints;
 - (id) _orderedActionViewsForCollectionView;
 - (BOOL) _shouldTreatEmptyStringsAsNil;
 - (void) _reevaluateSuperviewSizingConstraints;
 - (void) setDiscreteCancelActionViewWidthConstraint:(id)a;
 - (void) setDiscreteCancelActionViewHeightConstraint:(id)a;
 - (void) _applyKeyboardAlignmentViewsConstraints;
 - (void) setContentViewControllerViewLeftConstraint:(id)a;
 - (void) setContentViewControllerViewRightConstraint:(id)a;
 - (void) setContentViewControllerViewTopConstraint:(id)a;
 - (void) setContentViewControllerViewBottomConstraint:(id)a;
 - (id) contentViewControllerContainerViewWidthConstraint;
 - (void) setContentViewControllerContainerViewWidthConstraint:(id)a;
 - (id) contentViewControllerContainerViewHeightConstraint;
 - (void) setContentViewControllerContainerViewHeightConstraint:(id)a;
 - (id) contentViewControllerViewLeftConstraint;
 - (id) contentViewControllerViewRightConstraint;
 - (id) contentViewControllerViewTopConstraint;
 - (id) contentViewControllerViewBottomConstraint;
 - (id) centerXConstraint;
 - (id) centerYConstraint;
 - (void) setCenterXConstraint:(id)a;
 - (void) setCenterYConstraint:(id)a;
 - (void) setWidthConstraint:(id)a;
 - (void) setHeightConstraint:(id)a;
 - (BOOL) alignsToKeyboard;
 - (long long) layoutOrientation;
 - (id) initWithFrame:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - (id) actions;


@end
