
@protocol UIGestureRecognizerDelegate, _UIAlertActionRepresenting;
@interface _UIAlertControllerActionView : UIView <UIGestureRecognizerDelegate, _UIAlertActionRepresenting> {

    NSLayoutConstraint* _minimumHeightConstraint;
    UIView* labelContainerView;
    NSLayoutConstraint* _labelContainerLeadingConstraint;
    NSLayoutConstraint* _labelContainerTrailingConstraint;
    UILabel* label;
    UILabel* descriptiveLabel;
    UIImageView* imageView;
    UIImageView* checkView;
    UIView<UIAlertControllerBackgroundView>* highlightedBackgroundContainerView;
    NSMutableArray* highlightedBackgroundConstraints;
    NSMutableArray* havingDescriptiveLabelConstraints;
    NSMutableArray* notHavingDescriptiveLabelConstraints;
    NSLayoutConstraint* _descriptiveLabelWidthConstraint;
    NSMutableArray* _contentViewControllerConstraints;
    UIView* _contentViewControllerContainerView;
    UIAlertAction* _action;
    UIAlertControllerVisualStyle* _visualStyle;
    id selectedTarget;
    SEL selectedAction;
    id highlightTarget;
    SEL highlightAction;
    BOOL _hasDescriptiveText;
    UITapGestureRecognizer* _selectGestureRecognizer;
    BOOL _discrete;
    BOOL _highlighted;
}

 - (id) description;
 - (void) dealloc;
 - (void) touchesBegan:(id)a withEvent:(id)b ;
 - (void) touchesMoved:(id)a withEvent:(id)b ;
 - (void) touchesEnded:(id)a withEvent:(id)b ;
 - (void) touchesCancelled:(id)a withEvent:(id)b ;
 - (void) _physicalButtonsBegan:(id)a withEvent:(id)b ;
 - (void) _physicalButtonsEnded:(id)a withEvent:(id)b ;
 - (void) _physicalButtonsCancelled:(id)a withEvent:(id)b ;
 - (id) action;
 - (void) traitCollectionDidChange:(id)a ;
 - (id) tintColor;
 - (void) focusedViewDidChange;
 - (BOOL) canBecomeFocused;
 - (void) tintColorDidChange;
 - (void) _updateStyle;
 - (void) setHighlighted:(BOOL)a ;
 - (BOOL) isHighlighted;
 - (void) setAction:(id)a ;
 - (void) _updateBackgroundView;
 - (void) setHighlighted:(BOOL)a animated:(BOOL)b ;
 - (void) _uninstallSelectGestureRecognizer;
 - (void) _installSelectGestureRecognizer;
 - (void) _selectGestureChanged:(id)a ;
 - (id) visualStyle;
 - (void) setVisualStyle:(id)a ;
 - (void) _action:(id)a changedToTitle:(id)b ;
 - (void) _action:(id)a changedToTitleTextAlignment:(long long)b ;
 - (void) _action:(id)a changedToEnabled:(BOOL)b ;
 - (void) _action:(id)a changedToChecked:(BOOL)b ;
 - (void) _action:(id)a changedToBeDefault:(BOOL)b ;
 - (void) _action:(id)a updatedImageTintColor:(id)b ;
 - (void) _action:(id)a updatedTitleTextColor:(id)b ;
 - (void) _contentSizeChanged;
 - (void) _prepareConstraints;
 - (void) _updateFontSize;
 - (id) _touchForEvent:(id)a ;
 - (void) _triggerSelect;
 - (long long) _physicalButtonTypeForSelectGesture;
 - (long long) _physicalButtonTypeForBackGesture;
 - (BOOL) _buttonsShouldShowPressedState:(id)a ;
 - (void) _recomputeTextColor;
 - (id) _computedTintColor;
 - (BOOL) discrete;
 - (id) _titleFont;
 - (double) _minimumLabelScaleFactor;
 - (void) _prepareConstraintsForDescriptiveText:(BOOL)a ;
 - (void) _updateTextAlignmentForDescriptiveText:(BOOL)a titleTextAlignment:(long long)b ;
 - (void) _updateLabelContainerConstraints;
 - (void) _recomputeBackgroundColor;
 - (void) _updateMinimumHeight;
 - (BOOL) _idiomSupportsSelectGesture:(long long)a ;
 - (void) setAlignedDescriptiveLabelTextWidth:(double)a ;
 - (double) alignedDescriptiveLabelTextWidth;
 - (double) currentDescriptiveLabelTextWidth;
 - (void) setSelectedTarget:(id)a action:(SEL)b ;
 - (void) setHighlightTarget:(id)a action:(SEL)b ;
 - (void) setDiscrete:(BOOL)a ;
 - (id) initWithFrame:({CGRect={CGPoint=dd}{CGSize=dd}})a ;


@end
