
@interface _UIBackdropView : UIView {

    BOOL _autosizesToFitSuperview;
    BOOL _computesColorSettings;
    BOOL _appliesOutputSettingsAutomatically;
    BOOL _appliesOutputSettingsAutomaticallyEnabledComputesColorSettings;
    BOOL _applyingBackdropChanges;
    BOOL _applyingTransition;
    BOOL _requiresTintViews;
    BOOL _wantsColorSettings;
    BOOL _blursBackground;
    BOOL _allowsColorSettingsSuppression;
    BOOL _contentViewAccessed;
    BOOL _contentViewAccessorGuard;
    BOOL _applySettingsAfterLayout;
    BOOL _updateMaskViewsForViewReentrancyGuard;
    BOOL _simulatesMasks;
    BOOL _backdropVisibilitySetOnce;
    BOOL _blurRadiusSetOnce;
    BOOL _disablesOccludedBackdropBlurs;
    BOOL __backdropVisible;
    BOOL __zoomsBack;
    q _style;
    @"NSHashTable" _observers;
    @"<_UIBackdropViewObserver>" _observer;
    d _appliesOutputSettingsAnimationDuration;
    @"_UIBackdropViewSettings" _inputSettings;
    @"_UIBackdropViewSettings" _outputSettings;
    @"_UIBackdropViewSettings" _savedInputSettingsDuringRenderInContext;
    q _configuration;
    @"_UIBackdropEffectView" _backdropEffectView;
    @"NSString" _groupName;
    @"UIImage" _filterMaskImage;
    @"UIView" _grayscaleTintView;
    @"UIImage" _grayscaleTintMaskImage;
    @"UIView" _colorTintView;
    @"UIImage" _colorTintMaskImage;
    @"UIView" _colorBurnTintView;
    @"UIImage" _colorBurnTintMaskImage;
    @"CAFilter" _gaussianBlurFilter;
    @"CAFilter" _colorSaturateFilter;
    @"CAFilter" _tintFilter;
    @"UIView" _contentView;
    @"UIView" _darkeningTintView;
    @"UIImage" _darkeningTintMaskImage;
    q _maskMode;
    @"NSMutableSet" _partialMaskViews;
    @"UIView" _grayscaleTintMaskViewContainer;
    @"NSMutableDictionary" _grayscaleTintMaskViewMap;
    @"UIView" _colorTintMaskViewContainer;
    @"NSMutableDictionary" _colorTintMaskViewMap;
    @"UIView" _colorBurnTintMaskViewContainer;
    @"NSMutableDictionary" _colorBurnTintMaskViewMap;
    @"UIView" _darkeningTintMaskViewContainer;
    @"NSMutableDictionary" _darkeningTintMaskViewMap;
    @"UIView" _filterMaskViewContainer;
    @"NSMutableDictionary" _filterMaskViewMap;
    id _computeAndApplySettingsNotificationObserver;
    d _colorMatrixGrayscaleTintLevel;
    d _colorMatrixGrayscaleTintAlpha;
    @"UIColor" _colorMatrixColorTint;
    d _colorMatrixColorTintAlpha;
    q _blurHardEdges;
    ^{__CFRunLoopObserver=} _updateInputBoundsRunLoopObserver;
    d _previousBackdropStatisticsRed;
    d _previousBackdropStatisticsGreen;
    d _previousBackdropStatisticsBlue;
    d _previousBackdropStatisticsContrast;
    @"<_UIBackdropViewGraphicsQualityChangeDelegate>" _graphicsQualityChangeDelegate;
    @"NSString" __blurQuality;
    d __blurRadius;
    d __saturationDeltaFactor;
}
 + (Class) layerClass;
 + (id) allBackdropViews;
 + (Class) defaultSettingsClass;
 + (void) suppressColorSettingsForRunLoopModePush:(id)a;
 + (void) restoreColorSettingsForRunLoopModePop:(id)a;
 + (void) suppressColorSettingsForWillResignActive:(id)a;
 + (void) restoreColorSettingsForDidBecomeActive:(id)a;
 + (void) suppressColorSettingsForRequester:(id)a;
 + (void) restoreColorSettingsForRequester:(id)a;
 + (void) setAllBackdropViewsToGraphicsQuality:(q)a;
 + (void) adjustGraphicsQualityForAccessibilityIfNeeded:(id)a;

 - (void) setObserver:(id)a;
 - (void) dealloc;
 - (void) layoutSubviews;
 - (id) grayscaleTintMaskImage;
 - (id) colorTintMaskImage;
 - (id) filterMaskImage;
 - (d) blurRadius;
 - (d) saturationDeltaFactor;
 - (void) setBlurRadius:(d)a;
 - (void) setSaturationDeltaFactor:(d)a;
 - (void) didMoveToSuperview;
 - (void) setGraphicsQualityChangeDelegate:(id)a;
 - (id) initWithPrivateStyle:(q)a;
 - (id) inputSettings;
 - (void) setBlurHardEdges:(q)a;
 - (id) initWithFrame:({CGRect={CGPoint=dd}{CGSize=dd}})astyle:(q)b;
 - (id) initWithStyle:(q)a;
 - (void) updateMaskViewsForView:(id)a;
 - (id) observer;
 - (void) setComputesColorSettings:(BOOL)a;
 - (void) setAllowsColorSettingsSuppression:(BOOL)a;
 - (void) setConfiguration:(q)a;
 - (id) grayscaleTintMaskViewContainer;
 - (id) colorTintMaskViewContainer;
 - (id) colorBurnTintMaskViewContainer;
 - (id) darkeningTintMaskViewContainer;
 - (id) filterMaskViewContainer;
 - (void) transitionToStyle:(q)a;
 - (BOOL) computesColorSettings;
 - (void) willCallRenderInContextOnBackdropViewLayer;
 - (void) didCallRenderInContextOnBackdropViewLayer;
 - (void) setBackdropVisible:(BOOL)a;
 - (void) setGrayscaleTintMaskImage:(id)a;
 - (void) setColorTintMaskImage:(id)a;
 - (void) setFilterMaskImage:(id)a;
 - (id) initWithFrame:({CGRect={CGPoint=dd}{CGSize=dd}})aprivateStyle:(q)b;
 - (void) transitionToPrivateStyle:(q)a;
 - (void) setShouldRasterizeEffectsView:(BOOL)a;
 - (id) effectView;
 - (void) setDisablesOccludedBackdropBlurs:(BOOL)a;
 - (id) blurQuality;
 - (q) blurHardEdges;
 - (void) _updateInputBounds;
 - (d) _blurRadius;
 - (void) transitionToSettings:(id)a;
 - (void) setDarkeningTintMaskImage:(id)a;
 - (void) setBlurQuality:(id)a;
 - (void) setZoomsBack:(BOOL)a;
 - (BOOL) isBackdropVisible;
 - (id) colorBurnTintMaskImage;
 - (void) setColorBurnTintMaskImage:(id)a;
 - (id) darkeningTintMaskImage;
 - (void) settingsDidChange:(id)a;
 - (void) setBlursWithHardEdges:(BOOL)a;
 - (BOOL) blursWithHardEdges;
 - (BOOL) _backdropVisible;
 - (BOOL) _zoomsBack;
 - (id) _blurQuality;
 - (d) _saturationDeltaFactor;
 - (void) setAppliesOutputSettingsAnimationDuration:(d)a;
 - (id) outputSettings;
 - (BOOL) allowsColorSettingsSuppression;
 - (void) setWantsColorSettings:(BOOL)a;
 - (BOOL) wantsColorSettings;
 - (id) graphicsQualityChangeDelegate;
 - (id) backdropViewLayer;
 - (void) setAutosizesToFitSuperview:(BOOL)a;
 - (BOOL) autosizesToFitSuperview;
 - (void) setInputSettings:(id)a;
 - (void) setOutputSettings:(id)a;
 - (void) setObservers:(id)a;
 - (void) updateSubviewHierarchyIfNeededForSettings:(id)a;
 - (void) computeAndApplySettings:(id)a;
 - (void) setComputeAndApplySettingsNotificationObserver:(id)a;
 - (id) initWithFrame:({CGRect={CGPoint=dd}{CGSize=dd}})aautosizesToFitSuperview:(BOOL)bsettings:(id)c;
 - (id) computeAndApplySettingsNotificationObserver;
 - (void) clearUpdateInputBoundsRunLoopObserver;
 - (id) backdropEffectView;
 - (BOOL) applyingBackdropChanges;
 - (BOOL) appliesOutputSettingsAutomatically;
 - (void) applySettingsWithBuiltInAnimation:(id)a;
 - (id) observers;
 - (void) setApplyingBackdropChanges:(BOOL)a;
 - (void) delayedComputeAndApplySettings;
 - (void) setAppliesOutputSettingsAutomaticallyEnabledComputesColorSettings:(BOOL)a;
 - (BOOL) appliesOutputSettingsAutomaticallyEnabledComputesColorSettings;
 - (void) setApplySettingsAfterLayout:(BOOL)a;
 - (BOOL) applySettingsAfterLayout;
 - (void) adjustTintImplementationIfNeeded:(id)a;
 - (void) setMaskImage:(id)aonLayer:(id)b;
 - (id) grayscaleTintView;
 - (id) colorTintView;
 - (id) colorBurnTintView;
 - (id) darkeningTintView;
 - (id) grayscaleTintMaskViewMap;
 - (id) colorTintMaskViewMap;
 - (id) colorBurnTintMaskViewMap;
 - (id) darkeningTintMaskViewMap;
 - (id) filterMaskViewMap;
 - (q) maskMode;
 - (void) setGrayscaleTintMaskViewMap:(id)a;
 - (void) setGrayscaleTintMaskViewContainer:(id)a;
 - (void) setColorTintMaskViewMap:(id)a;
 - (void) setColorTintMaskViewContainer:(id)a;
 - (void) setColorBurnTintMaskViewMap:(id)a;
 - (void) setColorBurnTintMaskViewContainer:(id)a;
 - (void) setDarkeningTintMaskViewMap:(id)a;
 - (void) setDarkeningTintMaskViewContainer:(id)a;
 - (void) setFilterMaskViewMap:(id)a;
 - (void) setFilterMaskViewContainer:(id)a;
 - (BOOL) simulatesMasks;
 - (void) removeOverlayBlendModeFromView:(id)a;
 - (void) applyOverlayBlendModeToView:(id)a;
 - (BOOL) updateMaskViewsForViewReentrancyGuard;
 - (void) setUpdateMaskViewsForViewReentrancyGuard:(BOOL)a;
 - (id) partialMaskViews;
 - (void) setPartialMaskViews:(id)a;
 - (void) updateMaskViewForView:(id)aflag:(q)b;
 - (id) gaussianBlurFilter;
 - (id) colorSaturateFilter;
 - (id) tintFilter;
 - (BOOL) blurRadiusSetOnce;
 - (void) setBlurRadiusSetOnce:(BOOL)a;
 - (void) setBlurFilterWithRadius:(d)ablurQuality:(id)b;
 - (void) setBlurFilterWithRadius:(d)ablurQuality:(id)bblurHardEdges:(q)c;
 - (void) setGaussianBlurFilter:(id)a;
 - (void) _updateFilters;
 - (void) scheduleUpdateInputBoundsIfNeeded;
 - (^{__CFRunLoopObserver=}) updateInputBoundsRunLoopObserver;
 - (void) setUpdateInputBoundsRunLoopObserver:(^{__CFRunLoopObserver=})a;
 - (void) setColorSaturateFilter:(id)a;
 - (void) setTintFilter:(id)a;
 - (d) colorMatrixGrayscaleTintLevel;
 - (d) colorMatrixGrayscaleTintAlpha;
 - (d) colorMatrixColorTintAlpha;
 - (id) colorMatrixColorTint;
 - (void) setColorMatrixGrayscaleTintLevel:(d)a;
 - (void) setColorMatrixGrayscaleTintAlpha:(d)a;
 - (void) setColorMatrixColorTint:(id)a;
 - (void) setColorMatrixColorTintAlpha:(d)a;
 - (BOOL) backdropVisibilitySetOnce;
 - (void) setBackdropVisibilitySetOnce:(BOOL)a;
 - (void) ensureProperSubviewOrdering;
 - (void) setApplyingTransition:(BOOL)a;
 - (void) prepareForTransitionToSettings:(id)a;
 - (void) computeAndApplySettingsForTransition;
 - (void) transitionIncrementallyToSettings:(id)aweighting:(d)b;
 - (void) transitionIncrementallyToStyle:(q)aweighting:(d)b;
 - (BOOL) applyingTransition;
 - (BOOL) contentViewAccessorGuard;
 - (void) setContentViewAccessorGuard:(BOOL)a;
 - (void) setContentViewAccessed:(BOOL)a;
 - (void) addBackdropEffectViewIfNeededForSettings:(id)a;
 - (void) addGrayscaleTintViewIfNeededForSettings:(id)a;
 - (void) addColorTintViewIfNeededForSettings:(id)a;
 - (void) addColorBurnTintViewIfNeededForSettings:(id)a;
 - (void) addContentViewIfNeededForSettings:(id)a;
 - (void) addDarkeningTintViewIfNeededForSettings:(id)a;
 - (void) setBackdropEffectView:(id)a;
 - (void) setAppliesOutputSettingsAutomatically:(BOOL)a;
 - (void) setGrayscaleTintView:(id)a;
 - (void) setColorTintView:(id)a;
 - (void) setColorBurnTintView:(id)a;
 - (void) setDarkeningTintView:(id)a;
 - (BOOL) contentViewAccessed;
 - (BOOL) requiresTintViews;
 - (void) setTintFilterForSettings:(id)a;
 - (void) transitionComplete;
 - (d) appliesOutputSettingsAnimationDuration;
 - (id) initWithFrame:({CGRect={CGPoint=dd}{CGSize=dd}})asettings:(id)b;
 - (void) setMaskMode:(q)a;
 - (void) removeMaskViews;
 - (void) applyOverlayBlendMode:(q)atoView:(id)b;
 - (void) setUsesZoom;
 - (void) _setBlursBackground:(BOOL)a;
 - (void) transitionToColor:(id)a;
 - (void) transitionIncrementallyToPrivateStyle:(q)aweighting:(d)b;
 - (id) savedInputSettingsDuringRenderInContext;
 - (void) setSavedInputSettingsDuringRenderInContext:(id)a;
 - (void) setRequiresTintViews:(BOOL)a;
 - (BOOL) blursBackground;
 - (void) setBlursBackground:(BOOL)a;
 - (void) setSimulatesMasks:(BOOL)a;
 - (d) previousBackdropStatisticsRed;
 - (void) setPreviousBackdropStatisticsRed:(d)a;
 - (d) previousBackdropStatisticsGreen;
 - (void) setPreviousBackdropStatisticsGreen:(d)a;
 - (d) previousBackdropStatisticsBlue;
 - (void) setPreviousBackdropStatisticsBlue:(d)a;
 - (d) previousBackdropStatisticsContrast;
 - (void) setPreviousBackdropStatisticsContrast:(d)a;
 - (void) set_blurQuality:(id)a;
 - (void) set_blurRadius:(d)a;
 - (void) set_saturationDeltaFactor:(d)a;
 - (void) set_backdropVisible:(BOOL)a;
 - (id) init;
 - (q) configuration;
 - (void) removeObserver:(id)a;
 - (void) addObserver:(id)a;
 - (id) contentView;
 - (void) setContentView:(id)a;
 - (q) style;
 - (id) initWithFrame:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - (id) initWithSettings:(id)a;
 - (void) setFrame:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - (void) applySettings:(id)a;
 - (void) setBounds:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - (id) filters;
 - (id) groupName;
 - (BOOL) disablesOccludedBackdropBlurs;
 - (void) backdropLayerStatisticsDidChange:(id)a;
 - (void) setGroupName:(id)a;
 - (void) setStyle:(q)a;


@end
