
@interface _UIBackdropViewSettings : NSObject {

    BOOL _explicitlySetGraphicsQuality;
    BOOL _requiresColorStatistics;
    BOOL _highlighted;
    BOOL _selected;
    BOOL _enabled;
    BOOL _backdropVisible;
    BOOL _zoomsBack;
    BOOL _lightenGrayscaleWithSourceOver;
    BOOL _darkenWithSourceOver;
    BOOL _designMode;
    BOOL _usesBackdropEffectView;
    BOOL _usesGrayscaleTintView;
    BOOL _usesColorTintView;
    BOOL _usesColorBurnTintView;
    BOOL _usesContentView;
    BOOL _usesDarkeningTintView;
    BOOL _appliesTintAndBlurSettings;
    _UIBackdropView _backdrop;
    long long _style;
    long long _graphicsQuality;
    _UIBackdropColorSettings _colorSettings;
    long long _renderingHint;
    long long _stackingLevel;
    double _grayscaleTintLevel;
    double _grayscaleTintAlpha;
    double _grayscaleTintMaskAlpha;
    UIImage _grayscaleTintMaskImage;
    UIColor _colorTint;
    double _colorTintAlpha;
    double _colorTintMaskAlpha;
    UIImage _colorTintMaskImage;
    double _colorBurnTintLevel;
    double _colorBurnTintAlpha;
    UIImage _colorBurnTintMaskImage;
    double _darkeningTintAlpha;
    double _darkeningTintHue;
    double _darkeningTintSaturation;
    double _darkeningTintBrightness;
    UIImage _darkeningTintMaskImage;
    double _blurRadius;
    NSString _blurQuality;
    long long _blurHardEdges;
    double _saturationDeltaFactor;
    double _filterMaskAlpha;
    UIImage _filterMaskImage;
    UIColor _legibleColor;
    UIColor _combinedTintColor;
    double _scale;
    double _statisticsInterval;
    unsigned long long _version;
    long long _suppressSettingsDidChange;
    ^{__CFRunLoopObserver=} _runLoopObserver;
}
@property (nonatomic, assign, readwrite) _UIBackdropView* backdrop;
@property (nonatomic, assign, readwrite) NSNumber* style;
@property (nonatomic, assign, readwrite) NSNumber* graphicsQuality;
@property (nonatomic, assign, readwrite) NSNumber* explicitlySetGraphicsQuality;
@property (nonatomic, assign, readwrite) NSNumber* requiresColorStatistics;
@property (nonatomic, retain, readwrite) _UIBackdropColorSettings* colorSettings;
@property (nonatomic, assign, readwrite) NSNumber* renderingHint;
@property (nonatomic, assign, readwrite) NSNumber* stackingLevel;
@property (nonatomic, assign, readwrite, getter=isHighlighted) NSNumber* highlighted;
@property (nonatomic, assign, readwrite, getter=isSelected) NSNumber* selected;
@property (nonatomic, assign, readwrite, getter=isEnabled) NSNumber* enabled;
@property (nonatomic, assign, readwrite, getter=isBackdropVisible) NSNumber* backdropVisible;
@property (nonatomic, assign, readwrite) NSNumber* zoomsBack;
@property (nonatomic, assign, readwrite) NSNumber* grayscaleTintLevel;
@property (nonatomic, assign, readwrite) NSNumber* grayscaleTintAlpha;
@property (nonatomic, assign, readwrite) NSNumber* grayscaleTintMaskAlpha;
@property (nonatomic, retain, readwrite) UIImage* grayscaleTintMaskImage;
@property (nonatomic, assign, readwrite) NSNumber* lightenGrayscaleWithSourceOver;
@property (nonatomic, retain, readwrite) UIColor* colorTint;
@property (nonatomic, assign, readwrite) NSNumber* colorTintAlpha;
@property (nonatomic, assign, readwrite) NSNumber* colorTintMaskAlpha;
@property (nonatomic, retain, readwrite) UIImage* colorTintMaskImage;
@property (nonatomic, assign, readwrite) NSNumber* colorBurnTintLevel;
@property (nonatomic, assign, readwrite) NSNumber* colorBurnTintAlpha;
@property (nonatomic, retain, readwrite) UIImage* colorBurnTintMaskImage;
@property (nonatomic, assign, readwrite) NSNumber* darkeningTintAlpha;
@property (nonatomic, assign, readwrite) NSNumber* darkeningTintHue;
@property (nonatomic, assign, readwrite) NSNumber* darkeningTintSaturation;
@property (nonatomic, assign, readwrite) NSNumber* darkeningTintBrightness;
@property (nonatomic, retain, readwrite) UIImage* darkeningTintMaskImage;
@property (nonatomic, assign, readwrite) NSNumber* darkenWithSourceOver;
@property (nonatomic, assign, readwrite) NSNumber* blurRadius;
@property (nonatomic, copy, readwrite) NSString* blurQuality;
@property (nonatomic, assign, readwrite) NSNumber* blurHardEdges;
@property (nonatomic, assign, readwrite) NSNumber* blursWithHardEdges;
@property (nonatomic, assign, readwrite) NSNumber* saturationDeltaFactor;
@property (nonatomic, assign, readwrite) NSNumber* filterMaskAlpha;
@property (nonatomic, retain, readwrite) UIImage* filterMaskImage;
@property (nonatomic, retain, readwrite) UIColor* legibleColor;
@property (nonatomic, retain, readwrite) UIColor* combinedTintColor;
@property (nonatomic, assign, readwrite) NSNumber* scale;
@property (nonatomic, assign, readwrite) NSNumber* statisticsInterval;
@property (nonatomic, assign, readwrite) NSNumber* version;
@property (nonatomic, assign, readwrite, setter=setDesignMode:) NSNumber* designMode;
@property (nonatomic, assign, readwrite) NSNumber* usesBackdropEffectView;
@property (nonatomic, assign, readwrite) NSNumber* usesGrayscaleTintView;
@property (nonatomic, assign, readwrite) NSNumber* usesColorTintView;
@property (nonatomic, assign, readwrite) NSNumber* usesColorBurnTintView;
@property (nonatomic, assign, readwrite) NSNumber* usesContentView;
@property (nonatomic, assign, readwrite) NSNumber* usesDarkeningTintView;
@property (nonatomic, assign, readwrite) NSNumber* appliesTintAndBlurSettings;
@property (nonatomic, assign, readwrite) NSNumber* suppressSettingsDidChange;
@property (nonatomic, assign, readwrite) NSNumber* runLoopObserver;
 + (id) settingsForStyle:(long long)a;
 + (id) settingsForPrivateStyle:(long long)agraphicsQuality:(long long)b;
 + (id) settingsForPrivateStyle:(long long)a;
 + (id) darkeningTintColor;
 + (id) settingsForStyle:(long long)agraphicsQuality:(long long)b;

 - (void) setVersion:(unsigned long long)a;
 - (double) scale;
 - (id) description;
 - (void) dealloc;
 - (id) initWithDefaultValues;
 - (id) grayscaleTintMaskImage;
 - (id) colorTintMaskImage;
 - (id) filterMaskImage;
 - (double) blurRadius;
 - (double) saturationDeltaFactor;
 - (BOOL) usesBackdropEffectView;
 - (void) setValuesFromModel:(id)a;
 - (BOOL) requiresColorStatistics;
 - (id) colorSettings;
 - (void) computeOutputSettingsUsingModel:(id)a;
 - (BOOL) usesGrayscaleTintView;
 - (double) grayscaleTintAlpha;
 - (double) grayscaleTintLevel;
 - (BOOL) usesColorTintView;
 - (id) colorTint;
 - (double) colorTintAlpha;
 - (void) setUsesGrayscaleTintView:(BOOL)a;
 - (void) setUsesColorTintView:(BOOL)a;
 - (void) setBlurRadius:(double)a;
 - (void) setSaturationDeltaFactor:(double)a;
 - (void) setHighlighted:(BOOL)a;
 - (BOOL) isHighlighted;
 - (void) setBlurHardEdges:(long long)a;
 - (void) setColorTint:(id)a;
 - (BOOL) isSelected;
 - (void) setSelected:(BOOL)a;
 - (void) setGrayscaleTintAlpha:(double)a;
 - (double) darkeningTintAlpha;
 - (void) setDarkeningTintAlpha:(double)a;
 - (void) setDefaultValues;
 - (void) addKeyPathObserver:(id)a;
 - (void) removeKeyPathObserver:(id)a;
 - (void) restoreDefaultValues;
 - (long long) graphicsQuality;
 - (void) setRequiresColorStatistics:(BOOL)a;
 - (void) setBackdropVisible:(BOOL)a;
 - (void) setGrayscaleTintLevel:(double)a;
 - (void) setGrayscaleTintMaskAlpha:(double)a;
 - (void) setGrayscaleTintMaskImage:(id)a;
 - (void) setColorTintAlpha:(double)a;
 - (void) setColorTintMaskAlpha:(double)a;
 - (void) setColorTintMaskImage:(id)a;
 - (void) setFilterMaskAlpha:(double)a;
 - (void) setFilterMaskImage:(id)a;
 - (void) setUsesBackdropEffectView:(BOOL)a;
 - (void) setLegibleColor:(id)a;
 - (long long) renderingHint;
 - (long long) stackingLevel;
 - (void) setGraphicsQuality:(long long)a;
 - (void) setUsesDarkeningTintView:(BOOL)a;
 - (void) setStatisticsInterval:(double)a;
 - (id) blurQuality;
 - (long long) blurHardEdges;
 - (BOOL) lightenGrayscaleWithSourceOver;
 - (double) colorBurnTintLevel;
 - (double) colorBurnTintAlpha;
 - (double) darkeningTintHue;
 - (double) darkeningTintSaturation;
 - (double) darkeningTintBrightness;
 - (BOOL) darkenWithSourceOver;
 - (BOOL) usesColorBurnTintView;
 - (BOOL) usesDarkeningTintView;
 - (id) initWithDefaultValuesForGraphicsQuality:(long long)a;
 - (void) incrementSuppressSettingsDidChange;
 - (void) setExplicitlySetGraphicsQuality:(BOOL)a;
 - (void) decrementSuppressSettingsDidChange;
 - (void) setUsesContentView:(BOOL)a;
 - (void) setAppliesTintAndBlurSettings:(BOOL)a;
 - (void) setStackingLevel:(long long)a;
 - (void) setDarkeningTintHue:(double)a;
 - (void) setDarkeningTintSaturation:(double)a;
 - (void) setDarkeningTintBrightness:(double)a;
 - (void) setDarkeningTintMaskImage:(id)a;
 - (void) setBlurQuality:(id)a;
 - (void) setZoomsBack:(BOOL)a;
 - (void) scheduleSettingsDidChangeIfNeeded;
 - (void) clearRunLoopObserver;
 - (BOOL) appliesTintAndBlurSettings;
 - (BOOL) isBackdropVisible;
 - (double) colorTintMaskAlpha;
 - (void) setColorBurnTintLevel:(double)a;
 - (void) setColorBurnTintAlpha:(double)a;
 - (id) colorBurnTintMaskImage;
 - (void) setColorBurnTintMaskImage:(id)a;
 - (id) darkeningTintMaskImage;
 - (void) setDarkenWithSourceOver:(BOOL)a;
 - (BOOL) explicitlySetGraphicsQuality;
 - (double) filterMaskAlpha;
 - (double) grayscaleTintMaskAlpha;
 - (void) setLightenGrayscaleWithSourceOver:(BOOL)a;
 - (id) legibleColor;
 - (void) setRenderingHint:(long long)a;
 - (BOOL) usesContentView;
 - (BOOL) zoomsBack;
 - (long long) suppressSettingsDidChange;
 - (void) setSuppressSettingsDidChange:(long long)a;
 - (^{__CFRunLoopObserver=}) runLoopObserver;
 - (void) setRunLoopObserver:(^{__CFRunLoopObserver=})a;
 - (id) backdrop;
 - (void) setBlursWithHardEdges:(BOOL)a;
 - (void) setStackinglevel:(long long)a;
 - (void) setUsesColorBurnTintView:(BOOL)a;
 - (BOOL) blursWithHardEdges;
 - (id) combinedTintColor;
 - (void) setBackdrop:(id)a;
 - (void) setColorSettings:(id)a;
 - (void) setCombinedTintColor:(id)a;
 - (id) init;
 - (unsigned long long) version;
 - (long long) style;
 - (void) setScale:(double)a;
 - (double) statisticsInterval;
 - (void) setStyle:(long long)a;
 - (BOOL) designMode;
 - (void) setDesignMode:(BOOL)a;
 - (BOOL) isEnabled;
 - (void) setEnabled:(BOOL)a;


@end
