
@interface _UIBackdropViewSettings : NSObject {

    BOOL _explicitlySetGraphicsQuality;
    BOOL _requiresColorStatistics;
    BOOL _highlighted;
    BOOL _selected;
    BOOL _enabled;
    BOOL _backdropVisible;
    BOOL _zoomsBack;
    BOOL _lightenGrayscaleWithSourceOver;
    BOOL _darkenWithSourceOver;
    BOOL _designMode;
    BOOL _usesBackdropEffectView;
    BOOL _usesGrayscaleTintView;
    BOOL _usesColorTintView;
    BOOL _usesColorBurnTintView;
    BOOL _usesContentView;
    BOOL _usesDarkeningTintView;
    BOOL _appliesTintAndBlurSettings;
    @"_UIBackdropView" _backdrop;
    q _style;
    q _graphicsQuality;
    @"_UIBackdropColorSettings" _colorSettings;
    q _renderingHint;
    q _stackingLevel;
    d _grayscaleTintLevel;
    d _grayscaleTintAlpha;
    d _grayscaleTintMaskAlpha;
    @"UIImage" _grayscaleTintMaskImage;
    @"UIColor" _colorTint;
    d _colorTintAlpha;
    d _colorTintMaskAlpha;
    @"UIImage" _colorTintMaskImage;
    d _colorBurnTintLevel;
    d _colorBurnTintAlpha;
    @"UIImage" _colorBurnTintMaskImage;
    d _darkeningTintAlpha;
    d _darkeningTintHue;
    d _darkeningTintSaturation;
    d _darkeningTintBrightness;
    @"UIImage" _darkeningTintMaskImage;
    d _blurRadius;
    @"NSString" _blurQuality;
    q _blurHardEdges;
    d _saturationDeltaFactor;
    d _filterMaskAlpha;
    @"UIImage" _filterMaskImage;
    @"UIColor" _legibleColor;
    @"UIColor" _combinedTintColor;
    d _scale;
    d _statisticsInterval;
    Q _version;
    q _suppressSettingsDidChange;
    ^{__CFRunLoopObserver=} _runLoopObserver;
}
@property (nonatomic, assign, readwrite) _UIBackdropView* backdrop;
@property (nonatomic, assign, readwrite) NSNumber* style;
@property (nonatomic, assign, readwrite) NSNumber* graphicsQuality;
@property (nonatomic, assign, readwrite) NSNumber* explicitlySetGraphicsQuality;
@property (nonatomic, assign, readwrite) NSNumber* requiresColorStatistics;
@property (nonatomic, retain, readwrite) _UIBackdropColorSettings* colorSettings;
@property (nonatomic, assign, readwrite) NSNumber* renderingHint;
@property (nonatomic, assign, readwrite) NSNumber* stackingLevel;
@property (nonatomic, assign, readwrite, isHighlighted) NSNumber* highlighted;
@property (nonatomic, assign, readwrite, isSelected) NSNumber* selected;
@property (nonatomic, assign, readwrite, isEnabled) NSNumber* enabled;
@property (nonatomic, assign, readwrite, isBackdropVisible) NSNumber* backdropVisible;
@property (nonatomic, assign, readwrite) NSNumber* zoomsBack;
@property (nonatomic, assign, readwrite) NSNumber* grayscaleTintLevel;
@property (nonatomic, assign, readwrite) NSNumber* grayscaleTintAlpha;
@property (nonatomic, assign, readwrite) NSNumber* grayscaleTintMaskAlpha;
@property (nonatomic, retain, readwrite) UIImage* grayscaleTintMaskImage;
@property (nonatomic, assign, readwrite) NSNumber* lightenGrayscaleWithSourceOver;
@property (nonatomic, retain, readwrite) UIColor* colorTint;
@property (nonatomic, assign, readwrite) NSNumber* colorTintAlpha;
@property (nonatomic, assign, readwrite) NSNumber* colorTintMaskAlpha;
@property (nonatomic, retain, readwrite) UIImage* colorTintMaskImage;
@property (nonatomic, assign, readwrite) NSNumber* colorBurnTintLevel;
@property (nonatomic, assign, readwrite) NSNumber* colorBurnTintAlpha;
@property (nonatomic, retain, readwrite) UIImage* colorBurnTintMaskImage;
@property (nonatomic, assign, readwrite) NSNumber* darkeningTintAlpha;
@property (nonatomic, assign, readwrite) NSNumber* darkeningTintHue;
@property (nonatomic, assign, readwrite) NSNumber* darkeningTintSaturation;
@property (nonatomic, assign, readwrite) NSNumber* darkeningTintBrightness;
@property (nonatomic, retain, readwrite) UIImage* darkeningTintMaskImage;
@property (nonatomic, assign, readwrite) NSNumber* darkenWithSourceOver;
@property (nonatomic, assign, readwrite) NSNumber* blurRadius;
@property (nonatomic, copy, readwrite) NSString* blurQuality;
@property (nonatomic, assign, readwrite) NSNumber* blurHardEdges;
@property (nonatomic, assign, readwrite) NSNumber* blursWithHardEdges;
@property (nonatomic, assign, readwrite) NSNumber* saturationDeltaFactor;
@property (nonatomic, assign, readwrite) NSNumber* filterMaskAlpha;
@property (nonatomic, retain, readwrite) UIImage* filterMaskImage;
@property (nonatomic, retain, readwrite) UIColor* legibleColor;
@property (nonatomic, retain, readwrite) UIColor* combinedTintColor;
@property (nonatomic, assign, readwrite) NSNumber* scale;
@property (nonatomic, assign, readwrite) NSNumber* statisticsInterval;
@property (nonatomic, assign, readwrite) NSNumber* version;
@property (nonatomic, assign, readwrite, setDesignMode:) NSNumber* designMode;
@property (nonatomic, assign, readwrite) NSNumber* usesBackdropEffectView;
@property (nonatomic, assign, readwrite) NSNumber* usesGrayscaleTintView;
@property (nonatomic, assign, readwrite) NSNumber* usesColorTintView;
@property (nonatomic, assign, readwrite) NSNumber* usesColorBurnTintView;
@property (nonatomic, assign, readwrite) NSNumber* usesContentView;
@property (nonatomic, assign, readwrite) NSNumber* usesDarkeningTintView;
@property (nonatomic, assign, readwrite) NSNumber* appliesTintAndBlurSettings;
@property (nonatomic, assign, readwrite) NSNumber* suppressSettingsDidChange;
@property (nonatomic, assign, readwrite) NSNumber* runLoopObserver;
 + (id) settingsForStyle:(q)a;
 + (id) settingsForPrivateStyle:(q)agraphicsQuality:(q)b;
 + (id) settingsForPrivateStyle:(q)a;
 + (id) darkeningTintColor;
 + (id) settingsForStyle:(q)agraphicsQuality:(q)b;

 - (void) setVersion:(Q)a;
 - (d) scale;
 - (id) description;
 - (void) dealloc;
 - (id) initWithDefaultValues;
 - (id) grayscaleTintMaskImage;
 - (id) colorTintMaskImage;
 - (id) filterMaskImage;
 - (d) blurRadius;
 - (d) saturationDeltaFactor;
 - (BOOL) usesBackdropEffectView;
 - (void) setValuesFromModel:(id)a;
 - (BOOL) requiresColorStatistics;
 - (id) colorSettings;
 - (void) computeOutputSettingsUsingModel:(id)a;
 - (BOOL) usesGrayscaleTintView;
 - (d) grayscaleTintAlpha;
 - (d) grayscaleTintLevel;
 - (BOOL) usesColorTintView;
 - (id) colorTint;
 - (d) colorTintAlpha;
 - (void) setUsesGrayscaleTintView:(BOOL)a;
 - (void) setUsesColorTintView:(BOOL)a;
 - (void) setBlurRadius:(d)a;
 - (void) setSaturationDeltaFactor:(d)a;
 - (void) setHighlighted:(BOOL)a;
 - (BOOL) isHighlighted;
 - (void) setBlurHardEdges:(q)a;
 - (void) setColorTint:(id)a;
 - (BOOL) isSelected;
 - (void) setSelected:(BOOL)a;
 - (void) setGrayscaleTintAlpha:(d)a;
 - (d) darkeningTintAlpha;
 - (void) setDarkeningTintAlpha:(d)a;
 - (void) setDefaultValues;
 - (void) addKeyPathObserver:(id)a;
 - (void) removeKeyPathObserver:(id)a;
 - (void) restoreDefaultValues;
 - (q) graphicsQuality;
 - (void) setRequiresColorStatistics:(BOOL)a;
 - (void) setBackdropVisible:(BOOL)a;
 - (void) setGrayscaleTintLevel:(d)a;
 - (void) setGrayscaleTintMaskAlpha:(d)a;
 - (void) setGrayscaleTintMaskImage:(id)a;
 - (void) setColorTintAlpha:(d)a;
 - (void) setColorTintMaskAlpha:(d)a;
 - (void) setColorTintMaskImage:(id)a;
 - (void) setFilterMaskAlpha:(d)a;
 - (void) setFilterMaskImage:(id)a;
 - (void) setUsesBackdropEffectView:(BOOL)a;
 - (void) setLegibleColor:(id)a;
 - (q) renderingHint;
 - (q) stackingLevel;
 - (void) setGraphicsQuality:(q)a;
 - (void) setUsesDarkeningTintView:(BOOL)a;
 - (void) setStatisticsInterval:(d)a;
 - (id) blurQuality;
 - (q) blurHardEdges;
 - (BOOL) lightenGrayscaleWithSourceOver;
 - (d) colorBurnTintLevel;
 - (d) colorBurnTintAlpha;
 - (d) darkeningTintHue;
 - (d) darkeningTintSaturation;
 - (d) darkeningTintBrightness;
 - (BOOL) darkenWithSourceOver;
 - (BOOL) usesColorBurnTintView;
 - (BOOL) usesDarkeningTintView;
 - (id) initWithDefaultValuesForGraphicsQuality:(q)a;
 - (void) incrementSuppressSettingsDidChange;
 - (void) setExplicitlySetGraphicsQuality:(BOOL)a;
 - (void) decrementSuppressSettingsDidChange;
 - (void) setUsesContentView:(BOOL)a;
 - (void) setAppliesTintAndBlurSettings:(BOOL)a;
 - (void) setStackingLevel:(q)a;
 - (void) setDarkeningTintHue:(d)a;
 - (void) setDarkeningTintSaturation:(d)a;
 - (void) setDarkeningTintBrightness:(d)a;
 - (void) setDarkeningTintMaskImage:(id)a;
 - (void) setBlurQuality:(id)a;
 - (void) setZoomsBack:(BOOL)a;
 - (void) scheduleSettingsDidChangeIfNeeded;
 - (void) clearRunLoopObserver;
 - (BOOL) appliesTintAndBlurSettings;
 - (BOOL) isBackdropVisible;
 - (d) colorTintMaskAlpha;
 - (void) setColorBurnTintLevel:(d)a;
 - (void) setColorBurnTintAlpha:(d)a;
 - (id) colorBurnTintMaskImage;
 - (void) setColorBurnTintMaskImage:(id)a;
 - (id) darkeningTintMaskImage;
 - (void) setDarkenWithSourceOver:(BOOL)a;
 - (BOOL) explicitlySetGraphicsQuality;
 - (d) filterMaskAlpha;
 - (d) grayscaleTintMaskAlpha;
 - (void) setLightenGrayscaleWithSourceOver:(BOOL)a;
 - (id) legibleColor;
 - (void) setRenderingHint:(q)a;
 - (BOOL) usesContentView;
 - (BOOL) zoomsBack;
 - (q) suppressSettingsDidChange;
 - (void) setSuppressSettingsDidChange:(q)a;
 - (^{__CFRunLoopObserver=}) runLoopObserver;
 - (void) setRunLoopObserver:(^{__CFRunLoopObserver=})a;
 - (id) backdrop;
 - (void) setBlursWithHardEdges:(BOOL)a;
 - (void) setStackinglevel:(q)a;
 - (void) setUsesColorBurnTintView:(BOOL)a;
 - (BOOL) blursWithHardEdges;
 - (id) combinedTintColor;
 - (void) setBackdrop:(id)a;
 - (void) setColorSettings:(id)a;
 - (void) setCombinedTintColor:(id)a;
 - (id) init;
 - (Q) version;
 - (q) style;
 - (void) setScale:(d)a;
 - (d) statisticsInterval;
 - (void) setStyle:(q)a;
 - (BOOL) designMode;
 - (void) setDesignMode:(BOOL)a;
 - (BOOL) isEnabled;
 - (void) setEnabled:(BOOL)a;


@end
