
@protocol UIPickerViewDelegate, UIPickerViewDataSource;
@interface _UIDatePickerView : UIPickerView <UIPickerViewDelegate, UIPickerViewDataSource> {

    long long _loadingDate;
    NSDate* _userSuppliedDate;
    NSDate* _userSuppliedMinimumDate;
    NSDate* _userSuppliedMaximumDate;
    NSLocale* _compositeLocale;
    NSLocale* _userProvidedLocale;
    NSCalendar* _userProvidedCalendar;
    _UIDatePickerChineseCalendar* _chineseWrapperCalendar;
    NSDate* _minimumDate;
    NSDate* _maximumDate;
    NSDateComponents* _lastSelectedDateComponents;
    BOOL _allowsZeroTimeInterval;
    _UIDatePickerMode* _mode;
    NSTimeZone* _timeZone;
    double _timeInterval;
    UILabel* _hourLabel;
    UILabel* _minuteLabel;
    UIDatePicker* _datePickerDelegate;
    id _delegateOfDatePicker;
    int _expectedAMPM;
    {?="staggerTimeIntervals"b1"loadingDateOrTime"b1"highlightsToday"b1"usesBlackChrome"b1} _datePickerFlags;
}

 - (void) dealloc;
 - (double) timeInterval;
 - (void) setDelegate:(id)a ;
 - (void) setTimeZone:(id)a ;
 - (id) date;
 - (id) locale;
 - (id) timeZone;
 - (int) hour;
 - (int) minute;
 - (int) second;
 - (id) calendar;
 - (id) pickerImageNamePrefix;
 - (id) _orientationImageSuffix;
 - (void) _selectRow:(long long)a inComponent:(long long)b animated:(BOOL)c notify:(BOOL)d ;
 - (long long) numberOfComponentsInPickerView:(id)a ;
 - (long long) pickerView:(id)a numberOfRowsInComponent:(long long)b ;
 - (double) pickerView:(id)a widthForComponent:(long long)b ;
 - (double) pickerView:(id)a rowHeightForComponent:(long long)b ;
 - (double) _tableRowHeight;
 - (void) layoutSubviews;
 - (void) _resetSelectionOfTables;
 - (id) pickerView:(id)a viewForRow:(long long)b forComponent:(long long)c reusingView:(id)d ;
 - (void) pickerView:(id)a didSelectRow:(long long)b inComponent:(long long)c ;
 - (void) pickerTableView:(id)a didChangeSelectionBarRowFrom:(long long)b to:(long long)c ;
 - (void) scrollViewWillBeginDragging:(id)a ;
 - (void) setDate:(id)a ;
 - (void) setTimeInterval:(double)a ;
 - (void) setDatePickerMode:(long long)a ;
 - (void) setMinuteInterval:(long long)a ;
 - (BOOL) _isTimeIntervalMode;
 - (void) setMinimumDate:(id)a ;
 - (void) setMaximumDate:(id)a ;
 - (long long) datePickerMode;
 - (BOOL) _hasCustomLocale;
 - (BOOL) _hasCustomCalendar;
 - (id) minimumDate;
 - (id) maximumDate;
 - (long long) minuteInterval;
 - (id) userProvidedLocale;
 - (void) setUserProvidedLocale:(id)a ;
 - (id) userProvidedCalendar;
 - (void) setUserProvidedCalendar:(id)a ;
 - (void) setDate:(id)a animated:(BOOL)b ;
 - (void) setDelegateOfDatePicker:(id)a ;
 - (id) dateComponents;
 - (void) setDateComponents:(id)a ;
 - (void) setStaggerTimeIntervals:(BOOL)a ;
 - (void) setHighlightsToday:(BOOL)a ;
 - (void) _setHidesLabels:(BOOL)a ;
 - (BOOL) _updateDateOrTime;
 - (void) _setUsesBlackChrome:(BOOL)a ;
 - (BOOL) _usesBlackChrome;
 - (BOOL) _allowsZeroCountDownDuration;
 - (void) _setAllowsZeroCountDownDuration:(BOOL)a ;
 - (BOOL) _allowsZeroTimeInterval;
 - (void) _setAllowsZeroTimeInterval:(BOOL)a ;
 - (id) _selectedTextForCalendarUnit:(unsigned long long)a ;
 - (id) _labelTextForCalendarUnit:(unsigned long long)a ;
 - (void) _rebuildCompositeLocale;
 - (void) _datePickerReset:(id)a ;
 - (void) _todayChanged:(id)a ;
 - (BOOL) _updatedLastSelectedComponentsByValidatingSelectedDateWithLastManipulatedComponent:(long long)a ;
 - (BOOL) _isCurrentCalendar:(id)a ;
 - (void) _setDate:(id)a animated:(BOOL)b forced:(BOOL)c ;
 - (void) _doneLoadingDateOrTime;
 - (void) _loadDate:(id)a animated:(BOOL)b ;
 - (void) _updateEnabledCellsIncludingWMDCells:(BOOL)a ;
 - (void) _setMode:(id)a ;
 - (long long) _amPmValue;
 - (id) _componentsSelectedAfterEnforcingValidityOfComponents:(id)a withLastManipulatedComponent:(long long)b ;
 - (int) _selectedHourForColumn:(int)a ;
 - (id) _hoursStringForHour:(long long)a ;
 - (void) _fadeLabelForCalendarUnit:(unsigned long long)a toText:(id)b animated:(BOOL)c ;
 - (int) _selectedMinuteForColumn:(int)a ;
 - (id) _minutesStringForHour:(long long)a minutes:(long long)b ;
 - (id) _contentViewForSizingLabelForPositioningInComponent:(long long)a ;
 - (id) _hrMinFont;
 - (id) _labelForCalendarUnit:(unsigned long long)a createIfNecessary:(BOOL)b ;
 - (id) _makeNewAccessoryLabel;
 - (void) _positionLabel:(id)a forCalendarUnit:(unsigned long long)b relativeTo:(id)c order:(long long)d ;
 - (void) _setLabel:(id)a forCalendarUnit:(unsigned long long)b animated:(BOOL)c ;
 - (void) _updateLabels:(BOOL)a ;
 - (BOOL) _showingDate;
 - (id) _viewForSelectedRowInComponent:(long long)a ;
 - (id) delegateOfDatePicker;
 - (id) _lastSelectedDateComponents;
 - (BOOL) staggerTimeIntervals;
 - (BOOL) highlightsToday;
 - (long long) _selectionBarRowInComponent:(long long)a ;
 - (double) contentWidth;
 - (id) initWithFrame:({CGRect={CGPoint=dd}{CGSize=dd}})a ;
 - (void) setFrame:({CGRect={CGPoint=dd}{CGSize=dd}})a ;
 - (id) shadowColor;


@end
