
@interface _UIGlintyStringView : UIView {

    BOOL _animationRepeats;
    BOOL _adjustsFontSizeToFitWidth;
    BOOL _hasCustomBackgroundColor;
    BOOL _highlight;
    BOOL _allowsLuminanceAdjustments;
    BOOL _usesBackgroundDimming;
    BOOL _needsTextUpdate;
    BOOL _animating;
    BOOL _fading;
    BOOL _showing;
    i _textIndex;
    @"<_UIGlintyStringViewDelegate>" _delegate;
    @"NSString" _text;
    @"UIFont" _font;
    @"NSString" _textLanguage;
    @"_UILegibilitySettings" _legibilitySettings;
    @"_UIVibrantSettings" _vibrantSettings;
    @"UIView" _backgroundView;
    @"UIColor" _backgroundColor;
    @"UIColor" _chevronBackgroundColor;
    q _chevronStyle;
    d _horizontalPadding;
    @"UILabel" _label;
    @"UIView" _spotlightView;
    @"UIImage" _chevron;
    @"UIView" _highlightView;
    @"UIView" _effectView;
    @"UIView" _blurView;
    @"UIView" _shimmerImageView;
    @"UIView" _reflectionImageView;
    d _blurAlpha;
    @"NSMutableSet" _blurHiddenRequesters;
    {CGSize="width"d"height"d} _labelSize;
    {CGRect="origin"{CGPoint="x"d"y"d}"size"{CGSize="width"d"height"d}} _chevronFrame;
}

 - (void) dealloc;
 - (void) setDelegate:(id)a;
 - (void) hide;
 - (BOOL) showing;
 - (void) show;
 - (void) didMoveToWindow;
 - (void) layoutSubviews;
 - ({CGSize=dd}) sizeThatFits:({CGSize=dd})a;
 - (id) _highlightColor;
 - (void) setFont:(id)a;
 - (void) setText:(id)a;
 - (void) setAdjustsFontSizeToFitWidth:(BOOL)a;
 - (BOOL) adjustsFontSizeToFitWidth;
 - (void) setBackgroundView:(id)a;
 - (id) backgroundView;
 - (BOOL) isAnimating;
 - (void) stopAnimating;
 - (void) startAnimating;
 - (void) setAnimating:(BOOL)a;
 - (void) setLabel:(id)a;
 - (void) fadeOutWithDuration:(d)a;
 - (BOOL) animating;
 - (void) setHighlightView:(id)a;
 - (void) setChevronStyle:(q)a;
 - (void) updateText;
 - (void) setNeedsTextUpdate:(BOOL)a;
 - (BOOL) hasCustomBackgroundColor;
 - (id) effectView;
 - (void) setBlurAlpha:(d)a;
 - (id) blurView;
 - (void) updateBlurForHiddenRequesters;
 - (BOOL) fading;
 - (void) addGlintyAnimations;
 - (void) removeGlintyAnimations;
 - (void) hideEffects;
 - (void) hideBlur;
 - (void) setShowing:(BOOL)a;
 - (void) showEffects;
 - (void) showBlur;
 - (void) setFading:(BOOL)a;
 - (void) fadeInWithDuration:(d)a;
 - (id) _chevronImageForStyle:(q)a;
 - (void) setChevron:(id)a;
 - (void) updateTextWithBounds:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - (d) _chevronWidthWithPadding;
 - (d) _chevronWidthWithPaddingCompression:(d)a;
 - (d) _chevronHeightWithMaxOffset;
 - (void) _updateLabelWithFrame:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - (d) _chevronVerticalOffset;
 - (BOOL) allowsLuminanceAdjustments;
 - (id) vibrantSettings;
 - (void) setEffectView:(id)a;
 - (id) shapeViewForCharactersInString:(id)awithFont:(id)bcenteredInFrame:({CGRect={CGPoint=dd}{CGSize=dd}})c;
 - (id) chevron;
 - (void) setShimmerImageView:(id)a;
 - (void) setReflectionImageView:(id)a;
 - (BOOL) usesBackgroundDimming;
 - (void) setBlurView:(id)a;
 - (d) blurAlpha;
 - (id) shimmerImageView;
 - (id) reflectionImageView;
 - (void) addShimmerAnimationToLayer:(id)a;
 - (void) addReflectionAnimationToLayer:(id)a;
 - (id) _highlightCompositingFilter;
 - (BOOL) needsTextUpdate;
 - ({CGSize=dd}) _labelSizeThatFits:({CGSize=dd})a;
 - (d) _chevronPadding;
 - (d) baselineOffsetFromBottomWithSize:({CGSize=dd})a;
 - (id) initWithText:(id)aandFont:(id)b;
 - (void) setTextLanguage:(id)a;
 - (void) setLegibilitySettings:(id)a;
 - (void) setVibrantSettings:(id)a;
 - (void) setBlurHidden:(BOOL)aforRequester:(id)b;
 - (void) fadeOut;
 - (void) fadeIn;
 - (void) setHighlight:(BOOL)a;
 - (void) setHorizontalPadding:(d)a;
 - (void) _updateHighlight;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) labelFrame;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) chevronFrame;
 - (d) baselineOffsetFromBottom;
 - (id) textLanguage;
 - (void) setChevronFrame:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - (id) legibilitySettings;
 - (id) chevronBackgroundColor;
 - (void) setChevronBackgroundColor:(id)a;
 - (BOOL) animationRepeats;
 - (void) setAnimationRepeats:(BOOL)a;
 - (void) setHasCustomBackgroundColor:(BOOL)a;
 - (q) chevronStyle;
 - (d) horizontalPadding;
 - (void) setAllowsLuminanceAdjustments:(BOOL)a;
 - (void) setUsesBackgroundDimming:(BOOL)a;
 - ({CGSize=dd}) labelSize;
 - (void) setLabelSize:({CGSize=dd})a;
 - (id) spotlightView;
 - (void) setSpotlightView:(id)a;
 - (i) textIndex;
 - (void) setTextIndex:(i)a;
 - (id) blurHiddenRequesters;
 - (void) setBlurHiddenRequesters:(id)a;
 - (id) delegate;
 - (void) setBackgroundColor:(id)a;
 - (id) backgroundColor;
 - (id) font;
 - (id) label;
 - (BOOL) highlight;
 - (id) highlightView;
 - (id) text;


@end
