
@protocol _UIRemoteViewController_ViewControllerOperatorInterface, _UIRemoteViewController_TextEffectsOperatorInterface, UIActionSheetDelegate;
@interface _UIRemoteViewController : UIViewController <_UIRemoteViewController_ViewControllerOperatorInterface, _UIRemoteViewController_TextEffectsOperatorInterface, UIActionSheetDelegate> {

    NSString* _serviceBundleIdentifier;
    _UIViewServiceInterface* _serviceInterface;
    _UIRemoteViewService* _remoteViewService;
    id _serviceViewControllerProxy;
    id _serviceViewControllerControlMessageProxy;
    NSArray* _serviceViewControllerSupportedInterfaceOrientations;
    unsigned int _serviceAccessibilityServerPort;
    unsigned long long _serviceRegisteredScrollToTopViewCount;
    int _applicationDeactivationReason;
    id _viewControllerOperatorProxy;
    _UIAsyncInvocation* _viewControllerOperatorHalfDisconnectionInvocation;
    id _textEffectsOperatorProxy;
    _UIAsyncInvocation* _textEffectsOperatorHalfDisconnectionInvocation;
    BOOL _fencingCurrentTransaction;
    int _preFencedCommitActionsLock;
    NSMutableArray* _preFencedCommitActions;
    _UISizeTrackingView* _sizeTrackingView;
    _UIRemoteView* _serviceViewControllerRemoteView;
    _UITextEffectsRemoteView* _fullScreenTextEffectsRemoteView;
    _UITextEffectsRemoteView* _textEffectsAboveStatusBarRemoteView;
    _UITextEffectsRemoteView* _remoteKeyboardRemoteView;
    UIView* _fullScreenTextEffectsSnapshotView;
    BOOL _snapshotTextEffectsAfterRotation;
    unsigned int _serviceScreenDisplayID;
    _UIAsyncInvocation* _terminationInvocation;
    int _terminationErrorLock;
    NSError* _terminationError;
    UIActionSheet* _hostedActionSheet;
    _UITextServiceSession* _textServiceSession;
    int __automatic_invalidation_retainCount;
    BOOL __automatic_invalidation_invalidated;
    UIDimmingView* _hostedDimmingView;
    UIView* _touchGrabbingView;
    long long _preferredStatusBarStyle;
    BOOL _prefersStatusBarHidden;
    BOOL _isFocusDeferred;
    NSString* _deferredDisplayUUID;
    unsigned int _deferredContextID;
    NSArray* _allowedNotifications;
    BOOL _isUpdatingSize;
    BOOL _serviceViewShouldShareTouchesWithHost;
    BKSTouchDeliveryPolicyAssertion* _touchDeliveryPolicyAssertion;
}
 + (id) exportedInterface;
 + (BOOL) _shouldSendLegacyMethodsFromViewWillTransitionToSize;
 + (BOOL) _shouldForwardViewWillTransitionToSize;
 + (id) serviceViewControllerInterface;
 + (id) requestViewControllerWithService:(id)aconnectionHandler:(@?)b;
 + (BOOL) __shouldHostRemoteTextEffectsWindow;
 + (id) _requestViewController:(id)atraitCollection:(id)bfromServiceWithBundleIdentifier:(id)cservice:(id)dconnectionHandler:(@?)e;
 + (BOOL) shouldPropagateAppearanceCustomizations;
 + (BOOL) __shouldAllowHostProcessToTakeFocus;
 + (id) requestViewController:(id)afromServiceWithBundleIdentifier:(id)bconnectionHandler:(@?)c;
 + (id) requestViewController:(id)atraitCollection:(id)bfromServiceWithBundleIdentifier:(id)cconnectionHandler:(@?)d;
 + (id) requestViewControllerWithService:(id)atraitCollection:(id)bconnectionHandler:(@?)c;

 - (id) disconnect;
 - (id) retain;
 - (Vv) release;
 - (unsigned long long) retainCount;
 - (void) dealloc;
 - (BOOL) _tryRetain;
 - (BOOL) _isDeallocating;
 - (long long) preferredStatusBarStyle;
 - (BOOL) prefersStatusBarHidden;
 - (unsigned long long) supportedInterfaceOrientations;
 - (void) actionSheet:(id)a clickedButtonAtIndex:(long long)b ;
 - (void) __willChangeToIdiom:(long long)a onScreen:(id)b ;
 - (BOOL) canBecomeFirstResponder;
 - (void) viewDidMoveToWindow:(id)a shouldAppearOrDisappear:(BOOL)b ;
 - (void) viewWillTransitionToSize:({CGSize=dd})a withTransitionCoordinator:(id)b ;
 - (void) willTransitionToTraitCollection:(id)a withTransitionCoordinator:(id)b ;
 - (void) loadView;
 - (id) serviceViewControllerProxy;
 - (void) didMoveToParentViewController:(id)a ;
 - (BOOL) shouldAutorotateToInterfaceOrientation:(long long)a ;
 - (void) viewWillAppear:(BOOL)a ;
 - (void) _setContentOverlayInsets:({UIEdgeInsets=dddd})a ;
 - (BOOL) _customizesForPresentationInPopover;
 - (void) _traitCollectionDidChange:(id)a ;
 - (void) viewDidAppear:(BOOL)a ;
 - (void) viewWillDisappear:(BOOL)a ;
 - (void) viewDidDisappear:(BOOL)a ;
 - (BOOL) _ignoreAppSupportedOrientations;
 - (void) _willRotateToInterfaceOrientation:(long long)a duration:(double)b forwardToChildControllers:(BOOL)c skipSelf:(BOOL)d ;
 - (void) _willAnimateRotationToInterfaceOrientation:(long long)a duration:(double)b forwardToChildControllers:(BOOL)c skipSelf:(BOOL)d ;
 - (void) _didRotateFromInterfaceOrientation:(long long)a forwardToChildControllers:(BOOL)b skipSelf:(BOOL)c ;
 - (void) _willBecomeContentViewControllerOfPopover:(id)a ;
 - (void) _didResignContentViewControllerOfPopover:(id)a ;
 - (BOOL) _requiresKeyboardWindowWhenFirstResponder;
 - (void) viewServiceDidTerminateWithError:(id)a ;
 - (void) _applicationDidEnterBackground:(id)a ;
 - (void) _applicationWillEnterForeground:(id)a ;
 - (void) dimmingViewWasTapped:(id)a ;
 - (id) serviceViewControllerProxyWithErrorHandler:(@?)a ;
 - (int) __automatic_invalidation_logic;
 - (void) _applicationDidBecomeActive:(id)a ;
 - ({CGSize=dd}) intrinsicContentSizeForServiceSize:({CGSize=dd})a ;
 - (void) viewDidInvalidateIntrinsicContentSize;
 - (BOOL) _isUpdatingSize;
 - (BOOL) __shouldRemoteViewControllerFenceOperations;
 - (void) synchronizeAnimationsInActions:(@?)a ;
 - (void) _scrollToTopFromTouchAtViewLocation:({CGPoint=dd})a resultHandler:(@?)b ;
 - (BOOL) _serviceHasScrollToTopView;
 - (BOOL) serviceViewShouldShareTouchesWithHost;
 - (void) _prepareTouchDeliveryPolicy;
 - (void) _setTouchDeliveryPolicyAssertion:(id)a ;
 - (id) _initWithViewServiceBundleIdentifier:(id)a ;
 - (void) _awakeWithConnectionInfo:(id)a ;
 - (id) _terminateWithError:(id)a ;
 - (void) _firstResponderDidChange:(id)a ;
 - (void) _statusBarOrientationDidChange:(id)a ;
 - (void) _statusBarHeightDidChange:(id)a ;
 - (void) _hostWillEnterForeground:(id)a ;
 - (void) _hostDidEnterBackground:(id)a ;
 - (void) _applicationDidFinishSuspendSnapshot:(id)a ;
 - (void) _appearanceInvocationsDidChange:(id)a ;
 - (void) _snapshotAdjustedMediaTiming:(id)a ;
 - (void) _updateTintColor;
 - (void) _terminateUnconditionallyThen:(@?)a ;
 - ({?=[8I]}) serviceAuditToken;
 - (id) _addAutoAllowedNotifications:(id)a ;
 - (long long) __getPreferredInterfaceOrientation;
 - (id) _hostDeferralProperties;
 - (id) _clientDeferralProperties;
 - (id) textEffectsWindowForServiceScreen;
 - (void) _restoreTextEffectsRemoteView;
 - (void) _snapshotAndRemoveTextEffectsRemoteView;
 - (void) _setDeferred:(BOOL)a forDisplayUUID:(id)b ;
 - (void) _applicationWillDeactivate:(id)a ;
 - (void) _applicationDidAddDeactivationReason:(id)a ;
 - (void) _addPreFencedCommitAction:(@?)a ;
 - (BOOL) _shouldDeferEventsForFocusOnScreen:(id)a ;
 - (id) serviceBundleIdentifier;
 - (int) serviceProcessIdentifier;
 - (void) _updateTouchGrabbingView;
 - (id) allowedNotifications;
 - (void) setAllowedNotifications:(id)a ;
 - (void) _setIsUpdatingSize:(BOOL)a ;
 - (id) _appearanceSource;
 - (void) __presentActionSheetFromYCoordinate:(double)a withTitle:(id)b buttonTitles:(id)c cancelButtonIndex:(long long)d destructiveButtonIndex:(long long)e style:(long long)f ;
 - (void) __dismissActionSheetWithClickedButtonIndex:(long long)a animated:(BOOL)b ;
 - (void) __viewServiceDidPromoteFirstResponder;
 - (void) __viewServiceDidRegisterScrollToTopView;
 - (void) __viewServiceDidUnregisterScrollToTopView;
 - (void) __setSupportedInterfaceOrientations:(id)a ;
 - (void) __viewServiceDidUpdateTintColor:(id)a duration:(double)b ;
 - (void) __showServiceForText:(id)a type:(long long)b fromRectValue:(id)c replyHandler:(@?)d ;
 - (void) __dismissTextServiceSessionAnimated:(BOOL)a ;
 - (void) __setViewServiceIsDisplayingPopover:(BOOL)a ;
 - (void) __viewServicePopoverDidChangeContentSize:({CGSize=dd})a animated:(BOOL)b fenceSendRight:(id)c withReplyHandler:(@?)d ;
 - (void) __viewServicePopoverDidSetUseToolbarShine:(BOOL)a ;
 - (void) __viewServicePreferredContentSizeDidChange:({CGSize=dd})a fenceSendRight:(id)b ;
 - (void) __viewServiceInstrinsicContentSizeDidChange:({CGSize=dd})a fenceSendRight:(id)b ;
 - (void) __viewServiceDidUpdatePreferredStatusBarStyle:(long long)a hidden:(BOOL)b ;
 - (void) __sendNotificationName:(id)a userInfo:(id)b ;
 - (void) setInheritsSecurity:(BOOL)a ;
 - (void) _initializeAccessibilityPortInformation;
 - (void) saveStateForSession:(id)a anchor:(id)b ;
 - (void) restoreStateForSession:(id)a anchor:(id)b ;
 - (void) setServiceViewShouldShareTouchesWithHost:(BOOL)a ;
 - (id) _cancelTouchesForCurrentEventInHostedContent;
 - (id) _touchDeliveryPolicyAssertion;
 - (BOOL) inheritsSecurity;


@end
