
@protocol NSURLSessionDelegate, NSURLSessionTaskDelegate, NSURLSessionDataDelegate, NSURLSessionDownloadDelegate, NSSecureCoding, NSCopying;
@interface AFURLSessionManager : NSObject <NSURLSessionDelegate, NSURLSessionTaskDelegate, NSURLSessionDataDelegate, NSURLSessionDownloadDelegate, NSSecureCoding, NSCopying> {

    BOOL _attemptsToRecreateUploadTasksForBackgroundSessions;
    NSURLSession* _session;
    NSOperationQueue* _operationQueue;
    <AFURLResponseSerialization>* _responseSerializer;
    AFSecurityPolicy* _securityPolicy;
    AFNetworkReachabilityManager* _reachabilityManager;
    NSObject<OS_dispatch_queue>* _completionQueue;
    NSObject<OS_dispatch_group>* _completionGroup;
    NSURLSessionConfiguration* _sessionConfiguration;
    NSMutableDictionary* _mutableTaskDelegatesKeyedByTaskIdentifier;
    NSLock* _lock;
    @? _sessionDidBecomeInvalid;
    @? _sessionDidReceiveAuthenticationChallenge;
    @? _didFinishEventsForBackgroundURLSession;
    @? _taskWillPerformHTTPRedirection;
    @? _taskDidReceiveAuthenticationChallenge;
    @? _taskNeedNewBodyStream;
    @? _taskDidSendBodyData;
    @? _taskDidComplete;
    @? _dataTaskDidReceiveResponse;
    @? _dataTaskDidBecomeDownloadTask;
    @? _dataTaskDidReceiveData;
    @? _dataTaskWillCacheResponse;
    @? _downloadTaskDidFinishDownloading;
    @? _downloadTaskDidWriteData;
    @? _downloadTaskDidResume;
}
@property (nonatomic, retain, readwrite) NSURLSession* session;
@property (nonatomic, retain, readwrite) NSOperationQueue* operationQueue;
@property (nonatomic, retain, readwrite) NSNumber* responseSerializer;
@property (nonatomic, retain, readwrite) AFSecurityPolicy* securityPolicy;
@property (nonatomic, retain, readwrite) AFNetworkReachabilityManager* reachabilityManager;
@property (nonatomic, assign, readonly) NSArray* tasks;
@property (nonatomic, assign, readonly) NSArray* dataTasks;
@property (nonatomic, assign, readonly) NSArray* uploadTasks;
@property (nonatomic, assign, readonly) NSArray* downloadTasks;
@property (nonatomic, retain, readwrite) NSNumber* completionQueue;
@property (nonatomic, retain, readwrite) NSNumber* completionGroup;
@property (nonatomic, assign, readwrite) NSNumber* attemptsToRecreateUploadTasksForBackgroundSessions;
@property (nonatomic, retain, readwrite) NSURLSessionConfiguration* sessionConfiguration;
@property (nonatomic, retain, readwrite) NSMutableDictionary* mutableTaskDelegatesKeyedByTaskIdentifier;
@property (nonatomic, copy, readonly) NSString* taskDescriptionForSessionTasks;
@property (nonatomic, retain, readwrite) NSLock* lock;
@property (nonatomic, copy, readwrite) NSNumber* sessionDidBecomeInvalid;
@property (nonatomic, copy, readwrite) NSNumber* sessionDidReceiveAuthenticationChallenge;
@property (nonatomic, copy, readwrite) NSNumber* didFinishEventsForBackgroundURLSession;
@property (nonatomic, copy, readwrite) NSNumber* taskWillPerformHTTPRedirection;
@property (nonatomic, copy, readwrite) NSNumber* taskDidReceiveAuthenticationChallenge;
@property (nonatomic, copy, readwrite) NSNumber* taskNeedNewBodyStream;
@property (nonatomic, copy, readwrite) NSNumber* taskDidSendBodyData;
@property (nonatomic, copy, readwrite) NSNumber* taskDidComplete;
@property (nonatomic, copy, readwrite) NSNumber* dataTaskDidReceiveResponse;
@property (nonatomic, copy, readwrite) NSNumber* dataTaskDidBecomeDownloadTask;
@property (nonatomic, copy, readwrite) NSNumber* dataTaskDidReceiveData;
@property (nonatomic, copy, readwrite) NSNumber* dataTaskWillCacheResponse;
@property (nonatomic, copy, readwrite) NSNumber* downloadTaskDidFinishDownloading;
@property (nonatomic, copy, readwrite) NSNumber* downloadTaskDidWriteData;
@property (nonatomic, copy, readwrite) NSNumber* downloadTaskDidResume;
 + (BOOL) supportsSecureCoding;

 - (void) setResponseSerializer:(id)a;
 - (void) setSecurityPolicy:(id)a;
 - (void) setReachabilityManager:(id)a;
 - (id) completionQueue;
 - (id) responseSerializer;
 - (id) securityPolicy;
 - (void) setCompletionQueue:(id)a;
 - (id) completionGroup;
 - (void) setCompletionGroup:(id)a;
 - (id) reachabilityManager;
 - (id) initWithSessionConfiguration:(id)a;
 - (id) uploadTaskWithStreamedRequest:(id)aprogress:(^@)bcompletionHandler:(@?)c;
 - (@?) downloadTaskDidFinishDownloading;
 - (void) setDownloadTaskDidFinishDownloading:(@?)a;
 - (void) setSessionConfiguration:(id)a;
 - (id) sessionConfiguration;
 - (void) setMutableTaskDelegatesKeyedByTaskIdentifier:(id)a;
 - (void) setLock:(id)a;
 - (void) addDelegateForDataTask:(id)acompletionHandler:(@?)b;
 - (void) addDelegateForUploadTask:(id)aprogress:(^@)bcompletionHandler:(@?)c;
 - (void) addDelegateForDownloadTask:(id)aprogress:(^@)bdestination:(@?)ccompletionHandler:(@?)d;
 - (void) taskDidResume:(id)a;
 - (void) taskDidSuspend:(id)a;
 - (id) taskDescriptionForSessionTasks;
 - (id) mutableTaskDelegatesKeyedByTaskIdentifier;
 - (void) setDelegate:(id)aforTask:(id)b;
 - (id) dataTasks;
 - (id) uploadTasks;
 - (id) downloadTasks;
 - (id) tasks;
 - (id) tasksForKeyPath:(id)a;
 - (BOOL) attemptsToRecreateUploadTasksForBackgroundSessions;
 - (id) delegateForTask:(id)a;
 - (void) setSessionDidBecomeInvalid:(@?)a;
 - (void) setSessionDidReceiveAuthenticationChallenge:(@?)a;
 - (void) setDidFinishEventsForBackgroundURLSession:(@?)a;
 - (void) setTaskNeedNewBodyStream:(@?)a;
 - (void) setTaskWillPerformHTTPRedirection:(@?)a;
 - (void) setTaskDidReceiveAuthenticationChallenge:(@?)a;
 - (void) setTaskDidSendBodyData:(@?)a;
 - (void) setTaskDidComplete:(@?)a;
 - (void) setDataTaskDidReceiveResponse:(@?)a;
 - (void) setDataTaskDidBecomeDownloadTask:(@?)a;
 - (void) setDataTaskDidReceiveData:(@?)a;
 - (void) setDataTaskWillCacheResponse:(@?)a;
 - (void) setDownloadTaskDidWriteData:(@?)a;
 - (void) setDownloadTaskDidResume:(@?)a;
 - (@?) taskWillPerformHTTPRedirection;
 - (@?) dataTaskDidReceiveResponse;
 - (@?) dataTaskWillCacheResponse;
 - (@?) didFinishEventsForBackgroundURLSession;
 - (@?) sessionDidBecomeInvalid;
 - (void) removeAllDelegates;
 - (@?) sessionDidReceiveAuthenticationChallenge;
 - (@?) taskDidReceiveAuthenticationChallenge;
 - (@?) taskNeedNewBodyStream;
 - (@?) taskDidSendBodyData;
 - (void) removeDelegateForTask:(id)a;
 - (@?) taskDidComplete;
 - (@?) dataTaskDidBecomeDownloadTask;
 - (@?) dataTaskDidReceiveData;
 - (@?) downloadTaskDidWriteData;
 - (@?) downloadTaskDidResume;
 - (void) invalidateSessionCancelingTasks:(BOOL)a;
 - (id) uploadTaskWithRequest:(id)afromFile:(id)bprogress:(^@)ccompletionHandler:(@?)d;
 - (id) uploadTaskWithRequest:(id)afromData:(id)bprogress:(^@)ccompletionHandler:(@?)d;
 - (id) downloadTaskWithRequest:(id)aprogress:(^@)bdestination:(@?)ccompletionHandler:(@?)d;
 - (id) downloadTaskWithResumeData:(id)aprogress:(^@)bdestination:(@?)ccompletionHandler:(@?)d;
 - (id) uploadProgressForTask:(id)a;
 - (id) downloadProgressForTask:(id)a;
 - (void) setSessionDidBecomeInvalidBlock:(@?)a;
 - (void) setSessionDidReceiveAuthenticationChallengeBlock:(@?)a;
 - (void) setDidFinishEventsForBackgroundURLSessionBlock:(@?)a;
 - (void) setTaskNeedNewBodyStreamBlock:(@?)a;
 - (void) setTaskWillPerformHTTPRedirectionBlock:(@?)a;
 - (void) setTaskDidReceiveAuthenticationChallengeBlock:(@?)a;
 - (void) setTaskDidSendBodyDataBlock:(@?)a;
 - (void) setTaskDidCompleteBlock:(@?)a;
 - (void) setDataTaskDidReceiveResponseBlock:(@?)a;
 - (void) setDataTaskDidBecomeDownloadTaskBlock:(@?)a;
 - (void) setDataTaskDidReceiveDataBlock:(@?)a;
 - (void) setDataTaskWillCacheResponseBlock:(@?)a;
 - (void) setDownloadTaskDidFinishDownloadingBlock:(@?)a;
 - (void) setDownloadTaskDidWriteDataBlock:(@?)a;
 - (void) setDownloadTaskDidResumeBlock:(@?)a;
 - (void) setAttemptsToRecreateUploadTasksForBackgroundSessions:(BOOL)a;
 - (id) operationQueue;
 - (id) copyWithZone:(^{_NSZone=})a;
 - (id) description;
 - (void) .cxx_destruct;
 - (void) dealloc;
 - (id) lock;
 - (BOOL) respondsToSelector:(SEL)a;
 - (void) setOperationQueue:(id)a;
 - (id) init;
 - (void) encodeWithCoder:(id)a;
 - (id) initWithCoder:(id)a;
 - (id) session;
 - (void) setSession:(id)a;
 - (void) URLSession:(id)adidBecomeInvalidWithError:(id)b;
 - (id) dataTaskWithRequest:(id)acompletionHandler:(@?)b;
 - (void) URLSession:(id)adidReceiveChallenge:(id)bcompletionHandler:(@?)c;
 - (void) URLSession:(id)atask:(id)bwillPerformHTTPRedirection:(id)cnewRequest:(id)dcompletionHandler:(@?)e;
 - (void) URLSession:(id)atask:(id)bdidReceiveChallenge:(id)ccompletionHandler:(@?)d;
 - (void) URLSession:(id)atask:(id)bneedNewBodyStream:(@?)c;
 - (void) URLSession:(id)atask:(id)bdidSendBodyData:(long long)ctotalBytesSent:(long long)dtotalBytesExpectedToSend:(long long)e;
 - (void) URLSession:(id)atask:(id)bdidCompleteWithError:(id)c;
 - (void) URLSession:(id)adataTask:(id)bdidReceiveResponse:(id)ccompletionHandler:(@?)d;
 - (void) URLSession:(id)adataTask:(id)bdidBecomeDownloadTask:(id)c;
 - (void) URLSession:(id)adataTask:(id)bdidReceiveData:(id)c;
 - (void) URLSession:(id)adataTask:(id)bwillCacheResponse:(id)ccompletionHandler:(@?)d;
 - (void) URLSession:(id)adownloadTask:(id)bdidFinishDownloadingToURL:(id)c;
 - (void) URLSession:(id)adownloadTask:(id)bdidWriteData:(long long)ctotalBytesWritten:(long long)dtotalBytesExpectedToWrite:(long long)e;
 - (void) URLSession:(id)adownloadTask:(id)bdidResumeAtOffset:(long long)cexpectedTotalBytes:(long long)d;
 - (void) URLSessionDidFinishEventsForBackgroundURLSession:(id)a;


@end
