
@protocol BSWatchdogProviding;
@interface BSTransaction : NSObject <BSWatchdogProviding> {

    BSTransaction* _parentTransaction;
    NSMutableSet* _lifeAssertions;
    BOOL _failed;
    BOOL _interrupted;
    unsigned long long _state;
    NSString* _failureReason;
    NSDate* _startTime;
    NSMutableDictionary* _milestonesToHandlers;
    NSMutableArray* _childTransactions;
    NSMutableSet* _milestones;
    NSHashTable* _observers;
    NSMutableArray* _auditHistory;
    BOOL _buildAuditHistory;
    <BSLogging>* _debugLogger;
    @? _completionBlock;
}
@property (nonatomic, retain, readonly) NSNumber* queue;
@property (nonatomic, retain, readonly) NSSet* milestones;
@property (nonatomic, retain, readonly) NSArray* childTransactions;
@property (nonatomic, assign, readonly, getter=isInterrupted) NSNumber* interrupted;
@property (nonatomic, assign, readonly, getter=isInterruptable) NSNumber* interruptable;
@property (nonatomic, assign, readonly, getter=isRunning) NSNumber* running;
@property (nonatomic, assign, readonly, getter=isComplete) NSNumber* complete;
@property (nonatomic, assign, readonly, getter=isFailed) NSNumber* failed;
@property (nonatomic, copy, readwrite) NSNumber* completionBlock;
@property (nonatomic, retain, readwrite) BSTransaction* parentTransaction;
@property (nonatomic, assign, readonly) NSNumber* state;

 - (@?) completionBlock;
 - (void) setCompletionBlock:(@?)a ;
 - (void) interrupt;
 - (id) description;
 - (void) dealloc;
 - (id) debugDescription;
 - (id) init;
 - (unsigned long long) state;
 - (void) removeObserver:(id)a ;
 - (void) addObserver:(id)a ;
 - (id) queue;
 - (void) _setState:(unsigned long long)a ;
 - (void) _debugLogWithFormat:(id)a ;
 - (void) _setParentTransaction:(id)a assertIfNecessary:(BOOL)b ;
 - (void) _enumerateChildTransactionsWithBlock:(@?)a ;
 - (BOOL) isComplete;
 - (void) _addChildTransaction:(id)a ;
 - (void) _removeChildTransaction:(id)a ;
 - (void) _willBegin;
 - (void) _begin;
 - (unsigned long long) _state;
 - (void) begin;
 - (void) _didBegin;
 - (void) _preventTransactionCompletionForReason:(id)a andExecuteBlock:(@?)b ;
 - (BOOL) _isRootTransaction;
 - (BOOL) _canBeInterrupted;
 - (BOOL) isInterruptable;
 - (void) interruptWithReason:(id)a ;
 - (void) _interruptWithReason:(id)a force:(BOOL)b ;
 - (void) _addAuditHistory:(id)a ;
 - (void) _failNow;
 - (void) addMilestones:(id)a ;
 - (id) _stringForMilestones:(id)a ;
 - (BOOL) isRunning;
 - (BOOL) removeMilestones:(id)a ;
 - (BOOL) _removeMilestones:(id)a ignoringAuditHistory:(BOOL)b ;
 - (void) evaluateMilestone:(id)a withEvaluator:(@?)b ;
 - (BOOL) isWaitingForMilestone:(id)a ;
 - (void) _didSatisfyMilestone:(id)a ;
 - (id) _descriptionForDebugging:(BOOL)a indentLevel:(unsigned long long)b ;
 - (void) _checkAndReportIfCompleted;
 - (void) _noteTransactionStateInAuditHistory;
 - (void) setDebugLogger:(id)a ;
 - (id) _parentTransaction;
 - (void) _childTransactionDidComplete:(id)a ;
 - (id) _customizedDescriptionProperties;
 - (id) _stringForState:(unsigned long long)a ;
 - (void) _willAddChildTransaction:(id)a ;
 - (void) _setParentTransaction:(id)a ;
 - (void) _didAddChildTransaction:(id)a ;
 - (void) _willRemoveChildTransaction:(id)a ;
 - (void) _didRemoveChildTransaction:(id)a ;
 - (void) _willFailWithReason:(id)a ;
 - (void) failWithReason:(id)a ;
 - (void) _noteCompleted;
 - (void) _didComplete;
 - (BOOL) isFailed;
 - (void) _notifyObserversOfCompletion;
 - (void) _noteChildTransactionCompleted:(id)a ;
 - (void) _willInterruptWithReason:(id)a ;
 - (void) _didInterruptWithReason:(id)a ;
 - (void) removeAllMilestones;
 - (BOOL) _areChildTransactionsComplete;
 - (BOOL) _shouldComplete;
 - (void) _enumerateObserversWithBlock:(@?)a ;
 - (void) _addLifeAssertion:(id)a ;
 - (void) _removeLifeAssertion:(id)a ;
 - (id) _loggingProem;
 - (double) watchdogTimeout;
 - (BOOL) shouldWatchdog:(^@)a ;
 - (id) milestones;
 - (id) childTransactions;
 - (void) addChildTransaction:(id)a ;
 - (BOOL) hasChildTransactionsOfClass:(Class)a ;
 - (id) childTransactionsOfClass:(Class)a ;
 - (void) removeAllChildTransactionsOfClass:(Class)a ;
 - (void) removeChildTransaction:(id)a ;
 - (void) removeAllChildTransactions;
 - (BOOL) isInterrupted;
 - (void) addMilestone:(id)a ;
 - (BOOL) removeMilestone:(id)a ;
 - (void) satisfyMilestone:(id)a ;
 - (void) listenForSatisfiedMilestone:(id)a withBlock:(@?)b ;
 - (void) _evaluateCompletion;
 - (void) setBuildAuditHistory:(BOOL)a ;
 - (BOOL) buildAuditHistory;
 - (id) auditHistory;
 - (id) debugLogger;
 - (BOOL) _isRootTransactionComplete;
 - (BOOL) _isParentTransactionComplete;
 - (void) _forceInterrupt;
 - (id) _stringForInterruptReason:(id)a ;
 - (id) parentTransaction;
 - (void) setParentTransaction:(id)a ;


@end
