
@protocol NSCopying, CAPropertyInfo, NSCoding, CAMediaTiming;
@interface CAEmitterCell : NSObject <NSCopying, CAPropertyInfo, NSCoding, CAMediaTiming> {

    [2^v] _attr;
    ^v _state;
    unsigned int _flags;
}
@property (atomic, copy, readwrite) NSString* particleType;
@property (atomic, assign, readwrite) NSNumber* orientationLatitude;
@property (atomic, assign, readwrite) NSNumber* orientationLongitude;
@property (atomic, assign, readwrite) NSNumber* orientationRange;
@property (atomic, assign, readwrite) NSNumber* rotation;
@property (atomic, assign, readwrite) NSNumber* rotationRange;
@property (atomic, assign, readwrite) NSNumber* mass;
@property (atomic, assign, readwrite) NSNumber* massRange;
@property (atomic, assign, readwrite) NSNumber* contentsScale;
@property (atomic, copy, readwrite) NSString* contentsFrameMode;
@property (atomic, assign, readwrite) NSNumber* contentsFrameCount;
@property (atomic, assign, readwrite) NSNumber* contentsFramesPerRow;
@property (atomic, assign, readwrite) NSNumber* contentsFramesPerSecond;
@property (atomic, copy, readwrite) NSArray* emitterBehaviors;
@property (atomic, copy, readwrite) NSString* name;
@property (atomic, assign, readwrite, isEnabled) NSNumber* enabled;
@property (atomic, assign, readwrite) NSNumber* birthRate;
@property (atomic, assign, readwrite) NSNumber* lifetime;
@property (atomic, assign, readwrite) NSNumber* lifetimeRange;
@property (atomic, assign, readwrite) NSNumber* emissionLatitude;
@property (atomic, assign, readwrite) NSNumber* emissionLongitude;
@property (atomic, assign, readwrite) NSNumber* emissionRange;
@property (atomic, assign, readwrite) NSNumber* velocity;
@property (atomic, assign, readwrite) NSNumber* velocityRange;
@property (atomic, assign, readwrite) NSNumber* xAcceleration;
@property (atomic, assign, readwrite) NSNumber* yAcceleration;
@property (atomic, assign, readwrite) NSNumber* zAcceleration;
@property (atomic, assign, readwrite) NSNumber* scale;
@property (atomic, assign, readwrite) NSNumber* scaleRange;
@property (atomic, assign, readwrite) NSNumber* scaleSpeed;
@property (atomic, assign, readwrite) NSNumber* spin;
@property (atomic, assign, readwrite) NSNumber* spinRange;
@property (atomic, assign, readwrite) NSNumber* color;
@property (atomic, assign, readwrite) NSNumber* redRange;
@property (atomic, assign, readwrite) NSNumber* greenRange;
@property (atomic, assign, readwrite) NSNumber* blueRange;
@property (atomic, assign, readwrite) NSNumber* alphaRange;
@property (atomic, assign, readwrite) NSNumber* redSpeed;
@property (atomic, assign, readwrite) NSNumber* greenSpeed;
@property (atomic, assign, readwrite) NSNumber* blueSpeed;
@property (atomic, assign, readwrite) NSNumber* alphaSpeed;
@property (atomic, retain, readwrite) NSNumber* contents;
@property (atomic, assign, readwrite) NSNumber* contentsRect;
@property (atomic, copy, readwrite) NSString* minificationFilter;
@property (atomic, copy, readwrite) NSString* magnificationFilter;
@property (atomic, assign, readwrite) NSNumber* minificationFilterBias;
@property (atomic, copy, readwrite) NSArray* emitterCells;
@property (atomic, copy, readwrite) NSDictionary* style;
@property (atomic, assign, readwrite) NSNumber* beginTime;
@property (atomic, assign, readwrite) NSNumber* duration;
@property (atomic, assign, readwrite) NSNumber* speed;
@property (atomic, assign, readwrite) NSNumber* timeOffset;
@property (atomic, assign, readwrite) NSNumber* repeatCount;
@property (atomic, assign, readwrite) NSNumber* repeatDuration;
@property (atomic, assign, readwrite) NSNumber* autoreverses;
@property (atomic, copy, readwrite) NSString* fillMode;
 + (BOOL) automaticallyNotifiesObserversForKey:(id)a;
 + (id) properties;
 + (id) defaultValueForKey:(id)a;
 + (BOOL) CA_automaticallyNotifiesObservers:(Class)a;
 + (void) CAMLParserStartElement:(id)a;
 + (id) emitterCell;

 - (id) valueForUndefinedKey:(id)a;
 - (void) setValue:(id)aforUndefinedKey:(id)b;
 - (void) setValue:(id)aforKeyPath:(id)b;
 - (double) scale;
 - (double) duration;
 - (id) copyWithZone:(^{_NSZone=})a;
 - (void) dealloc;
 - (void) setValue:(id)aforKey:(id)b;
 - (id) name;
 - (void) didChangeValueForKey:(id)a;
 - (void) setRotation:(double)a;
 - (id) debugDescription;
 - (void) encodeWithCoder:(id)a;
 - (id) initWithCoder:(id)a;
 - (id) valueForKey:(id)a;
 - (id) valueForKeyPath:(id)a;
 - (void) setName:(id)a;
 - (void) setContentsScale:(double)a;
 - (id) style;
 - (void) setMass:(float)a;
 - (void) setColor:(^{CGColor=})a;
 - (void) CAMLParser:(id)asetValue:(id)bforKey:(id)c;
 - (void) encodeWithCAMLWriter:(id)a;
 - (id) CAMLTypeForKey:(id)a;
 - (void) setBeginTime:(double)a;
 - (void) setDuration:(double)a;
 - (double) beginTime;
 - (^{Object=^^?{Atomic={?=i}}}) CA_copyRenderValue;
 - (void) CA_prepareRenderValue;
 - (double) timeOffset;
 - (float) repeatCount;
 - (double) repeatDuration;
 - (void) setRepeatDuration:(double)a;
 - (BOOL) autoreverses;
 - (id) fillMode;
 - (void) setFillMode:(id)a;
 - (BOOL) shouldArchiveValueForKey:(id)a;
 - (id) contents;
 - (id) particleType;
 - (float) birthRate;
 - (float) lifetime;
 - (float) lifetimeRange;
 - (double) emissionLatitude;
 - (double) emissionLongitude;
 - (double) emissionRange;
 - (double) velocityRange;
 - (double) xAcceleration;
 - (double) yAcceleration;
 - (double) zAcceleration;
 - (float) massRange;
 - (double) scaleRange;
 - (double) scaleSpeed;
 - (double) orientationLatitude;
 - (double) orientationLongitude;
 - (double) orientationRange;
 - (double) rotation;
 - (double) rotationRange;
 - (double) spin;
 - (double) spinRange;
 - (^{CGColor=}) color;
 - (float) redRange;
 - (float) greenRange;
 - (float) blueRange;
 - (float) alphaRange;
 - (float) redSpeed;
 - (float) greenSpeed;
 - (float) blueSpeed;
 - (float) alphaSpeed;
 - (float) minificationFilterBias;
 - (double) contentsScale;
 - (unsigned int) contentsFrameCount;
 - (unsigned int) contentsFramesPerRow;
 - (float) contentsFramesPerSecond;
 - (id) contentsFrameMode;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) contentsRect;
 - (id) magnificationFilter;
 - (id) minificationFilter;
 - (id) emitterCells;
 - (id) emitterBehaviors;
 - (void) setBirthRate:(float)a;
 - (void) setLifetime:(float)a;
 - (void) setLifetimeRange:(float)a;
 - (void) setEmissionLatitude:(double)a;
 - (void) setEmissionLongitude:(double)a;
 - (void) setEmissionRange:(double)a;
 - (void) setVelocityRange:(double)a;
 - (void) setXAcceleration:(double)a;
 - (void) setYAcceleration:(double)a;
 - (void) setZAcceleration:(double)a;
 - (void) setScale:(double)a;
 - (void) setScaleRange:(double)a;
 - (void) setScaleSpeed:(double)a;
 - (void) setOrientationLatitude:(double)a;
 - (void) setOrientationLongitude:(double)a;
 - (void) setOrientationRange:(double)a;
 - (void) setRotationRange:(double)a;
 - (void) setSpin:(double)a;
 - (void) setSpinRange:(double)a;
 - (void) setRedRange:(float)a;
 - (void) setRedSpeed:(float)a;
 - (void) setGreenRange:(float)a;
 - (void) setGreenSpeed:(float)a;
 - (void) setBlueRange:(float)a;
 - (void) setBlueSpeed:(float)a;
 - (void) setAlphaRange:(float)a;
 - (void) setAlphaSpeed:(float)a;
 - (void) setContents:(id)a;
 - (void) setMinificationFilterBias:(float)a;
 - (void) setEmitterCells:(id)a;
 - (void) setParticleType:(id)a;
 - (void) setMassRange:(float)a;
 - (void) setEmitterBehaviors:(id)a;
 - (void) setContentsFrameMode:(id)a;
 - (void) setContentsFrameCount:(unsigned int)a;
 - (void) setContentsFramesPerRow:(unsigned int)a;
 - (void) setContentsFramesPerSecond:(float)a;
 - (void) setStyle:(id)a;
 - (void) setTimeOffset:(double)a;
 - (void) setRepeatCount:(float)a;
 - (void) setAutoreverses:(BOOL)a;
 - (void) setContentsRect:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - (void) setMinificationFilter:(id)a;
 - (void) setMagnificationFilter:(id)a;
 - (double) velocity;
 - (void) setVelocity:(double)a;
 - (float) mass;
 - (BOOL) isEnabled;
 - (void) setEnabled:(BOOL)a;
 - (float) speed;
 - (void) setSpeed:(float)a;


@end
