
@protocol NSCopying;
@interface CIBurstFaceStat : NSObject <NSCopying> {

    BOOL leftEyeOpen;
    BOOL rightEyeOpen;
    BOOL smiling;
    BOOL foundByFaceCore;
    BOOL hasLeftEye;
    BOOL hasRightEye;
    BOOL leftEyePleasant;
    BOOL rightEyePleasant;
    BOOL mouthPleasant;
    BOOL hasRollAngle;
    BOOL hasYawAngle;
    BOOL smallFace;
    BOOL _isSyncedWithImage;
    float normalizedSigma;
    int faceId;
    int hwFaceId;
    int framesSinceLast;
    float focusScore;
    float normalizedFocusScore;
    float faceScore;
    float leftEyeBlinkScore;
    float rightEyeBlinkScore;
    float smileScore;
    int FCRLeftEyeFeaturesOffset;
    int FCRRightEyeFeaturesOffset;
    int FCRSmileFeaturesOffset;
    int FCRBlinkFeaturesSize;
    int FCRSmileFeaturesSize;
    float faceHOGTime;
    float faceCropTime;
    float faceScoreTime;
    float normalizedSmileScore;
    float rollAngle;
    float yawAngle;
    NSMutableArray* FCRSmileAndBlinkFeatures;
    NSMutableArray* faceHOG;
    double timestamp;
    {CGRect="origin"{CGPoint="x"d"y"d}"size"{CGSize="width"d"height"d}} faceRect;
    {CGRect="origin"{CGPoint="x"d"y"d}"size"{CGSize="width"d"height"d}} normalizedFaceRect;
    {CGRect="origin"{CGPoint="x"d"y"d}"size"{CGSize="width"d"height"d}} leftEyeRect;
    {CGRect="origin"{CGPoint="x"d"y"d}"size"{CGSize="width"d"height"d}} rightEyeRect;
    {CGRect="origin"{CGPoint="x"d"y"d}"size"{CGSize="width"d"height"d}} _hwFaceRect;
}
@property (atomic, assign, readwrite) NSNumber* leftEyeOpen;
@property (atomic, assign, readwrite) NSNumber* rightEyeOpen;
@property (atomic, assign, readwrite) NSNumber* smiling;
@property (atomic, assign, readwrite) NSNumber* leftEyeBlinkScore;
@property (atomic, assign, readwrite) NSNumber* rightEyeBlinkScore;
@property (atomic, assign, readwrite) NSNumber* smileScore;
@property (atomic, assign, readwrite) NSNumber* hasLeftEye;
@property (atomic, assign, readwrite) NSNumber* hasRightEye;
@property (atomic, assign, readwrite) NSNumber* foundByFaceCore;
@property (atomic, assign, readwrite) NSNumber* faceRect;
@property (atomic, assign, readwrite) NSNumber* normalizedFaceRect;
@property (atomic, assign, readwrite) NSNumber* faceId;
@property (atomic, assign, readwrite) NSNumber* framesSinceLast;
@property (atomic, assign, readwrite) NSNumber* focusScore;
@property (atomic, assign, readwrite) NSNumber* faceScore;
@property (atomic, assign, readwrite) NSNumber* leftEyeRect;
@property (atomic, assign, readwrite) NSNumber* rightEyeRect;
@property (atomic, assign, readwrite) NSNumber* FCRLeftEyeFeaturesOffset;
@property (atomic, assign, readwrite) NSNumber* FCRRightEyeFeaturesOffset;
@property (atomic, assign, readwrite) NSNumber* FCRSmileFeaturesOffset;
@property (atomic, assign, readwrite) NSNumber* FCRBlinkFeaturesSize;
@property (atomic, assign, readwrite) NSNumber* FCRSmileFeaturesSize;
@property (atomic, assign, readwrite) NSMutableArray* FCRSmileAndBlinkFeatures;
@property (atomic, assign, readwrite) NSNumber* faceHOGTime;
@property (atomic, assign, readwrite) NSNumber* faceCropTime;
@property (atomic, assign, readwrite) NSNumber* faceScoreTime;
@property (atomic, assign, readwrite) NSMutableArray* faceHOG;
@property (atomic, assign, readwrite) NSNumber* normalizedSmileScore;
@property (atomic, assign, readwrite) NSNumber* leftEyePleasant;
@property (atomic, assign, readwrite) NSNumber* rightEyePleasant;
@property (atomic, assign, readwrite) NSNumber* mouthPleasant;
@property (atomic, assign, readwrite) NSNumber* hwFaceId;
@property (atomic, assign, readwrite) NSNumber* hwFaceRect;
@property (atomic, assign, readwrite) NSNumber* normalizedFocusScore;
@property (atomic, assign, readwrite) NSNumber* normalizedSigma;
@property (atomic, assign, readwrite) NSNumber* hasRollAngle;
@property (atomic, assign, readwrite) NSNumber* hasYawAngle;
@property (atomic, assign, readwrite) NSNumber* rollAngle;
@property (atomic, assign, readwrite) NSNumber* yawAngle;
@property (atomic, assign, readwrite) NSNumber* timestamp;
@property (atomic, assign, readwrite) NSNumber* isSyncedWithImage;
@property (atomic, assign, readwrite) NSNumber* smallFace;

 - (id) copyWithZone:(^{_NSZone=})a ;
 - (void) dealloc;
 - (int) faceId;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) normalizedFaceRect;
 - (BOOL) hasRollAngle;
 - (float) rollAngle;
 - (BOOL) hasYawAngle;
 - (float) yawAngle;
 - (BOOL) hasLeftEye;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) leftEyeRect;
 - (float) leftEyeBlinkScore;
 - (BOOL) hasRightEye;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) rightEyeRect;
 - (float) rightEyeBlinkScore;
 - (float) smileScore;
 - (float) focusScore;
 - (BOOL) leftEyeOpen;
 - (BOOL) rightEyeOpen;
 - (BOOL) smiling;
 - (BOOL) smallFace;
 - (int) FCRLeftEyeFeaturesOffset;
 - (int) FCRRightEyeFeaturesOffset;
 - (int) FCRSmileFeaturesOffset;
 - (int) FCRBlinkFeaturesSize;
 - (int) FCRSmileFeaturesSize;
 - (void) setSmiling:(BOOL)a ;
 - (float) normalizedFocusScore;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) faceRect;
 - (void) setFaceId:(int)a ;
 - (void) setFaceRect:({CGRect={CGPoint=dd}{CGSize=dd}})a ;
 - (int) framesSinceLast;
 - (void) setFramesSinceLast:(int)a ;
 - (void) setHwFaceId:(int)a ;
 - (int) hwFaceId;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) hwFaceRect;
 - (void) setHwFaceRect:({CGRect={CGPoint=dd}{CGSize=dd}})a ;
 - (BOOL) isSyncedWithImage;
 - (void) setNormalizedFaceRect:({CGRect={CGPoint=dd}{CGSize=dd}})a ;
 - (void) setFoundByFaceCore:(BOOL)a ;
 - (void) setHasLeftEye:(BOOL)a ;
 - (void) setHasRightEye:(BOOL)a ;
 - (void) setLeftEyeOpen:(BOOL)a ;
 - (void) setRightEyeOpen:(BOOL)a ;
 - (void) setLeftEyeBlinkScore:(float)a ;
 - (void) setRightEyeBlinkScore:(float)a ;
 - (void) setSmileScore:(float)a ;
 - (void) setSmallFace:(BOOL)a ;
 - (void) setLeftEyeRect:({CGRect={CGPoint=dd}{CGSize=dd}})a ;
 - (void) setRightEyeRect:({CGRect={CGPoint=dd}{CGSize=dd}})a ;
 - (BOOL) foundByFaceCore;
 - (void) setFocusScore:(float)a ;
 - (void) setNormalizedFocusScore:(float)a ;
 - (void) setNormalizedSigma:(float)a ;
 - (void) setHasRollAngle:(BOOL)a ;
 - (void) setRollAngle:(float)a ;
 - (void) setHasYawAngle:(BOOL)a ;
 - (void) setYawAngle:(float)a ;
 - (void) setIsSyncedWithImage:(BOOL)a ;
 - (float) normalizedSigma;
 - (float) faceScore;
 - (float) normalizedSmileScore;
 - (BOOL) leftEyePleasant;
 - (BOOL) rightEyePleasant;
 - (BOOL) mouthPleasant;
 - (id) faceHOG;
 - (id) FCRSmileAndBlinkFeatures;
 - (id) initWithFaceStat:(id)a ;
 - (void) setFaceScore:(float)a ;
 - (void) setFCRLeftEyeFeaturesOffset:(int)a ;
 - (void) setFCRRightEyeFeaturesOffset:(int)a ;
 - (void) setFCRSmileFeaturesOffset:(int)a ;
 - (void) setFCRBlinkFeaturesSize:(int)a ;
 - (void) setFCRSmileFeaturesSize:(int)a ;
 - (void) setFCRSmileAndBlinkFeatures:(id)a ;
 - (float) faceHOGTime;
 - (void) setFaceHOGTime:(float)a ;
 - (float) faceCropTime;
 - (void) setFaceCropTime:(float)a ;
 - (float) faceScoreTime;
 - (void) setFaceScoreTime:(float)a ;
 - (void) setFaceHOG:(id)a ;
 - (void) setNormalizedSmileScore:(float)a ;
 - (void) setLeftEyePleasant:(BOOL)a ;
 - (void) setRightEyePleasant:(BOOL)a ;
 - (void) setMouthPleasant:(BOOL)a ;
 - (double) timestamp;
 - (void) setTimestamp:(double)a ;


@end
