
@interface CSIGenerator : NSObject {

    {CGSize="width"d"height"d} _size;
    NSString _name;
    NSString _utiType;
    NSMutableArray _slices;
    NSMutableArray _bitmaps;
    NSMutableArray _metrics;
    BOOL _isFPOHint;
    BOOL _isExcludedFromFilter;
    BOOL _isVectorBased;
    long long _templateRenderingMode;
    BOOL _allowsMultiPassEncoding;
    short _colorSpaceID;
    short _layout;
    unsigned int _scaleFactor;
    CUIPSDGradient _gradient;
    NSData _rawData;
    CUIShapeEffectPreset _effectPreset;
    int _blendMode;
    double _opacity;
    NSDate _modtime;
    unsigned int _pixelFormat;
    int _exifOrientation;
    unsigned long long _rowbytes;
}
@property (nonatomic, copy, readwrite) NSString* name;
@property (nonatomic, copy, readwrite) NSString* utiType;
@property (nonatomic, assign, readwrite) NSNumber* isRenditionFPO;
@property (nonatomic, assign, readwrite) NSNumber* isVectorBased;
@property (nonatomic, assign, readwrite) NSNumber* templateRenderingMode;
@property (nonatomic, assign, readwrite, getter=isExcludedFromContrastFilter) NSNumber* excludedFromContrastFilter;
@property (nonatomic, assign, readwrite) NSNumber* colorSpaceID;
@property (nonatomic, assign, readwrite) NSNumber* scaleFactor;
@property (nonatomic, assign, readwrite) NSNumber* pixelFormat;
@property (nonatomic, assign, readwrite) NSNumber* allowsMultiPassEncoding;
@property (nonatomic, assign, readwrite) NSNumber* exifOrientation;
@property (nonatomic, retain, readwrite) CUIPSDGradient* gradient;
@property (nonatomic, retain, readwrite) CUIShapeEffectPreset* effectPreset;
@property (nonatomic, assign, readwrite) NSNumber* blendMode;
@property (nonatomic, assign, readwrite) NSNumber* opacity;
@property (nonatomic, copy, readwrite) NSDate* modtime;
 + (void) initialize;
 + (void) setFileCompression:(int)a;
 + (int) fileCompression;

 - (void) dealloc;
 - (id) name;
 - (unsigned int) scaleFactor;
 - (void) setTemplateRenderingMode:(long long)a;
 - (void) setExifOrientation:(int)a;
 - (void) setName:(id)a;
 - (void) setEffectPreset:(id)a;
 - (long long) templateRenderingMode;
 - (id) modtime;
 - (int) blendMode;
 - (BOOL) allowsMultiPassEncoding;
 - (void) _addNodes:(id)atoNodeList:(^{_csigradientdatanode=Ifdddddddd})b;
 - (void) formatCSIHeader:(^{_csiheader=IIIIIIIb4b28{_csimetadata=ISS[128c]}I{_csibitmaplist=I[0I]}})a;
 - (void) writeHeader:(^{_csiheader=IIIIIIIb4b28{_csimetadata=ISS[128c]}I{_csibitmaplist=I[0I]}})atoData:(id)b;
 - (unsigned long long) writeResourcesToData:(id)a;
 - (unsigned long long) writeGradientToData:(id)a;
 - (unsigned long long) writeRawDataToData:(id)a;
 - (unsigned long long) writeBitmap:(id)atoData:(id)bcompress:(BOOL)c;
 - (id) initWithCanvasSize:({CGSize=dd})asliceCount:(unsigned int)blayout:(short)c;
 - (id) initWithShapeEffectPreset:(id)aforScaleFactor:(unsigned int)b;
 - (id) initWithRawData:(id)apixelFormat:(unsigned int)blayout:(short)c;
 - (void) addBitmap:(id)a;
 - (void) addSliceRect:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - (void) addMetrics:({?={CGSize=dd}{CGSize=dd}{CGSize=dd}})a;
 - (id) CSIRepresentationWithCompression:(BOOL)a;
 - (id) utiType;
 - (void) setUtiType:(id)a;
 - (BOOL) isRenditionFPO;
 - (void) setIsRenditionFPO:(BOOL)a;
 - (BOOL) isVectorBased;
 - (void) setIsVectorBased:(BOOL)a;
 - (BOOL) isExcludedFromContrastFilter;
 - (void) setExcludedFromContrastFilter:(BOOL)a;
 - (short) colorSpaceID;
 - (void) setColorSpaceID:(short)a;
 - (id) gradient;
 - (void) setGradient:(id)a;
 - (void) setScaleFactor:(unsigned int)a;
 - (unsigned int) pixelFormat;
 - (void) setPixelFormat:(unsigned int)a;
 - (id) effectPreset;
 - (void) setBlendMode:(int)a;
 - (void) setModtime:(id)a;
 - (int) exifOrientation;
 - (void) setAllowsMultiPassEncoding:(BOOL)a;
 - (double) opacity;
 - (void) setOpacity:(double)a;


@end
