
@protocol NSCopying, NSMutableCopying, NSSecureCoding, NSFastEnumeration;
@interface NSArray : NSObject <NSCopying, NSMutableCopying, NSSecureCoding, NSFastEnumeration> {

}
@property (atomic, assign, readonly) NSNumber* count;
 + (id) arrayWithContentsOfFile:(id)a;
 + (id) arrayWithContentsOfURL:(id)a;
 + (id) newWithContentsOf:(id)aimmutable:(BOOL)b;
 + (BOOL) supportsSecureCoding;
 + (id) allocWithZone:(^{_NSZone=})a;
 + (id) arrayWithObjects:(r^@)acount:(unsigned long long)b;
 + (id) array;
 + (id) newArrayWithObjects:(r^@)acount:(unsigned long long)b;
 + (id) arrayWithArray:(id)arange:({_NSRange=QQ})bcopyItems:(BOOL)c;
 + (id) arrayWithArray:(id)arange:({_NSRange=QQ})b;
 + (id) arrayWithArray:(id)acopyItems:(BOOL)b;
 + (id) arrayWithOrderedSet:(id)arange:({_NSRange=QQ})bcopyItems:(BOOL)c;
 + (id) arrayWithOrderedSet:(id)arange:({_NSRange=QQ})b;
 + (id) arrayWithOrderedSet:(id)acopyItems:(BOOL)b;
 + (id) arrayWithOrderedSet:(id)a;
 + (id) arrayWithSet:(id)acopyItems:(BOOL)b;
 + (id) arrayWithSet:(id)a;
 + (id) arrayWithArray:(id)a;
 + (id) arrayWithObject:(id)a;
 + (id) arrayWithObjects:(id)a;

 - (BOOL) MPIsEmpty;
 - (id) subarraysOfSize:(unsigned long long)a ;
 - (id) pickableRouteWithUID:(id)a ;
 - (id) cutFirstObject;
 - (id) _ui_onlyObject;
 - (id) _ui_firstObject;
 - (id) _filteredArrayOfObjectsPassingTest:(@?)a ;
 - (id) _initWithObjectsFromArray:(id)a range:({_NSRange=QQ})b ;
 - (void) _makeObjectsPerformSelector:(SEL)a object:(id)b range:({_NSRange=QQ})c ;
 - (id) _nextToLastObject;
 - ({CGSize=dd}) _legacy_drawComponentsJoinedByString:(id)a atPoint:(^{CGPoint=dd})b forWidth:(double)c withFont:(id)d lineBreakMode:(long long)e ;
 - (id) _webkit_stringAtIndex:(unsigned long long)a ;
 - (id) _webkit_numberAtIndex:(unsigned long long)a ;
 - (id) _web_lowercaseStrings;
 - (void) encodeWithCAMLWriter:(id)a ;
 - (id) CAMLType;
 - (id) CA_addValue:(id)a multipliedBy:(int)b ;
 - (id) CA_interpolateValue:(id)a byFraction:(float)b ;
 - (id) CA_interpolateValues:(id)a interpolator:(id)b ;
 - (id) _arrayByFilteringCandidatesForNonExtendedView;
 - (id) bs_firstObjectPassingTest:(@?)a ;
 - (id) bs_firstObjectOfClass:(Class)a ;
 - (void) bs_each:(@?)a ;
 - (id) bs_map:(@?)a ;
 - (id) bs_filter:(@?)a ;
 - (id) bs_flatten;
 - (BOOL) bs_containsObjectPassingTest:(@?)a ;
 - (id) bs_firstObjectOfClassNamed:(id)a ;
 - (id) bs_mapNoNulls:(@?)a ;
 - (id) bs_reverse;
 - (id) bs_first:(unsigned long long)a ;
 - (id) replacementObjectForPortCoder:(id)a ;
 - (id) filteredArrayUsingPredicate:(id)a ;
 - (id) sortedArrayUsingDescriptors:(id)a ;
 - (id) pathsMatchingExtensions:(id)a ;
 - (id) stringsByAppendingPathComponent:(id)a ;
 - (void) removeObserver:(id)a forKeyPath:(id)b ;
 - (void) addObserver:(id)a forKeyPath:(id)b options:(unsigned long long)c context:(^v)d ;
 - (void) addObserver:(id)a toObjectsAtIndexes:(id)b forKeyPath:(id)c options:(unsigned long long)d context:(^v)e ;
 - (void) removeObserver:(id)a fromObjectsAtIndexes:(id)b forKeyPath:(id)c context:(^v)d ;
 - (void) removeObserver:(id)a fromObjectsAtIndexes:(id)b forKeyPath:(id)c ;
 - (void) removeObserver:(id)a forKeyPath:(id)b context:(^v)c ;
 - (id) _valueForKeyPath:(id)a ofObjectAtIndex:(unsigned long long)b ;
 - (id) _mutableArrayValueForKeyPath:(id)a ofObjectAtIndex:(unsigned long long)b ;
 - (id) _mutableOrderedSetValueForKeyPath:(id)a ofObjectAtIndex:(unsigned long long)b ;
 - (id) _mutableSetValueForKeyPath:(id)a ofObjectAtIndex:(unsigned long long)b ;
 - (void) _setValue:(id)a forKeyPath:(id)b ofObjectAtIndex:(unsigned long long)c ;
 - (BOOL) _validateValue:(N^@)a forKeyPath:(id)b ofObjectAtIndex:(unsigned long long)c error:(o^@)d ;
 - (id) _sumForKeyPath:(id)a ;
 - (id) _unionOfArraysForKeyPath:(id)a ;
 - (id) _unionOfObjectsForKeyPath:(id)a ;
 - (id) _avgForKeyPath:(id)a ;
 - (id) _countForKeyPath:(id)a ;
 - (id) _maxForKeyPath:(id)a ;
 - (id) _minForKeyPath:(id)a ;
 - (id) _unionOfSetsForKeyPath:(id)a ;
 - (id) _distinctUnionOfArraysForKeyPath:(id)a ;
 - (id) _distinctUnionOfObjectsForKeyPath:(id)a ;
 - (id) _distinctUnionOfSetsForKeyPath:(id)a ;
 - (void) setValue:(id)a forKey:(id)b ;
 - (id) valueForKey:(id)a ;
 - (id) valueForKeyPath:(id)a ;
 - (BOOL) writeToFile:(id)a atomically:(BOOL)b ;
 - (Class) classForCoder;
 - (id) sortedArrayUsingFunction:(^?)a context:(^v)b hint:(id)c ;
 - (id) _stringToWrite;
 - (BOOL) writeToURL:(id)a atomically:(BOOL)b ;
 - (id) initWithContentsOfFile:(id)a ;
 - (id) sortedArrayHint;
 - (id) sortedArrayUsingSelector:(SEL)a hint:(id)b ;
 - (id) debugDescription;
 - (void) encodeWithCoder:(id)a ;
 - (id) initWithCoder:(id)a ;
 - (id) initWithContentsOfURL:(id)a ;
 - (id) initWithObjects:(id)a ;
 - (id) sortedArrayUsingSelector:(SEL)a ;
 - (id) initWithSet:(id)a ;
 - (id) arrayByAddingObject:(id)a ;
 - (id) subarrayWithRange:({_NSRange=QQ})a ;
 - (BOOL) containsObjectIdenticalTo:(id)a ;
 - (id) sortedArrayUsingComparator:(@?)a ;
 - (unsigned long long) indexOfObject:(id)a inSortedRange:({_NSRange=QQ})b options:(unsigned long long)c usingComparator:(@?)d ;
 - (id) copyWithZone:(^{_NSZone=})a ;
 - (id) mutableCopyWithZone:(^{_NSZone=})a ;
 - (id) description;
 - (unsigned long long) count;
 - (id) objectAtIndex:(unsigned long long)a ;
 - (void) getObjects:(^@)a range:({_NSRange=QQ})b ;
 - (unsigned long long) countForObject:(id)a ;
 - (BOOL) containsObject:(id)a ;
 - (unsigned long long) hash;
 - (BOOL) isEqual:(id)a ;
 - (id) descriptionWithLocale:(id)a ;
 - (unsigned long long) _cfTypeID;
 - (void) getObjects:(^@)a ;
 - (unsigned long long) countByEnumeratingWithState:(^{?=Q^@^Q[5Q]})a objects:(^@)b count:(unsigned long long)c ;
 - (id) initWithObjects:(r^@)a count:(unsigned long long)b ;
 - (void) enumerateObjectsWithOptions:(unsigned long long)a usingBlock:(@?)b ;
 - (unsigned long long) indexOfObjectIdenticalTo:(id)a ;
 - (id) initWithArray:(id)a copyItems:(BOOL)b ;
 - (BOOL) _hasObjects;
 - (BOOL) _hasStrongReferences;
 - (id) initWithObject:(id)a ;
 - (id) initWithArray:(id)a ;
 - (id) indexesOfObjectsAtIndexes:(id)a options:(unsigned long long)b passingTest:(@?)c ;
 - (id) indexesOfObjectsWithOptions:(unsigned long long)a passingTest:(@?)b ;
 - (unsigned long long) indexOfObjectWithOptions:(unsigned long long)a passingTest:(@?)b ;
 - (BOOL) isNSArray__;
 - (BOOL) isEqualToArray:(id)a ;
 - (unsigned long long) indexOfObjectAtIndexes:(id)a options:(unsigned long long)b passingTest:(@?)c ;
 - (id) objectWithOptions:(unsigned long long)a passingTest:(@?)b ;
 - (id) objectsAtIndexes:(id)a ;
 - (id) objectsWithOptions:(unsigned long long)a passingTest:(@?)b ;
 - (id) sortedArrayFromRange:({_NSRange=QQ})a options:(unsigned long long)b usingComparator:(@?)c ;
 - (id) sortedArrayWithOptions:(unsigned long long)a usingComparator:(@?)b ;
 - (id) descriptionWithLocale:(id)a indent:(unsigned long long)b ;
 - (id) initWithArray:(id)a range:({_NSRange=QQ})b copyItems:(BOOL)c ;
 - (id) initWithOrderedSet:(id)a range:({_NSRange=QQ})b copyItems:(BOOL)c ;
 - (id) initWithSet:(id)a copyItems:(BOOL)b ;
 - (id) allObjects;
 - (id) componentsJoinedByString:(id)a ;
 - (BOOL) containsObject:(id)a inRange:({_NSRange=QQ})b ;
 - (BOOL) containsObjectIdenticalTo:(id)a inRange:({_NSRange=QQ})b ;
 - (unsigned long long) countForObject:(id)a inRange:({_NSRange=QQ})b ;
 - (void) enumerateObjectsAtIndexes:(id)a options:(unsigned long long)b usingBlock:(@?)c ;
 - (id) firstObjectCommonWithArray:(id)a ;
 - (unsigned long long) indexOfObject:(id)a inRange:({_NSRange=QQ})b ;
 - (unsigned long long) indexOfObject:(id)a ;
 - (unsigned long long) indexOfObjectIdenticalTo:(id)a inRange:({_NSRange=QQ})b ;
 - (id) indexesOfObject:(id)a inRange:({_NSRange=QQ})b ;
 - (id) indexesOfObject:(id)a ;
 - (id) indexesOfObjectIdenticalTo:(id)a inRange:({_NSRange=QQ})b ;
 - (id) indexesOfObjectIdenticalTo:(id)a ;
 - (id) lastObject;
 - (id) objectAtIndexes:(id)a options:(unsigned long long)b passingTest:(@?)c ;
 - (id) objectPassingTest:(@?)a ;
 - (id) objectsAtIndexes:(id)a options:(unsigned long long)b passingTest:(@?)c ;
 - (id) objectEnumerator;
 - (id) reversedArray;
 - (id) initWithArray:(id)a range:({_NSRange=QQ})b ;
 - (id) initWithOrderedSet:(id)a range:({_NSRange=QQ})b ;
 - (id) initWithOrderedSet:(id)a copyItems:(BOOL)b ;
 - (id) initWithOrderedSet:(id)a ;
 - (id) arrayByExcludingToObjectsInArray:(id)a ;
 - (id) objectsPassingTest:(@?)a ;
 - (id) arrayByExcludingObjectsInArray:(id)a ;
 - (id) arrayByAddingObjectsFromArray:(id)a ;
 - (void) encodeWithCoder:(id)a ;
 - (id) initWithCoder:(id)a ;
 - (void) enumerateObjectsUsingBlock:(@?)a ;
 - (id) firstObject;
 - (id) objectAtIndexedSubscript:(unsigned long long)a ;
 - (void) makeObjectsPerformSelector:(SEL)a ;
 - (id) arrayByApplyingSelector:(SEL)a ;
 - (id) reverseObjectEnumerator;
 - (id) indexesOfObjectsPassingTest:(@?)a ;
 - (id) sortedArrayUsingFunction:(^?)a context:(^v)b ;
 - (void) makeObjectsPerformSelector:(SEL)a withObject:(id)b ;
 - (unsigned long long) indexOfObjectPassingTest:(@?)a ;


@end
