
@protocol NSCopying, NSMutableCopying, NSSecureCoding;
@interface NSAttributedString : NSObject <NSCopying, NSMutableCopying, NSSecureCoding> {

}
@property (atomic, copy, readonly) NSString* string;
 + (id) attributedStringWithAttachment:(id)a;
 + (id) _documentTypeForFileType:(id)a;
 + (BOOL) supportsSecureCoding;
 + (void) _setAttributedDictionaryClass:(Class)a;
 + (id) allocWithZone:(^{_NSZone=})a;

 - (id) MP_attributedStringByAddingAttributes:(id)a toOccurrencesOfSubstring:(id)b options:(unsigned long long)c ;
 - (id) _ui_secureStringWithPointSize:(double)a ;
 - (long long) _ui_resolvedTextAlignment;
 - (id) _ui_attributedStringWithOriginalFontAttributes;
 - (id) _ui_fontsInRange:({_NSRange=QQ})a usingDefaultFont:(id)b ;
 - (id) _ui_synthesizeAttributedSubstringFromRange:({_NSRange=QQ})a usingDefaultAttributes:(id)b ;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) boundingRectWithSize:({CGSize=dd})a options:(long long)b context:(id)c ;
 - (id) _ui_attributedSubstringFromRange:({_NSRange=QQ})a withTrackingAdjustment:(double)b ;
 - (id) _ui_attributedSubstringFromRange:({_NSRange=QQ})a scaledByScaleFactor:(double)b ;
 - (void) drawWithRect:({CGRect={CGPoint=dd}{CGSize=dd}})a options:(long long)b context:(id)c ;
 - (void) drawWithRect:({CGRect={CGPoint=dd}{CGSize=dd}})a options:(long long)b ;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) boundingRectWithSize:({CGSize=dd})a options:(long long)b ;
 - ({CGSize=dd}) size;
 - (void) drawInRect:({CGRect={CGPoint=dd}{CGSize=dd}})a ;
 - (void) drawAtPoint:({CGPoint=dd})a ;
 - (id) dataFromRange:({_NSRange=QQ})a documentAttributes:(id)b error:(^@)c ;
 - (id) initWithData:(id)a options:(id)b documentAttributes:(^@)c error:(^@)d ;
 - ({_NSRange=QQ}) rangeOfTextTable:(id)a atIndex:(unsigned long long)b ;
 - ({_NSRange=QQ}) rangeOfTextBlock:(id)a atIndex:(unsigned long long)b ;
 - ({_NSRange=QQ}) _rangeOfTextTableRow:(id)a atIndex:(unsigned long long)b completeRow:(^B)c ;
 - ({_NSRange=QQ}) _rangeOfTextTableRow:(id)a atIndex:(unsigned long long)b ;
 - (BOOL) _isStringDrawingTextStorage;
 - (unsigned long long) _lineBreakBeforeIndex:(unsigned long long)a withinRange:({_NSRange=QQ})b usesAlternativeBreaker:(BOOL)c ;
 - (unsigned long long) lineBreakByHyphenatingBeforeIndex:(unsigned long long)a withinRange:({_NSRange=QQ})b ;
 - ({_NSRange=QQ}) doubleClickAtIndex:(unsigned long long)a inRange:({_NSRange=QQ})b ;
 - (id) stringByStrippingAttachmentCharactersAndConvertingWritingDirectionToBidiControlCharactersFromRange:({_NSRange=QQ})a ;
 - (id) fileWrapperFromRange:({_NSRange=QQ})a documentAttributes:(id)b error:(^@)c ;
 - (id) _initWithRTFSelector:(SEL)a argument:(id)b documentAttributes:(^@)c ;
 - (id) initWithURL:(id)a options:(id)b documentAttributes:(^@)c error:(^@)d ;
 - (id) initWithHTML:(id)a options:(id)b documentAttributes:(^@)c ;
 - (id) defaultLanguage;
 - ({_NSRange=QQ}) doubleClickAtIndex:(unsigned long long)a ;
 - (unsigned long long) lineBreakBeforeIndex:(unsigned long long)a withinRange:({_NSRange=QQ})b ;
 - (unsigned long long) nextWordFromIndex:(unsigned long long)a forward:(BOOL)b ;
 - (id) RTFDFileWrapperFromRange:({_NSRange=QQ})a documentAttributes:(id)b ;
 - (id) docFormatFromRange:({_NSRange=QQ})a documentAttributes:(id)b ;
 - (void) _readDocumentFragment:(id)a fromRange:({_NSRange=QQ})b documentAttributes:(id)c subresources:(^@)d ;
 - (id) initWithRTFDFileWrapper:(id)a documentAttributes:(^@)b ;
 - (id) initWithDocFormat:(id)a documentAttributes:(^@)b ;
 - (id) initWithFileURL:(id)a options:(id)b documentAttributes:(^@)c error:(^@)d ;
 - (id) _initWithURLFunnel:(id)a options:(id)b documentAttributes:(^@)c ;
 - (id) initWithURL:(id)a documentAttributes:(^@)b ;
 - (id) initWithPath:(id)a documentAttributes:(^@)b ;
 - (id) initWithHTML:(id)a documentAttributes:(^@)b ;
 - (id) initWithHTML:(id)a baseURL:(id)b documentAttributes:(^@)c ;
 - (id) _initWithDOMRange:(id)a ;
 - (id) fontAttributesInRange:({_NSRange=QQ})a ;
 - (id) rulerAttributesInRange:({_NSRange=QQ})a ;
 - (BOOL) _atStartOfTextTable:(id)a atIndex:(unsigned long long)b ;
 - (BOOL) _atEndOfTextTable:(id)a atIndex:(unsigned long long)b ;
 - (BOOL) _atStartOfTextTableRow:(id)a atIndex:(unsigned long long)b ;
 - (BOOL) _atEndOfTextTableRow:(id)a atIndex:(unsigned long long)b ;
 - ({_NSRange=QQ}) rangeOfTextList:(id)a atIndex:(unsigned long long)b ;
 - (long long) itemNumberInTextList:(id)a atIndex:(unsigned long long)b ;
 - (id) _documentFromRange:({_NSRange=QQ})a document:(id)b documentAttributes:(id)c subresources:(^@)d ;
 - (BOOL) containsAttachments;
 - (id) initWithRTFD:(id)a documentAttributes:(^@)b ;
 - (id) initWithRTF:(id)a documentAttributes:(^@)b ;
 - (id) RTFFromRange:({_NSRange=QQ})a documentAttributes:(id)b ;
 - (id) RTFDFromRange:({_NSRange=QQ})a documentAttributes:(id)b ;
 - (id) _UIKBStringWideAttributeValueForKey:(id)a ;
 - (Class) classForCoder;
 - (id) replacementObjectForPortCoder:(id)a ;
 - (id) attributedSubstringFromRange:({_NSRange=QQ})a ;
 - (BOOL) isEqualToAttributedString:(id)a ;
 - (id) attributedSubstringFromRange:({_NSRange=QQ})a replacingCharactersInRanges:(r^{_NSRange=QQ})b numberOfRanges:(long long)c withString:(id)d ;
 - (id) attributedStringByWeaklyAddingAttributes:(id)a ;
 - (id) copyWithZone:(^{_NSZone=})a ;
 - (id) mutableCopyWithZone:(^{_NSZone=})a ;
 - (id) description;
 - (id) _createAttributedSubstringWithRange:({_NSRange=QQ})a ;
 - (id) string;
 - (id) attributesAtIndex:(unsigned long long)a effectiveRange:(^{_NSRange=QQ})b ;
 - (id) attribute:(id)a atIndex:(unsigned long long)b effectiveRange:(^{_NSRange=QQ})c ;
 - (id) attributesAtIndex:(unsigned long long)a longestEffectiveRange:(^{_NSRange=QQ})b inRange:({_NSRange=QQ})c ;
 - (id) attribute:(id)a atIndex:(unsigned long long)b longestEffectiveRange:(^{_NSRange=QQ})c inRange:({_NSRange=QQ})d ;
 - (unsigned long long) hash;
 - (BOOL) isEqual:(id)a ;
 - (unsigned long long) _cfTypeID;
 - (unsigned long long) length;
 - (void) encodeWithCoder:(id)a ;
 - (id) initWithCoder:(id)a ;
 - (void) enumerateAttribute:(id)a inRange:({_NSRange=QQ})b options:(unsigned long long)c usingBlock:(@?)d ;
 - (void) enumerateAttributesInRange:({_NSRange=QQ})a options:(unsigned long long)b usingBlock:(@?)c ;


@end
