
@protocol NSCopying, NSSecureCoding;
@interface NSCalendar : NSObject <NSCopying, NSSecureCoding> {

}
@property (atomic, copy, readonly) NSString* calendarIdentifier;
@property (atomic, copy, readwrite) NSLocale* locale;
@property (atomic, copy, readwrite) NSTimeZone* timeZone;
@property (atomic, assign, readwrite) NSNumber* firstWeekday;
@property (atomic, assign, readwrite) NSNumber* minimumDaysInFirstWeek;
@property (atomic, copy, readonly) NSArray* eraSymbols;
@property (atomic, copy, readonly) NSArray* longEraSymbols;
@property (atomic, copy, readonly) NSArray* monthSymbols;
@property (atomic, copy, readonly) NSArray* shortMonthSymbols;
@property (atomic, copy, readonly) NSArray* veryShortMonthSymbols;
@property (atomic, copy, readonly) NSArray* standaloneMonthSymbols;
@property (atomic, copy, readonly) NSArray* shortStandaloneMonthSymbols;
@property (atomic, copy, readonly) NSArray* veryShortStandaloneMonthSymbols;
@property (atomic, copy, readonly) NSArray* weekdaySymbols;
@property (atomic, copy, readonly) NSArray* shortWeekdaySymbols;
@property (atomic, copy, readonly) NSArray* veryShortWeekdaySymbols;
@property (atomic, copy, readonly) NSArray* standaloneWeekdaySymbols;
@property (atomic, copy, readonly) NSArray* shortStandaloneWeekdaySymbols;
@property (atomic, copy, readonly) NSArray* veryShortStandaloneWeekdaySymbols;
@property (atomic, copy, readonly) NSArray* quarterSymbols;
@property (atomic, copy, readonly) NSArray* shortQuarterSymbols;
@property (atomic, copy, readonly) NSArray* standaloneQuarterSymbols;
@property (atomic, copy, readonly) NSArray* shortStandaloneQuarterSymbols;
@property (atomic, copy, readonly) NSString* AMSymbol;
@property (atomic, copy, readonly) NSString* PMSymbol;
 + (id) autoupdatingCurrentCalendar;
 + (BOOL) supportsSecureCoding;
 + (void) initialize;
 + (id) allocWithZone:(^{_NSZone=})a;
 + (id) currentCalendar;
 + (id) calendarWithIdentifier:(id)a;

 - (id) _dateOnlyComponentsForDate:(id)a;
 - (id) _timeOnlyComponentsForDate:(id)a;
 - (BOOL) date:(id)aisSameDayAsDate:(id)b;
 - (BOOL) date:(id)aisSameYearAsDate:(id)b;
 - (Class) classForCoder;
 - (void) encodeWithCoder:(id)a;
 - (id) initWithCoder:(id)a;
 - (id) copyWithZone:(^{_NSZone=})a;
 - (unsigned long long) hash;
 - (BOOL) isEqual:(id)a;
 - (unsigned long long) _cfTypeID;
 - (id) initWithCalendarIdentifier:(id)a;
 - (void) setTimeZone:(id)a;
 - (id) dateFromComponents:(id)a;
 - (BOOL) isDateInToday:(id)a;
 - (BOOL) isDateInTomorrow:(id)a;
 - (BOOL) isDateInYesterday:(id)a;
 - (BOOL) isDate:(id)ainSameDayAsDate:(id)b;
 - (long long) compareDate:(id)atoDate:(id)btoUnitGranularity:(unsigned long long)c;
 - (id) calendarIdentifier;
 - (void) setLocale:(id)a;
 - (id) locale;
 - (id) timeZone;
 - (void) setFirstWeekday:(unsigned long long)a;
 - (unsigned long long) firstWeekday;
 - (void) setMinimumDaysInFirstWeek:(unsigned long long)a;
 - (unsigned long long) minimumDaysInFirstWeek;
 - ({_NSRange=QQ}) minimumRangeOfUnit:(unsigned long long)a;
 - ({_NSRange=QQ}) maximumRangeOfUnit:(unsigned long long)a;
 - ({_NSRange=QQ}) rangeOfUnit:(unsigned long long)ainUnit:(unsigned long long)bforDate:(id)c;
 - (unsigned long long) ordinalityOfUnit:(unsigned long long)ainUnit:(unsigned long long)bforDate:(id)c;
 - (BOOL) rangeOfUnit:(unsigned long long)astartDate:(^@)binterval:(^d)cforDate:(id)d;
 - (id) components:(unsigned long long)afromDate:(id)b;
 - (id) dateByAddingComponents:(id)atoDate:(id)boptions:(unsigned long long)c;
 - (id) components:(unsigned long long)afromDate:(id)btoDate:(id)coptions:(unsigned long long)d;
 - (BOOL) nextWeekendStartDate:(o^@)ainterval:(o^d)boptions:(unsigned long long)cafterDate:(id)d;
 - (BOOL) isDateInWeekend:(id)a;
 - (void) enumerateDatesStartingAfterDate:(id)amatchingComponents:(id)boptions:(unsigned long long)cusingBlock:(@?)d;
 - (id) gregorianStartDate;
 - (void) setGregorianStartDate:(id)a;
 - (id) nextDateAfterDate:(id)amatchingComponents:(id)boptions:(unsigned long long)c;
 - (id) dateBySettingUnit:(unsigned long long)avalue:(long long)bofDate:(id)coptions:(unsigned long long)d;
 - (long long) component:(unsigned long long)afromDate:(id)b;
 - (id) dateBySettingHour:(long long)aminute:(long long)bsecond:(long long)cofDate:(id)doptions:(unsigned long long)e;
 - (void) getEra:(o^q)ayear:(o^q)bmonth:(o^q)cday:(o^q)dfromDate:(id)e;
 - (void) getEra:(o^q)ayearForWeekOfYear:(o^q)bweekOfYear:(o^q)cweekday:(o^q)dfromDate:(id)e;
 - (void) getHour:(o^q)aminute:(o^q)bsecond:(o^q)cnanosecond:(o^q)dfromDate:(id)e;
 - (id) dateWithEra:(long long)ayear:(long long)bmonth:(long long)cday:(long long)dhour:(long long)eminute:(long long)fsecond:(long long)gnanosecond:(long long)h;
 - (id) dateWithEra:(long long)ayearForWeekOfYear:(long long)bweekOfYear:(long long)cweekday:(long long)dhour:(long long)eminute:(long long)fsecond:(long long)gnanosecond:(long long)h;
 - (id) startOfDayForDate:(id)a;
 - (id) componentsInTimeZone:(id)afromDate:(id)b;
 - (BOOL) isDate:(id)aequalToDate:(id)btoUnitGranularity:(unsigned long long)c;
 - (BOOL) rangeOfWeekendStartDate:(o^@)ainterval:(o^d)bcontainingDate:(id)c;
 - (id) components:(unsigned long long)afromDateComponents:(id)btoDateComponents:(id)coptions:(unsigned long long)d;
 - (id) dateByAddingUnit:(unsigned long long)avalue:(long long)btoDate:(id)coptions:(unsigned long long)d;
 - (id) nextDateAfterDate:(id)amatchingUnit:(unsigned long long)bvalue:(long long)coptions:(unsigned long long)d;
 - (id) nextDateAfterDate:(id)amatchingHour:(long long)bminute:(long long)csecond:(long long)doptions:(unsigned long long)e;
 - (id) dateBySettingUnit:(unsigned long long)avalue:(long long)btoDate:(id)coptions:(unsigned long long)d;
 - (id) dateBySettingHour:(long long)aminute:(long long)bsecond:(long long)ctoDate:(id)doptions:(unsigned long long)e;
 - (BOOL) date:(id)amatchesComponents:(id)b;
 - (id) _copyLocale;
 - (id) _copyTimeZone;
 - (void) _setGregorianStartDate:(id)a;
 - (id) _gregorianStartDate;
 - (id) eraSymbols;
 - (id) weekdaySymbols;
 - (id) shortWeekdaySymbols;
 - (id) longEraSymbols;
 - (id) veryShortMonthSymbols;
 - (id) veryShortStandaloneMonthSymbols;
 - (id) veryShortWeekdaySymbols;
 - (id) standaloneWeekdaySymbols;
 - (id) shortStandaloneWeekdaySymbols;
 - (id) veryShortStandaloneWeekdaySymbols;
 - (id) quarterSymbols;
 - (id) shortQuarterSymbols;
 - (id) standaloneQuarterSymbols;
 - (id) shortStandaloneQuarterSymbols;
 - ({?=qq}) _minimumRangeOfUnit:(unsigned long long)a;
 - ({?=qq}) _maximumRangeOfUnit:(unsigned long long)a;
 - ({?=qq}) _rangeOfUnit:(unsigned long long)ainUnit:(unsigned long long)bforAT:(double)c;
 - (long long) _ordinalityOfUnit:(unsigned long long)ainUnit:(unsigned long long)bforAT:(double)c;
 - (unsigned char) _rangeOfUnit:(unsigned long long)astartTime:(^d)binterval:(^d)cforAT:(double)d;
 - (unsigned char) _composeAbsoluteTime:(^d)a;
 - (unsigned char) _decomposeAbsoluteTime:(double)a;
 - (unsigned char) _addComponents:(^d)a;
 - (unsigned char) _diffComponents:(double)a;
 - (id) init;
 - (void) encodeWithCoder:(id)a;
 - (id) initWithCoder:(id)a;
 - (id) monthSymbols;
 - (id) shortMonthSymbols;
 - (id) standaloneMonthSymbols;
 - (id) shortStandaloneMonthSymbols;
 - (id) AMSymbol;
 - (id) PMSymbol;


@end
