
@interface NSConnection : NSObject {

    id receivePort;
    id sendPort;
    id delegate;
    int busy;
    int localProxyCount;
    int waitCount;
    id delayedRL;
    id statistics;
    unsigned char isDead;
    unsigned char isValid;
    unsigned char wantsInvalid;
    b1 authGen;
    b1 authCheck;
    b1 _reserved1;
    b1 _reserved2;
    b1 doRequest;
    b1 isQueueing;
    b1 isMulti;
    b1 invalidateRP;
    id ___1;
    id ___2;
    id runLoops;
    id requestModes;
    id rootObject;
    ^v registerInfo;
    id replMode;
    id classInfoImported;
    id releasedProxies;
    id reserved;
}
@property (atomic, copy, readonly) NSDictionary* statistics;
@property (atomic, assign, readwrite) NSNumber* requestTimeout;
@property (atomic, assign, readwrite) NSNumber* replyTimeout;
@property (atomic, retain, readwrite) NSNumber* rootObject;
@property (atomic, assign, readwrite) NSNumber* delegate;
@property (atomic, assign, readwrite) NSNumber* independentConversationQueueing;
@property (atomic, assign, readonly, isValid) NSNumber* valid;
@property (atomic, retain, readonly) NSDistantObject* rootProxy;
@property (atomic, copy, readonly) NSArray* requestModes;
@property (atomic, retain, readonly) NSPort* sendPort;
@property (atomic, retain, readonly) NSPort* receivePort;
@property (atomic, assign, readonly) NSNumber* multipleThreadsEnabled;
@property (atomic, copy, readonly) NSArray* remoteObjects;
@property (atomic, copy, readonly) NSArray* localObjects;
 + (id) lookUpConnectionWithReceivePort:(id)asendPort:(id)b;
 + (id) connectionWithReceivePort:(id)asendPort:(id)b;
 + (void) _portInvalidated:(id)a;
 + (id) connectionWithRegisteredName:(id)ahost:(id)busingNameServer:(id)c;
 + (id) serviceConnectionWithName:(id)arootObject:(id)busingNameServer:(id)c;
 + (id) allConnections;
 + (void) _enableLogging:(BOOL)a;
 + (id) connectionWithRegisteredName:(id)ahost:(id)b;
 + (id) rootProxyForConnectionWithRegisteredName:(id)ahost:(id)b;
 + (id) rootProxyForConnectionWithRegisteredName:(id)ahost:(id)busingNameServer:(id)c;
 + (id) serviceConnectionWithName:(id)arootObject:(id)b;
 + (id) defaultConnection;
 + (id) currentConversation;
 + (void) _toggleLogging;
 + (void) initialize;
 + (id) statistics;

 - (id) receivePort;
 - (id) sendPort;
 - (void) dispatchWithComponents:(id)a;
 - (void) handlePortMessage:(id)a;
 - (void) removeRunLoop:(id)a;
 - (void) returnResult:(id)aexception:(id)bsequence:(unsigned int)cimports:(id)d;
 - (id) initWithReceivePort:(id)asendPort:(id)b;
 - (id) rootProxy;
 - (BOOL) registerName:(id)awithNameServer:(id)b;
 - (void) setRootObject:(id)a;
 - (void) addRunLoop:(id)a;
 - (double) replyTimeout;
 - (double) requestTimeout;
 - (void) _setWhitelist:(id)a;
 - (void) sendReleasedProxies;
 - (id) keyedRootObject;
 - (id) rootObject;
 - (void) addPortsToRunLoop:(id)a;
 - (void) removePortsFromRunLoop:(id)a;
 - (void) _encodeProxyList:(id)aforCoder:(id)b;
 - (void) handleKeyedReleasedProxies:(id)a;
 - (void) handleUnkeyedReleasedProxies:(char*)alength:(unsigned long long)b;
 - (Class) _portCoderClass;
 - (void) _sendBeforeTime:(double)acoder:(id)bdoAuthenticationCheck:(BOOL)c;
 - (BOOL) _verifyComponents:(id)a;
 - (id) portCoderWithComponents:(id)a;
 - (void) handlePortCoder:(id)a;
 - (void) handleRequest:(id)asequence:(unsigned int)b;
 - (void) decodeReleasedProxies:(id)a;
 - (id) newConversation;
 - (BOOL) _shouldDispatch:(^@)ainvocation:(id)bsequence:(unsigned int)ccoder:(id)d;
 - (id) dispatchInvocation:(id)a;
 - (void) encodeReleasedProxies:(id)a;
 - (BOOL) hasRunLoop:(id)a;
 - (void) sendInvocation:(id)ainternal:(BOOL)b;
 - (void) _authenticateComponents:(id)a;
 - (BOOL) registerName:(id)a;
 - (void) setRequestTimeout:(double)a;
 - (void) setReplyTimeout:(double)a;
 - (BOOL) independentConversationQueueing;
 - (void) setIndependentConversationQueueing:(BOOL)a;
 - (void) addRequestMode:(id)a;
 - (void) removeRequestMode:(id)a;
 - (id) requestModes;
 - (id) replyMode;
 - (void) setReplyMode:(id)a;
 - (void) _incrementLocalProxyCount;
 - (void) _decrementLocalProxyCount;
 - (void) addClassNamed:(char*)aversion:(unsigned long long)b;
 - (unsigned long long) versionForClassNamed:(id)a;
 - (void) releaseWireID:(unsigned int)acount:(unsigned long long)b;
 - (id) remoteObjects;
 - (id) localObjects;
 - (Class) _portCoderClassWithComponents:(id)a;
 - (BOOL) sendWireCountForWireID:(unsigned int)aport:(id)b;
 - (void) sendInvocation:(id)a;
 - (void) _setUseKC:(BOOL)a;
 - (void) enableMultipleThreads;
 - (BOOL) multipleThreadsEnabled;
 - (void) runInNewThread;
 - (id) description;
 - (id) retain;
 - (Vv) release;
 - (void) dealloc;
 - (void) finalize;
 - (void) invalidate;
 - (BOOL) isValid;
 - (void) setDelegate:(id)a;
 - (id) init;
 - (void) run;
 - (id) delegate;
 - (id) statistics;


@end
