
@protocol NSCopying, NSMutableCopying, NSSecureCoding;
@interface NSData : NSObject <NSCopying, NSMutableCopying, NSSecureCoding> {

}
@property (atomic, assign, readonly) NSNumber* length;
@property (atomic, assign, readonly) NSNumber* bytes;
 + (id) mappedDataWithContentsOfTemporaryFile:(id)aerror:(^@)b;
 + (id) MCDataWithHexString:(id)a;
 + (id) MCDataWithCFData:(^{__CFData=})a;
 + (id) dataWithBytesNoCopy:(^v)alength:(unsigned long long)bfreeWhenDone:(BOOL)c;
 + (BOOL) supportsSecureCoding;
 + (id) dataWithContentsOfURL:(id)a;
 + (id) dataWithContentsOfMappedFile:(id)a;
 + (id) dataWithData:(id)a;
 + (id) allocWithZone:(^{_NSZone=})a;
 + (id) data;
 + (id) dataWithBytes:(r^v)alength:(unsigned long long)b;
 + (id) dataWithBytesNoCopy:(^v)alength:(unsigned long long)b;
 + (id) dataWithContentsOfFile:(id)a;
 + (id) dataWithContentsOfURL:(id)aoptions:(unsigned long long)berror:(^@)c;
 + (id) dataWithContentsOfFile:(id)aoptions:(unsigned long long)berror:(^@)c;

 - (id) decompressedGzipData;
 - (id) decompressedGzipDataUsingTemporaryFile;
 - (id) ml_stringValueForSQL;
 - (void) ml_bindToSQLiteStatement:(^{sqlite3_stmt=})a atPosition:(int)b ;
 - (id) MCHexString;
 - (id) MCBase64String;
 - (id) MCInitWithBase64String:(id)a ;
 - (id) MCSHA1Hash;
 - (id) _CUTDecompressData;
 - (id) _CUTStringFromBaseData;
 - (id) _CUTOptionallyDecompressData;
 - (id) _CUTCopyGzippedData;
 - (BOOL) _web_isCaseInsensitiveEqualToCString:(r*)a ;
 - (id) _webkit_parseRFC822HeaderFields;
 - (BOOL) _web_startsWithBlankLine;
 - (long long) _web_locationAfterFirstBlankLine;
 - (id) _webkit_guessedMIMETypeForXML;
 - (id) _webkit_guessedMIMEType;
 - (id) replacementObjectForPortCoder:(id)a ;
 - (id) _web_guessedMIMETypeForXML;
 - (id) _web_guessedMIMEType;
 - (id) _web_guessedMIMETypeForExtension:(id)a ;
 - (id) _web_parseRFC822HeaderFields;
 - (id) _replaceCString:(r*)a withCString:(r*)b ;
 - (BOOL) isNSData__;
 - (id) initWithBytesNoCopy:(^v)a length:(unsigned long long)b freeWhenDone:(BOOL)c ;
 - (id) subdataWithRange:({_NSRange=QQ})a ;
 - (BOOL) writeToFile:(id)a atomically:(BOOL)b ;
 - (Class) classForCoder;
 - (id) replacementObjectForCoder:(id)a ;
 - (BOOL) writeToURL:(id)a atomically:(BOOL)b ;
 - (id) initWithContentsOfFile:(id)a ;
 - (id) initWithBytes:(^v)a length:(unsigned long long)b copy:(BOOL)c deallocator:(@?)d ;
 - (id) initWithBytes:(r^v)a length:(unsigned long long)b ;
 - (BOOL) _isDispatchData;
 - (BOOL) isEqualToData:(id)a ;
 - (BOOL) _canReplaceWithDispatchDataForXPCCoder;
 - (void) enumerateByteRangesUsingBlock:(@?)a ;
 - (BOOL) _isCompact;
 - (BOOL) _copyWillRetain;
 - (BOOL) writeToFile:(id)a options:(unsigned long long)b error:(^@)c ;
 - (id) initWithBytesNoCopy:(^v)a length:(unsigned long long)b ;
 - (id) initWithContentsOfMappedFile:(id)a ;
 - (id) initWithContentsOfFile:(id)a options:(unsigned long long)b error:(^@)c ;
 - (id) initWithContentsOfURL:(id)a options:(unsigned long long)b error:(^@)c ;
 - ({_NSRange=QQ}) rangeOfData:(id)a options:(unsigned long long)b range:({_NSRange=QQ})c ;
 - (BOOL) _decodeBase64EncodedCharacterBuffer:(r*)a length:(unsigned long long)b options:(unsigned long long)c buffer:(char*)d bufferLength:(unsigned long long)e state:(^{?=BBQQQI})f ;
 - (id) _initWithBase64EncodedObject:(id)a options:(unsigned long long)b ;
 - (id) _base64EncodingAsString:(BOOL)a withOptions:(unsigned long long)b ;
 - (id) _asciiDescription;
 - (BOOL) _allowsDirectEncoding;
 - (void) getBytes:(^v)a ;
 - (BOOL) writeToURL:(id)a options:(unsigned long long)b error:(^@)c ;
 - (id) initWithContentsOfMappedFile:(id)a error:(^@)b ;
 - (id) initWithContentsOfFile:(id)a error:(^@)b ;
 - (id) initWithBase64EncodedString:(id)a options:(unsigned long long)b ;
 - (id) initWithBase64EncodedData:(id)a options:(unsigned long long)b ;
 - (id) base64EncodedDataWithOptions:(unsigned long long)a ;
 - (id) copyWithZone:(^{_NSZone=})a ;
 - (id) mutableCopyWithZone:(^{_NSZone=})a ;
 - (id) description;
 - (r^v) bytes;
 - (void) getBytes:(^v)a range:({_NSRange=QQ})b ;
 - (unsigned long long) hash;
 - (BOOL) isEqual:(id)a ;
 - (unsigned long long) _cfTypeID;
 - (void) getBytes:(^v)a length:(unsigned long long)b ;
 - (id) base64EncodedStringWithOptions:(unsigned long long)a ;
 - (BOOL) writeToFile:(id)a atomically:(BOOL)b error:(^@)c ;
 - (unsigned long long) length;
 - (id) initWithBytes:(^v)a length:(unsigned long long)b copy:(BOOL)c freeWhenDone:(BOOL)d bytesAreVM:(BOOL)e ;
 - (void) encodeWithCoder:(id)a ;
 - (id) initWithCoder:(id)a ;
 - (id) initWithData:(id)a ;
 - (id) initWithContentsOfURL:(id)a ;
 - (id) initWithBytesNoCopy:(^v)a length:(unsigned long long)b deallocator:(@?)c ;
 - (id) base64Encoding;
 - (id) initWithBase64Encoding:(id)a ;
 - (BOOL) _isSafeResumeDataForBackgroundDownload:(int)a ;


@end
