
@interface NSDateFormatter : NSFormatter {

    NSMutableDictionary* _attributes;
    ^{__CFDateFormatter=} _formatter;
    unsigned long long _counter;
    NSObject<OS_dispatch_semaphore>* _lock;
}
 + (void) setDefaultFormatterBehavior:(unsigned long long)a;
 + (unsigned long long) defaultFormatterBehavior;
 + (id) localizedStringFromDate:(id)adateStyle:(unsigned long long)btimeStyle:(unsigned long long)c;
 + (id) dateFormatFromTemplate:(id)aoptions:(unsigned long long)blocale:(id)c;
 + (void) initialize;

 - (BOOL) getObjectValue:(o^@)a forString:(id)b errorDescription:(o^@)c ;
 - (id) stringForObjectValue:(id)a ;
 - (void) _regenerateFormatter;
 - (void) _clearFormatter;
 - (id) dateFormat;
 - (id) _timeZone_forOldMethods;
 - (id) _locale_forOldMethods;
 - (void) _regenerateFormatterIfAbsent;
 - (BOOL) getObjectValue:(o^@)a forString:(id)b range:(N^{_NSRange=QQ})c error:(o^@)d ;
 - (void) setFormatterBehavior:(unsigned long long)a ;
 - (void) setDateStyle:(unsigned long long)a ;
 - (void) setTimeStyle:(unsigned long long)a ;
 - (id) _getLocaleAlreadyLocked:(BOOL)a ;
 - (void) _setDateFormat:(id)a alreadyLocked:(BOOL)b ;
 - (void) setLocalizedDateFormatFromTemplate:(id)a ;
 - (unsigned long long) dateStyle;
 - (unsigned long long) timeStyle;
 - (BOOL) generatesCalendarDates;
 - (void) setGeneratesCalendarDates:(BOOL)a ;
 - (unsigned long long) formatterBehavior;
 - (id) _dateFormat;
 - (void) _setDateFormat:(id)a ;
 - (void) _setIsLenient:(BOOL)a ;
 - (BOOL) isLenient;
 - (void) setLenient:(BOOL)a ;
 - (id) twoDigitStartDate;
 - (void) setTwoDigitStartDate:(id)a ;
 - (id) defaultDate;
 - (void) setDefaultDate:(id)a ;
 - (void) setEraSymbols:(id)a ;
 - (void) setMonthSymbols:(id)a ;
 - (void) setShortMonthSymbols:(id)a ;
 - (void) setWeekdaySymbols:(id)a ;
 - (void) setShortWeekdaySymbols:(id)a ;
 - (void) setAMSymbol:(id)a ;
 - (void) setPMSymbol:(id)a ;
 - (void) setLongEraSymbols:(id)a ;
 - (void) setVeryShortMonthSymbols:(id)a ;
 - (void) setStandaloneMonthSymbols:(id)a ;
 - (void) setShortStandaloneMonthSymbols:(id)a ;
 - (void) setVeryShortStandaloneMonthSymbols:(id)a ;
 - (void) setVeryShortWeekdaySymbols:(id)a ;
 - (void) setStandaloneWeekdaySymbols:(id)a ;
 - (void) setShortStandaloneWeekdaySymbols:(id)a ;
 - (void) setVeryShortStandaloneWeekdaySymbols:(id)a ;
 - (void) setQuarterSymbols:(id)a ;
 - (void) setShortQuarterSymbols:(id)a ;
 - (void) setStandaloneQuarterSymbols:(id)a ;
 - (void) setShortStandaloneQuarterSymbols:(id)a ;
 - (void) setFormattingContext:(long long)a ;
 - (long long) formattingContext;
 - (BOOL) doesRelativeDateFormatting;
 - (BOOL) _usesCharacterDirection;
 - (void) _setUsesCharacterDirection:(BOOL)a ;
 - (id) copyWithZone:(^{_NSZone=})a ;
 - (void) dealloc;
 - (void) finalize;
 - (void) setTimeZone:(id)a ;
 - (void) setLocale:(id)a ;
 - (id) locale;
 - (id) timeZone;
 - (id) gregorianStartDate;
 - (void) setGregorianStartDate:(id)a ;
 - (id) calendar;
 - (id) eraSymbols;
 - (id) weekdaySymbols;
 - (id) shortWeekdaySymbols;
 - (id) longEraSymbols;
 - (id) veryShortMonthSymbols;
 - (id) veryShortStandaloneMonthSymbols;
 - (id) veryShortWeekdaySymbols;
 - (id) standaloneWeekdaySymbols;
 - (id) shortStandaloneWeekdaySymbols;
 - (id) veryShortStandaloneWeekdaySymbols;
 - (id) quarterSymbols;
 - (id) shortQuarterSymbols;
 - (id) standaloneQuarterSymbols;
 - (id) shortStandaloneQuarterSymbols;
 - (void) setCalendar:(id)a ;
 - (void) setDoesRelativeDateFormatting:(BOOL)a ;
 - (void) _reset;
 - (id) dateFromString:(id)a ;
 - (id) init;
 - (void) encodeWithCoder:(id)a ;
 - (id) initWithCoder:(id)a ;
 - (id) stringFromDate:(id)a ;
 - (void) setDateFormat:(id)a ;
 - (id) monthSymbols;
 - (id) shortMonthSymbols;
 - (id) standaloneMonthSymbols;
 - (id) shortStandaloneMonthSymbols;
 - (id) AMSymbol;
 - (id) PMSymbol;


@end
