
@interface NSFileManager : NSObject {

}
@property (atomic, assign, readwrite) NSNumber* delegate;
@property (atomic, copy, readonly) NSString* currentDirectoryPath;
@property (atomic, copy, readonly) NSNumber* ubiquityIdentityToken;
 + (id) _web_createTemporaryFileForQuickLook:(id)a;
 + (BOOL) ensureDirectoryExists:(id)a;
 + (id) cacheDirectoryPathWithName:(id)a;
 + (BOOL) _storeMovePath:(id)atoPath:(id)b;
 + (id) defaultManager;

 - (id) gs_createTemporarySubdirectoryOfItem:(id)awithTemplate:(id)berror:(^@)c;
 - (int) gs_createTemporaryFdInDirectory:(id)awithTemplate:(id)berror:(^@)c;
 - (id) gs_createTemporaryFileInDirectory:(id)awithTemplate:(id)bandExtension:(id)cerror:(^@)d;
 - (BOOL) _cutIsPathOnMissingVolume:(id)a;
 - (id) cutCreateUniqueDirectoryWithName:(id)aatPath:(id)bofType:(id)c;
 - (id) cutUniqueFilename:(id)aatPath:(id)bofType:(id)c;
 - (id) cutRandomTemporaryPathWithFileName:(id)a;
 - (id) _webkit_createTemporaryDirectoryWithTemplatePrefix:(id)a;
 - (id) _webkit_pathWithUniqueFilenameForPath:(id)a;
 - (id) stringWithFileSystemRepresentation:(r*)alength:(unsigned long long)b;
 - (id) displayNameAtPath:(id)a;
 - (id) componentsToDisplayForPath:(id)a;
 - (id) _info;
 - (id) destinationOfSymbolicLinkAtPath:(id)aerror:(^@)b;
 - (BOOL) getFileSystemRepresentation:(char*)amaxLength:(unsigned long long)bwithPath:(id)c;
 - (id) contentsOfDirectoryAtPath:(id)aerror:(^@)b;
 - (id) _URLForReplacingItemAtURL:(id)aerror:(^@)b;
 - (BOOL) createDirectoryAtPath:(id)awithIntermediateDirectories:(BOOL)battributes:(id)cerror:(^@)d;
 - (BOOL) getRelationship:(^q)aofDirectoryAtURL:(id)btoItemAtURL:(id)cerror:(^@)d;
 - (long long) relationshipOfURL:(id)atoURL:(id)berror:(^@)c;
 - (BOOL) setAttributes:(id)aofItemAtPath:(id)berror:(^@)c;
 - (id) currentDirectoryPath;
 - (BOOL) isWritableFileAtPath:(id)a;
 - (BOOL) removeItemAtPath:(id)aerror:(^@)b;
 - (id) directoryContentsAtPath:(id)amatchingExtension:(id)boptions:(long long)ckeepExtension:(BOOL)derror:(^@)e;
 - (id) directoryContentsAtPath:(id)amatchingExtension:(id)boptions:(long long)ckeepExtension:(BOOL)d;
 - (id) enumeratorAtPath:(id)a;
 - (BOOL) changeFileAttributes:(id)aatPath:(id)b;
 - (BOOL) createSymbolicLinkAtPath:(id)awithDestinationPath:(id)berror:(^@)c;
 - (r*) fileSystemRepresentationWithPath:(id)a;
 - (BOOL) contentsEqualAtPath:(id)aandPath:(id)b;
 - (id) attributesOfFileSystemForPath:(id)aerror:(^@)b;
 - (BOOL) copyItemAtPath:(id)atoPath:(id)berror:(^@)c;
 - (BOOL) linkItemAtPath:(id)atoPath:(id)berror:(^@)c;
 - (BOOL) _processHasUbiquityContainerEntitlement;
 - (BOOL) _processUsesCloudServices;
 - (BOOL) _processCanAccessUbiquityIdentityToken;
 - (id) mountedVolumeURLsIncludingResourceValuesForKeys:(id)aoptions:(unsigned long long)b;
 - (id) contentsOfDirectoryAtURL:(id)aincludingPropertiesForKeys:(id)boptions:(unsigned long long)cerror:(^@)d;
 - (id) _URLForTrashingItemAtURL:(id)acreate:(BOOL)berror:(^@)c;
 - (BOOL) getRelationship:(^q)aofDirectory:(unsigned long long)binDomain:(unsigned long long)ctoItemAtURL:(id)derror:(^@)e;
 - (long long) relationshipOfDirectory:(unsigned long long)ainDomain:(unsigned long long)btoURL:(id)cerror:(^@)d;
 - (id) _displayPathForPath:(id)a;
 - (BOOL) directoryCanBeCreatedAtPath:(id)a;
 - (BOOL) changeCurrentDirectoryPath:(id)a;
 - (id) fileAttributesAtPath:(id)atraverseLink:(BOOL)b;
 - (BOOL) isReadableFileAtPath:(id)a;
 - (BOOL) isExecutableFileAtPath:(id)a;
 - (BOOL) isDeletableFileAtPath:(id)a;
 - (BOOL) removeFileAtPath:(id)ahandler:(id)b;
 - (id) directoryContentsAtPath:(id)a;
 - (BOOL) createDirectoryAtPath:(id)aattributes:(id)b;
 - (id) pathContentOfSymbolicLinkAtPath:(id)a;
 - (BOOL) createSymbolicLinkAtPath:(id)apathContent:(id)b;
 - (BOOL) createFileAtPath:(id)acontents:(id)battributes:(id)c;
 - (id) contentsAtPath:(id)a;
 - (id) fileSystemAttributesAtPath:(id)a;
 - (id) extendedAttributesAtPath:(id)aerror:(^@)b;
 - (id) extendedAttributeForKey:(id)aatPath:(id)berror:(^@)c;
 - (BOOL) removeExtendedAttributeForKey:(id)aatPath:(id)berror:(^@)c;
 - (BOOL) setExtendedAttribute:(id)aforKey:(id)batPath:(id)cerror:(^@)d;
 - (BOOL) filesystemItemCopyOperation:(id)ashouldCopyItemAtPath:(id)btoPath:(id)c;
 - (BOOL) filesystemItemCopyOperation:(id)ashouldProceedAfterError:(id)bcopyingItemAtPath:(id)ctoPath:(id)d;
 - (BOOL) copyItemAtURL:(id)atoURL:(id)berror:(^@)c;
 - (BOOL) filesystemItemMoveOperation:(id)ashouldMoveItemAtPath:(id)btoPath:(id)c;
 - (BOOL) filesystemItemMoveOperation:(id)ashouldProceedAfterError:(id)bmovingItemAtPath:(id)ctoPath:(id)d;
 - (BOOL) filesystemItemLinkOperation:(id)ashouldLinkItemAtPath:(id)btoPath:(id)c;
 - (BOOL) filesystemItemLinkOperation:(id)ashouldProceedAfterError:(id)blinkingItemAtPath:(id)ctoPath:(id)d;
 - (BOOL) filesystemItemRemoveOperation:(id)ashouldRemoveItemAtPath:(id)b;
 - (BOOL) filesystemItemRemoveOperation:(id)ashouldProceedAfterError:(id)bremovingItemAtPath:(id)c;
 - (BOOL) trashItemAtURL:(id)aresultingItemURL:(^@)berror:(^@)c;
 - (id) _attributesOfItemAtPath:(id)afilterResourceFork:(BOOL)berror:(^@)c;
 - (id) _attributesOfItemAtURL:(id)afilterResourceFork:(BOOL)berror:(^@)c;
 - (BOOL) createSymbolicLinkAtURL:(id)awithDestinationURL:(id)berror:(^@)c;
 - (BOOL) replaceItemAtURL:(id)awithItemAtURL:(id)bbackupItemName:(id)coptions:(unsigned long long)dresultingItemURL:(^@)eerror:(^@)f;
 - (BOOL) setUbiquitous:(BOOL)aitemAtURL:(id)bdestinationURL:(id)cerror:(^@)d;
 - (BOOL) isUbiquitousItemAtURL:(id)a;
 - (BOOL) evictUbiquitousItemAtURL:(id)aerror:(^@)b;
 - (id) URLForPublishingUbiquitousItemAtURL:(id)aexpirationDate:(^@)berror:(^@)c;
 - (void) _registerForUbiquityAccountChangeNotifications;
 - (BOOL) _web_changeFinderAttributes:(id)aforFileAtPath:(id)b;
 - (void) _performRemoveFileAtPath:(id)a;
 - (BOOL) _web_createFileAtPath:(id)acontents:(id)battributes:(id)c;
 - (void) _web_backgroundRemoveFileAtPath:(id)a;
 - (void) _web_backgroundRemoveLeftoverFiles:(id)a;
 - (id) _web_visibleItemsInDirectoryAtPath:(id)a;
 - (id) _web_carbonPathForPath_nowarn:(id)a;
 - (BOOL) _web_fileExistsAtPath_nowarn:(id)aisDirectory:(^B)btraverseLink:(BOOL)c;
 - (id) _web_startupVolumeName_nowarn;
 - (BOOL) _web_createIntermediateDirectoriesForPath_nowarn:(id)aattributes:(id)b;
 - (void) _web_noteFileChangedAtPath_nowarn:(id)a;
 - (BOOL) _web_changeFileAttributes_nowarn:(id)aatPath:(id)b;
 - (void) dealloc;
 - (void) setDelegate:(id)a;
 - (BOOL) _web_createDirectoryAtPathWithIntermediateDirectories:(id)aattributes:(id)b;
 - (BOOL) linkItemAtURL:(id)atoURL:(id)berror:(^@)c;
 - (id) subpathsOfDirectoryAtPath:(id)aerror:(^@)b;
 - (BOOL) startDownloadingUbiquitousItemAtURL:(id)aerror:(^@)b;
 - (BOOL) moveItemAtURL:(id)atoURL:(id)berror:(^@)c;
 - (id) ubiquityIdentityToken;
 - (id) URLForUbiquityContainerIdentifier:(id)a;
 - (id) URLsForDirectory:(unsigned long long)ainDomains:(unsigned long long)b;
 - (id) attributesOfItemAtPath:(id)aerror:(^@)b;
 - (id) delegate;
 - (BOOL) moveItemAtPath:(id)atoPath:(id)berror:(^@)c;
 - (BOOL) fileExistsAtPath:(id)aisDirectory:(^B)b;
 - (BOOL) removeItemAtURL:(id)aerror:(^@)b;
 - (BOOL) createDirectoryAtURL:(id)awithIntermediateDirectories:(BOOL)battributes:(id)cerror:(^@)d;
 - (id) containerURLForSecurityApplicationGroupIdentifier:(id)a;
 - (id) URLForDirectory:(unsigned long long)ainDomain:(unsigned long long)bappropriateForURL:(id)ccreate:(BOOL)derror:(^@)e;
 - (BOOL) fileExistsAtPath:(id)a;
 - (id) subpathsAtPath:(id)a;
 - (id) enumeratorAtURL:(id)aincludingPropertiesForKeys:(id)boptions:(unsigned long long)cerrorHandler:(@?)d;
 - (BOOL) _web_removeFileOnlyAtPath:(id)a;
 - (id) _web_pathWithUniqueFilenameForPath:(id)a;
 - (BOOL) _web_createFileAtPathWithIntermediateDirectories:(id)acontents:(id)battributes:(id)cdirectoryAttributes:(id)d;


@end
