
@interface NSFileManager : NSObject {

}
@property (atomic, assign, readwrite) NSNumber* delegate;
@property (atomic, copy, readonly) NSString* currentDirectoryPath;
@property (atomic, copy, readonly) NSNumber* ubiquityIdentityToken;
 + (id) _web_createTemporaryFileForQuickLook:(id)a;
 + (BOOL) ensureDirectoryExists:(id)a;
 + (id) cacheDirectoryPathWithName:(id)a;
 + (BOOL) _storeMovePath:(id)atoPath:(id)b;
 + (id) defaultManager;

 - (id) gs_createTemporarySubdirectoryOfItem:(id)a withTemplate:(id)b error:(^@)c ;
 - (int) gs_createTemporaryFdInDirectory:(id)a withTemplate:(id)b error:(^@)c ;
 - (id) gs_createTemporaryFileInDirectory:(id)a withTemplate:(id)b andExtension:(id)c error:(^@)d ;
 - (BOOL) _cutIsPathOnMissingVolume:(id)a ;
 - (id) cutCreateUniqueDirectoryWithName:(id)a atPath:(id)b ofType:(id)c ;
 - (id) cutUniqueFilename:(id)a atPath:(id)b ofType:(id)c ;
 - (id) cutRandomTemporaryPathWithFileName:(id)a ;
 - (id) _webkit_createTemporaryDirectoryWithTemplatePrefix:(id)a ;
 - (id) _webkit_pathWithUniqueFilenameForPath:(id)a ;
 - (id) stringWithFileSystemRepresentation:(r*)a length:(unsigned long long)b ;
 - (id) displayNameAtPath:(id)a ;
 - (id) componentsToDisplayForPath:(id)a ;
 - (id) _info;
 - (id) destinationOfSymbolicLinkAtPath:(id)a error:(^@)b ;
 - (BOOL) getFileSystemRepresentation:(char*)a maxLength:(unsigned long long)b withPath:(id)c ;
 - (id) contentsOfDirectoryAtPath:(id)a error:(^@)b ;
 - (id) _URLForReplacingItemAtURL:(id)a error:(^@)b ;
 - (BOOL) createDirectoryAtPath:(id)a withIntermediateDirectories:(BOOL)b attributes:(id)c error:(^@)d ;
 - (BOOL) getRelationship:(^q)a ofDirectoryAtURL:(id)b toItemAtURL:(id)c error:(^@)d ;
 - (long long) relationshipOfURL:(id)a toURL:(id)b error:(^@)c ;
 - (BOOL) setAttributes:(id)a ofItemAtPath:(id)b error:(^@)c ;
 - (id) currentDirectoryPath;
 - (BOOL) isWritableFileAtPath:(id)a ;
 - (BOOL) removeItemAtPath:(id)a error:(^@)b ;
 - (id) directoryContentsAtPath:(id)a matchingExtension:(id)b options:(long long)c keepExtension:(BOOL)d error:(^@)e ;
 - (id) directoryContentsAtPath:(id)a matchingExtension:(id)b options:(long long)c keepExtension:(BOOL)d ;
 - (id) enumeratorAtPath:(id)a ;
 - (BOOL) changeFileAttributes:(id)a atPath:(id)b ;
 - (BOOL) createSymbolicLinkAtPath:(id)a withDestinationPath:(id)b error:(^@)c ;
 - (r*) fileSystemRepresentationWithPath:(id)a ;
 - (BOOL) contentsEqualAtPath:(id)a andPath:(id)b ;
 - (id) attributesOfFileSystemForPath:(id)a error:(^@)b ;
 - (BOOL) copyItemAtPath:(id)a toPath:(id)b error:(^@)c ;
 - (BOOL) linkItemAtPath:(id)a toPath:(id)b error:(^@)c ;
 - (BOOL) _processHasUbiquityContainerEntitlement;
 - (BOOL) _processUsesCloudServices;
 - (BOOL) _processCanAccessUbiquityIdentityToken;
 - (id) mountedVolumeURLsIncludingResourceValuesForKeys:(id)a options:(unsigned long long)b ;
 - (id) contentsOfDirectoryAtURL:(id)a includingPropertiesForKeys:(id)b options:(unsigned long long)c error:(^@)d ;
 - (id) _URLForTrashingItemAtURL:(id)a create:(BOOL)b error:(^@)c ;
 - (BOOL) getRelationship:(^q)a ofDirectory:(unsigned long long)b inDomain:(unsigned long long)c toItemAtURL:(id)d error:(^@)e ;
 - (long long) relationshipOfDirectory:(unsigned long long)a inDomain:(unsigned long long)b toURL:(id)c error:(^@)d ;
 - (id) _displayPathForPath:(id)a ;
 - (BOOL) directoryCanBeCreatedAtPath:(id)a ;
 - (BOOL) changeCurrentDirectoryPath:(id)a ;
 - (id) fileAttributesAtPath:(id)a traverseLink:(BOOL)b ;
 - (BOOL) isReadableFileAtPath:(id)a ;
 - (BOOL) isExecutableFileAtPath:(id)a ;
 - (BOOL) isDeletableFileAtPath:(id)a ;
 - (BOOL) removeFileAtPath:(id)a handler:(id)b ;
 - (id) directoryContentsAtPath:(id)a ;
 - (BOOL) createDirectoryAtPath:(id)a attributes:(id)b ;
 - (id) pathContentOfSymbolicLinkAtPath:(id)a ;
 - (BOOL) createSymbolicLinkAtPath:(id)a pathContent:(id)b ;
 - (BOOL) createFileAtPath:(id)a contents:(id)b attributes:(id)c ;
 - (id) contentsAtPath:(id)a ;
 - (id) fileSystemAttributesAtPath:(id)a ;
 - (id) extendedAttributesAtPath:(id)a error:(^@)b ;
 - (id) extendedAttributeForKey:(id)a atPath:(id)b error:(^@)c ;
 - (BOOL) removeExtendedAttributeForKey:(id)a atPath:(id)b error:(^@)c ;
 - (BOOL) setExtendedAttribute:(id)a forKey:(id)b atPath:(id)c error:(^@)d ;
 - (BOOL) filesystemItemCopyOperation:(id)a shouldCopyItemAtPath:(id)b toPath:(id)c ;
 - (BOOL) filesystemItemCopyOperation:(id)a shouldProceedAfterError:(id)b copyingItemAtPath:(id)c toPath:(id)d ;
 - (BOOL) copyItemAtURL:(id)a toURL:(id)b error:(^@)c ;
 - (BOOL) filesystemItemMoveOperation:(id)a shouldMoveItemAtPath:(id)b toPath:(id)c ;
 - (BOOL) filesystemItemMoveOperation:(id)a shouldProceedAfterError:(id)b movingItemAtPath:(id)c toPath:(id)d ;
 - (BOOL) filesystemItemLinkOperation:(id)a shouldLinkItemAtPath:(id)b toPath:(id)c ;
 - (BOOL) filesystemItemLinkOperation:(id)a shouldProceedAfterError:(id)b linkingItemAtPath:(id)c toPath:(id)d ;
 - (BOOL) filesystemItemRemoveOperation:(id)a shouldRemoveItemAtPath:(id)b ;
 - (BOOL) filesystemItemRemoveOperation:(id)a shouldProceedAfterError:(id)b removingItemAtPath:(id)c ;
 - (BOOL) trashItemAtURL:(id)a resultingItemURL:(^@)b error:(^@)c ;
 - (id) _attributesOfItemAtPath:(id)a filterResourceFork:(BOOL)b error:(^@)c ;
 - (id) _attributesOfItemAtURL:(id)a filterResourceFork:(BOOL)b error:(^@)c ;
 - (BOOL) createSymbolicLinkAtURL:(id)a withDestinationURL:(id)b error:(^@)c ;
 - (BOOL) replaceItemAtURL:(id)a withItemAtURL:(id)b backupItemName:(id)c options:(unsigned long long)d resultingItemURL:(^@)e error:(^@)f ;
 - (BOOL) setUbiquitous:(BOOL)a itemAtURL:(id)b destinationURL:(id)c error:(^@)d ;
 - (BOOL) isUbiquitousItemAtURL:(id)a ;
 - (BOOL) evictUbiquitousItemAtURL:(id)a error:(^@)b ;
 - (id) URLForPublishingUbiquitousItemAtURL:(id)a expirationDate:(^@)b error:(^@)c ;
 - (void) _registerForUbiquityAccountChangeNotifications;
 - (BOOL) _web_changeFinderAttributes:(id)a forFileAtPath:(id)b ;
 - (void) _performRemoveFileAtPath:(id)a ;
 - (BOOL) _web_createFileAtPath:(id)a contents:(id)b attributes:(id)c ;
 - (void) _web_backgroundRemoveFileAtPath:(id)a ;
 - (void) _web_backgroundRemoveLeftoverFiles:(id)a ;
 - (id) _web_visibleItemsInDirectoryAtPath:(id)a ;
 - (id) _web_carbonPathForPath_nowarn:(id)a ;
 - (BOOL) _web_fileExistsAtPath_nowarn:(id)a isDirectory:(^B)b traverseLink:(BOOL)c ;
 - (id) _web_startupVolumeName_nowarn;
 - (BOOL) _web_createIntermediateDirectoriesForPath_nowarn:(id)a attributes:(id)b ;
 - (void) _web_noteFileChangedAtPath_nowarn:(id)a ;
 - (BOOL) _web_changeFileAttributes_nowarn:(id)a atPath:(id)b ;
 - (void) dealloc;
 - (void) setDelegate:(id)a ;
 - (BOOL) _web_createDirectoryAtPathWithIntermediateDirectories:(id)a attributes:(id)b ;
 - (BOOL) linkItemAtURL:(id)a toURL:(id)b error:(^@)c ;
 - (id) subpathsOfDirectoryAtPath:(id)a error:(^@)b ;
 - (BOOL) startDownloadingUbiquitousItemAtURL:(id)a error:(^@)b ;
 - (BOOL) moveItemAtURL:(id)a toURL:(id)b error:(^@)c ;
 - (id) ubiquityIdentityToken;
 - (id) URLForUbiquityContainerIdentifier:(id)a ;
 - (id) URLsForDirectory:(unsigned long long)a inDomains:(unsigned long long)b ;
 - (id) attributesOfItemAtPath:(id)a error:(^@)b ;
 - (id) delegate;
 - (BOOL) moveItemAtPath:(id)a toPath:(id)b error:(^@)c ;
 - (BOOL) fileExistsAtPath:(id)a isDirectory:(^B)b ;
 - (BOOL) removeItemAtURL:(id)a error:(^@)b ;
 - (BOOL) createDirectoryAtURL:(id)a withIntermediateDirectories:(BOOL)b attributes:(id)c error:(^@)d ;
 - (id) containerURLForSecurityApplicationGroupIdentifier:(id)a ;
 - (id) URLForDirectory:(unsigned long long)a inDomain:(unsigned long long)b appropriateForURL:(id)c create:(BOOL)d error:(^@)e ;
 - (BOOL) fileExistsAtPath:(id)a ;
 - (id) subpathsAtPath:(id)a ;
 - (id) enumeratorAtURL:(id)a includingPropertiesForKeys:(id)b options:(unsigned long long)c errorHandler:(@?)d ;
 - (BOOL) _web_removeFileOnlyAtPath:(id)a ;
 - (id) _web_pathWithUniqueFilenameForPath:(id)a ;
 - (BOOL) _web_createFileAtPathWithIntermediateDirectories:(id)a contents:(id)b attributes:(id)c directoryAttributes:(id)d ;


@end
