
@protocol NSISVariableDelegate;
@interface NSISEngine : NSObject <NSISVariableDelegate> {

    NSMapTable* _rows;
    NSMapTable* _rowsCrossIndex;
    NSISVariable* _headForObjectiveRow;
    NSMutableArray* _variablesWithValueRestrictionViolations;
    NSMutableArray* _pendingRemovals;
    <NSISEngineDelegate>* _delegate;
    NSMapTable* _brokenConstraintPositiveErrors;
    NSMapTable* _brokenConstraintNegativeErrors;
    NSMutableSet* _variablesWithIntegralizationViolations;
    ^{__CFDictionary=} _integralizationAdjustmentsForConstraintMarkers;
    @? _unsatisfiabilityHandler;
    unsigned long long _pivotCount;
    {CGSize="width"d"height"d} _engineScalingCoefficients;
    NSMutableDictionary* _recordedOperations;
    int _automaticOptimizationDisabledCount;
    int _engineDelegateCallsDisabledCount;
    int _variableDelegateCallsDisabledCount;
    unsigned int _totalChangeCount;
    unsigned int _changeCountAtLastOptimization;
    BOOL _lastOptimizationInvolvedIntegralization;
    BOOL _shouldIntegralize;
    BOOL _revertsAfterUnsatisfiabilityHandler;
    BOOL _accumulatingRemovals;
}
@property (atomic, assign, readwrite) NSNumber* delegate;
@property (atomic, assign, readwrite) NSNumber* shouldIntegralize;
@property (atomic, assign, readwrite) NSNumber* revertsAfterUnsatisfiabilityHandler;
@property (nonatomic, assign, readwrite) NSNumber* engineScalingCoefficients;
@property (atomic, retain, readwrite) NSMapTable* rows;
@property (atomic, retain, readwrite) NSMapTable* rowsCrossIndex;
@property (atomic, retain, readwrite) NSISVariable* headForObjectiveRow;
@property (atomic, retain, readwrite) NSMutableArray* variablesWithValueRestrictionViolations;
@property (atomic, retain, readwrite) NSMutableSet* variablesWithIntegralizationViolations;
@property (atomic, assign, readwrite) NSNumber* integralizationAdjustmentsForConstraintMarkers;

 - (void) setShouldIntegralize:(BOOL)a ;
 - (unsigned long long) optimize;
 - (BOOL) tryToAddConstraintWithMarker:(id)a expression:(id)b integralizationAdjustment:(double)c mutuallyExclusiveConstraints:(^@)d ;
 - (void) addVariableToBeOptimized:(id)a priority:(double)b ;
 - (void) removeVariableToBeOptimized:(id)a priority:(double)b ;
 - (void) changeVariableToBeOptimized:(id)a fromPriority:(double)b toPriority:(double)c ;
 - (void) removeConstraintWithMarker:(id)a ;
 - (void) constraintDidChangeSuchThatMarker:(id)a shouldBeReplacedByMarkerPlusDelta:(double)b ;
 - (BOOL) tryToChangeConstraintSuchThatMarker:(id)a isReplacedByMarkerPlusDelta:(double)b undoHandler:(@?)c ;
 - (void) nsis_valueOfVariable:(id)a didChangeInEngine:(id)b ;
 - (id) nsis_descriptionOfVariable:(id)a ;
 - (BOOL) nsis_shouldIntegralizeVariable:(id)a ;
 - (BOOL) nsis_valueOfVariableIsUserObservable:(id)a ;
 - (void) verifyInternalIntegrity;
 - (id) _brokenConstraintPositiveErrors;
 - (id) _brokenConstraintPositiveErrorsIfAvailable;
 - (id) _brokenConstraintNegativeErrors;
 - (id) _brokenConstraintNegativeErrorsIfAvailable;
 - (id) markerForBrokenConstraintWithPositiveErrorVar:(id)a ;
 - (id) markerForBrokenConstraintWithNegativeErrorVar:(id)a ;
 - (void) rawSetRowWithHead:(id)a body:(id)b ;
 - (void) rowCrossIndexNoteBodyVariable:(id)a wasAddedToRowWithHead:(id)b ;
 - (id) rowBodyForHead:(id)a ;
 - (void) rowCrossIndexNoteBodyVariable:(id)a wasRemovedFromRowWithHead:(id)b ;
 - (void) rawRemoveRowWithHead:(id)a ;
 - (id) rowHeadsForRowsContainingBodyVar:(id)a ;
 - (void) rowCrossIndexNoteDroppedBodyVar:(id)a ;
 - (id) rowBodyForNonObjectiveHead:(id)a ;
 - (void) removeRowWithHead:(id)a ;
 - (void) substituteOutAllOccurencesOfBodyVar:(id)a withExpression:(id)b ;
 - (void) setRowWithHead:(id)a body:(id)b ;
 - (void) addVariable:(id)a coefficient:(double)b toRowWithHead:(id)c body:(id)d ;
 - (id) rowBodyForObjectiveHead:(id)a ;
 - (void) addVariable:(id)a priority:(double)b times:(double)c toObjectiveRowWithHead:(id)d body:(id)e ;
 - (void) replaceMarker:(id)a withMarkerPlusCoefficient:(double)b timesVariable:(id)c ;
 - (void) setPositiveErrorVar:(id)a forBrokenConstraintWithMarker:(id)b ;
 - (void) setNegativeErrorVar:(id)a forBrokenConstraintWithMarker:(id)b ;
 - (id) fallbackMarkerForConstraintToBreakInRowWithHead:(id)a body:(id)b ;
 - (id) errorVariableIntroducedByBreakingConstraintWithMarker:(id)a errorIsPositive:(BOOL)b ;
 - (id) chooseOutgoingRowHeadForIncomingRowHead:(id)a ;
 - (void) pivotToMakeBodyVar:(id)a newHeadOfRowWithHead:(id)b andDropRow:(BOOL)c ;
 - (id) handleUnsatisfiableRowWithHead:(id)a body:(id)b usingInfeasibilityHandlingBehavior:(long long)c mutuallyExclusiveConstraints:(^@)d ;
 - (double) integralizationAdjustmentForMarker:(id)a ;
 - (id) variableToWorkOnAmongVariablesWithIntegralizationViolationsIgnoringLostCauses:(id)a varsAlreadyAdjusted:(id)b ;
 - (double) valueForVariableWithoutIntegralizationAdjustments:(id)a ;
 - (void) setIntegralizationAdjustment:(double)a forMarker:(id)b ;
 - (double) valueForVariable:(id)a ;
 - (void) withoutOptimizingAtEndRunBlockWithAutomaticOptimizationDisabled:(@?)a ;
 - (id) chooseHeadForRowBody:(id)a ;
 - (unsigned long long) minimizeConstantInObjectiveRowWithHead:(id)a ;
 - (void) removeBodyVarFromAllRows:(id)a ;
 - (void) setRows:(id)a ;
 - (void) setRowsCrossIndex:(id)a ;
 - (void) setHeadForObjectiveRow:(id)a ;
 - (void) setVariablesWithValueRestrictionViolations:(id)a ;
 - (void) setVariablesWithIntegralizationViolations:(id)a ;
 - (void) setIntegralizationAdjustmentsForConstraintMarkers:(^{__CFDictionary=})a ;
 - (id) fixUpValueRestrictionViolationsWithInfeasibilityHandlingBehavior:(long long)a ;
 - (void) fixupIntegralizationViolations;
 - (void) _flushPendingRemovals;
 - (void) withBehaviors:(unsigned long long)a performModifications:(@?)b ;
 - (BOOL) hasValue:(^d)a forVariable:(id)b ;
 - (id) createExpressionBySubstitutingForRowHeadVariablesInExpression:(id)a ;
 - (BOOL) tryAddingDirectly:(id)a ;
 - (BOOL) tryUsingArtificialVariableToAddConstraintWithMarker:(id)a rowBody:(id)b usingInfeasibilityHandlingBehavior:(long long)c mutuallyExclusiveConstraints:(^@)d ;
 - (void) addExpression:(id)a priority:(double)b times:(double)c toObjectiveRowWithHead:(id)d body:(id)e ;
 - (id) outgoingRowHeadForRemovingConstraintWithMarker:(id)a ;
 - (id) positiveErrorVarForBrokenConstraintWithMarker:(id)a ;
 - (id) negativeErrorVarForBrokenConstraintWithMarker:(id)a ;
 - (void) _coreReplaceMarker:(id)a withMarkerPlusDelta:(double)b ;
 - (id) tryToOptimizeReturningMutuallyExclusiveConstraints;
 - (void) enumerateRows:(@?)a ;
 - (void) enumerateRowsCrossIndex:(@?)a ;
 - (void) enumerateOriginalConstraints:(@?)a ;
 - (BOOL) bodyVarIsAmbiguous:(id)a withPivotOfOutgoingRowHead:(^@)b ;
 - (BOOL) incoming:(^@)a andOutgoing:(^@)b rowHeadsThatMakeValueAmbiguousForVariable:(id)c ;
 - (^{__CFDictionary=}) integralizationAdjustmentsForConstraintMarkers;
 - (id) allRowHeads;
 - (void) addExpression:(id)a times:(double)b toRowWithHead:(id)c body:(id)d ;
 - (void) performModifications:(@?)a withUnsatisfiableConstraintsHandler:(@?)b ;
 - (unsigned long long) numberOfConstraintsEligibleForAdjustmentToIntegralizeVariable:(id)a ignoringConstraintsWithMarkers:(id)b ;
 - (void) beginRecording;
 - (id) recordedCommandsData;
 - (unsigned long long) replayCommandsData:(id)a verifyingIntegrity:(BOOL)b ;
 - (BOOL) shouldIntegralize;
 - (void) withAutomaticOptimizationDisabled:(@?)a ;
 - (void) withDelegateCallsDisabled:(@?)a ;
 - (id) constraints;
 - (unsigned long long) pivotCount;
 - (BOOL) valueOfVariableIsAmbiguous:(id)a ;
 - (id) rowsCrossIndex;
 - (id) headForObjectiveRow;
 - (id) variablesWithValueRestrictionViolations;
 - (id) variablesWithIntegralizationViolations;
 - (BOOL) revertsAfterUnsatisfiabilityHandler;
 - (void) setRevertsAfterUnsatisfiabilityHandler:(BOOL)a ;
 - (id) description;
 - (void) dealloc;
 - (void) setDelegate:(id)a ;
 - (void) setEngineScalingCoefficients:({CGSize=dd})a ;
 - (id) rows;
 - (id) candidateRedundantConstraints;
 - ({CGSize=dd}) engineScalingCoefficients;
 - (id) constraintsAffectingValueOfVariable:(id)a ;
 - (BOOL) exerciseAmbiguityInVariable:(id)a ;
 - (id) init;
 - (id) delegate;


@end
