
@protocol NSCoding;
@interface NSLayoutManager : NSObject <NSCoding> {

    @"NSTextStorage" _textStorage;
    @"NSGlyphGenerator" _glyphGenerator;
    @"NSTypesetter" _typesetter;
    @"NSMutableArray" _textContainers;
    @"NSStorage" _containerUsedRects;
    @"NSRunStorage" _containerRuns;
    @"NSTextContainer" _extraLineFragmentContainer;
    {__lmFlags="containersAreFull"b1"glyphsMightDrawOutsideLines"b1"backgroundLayoutEnabled"b1"resizingInProgress"b1"allowScreenFonts"b1"cachedRectArrayInUse"b1"displayInvalidationInProgress"b1"insertionPointNeedsUpdate"b1"layoutManagerInDirtyList"b1"originalFontOverride"b1"showInvisibleCharacters"b1"showControlCharacters"b1"delegateRespondsToDidInvalidate"b1"delegateRespondsToDidComplete"b1"glyphFormat"b2"textStorageRespondsToIsEditing"b1"notifyEditedInProgress"b1"containersChanged"b1"isGeneratingGlyphs"b1"hasNonGeneratedGlyphData"b1"syncAlignmentToDirection"b1"defaultAttachmentScaling"b2"usesFontLeading"b1"seenRightToLeft"b1"ignoresViewTransformations"b1"needToFlushGlyph"b1"flipsIfNeeded"b1"allowNonContig"b1"useNonContig"b1"inBackgroundLayout"b1} _lmFlags;
    id _delegate;
    S _textViewResizeDisableStack;
    S _displayInvalidationDisableStack;
    {_NSRange="location"Q"length"Q} _deferredDisplayCharRange;
    id _firstTextView;
    ^{CGRect={CGPoint=dd}{CGSize=dd}} _cachedRectArray;
    Q _cachedRectArrayCapacity;
    * _glyphBuffer;
    Q _glyphBufferSize;
    {_NSRange="location"Q"length"Q} _cachedLocationNominalGlyphRange;
    Q _cachedLocationGlyphIndex;
    {CGPoint="x"d"y"d} _cachedLocation;
    {_NSRange="location"Q"length"Q} _cachedFontCharRange;
    @"NSFont" _cachedFont;
    Q _firstUnlaidGlyphIndex;
    Q _firstUnlaidCharIndex;
    {_NSRange="location"Q"length"Q} _newlyFilledGlyphRange;
    id _extraData;
}
@property (atomic, assign, readwrite) NSNumber* allowsOriginalFontMetricsOverride;
@property (nonatomic, assign, readwrite) NSTextStorage* textStorage;
@property (nonatomic, assign, readonly) NSArray* textContainers;
@property (nonatomic, assign, readwrite) NSNumber* delegate;
@property (nonatomic, assign, readwrite) NSNumber* showsInvisibleCharacters;
@property (nonatomic, assign, readwrite) NSNumber* showsControlCharacters;
@property (nonatomic, assign, readwrite) NSNumber* hyphenationFactor;
@property (nonatomic, assign, readwrite) NSNumber* usesFontLeading;
@property (nonatomic, assign, readwrite) NSNumber* allowsNonContiguousLayout;
@property (nonatomic, assign, readonly) NSNumber* hasNonContiguousLayout;
@property (nonatomic, assign, readonly) NSNumber* numberOfGlyphs;
@property (nonatomic, assign, readonly) NSNumber* extraLineFragmentRect;
@property (nonatomic, assign, readonly) NSNumber* extraLineFragmentUsedRect;
@property (nonatomic, assign, readonly) NSTextContainer* extraLineFragmentTextContainer;
 + (void) initialize;
 + (id) _defaultLinkAttributes;
 + (BOOL) _usesScreenFonts;
 + (BOOL) _ignoresViewTransformations;
 + (BOOL) _showsInvisibleCharacters;
 + (BOOL) _showsControlCharacters;

 - (id) _commonTextViewController;
 - (id) description;
 - (void) dealloc;
 - (void) finalize;
 - (void) setDelegate:(id)a;
 - (void) coordinateAccess:(@?)a;
 - (void) addTemporaryAttribute:(id)avalue:(id)bforCharacterRange:({_NSRange=QQ})c;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) boundingRectForGlyphRange:({_NSRange=QQ})ainTextContainer:(id)b;
 - (void) ensureLayoutForBoundingRect:({CGRect={CGPoint=dd}{CGSize=dd}})ainTextContainer:(id)b;
 - (BOOL) allowsNonContiguousLayout;
 - (void) setAllowsNonContiguousLayout:(BOOL)a;
 - (void) enumerateLineFragmentsForGlyphRange:({_NSRange=QQ})ausingBlock:(@?)b;
 - (void) enumerateEnclosingRectsForGlyphRange:({_NSRange=QQ})awithinSelectedGlyphRange:({_NSRange=QQ})binTextContainer:(id)cusingBlock:(@?)d;
 - (BOOL) hasNonContiguousLayout;
 - (void) removeTemporaryAttribute:(id)aforCharacterRange:({_NSRange=QQ})b;
 - ({_NSRange=QQ}) rangeOfCharacterClusterAtIndex:(Q)atype:(q)b;
 - (void) enumerateEnclosingRectsForCharacterRange:({_NSRange=QQ})awithinSelectedCharacterRange:({_NSRange=QQ})binTextContainer:(id)cusingBlock:(@?)d;
 - (Q) characterIndexForPoint:({CGPoint=dd})ainTextContainer:(id)bfractionOfDistanceBetweenInsertionPoints:(^d)c;
 - (q) propertyForGlyphAtIndex:(Q)a;
 - (Q) getLineFragmentInsertionPointsForCharacterAtIndex:(Q)aalternatePositions:(BOOL)binDisplayOrder:(BOOL)cpositions:(^d)dcharacterIndexes:(^Q)e;
 - (id) init;
 - (void) encodeWithCoder:(id)a;
 - (id) initWithCoder:(id)a;
 - (id) delegate;
 - (id) textStorage;
 - (id) textContainerForGlyphAtIndex:(Q)aeffectiveRange:(^{_NSRange=QQ})b;
 - (id) typesetter;
 - (id) circleImageWithSize:({CGSize=dd})abufferWidth:(d)busingColor:(id)c;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) lineFragmentUsedRectForGlyphAtIndex:(Q)aeffectiveRange:(^{_NSRange=QQ})b;
 - ({CGPoint=dd}) locationForGlyphAtIndex:(Q)a;
 - (q) intAttribute:(q)aforGlyphAtIndex:(Q)b;
 - (^{CGRect={CGPoint=dd}{CGSize=dd}}) rectArrayForGlyphRange:({_NSRange=QQ})awithinSelectedGlyphRange:({_NSRange=QQ})binTextContainer:(id)crectCount:(^Q)d;
 - (Q) characterIndexForGlyphAtIndex:(Q)a;
 - (S) glyphAtIndex:(Q)a;
 - (BOOL) _drawsUnderlinesLikeWebKit;
 - (BOOL) notShownAttributeForGlyphAtIndex:(Q)a;
 - (void) _drawLineForGlyphRange:({_NSRange=QQ})ainContext:(^{CGContext=})bfrom:(d)cto:(d)dat:(d)ethickness:(d)flineOrigin:({CGPoint=dd})gbreakForDescenders:(BOOL)hflipped:(BOOL)i;
 - ({_NSRange=QQ}) characterRangeForGlyphRange:({_NSRange=QQ})aactualGlyphRange:(^{_NSRange=QQ})b;
 - (id) temporaryAttribute:(id)aatCharacterIndex:(Q)beffectiveRange:(^{_NSRange=QQ})c;
 - (d) defaultLineHeightForFont:(id)a;
 - ({_NSRange=QQ}) glyphRangeForCharacterRange:({_NSRange=QQ})aactualCharacterRange:(^{_NSRange=QQ})b;
 - (d) defaultBaselineOffsetForFont:(id)a;
 - (id) temporaryAttribute:(id)aatCharacterIndex:(Q)blongestEffectiveRange:(^{_NSRange=QQ})cinRange:({_NSRange=QQ})d;
 - (void) drawUnderlineForGlyphRange:({_NSRange=QQ})aunderlineType:(q)bbaselineOffset:(d)clineFragmentRect:({CGRect={CGPoint=dd}{CGSize=dd}})dlineFragmentGlyphRange:({_NSRange=QQ})econtainerOrigin:({CGPoint=dd})f;
 - (void) drawStrikethroughForGlyphRange:({_NSRange=QQ})astrikethroughType:(q)bbaselineOffset:(d)clineFragmentRect:({CGRect={CGPoint=dd}{CGSize=dd}})dlineFragmentGlyphRange:({_NSRange=QQ})econtainerOrigin:({CGPoint=dd})f;
 - (void) _showCGGlyphs:(r^S)apositions:(r^{CGPoint=dd})bcount:(Q)cfont:(id)dmatrix:({CGAffineTransform=dddddd})eattributes:(id)finContext:(^{CGContext=})g;
 - (void) showAttachmentCell:(id)ainRect:({CGRect={CGPoint=dd}{CGSize=dd}})bcharacterIndex:(Q)c;
 - (void) drawSpellingUnderlineForGlyphRange:({_NSRange=QQ})aspellingState:(q)binGlyphRange:({_NSRange=QQ})clineFragmentRect:({CGRect={CGPoint=dd}{CGSize=dd}})dlineFragmentGlyphRange:({_NSRange=QQ})econtainerOrigin:({CGPoint=dd})f;
 - (void) _drawLineForGlyphRange:({_NSRange=QQ})ainContext:(^{CGContext=})bfrom:(d)cto:(d)dat:(d)ethickness:(d)flineOrigin:({CGPoint=dd})gbreakForDescenders:(BOOL)h;
 - (void) _drawLineForGlyphRange:({_NSRange=QQ})atype:(q)bbaselineOffset:(d)clineFragmentRect:({CGRect={CGPoint=dd}{CGSize=dd}})dlineFragmentGlyphRange:({_NSRange=QQ})econtainerOrigin:({CGPoint=dd})fisStrikethrough:(BOOL)g;
 - (void) _lineGlyphRange:({_NSRange=QQ})atype:(q)blineFragmentRect:({CGRect={CGPoint=dd}{CGSize=dd}})clineFragmentGlyphRange:({_NSRange=QQ})dcontainerOrigin:({CGPoint=dd})eisStrikethrough:(BOOL)f;
 - ({_NSRange=QQ}) _primitiveCharacterRangeForGlyphRange:({_NSRange=QQ})a;
 - ({_NSRange=QQ}) _blockRangeForCharRange:({_NSRange=QQ})a;
 - ({_NSRange=QQ}) _primitiveGlyphRangeForCharacterRange:({_NSRange=QQ})a;
 - ({_NSRange=QQ}) _blockRowRangeForCharRange:({_NSRange=QQ})acompleteRows:(^B)b;
 - ({_NSRange=QQ}) _blockRowRangeForCharRange:({_NSRange=QQ})a;
 - (id) attributedString;
 - (Q) _glyphIndexForCharacterIndex:(Q)astartOfRange:(BOOL)bokToFillHoles:(BOOL)cconsiderNulls:(BOOL)d;
 - (void) _fillGlyphHoleForCharacterRange:({_NSRange=QQ})astartGlyphIndex:(Q)bdesiredNumberOfCharacters:(Q)c;
 - (id) glyphGenerator;
 - (void) setExtraLineFragmentRect:({CGRect={CGPoint=dd}{CGSize=dd}})ausedRect:({CGRect={CGPoint=dd}{CGSize=dd}})btextContainer:(id)c;
 - (void) setTextContainer:(id)aforGlyphRange:({_NSRange=QQ})b;
 - (void) setLineFragmentRect:({CGRect={CGPoint=dd}{CGSize=dd}})aforGlyphRange:({_NSRange=QQ})busedRect:({CGRect={CGPoint=dd}{CGSize=dd}})c;
 - (void) setLocation:({CGPoint=dd})aforStartOfGlyphRange:({_NSRange=QQ})b;
 - (BOOL) _doOptimizedLayoutStartingAtGlyphIndex:(Q)aforCharacterRange:({_NSRange=QQ})binTextContainer:(id)clineLimit:(Q)dnextGlyphIndex:(^Q)e;
 - (void) _invalidateGlyphsForExtendedCharacterRange:({_NSRange=QQ})achangeInLength:(q)bincludeBlocks:(BOOL)c;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) layoutRectForTextBlock:(id)aatIndex:(Q)beffectiveRange:(^{_NSRange=QQ})c;
 - (void) setNotShownAttribute:(BOOL)aforGlyphAtIndex:(Q)b;
 - (void) _doLayoutWithFullContainerStartingAtGlyphIndex:(Q)anextGlyphIndex:(^Q)b;
 - (void) _invalidateLayoutForExtendedCharacterRange:({_NSRange=QQ})aisSoft:(BOOL)binvalidateUsage:(BOOL)c;
 - (void) _invalidateUsageForTextContainersInRange:({_NSRange=QQ})a;
 - (void) _resizeTextViewForTextContainer:(id)a;
 - (void) _invalidateInsertionPoint;
 - (void) invalidateDisplayForGlyphRange:({_NSRange=QQ})a;
 - (void) _invalidateDisplayIfNeeded;
 - (void) _invalidateLayoutForExtendedCharacterRange:({_NSRange=QQ})aisSoft:(BOOL)b;
 - (void) _fillLayoutHoleForCharacterRange:({_NSRange=QQ})adesiredNumberOfLines:(Q)bisSoft:(BOOL)c;
 - (Q) _smallEncodingGlyphIndexForCharacterIndex:(Q)astartOfRange:(BOOL)bokToFillHoles:(BOOL)cconsiderNulls:(BOOL)d;
 - (Q) glyphIndexForCharacterAtIndex:(Q)a;
 - (void) _mergeLayoutHoles;
 - (void) _fillLayoutHoleAtIndex:(Q)adesiredNumberOfLines:(Q)b;
 - (id) _lineFragmentDescriptionForGlyphRange:({_NSRange=QQ})aincludeGlyphLocations:(BOOL)b;
 - (id) _lineFragmentDescription:(BOOL)a;
 - (id) _glyphDescriptionForGlyphRange:({_NSRange=QQ})a;
 - (Q) _indexOfFirstGlyphInTextContainer:(id)aokToFillHoles:(BOOL)b;
 - (void) _recalculateUsageForTextContainerAtIndex:(Q)a;
 - (void) invalidateDisplayForCharacterRange:({_NSRange=QQ})a;
 - (void) _growCachedRectArrayToSize:(Q)a;
 - (^{CGRect={CGPoint=dd}{CGSize=dd}}) _rectArrayForRange:({_NSRange=QQ})awithinSelectionRange:({_NSRange=QQ})brangeIsCharRange:(BOOL)csingleRectOnly:(BOOL)dfullLineRectsOnly:(BOOL)einTextContainer:(id)frectCount:(^Q)grangeWithinContainer:(^{_NSRange=QQ})hglyphsDrawOutsideLines:(^B)irectArray:(^{CGRect={CGPoint=dd}{CGSize=dd}})jrectArrayCapacity:(Q)k;
 - (^{CGRect={CGPoint=dd}{CGSize=dd}}) _rectArrayForRange:({_NSRange=QQ})awithinSelectionRange:({_NSRange=QQ})brangeIsCharRange:(BOOL)csingleRectOnly:(BOOL)dfullLineRectsOnly:(BOOL)einTextContainer:(id)frectCount:(^Q)grangeWithinContainer:(^{_NSRange=QQ})hglyphsDrawOutsideLines:(^B)i;
 - (id) substituteFontForFont:(id)a;
 - ({CGSize=dd}) attachmentSizeForGlyphAtIndex:(Q)a;
 - ({_NSRange=QQ}) _glyphRangeForCharacterRange:({_NSRange=QQ})aactualCharacterRange:(^{_NSRange=QQ})bokToFillHoles:(BOOL)c;
 - ({_NSRange=QQ}) _firstPassGlyphRangeForBoundingRect:({CGRect={CGPoint=dd}{CGSize=dd}})ainTextContainer:(id)bhintGlyphRange:({_NSRange=QQ})cokToFillHoles:(BOOL)d;
 - ({_NSRange=QQ}) _firstPassGlyphRangeForBoundingRect:({CGRect={CGPoint=dd}{CGSize=dd}})ainTextContainer:(id)bokToFillHoles:(BOOL)c;
 - (void) _noteFirstTextViewVisibleCharacterRangeIfAfterIndex:(Q)a;
 - (void) _setRowArrayCache:(id)a;
 - (void) _markSelfAsDirtyForBackgroundLayout:(id)a;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) boundsRectForTextBlock:(id)aatIndex:(Q)beffectiveRange:(^{_NSRange=QQ})c;
 - (id) temporaryAttributesAtCharacterIndex:(Q)alongestEffectiveRange:(^{_NSRange=QQ})binRange:({_NSRange=QQ})c;
 - (^{CGRect={CGPoint=dd}{CGSize=dd}}) rectArrayForCharacterRange:({_NSRange=QQ})awithinSelectedCharacterRange:({_NSRange=QQ})binTextContainer:(id)crectCount:(^Q)d;
 - (void) fillBackgroundRectArray:(r^{CGRect={CGPoint=dd}{CGSize=dd}})acount:(Q)bforCharacterRange:({_NSRange=QQ})ccolor:(id)d;
 - (BOOL) _drawsDebugBaselines;
 - (BOOL) _hasSeenRightToLeft;
 - (void) showAttachment:(id)ainRect:({CGRect={CGPoint=dd}{CGSize=dd}})btextContainer:(id)ccharacterIndex:(Q)d;
 - (void) underlineGlyphRange:({_NSRange=QQ})aunderlineType:(q)blineFragmentRect:({CGRect={CGPoint=dd}{CGSize=dd}})clineFragmentGlyphRange:({_NSRange=QQ})dcontainerOrigin:({CGPoint=dd})e;
 - (void) showCGGlyphs:(r^S)apositions:(r^{CGPoint=dd})bcount:(Q)cfont:(id)dmatrix:({CGAffineTransform=dddddd})eattributes:(id)finContext:(^{CGContext=})g;
 - (void) strikethroughGlyphRange:({_NSRange=QQ})astrikethroughType:(q)blineFragmentRect:({CGRect={CGPoint=dd}{CGSize=dd}})clineFragmentGlyphRange:({_NSRange=QQ})dcontainerOrigin:({CGPoint=dd})e;
 - (void) setBaselineOffset:(d)aforGlyphAtIndex:(Q)b;
 - (void) _invalidateGlyphsForExtendedCharacterRange:({_NSRange=QQ})achangeInLength:(q)b;
 - (void) invalidateLayoutForCharacterRange:({_NSRange=QQ})aactualCharacterRange:(^{_NSRange=QQ})b;
 - (void) _mergeGlyphHoles;
 - ({_NSRange=QQ}) _blockRangeForGlyphRange:({_NSRange=QQ})a;
 - ({_NSRange=QQ}) _blockRowRangeForGlyphRange:({_NSRange=QQ})acompleteRows:(^B)b;
 - ({_NSRange=QQ}) _blockRowRangeForGlyphRange:({_NSRange=QQ})a;
 - (id) _rowArrayCache;
 - ({_NSRange=QQ}) _extendedCharRangeForInvalidation:({_NSRange=QQ})aeditedCharRange:({_NSRange=QQ})b;
 - (void) _adjustCharacterIndicesForRawGlyphRange:({_NSRange=QQ})abyDelta:(q)b;
 - (BOOL) _canDoLayout;
 - (void) _fillGlyphHoleAtIndex:(Q)adesiredNumberOfCharacters:(Q)b;
 - (Q) _smallEncodingGlyphIndexForCharacterIndex:(Q)astartOfRange:(BOOL)bokToFillHoles:(BOOL)c;
 - (Q) _glyphIndexForCharacterIndex:(Q)astartOfRange:(BOOL)bokToFillHoles:(BOOL)c;
 - (id) _containerDescription;
 - (id) _lineFragmentDescription;
 - (id) _glyphLocationDescription;
 - (id) _glyphDescription;
 - (id) _glyphHoleDescription;
 - (id) _layoutHoleDescription;
 - (id) _glyphTreeDescription;
 - (id) _layoutTreeDescription;
 - (id) _blockDescription;
 - (void) _updateUsageForTextContainer:(id)aaddingUsedRect:({CGRect={CGPoint=dd}{CGSize=dd}})b;
 - (^{_NSStoredContainerUsage={CGRect={CGPoint=dd}{CGSize=dd}}{CGRect={CGPoint=dd}{CGSize=dd}}{?=b1b1b1b29}{CGRect={CGPoint=dd}{CGSize=dd}}{_NSRange=QQ}}) _validatedStoredUsageForTextContainerAtIndex:(Q)a;
 - (id) _selectedRanges;
 - (void) _fixSelectionAfterChangeInCharacterRange:({_NSRange=QQ})achangeInLength:(q)b;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) _boundingRectForGlyphRange:({_NSRange=QQ})ainTextContainer:(id)bfast:(BOOL)cfullLineRectsOnly:(BOOL)d;
 - ({_NSRange=QQ}) _glyphRangeForBoundingRect:({CGRect={CGPoint=dd}{CGSize=dd}})ainTextContainer:(id)bfast:(BOOL)cokToFillHoles:(BOOL)d;
 - (void) _firstTextViewChanged;
 - (void) _drawBackgroundForGlyphRange:({_NSRange=QQ})aatPoint:({CGPoint=dd})b;
 - (id) selectedTextAttributesForCharacterAtIndex:(Q)aeffectiveRange:(^{_NSRange=QQ})b;
 - (*) _packedGlyphs:(Q)arange:({_NSRange=QQ})blength:(^Q)c;
 - (void) _drawGlyphsForGlyphRange:({_NSRange=QQ})aatPoint:({CGPoint=dd})b;
 - (I) _glyphAtIndex:(Q)acharacterIndex:(^Q)bglyphInscription:(^Q)cisValidIndex:(^B)d;
 - (BOOL) _needToFlushGlyph;
 - (void) _setNeedToFlushGlyph:(BOOL)a;
 - (void) _simpleInsertGlyph:(I)aatGlyphIndex:(Q)bcharacterIndex:(Q)celastic:(BOOL)d;
 - (void) _simpleDeleteGlyphsInRange:({_NSRange=QQ})a;
 - (void) _insertGlyphs:(^I)aelasticAttributes:(^B)bcount:(Q)catGlyphIndex:(Q)dcharacterIndex:(Q)e;
 - (void) _promoteGlyphStoreToFormat:(Q)a;
 - (id) _attachmentSizesRun;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) _currentAttachmentRect;
 - (Q) _currentAttachmentIndex;
 - (void) _setCurrentAttachmentRect:({CGRect={CGPoint=dd}{CGSize=dd}})aindex:(Q)b;
 - (void) _clearCurrentAttachmentSettings;
 - (void) _clearTemporaryAttributes;
 - (void) _clearTemporaryAttributesForCharacterRange:({_NSRange=QQ})achangeInLength:(q)b;
 - (void) setAllowsOriginalFontMetricsOverride:(BOOL)a;
 - (BOOL) allowsOriginalFontMetricsOverride;
 - (void) _setHasSeenRightToLeft:(BOOL)a;
 - (BOOL) flipsIfNeeded;
 - (void) setFlipsIfNeeded:(BOOL)a;
 - (void) setLineFragmentRect:({CGRect={CGPoint=dd}{CGSize=dd}})aforGlyphRange:({_NSRange=QQ})busedRect:({CGRect={CGPoint=dd}{CGSize=dd}})cbaselineOffset:(d)d;
 - (d) baselineOffsetForGlyphAtIndex:(Q)a;
 - (BOOL) ignoresViewTransformations;
 - (void) setIgnoresViewTransformations:(BOOL)a;
 - (BOOL) ignoresAntialiasThreshold;
 - (void) setIgnoresAntialiasThreshold:(BOOL)a;
 - (BOOL) _alwaysDrawsActive;
 - (void) _setAlwaysDrawsActive:(BOOL)a;
 - (id) _insertionPointHelperForGlyphAtIndex:(Q)a;
 - (q) getLineFragmentInsertionPointArraysForCharacterAtIndex:(Q)ainDisplayOrder:(BOOL)bpositions:(^^d)ccharacterIndexes:(^^Q)dcount:(^Q)ealternatePositions:(^^d)fcharacterIndexes:(^^Q)gcount:(^Q)h;
 - (id) _selectionRangesForInsertionPointRange:({_NSRange=QQ})a;
 - (void) _setDrawsUnderlinesLikeWebKit:(BOOL)a;
 - (void) _setDrawsDebugBaselines:(BOOL)a;
 - (void) ensureLayoutForCharacterRange:({_NSRange=QQ})a;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) usedRectForTextContainer:(id)a;
 - (void) getFirstUnlaidCharacterIndex:(^Q)aglyphIndex:(^Q)b;
 - (BOOL) synchronizesAlignmentToDirection;
 - (q) typesetterBehavior;
 - (d) hyphenationFactor;
 - (id) textContainers;
 - (Q) getGlyphsInRange:({_NSRange=QQ})aglyphs:(^S)bproperties:(^q)ccharacterIndexes:(^Q)dbidiLevels:(*)e;
 - (BOOL) usesFontLeading;
 - (void) insertGlyph:(I)aatGlyphIndex:(Q)bcharacterIndex:(Q)c;
 - (void) setEllipsisGlyphAttribute:(BOOL)aforGlyphAtIndex:(Q)b;
 - (void) setAttachmentSize:({CGSize=dd})aforGlyphRange:({_NSRange=QQ})b;
 - (void) setUsesFontLeading:(BOOL)a;
 - (void) setTypesetterBehavior:(q)a;
 - (void) setGlyphs:(r^S)aproperties:(r^q)bcharacterIndexes:(r^Q)cfont:(id)dforGlyphRange:({_NSRange=QQ})e;
 - (void) insertGlyphs:(r^I)alength:(Q)bforStartingGlyphAtIndex:(Q)ccharacterIndex:(Q)d;
 - (void) setIntAttribute:(q)avalue:(q)bforGlyphAtIndex:(Q)c;
 - (Q) layoutOptions;
 - (void) deleteGlyphsInRange:({_NSRange=QQ})a;
 - (Q) numberOfGlyphs;
 - (void) _commonInit;
 - (void) setGlyphGenerator:(id)a;
 - (void) insertTextContainer:(id)aatIndex:(Q)b;
 - ({_NSRange=QQ}) _characterRangeCurrentlyInAndAfterContainer:(id)a;
 - (void) textContainerChangedTextView:(id)a;
 - (void) _setGlyphsPerLineEstimate:(Q)aoffsetPerLineEstimate:(d)b;
 - (void) invalidateGlyphsForCharacterRange:({_NSRange=QQ})achangeInLength:(q)bactualCharacterRange:(^{_NSRange=QQ})c;
 - (void) invalidateLayoutForCharacterRange:({_NSRange=QQ})aisSoft:(BOOL)bactualCharacterRange:(^{_NSRange=QQ})c;
 - (void) _invalidateGlyphsForCharacterRange:({_NSRange=QQ})aeditedCharacterRange:({_NSRange=QQ})bchangeInLength:(q)cactualCharacterRange:(^{_NSRange=QQ})d;
 - (void) _primitiveInvalidateDisplayForGlyphRange:({_NSRange=QQ})a;
 - (void) _forceDisplayToBeCorrectForViewsWithUnlaidGlyphs;
 - (void) textStorage:(id)aedited:(Q)brange:({_NSRange=QQ})cchangeInLength:(q)dinvalidatedRange:({_NSRange=QQ})e;
 - (void) ensureGlyphsForCharacterRange:({_NSRange=QQ})a;
 - ({_NSRange=QQ}) glyphRangeForBoundingRect:({CGRect={CGPoint=dd}{CGSize=dd}})ainTextContainer:(id)b;
 - (void) ensureLayoutForGlyphRange:({_NSRange=QQ})a;
 - (void) _primitiveDeleteGlyphsInRange:({_NSRange=QQ})a;
 - (S) glyphAtIndex:(Q)aisValidIndex:(^B)b;
 - (Q) getGlyphsInRange:({_NSRange=QQ})aglyphs:(^I)bcharacterIndexes:(^Q)cglyphInscriptions:(^Q)delasticBits:(^B)ebidiLevels:(*)f;
 - (Q) firstUnlaidCharacterIndex;
 - (Q) firstUnlaidGlyphIndex;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) lineFragmentUsedRectForGlyphAtIndex:(Q)aeffectiveRange:(^{_NSRange=QQ})bwithoutAdditionalLayout:(BOOL)c;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) lineFragmentRectForGlyphAtIndex:(Q)aeffectiveRange:(^{_NSRange=QQ})b;
 - (d) fractionOfDistanceThroughGlyphForPoint:({CGPoint=dd})ainTextContainer:(id)b;
 - (Q) glyphIndexForPoint:({CGPoint=dd})ainTextContainer:(id)b;
 - (Q) glyphIndexForPoint:({CGPoint=dd})ainTextContainer:(id)bfractionOfDistanceThroughGlyph:(^d)c;
 - (id) temporaryAttributesAtCharacterIndex:(Q)aeffectiveRange:(^{_NSRange=QQ})b;
 - (BOOL) usesScreenFonts;
 - (void) setTextStorage:(id)a;
 - (void) replaceTextStorage:(id)a;
 - (id) _glyphGenerator;
 - (void) _setGlyphGenerator:(id)a;
 - (void) setTypesetter:(id)a;
 - (void) addTextContainer:(id)a;
 - (void) removeTextContainerAtIndex:(Q)a;
 - (void) textContainerChangedGeometry:(id)a;
 - (void) textContainerChangedTextView:(id)afromTextView:(id)b;
 - (void) _setGlyphsPerLineEstimate:(Q)aintegerOffsetPerLineEstimate:(Q)b;
 - (void) setBackgroundLayoutEnabled:(BOOL)a;
 - (BOOL) backgroundLayoutEnabled;
 - (void) setUsesScreenFonts:(BOOL)a;
 - (void) setShowsInvisibleCharacters:(BOOL)a;
 - (BOOL) showsInvisibleCharacters;
 - (void) setShowsControlCharacters:(BOOL)a;
 - (BOOL) showsControlCharacters;
 - (void) setHyphenationFactor:(d)a;
 - (BOOL) backgroundColorProvidesOpaqueSurface;
 - (void) processEditingForTextStorage:(id)aedited:(Q)brange:({_NSRange=QQ})cchangeInLength:(q)dinvalidatedRange:({_NSRange=QQ})e;
 - (void) ensureGlyphsForGlyphRange:({_NSRange=QQ})a;
 - (void) ensureLayoutForTextContainer:(id)a;
 - (void) replaceGlyphAtIndex:(Q)awithGlyph:(I)b;
 - (void) setCharacterIndex:(Q)aforGlyphAtIndex:(Q)b;
 - (void) invalidateGlyphsOnLayoutInvalidationForGlyphRange:({_NSRange=QQ})a;
 - (BOOL) isValidGlyphIndex:(Q)a;
 - (Q) getGlyphsInRange:({_NSRange=QQ})aglyphs:(^I)bcharacterIndexes:(^Q)cglyphInscriptions:(^Q)delasticBits:(^B)e;
 - (Q) getGlyphs:(^I)arange:({_NSRange=QQ})b;
 - (void) setLocation:({CGPoint=dd})aforStartOfGlyphRange:({_NSRange=QQ})bcoalesceRuns:(BOOL)c;
 - (void) setLocations:(^{CGPoint=dd})astartingGlyphIndexes:(^Q)bcount:(Q)cforGlyphRange:({_NSRange=QQ})d;
 - (void) setDrawsOutsideLineFragment:(BOOL)aforGlyphAtIndex:(Q)b;
 - (id) textContainerForGlyphAtIndex:(Q)aeffectiveRange:(^{_NSRange=QQ})bwithoutAdditionalLayout:(BOOL)c;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) lineFragmentRectForGlyphAtIndex:(Q)aeffectiveRange:(^{_NSRange=QQ})bwithoutAdditionalLayout:(BOOL)c;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) lineFragmentUsedRectForGlyphAtIndex:(Q)aeffectiveRange:(^{_NSRange=QQ})ballowLayout:(BOOL)c;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) extraLineFragmentRect;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) extraLineFragmentUsedRect;
 - (id) extraLineFragmentTextContainer;
 - (BOOL) drawsOutsideLineFragmentForGlyphAtIndex:(Q)a;
 - ({_NSRange=QQ}) truncatedGlyphRangeInLineFragmentForGlyphAtIndex:(Q)a;
 - (void) setLayoutRect:({CGRect={CGPoint=dd}{CGSize=dd}})aforTextBlock:(id)bglyphRange:({_NSRange=QQ})c;
 - (void) setBoundsRect:({CGRect={CGPoint=dd}{CGSize=dd}})aforTextBlock:(id)bglyphRange:({_NSRange=QQ})c;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) layoutRectForTextBlock:(id)aglyphRange:({_NSRange=QQ})b;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) boundsRectForTextBlock:(id)aglyphRange:({_NSRange=QQ})b;
 - ({_NSRange=QQ}) glyphRangeForTextContainer:(id)a;
 - ({_NSRange=QQ}) rangeOfNominallySpacedGlyphsContainingIndex:(Q)a;
 - ({_NSRange=QQ}) glyphRangeForBoundingRectWithoutAdditionalLayout:({CGRect={CGPoint=dd}{CGSize=dd}})ainTextContainer:(id)b;
 - (void) setTemporaryAttributes:(id)aforCharacterRange:({_NSRange=QQ})b;
 - (void) addTemporaryAttributes:(id)aforCharacterRange:({_NSRange=QQ})b;
 - (id) _temporaryAttribute:(id)aatCharacterIndex:(Q)beffectiveRange:(^{_NSRange=QQ})c;
 - (id) _temporaryAttribute:(id)aatCharacterIndex:(Q)blongestEffectiveRange:(^{_NSRange=QQ})cinRange:({_NSRange=QQ})d;
 - (id) _temporaryAttributesAtCharacterIndex:(Q)alongestEffectiveRange:(^{_NSRange=QQ})binRange:({_NSRange=QQ})c;
 - (void) setSynchronizesAlignmentToDirection:(BOOL)a;
 - (void) drawGlyphsForGlyphRange:({_NSRange=QQ})aatPoint:({CGPoint=dd})b;
 - (void) drawBackgroundForGlyphRange:({_NSRange=QQ})aatPoint:({CGPoint=dd})b;


@end
