
@interface NSNumber : NSValue {

}
 + (id) numberWithItemIdentifier:(Q)a;
 + (BOOL) supportsSecureCoding;
 + (id) numberWithUnsignedLongLong:(Q)a;
 + (id) numberWithFloat:(f)a;
 + (id) numberWithChar:(c)a;
 + (id) numberWithUnsignedChar:(C)a;
 + (id) numberWithShort:(s)a;
 + (id) numberWithUnsignedShort:(S)a;
 + (id) numberWithUnsignedInt:(I)a;
 + (id) numberWithLong:(q)a;
 + (void) initialize;
 + (id) allocWithZone:(^{_NSZone=})a;
 + (id) numberWithInt:(i)a;
 + (id) numberWithLongLong:(q)a;
 + (id) numberWithInteger:(q)a;
 + (id) numberWithBool:(BOOL)a;
 + (id) numberWithUnsignedInteger:(Q)a;
 + (id) numberWithDouble:(d)a;
 + (id) numberWithUnsignedLong:(Q)a;

 - (id) MPMediaLibraryDataProviderSystemML3CoercedString;
 - (id) ml_stringValueForSQL;
 - (void) ml_bindToSQLiteStatement:(^{sqlite3_stmt=})aatPosition:(i)b;
 - (Q) itemIdentifierValue;
 - (id) initWithItemIdentifier:(Q)a;
 - (void) encodeWithCAMLWriter:(id)a;
 - (id) CAMLType;
 - (id) CA_addValue:(id)amultipliedBy:(i)b;
 - (id) CA_interpolateValue:(id)abyFraction:(f)b;
 - (id) CA_roundToIntegerFromValue:(id)a;
 - (d) CA_distanceToValue:(id)a;
 - (id) CA_interpolateValues:(id)ainterpolator:(id)b;
 - (^{Object=^^?{Atomic={?=i}}}) CA_copyRenderValue;
 - (Class) classForCoder;
 - (BOOL) _allowsDirectEncoding;
 - (S) unsignedShortValue;
 - (C) unsignedCharValue;
 - (id) initWithUnsignedShort:(S)a;
 - (id) initWithShort:(s)a;
 - (id) initWithUnsignedLongLong:(Q)a;
 - (id) initWithLongLong:(q)a;
 - (id) initWithUnsignedLong:(Q)a;
 - (id) initWithLong:(q)a;
 - (id) initWithUnsignedInt:(I)a;
 - (id) initWithInt:(i)a;
 - (id) initWithFloat:(f)a;
 - (id) initWithDouble:(d)a;
 - (id) initWithUnsignedChar:(C)a;
 - (id) initWithChar:(c)a;
 - (id) initWithBool:(BOOL)a;
 - ({?=b8b4b1b1b18[8S]}) decimalValue;
 - (id) initWithInteger:(q)a;
 - (id) initWithUnsignedInteger:(Q)a;
 - (id) copyWithZone:(^{_NSZone=})a;
 - (id) description;
 - (Q) hash;
 - (BOOL) isEqual:(id)a;
 - (BOOL) boolValue;
 - (q) _cfNumberType;
 - (C) _getValue:(^v)aforType:(q)b;
 - (q) compare:(id)a;
 - (q) _reverseCompare:(id)a;
 - (d) doubleValue;
 - (BOOL) _getCString:(*)alength:(i)bmultiplier:(d)c;
 - (BOOL) isNSNumber__;
 - (BOOL) isEqualToNumber:(id)a;
 - (id) descriptionWithLocale:(id)a;
 - (id) stringValue;
 - (q) longValue;
 - (Q) unsignedLongValue;
 - (I) unsignedIntValue;
 - (c) charValue;
 - (s) shortValue;
 - (i) intValue;
 - (q) longLongValue;
 - (f) floatValue;
 - (Q) unsignedLongLongValue;
 - (Q) unsignedIntegerValue;
 - (Q) _cfTypeID;
 - (void) encodeWithCoder:(id)a;
 - (id) initWithCoder:(id)a;
 - (q) integerValue;


@end
