
@protocol NSCopying, NSMutableCopying, NSSecureCoding, NSFastEnumeration;
@interface NSOrderedSet : NSObject <NSCopying, NSMutableCopying, NSSecureCoding, NSFastEnumeration> {

}
@property (atomic, assign, readonly) NSNumber* count;
 + (BOOL) supportsSecureCoding;
 + (id) orderedSetWithObjects:(r^@)acount:(unsigned long long)b;
 + (id) allocWithZone:(^{_NSZone=})a;
 + (id) orderedSetWithArray:(id)a;
 + (id) orderedSetWithObject:(id)a;
 + (id) newOrderedSetWithObjects:(r^@)acount:(unsigned long long)b;
 + (id) orderedSetWithObjects:(id)a;
 + (id) orderedSetWithArray:(id)arange:({_NSRange=QQ})bcopyItems:(BOOL)c;
 + (id) orderedSetWithArray:(id)arange:({_NSRange=QQ})b;
 + (id) orderedSetWithArray:(id)acopyItems:(BOOL)b;
 + (id) orderedSetWithOrderedSet:(id)arange:({_NSRange=QQ})bcopyItems:(BOOL)c;
 + (id) orderedSetWithOrderedSet:(id)arange:({_NSRange=QQ})b;
 + (id) orderedSetWithOrderedSet:(id)acopyItems:(BOOL)b;
 + (id) orderedSetWithOrderedSet:(id)a;
 + (id) orderedSetWithSet:(id)acopyItems:(BOOL)b;
 + (id) orderedSetWithSet:(id)a;
 + (id) orderedSet;

 - (id) filteredOrderedSetUsingPredicate:(id)a;
 - (id) sortedArrayUsingDescriptors:(id)a;
 - (void) removeObserver:(id)aforKeyPath:(id)b;
 - (void) addObserver:(id)aforKeyPath:(id)boptions:(unsigned long long)ccontext:(^v)d;
 - (void) removeObserver:(id)aforKeyPath:(id)bcontext:(^v)c;
 - (id) _valueForKeyPath:(id)aofObjectAtIndex:(unsigned long long)b;
 - (id) _mutableArrayValueForKeyPath:(id)aofObjectAtIndex:(unsigned long long)b;
 - (id) _mutableOrderedSetValueForKeyPath:(id)aofObjectAtIndex:(unsigned long long)b;
 - (id) _mutableSetValueForKeyPath:(id)aofObjectAtIndex:(unsigned long long)b;
 - (void) _setValue:(id)aforKeyPath:(id)bofObjectAtIndex:(unsigned long long)c;
 - (BOOL) _validateValue:(N^@)aforKeyPath:(id)bofObjectAtIndex:(unsigned long long)cerror:(o^@)d;
 - (id) _sumForKeyPath:(id)a;
 - (id) _avgForKeyPath:(id)a;
 - (id) _countForKeyPath:(id)a;
 - (id) _maxForKeyPath:(id)a;
 - (id) _minForKeyPath:(id)a;
 - (void) setValue:(id)aforKey:(id)b;
 - (id) valueForKey:(id)a;
 - (id) valueForKeyPath:(id)a;
 - (Class) classForCoder;
 - (id) initWithObjects:(id)a;
 - (BOOL) intersectsSet:(id)a;
 - (BOOL) isSubsetOfSet:(id)a;
 - (id) initWithSet:(id)a;
 - (id) sortedArrayUsingComparator:(@?)a;
 - (unsigned long long) indexOfObject:(id)ainSortedRange:({_NSRange=QQ})boptions:(unsigned long long)cusingComparator:(@?)d;
 - (id) copyWithZone:(^{_NSZone=})a;
 - (id) mutableCopyWithZone:(^{_NSZone=})a;
 - (id) description;
 - (unsigned long long) count;
 - (id) objectAtIndex:(unsigned long long)a;
 - (void) getObjects:(^@)arange:({_NSRange=QQ})b;
 - (unsigned long long) countForObject:(id)a;
 - (BOOL) containsObject:(id)a;
 - (unsigned long long) hash;
 - (BOOL) isEqual:(id)a;
 - (id) descriptionWithLocale:(id)a;
 - (void) getObjects:(^@)a;
 - (unsigned long long) countByEnumeratingWithState:(^{?=Q^@^Q[5Q]})aobjects:(^@)bcount:(unsigned long long)c;
 - (id) initWithObjects:(r^@)acount:(unsigned long long)b;
 - (void) enumerateObjectsWithOptions:(unsigned long long)ausingBlock:(@?)b;
 - (id) initWithArray:(id)acopyItems:(BOOL)b;
 - (id) initWithObject:(id)a;
 - (id) initWithArray:(id)a;
 - (id) indexesOfObjectsAtIndexes:(id)aoptions:(unsigned long long)bpassingTest:(@?)c;
 - (id) indexesOfObjectsWithOptions:(unsigned long long)apassingTest:(@?)b;
 - (unsigned long long) indexOfObjectWithOptions:(unsigned long long)apassingTest:(@?)b;
 - (unsigned long long) indexOfObjectAtIndexes:(id)aoptions:(unsigned long long)bpassingTest:(@?)c;
 - (id) objectWithOptions:(unsigned long long)apassingTest:(@?)b;
 - (id) objectsAtIndexes:(id)a;
 - (id) objectsWithOptions:(unsigned long long)apassingTest:(@?)b;
 - (id) sortedArrayFromRange:({_NSRange=QQ})aoptions:(unsigned long long)busingComparator:(@?)c;
 - (id) sortedArrayWithOptions:(unsigned long long)ausingComparator:(@?)b;
 - (id) descriptionWithLocale:(id)aindent:(unsigned long long)b;
 - (id) initWithArray:(id)arange:({_NSRange=QQ})bcopyItems:(BOOL)c;
 - (id) initWithOrderedSet:(id)arange:({_NSRange=QQ})bcopyItems:(BOOL)c;
 - (id) initWithSet:(id)acopyItems:(BOOL)b;
 - (id) array;
 - (id) allObjects;
 - (BOOL) containsObject:(id)ainRange:({_NSRange=QQ})b;
 - (unsigned long long) countForObject:(id)ainRange:({_NSRange=QQ})b;
 - (void) enumerateObjectsAtIndexes:(id)aoptions:(unsigned long long)busingBlock:(@?)c;
 - (unsigned long long) indexOfObject:(id)ainRange:({_NSRange=QQ})b;
 - (unsigned long long) indexOfObject:(id)a;
 - (id) lastObject;
 - (id) objectAtIndexes:(id)aoptions:(unsigned long long)bpassingTest:(@?)c;
 - (id) objectPassingTest:(@?)a;
 - (id) objectsAtIndexes:(id)aoptions:(unsigned long long)bpassingTest:(@?)c;
 - (id) objectEnumerator;
 - (id) initWithArray:(id)arange:({_NSRange=QQ})b;
 - (id) initWithOrderedSet:(id)arange:({_NSRange=QQ})b;
 - (id) initWithOrderedSet:(id)acopyItems:(BOOL)b;
 - (id) initWithOrderedSet:(id)a;
 - (id) set;
 - (BOOL) isNSOrderedSet__;
 - (BOOL) intersectsOrderedSet:(id)a;
 - (BOOL) isSubsetOfOrderedSet:(id)a;
 - (BOOL) isEqualToOrderedSet:(id)a;
 - (id) reversedOrderedSet;
 - (id) objectsPassingTest:(@?)a;
 - (void) encodeWithCoder:(id)a;
 - (id) initWithCoder:(id)a;
 - (void) enumerateObjectsUsingBlock:(@?)a;
 - (id) firstObject;
 - (id) objectAtIndexedSubscript:(unsigned long long)a;
 - (id) reverseObjectEnumerator;
 - (id) indexesOfObjectsPassingTest:(@?)a;
 - (unsigned long long) indexOfObjectPassingTest:(@?)a;


@end
