
@protocol NSCopying, NSMutableCopying, NSSecureCoding, NSFastEnumeration;
@interface NSOrderedSet : NSObject <NSCopying, NSMutableCopying, NSSecureCoding, NSFastEnumeration> {

}
@property (atomic, assign, readonly) NSNumber* count;
 + (BOOL) supportsSecureCoding;
 + (id) orderedSetWithObjects:(r^@)acount:(unsigned long long)b;
 + (id) allocWithZone:(^{_NSZone=})a;
 + (id) orderedSetWithArray:(id)a;
 + (id) orderedSetWithObject:(id)a;
 + (id) newOrderedSetWithObjects:(r^@)acount:(unsigned long long)b;
 + (id) orderedSetWithObjects:(id)a;
 + (id) orderedSetWithArray:(id)arange:({_NSRange=QQ})bcopyItems:(BOOL)c;
 + (id) orderedSetWithArray:(id)arange:({_NSRange=QQ})b;
 + (id) orderedSetWithArray:(id)acopyItems:(BOOL)b;
 + (id) orderedSetWithOrderedSet:(id)arange:({_NSRange=QQ})bcopyItems:(BOOL)c;
 + (id) orderedSetWithOrderedSet:(id)arange:({_NSRange=QQ})b;
 + (id) orderedSetWithOrderedSet:(id)acopyItems:(BOOL)b;
 + (id) orderedSetWithOrderedSet:(id)a;
 + (id) orderedSetWithSet:(id)acopyItems:(BOOL)b;
 + (id) orderedSetWithSet:(id)a;
 + (id) orderedSet;

 - (id) filteredOrderedSetUsingPredicate:(id)a ;
 - (id) sortedArrayUsingDescriptors:(id)a ;
 - (void) removeObserver:(id)a forKeyPath:(id)b ;
 - (void) addObserver:(id)a forKeyPath:(id)b options:(unsigned long long)c context:(^v)d ;
 - (void) removeObserver:(id)a forKeyPath:(id)b context:(^v)c ;
 - (id) _valueForKeyPath:(id)a ofObjectAtIndex:(unsigned long long)b ;
 - (id) _mutableArrayValueForKeyPath:(id)a ofObjectAtIndex:(unsigned long long)b ;
 - (id) _mutableOrderedSetValueForKeyPath:(id)a ofObjectAtIndex:(unsigned long long)b ;
 - (id) _mutableSetValueForKeyPath:(id)a ofObjectAtIndex:(unsigned long long)b ;
 - (void) _setValue:(id)a forKeyPath:(id)b ofObjectAtIndex:(unsigned long long)c ;
 - (BOOL) _validateValue:(N^@)a forKeyPath:(id)b ofObjectAtIndex:(unsigned long long)c error:(o^@)d ;
 - (id) _sumForKeyPath:(id)a ;
 - (id) _avgForKeyPath:(id)a ;
 - (id) _countForKeyPath:(id)a ;
 - (id) _maxForKeyPath:(id)a ;
 - (id) _minForKeyPath:(id)a ;
 - (void) setValue:(id)a forKey:(id)b ;
 - (id) valueForKey:(id)a ;
 - (id) valueForKeyPath:(id)a ;
 - (Class) classForCoder;
 - (id) initWithObjects:(id)a ;
 - (BOOL) intersectsSet:(id)a ;
 - (BOOL) isSubsetOfSet:(id)a ;
 - (id) initWithSet:(id)a ;
 - (id) sortedArrayUsingComparator:(@?)a ;
 - (unsigned long long) indexOfObject:(id)a inSortedRange:({_NSRange=QQ})b options:(unsigned long long)c usingComparator:(@?)d ;
 - (id) copyWithZone:(^{_NSZone=})a ;
 - (id) mutableCopyWithZone:(^{_NSZone=})a ;
 - (id) description;
 - (unsigned long long) count;
 - (id) objectAtIndex:(unsigned long long)a ;
 - (void) getObjects:(^@)a range:({_NSRange=QQ})b ;
 - (unsigned long long) countForObject:(id)a ;
 - (BOOL) containsObject:(id)a ;
 - (unsigned long long) hash;
 - (BOOL) isEqual:(id)a ;
 - (id) descriptionWithLocale:(id)a ;
 - (void) getObjects:(^@)a ;
 - (unsigned long long) countByEnumeratingWithState:(^{?=Q^@^Q[5Q]})a objects:(^@)b count:(unsigned long long)c ;
 - (id) initWithObjects:(r^@)a count:(unsigned long long)b ;
 - (void) enumerateObjectsWithOptions:(unsigned long long)a usingBlock:(@?)b ;
 - (id) initWithArray:(id)a copyItems:(BOOL)b ;
 - (id) initWithObject:(id)a ;
 - (id) initWithArray:(id)a ;
 - (id) indexesOfObjectsAtIndexes:(id)a options:(unsigned long long)b passingTest:(@?)c ;
 - (id) indexesOfObjectsWithOptions:(unsigned long long)a passingTest:(@?)b ;
 - (unsigned long long) indexOfObjectWithOptions:(unsigned long long)a passingTest:(@?)b ;
 - (unsigned long long) indexOfObjectAtIndexes:(id)a options:(unsigned long long)b passingTest:(@?)c ;
 - (id) objectWithOptions:(unsigned long long)a passingTest:(@?)b ;
 - (id) objectsAtIndexes:(id)a ;
 - (id) objectsWithOptions:(unsigned long long)a passingTest:(@?)b ;
 - (id) sortedArrayFromRange:({_NSRange=QQ})a options:(unsigned long long)b usingComparator:(@?)c ;
 - (id) sortedArrayWithOptions:(unsigned long long)a usingComparator:(@?)b ;
 - (id) descriptionWithLocale:(id)a indent:(unsigned long long)b ;
 - (id) initWithArray:(id)a range:({_NSRange=QQ})b copyItems:(BOOL)c ;
 - (id) initWithOrderedSet:(id)a range:({_NSRange=QQ})b copyItems:(BOOL)c ;
 - (id) initWithSet:(id)a copyItems:(BOOL)b ;
 - (id) array;
 - (id) allObjects;
 - (BOOL) containsObject:(id)a inRange:({_NSRange=QQ})b ;
 - (unsigned long long) countForObject:(id)a inRange:({_NSRange=QQ})b ;
 - (void) enumerateObjectsAtIndexes:(id)a options:(unsigned long long)b usingBlock:(@?)c ;
 - (unsigned long long) indexOfObject:(id)a inRange:({_NSRange=QQ})b ;
 - (unsigned long long) indexOfObject:(id)a ;
 - (id) lastObject;
 - (id) objectAtIndexes:(id)a options:(unsigned long long)b passingTest:(@?)c ;
 - (id) objectPassingTest:(@?)a ;
 - (id) objectsAtIndexes:(id)a options:(unsigned long long)b passingTest:(@?)c ;
 - (id) objectEnumerator;
 - (id) initWithArray:(id)a range:({_NSRange=QQ})b ;
 - (id) initWithOrderedSet:(id)a range:({_NSRange=QQ})b ;
 - (id) initWithOrderedSet:(id)a copyItems:(BOOL)b ;
 - (id) initWithOrderedSet:(id)a ;
 - (id) set;
 - (BOOL) isNSOrderedSet__;
 - (BOOL) intersectsOrderedSet:(id)a ;
 - (BOOL) isSubsetOfOrderedSet:(id)a ;
 - (BOOL) isEqualToOrderedSet:(id)a ;
 - (id) reversedOrderedSet;
 - (id) objectsPassingTest:(@?)a ;
 - (void) encodeWithCoder:(id)a ;
 - (id) initWithCoder:(id)a ;
 - (void) enumerateObjectsUsingBlock:(@?)a ;
 - (id) firstObject;
 - (id) objectAtIndexedSubscript:(unsigned long long)a ;
 - (id) reverseObjectEnumerator;
 - (id) indexesOfObjectsPassingTest:(@?)a ;
 - (unsigned long long) indexOfObjectPassingTest:(@?)a ;


@end
