
@protocol NSProgressPublisher;
@interface NSProgress : NSObject <NSProgressPublisher> {

    id _group;
    q _reserved4;
    id _values;
    id _reserved5;
    @? _cancellationHandler;
    @? _pausingHandler;
    @? _prioritizationHandler;
    Q _flags;
    id _userInfoProxy;
    @"NSString" _publisherID;
    @"NSXPCConnection" _connection;
    q _unpublishingBlockageCount;
    q _disconnectingBlockageCount;
    q _remoteObserverCount;
    @"NSMutableDictionary" _acknowledgementHandlersByBundleID;
    @"NSMutableDictionary" _lastNotificationTimesByKey;
    @"NSMutableDictionary" _userInfoLastNotificationTimesByKey;
    @"NSLock" _lock;
    @"NSMutableSet" _childrenGroups;
}
@property (nonatomic, assign, readwrite) NSNumber* installState;
@property (nonatomic, assign, readwrite) NSNumber* installPhase;
@property (atomic, assign, readwrite) NSNumber* totalUnitCount;
@property (atomic, assign, readwrite) NSNumber* completedUnitCount;
@property (atomic, copy, readwrite) NSString* localizedDescription;
@property (atomic, copy, readwrite) NSString* localizedAdditionalDescription;
@property (atomic, assign, readwrite, isCancellable) NSNumber* cancellable;
@property (atomic, assign, readwrite, isPausable) NSNumber* pausable;
@property (atomic, assign, readonly, isCancelled) NSNumber* cancelled;
@property (atomic, assign, readonly, isPaused) NSNumber* paused;
@property (atomic, copy, readwrite) NSNumber* cancellationHandler;
@property (atomic, copy, readwrite) NSNumber* pausingHandler;
@property (atomic, assign, readonly, isIndeterminate) NSNumber* indeterminate;
@property (atomic, assign, readonly) NSNumber* fractionCompleted;
@property (atomic, copy, readonly) NSDictionary* userInfo;
@property (atomic, copy, readwrite) NSString* kind;
@property (atomic, assign, readonly, isOld) NSNumber* old;
 + (id) publishingKeyForApp:(id)awithPhase:(Q)b;
 + (id) childProgressForBundleID:(id)aandPhase:(Q)b;
 + (id) keyPathsForValuesAffectingInstallState;
 + (id) keyPathsForValuesAffectingInstallPhase;
 + (id) _addSubscriberForCategory:(id)ausingPublishingHandler:(@?)b;
 + (BOOL) automaticallyNotifiesObserversForKey:(id)a;
 + (id) currentProgress;
 + (id) progressWithTotalUnitCount:(q)a;
 + (id) _registrarInterface;
 + (id) _publisherInterface;
 + (id) _addSubscriberForFileURL:(id)awithPublishingHandler:(@?)b;
 + (void) _removeSubscriber:(id)a;
 + (id) _addSubscriberForFileURL:(id)ausingBlock:(@?)b;
 + (id) keyPathsForValuesAffectingLocalizedDescription;
 + (id) keyPathsForValuesAffectingLocalizedAdditionalDescription;
 + (id) addSubscriberForFileURL:(id)awithPublishingHandler:(@?)b;
 + (void) removeSubscriber:(id)a;
 + (id) addSubscriberForFileURL:(id)ausingBlock:(@?)b;
 + (id) _subscriberInterface;

 - (void) setInstallState:(Q)a;
 - (Q) installState;
 - (id) initWithParent:(id)abundleID:(id)bandPhase:(Q)c;
 - (Q) installPhase;
 - (void) setInstallPhase:(Q)a;
 - (id) _LSDescription;
 - (void) resume;
 - (BOOL) isPaused;
 - (void) setPausable:(BOOL)a;
 - (void) setCancellable:(BOOL)a;
 - (void) setPrioritizable:(BOOL)a;
 - (void) setUserInfoObject:(id)aforKey:(id)b;
 - (BOOL) isPausable;
 - (BOOL) isCancellable;
 - (BOOL) isPrioritizable;
 - (void) setPrioritizationHandler:(@?)a;
 - (BOOL) isCancelled;
 - (BOOL) isFinished;
 - (void) setCompletedUnitCount:(q)a;
 - (void) setTotalUnitCount:(q)a;
 - (void) becomeCurrentWithPendingUnitCount:(q)a;
 - (void) resignCurrent;
 - (d) fractionCompleted;
 - (BOOL) isIndeterminate;
 - (id) initWithParent:(id)auserInfo:(id)b;
 - (void) setCancellationHandler:(@?)a;
 - (void) setPausingHandler:(@?)a;
 - (q) totalUnitCount;
 - (void) pause;
 - (void) _setCompletedUnitCount:(q)atotalUnitCount:(q)b;
 - (void) _setGroup:(id)a;
 - (Vv) prioritize;
 - (void) _updateGroup:(id)aoldFraction:(id)bnewFraction:(id)cportion:(q)d;
 - (void) _removeGroup:(id)afraction:(id)bportion:(q)c;
 - (id) _indentedDescription:(Q)a;
 - (Q) ownedDictionaryCount;
 - (id) ownedDictionaryKeyEnumerator;
 - (id) ownedDictionaryObjectForKey:(id)a;
 - (void) _addChild:(id)atoGroup:(id)bisPaused:(^B)cisCancelled:(^B)d;
 - (void) __notifyRemoteObserversOfValueForKey:(id)ainUserInfo:(BOOL)b;
 - (void) _unblockUnpublishing;
 - (void) _notifyRemoteObserversOfValueForKey:(id)ainUserInfo:(BOOL)b;
 - (void) _setValueForKeys:(@?)asettingBlock:(@?)b;
 - (void) _updateFractionCompletedFromOldFraction:(id)atoNewFraction:(id)b;
 - (void) _setUserInfoValue:(id)aforKey:(id)b;
 - (void) _publish;
 - (void) _unblockDisconnecting;
 - (void) _unpublish;
 - (void) _setAcknowledgementHandler:(@?)aforAppBundleIdentifier:(id)b;
 - (@?) _acknowledgementHandlerForAppBundleIdentifier:(id)a;
 - (Vv) startProvidingValuesWithInitialAcceptor:(@?)a;
 - (Vv) stopProvidingValues;
 - (Vv) appWithBundleID:(id)adidAcknowledgeWithSuccess:(BOOL)b;
 - (void) setLocalizedDescription:(id)a;
 - (void) setLocalizedAdditionalDescription:(id)a;
 - (id) localizedAdditionalDescription;
 - (@?) cancellationHandler;
 - (@?) pausingHandler;
 - (void) setKind:(id)a;
 - (void) publish;
 - (void) unpublish;
 - (void) setAcknowledgementHandler:(@?)aforAppBundleIdentifier:(id)b;
 - (@?) acknowledgementHandlerForAppBundleIdentifier:(id)a;
 - (void) acknowledgeWithSuccess:(BOOL)a;
 - (BOOL) isOld;
 - (id) _publishingAppBundleIdentifier;
 - (@?) prioritizationHandler;
 - (void) handleAcknowledgementByAppWithBundleIdentifier:(id)ausingBlock:(@?)b;
 - (id) _initWithValues:(id)a;
 - (void) _setRemoteValue:(id)aforKey:(id)binUserInfo:(BOOL)c;
 - (void) handleAcknowledgementByAppWithBundleIdentifer:(id)ausingBlock:(@?)b;
 - (void) acknowledge;
 - (id) description;
 - (void) dealloc;
 - (id) localizedDescription;
 - (id) userInfo;
 - (id) kind;
 - (q) completedUnitCount;
 - (id) init;
 - (void) cancel;


@end
