
@protocol NSCopying, NSMutableCopying, NSSecureCoding, NSFastEnumeration;
@interface NSSet : NSObject <NSCopying, NSMutableCopying, NSSecureCoding, NSFastEnumeration> {

}
@property (atomic, assign, readonly) NSNumber* count;
 + (BOOL) supportsSecureCoding;
 + (BOOL) supportsSecureCoding;
 + (id) setWithObject:(id)a;
 + (id) allocWithZone:(^{_NSZone=})a;
 + (id) setWithArray:(id)a;
 + (id) setWithArray:(id)arange:({_NSRange=QQ})bcopyItems:(BOOL)c;
 + (id) set;
 + (id) setWithSet:(id)a;
 + (id) setWithObjects:(r^@)acount:(Q)b;
 + (id) newSetWithObjects:(r^@)acount:(Q)b;
 + (id) setWithArray:(id)arange:({_NSRange=QQ})b;
 + (id) setWithArray:(id)acopyItems:(BOOL)b;
 + (id) setWithOrderedSet:(id)arange:({_NSRange=QQ})bcopyItems:(BOOL)c;
 + (id) setWithOrderedSet:(id)arange:({_NSRange=QQ})b;
 + (id) setWithOrderedSet:(id)acopyItems:(BOOL)b;
 + (id) setWithOrderedSet:(id)a;
 + (id) setWithSet:(id)acopyItems:(BOOL)b;
 + (id) setWithObjects:(id)a;

 - (void) encodeWithCAMLWriter:(id)a;
 - (id) CAMLType;
 - (id) replacementObjectForPortCoder:(id)a;
 - (id) filteredSetUsingPredicate:(id)a;
 - (id) sortedArrayUsingDescriptors:(id)a;
 - (Class) classForCoder;
 - (void) encodeWithCoder:(id)a;
 - (id) initWithCoder:(id)a;
 - (void) removeObserver:(id)aforKeyPath:(id)b;
 - (void) addObserver:(id)aforKeyPath:(id)boptions:(Q)ccontext:(^v)d;
 - (void) removeObserver:(id)aforKeyPath:(id)bcontext:(^v)c;
 - (id) _sumForKeyPath:(id)a;
 - (id) _avgForKeyPath:(id)a;
 - (id) _countForKeyPath:(id)a;
 - (id) _maxForKeyPath:(id)a;
 - (id) _minForKeyPath:(id)a;
 - (id) _distinctUnionOfArraysForKeyPath:(id)a;
 - (id) _distinctUnionOfObjectsForKeyPath:(id)a;
 - (id) _distinctUnionOfSetsForKeyPath:(id)a;
 - (void) setValue:(id)aforKey:(id)b;
 - (id) valueForKey:(id)a;
 - (id) valueForKeyPath:(id)a;
 - (id) initWithObjects:(id)a;
 - (id) anyObject;
 - (BOOL) intersectsSet:(id)a;
 - (BOOL) isSubsetOfSet:(id)a;
 - (id) setByAddingObject:(id)a;
 - (id) initWithSet:(id)a;
 - (id) sortedArrayUsingComparator:(@?)a;
 - (id) copyWithZone:(^{_NSZone=})a;
 - (id) mutableCopyWithZone:(^{_NSZone=})a;
 - (id) description;
 - (Q) count;
 - (void) getObjects:(^@)arange:({_NSRange=QQ})b;
 - (Q) countForObject:(id)a;
 - (BOOL) containsObject:(id)a;
 - (Q) hash;
 - (BOOL) isEqual:(id)a;
 - (id) descriptionWithLocale:(id)a;
 - (Q) _cfTypeID;
 - (id) member:(id)a;
 - (BOOL) __getValue:(^@)aforObj:(id)b;
 - (void) getObjects:(^@)a;
 - (void) __applyValues:(^?)acontext:(^v)b;
 - (Q) countByEnumeratingWithState:(^{?=Q^@^Q[5Q]})aobjects:(^@)bcount:(Q)c;
 - (id) initWithObjects:(r^@)acount:(Q)b;
 - (void) enumerateObjectsWithOptions:(Q)ausingBlock:(@?)b;
 - (id) initWithArray:(id)acopyItems:(BOOL)b;
 - (id) initWithObject:(id)a;
 - (id) initWithArray:(id)a;
 - (id) objectWithOptions:(Q)apassingTest:(@?)b;
 - (id) objectsWithOptions:(Q)apassingTest:(@?)b;
 - (id) sortedArrayWithOptions:(Q)ausingComparator:(@?)b;
 - (id) descriptionWithLocale:(id)aindent:(Q)b;
 - (id) initWithArray:(id)arange:({_NSRange=QQ})bcopyItems:(BOOL)c;
 - (id) initWithOrderedSet:(id)arange:({_NSRange=QQ})bcopyItems:(BOOL)c;
 - (void) getObjects:(^@)acount:(Q)b;
 - (id) initWithSet:(id)acopyItems:(BOOL)b;
 - (id) allObjects;
 - (id) objectPassingTest:(@?)a;
 - (id) objectEnumerator;
 - (id) initWithArray:(id)arange:({_NSRange=QQ})b;
 - (id) initWithOrderedSet:(id)arange:({_NSRange=QQ})b;
 - (id) initWithOrderedSet:(id)acopyItems:(BOOL)b;
 - (id) initWithOrderedSet:(id)a;
 - (BOOL) isNSSet__;
 - (BOOL) isEqualToSet:(id)a;
 - (BOOL) intersectsOrderedSet:(id)a;
 - (BOOL) isSubsetOfOrderedSet:(id)a;
 - (id) members:(id)anotFoundMarker:(id)b;
 - (id) objectsPassingTest:(@?)a;
 - (id) setByAddingObjectsFromArray:(id)a;
 - (id) setByAddingObjectsFromSet:(id)a;
 - (void) encodeWithCoder:(id)a;
 - (id) initWithCoder:(id)a;
 - (void) enumerateObjectsUsingBlock:(@?)a;
 - (void) makeObjectsPerformSelector:(SEL)a;
 - (void) makeObjectsPerformSelector:(SEL)awithObject:(id)b;


@end
