
@protocol NSCopying, NSMutableCopying, NSSecureCoding, NSFastEnumeration;
@interface NSSet : NSObject <NSCopying, NSMutableCopying, NSSecureCoding, NSFastEnumeration> {

}
@property (atomic, assign, readonly) NSNumber* count;
 + (BOOL) supportsSecureCoding;
 + (BOOL) supportsSecureCoding;
 + (id) setWithObject:(id)a;
 + (id) allocWithZone:(^{_NSZone=})a;
 + (id) setWithArray:(id)a;
 + (id) setWithArray:(id)arange:({_NSRange=QQ})bcopyItems:(BOOL)c;
 + (id) set;
 + (id) setWithSet:(id)a;
 + (id) setWithObjects:(r^@)acount:(unsigned long long)b;
 + (id) newSetWithObjects:(r^@)acount:(unsigned long long)b;
 + (id) setWithArray:(id)arange:({_NSRange=QQ})b;
 + (id) setWithArray:(id)acopyItems:(BOOL)b;
 + (id) setWithOrderedSet:(id)arange:({_NSRange=QQ})bcopyItems:(BOOL)c;
 + (id) setWithOrderedSet:(id)arange:({_NSRange=QQ})b;
 + (id) setWithOrderedSet:(id)acopyItems:(BOOL)b;
 + (id) setWithOrderedSet:(id)a;
 + (id) setWithSet:(id)acopyItems:(BOOL)b;
 + (id) setWithObjects:(id)a;

 - (void) encodeWithCAMLWriter:(id)a ;
 - (id) CAMLType;
 - (id) replacementObjectForPortCoder:(id)a ;
 - (id) filteredSetUsingPredicate:(id)a ;
 - (id) sortedArrayUsingDescriptors:(id)a ;
 - (Class) classForCoder;
 - (void) encodeWithCoder:(id)a ;
 - (id) initWithCoder:(id)a ;
 - (void) removeObserver:(id)a forKeyPath:(id)b ;
 - (void) addObserver:(id)a forKeyPath:(id)b options:(unsigned long long)c context:(^v)d ;
 - (void) removeObserver:(id)a forKeyPath:(id)b context:(^v)c ;
 - (id) _sumForKeyPath:(id)a ;
 - (id) _avgForKeyPath:(id)a ;
 - (id) _countForKeyPath:(id)a ;
 - (id) _maxForKeyPath:(id)a ;
 - (id) _minForKeyPath:(id)a ;
 - (id) _distinctUnionOfArraysForKeyPath:(id)a ;
 - (id) _distinctUnionOfObjectsForKeyPath:(id)a ;
 - (id) _distinctUnionOfSetsForKeyPath:(id)a ;
 - (void) setValue:(id)a forKey:(id)b ;
 - (id) valueForKey:(id)a ;
 - (id) valueForKeyPath:(id)a ;
 - (id) initWithObjects:(id)a ;
 - (id) anyObject;
 - (BOOL) intersectsSet:(id)a ;
 - (BOOL) isSubsetOfSet:(id)a ;
 - (id) setByAddingObject:(id)a ;
 - (id) initWithSet:(id)a ;
 - (id) sortedArrayUsingComparator:(@?)a ;
 - (id) copyWithZone:(^{_NSZone=})a ;
 - (id) mutableCopyWithZone:(^{_NSZone=})a ;
 - (id) description;
 - (unsigned long long) count;
 - (void) getObjects:(^@)a range:({_NSRange=QQ})b ;
 - (unsigned long long) countForObject:(id)a ;
 - (BOOL) containsObject:(id)a ;
 - (unsigned long long) hash;
 - (BOOL) isEqual:(id)a ;
 - (id) descriptionWithLocale:(id)a ;
 - (unsigned long long) _cfTypeID;
 - (id) member:(id)a ;
 - (BOOL) __getValue:(^@)a forObj:(id)b ;
 - (void) getObjects:(^@)a ;
 - (void) __applyValues:(^?)a context:(^v)b ;
 - (unsigned long long) countByEnumeratingWithState:(^{?=Q^@^Q[5Q]})a objects:(^@)b count:(unsigned long long)c ;
 - (id) initWithObjects:(r^@)a count:(unsigned long long)b ;
 - (void) enumerateObjectsWithOptions:(unsigned long long)a usingBlock:(@?)b ;
 - (id) initWithArray:(id)a copyItems:(BOOL)b ;
 - (id) initWithObject:(id)a ;
 - (id) initWithArray:(id)a ;
 - (id) objectWithOptions:(unsigned long long)a passingTest:(@?)b ;
 - (id) objectsWithOptions:(unsigned long long)a passingTest:(@?)b ;
 - (id) sortedArrayWithOptions:(unsigned long long)a usingComparator:(@?)b ;
 - (id) descriptionWithLocale:(id)a indent:(unsigned long long)b ;
 - (id) initWithArray:(id)a range:({_NSRange=QQ})b copyItems:(BOOL)c ;
 - (id) initWithOrderedSet:(id)a range:({_NSRange=QQ})b copyItems:(BOOL)c ;
 - (void) getObjects:(^@)a count:(unsigned long long)b ;
 - (id) initWithSet:(id)a copyItems:(BOOL)b ;
 - (id) allObjects;
 - (id) objectPassingTest:(@?)a ;
 - (id) objectEnumerator;
 - (id) initWithArray:(id)a range:({_NSRange=QQ})b ;
 - (id) initWithOrderedSet:(id)a range:({_NSRange=QQ})b ;
 - (id) initWithOrderedSet:(id)a copyItems:(BOOL)b ;
 - (id) initWithOrderedSet:(id)a ;
 - (BOOL) isNSSet__;
 - (BOOL) isEqualToSet:(id)a ;
 - (BOOL) intersectsOrderedSet:(id)a ;
 - (BOOL) isSubsetOfOrderedSet:(id)a ;
 - (id) members:(id)a notFoundMarker:(id)b ;
 - (id) objectsPassingTest:(@?)a ;
 - (id) setByAddingObjectsFromArray:(id)a ;
 - (id) setByAddingObjectsFromSet:(id)a ;
 - (void) encodeWithCoder:(id)a ;
 - (id) initWithCoder:(id)a ;
 - (void) enumerateObjectsUsingBlock:(@?)a ;
 - (void) makeObjectsPerformSelector:(SEL)a ;
 - (void) makeObjectsPerformSelector:(SEL)a withObject:(id)b ;


@end
