
@protocol NSCoding;
@interface UIActivityIndicatorView : UIView <NSCoding> {

    double _duration;
    BOOL _animating;
    long long _activityIndicatorViewStyle;
    long long _actualActivityIndicatorViewStyle;
    BOOL _hidesWhenStopped;
    BOOL _hasShadow;
    BOOL _clockWise;
    BOOL _spinning;
    BOOL _useArtwork;
    BOOL _useOutlineShadow;
    double _width;
    UIColor _color;
    long long _spokeCount;
    UIColor _shadowColor;
    double _innerRadius;
    long long _spokeFrameRatio;
    NSArray _spokeImages;
    double _spinningDuration;
    NSString _artBackupKeyString;
    UIImageView _internalView;
    {CGSize="width"d"height"d} _shadowOffset;
}
 + ({CGSize=dd}) size;
 + ({CGSize=dd}) defaultSizeForStyle:(long long)a;
 + (BOOL) _isModernStyle:(long long)a;
 + (id) _loadResourcesForStyle:(long long)a;

 - (void) af_startAnimating;
 - (void) af_stopAnimating;
 - (void) setAnimatingWithStateOfTask:(id)a;
 - (void) setAnimatingWithStateOfOperation:(id)a;
 - (void) dealloc;
 - (void) _populateArchivedSubviews:(id)a;
 - ({CGSize=dd}) _intrinsicSizeWithinSize:({CGSize=dd})a;
 - (BOOL) _contentHuggingDefault_isUsuallyFixedHeight;
 - (BOOL) _contentHuggingDefault_isUsuallyFixedWidth;
 - ({CGSize=dd}) sizeThatFits:({CGSize=dd})a;
 - (void) _didMoveFromWindow:(id)atoWindow:(id)b;
 - (void) _removeAllAnimations:(BOOL)a;
 - (void) setHighlighted:(BOOL)a;
 - (BOOL) isHighlighted;
 - (void) stopAnimation;
 - (BOOL) isAnimating;
 - (void) stopAnimating;
 - (void) startAnimating;
 - (void) setAnimating:(BOOL)a;
 - (long long) activityIndicatorViewStyle;
 - (void) setActivityIndicatorViewStyle:(long long)a;
 - (void) startAnimation;
 - (void) _tearDownAnimation;
 - (void) _setUpAnimation;
 - (void) setHidesWhenStopped:(BOOL)a;
 - (void) _applicationDidEnterBackground:(id)a;
 - (void) _applicationWillEnterForeground:(id)a;
 - (void) _feedTheGear;
 - (id) _defaulColorForStyle:(long long)a;
 - (id) _layoutInfosForStyle:(long long)a;
 - (BOOL) hidesWhenStopped;
 - (BOOL) _canCustomize;
 - (long long) spokeCount;
 - (long long) spokeFrameRatio;
 - (double) _spokeWidthForGearWidth:(double)a;
 - (double) _spokeLengthForGearWidth:(double)a;
 - (double) _widthForGearWidth:(double)a;
 - (double) _alphaValueForStep:(long long)a;
 - (BOOL) _isModern;
 - (id) _artBackupKey;
 - (id) _imageForStep:(long long)a;
 - (BOOL) _shouldGoToCustomStyle;
 - (long long) _customStyleForStyle:(long long)a;
 - (BOOL) _shouldGoBackToBaseStyle;
 - (BOOL) _hasCustomColor;
 - (id) _generateModernImagesForImages:(id)a;
 - (BOOL) _isArtWorkBased;
 - (id) _generateImages;
 - (void) _updateInternalViewFrameWithBounds:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - (BOOL) _canCustomizeStyle:(long long)a;
 - (id) initWithActivityIndicatorStyle:(long long)a;
 - (void) setUseOutlineShadow:(BOOL)a;
 - (void) setSpokeCount:(long long)a;
 - (void) setInnerRadius:(double)a;
 - (void) setSpokeFrameRatio:(long long)a;
 - (void) setClockWise:(BOOL)a;
 - (void) setSpinningDuration:(double)a;
 - (id) artBackupKey;
 - (id) _styleNameForStyle:(long long)a;
 - (void) generateImages;
 - (BOOL) hasShadow;
 - (void) setHasShadow:(BOOL)a;
 - (double) innerRadius;
 - (id) spokeImages;
 - (BOOL) clockWise;
 - (BOOL) spinning;
 - (void) setSpinning:(BOOL)a;
 - (double) spinningDuration;
 - (BOOL) useArtwork;
 - (void) setUseArtwork:(BOOL)a;
 - (id) artBackupKeyString;
 - (id) internalView;
 - (BOOL) useOutlineShadow;
 - (BOOL) isElementAccessibilityExposedToInterfaceBuilder;
 - (void) encodeWithCoder:(id)a;
 - (id) initWithCoder:(id)a;
 - (void) setShadowOffset:({CGSize=dd})a;
 - (void) setShadowColor:(id)a;
 - (void) _commonInit;
 - (id) initWithFrame:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - (void) setFrame:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - (void) setColor:(id)a;
 - (void) setBounds:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - (id) color;
 - ({CGSize=dd}) shadowOffset;
 - (id) shadowColor;
 - (void) setStyle:(long long)a;
 - (void) setAnimationDuration:(double)a;
 - (double) width;
 - (void) setWidth:(double)a;


@end
