
@protocol UIViewControllerRestoration, UIAlertControllerContaining, UIActivityGroupViewControllerDelegate, UIActivityGroupViewControllerDataSource, SFAirDropActivityViewControllerDelegate;
@interface UIActivityViewController : UIViewController <UIViewControllerRestoration, UIAlertControllerContaining, UIActivityGroupViewControllerDelegate, UIActivityGroupViewControllerDataSource, SFAirDropActivityViewControllerDelegate> {

    BOOL _useBlackPopoverStyle;
    BOOL _showKeyboardAutomatically;
    BOOL _allowsEmbedding;
    BOOL _willDismissActivityViewController;
    BOOL _performActivityForStateRestoration;
    BOOL _shouldMatchOnlyUserElectedExtensions;
    @? _completionHandler;
    @? _completionWithItemsHandler;
    NSArray* _excludedActivityTypes;
    UIActivity* _activity;
    NSArray* _includedActivityTypes;
    long long _excludedActivityCategories;
    NSArray* _activityTypeOrder;
    NSString* _mailAutosaveIdentifier;
    @? _preCompletionHandler;
    <UIActivityViewControllerDelegate>* _airDropDelegate;
    UIViewController* _activityViewController;
    NSArray* _activityItems;
    NSArray* _applicationActivities;
    UIAlertController* _activityAlertController;
    _UIAlertControllerShimPresenter* _activityAlertControllerShimPresenter;
    _UIActivityGroupListViewController* _activityGroupListViewController;
    UIAlertAction* _activityAlertCancelAction;
    NSOperationQueue* _activityItemProviderOperationQueue;
    long long _totalProviderCount;
    long long _completedProviderCount;
    unsigned long long _backgroundTaskIdentifier;
    long long _originalPopoverBackgroundStyle;
    Class _originalPopoverBackgroundViewClass;
    NSString* _subject;
    SFAirDropActivityViewController* _airDropViewController;
    @? __popoverDismissalAction;
    _UIActivityApplicationExtensionDiscovery* _applicationExtensionDiscovery;
}
 + (id) _activeActivityViewControllers;
 + (id) viewControllerWithRestorationIdentifierPath:(id)acoder:(id)b;
 + (id) _dataTypeIdentifierForActivityItem:(id)aactivity:(id)b;
 + (id) _itemProviderForActivityItem:(id)atypeIdentifier:(id)bactivity:(id)c;
 + (id) _subjectForActivityItem:(id)aactivity:(id)b;
 + (id) _thumbnailImageForActivityItem:(id)aactivity:(id)b;
 + (id) _attachmentNameForActivityItem:(id)aactivity:(id)b;
 + (void) _reloadImageForActivity:(id)a;
 + (void) _addActivityItem:(id)aactivityViewController:(id)boriginalActivityItem:(id)c;
 + (void) _clearActivityItems:(id)a;

 - (void) observeValueForKeyPath:(id)a ofObject:(id)b change:(id)c context:(^v)d ;
 - (void) dealloc;
 - (unsigned long long) supportedInterfaceOrientations;
 - (void) encodeRestorableStateWithCoder:(id)a ;
 - (void) decodeRestorableStateWithCoder:(id)a ;
 - (void) viewDidLayoutSubviews;
 - (@?) completionHandler;
 - (void) preferredContentSizeDidChangeForChildContentContainer:(id)a ;
 - (void) viewWillTransitionToSize:({CGSize=dd})a withTransitionCoordinator:(id)b ;
 - (void) setModalPresentationStyle:(long long)a ;
 - (void) dismissViewControllerAnimated:(BOOL)a completion:(@?)b ;
 - (BOOL) shouldAutorotateToInterfaceOrientation:(long long)a ;
 - (void) viewWillAppear:(BOOL)a ;
 - (void) _setPopoverController:(id)a ;
 - (void) viewDidLoad;
 - (void) viewDidAppear:(BOOL)a ;
 - (void) viewWillDisappear:(BOOL)a ;
 - (void) viewDidDisappear:(BOOL)a ;
 - (id) _presentationControllerForPresentedController:(id)a presentingController:(id)b sourceController:(id)c ;
 - (BOOL) _requiresCustomPresentationController;
 - (void) presentViewController:(id)a animated:(BOOL)b completion:(@?)c ;
 - (void) willRotateToInterfaceOrientation:(long long)a duration:(double)b ;
 - (void) _didResignContentViewControllerOfPopover:(id)a ;
 - (id) _containedAlertController;
 - (id) activityGroupViewController:(id)a availableActivitiesInCategory:(long long)b ;
 - (void) activityGroupViewController:(id)a didSelectActivity:(id)b ;
 - (void) setCompletionWithItemsHandler:(@?)a ;
 - (BOOL) sourceIsManaged;
 - (void) setSubject:(id)a ;
 - (void) _performActivity:(id)a ;
 - (BOOL) _shouldShowSystemActivity:(id)a ;
 - (void) _prepareActivity:(id)a ;
 - (id) activityViewController;
 - (id) activity;
 - (id) initWithActivityItems:(id)a applicationActivities:(id)b ;
 - (void) setExcludedActivityTypes:(id)a ;
 - (void) setActivityViewController:(id)a ;
 - (void) setCompletionHandler:(@?)a ;
 - (void) _cancel;
 - (id) _availableActivities;
 - (id) airDropViewController;
 - (void) setAirDropViewController:(id)a ;
 - (void) _reloadImageForActivity:(id)a ;
 - (id) activityGroupListViewController;
 - (void) setActivityItems:(id)a ;
 - (void) setApplicationActivities:(id)a ;
 - (void) _notifyReloadImageForActivity:(id)a ;
 - (void) setWillDismissActivityViewController:(BOOL)a ;
 - (void) setActivityAlertCancelAction:(id)a ;
 - (void) setActivityAlertController:(id)a ;
 - (id) activityAlertController;
 - (void) setActivityAlertControllerShimPresenter:(id)a ;
 - (id) _availableActivitiesForItems:(id)a applicationExtensionActivities:(id)b ;
 - (id) applicationExtensionDiscovery;
 - (void) setApplicationExtensionDiscovery:(id)a ;
 - (BOOL) shouldMatchOnlyUserElectedExtensions;
 - (id) _activityItemValues;
 - (void) _updateActivities:(id)a animated:(BOOL)b ;
 - (id) excludedActivityTypes;
 - (long long) excludedActivityCategories;
 - (id) includedActivityTypes;
 - (id) activityItems;
 - (id) activityTypeOrder;
 - (id) _availableActivitiesForItems:(id)a ;
 - (void) _updateActivityItems:(id)a animated:(BOOL)b ;
 - (void) setShouldMatchOnlyUserElectedExtensions:(BOOL)a ;
 - (id) _newActivityGroupViewControllerForItems:(id)a category:(long long)b userDefaults:(id)c ;
 - (BOOL) allowsEmbedding;
 - (id) activityAlertControllerShimPresenter;
 - (void) _updatePreferredContentSizes;
 - (void) _setDarkStyleOnLegacyApp;
 - (void) _removeFromActiveActivityViewControllers;
 - (void) setPreCompletionHandler:(@?)a ;
 - (BOOL) willDismissActivityViewController;
 - (void) setActivity:(id)a ;
 - (void) setActivityItemProviderOperationQueue:(id)a ;
 - (void) _cleanupActivityWithSuccess:(BOOL)a items:(id)b error:(id)c ;
 - (BOOL) performActivityForStateRestoration;
 - (void) _cleanupActivityWithSuccess:(BOOL)a ;
 - (BOOL) showKeyboardAutomatically;
 - (id) mailAutosaveIdentifier;
 - (id) subject;
 - (void) _prepareActivity:(id)a completion:(@?)b ;
 - (void) setPerformActivityForStateRestoration:(BOOL)a ;
 - (void) _addToActiveActivityViewControllers;
 - (void) set_popoverDismissalAction:(@?)a ;
 - (void) _resetAfterActivity:(BOOL)a ;
 - (void) _executeActivity;
 - (BOOL) useBlackPopoverStyle;
 - (@?) _popoverDismissalAction;
 - (id) activityItemProviderOperationQueue;
 - (id) activityAlertCancelAction;
 - (void) _changeActionButtonToDone;
 - (void) airDropActivityRequestingSharedItemsWithCompletionHandler:(@?)a ;
 - (void) airDropActivityDidSuccessfullyCompleteTransfer;
 - (void) airDropActivityDidSuccessfullyStartTransfer;
 - (void) _updateActivityItems:(id)a ;
 - (double) _displayHeight;
 - (void) _mailAutosaveWithHandler:(@?)a ;
 - (id) _titleForActivity:(id)a ;
 - (void) _performActivityOfType:(id)a ;
 - (@?) completionWithItemsHandler;
 - (void) setUseBlackPopoverStyle:(BOOL)a ;
 - (void) setShowKeyboardAutomatically:(BOOL)a ;
 - (void) setIncludedActivityTypes:(id)a ;
 - (void) setExcludedActivityCategories:(long long)a ;
 - (void) setActivityTypeOrder:(id)a ;
 - (void) setAllowsEmbedding:(BOOL)a ;
 - (void) setMailAutosaveIdentifier:(id)a ;
 - (@?) preCompletionHandler;
 - (id) airDropDelegate;
 - (void) setAirDropDelegate:(id)a ;
 - (id) applicationActivities;
 - (void) setActivityGroupListViewController:(id)a ;
 - (long long) totalProviderCount;
 - (void) setTotalProviderCount:(long long)a ;
 - (long long) completedProviderCount;
 - (void) setCompletedProviderCount:(long long)a ;
 - (long long) originalPopoverBackgroundStyle;
 - (void) setOriginalPopoverBackgroundStyle:(long long)a ;
 - (Class) originalPopoverBackgroundViewClass;
 - (void) setOriginalPopoverBackgroundViewClass:(Class)a ;
 - (void) setBackgroundTaskIdentifier:(unsigned long long)a ;
 - (unsigned long long) backgroundTaskIdentifier;


@end
