
@protocol UIPopoverControllerDelegate;
@interface UIActionSheet : UIView <UIPopoverControllerDelegate> {

    UIAlertController* _alertController;
    _UIAlertControllerShimPresenter* _presenter;
    NSMutableArray* _actions;
    long long _cancelIndex;
    long long _firstOtherButtonIndex;
    long long _destructiveButtonIndex;
    long long _actionSheetStyle;
    id _context;
    BOOL _hasPreparedAlertActions;
    BOOL _isPresented;
    BOOL _alertControllerShouldDismiss;
    BOOL _handlingAlertActionShouldDismiss;
    BOOL _dismissingAlertController;
    _UIWeakRef* _weakDelegate;
}
 + (BOOL) _isAlertControllerShimClass;
 + (Class) _popoverControllerClass;

 - (id) title;
 - (void) setTitle:(id)a ;
 - (void) dealloc;
 - (void) setDelegate:(id)a ;
 - (long long) cancelButtonIndex;
 - (void) dismissWithClickedButtonIndex:(long long)a animated:(BOOL)b ;
 - (long long) addButtonWithTitle:(id)a ;
 - (void) setCancelButtonIndex:(long long)a ;
 - (id) message;
 - (id) _titleLabel;
 - (id) subtitle;
 - (void) showInView:(id)a ;
 - (void) setSubtitle:(id)a ;
 - (void) setMessage:(id)a ;
 - (void) popoverControllerDidDismissPopover:(id)a ;
 - (void) setDefaultButtonIndex:(long long)a ;
 - (long long) firstOtherButtonIndex;
 - (void) _setFirstOtherButtonIndex:(long long)a ;
 - (void) _dismissForTappedIndex:(long long)a ;
 - (BOOL) _prepareToDismissForTappedIndex:(long long)a ;
 - (id) _preparedAlertActionAtIndex:(unsigned long long)a ;
 - (void) setWeakDelegate:(id)a ;
 - (id) weakDelegate;
 - (id) _alertController;
 - (void) _performPresentationDismissalWithClickedButtonIndex:(long long)a animated:(BOOL)b ;
 - (void) _prepareAlertActions;
 - (long long) numberOfButtons;
 - (void) _setIsPresented:(BOOL)a ;
 - (void) setBodyText:(id)a ;
 - (id) bodyText;
 - (void) setTaglineText:(id)a ;
 - (id) addButtonWithTitle:(id)a label:(id)b ;
 - (id) buttonAtIndex:(long long)a ;
 - (id) _buttonAtIndex:(long long)a ;
 - (id) buttonTitleAtIndex:(long long)a ;
 - (void) presentSheetInView:(id)a ;
 - (void) setTitleMaxLineCount:(int)a ;
 - (void) setDimView:(id)a ;
 - (void) setDimsBackground:(BOOL)a ;
 - (int) numberOfLinesInTitle;
 - (BOOL) _isSBAlert;
 - (id) _addButtonWithTitle:(id)a label:(id)b ;
 - (void) setDestructiveButtonIndex:(long long)a ;
 - (void) _didPresent;
 - (void) _showFromRect:({CGRect={CGPoint=dd}{CGSize=dd}})a inView:(id)b direction:(unsigned long long)c animated:(BOOL)d ;
 - (void) showFromBarButtonItem:(id)a animated:(BOOL)b ;
 - (void) setIndexOfSelectedButton:(long long)a ;
 - (id) initWithTitle:(id)a delegate:(id)b cancelButtonTitle:(id)c destructiveButtonTitle:(id)d otherButtonTitles:(id)e ;
 - (void) setActionSheetStyle:(long long)a ;
 - (long long) actionSheetStyle;
 - (long long) destructiveButtonIndex;
 - (void) showFromToolbar:(id)a ;
 - (void) showFromTabBar:(id)a ;
 - (void) showFromRect:({CGRect={CGPoint=dd}{CGSize=dd}})a inView:(id)b animated:(BOOL)c ;
 - (void) presentFromBarButtonItem:(id)a direction:(unsigned long long)b allowInteractionWithViews:(id)c backgroundStyle:(long long)d animated:(BOOL)e ;
 - (void) presentFromRect:({CGRect={CGPoint=dd}{CGSize=dd}})a inView:(id)b direction:(unsigned long long)c allowInteractionWithViews:(id)d backgroundStyle:(long long)e animated:(BOOL)f ;
 - (id) _relinquishPopoverController;
 - (void) presentSheetInContentView:(id)a ;
 - (void) setInPopover:(BOOL)a ;
 - (void) setUseThreeColumnsButtonsLayout:(BOOL)a ;
 - (BOOL) useThreeColumnsButtonsLayout;
 - (void) _setIndexesOfSelectedButtons:(id)a ;
 - (void) _toggleButtonSelectionAtIndex:(unsigned long long)a ;
 - (id) _indexesOfSelectedButtons;
 - (void) setSelectedButtonGlyphImage:(id)a ;
 - (void) setSelectedButtonGlyphHighlightedImage:(id)a ;
 - (void) _setAttributedTitleString:(id)a ;
 - (id) _attributedTitleString;
 - (void) _setContentView:(id)a ;
 - (id) addMediaButtonWithTitle:(id)a iconView:(id)b andTableIconView:(id)c ;
 - (id) _addMediaButtonWithTitle:(id)a iconView:(id)b andTableIconView:(id)c ;
 - (id) delegate;
 - (id) initWithFrame:({CGRect={CGPoint=dd}{CGSize=dd}})a ;
 - (void) setContext:(id)a ;
 - (id) _contentView;
 - (BOOL) isVisible;
 - (id) context;


@end
