
@protocol FBSUIApplicationWorkspaceDelegate, FBSSceneDelegate, FBSUIApplicationSystemServiceDelegate, NSUserActivityDelegate, UIActionSheetDelegate;
@interface UIApplication : UIResponder <FBSUIApplicationWorkspaceDelegate, FBSSceneDelegate, FBSUIApplicationSystemServiceDelegate, NSUserActivityDelegate, UIActionSheetDelegate> {

    <UIApplicationDelegate>* _delegate;
    NSMutableSet* _exclusiveTouchWindows;
    UIEvent* _event;
    UIEvent* _touchesEvent;
    UIEvent* _motionEvent;
    UIEvent* _remoteControlEvent;
    long long _remoteControlEventObservers;
    NSArray* _topLevelNibObjects;
    long long _networkResourcesCurrentlyLoadingCount;
    NSTimer* _hideNetworkActivityIndicatorTimer;
    UIAlertView* _editAlertView;
    UIStatusBar* _statusBar;
    long long _statusBarRequestedStyle;
    UIStatusBarWindow* _statusBarWindow;
    NSMutableArray* _observerBlocks;
    NSMutableArray* _postCommitActions;
    NSString* _mainStoryboardName;
    NSMutableArray* _tintViewDurationStack;
    NSMutableArray* _statusBarTintColorLockingControllers;
    long long _statusBarTintColorLockingCount;
    NSString* _preferredContentSizeCategory;
    {?="deactivatingReasonFlags"b11"isSuspended"b1"isSuspendedEventsOnly"b1"isLaunchedSuspended"b1"calledNonSuspendedLaunchDelegate"b1"calledSuspendedLaunchDelegate"b1"isHandlingURL"b1"statusBarShowsProgress"b1"statusBarHidden"b1"statusBarHiddenDefault"b1"statusBarHiddenVerticallyCompact"b1"blockInteractionEvents"b4"receivesMemoryWarnings"b1"showingProgress"b1"receivesPowerMessages"b1"launchEventReceived"b1"activateEventReceived"b1"systemIsAnimatingApplicationLifecycleEvent"b1"isActivating"b1"isSuspendedUnderLock"b1"shouldExitAfterSendSuspend"b1"terminating"b1"isHandlingShortCutURL"b1"idleTimerDisabled"b1"deviceOrientation"b3"delegateShouldBeReleasedUponSet"b1"delegateHandleOpenURL"b1"delegateOpenURL"b1"delegateDidReceiveMemoryWarning"b1"delegateWillTerminate"b1"delegateSignificantTimeChange"b1"delegateWillChangeInterfaceOrientation"b1"delegateDidChangeInterfaceOrientation"b1"delegateWillChangeStatusBarFrame"b1"delegateDidChangeStatusBarFrame"b1"delegateDeviceAccelerated"b1"delegateDeviceChangedOrientation"b1"delegateDidBecomeActive"b1"delegateWillResignActive"b1"delegateDidEnterBackground"b1"delegateDidEnterBackgroundWasSent"b1"delegateWillEnterForeground"b1"delegateWillSuspend"b1"delegateDidResume"b1"delegateSupportsStateRestoration"b1"delegateSupportedInterfaceOrientations"b1"delegateHandleSiriTask"b1"delegateSupportsWatchKitRequests"b1"userDefaultsSyncDisabled"b1"headsetButtonClickCount"b4"isHeadsetButtonDown"b1"isFastForwardActive"b1"isRewindActive"b1"shakeToEdit"b1"zoomInClassicMode"b1"ignoreHeadsetClicks"b1"touchRotationDisabled"b1"taskSuspendingUnsupported"b1"taskSuspendingOnLockUnsupported"b1"isUnitTests"b1"requiresHighResolution"b1"singleUseLaunchOrientation"b3"defaultInterfaceOrientation"b3"supportedInterfaceOrientationsMask"b5"delegateWantsNextResponder"b1"isRunningInApplicationSwitcher"b1"isSendingEventForProgrammaticTouchCancellation"b1"delegateWantsStatusBarTouchesEnded"b1"interfaceLayoutDirectionIsValid"b1"interfaceLayoutDirection"b3"restorationExtended"b1"normalRestorationInProgress"b1"normalRestorationCompleted"b1"isDelayingTintViewChange"b1"isUpdatingTintViewColor"b1"isHandlingMemoryWarning"b1"forceStatusBarTintColorChanges"b1"disableLegacyAutorotation"b1"isFakingForegroundTransitionForBackgroundFetch"b1"couldNotRestoreStateWhenLocked"b1"disableStyleOverrides"b1"legibilityAccessibilitySettingEnabled"b1"viewControllerBasedStatusBarAppearance"b1"fakingRequiresHighResolution"b1"isStatusBarFading"b1"systemWindowsSecure"b1} _applicationFlags;
    UIColor* _defaultTopNavBarTintColor;
    long long _undoButtonIndex;
    long long _redoButtonIndex;
    UIMoveEvent* _moveEvent;
    UIPhysicalButtonsEvent* _physicalButtonsEvent;
    UIWheelEvent* _wheelEvent;
    NSMutableDictionary* _physicalButtonMap;
    UIPhysicalKeyboardEvent* _physicalKeyboardEvent;
    BOOL _alwaysHitTestsForMainScreen;
    UIWindow* _backgroundHitTestWindow;
    NSMutableArray* _eventQueue;
    ^{__CFDictionary=} _childEventMap;
    long long _disableTouchCoalescingCount;
    long long _classicMode;
    NSMutableSet* _actionsPendingInitialization;
    NSMutableSet* _idleTimerDisabledReasons;
    double _currentTimestampWhenFirstTouchCameDown;
    {CGPoint="x"d"y"d} _currentLocationWhereFirstTouchCameDown;
    NSString* _currentActivityUUID;
    NSString* _currentActivityType;
    UIApplicationSceneSettingsDiffInspector* _sceneSettingsDiffInspector;
    BOOL _saveStateRestorationArchiveWithFileProtectionCompleteUntilFirstUserAuthentication;
    int _simulatorShakeNotificationToken;
    double _lastTimestampWhenFirstTouchCameDown;
    double _lastTimestampWhenAllTouchesLifted;
    long long _virtualHorizontalSizeClass;
    long long _virtualVerticalSizeClass;
    long long __expectedViewOrientation;
    NSString* _preferredContentSizeCategoryName;
    {CGPoint="x"d"y"d} _lastLocationWhereFirstTouchCameDown;
    {CGPoint="x"d"y"d} _lastLocationWhereAllTouchesLifted;
    {CGSize="width"d"height"d} _virtualWindowSizeInSceneReferenceSpace;
}
 + (BOOL) registerAsSystemApp;
 + (BOOL) rendersLocally;
 + (BOOL) shouldBackgroundMainThreadOnSuspendedLaunch;
 + (void) _startWindowServerIfNecessary;
 + (void) _startStatusBarServerIfNecessary;
 + (Class) _statusBarClass;
 + (Class) _statusBarWindowClass;
 + (long long) statusBarStyleForString:(id)a;
 + (long long) _backgroundStyleForString:(id)a;
 + (BOOL) _isBackgroundStyleTransparent:(long long)a;
 + (long long) interfaceOrientationForString:(id)a;
 + (BOOL) isRunningInStoreDemoMode;
 + (long long) runningInStoreDemoModeFProgramNumber;
 + (BOOL) shouldMakeUIForDefaultPNG;
 + (void) _noteInterfaceOrientationChangingTo:(long long)a;
 + (void) _installAfterCACommitHandler;
 + (BOOL) _isAfterCACommitHandlerInstalled;
 + (BOOL) isRunningEventPump;
 + (id) stringForStatusBarStyle:(long long)a;
 + (id) stringForInterfaceOrientation:(long long)a;
 + (void) registerObjectForStateRestoration:(id)arestorationIdentifier:(id)b;
 + (id) sharedApplication;
 + (id) _defaultContentSizeCategory;

 - (void) ql_setStatusBarHiddenWithoutChangingApplicationFlag:(BOOL)awithAnimation:(long long)b;
 - (BOOL) isSuspendedForAnyReason;
 - (BOOL) isNetworkActivityIndicatorVisible;
 - (id) userHomeDirectory;
 - (void) userActivityWillSave:(id)a;
 - (void) dealloc;
 - (void) setDelegate:(id)a;
 - (long long) statusBarOrientation;
 - (long long) alertInterfaceOrientation;
 - (void) startedTest:(id)a;
 - (void) finishedTest:(id)a;
 - (id) _touchesEvent;
 - (long long) _frontMostAppOrientation;
 - (long long) _statusBarOrientationForWindow:(id)a;
 - (BOOL) isStatusBarHidden;
 - (double) statusBarHeight;
 - (id) statusBar;
 - (void) setApplicationSupportsShakeToEdit:(BOOL)a;
 - (void) _deactivateForReason:(int)anotify:(BOOL)b;
 - (void) _fetchInfoPlistFlags;
 - (void) _setTextLegibilityEnabled:(BOOL)a;
 - (void) _sendMotionBegan:(long long)a;
 - (void) _sendMotionEnded:(long long)a;
 - (id) _mainScene;
 - (void) setIdleTimerDisabled:(BOOL)a;
 - (void) _setIdleTimerDisabled:(BOOL)aforReason:(id)b;
 - (BOOL) isFrontBoard;
 - (id) _mainSceneForDisplay:(id)a;
 - (id) _mainStoryboardName;
 - (BOOL) _doRestorationIfNecessary;
 - (void) applicationWillSuspend;
 - (id) keyWindow;
 - (id) _getActivityContinuationDictionaryIfPresent:(id)a;
 - (void) _setHandlingURL:(BOOL)aurl:(id)b;
 - (BOOL) _handleDelegateCallbacksWithOptions:(id)aisSuspended:(BOOL)brestoreState:(BOOL)c;
 - (BOOL) _hasStoryboard;
 - (void) _applicationOpenURL:(id)apayload:(id)b;
 - (void) _applicationHandleSiriTask:(id)a;
 - (void) _applicationHandleWatchKitRequest:(id)a;
 - (void) _handleActivityContinuation:(id)a;
 - (void) _handleNonLaunchSpecificActions:(id)aforScene:(id)bwithTransitionContext:(id)c;
 - (void) _checkActivityContinuationAndBecomeCurrentIfNeeded;
 - (void) _registerForUserDefaultsChanges;
 - (void) _registerForSignificantTimeChangeNotification;
 - (void) _registerForLanguageChangedNotification;
 - (void) _registerForLocaleWillChangeNotification;
 - (void) _registerForLocaleChangedNotification;
 - (void) _registerForAlertItemStateChangeNotification;
 - (void) _registerForKeyBagLockStatusNotification;
 - (void) _registerForNameLayerTreeNotification;
 - (void) _registerForPreferredContentSizeChangedNotification;
 - (void) _registerForLegibilitySettingChangedNotification;
 - (void) _registerForBackgroundRefreshStatusChangedNotification;
 - (void) _installEventRunLoopSource;
 - (void) __completeAndRunAsPlugin;
 - (BOOL) _hasCalledRunWithMainScene;
 - (void) _setSuspended:(BOOL)a;
 - (void) _setShouldZoom:(BOOL)a;
 - (void) _runWithMainScene:(id)atransitionContext:(id)bcompletion:(@?)c;
 - (void) _handleApplicationLaunchEventWithCompletion:(@?)a;
 - (void) _handleApplicationDectivationWithScene:(id)ashouldForceExit:(BOOL)btransitionContext:(id)ccompletion:(@?)d;
 - (void) _handleApplicationLifecycleEventWithScene:(id)atransitionContext:(id)bcompletion:(@?)c;
 - (id) _extendLaunchTest;
 - (id) _currentTests;
 - (void) finishedTest:(id)aextraResults:(id)b;
 - (BOOL) _legacyAutorotationIsDisabled;
 - (id) displayIdentifier;
 - (long long) statusBarStyle;
 - (void) _setSuspendedEventsOnly:(BOOL)a;
 - (void) _setSuspendedUnderLock:(BOOL)a;
 - (BOOL) systemIsAnimatingApplicationLifecycleEvent;
 - (BOOL) _supportedInterfaceOrientationsIsEnabled;
 - (BOOL) _applicationLaunchesIntoPortrait;
 - (void) _createStatusBarWithRequestedStyle:(long long)aorientation:(long long)bhidden:(BOOL)c;
 - (void) _notifySpringBoardOfStatusBarOrientationChangeAndFenceWithAnimationDuration:(double)a;
 - (void) setReceivesMemoryWarnings:(BOOL)a;
 - (int) _loadMainInterfaceFile;
 - (void) _checkBackgroundRefreshAPIAdoption;
 - (void) _reportMainSceneUpdateFinished:(@?)a;
 - (BOOL) _isSpringBoardShowingAnAlert;
 - (void) _callInitializationDelegatesForMainScene:(id)atransitionContext:(id)b;
 - (void) _deactivateForReason:(int)a;
 - (void) _stopDeactivatingForReason:(int)a;
 - (void) _fixupBackgroundHitTestWindow;
 - (BOOL) _saveSnapshotWithName:(id)a;
 - (int) _loadMainStoryboardFileNamed:(id)abundle:(id)b;
 - (int) _loadMainNibFileNamed:(id)abundle:(id)b;
 - (void) _setDelegate:(id)aassumeOwnership:(BOOL)b;
 - (void) _run;
 - (unsigned long long) beginBackgroundTaskWithExpirationHandler:(@?)a;
 - (void) pushRunLoopMode:(id)arequester:(id)b;
 - (id) userInfoDictionaryForRunLoopMode:(id)arequester:(id)b;
 - (void) popRunLoopMode:(id)arequester:(id)b;
 - (BOOL) sendAction:(SEL)ato:(id)bfrom:(id)cforEvent:(id)d;
 - (id) _targetInChainForAction:(SEL)asender:(id)b;
 - (void) _setStatusBarShowsProgress:(BOOL)a;
 - (BOOL) _isStatusBarHiddenForOrientation:(long long)a;
 - (BOOL) _isSpringBoard;
 - (id) _statusBarControllingWindow;
 - (BOOL) _alwaysHitTestsForMainScreen;
 - (id) _implicitStatusBarAnimationParametersWithClass:(Class)a;
 - (id) _implicitStatusBarStyleAnimationParametersWithViewController:(id)a;
 - (void) _setStatusBarStyle:(long long)aanimationParameters:(id)b;
 - (id) _implicitStatusBarHiddenAnimationParametersWithViewController:(id)aanimation:(long long)b;
 - (void) _setStatusBarHidden:(BOOL)aanimationParameters:(id)bchangeApplicationFlag:(BOOL)c;
 - (void) setStatusBarStyle:(long long)aanimationParameters:(id)b;
 - (void) setStatusBarStyle:(long long)a;
 - (BOOL) _supportsCompactStatusBarHiding;
 - (BOOL) _isOrientationVerticallyCompact:(long long)a;
 - (void) setStatusBarHidden:(BOOL)aanimationParameters:(id)b;
 - (double) statusBarHeightForOrientation:(long long)a;
 - (void) setStatusBarHidden:(BOOL)a;
 - (void) setStatusBarHidden:(BOOL)aanimationParameters:(id)bchangeApplicationFlag:(BOOL)c;
 - (void) setStatusBarHidden:(BOOL)aduration:(double)bchangeApplicationFlag:(BOOL)c;
 - (void) setStatusBarHidden:(BOOL)awithAnimation:(long long)b;
 - (void) setStatusBarOrientation:(long long)aanimationParameters:(id)b;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) statusBarFrameForOrientation:(long long)a;
 - (void) _notifyWillChangeStatusBarFrame:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - (void) _notifyDidChangeStatusBarFrame:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - (void) setStatusBarOrientation:(long long)aanimationParameters:(id)bnotifySpringBoardAndFence:(BOOL)c;
 - (BOOL) _isAutorotationDisabledForAppWindows;
 - (void) _setStatusBarOrientation:(long long)aanimated:(BOOL)b;
 - (unsigned long long) supportedInterfaceOrientationsForWindow:(id)a;
 - (void) removeStatusBarStyleOverrides:(int)a;
 - (void) addStatusBarStyleOverrides:(int)a;
 - (void) setGlowAnimationEnabled:(BOOL)aforStyle:(long long)b;
 - (void) setDoubleHeightMode:(int)aglowAnimationEnabled:(BOOL)b;
 - (void) _updateCurrentTintViewForWindow:(id)a;
 - (BOOL) _isStatusBarTintColorLocked;
 - (id) _currentTintViewWindow;
 - (double) _currentTintViewDuration;
 - (void) _setTopNavBarTintColor:(id)awithDuration:(double)b;
 - (BOOL) _shouldTintStatusBar;
 - (void) _updateCurrentTintViewColor;
 - (BOOL) _hasStatusBarTintColorLockingController;
 - (void) applicationWillSuspendForEventsOnly;
 - (void) applicationDidResumeForEventsOnly;
 - (void) applicationWillSuspendUnderLock;
 - (void) applicationDidResumeFromUnderLock;
 - (void) suspendReturningToLastApp:(BOOL)a;
 - (void) _postSimpleRemoteNotificationForAction:(long long)aandContext:(long long)btrackID:(id)c;
 - (void) _sendMoveEventWithPhysicalButtonsEvent:(id)a;
 - (void) _physicalButtonsBegan:(id)awithEvent:(id)b;
 - (void) _finishButtonEvent:(id)a;
 - (void) _sendButtonEventWithType:(long long)aphase:(long long)btimestamp:(double)c;
 - (void) _physicalButtonsEnded:(id)awithEvent:(id)b;
 - (void) _physicalButtonsCancelled:(id)awithEvent:(id)b;
 - (void) _handleHeadsetButtonClick;
 - (void) _handleHeadsetButtonDoubleClick;
 - (void) _handleHeadsetButtonTripleClick;
 - (void) _sendHeadsetOriginatedMediaRemoteCommand:(unsigned int)a;
 - (BOOL) _shouldIgnoreHeadsetClicks;
 - (void) proximityStateChanged:(BOOL)a;
 - (void) setProximityEventsEnabled:(BOOL)a;
 - (id) _snapshotContextWithName:(id)ascreen:(id)b;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) applicationSnapshotRectForScreen:(id)aorientation:(long long)b;
 - (id) _sceneIDForScreen:(id)a;
 - (BOOL) reportApplicationSuspended;
 - (void) applicationWillTerminate;
 - (void) _terminateWithStatus:(int)a;
 - (double) defaultImageSnapshotExpiration;
 - (BOOL) isSuspendedUnderLock;
 - (void) _applicationDidEnterBackground;
 - (void) _saveApplicationPreservationStateIfSupported;
 - (BOOL) _updateDefaultImage;
 - (id) nameOfDefaultImageToUpdateAtSuspension;
 - (void) _cancelAllInputs;
 - (void) applicationSuspend;
 - (void) _purgeSharedInstances;
 - (void) _destroyContextsAndNotifySpringBoard;
 - (BOOL) isRunningQuitTest;
 - (BOOL) isRunningSuspendTest;
 - (BOOL) _isActivated;
 - (void) _setCompatibilityModeOnSettings:(id)a;
 - (void) _sendOrderedOutContextsAndInvalidate:(BOOL)a;
 - (id) _applicationProxyForURLScheme:(id)apublicURLsOnly:(BOOL)b;
 - (BOOL) openURL:(id)a;
 - (BOOL) _canOpenURL:(id)apublicURLsOnly:(BOOL)b;
 - (void) applicationOpenToShortCut:(id)a;
 - (void) applicationOpenURL:(id)a;
 - (void) _syncWithBackgroundTaskQueue;
 - (BOOL) _shouldZoom;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) applicationSnapshotRectForOrientation:(long long)a;
 - (void) prepareForDefaultImageSnapshot;
 - (BOOL) removeDefaultImage:(id)aforScreen:(id)b;
 - (id) userCachesDirectory;
 - (void) addStatusBarItem:(int)a;
 - (void) addStatusBarImageNamed:(id)a;
 - (void) removeStatusBarItem:(int)a;
 - (id) currentUserNotificationSettings;
 - (void) registerUserNotificationSettings:(id)a;
 - (void) _setClassicMode:(long long)a;
 - (BOOL) _shouldUseHiResForClassic;
 - (void) _setAlwaysHitTestsForMainScreen:(BOOL)a;
 - (id) _motionEvent;
 - (id) _remoteControlEvent;
 - (id) _motionKeyWindow;
 - (BOOL) _needsShakesWhenInactive;
 - (void) _showEditAlertViewWithUndoManager:(id)awindow:(id)b;
 - (BOOL) applicationSupportsShakeToEdit;
 - (void) _showEditAlertView;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) statusBarFrame;
 - (long long) activeInterfaceOrientation;
 - (void) setStatusBarMode:(int)ainterfaceOrientation:(long long)bduration:(float)cfenceID:(int)danimation:(int)estartTime:(double)f;
 - (void) setStatusBarOrientation:(long long)aanimation:(int)bduration:(double)c;
 - (void) setStatusBarStyle:(long long)aduration:(double)b;
 - (void) setStatusBarMode:(int)ainterfaceOrientation:(long long)bduration:(float)cfenceID:(int)danimation:(int)e;
 - (void) setStatusBarMode:(int)ainterfaceOrientation:(long long)bduration:(float)cfenceID:(int)d;
 - (void) setStatusBarMode:(int)ainterfaceOrientation:(long long)bduration:(float)c;
 - (BOOL) _hasApplicationCalledLaunchDelegate;
 - (void) beginIgnoringInteractionEvents;
 - (void) endIgnoringInteractionEvents;
 - (void) _handleUserDefaultsDidChange:(id)a;
 - (void) userDefaultsDidChange:(id)a;
 - (void) setSystemVolumeHUDEnabled:(BOOL)aforAudioCategory:(id)b;
 - (void) didReceiveMemoryWarning;
 - (void) _performMemoryWarning;
 - (void) _receivedMemoryNotification;
 - (void) _playbackTimerCallback:(id)a;
 - (void) _startPlaybackTimer;
 - (BOOL) _prepareButtonEvent:(id)atype:(long long)bphase:(long long)ctimestamp:(double)d;
 - (id) _physicalButtonForType:(long long)a;
 - (void) _setPhysicalButton:(id)aforType:(long long)b;
 - (id) _keyWindowForScreen:(id)a;
 - (id) _gestureRecognizersForResponder:(id)a;
 - (id) _physicalButtonsEvent;
 - (void) _cancelTouches:(id)awithEvent:(id)b;
 - (void) _cancelGestureRecognizers:(id)a;
 - (void) _cancelTouches:(id)awithEvent:(id)bincludingGestures:(BOOL)cnotificationBlock:(@?)d;
 - (void) _cancelAllTouches;
 - (BOOL) _shouldHandleTestURL:(id)a;
 - (BOOL) handleTestURL:(id)a;
 - (void) _updateSnapshotAndStateRestorationArchiveForBackgroundEvent:(@?)asaveState:(BOOL)bexitIfCouldNotRestoreState:(BOOL)c;
 - (void) _setVirtualWindowSizeInSceneReferenceSpace:({CGSize=dd})avirtualHorizontalSizeClass:(long long)bvirtualVerticalSizeClass:(long long)c;
 - (void) terminateWithSuccess;
 - (BOOL) isSuspendedEventsOnly;
 - (void) _userActivityWillSave:(id)a;
 - (void) _cleanupUserActivity:(id)aactivityIdentifier:(id)b;
 - (void) _addResponder:(id)adocument:(id)bforUserActivity:(id)c;
 - (void) _removeResponder:(id)adocument:(id)bforUserActivity:(id)c;
 - (BOOL) _callDelegateWillContinueActivityWithType:(id)a;
 - (BOOL) _callContinueUserActivity:(id)a;
 - (void) _handleApplicationActivationWithScene:(id)atransitionContext:(id)bcompletion:(@?)c;
 - (BOOL) _isLaunchedSuspended;
 - (void) _sendWillEnterForegroundCallbacks;
 - (void) applicationDidResume;
 - (BOOL) handleEvent:(^{__GSEvent=})awithNewEvent:(id)b;
 - (BOOL) _handlePhysicalButtonEvent:(id)a;
 - (void) applicationDidEndResumeAnimation;
 - (void) _updateOrientation;
 - (void) applicationDidBeginSuspendAnimation;
 - (void) handleKeyEvent:(^{__GSEvent=})a;
 - (void) lockDevice:(^{__GSEvent=})a;
 - (void) _dumpUIHierarchy:(^{__GSEvent=})a;
 - (void) _dumpScreenContents:(^{__GSEvent=})a;
 - (void) _processScriptEvent:(^{__GSEvent=})a;
 - (void) vibrateForDuration:(int)a;
 - (void) setBacklightLevel:(float)a;
 - (void) acceleratedInX:(float)aY:(float)bZ:(float)c;
 - (void) _handleUnicodeEvent:(^{__IOHIDEvent=})a;
 - (^{__GSKeyboard=}) GSKeyboardForHWLayout:(id)aforceRebuild:(BOOL)b;
 - (void) handleKeyUIEvent:(id)a;
 - (void) _handleKeyUIEvent:(id)a;
 - (BOOL) sendAction:(SEL)atoTarget:(id)bfromSender:(id)cforEvent:(id)d;
 - (long long) _physicalButtonTypeForKeyCode:(long long)a;
 - (void) _sendPhysicalButtonEventWithKeyboardEvent:(id)a;
 - (void) _handleKeyEvent:(^{__GSEvent=})a;
 - (void) _sendMoveEventWithDirection:(long long)aheading:(unsigned long long)bfromEvent:(id)c;
 - (void) _wheelChangedWithEvent:(id)a;
 - (id) _rootViewControllers;
 - (void) setExpectsFaceContact:(BOOL)ainLandscape:(BOOL)b;
 - (void) _setBackgroundStyle:(long long)a;
 - (void) registerForRemoteNotifications;
 - (BOOL) isRegisteredForRemoteNotifications;
 - (void) unregisterForRemoteNotifications;
 - (void) scheduleLocalNotification:(id)a;
 - (long long) applicationIconBadgeNumber;
 - (void) validateNotification:(id)a;
 - (void) cancelLocalNotification:(id)a;
 - (void) cancelAllLocalNotifications;
 - (void) setScheduledLocalNotifications:(id)a;
 - (id) scheduledLocalNotifications;
 - (void) setNetworkActivityIndicatorVisible:(BOOL)a;
 - (void) _hideNetworkActivityIndicator;
 - (id) _backgroundModes;
 - (id) statusBarWindow;
 - (void) _setPreferredContentSizeCategory:(id)a;
 - (void) _setShouldFixMainThreadPriority:(BOOL)a;
 - (void) _setLastTimestampWhenFirstTouchCameDown:(double)a;
 - (void) _setLastLocationWhereFirstTouchCameDown:({CGPoint=dd})a;
 - (id) _launchTestName;
 - (void) _setAmbiguousControlCenterActivationMargin:(double)a;
 - (BOOL) shouldLaunchSafe;
 - (BOOL) isIgnoringInteractionEvents;
 - (id) idleTimerDisabledReasons;
 - (BOOL) isIdleTimerDisabled;
 - (BOOL) _isNormalRestorationInProgress;
 - (BOOL) _isRestorationExtended;
 - (void) _setRestorationExtended:(BOOL)a;
 - (BOOL) _hasNormalRestorationCompleted;
 - (id) _workspace;
 - (id) _newSceneForWindow:(id)aoldDisplay:(id)bnewDisplay:(id)c;
 - (void) _addAfterCACommitBlockForViewController:(id)a;
 - (void) _performBlockAfterCATransactionCommits:(@?)a;
 - (double) _execOrResumeTime;
 - (double) _launchTime;
 - (long long) _currentExpectedInterfaceOrientation;
 - (void) _unregisterForSignificantTimeChangeNotification;
 - (void) _unregisterForLanguageChangedNotification;
 - (void) _unregisterForLocaleChangedNotification;
 - (void) _unregisterForTimeChangedNotification;
 - (void) pushRunLoopMode:(id)a;
 - (void) popRunLoopMode:(id)a;
 - (BOOL) handleDoubleHeightStatusBarTap:(long long)a;
 - (void) performDisablingStatusBarStyleValidation:(@?)a;
 - (void) _updateCurrentStatusBarViewControllerAppearance;
 - (void) setStatusBarStyle:(long long)aanimation:(int)bstartTime:(double)cduration:(double)dcurve:(long long)e;
 - (void) setStatusBarStyle:(long long)aanimation:(int)b;
 - (void) setStatusBarStyle:(long long)aanimated:(BOOL)b;
 - (BOOL) _isInStatusBarFadeAnimation;
 - (void) setStatusBarHidden:(BOOL)aduration:(double)b;
 - (void) setStatusBarOrientation:(long long)aanimated:(BOOL)b;
 - (void) setStatusBarOrientation:(long long)a;
 - (BOOL) _statusBarOrientationFollowsWindow:(id)a;
 - (void) _setSupportedInterfaceOrientationsIsEnabled:(BOOL)a;
 - (unsigned long long) _supportedInterfaceOrientationsForWindow:(id)a;
 - (double) statusBarOrientationAnimationDuration;
 - (void) setDoubleHeightStatusText:(id)aforStyle:(long long)b;
 - (void) setDoubleHeightMode:(int)a;
 - (int) doubleHeightMode;
 - (void) setDoubleHeightPrefixText:(id)a;
 - (void) setDoubleHeightStatusText:(id)a;
 - (id) _defaultTopNavBarTintColor;
 - (void) _setDefaultTopNavBarTintColor:(id)a;
 - (void) _pushTintViewDuration:(double)a;
 - (void) _popTintViewDuration;
 - (void) _pushStatusBarTintColorLock;
 - (void) _popStatusBarTintColorLock;
 - (void) _addViewControllerForLockingStatusBarTintColor:(id)a;
 - (void) _removeViewControllerForLockingStatusBarTintColor:(id)a;
 - (BOOL) isRunningInTaskSwitcher;
 - (BOOL) _isActivating;
 - (unsigned int) _frontmostApplicationPort;
 - (void) mediaKeyDown:(^{__GSEvent=})a;
 - (void) mediaKeyUp:(^{__GSEvent=})a;
 - (void) lockButtonDown:(^{__GSEvent=})a;
 - (void) lockButtonUp:(^{__GSEvent=})a;
 - (void) headsetButtonDown:(^{__GSEvent=})a;
 - (void) headsetButtonUp:(^{__GSEvent=})a;
 - (void) headsetAvailabilityChanged:(^{__GSEvent=})a;
 - (void) menuButtonDown:(^{__GSEvent=})a;
 - (void) menuButtonUp:(^{__GSEvent=})a;
 - (void) _scrollsToTopInitiatorView:(id)atouchesEnded:(id)bwithEvent:(id)c;
 - (void) ringerChanged:(int)a;
 - (void) setWantsVolumeButtonEvents:(BOOL)a;
 - (void) setWantsLockEvents:(BOOL)a;
 - (void) volumeChanged:(^{__GSEvent=})a;
 - (void) accessoryKeyStateChanged:(^{__GSEvent=})a;
 - (void) resetIdleTimerAndUndim;
 - (void) _postSimpleRemoteNotificationForAction:(long long)aandContext:(long long)b;
 - (void) _headsetButtonDown:(^{__IOHIDEvent=})a;
 - (void) _headsetButtonUp:(^{__IOHIDEvent=})a;
 - (void) _mainSceneCompatibilityModeZoomDidChange;
 - (void) updateSuspendedSettings:(id)a;
 - (BOOL) canOpenURL:(id)a;
 - (BOOL) isHandlingOpenShortCut;
 - (BOOL) isHandlingURL;
 - (void) showTTYPromptForNumber:(id)awithID:(int)b;
 - (void) showNetworkPromptsIfNecessary:(BOOL)a;
 - (void) setUsesBackgroundNetwork:(BOOL)a;
 - (BOOL) usesBackgroundNetwork;
 - (id) userLibraryDirectory;
 - (id) _localCachesDirectory;
 - (^{CGImage=}) _createDefaultImageSnapshotForScreen:(id)a;
 - (id) pathToDefaultImageNamed:(id)aforScreen:(id)b;
 - (void) prepareForDefaultImageSnapshotForScreen:(id)a;
 - (BOOL) removeDefaultImage:(id)a;
 - (BOOL) _isInteractionEvent:(^{__GSEvent=})a;
 - (BOOL) _isMotionEvent:(^{__GSEvent=})a;
 - (BOOL) launchApplicationWithIdentifier:(id)asuspended:(BOOL)b;
 - (void) setNewsstandIconImage:(id)a;
 - (void) addStatusBarImageNamed:(id)aremoveOnExit:(BOOL)b;
 - (void) removeStatusBarImageNamed:(id)a;
 - (void) addStatusBarItem:(int)aremoveOnExit:(BOOL)b;
 - (void) setApplicationBadgeString:(id)a;
 - (void) setApplicationIconBadgeNumber:(long long)a;
 - (BOOL) isProtectedDataAvailable;
 - (long long) userInterfaceLayoutDirection;
 - (void) addWebClipToHomeScreen:(id)a;
 - (BOOL) homeScreenCanAddIcons;
 - (long long) _classicMode;
 - (void) _overrideDefaultInterfaceOrientationWithOrientation:(long long)a;
 - (void) _removeDefaultInterfaceOrientatationOverride;
 - (int) statusBarMode;
 - (void) _setStatusBarMode:(int)a;
 - (id) _event;
 - (id) _moveEvent;
 - (id) _wheelEvent;
 - (id) _physicalKeyboardEvent;
 - (void) _sendMotionCancelled:(long long)a;
 - (void) _sendRemoteControlEvent:(long long)a;
 - (void) alertView:(id)aclickedButtonAtIndex:(long long)b;
 - (void) alertView:(id)adidDismissWithButtonIndex:(long long)b;
 - (void) alertViewCancel:(id)a;
 - (BOOL) _alertWindowShouldRotate;
 - (void) motionEnded:(long long)awithEvent:(id)b;
 - (id) _exclusiveTouchWindows;
 - (void) _setRotationDisabledDuringTouch:(BOOL)a;
 - (BOOL) _rotationDisabledDuringTouch;
 - (BOOL) _isTrackingAnyTouch;
 - (void) _setUserDefaultsSyncEnabled:(BOOL)a;
 - (long long) statusBar:(id)astyleForRequestedStyle:(long long)boverrides:(int)c;
 - (void) statusBar:(id)awillAnimateFromHeight:(double)btoHeight:(double)cduration:(double)danimation:(int)e;
 - (void) statusBar:(id)adidAnimateFromHeight:(double)btoHeight:(double)canimation:(int)d;
 - (double) statusBarHeightForOrientation:(long long)aignoreHidden:(BOOL)b;
 - (void) noteActiveInterfaceOrientationWillChangeToOrientation:(long long)a;
 - (void) noteActiveInterfaceOrientationDidChangeToOrientation:(long long)awillAnimateWithSettings:(id)bfromOrientation:(long long)c;
 - (long long) _getSpringBoardOrientation;
 - (void) setStatusBarMode:(int)aduration:(float)b;
 - (double) windowRotationDuration;
 - (void) setStatusBarShowsProgress:(BOOL)a;
 - (BOOL) _usesEmoji;
 - (void) setIgnoresInteractionEvents:(BOOL)a;
 - (BOOL) ignoresInteractionEvents;
 - (unsigned long long) blockInteractionEventsCount;
 - (void) significantTimeChange;
 - (void) batteryStatusDidChange:(id)a;
 - (void) _clearTouchesForView:(id)a;
 - (void) _cancelCurrentTouchEvent;
 - (void) _unregisterForUserDefaultsChanges;
 - (BOOL) _isSensitiveUIEnabled;
 - (BOOL) _overridesDynamicCaret;
 - (float) backlightLevel;
 - (void) setSuspensionAnimationDelay:(double)a;
 - (void) setSystemVolumeHUDEnabled:(BOOL)a;
 - (BOOL) _isHandlingMemoryWarning;
 - (void) _stopPlayback;
 - (void) _addRecorder:(id)a;
 - (void) _removeRecorder:(id)a;
 - (void) _playbackEvents:(id)aatPlaybackRate:(float)bmessageWhenDone:(id)cwithSelector:(SEL)d;
 - (void) _eatCurrentTouch;
 - (BOOL) _didEatCurrentTouch;
 - (BOOL) _shouldDelayTouchesForControlCenter;
 - (BOOL) _shouldDisableTouchCoalescing;
 - (void) _disableTouchCoalescingWithCount:(long long)a;
 - (void) _enableTouchCoalescingWithCount:(long long)a;
 - (void) _cancelPhysicalButtonsWithType:(long long)a;
 - (void) _cancelGestureRecognizersForView:(id)a;
 - (void) _cancelViewProcessingOfTouches:(id)awithEvent:(id)bsendingTouchesCancelledToViewsOfTouches:(id)c;
 - (BOOL) _isSendingEventForProgrammaticTouchCancellation;
 - (void) _cancelUnfinishedTouchesForEvent:(id)a;
 - (void) _updateSnapshotForBackgroundApplication:(BOOL)a;
 - (void) _setReachabilitySupported:(BOOL)a;
 - (void) _deactivateReachability;
 - (BOOL) _activityContinuationsAreBeingTracked;
 - (void) _findBestActivityToMakeCurrent:(id)a;
 - (void) _addResponder:(id)aforUserActivity:(id)b;
 - (void) _removeResponder:(id)aforUserActivity:(id)b;
 - (void) _addDocument:(id)aforUserActivity:(id)b;
 - (void) _removeDocument:(id)aforUserActivity:(id)b;
 - (void) _handleHIDEvent:(^{__IOHIDEvent=})a;
 - (void) handleKeyHIDEvent:(^{__IOHIDEvent=})a;
 - (id) keyCommands;
 - (id) textInputMode;
 - (void) setHardwareKeyboardLayoutName:(id)a;
 - (void) clearHardwareKeyboardState;
 - (id) windows;
 - (void) setExpectsFaceContact:(BOOL)a;
 - (void) _setApplicationIsOpaque:(BOOL)a;
 - (void) _setApplicationBackdropStyle:(long long)a;
 - (void) applicationWillOrderInContext:(id)aforWindow:(id)b;
 - (void) applicationDidOrderOutContext:(id)aforWindow:(id)b;
 - (void) _bringContextToFront:(id)a;
 - (BOOL) _isWindowServerHostingManaged;
 - (void) didDismissActionSheet;
 - (void) didDismissMiniAlert;
 - (void) willDisplayMiniAlert;
 - (void) willDismissMiniAlert;
 - (void) setHasMiniAlerts:(BOOL)a;
 - (BOOL) isLocked;
 - (BOOL) isPasscodeRequiredToUnlock;
 - (void) requestDeviceUnlock;
 - (BOOL) canShowAlerts;
 - (id) displayIDForURLScheme:(id)aisPublic:(BOOL)b;
 - (void) runModal:(id)a;
 - (void) stopModal;
 - (BOOL) _supportsShakesWhenNotActive;
 - (unsigned long long) enabledRemoteNotificationTypes;
 - (void) registerForRemoteNotificationTypes:(unsigned long long)a;
 - (void) presentLocalNotificationNow:(id)a;
 - (BOOL) _isViewContentScalingDisabled;
 - (BOOL) _requiresHighResolution;
 - (BOOL) _fakingRequiresHighResolution;
 - (BOOL) _taskSuspendingUnsupported;
 - (void) _openURL:(id)aoriginatingView:(id)bcompletionHandler:(@?)c;
 - (void) _beginShowingNetworkActivityIndicator;
 - (void) _endShowingNetworkActivityIndicator;
 - (void) _setIgnoreHeadsetClicks:(BOOL)a;
 - (BOOL) shouldFenceStatusBarRotation;
 - (BOOL) _executableWasLinkedWithUIKit;
 - (long long) applicationState;
 - (void) _wakeTimerFired;
 - (BOOL) setKeepAliveTimeout:(double)ahandler:(@?)b;
 - (void) clearKeepAliveTimeout;
 - (void) setMinimumBackgroundFetchInterval:(double)a;
 - (long long) backgroundRefreshStatus;
 - (void) endReceivingRemoteControlEvents;
 - (BOOL) _usesPreMTAlertBehavior;
 - (id) _fallbackPresentationViewController;
 - (void) _setSystemWindowsSecure:(BOOL)a;
 - (BOOL) _areSystemWindowsSecure;
 - (BOOL) _canShowTextServices;
 - (id) _showServiceForText:(id)atype:(long long)bfromRect:({CGRect={CGPoint=dd}{CGSize=dd}})cinView:(id)d;
 - (void) _setPreferredContentSizeCategoryName:(id)a;
 - (double) _lastTimestampWhenFirstTouchCameDown;
 - (double) _lastTimestampWhenAllTouchesLifted;
 - (void) _setLastTimestampWhenAllTouchesLifted:(double)a;
 - ({CGPoint=dd}) _lastLocationWhereFirstTouchCameDown;
 - ({CGPoint=dd}) _lastLocationWhereAllTouchesLifted;
 - (void) _setLastLocationWhereAllTouchesLifted:({CGPoint=dd})a;
 - ({CGSize=dd}) _virtualWindowSizeInSceneReferenceSpace;
 - (long long) _virtualHorizontalSizeClass;
 - (long long) _virtualVerticalSizeClass;
 - (long long) _expectedViewOrientation;
 - (void) _setExpectedViewOrientation:(long long)a;
 - (id) preferredContentSizeCategoryName;
 - (void) _restoreApplicationPreservationStateWithSessionIdentifier:(id)abeginHandler:(@?)bcompletionHandler:(@?)c;
 - (void) _saveApplicationPreservationState:(id)aviewController:(id)bsessionIdentifier:(id)cbeginHandler:(@?)dcompletionHandler:(@?)e;
 - (void) ignoreSnapshotOnNextApplicationLaunch;
 - (void) saveApplicationPreservationStateWithSessionIdentifier:(id)aviewController:(id)bbeginHandler:(@?)ccompletionHandler:(@?)d;
 - (void) restoreApplicationPreservationStateWithSessionIdentifier:(id)aviewController:(id)bbeginHandler:(@?)ccompletionHandler:(@?)d;
 - (void) removeApplicationPreservationStateWithSessionIdentifier:(id)a;
 - (void) _setSaveStateRestorationArchiveWithFileProtectionCompleteUntilFirstUserAuthentication;
 - (void) extendStateRestoration;
 - (void) completeStateRestoration;
 - (void) setProximitySensingEnabled:(BOOL)a;
 - (BOOL) isProximitySensingEnabled;
 - (void) setStatusBarHidden:(BOOL)aanimated:(BOOL)b;
 - (BOOL) _accessibilityCaptureSimulatorEvent:(^{__GSEvent=})a;
 - (void) _sendDictionaryToPPT:(id)a;
 - (void) failedTest:(id)a;
 - (void) startLeaking;
 - (void) stopLeaking;
 - (void) _executeResizeTest;
 - (void) startedSubTest:(id)aforTest:(id)b;
 - (void) finishedSubTest:(id)aforTest:(id)b;
 - (void) _executeNextResizeSubTest;
 - (void) runTest:(id)astartingBeforeAnimation:(id)bstoppingAfterAnimation:(id)c;
 - (void) _noteAnimationStarted:(id)a;
 - (void) _noteAnimationFinished:(id)a;
 - (id) _pathForFrameworkName:(id)ainPrivate:(BOOL)b;
 - (BOOL) launchedToTest;
 - (BOOL) isRunningTest:(id)a;
 - (void) startCHUDRecording:(id)a;
 - (id) _currentFrameCountForTestDisplay;
 - (void) startedSubTest:(id)aforTest:(id)bwithMetrics:(id)c;
 - (id) subTest:(id)aForTest:(id)bwithMetrics:(id)c;
 - (^{__CFMessagePort=}) _purplePPTServerPort;
 - (void) finishedIPTest:(id)aextraResults:(id)b;
 - (BOOL) isRunningTest;
 - (void) _reportResults:(id)a;
 - (void) stopCHUDRecording;
 - (void) finishedTest:(id)aextraResults:(id)bwaitForNotification:(id)cwithTeardownBlock:(@?)d;
 - (void) finishedTest:(id)awaitForCommit:(BOOL)bextraResults:(id)cwithTeardownBlock:(@?)d;
 - (void) installCACommitCompletionBlock:(@?)a;
 - (void) failedTest:(id)awithResults:(id)b;
 - (void) failedTest:(id)awithFailure:(id)bwithResults:(id)c;
 - (long long) _testOrientation:(id)aoptions:(id)b;
 - (BOOL) runTest:(id)aoptions:(id)b;
 - (void) failedTest:(id)awithFailure:(id)b;
 - (void) rotateIfNeeded:(long long)acompletion:(@?)b;
 - (BOOL) _isSupportedOrientation:(long long)a;
 - (void) _leak;
 - (void) runTest:(id)aforAnimation:(id)b;
 - (^v) _getSymbol:(id)aforFramework:(id)b;
 - (BOOL) shouldRecordExtendedLaunchTime;
 - (id) resultsForTest:(id)a;
 - (BOOL) isPPTAvailable;
 - (void) startedIPTest:(id)a;
 - (void) finishedIPTest:(id)a;
 - (void) finishedTest:(id)aextraResults:(id)bwithTeardownBlock:(@?)c;
 - (void) finishedTest:(id)aextraResults:(id)bwaitForNotification:(id)c;
 - (void) finishedTest:(id)awaitForCommit:(BOOL)bextraResults:(id)c;
 - (void) enableFramebufferStatisticsGathering;
 - (void) testPrep:(id)aoptions:(id)b;
 - (BOOL) rotateIfNeeded:(long long)a;
 - (void) _sheetWithRemoteIdentifierDidDismiss:(id)a;
 - (void) _accessibilityInit;
 - (BOOL) _accessibilityApplicationIsSystemWideServer;
 - (id) _accessibilitySettingsBundle;
 - (Class) _accessibilityBundlePrincipalClass;
 - (void) _accessibilitySetUpQuickSpeak;
 - (void) _updateAccessibilitySettingsLoader;
 - (void) _updateApplicationAccessibility;
 - (void) _updateLargeTextNotification;
 - (void) _updateAccessibilityItunesSettings;
 - (void) _accessibilityStatusChanged:(id)a;
 - (void) beginRemoteSheet:(id)adelegate:(id)bdidEndSelector:(SEL)ccontextInfo:(^v)drequireTopApplication:(BOOL)e;
 - (void) beginRemoteSheet:(id)adelegate:(id)bdidEndSelector:(SEL)ccontextInfo:(^v)drequireTopApplication:(BOOL)epresentAnimated:(BOOL)f;
 - (void) beginRemoteSheet:(id)adelegate:(id)bdidEndSelector:(SEL)ccontextInfo:(^v)drequireTopApplication:(BOOL)eopaque:(BOOL)fpresentAnimated:(BOOL)g;
 - (void) beginRemoteSheetController:(id)aviewOrNil:(id)bdelegate:(id)cdidEndSelector:(SEL)dcontextInfo:(^v)erequireTopApplication:(BOOL)fopaque:(BOOL)gpresentAnimated:(BOOL)h;
 - (void) endRemoteSheet:(id)areturnCode:(long long)b;
 - (void) endRemoteSheet:(id)areturnCode:(long long)bdismissAnimated:(BOOL)c;
 - (void) beginRemoteSheet:(id)adelegate:(id)bdidEndSelector:(SEL)ccontextInfo:(^v)d;
 - (void) beginRemoteSheetController:(id)adelegate:(id)bdidEndSelector:(SEL)ccontextInfo:(^v)drequireTopApplication:(BOOL)eopaque:(BOOL)fpresentAnimated:(BOOL)g;
 - (void) endRemoteSheet:(id)a;
 - (void) _alertSheetStackChanged;
 - (void) installNotificationObserverForNotificationName:(id)aforOneNotification:(BOOL)busingBlock:(@?)c;
 - (void) _runSubTestForKeyboardDismissalWithName:(id)awithHideKeyboardBlock:(@?)bwithExtraResultsBlock:(@?)cwithCleanupBlock:(@?)d;
 - (void) _runSubTestForKeyboardMergeWithName:(id)awithExtraResultsBlock:(@?)bwithCleanupBlock:(@?)c;
 - (void) showKeyboardUsingBlock:(@?)awithCompletionBlock:(@?)b;
 - (void) _runSubTestForKeyboardBringupWithName:(id)awithShowKeyboardBlock:(@?)bwithHideKeyboardBlock:(@?)cwithExtraResultsBlock:(@?)dwithCleanupBlock:(@?)e;
 - (void) _runSubTestForKeyboardSplitWithName:(id)awithShowKeyboardBlock:(@?)bwithExtraResultsBlock:(@?)cwithCleanupBlock:(@?)d;
 - (void) runTestForKeyboardBringupAndDismissalWithName:(id)awithShowKeyboardBlock:(@?)bwithHideKeyboardBlock:(@?)cwithExtraResultsBlock:(@?)dwithCleanupBlock:(@?)e;
 - (void) runTestForKeyboardRotationWithName:(id)afromOrientation:(long long)bwithShowKeyboardBlock:(@?)cwithExtraResultsBlock:(@?)dwithCleanupBlock:(@?)e;
 - (void) runTestForKeyboardSplitAndMergeWithName:(id)awithShowKeyboardBlock:(@?)bwithExtraResultsBlock:(@?)cwithCleanupBlock:(@?)d;
 - (id) init;
 - (void) suspend;
 - (id) delegate;
 - (unsigned long long) beginBackgroundTaskWithName:(id)aexpirationHandler:(@?)b;
 - (void) endBackgroundTask:(unsigned long long)a;
 - (id) preferredContentSizeCategory;
 - (id) _preferredContentSizeCategory:(unsigned long long)a;
 - (double) backgroundTimeRemaining;
 - (void) workspace:(id)adidLaunchWithCompletion:(@?)b;
 - (void) workspaceShouldExit:(id)a;
 - (void) workspaceNoteAssertionExpirationImminent:(id)a;
 - (long long) interfaceOrientation;
 - (void) scene:(id)adidReceiveActions:(id)b;
 - (void) scene:(id)adidUpdateWithDiff:(id)btransitionContext:(id)ccompletion:(@?)d;
 - (void) workspaceDidEndTransaction:(id)a;
 - (void) workspace:(id)adidCreateScene:(id)bwithTransitionContext:(id)ccompletion:(@?)d;
 - (void) workspace:(id)awillDestroyScene:(id)bwithTransitionContext:(id)ccompletion:(@?)d;
 - (void) workspace:(id)adidReceiveActions:(id)b;
 - (void) _installAutoreleasePoolsIfNecessaryForMode:(^{__CFString=})a;
 - (BOOL) _isClassic;
 - (void) beginReceivingRemoteControlEvents;
 - (BOOL) handleEvent:(^{__GSEvent=})a;
 - (id) nextResponder;
 - (BOOL) becomeFirstResponder;
 - (void) sendEvent:(id)a;
 - (void) _setStatusBarOrientation:(long long)a;
 - (BOOL) isSuspended;


@end
