
@protocol NSCoding;
@interface UIBarButtonItem : UIBarItem <NSCoding> {

    @"NSString" _title;
    @"NSSet" _possibleTitles;
    SEL _action;
    id _target;
    @"UIImage" _image;
    @"UIImage" _landscapeImagePhone;
    {UIEdgeInsets="top"d"left"d"bottom"d"right"d} _imageInsets;
    {UIEdgeInsets="top"d"left"d"bottom"d"right"d} _landscapeImagePhoneInsets;
    d _width;
    @"UIView" _view;
    q _tag;
    id _appearanceStorage;
    {?="enabled"b1"style"b3"isSystemItem"b1"systemItem"b7"viewIsCustom"b1"isMinibarView"b1"disableAutosizing"b1"selected"b1"imageHasEffects"b1} _barButtonItemFlags;
    BOOL _flexible;
    BOOL __showsBackButtonIndicator;
    BOOL __hidden;
    BOOL __viewWantsLetterpressImage;
    BOOL __needsViewUpdateForLetterpressImage;
    d _toolbarCharge;
    d _minimumWidth;
    d _maximumWidth;
    @"NSSet" _possibleSystemItems;
    @"NSDictionary" _stylesForSizingTitles;
    @"UIBarButtonItem" __itemVariation;
    @"UINavigationItem" __owningNavigationItem;
}
 + (void) _getSystemItemStyle:(^q)atitle:(^@)bimage:(^@)cselectedImage:(^@)daction:(^:)eforBarStyle:(q)flandscape:(BOOL)galwaysBordered:(BOOL)husingSystemItem:(q)iusingItemStyle:(q)j;
 + (id) _appearanceBlindViewClasses;
 + (Class) classForNavigationButton;
 + (Class) classForToolbarButton;

 - (id) target;
 - (id) title;
 - (void) setTitle:(id)a;
 - (void) dealloc;
 - (void) setTarget:(id)a;
 - (SEL) action;
 - (void) setView:(id)a;
 - (id) tintColor;
 - (void) setTintColor:(id)a;
 - (void) setTag:(q)a;
 - (BOOL) isCustomViewItem;
 - (id) _appearanceStorage;
 - (BOOL) _needsViewUpdateForLetterpressImage;
 - (void) _updateView;
 - (BOOL) _hidden;
 - (BOOL) _showsBackButtonIndicator;
 - (void) _setOwningNavigationItem:(id)a;
 - (BOOL) isSystemItem;
 - (q) systemItem;
 - (id) createViewForNavigationItem:(id)a;
 - (id) landscapeImagePhone;
 - (BOOL) isMinibarView;
 - (void) setIsMinibarView:(BOOL)a;
 - (void) setTitleTextAttributes:(id)aforState:(Q)b;
 - (BOOL) _shouldBezelSystemButtonImage;
 - (id) backgroundImageForState:(Q)astyle:(q)bbarMetrics:(q)c;
 - (BOOL) _isImageBarButtonItem;
 - (d) _leftImagePaddingForEdgeMarginInNavBar;
 - (d) _rightImagePaddingForEdgeMarginInNavBar;
 - (id) scriptingID;
 - (void) setBackgroundImage:(id)aforState:(Q)bbarMetrics:(q)c;
 - (id) _stylesForSizingTitles;
 - (void) _setStylesForSizingTitles:(id)a;
 - (id) _possibleSystemItems;
 - (d) _minimumWidth;
 - (d) _maximumWidth;
 - (void) setBackButtonBackgroundImage:(id)aforState:(Q)bbarMetrics:(q)c;
 - (void) setAction:(SEL)a;
 - (void) setSelected:(BOOL)a;
 - (id) initWithTitle:(id)astyle:(q)btarget:(id)caction:(SEL)d;
 - (void) _setPossibleItemVariations:(id)a;
 - (void) _setItemVariation:(id)a;
 - (d) _width;
 - (id) backgroundImageForState:(Q)abarMetrics:(q)b;
 - (id) titleTextAttributesForState:(Q)a;
 - (id) createViewForToolbar:(id)a;
 - (BOOL) _imageHasEffects;
 - (id) customView;
 - (void) _sendAction:(id)awithEvent:(id)b;
 - (BOOL) _flexible;
 - (void) _setHidden:(BOOL)a;
 - (void) _connectInterfaceBuilderEventConnection:(id)a;
 - (void) setImageInsets:({UIEdgeInsets=dddd})a;
 - ({UIEdgeInsets=dddd}) imageInsets;
 - (id) initWithCustomView:(id)a;
 - (void) _setToolbarCharge:(d)a;
 - (void) setLandscapeImagePhone:(id)a;
 - (void) setCustomView:(id)a;
 - (void) setPossibleTitles:(id)a;
 - (void) _getSystemItemStyle:(^q)atitle:(^@)bimage:(^@)cselectedImage:(^@)daction:(^:)eforBarStyle:(q)flandscape:(BOOL)galwaysBordered:(BOOL)h;
 - (void) _getNavBarEdgeSizeAdjust:(^{CGSize=dd})aimageInsets:(^{UIEdgeInsets=dddd})blandscape:(BOOL)c;
 - (void) _getToolbarEdgeInsets:(^{UIEdgeInsets=dddd})aimageInsets:(^{UIEdgeInsets=dddd})bglowInsets:(^{UIEdgeInsets=dddd})cforBarStyle:(q)dlandscape:(BOOL)ealwaysBordered:(BOOL)f;
 - (id) _owningNavigationItem;
 - (void) setBackgroundImage:(id)aforState:(Q)bstyle:(q)cbarMetrics:(q)d;
 - (void) _applyPositionAdjustmentToSegmentedControl:(id)a;
 - (id) initWithImage:(id)astyle:(q)btarget:(id)caction:(SEL)d;
 - (id) initWithImage:(id)alandscapeImagePhone:(id)bstyle:(q)ctarget:(id)daction:(SEL)e;
 - (id) initWithBarButtonSystemItem:(q)atarget:(id)baction:(SEL)c;
 - (void) setLandscapeImagePhoneInsets:({UIEdgeInsets=dddd})a;
 - ({UIEdgeInsets=dddd}) landscapeImagePhoneInsets;
 - (id) _possibleItemVariations;
 - (id) itemVariation;
 - (id) possibleTitles;
 - (void) _setSystemItem:(q)a;
 - (void) _setPossibleSystemItems:(id)a;
 - (BOOL) selected;
 - (id) backButtonBackgroundImageForState:(Q)abarMetrics:(q)b;
 - (void) setBackgroundVerticalPositionAdjustment:(d)aforBarMetrics:(q)b;
 - (d) backgroundVerticalPositionAdjustmentForBarMetrics:(q)a;
 - (void) setTitlePositionAdjustment:({UIOffset=dd})aforBarMetrics:(q)b;
 - ({UIOffset=dd}) titlePositionAdjustmentForBarMetrics:(q)a;
 - (void) setBackButtonBackgroundVerticalPositionAdjustment:(d)aforBarMetrics:(q)b;
 - (d) backButtonBackgroundVerticalPositionAdjustmentForBarMetrics:(q)a;
 - (void) setBackButtonTitlePositionAdjustment:({UIOffset=dd})aforBarMetrics:(q)b;
 - ({UIOffset=dd}) backButtonTitlePositionAdjustmentForBarMetrics:(q)a;
 - (d) _toolbarCharge;
 - (void) _setMinimumWidth:(d)a;
 - (void) _setMaximumWidth:(d)a;
 - (void) _setFlexible:(BOOL)a;
 - (id) _itemVariation;
 - (void) _setShowsBackButtonIndicator:(BOOL)a;
 - (BOOL) _viewWantsLetterpressImage;
 - (id) _miniImage;
 - (void) _setMiniImage:(id)a;
 - ({UIEdgeInsets=dddd}) _miniImageInsets;
 - (void) _setMiniImageInsets:({UIEdgeInsets=dddd})a;
 - (id) _toolbarButton;
 - (void) _setImageHasEffects:(BOOL)a;
 - (id) _foregroundColorForLetterpressWithView:(id)a;
 - (void) _setWidth:(d)a;
 - (id) init;
 - (void) encodeWithCoder:(id)a;
 - (id) initWithCoder:(id)a;
 - (id) window;
 - (void) setImage:(id)a;
 - (q) style;
 - (q) tag;
 - (id) image;
 - (void) setStyle:(q)a;
 - (id) view;
 - (id) nextResponder;
 - (BOOL) isEnabled;
 - (void) setEnabled:(BOOL)a;
 - (d) width;
 - (void) setWidth:(d)a;


@end
