
@protocol NSCoding;
@interface UIButton : UIControl <NSCoding> {

    unsigned long long _externalFlatEdge;
    ^{__CFDictionary=} _contentLookup;
    {UIEdgeInsets="top"d"left"d"bottom"d"right"d} _contentEdgeInsets;
    {UIEdgeInsets="top"d"left"d"bottom"d"right"d} _titleEdgeInsets;
    {UIEdgeInsets="top"d"left"d"bottom"d"right"d} _imageEdgeInsets;
    UIImageView* _backgroundView;
    UIImageView* _imageView;
    UILabel* _titleView;
    BOOL _initialized;
    unsigned long long _lastDrawingControlState;
    UITapGestureRecognizer* _selectGestureRecognizer;
    {?="reversesTitleShadowWhenHighlighted"b1"adjustsImageWhenHighlighted"b1"adjustsImageWhenDisabled"b1"autosizeToFit"b1"disabledDimsImage"b1"showsTouchWhenHighlighted"b1"buttonType"b8"shouldHandleScrollerMouseEvent"b1"titleFrozen"b1"resendTraitToImageViews"b2} _buttonFlags;
    _UIButtonMaskAnimationView* _maskAnimationView;
    UIView* _selectionView;
    UIFont* _lazyTitleViewFont;
    NSArray* _contentConstraints;
    {UIEdgeInsets="top"d"left"d"bottom"d"right"d} _internalTitlePaddingInsets;
}
 + (id) sharedImageCache;
 + (void) setSharedImageCache:(id)a;
 + (id) af_sharedImageRequestOperationQueue;
 + (id) buttonWithType:(long long)a;
 + (void) _setVisuallyHighlighted:(BOOL)aforViews:(id)binitialPress:(BOOL)c;
 + (id) _defaultNormalTitleColor;
 + (id) _defaultNormalTitleShadowColor;
 + (id) _defaultImageForType:(long long)aandState:(unsigned long long)b;
 + (void) _setVisuallyHighlighted:(BOOL)aforViews:(id)binitialPress:(BOOL)cbaseAlpha:(double)d;
 + (id) _selectedIndicatorImage;
 + (id) _infoLightImage;
 + (id) _detailDisclosureImage;
 + (id) _plusImage;
 + (id) _infoDarkImage;
 + (id) _exclamationMarkImage;
 + (id) _questionMarkImage;
 + (id) _checkmarkImage;
 + (id) _minusImage;
 + (id) _xImage;
 + (id) _defaultBackgroundImageForType:(long long)aandState:(unsigned long long)b;
 + (id) _defaultTitleColorForState:(unsigned long long)abutton:(id)b;
 + (id) _defaultImageColorForState:(unsigned long long)abutton:(id)b;

 - (void) setImageForState:(unsigned long long)awithURL:(id)bplaceholderImage:(id)c;
 - (void) setImageForState:(unsigned long long)awithURLRequest:(id)bplaceholderImage:(id)csuccess:(@?)dfailure:(@?)e;
 - (void) cancelImageRequestOperationForState:(unsigned long long)a;
 - (void) setBackgroundImageForState:(unsigned long long)awithURL:(id)bplaceholderImage:(id)c;
 - (void) setBackgroundImageForState:(unsigned long long)awithURLRequest:(id)bplaceholderImage:(id)csuccess:(@?)dfailure:(@?)e;
 - (void) cancelBackgroundImageRequestOperationForState:(unsigned long long)a;
 - (void) setImageForState:(unsigned long long)awithURL:(id)b;
 - (void) setBackgroundImageForState:(unsigned long long)awithURL:(id)b;
 - (id) imageResponseSerializer;
 - (void) setImageResponseSerializer:(id)a;
 - (id) af_imageRequestOperationForState:(unsigned long long)a;
 - (void) af_setImageRequestOperation:(id)aforState:(unsigned long long)b;
 - (id) af_backgroundImageRequestOperationForState:(unsigned long long)a;
 - (void) af_setBackgroundImageRequestOperation:(id)aforState:(unsigned long long)b;
 - (id) title;
 - (void) setTitle:(id)a;
 - (void) dealloc;
 - (void) setTitle:(id)aforState:(unsigned long long)b;
 - (void) _populateArchivedSubviews:(id)a;
 - ({CGSize=dd}) _intrinsicSizeWithinSize:({CGSize=dd})a;
 - (void) layoutSubviews;
 - (BOOL) _contentHuggingDefault_isUsuallyFixedHeight;
 - (BOOL) _contentHuggingDefault_isUsuallyFixedWidth;
 - ({CGSize=dd}) sizeThatFits:({CGSize=dd})a;
 - (id) _backgroundView;
 - (BOOL) gestureRecognizerShouldBegin:(id)a;
 - (void) setAttributedTitle:(id)aforState:(unsigned long long)b;
 - (long long) _buttonType;
 - (void) _setButtonType:(long long)a;
 - (void) setFont:(id)a;
 - ({UIEdgeInsets=dddd}) alignmentRectInsets;
 - (long long) _lineBreakMode;
 - (void) invalidateIntrinsicContentSize;
 - (void) traitCollectionDidChange:(id)a;
 - (void) setTintColor:(id)a;
 - (void) focusedViewDidChange;
 - (BOOL) canBecomeFocused;
 - (void) tintColorDidChange;
 - (void) _intrinsicContentSizeInvalidatedForChildView:(id)a;
 - (void) _willMoveToWindow:(id)a;
 - (void) _didChangeFromIdiom:(long long)aonScreen:(id)btraverseHierarchy:(BOOL)c;
 - (BOOL) _alwaysHandleScrollerMouseEvent;
 - (id) _scriptingInfo;
 - (void) setImage:(id)aforState:(unsigned long long)b;
 - (id) titleForState:(unsigned long long)a;
 - (void) _setLineBreakMode:(long long)a;
 - (void) _updateTitleView;
 - (id) _titleView;
 - (void) setHighlighted:(BOOL)a;
 - (void) setTitleColor:(id)aforState:(unsigned long long)b;
 - (void) _setTitleShadowOffset:({CGSize=dd})a;
 - (id) titleLabel;
 - (void) _setFrame:({CGRect={CGPoint=dd}{CGSize=dd}})adeferLayout:(BOOL)b;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) _selectedIndicatorBounds;
 - (id) _imageView;
 - (void) setTitleShadowColor:(id)aforState:(unsigned long long)b;
 - (void) setTitleColor:(id)aforStates:(unsigned long long)b;
 - (void) setAdjustsImageWhenHighlighted:(BOOL)a;
 - (void) setAdjustsImageWhenDisabled:(BOOL)a;
 - (void) setBackgroundImage:(id)aforState:(unsigned long long)b;
 - (void) setBackgroundImage:(id)aforStates:(unsigned long long)b;
 - (void) _setImageColor:(id)aforState:(unsigned long long)b;
 - (void) setTitleEdgeInsets:({UIEdgeInsets=dddd})a;
 - (BOOL) _isTitleFrozen;
 - (void) _setFont:(id)a;
 - (void) _setTitleFrozen:(BOOL)a;
 - (void) setTitleShadowColor:(id)aforStates:(unsigned long long)b;
 - (void) setTitle:(id)aforStates:(unsigned long long)b;
 - (void) setImage:(id)aforStates:(unsigned long long)b;
 - (void) setContentHorizontalAlignment:(long long)a;
 - (void) setContentVerticalAlignment:(long long)a;
 - (void) setDisabledDimsImage:(BOOL)a;
 - (id) imageForState:(unsigned long long)a;
 - (id) _createPreparedImageViewWithFrame:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - (id) backgroundImageForState:(unsigned long long)a;
 - (void) setContentEdgeInsets:({UIEdgeInsets=dddd})a;
 - (void) _sendSetNeedsLayoutToSuperviewOnTitleAnimationCompletionIfNecessary;
 - ({UIEdgeInsets=dddd}) _pathTitleEdgeInsets;
 - ({UIEdgeInsets=dddd}) _pathImageEdgeInsets;
 - (BOOL) _isModernButton;
 - (BOOL) _isExternalRoundedRectButton;
 - (id) _externalUnfocusedBorderColor;
 - (void) setSelected:(BOOL)a;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) _clippedHighlightBounds;
 - (double) _highlightCornerRadius;
 - (void) updateConstraints;
 - (id) imageView;
 - (id) viewForBaselineLayout;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) backgroundRectForBounds:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - (void) setAutosizesToFit:(BOOL)a;
 - (id) currentTitle;
 - (id) currentImage;
 - (id) _contentForState:(unsigned long long)a;
 - (void) _setContent:(id)aforState:(unsigned long long)b;
 - (id) _layoutDebuggingTitle;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) contentRectForBounds:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) titleRectForContentRect:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) imageRectForContentRect:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - (void) setShowPressFeedback:(BOOL)a;
 - (void) _titleAttributesChanged;
 - (long long) buttonType;
 - (id) _backgroundForState:(unsigned long long)ausesBackgroundForNormalState:(^B)b;
 - (id) _setupBackgroundView;
 - (void) _setTitleColor:(id)aforStates:(unsigned long long)b;
 - (void) _setShadowColor:(id)aforStates:(unsigned long long)b;
 - (id) titleColorForState:(unsigned long long)a;
 - (id) titleShadowColorForState:(unsigned long long)a;
 - (id) attributedTitleForState:(unsigned long long)a;
 - ({UIEdgeInsets=dddd}) contentEdgeInsets;
 - (void) _setContentConstraints:(id)a;
 - (void) _invalidateContentConstraints;
 - (void) setShowsTouchWhenHighlighted:(BOOL)a;
 - (void) _applyAppropriateChargeForButtonType;
 - (void) _takeContentFromArchivableContent:(id)a;
 - (id) _archivableContent:(^@)a;
 - (void) _uninstallSelectGestureRecognizer;
 - (void) _updateEffectsForImageView:(id)abackground:(BOOL)b;
 - (void) _installSelectGestureRecognizer;
 - (BOOL) autosizesToFit;
 - ({CGPoint=dd}) pressFeedbackPosition;
 - (BOOL) _canHaveTitle;
 - (void) _setupTitleView;
 - (void) _setupImageView;
 - (BOOL) _hasDrawingStyle;
 - (BOOL) _isEffectivelyDisabledExternalRoundedRectButton;
 - (void) _selectGestureChanged:(id)a;
 - (id) _imageForState:(unsigned long long)ausesImageForNormalState:(^B)b;
 - (void) _updateImageView;
 - (BOOL) _hasHighlightColor;
 - (BOOL) _isExternalRoundedRectButtonWithPressednessState;
 - (id) _selectedIndicatorViewWithImage:(id)a;
 - (double) _selectedIndicatorAlpha;
 - (BOOL) _textNeedsCompositingModeWhenSelected;
 - (BOOL) _imageNeedsCompositingModeWhenSelected;
 - (unsigned long long) _externalFlatEdge;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) _highlightBoundsForDrawingStyle;
 - (id) _borderColorForState:(unsigned long long)a;
 - (void) _prepareMaskAnimationViewIfNecessary;
 - (id) _transitionAnimationWithKeyPath:(id)a;
 - (double) _borderWidthForState:(unsigned long long)abounds:({CGRect={CGPoint=dd}{CGSize=dd}})b;
 - (id) _fadeOutAnimationWithKeyPath:(id)a;
 - (void) _updateMaskState;
 - (id) _externalFocusedTitleColor;
 - (id) _externalTitleColorForState:(unsigned long long)a;
 - (id) _externalBorderColorForState:(unsigned long long)a;
 - (double) _drawingStrokeForState:(unsigned long long)a;
 - ({UIEdgeInsets=dddd}) _outsetInsets:({UIEdgeInsets=dddd})a;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) _highlightBounds;
 - (id) _titleForState:(unsigned long long)a;
 - (id) _titleColorForState:(unsigned long long)a;
 - (id) _shadowColorForState:(unsigned long long)a;
 - (id) _attributedTitleForState:(unsigned long long)a;
 - (id) _imageColorForState:(unsigned long long)a;
 - ({UIEdgeInsets=dddd}) _combinedContentPaddingInsets;
 - ({UIEdgeInsets=dddd}) titleEdgeInsets;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) _titleRectForContentRect:({CGRect={CGPoint=dd}{CGSize=dd}})acalculatePositionForEmptyTitle:(BOOL)b;
 - ({UIEdgeInsets=dddd}) imageEdgeInsets;
 - (void) _setContentHuggingPriorities:({CGSize=dd})a;
 - (id) _titleOrImageViewForBaselineLayout;
 - (BOOL) _likelyToHaveTitle;
 - (void) _setupTitleViewRequestingLayout:(BOOL)a;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) _highlightRectForImageRect:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) _highlightRectForTextRect:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - (BOOL) adjustsImageWhenHighlighted;
 - (BOOL) showsTouchWhenHighlighted;
 - (BOOL) adjustsImageWhenDisabled;
 - (void) _beginTitleAnimation;
 - (id) _letterpressStyleForState:(unsigned long long)a;
 - (void) _updateBackgroundImageView;
 - (void) _layoutBackgroundImageView;
 - (void) _layoutImageView;
 - (void) _layoutTitleView;
 - (void) _setupDrawingStyleForState:(unsigned long long)a;
 - (BOOL) _shouldUpdatePressedness;
 - (void) _updateSelectionViewForState:(unsigned long long)a;
 - (void) _setupPressednessForState:(unsigned long long)a;
 - ({CGSize=dd}) _titleShadowOffset;
 - (id) _newImageViewWithFrame:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - (id) _newLabelWithFrame:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - (void) _setTitle:(id)aforStates:(unsigned long long)b;
 - (void) _setImage:(id)aforStates:(unsigned long long)b;
 - (void) _setBackground:(id)aforStates:(unsigned long long)b;
 - (double) _drawingStrokeForStyle:(long long)a;
 - (void) _setDrawingStroke:(double)aforState:(unsigned long long)b;
 - (long long) _drawingStyleForStroke:(double)a;
 - (long long) _externalDrawingStyleForState:(unsigned long long)a;
 - (BOOL) _shouldDefaultToTemplatesForImageViewBackground:(BOOL)a;
 - (id) _externalImageColorForState:(unsigned long long)a;
 - (BOOL) _hasImageForProperty:(id)a;
 - (BOOL) reversesTitleShadowWhenHighlighted;
 - (void) setReversesTitleShadowWhenHighlighted:(BOOL)a;
 - (void) setImageEdgeInsets:({UIEdgeInsets=dddd})a;
 - (void) _setExternalFlatEdge:(unsigned long long)a;
 - (id) currentTitleColor;
 - (id) _currentImageColor;
 - (id) currentTitleShadowColor;
 - (id) currentBackgroundImage;
 - (id) currentAttributedTitle;
 - ({CGSize=dd}) titleShadowOffset;
 - (void) setTitleShadowOffset:({CGSize=dd})a;
 - (void) _setShouldHandleScrollerMouseEvent:(BOOL)a;
 - (void) crossfadeToImage:(id)aforState:(unsigned long long)b;
 - (void) _setLetterpressStyle:(id)aforState:(unsigned long long)b;
 - (void) _setDrawingStyle:(long long)aforState:(unsigned long long)b;
 - (long long) _drawingStyleForState:(unsigned long long)a;
 - (void) _setImageColor:(id)aforStates:(unsigned long long)b;
 - (void) _setAttributedTitle:(id)aforStates:(unsigned long long)b;
 - (id) _contentConstraints;
 - ({UIEdgeInsets=dddd}) _internalTitlePaddingInsets;
 - (void) _setInternalTitlePaddingInsets:({UIEdgeInsets=dddd})a;
 - (unsigned long long) defaultAccessibilityTraits;
 - (BOOL) isAccessibilityElementByDefault;
 - (BOOL) isElementAccessibilityExposedToInterfaceBuilder;
 - (void) encodeWithCoder:(id)a;
 - (id) initWithCoder:(id)a;
 - (id) initWithFrame:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - (void) setFrame:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - (void) setBounds:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - (id) font;
 - (long long) lineBreakMode;
 - (void) setLineBreakMode:(long long)a;
 - (id) _font;
 - (id) image;
 - (void) setEnabled:(BOOL)a;


@end
