
@interface UIConcreteLocalNotification : UILocalNotification {

    @"NSDate" fireDate;
    @"NSTimeZone" timeZone;
    Q repeatInterval;
    @"NSCalendar" repeatCalendar;
    i totalRepeatCount;
    i remainingRepeatCount;
    @"CLRegion" region;
    BOOL regionTriggersOnce;
    @"NSString" alertBody;
    BOOL hasAction;
    @"NSString" alertAction;
    @"NSString" alertLaunchImage;
    @"NSString" alertTitle;
    @"NSString" soundName;
    q applicationIconBadgeNumber;
    @"NSData" userInfoData;
    BOOL hideAlertTitle;
    BOOL allowSnooze;
    i soundType;
    BOOL interruptAudioAndLockDevice;
    BOOL resumeApplicationInBackground;
    BOOL fireNotificationsWhenAppRunning;
    BOOL showAlarmStatusBarItem;
    @"NSString" customLockSliderLabel;
    @"NSString" firedNotificationName;
    @"NSString" snoozedNotificationName;
    @"NSString" category;
    BOOL isTransient;
}

 - (id) fireDate;
 - (void) setFireDate:(id)a;
 - (id) copyWithZone:(^{_NSZone=})a;
 - (id) description;
 - (void) dealloc;
 - (id) userInfo;
 - (BOOL) isValid;
 - (Q) hash;
 - (BOOL) isEqual:(id)a;
 - (void) setTimeZone:(id)a;
 - (id) timeZone;
 - (void) setCategory:(id)a;
 - (void) setRepeatInterval:(Q)a;
 - (id) alertBody;
 - (id) soundName;
 - (q) applicationIconBadgeNumber;
 - (void) validate;
 - (void) setApplicationIconBadgeNumber:(q)a;
 - (Q) repeatInterval;
 - (void) setTotalRepeatCount:(i)a;
 - (void) setSoundType:(i)a;
 - (void) setRepeatCalendar:(id)a;
 - (void) setRemainingRepeatCount:(i)a;
 - (void) setAlertBody:(id)a;
 - (void) setHasAction:(BOOL)a;
 - (void) setAlertAction:(id)a;
 - (void) setAlertLaunchImage:(id)a;
 - (void) setAlertTitle:(id)a;
 - (void) setSoundName:(id)a;
 - (void) _setUserInfoData:(id)a;
 - (void) setHideAlertTitle:(BOOL)a;
 - (void) setAllowSnooze:(BOOL)a;
 - (void) setInterruptAudioAndLockDevice:(BOOL)a;
 - (void) setResumeApplicationInBackground:(BOOL)a;
 - (void) setFireNotificationsWhenAppRunning:(BOOL)a;
 - (void) setShowAlarmStatusBarItem:(BOOL)a;
 - (void) setCustomLockSliderLabel:(id)a;
 - (void) setFiredNotificationName:(id)a;
 - (void) setSnoozedNotificationName:(id)a;
 - (void) setIsTransient:(BOOL)a;
 - (void) setRegion:(id)a;
 - (void) setRegionTriggersOnce:(BOOL)a;
 - (id) repeatCalendar;
 - (i) totalRepeatCount;
 - (BOOL) hasAction;
 - (id) alertAction;
 - (id) alertLaunchImage;
 - (id) alertTitle;
 - (BOOL) hideAlertTitle;
 - (BOOL) allowSnooze;
 - (i) soundType;
 - (BOOL) interruptAudioAndLockDevice;
 - (BOOL) resumeApplicationInBackground;
 - (BOOL) fireNotificationsWhenAppRunning;
 - (BOOL) showAlarmStatusBarItem;
 - (id) customLockSliderLabel;
 - (id) firedNotificationName;
 - (id) snoozedNotificationName;
 - (id) region;
 - (BOOL) regionTriggersOnce;
 - (id) nextFireDateForLastFireDate:(id)a;
 - (BOOL) isTriggeredByDate;
 - (id) nextFireDateAfterDate:(id)alocalTimeZone:(id)b;
 - (q) compareFireDates:(id)a;
 - (void) clearNonSystemProperties;
 - (i) remainingRepeatCount;
 - (BOOL) isTransient;
 - (id) init;
 - (void) encodeWithCoder:(id)a;
 - (id) initWithCoder:(id)a;
 - (void) setUserInfo:(id)a;
 - (id) category;


@end
