
@protocol NSCoding;
@interface UICollectionViewLayout : NSObject <NSCoding> {

    @"UICollectionView" _collectionView;
    {CGSize="width"d"height"d} _collectionViewBoundsSize;
    @"NSMutableDictionary" _initialAnimationLayoutAttributesDict;
    @"NSMutableDictionary" _finalAnimationLayoutAttributesDict;
    @"NSMutableDictionary" _deletedSupplementaryIndexPathsDict;
    @"NSMutableDictionary" _insertedSupplementaryIndexPathsDict;
    @"NSMutableDictionary" _deletedDecorationIndexPathsDict;
    @"NSMutableDictionary" _insertedDecorationIndexPathsDict;
    @"NSMutableIndexSet" _deletedSectionsSet;
    @"NSMutableIndexSet" _insertedSectionsSet;
    @"NSMutableDictionary" _decorationViewClassDict;
    @"NSMutableDictionary" _decorationViewNibDict;
    @"NSMutableDictionary" _decorationViewExternalObjectsTables;
    @"UICollectionViewLayout" _transitioningFromLayout;
    @"UICollectionViewLayout" _transitioningToLayout;
    @"UIDynamicAnimator" _animator;
    @"UICollectionViewLayoutInvalidationContext" _invalidationContext;
    {CGRect="origin"{CGPoint="x"d"y"d}"size"{CGSize="width"d"height"d}} _frame;
    @"NSIndexSet" _sections;
    @"NSIndexSet" _items;
    @"NSArray" _elementKinds;
    ^{_UICollectionViewCompositionLayout=#} _compositionLayout;
    @"UICollectionViewLayout" _siblingLayout;
    {CGPoint="x"d"y"d} _layoutOffset;
    Q _layoutOffsetEdges;
    {?="inTransitionFromTransitionLayout"b1"inTransitionToTransitionLayout"b1"prepared"b1} _layoutFlags;
    q _sublayoutType;
}
@property (nonatomic, assign, readonly) UICollectionView* collectionView;
@property (nonatomic, assign, readwrite, _frame, _setFrame:) NSNumber* frame;
@property (nonatomic, copy, readwrite, _sections, _setSections:) NSIndexSet* sections;
@property (nonatomic, copy, readwrite, _items, _setItems:) NSIndexSet* items;
@property (nonatomic, copy, readwrite, _elementKinds, _setElementKinds:) NSArray* elementKinds;
@property (nonatomic, assign, readwrite, _compositionLayout, _setCompositionLayout:) _UICollectionViewCompositionLayout* compositionLayout;
@property (nonatomic, assign, readwrite, _siblingLayout, _setSiblingLayout:) UICollectionViewLayout* siblingLayout;
@property (nonatomic, assign, readwrite, _layoutOffset, _setLayoutOffset:) NSNumber* layoutOffset;
@property (nonatomic, assign, readwrite, _layoutOffsetEdges, _setLayoutOffsetEdges:) NSNumber* layoutOffsetEdges;
@property (nonatomic, assign, readwrite, _sublayoutType, _setSublayoutType:) NSNumber* sublayoutType;
@property (nonatomic, assign, readwrite, _isPrepared, _setPrepared:) NSNumber* prepared;
 + (Class) invalidationContextClass;
 + (Class) layoutAttributesClass;

 - (void) dealloc;
 - (id) layoutAttributesForElementsInRect:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - (id) layoutAttributesForItemAtIndexPath:(id)a;
 - (id) collectionView;
 - (id) _items;
 - ({CGSize=dd}) collectionViewContentSize;
 - (void) invalidateLayout;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) _bounds;
 - (void) _setFrame:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - (void) _setSublayoutType:(q)a;
 - (void) _setCompositionLayout:(^{_UICollectionViewCompositionLayout=#})a;
 - (void) _setSections:(id)a;
 - (void) _setLayoutOffset:({CGPoint=dd})a;
 - (void) _setLayoutOffsetEdges:(Q)a;
 - (void) _setSiblingLayout:(id)a;
 - (void) _setItems:(id)a;
 - (void) _setElementKinds:(id)a;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) convertRect:({CGRect={CGPoint=dd}{CGSize=dd}})afromLayout:(id)b;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) convertRect:({CGRect={CGPoint=dd}{CGSize=dd}})atoLayout:(id)b;
 - (id) _sections;
 - (BOOL) shouldInvalidateLayoutForPreferredLayoutAttributes:(id)awithOriginalAttributes:(id)b;
 - (id) layoutAttributesForSupplementaryViewOfKind:(id)aatIndexPath:(id)b;
 - (id) layoutAttributesForDecorationViewOfKind:(id)aatIndexPath:(id)b;
 - (void) prepareLayout;
 - (id) _siblingLayout;
 - (BOOL) _isPrepared;
 - ({CGPoint=dd}) _layoutOffset;
 - (Q) _layoutOffsetEdges;
 - (void) invalidateLayoutWithContext:(id)a;
 - (id) invalidationContextForBoundsChange:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - (id) invalidationContextForPreferredLayoutAttributes:(id)awithOriginalAttributes:(id)b;
 - (void) registerClass:(Class)aforDecorationViewOfKind:(id)b;
 - (BOOL) shouldInvalidateLayoutForBoundsChange:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - (id) indexPathsToDeleteForSupplementaryViewOfKind:(id)a;
 - (id) indexPathsToDeleteForDecorationViewOfKind:(id)a;
 - (id) indexPathsToInsertForSupplementaryViewOfKind:(id)a;
 - (id) indexPathsToInsertForDecorationViewOfKind:(id)a;
 - (void) _setCollectionView:(id)a;
 - (void) _invalidateLayoutUsingContext:(id)a;
 - (id) _decorationViewForLayoutAttributes:(id)a;
 - (void) prepareForAnimatedBoundsChange:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - ({CGPoint=dd}) targetContentOffsetForProposedContentOffset:({CGPoint=dd})a;
 - (void) _prepareToAnimateFromCollectionViewItems:(id)aatContentOffset:({CGPoint=dd})btoItems:(id)catContentOffset:({CGPoint=dd})d;
 - (id) finalLayoutAttributesForDisappearingItemAtIndexPath:(id)a;
 - (id) finalLayoutAttributesForDisappearingSupplementaryElementOfKind:(id)aatIndexPath:(id)b;
 - (id) finalLayoutAttributesForDisappearingDecorationElementOfKind:(id)aatIndexPath:(id)b;
 - (id) initialLayoutAttributesForAppearingItemAtIndexPath:(id)a;
 - (id) initialLayoutAttributesForAppearingSupplementaryElementOfKind:(id)aatIndexPath:(id)b;
 - (id) initialLayoutAttributesForAppearingDecorationElementOfKind:(id)aatIndexPath:(id)b;
 - (void) _finalizeCollectionViewItemAnimations;
 - (void) finalizeAnimatedBoundsChange;
 - (@?) _animationForReusableView:(id)atoLayoutAttributes:(id)btype:(Q)c;
 - (void) _prepareForTransitionToLayout:(id)a;
 - (void) _prepareForTransitionFromLayout:(id)a;
 - ({CGPoint=dd}) transitionContentOffsetForProposedContentOffset:({CGPoint=dd})akeyItemIndexPath:(id)b;
 - (BOOL) _supportsAdvancedTransitionAnimations;
 - (void) _finalizeLayoutTransition;
 - (void) _didFinishLayoutTransitionAnimations:(BOOL)a;
 - ({CGPoint=dd}) targetContentOffsetForProposedContentOffset:({CGPoint=dd})awithScrollingVelocity:({CGPoint=dd})b;
 - (void) prepareForCollectionViewUpdates:(id)a;
 - ({CGPoint=dd}) updatesContentOffsetForProposedContentOffset:({CGPoint=dd})a;
 - (void) finalizeCollectionViewUpdates;
 - (id) _reorderingTargetItemIndexPathForPosition:({CGPoint=dd})awithPreviousIndexPath:(id)b;
 - (id) _invalidationContextForReorderingTargetPosition:({CGPoint=dd})atargetIndexPaths:(id)bwithPreviousPosition:({CGPoint=dd})cpreviousIndexPaths:(id)d;
 - (id) _invalidationContextForEndingReorderingItemToFinalIndexPaths:(id)apreviousIndexPaths:(id)breorderingCancelled:(BOOL)c;
 - (^{_UICollectionViewCompositionLayout=#}) _compositionLayout;
 - (@?) _animationForReusableView:(id)atoLayoutAttributes:(id)b;
 - (void) prepareForTransitionToLayout:(id)a;
 - (void) prepareForTransitionFromLayout:(id)a;
 - (void) finalizeLayoutTransition;
 - (id) _indexPathsToDeleteForSupplementaryViewOfKind:(id)a;
 - (id) _indexPathsToDeleteForDecorationViewOfKind:(id)a;
 - (id) _indexPathsToInsertForSupplementaryViewOfKind:(id)a;
 - (id) _indexPathsToInsertForDecorationViewOfKind:(id)a;
 - ({CGPoint=dd}) _offsetInTopParentLayout:(^^{_UICollectionViewCompositionLayout=#})a;
 - (id) snapshottedLayoutAttributeForItemAtIndexPath:(id)a;
 - (void) registerNib:(id)aforDecorationViewOfKind:(id)b;
 - (void) _setCollectionViewBoundsSize:({CGSize=dd})a;
 - (void) _setDynamicAnimator:(id)a;
 - (id) _dynamicAnimator;
 - (void) _setExternalObjectTable:(id)aforNibLoadingOfDecorationViewOfKind:(id)b;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) _dynamicReferenceBounds;
 - (id) _elementKinds;
 - (void) _setPrepared:(BOOL)a;
 - (id) _layoutAttributesForReorderedItemAtIndexPath:(id)awithTargetPosition:({CGPoint=dd})b;
 - (q) _sublayoutType;
 - (id) init;
 - (void) encodeWithCoder:(id)a;
 - (id) initWithCoder:(id)a;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) _frame;


@end
