
@protocol UIKeyboardInput, UITextInputPrivate;
@interface UIDefaultKeyboardInput : UIView <UIKeyboardInput, UITextInputPrivate> {

    UITextInputTraits* m_traits;
}

 - (void) dealloc;
 - (void) forwardInvocation:(id)a ;
 - (id) methodSignatureForSelector:(SEL)a ;
 - (void) setText:(id)a ;
 - (void) setSecure:(BOOL)a ;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) visibleBounds;
 - (BOOL) isEditing;
 - (id) interactionAssistant;
 - (id) selectionView;
 - (void) setSelectionWithPoint:({CGPoint=dd})a ;
 - (void) takeTraitsFrom:(id)a ;
 - (id) beginningOfDocument;
 - (id) endOfDocument;
 - (id) textRangeFromPosition:(id)a toPosition:(id)b ;
 - (id) textInRange:(id)a ;
 - (id) inputDelegate;
 - (void) setSelectedTextRange:(id)a ;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) caretRectForPosition:(id)a ;
 - (BOOL) hasText;
 - (void) deleteBackward;
 - (void) replaceRange:(id)a withText:(id)b ;
 - (id) selectedTextRange;
 - (id) markedTextRange;
 - (id) markedTextStyle;
 - (void) setMarkedTextStyle:(id)a ;
 - (void) unmarkText;
 - (id) positionFromPosition:(id)a offset:(long long)b ;
 - (id) positionFromPosition:(id)a inDirection:(long long)b offset:(long long)c ;
 - (long long) comparePosition:(id)a toPosition:(id)b ;
 - (long long) offsetFromPosition:(id)a toPosition:(id)b ;
 - (id) positionWithinRange:(id)a farthestInDirection:(long long)b ;
 - (id) characterRangeByExtendingPosition:(id)a inDirection:(long long)b ;
 - (void) setInputDelegate:(id)a ;
 - (id) tokenizer;
 - (long long) baseWritingDirectionForPosition:(id)a inDirection:(long long)b ;
 - (void) setBaseWritingDirection:(long long)a forRange:(id)b ;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) firstRectForRange:(id)a ;
 - (id) selectionRectsForRange:(id)a ;
 - (id) closestPositionToPoint:({CGPoint=dd})a ;
 - (id) closestPositionToPoint:({CGPoint=dd})a withinRange:(id)b ;
 - (id) characterRangeAtPoint:({CGPoint=dd})a ;
 - (void) selectAll;
 - (id) textColorForCaretSelection;
 - ({_NSRange=QQ}) selectionRange;
 - (BOOL) hasContent;
 - (void) updateSelection;
 - (BOOL) becomesEditableWithGestures;
 - (void) setBecomesEditableWithGestures:(BOOL)a ;
 - (id) fontForCaretSelection;
 - (id) rangeEnclosingPosition:(id)a withGranularity:(long long)b inDirection:(long long)c ;
 - (BOOL) isPosition:(id)a atBoundary:(long long)b inDirection:(long long)c ;
 - (id) positionFromPosition:(id)a toBoundary:(long long)b inDirection:(long long)c ;
 - (BOOL) isPosition:(id)a withinTextUnit:(long long)b inDirection:(long long)c ;
 - (BOOL) acceptsEmoji;
 - (void) setAcceptsEmoji:(BOOL)a ;
 - (BOOL) forceEnableDictation;
 - (void) setForceEnableDictation:(BOOL)a ;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) caretRect;
 - (void) replaceCurrentWordWithText:(id)a ;
 - (void) confirmMarkedText:(id)a ;
 - (unsigned short) characterInRelationToCaretSelection:(int)a ;
 - (unsigned short) characterAfterCaretSelection;
 - (id) rectsForNSRange:({_NSRange=QQ})a ;
 - (id) nextUnperturbedDictationResultBoundaryFromPosition:(id)a ;
 - (int) wordOffsetInRange:(id)a ;
 - (BOOL) selectionAtDocumentStart;
 - (BOOL) selectionAtWordStart;
 - (id) rangeByMovingCurrentSelection:(int)a ;
 - (id) rangeByExtendingCurrentSelection:(int)a ;
 - (void) extendCurrentSelection:(int)a ;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) convertCaretRect:({CGRect={CGPoint=dd}{CGSize=dd}})a ;
 - (BOOL) isShowingPlaceholder;
 - (void) setupPlaceholderTextIfNeeded;
 - (id) delegate;
 - (BOOL) isSecure;
 - (id) textInputTraits;
 - (BOOL) isEditable;
 - (unsigned short) characterBeforeCaretSelection;
 - (void) setMarkedText:(id)a selectedRange:({_NSRange=QQ})b ;
 - (void) insertText:(id)a ;
 - (int) selectionState;
 - (BOOL) hasSelection;
 - (id) text;


@end
