
@protocol UITextInputControllerDelegate, NSLayoutManagerDelegate, NSUITextViewCommonMethods, UIAutoscrollContainer, UITextInput, UITextAutoscrolling, UIKeyboardInput;
@interface UIFieldEditor : UIScrollView <UITextInputControllerDelegate, NSLayoutManagerDelegate, NSUITextViewCommonMethods, UIAutoscrollContainer, UITextInput, UITextAutoscrolling, UIKeyboardInput> {

    @"UITextInputController" _inputController;
    @"UITextField" _proxiedView;
    @"UIAutoscroll" _autoscroll;
    @"NSTextContainer" _textContainer;
    @"_UIFieldEditorLayoutManager" _layoutManager;
    @"_UICascadingTextStorage" _textStorage;
    {?="delegateRespondsToFieldEditorDidChange"b1"delegateRespondsToShouldInsertText"b1"delegateRespondsToShouldReplaceWithText"b1"suppressScrollToSelection"b1"clearOnNextEdit"b1} _feFlags;
    {UIEdgeInsets="top"d"left"d"bottom"d"right"d} _padding;
    @"_UIFieldEditorContentView" _contentView;
    {_NSRange="location"Q"length"Q} _unobscuredSecureRange;
    @"NSTimer" _obscureAllTextTimer;
    {CGPoint="x"d"y"d} _textContainerOrigin;
    double _contentWidth;
    @"_UIFieldEditorContentView" _passcodeStyleCutoutView;
    {CGPoint="x"d"y"d} _autoscrollContentOffset;
}
 + (void) releaseSharedInstance;
 + (id) activeFieldEditor;
 + (id) sharedFieldEditor;
 + (id) excludedElementsForHTML;

 - (void) dealloc;
 - (BOOL) respondsToSelector:(SEL)a;
 - (id) methodSignatureForSelector:(SEL)a;
 - (id) forwardingTargetForSelector:(SEL)a;
 - (void) layoutSubviews;
 - (void) setAttributedText:(id)a;
 - (id) _inputController;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) _responderExternalTouchRectForWindow:(id)a;
 - (void) setTextColor:(id)a;
 - (void) setFont:(id)a;
 - (void) setText:(id)a;
 - (id) proxiedView;
 - (id) _responderForBecomeFirstResponder;
 - (BOOL) isFirstResponder;
 - ({CGPoint=dd}) autoscrollContentOffset;
 - (void) setAutoscrollContentOffset:({CGPoint=dd})a;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) contentFrameForView:(id)a;
 - (id) attributedText;
 - (BOOL) isEditing;
 - (void) drawTextInRect:({CGRect={CGPoint=dd}{CGSize=dd}})aforContentView:(id)b;
 - (void) becomeFieldEditorForView:(id)a;
 - (void) _performWhileSuppressingDelegateNotifications:(@?)a;
 - (void) _textStorageDidProcessEditing:(id)a;
 - (BOOL) _shouldObscureInput;
 - (BOOL) _isPasscodeStyle;
 - (id) interactionAssistant;
 - (BOOL) keyboardInput:(id)ashouldInsertText:(id)bisMarkedText:(BOOL)c;
 - (BOOL) keyboardInput:(id)ashouldReplaceTextInRange:({_NSRange=QQ})breplacementText:(id)c;
 - (BOOL) keyboardInputShouldDelete:(id)a;
 - (BOOL) keyboardInputChanged:(id)a;
 - (void) keyboardInputChangedSelection:(id)a;
 - (void) scrollSelectionToVisible:(BOOL)a;
 - (id) textColor;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) _selectionClipRect;
 - (int) scrollXOffset;
 - (void) cancelAutoscroll;
 - (int) scrollYOffset;
 - (void) setScrollXOffset:(int)ascrollYOffset:(int)badjustForPurpleCaret:(BOOL)c;
 - (id) textInputView;
 - (void) _cancelObscureAllTextTimer;
 - (void) setTypingAttributes:(id)a;
 - (id) _textInputTraits;
 - (void) setSelection:({_NSRange=QQ})a;
 - (void) _obscureAllText;
 - (void) _setValue:(id)aforTextAttribute:(id)b;
 - (id) _textContainer;
 - (void) setAttributedText:(id)aandSetCaretSelectionAfterText:(BOOL)b;
 - (id) beginningOfDocument;
 - (id) endOfDocument;
 - (id) textRangeFromPosition:(id)atoPosition:(id)b;
 - (id) textInRange:(id)a;
 - (void) setText:(id)aandSetCaretSelectionAfterText:(BOOL)b;
 - (id) inputDelegate;
 - (void) addTextAlternativesDisplayStyleToRange:({_NSRange=QQ})a;
 - (void) setSelectedTextRange:(id)a;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) caretRectForPosition:(id)a;
 - (void) _scrollRangeToVisible:({_NSRange=QQ})aanimated:(BOOL)b;
 - (BOOL) drawsAsAtom;
 - (int) atomStyle;
 - (BOOL) hasText;
 - (void) clearText;
 - (id) _layoutManager;
 - ({_NSRange=QQ}) _unobscuredSecureRange;
 - (BOOL) _clearOnEditIfNeeded;
 - (void) deleteBackward;
 - (void) replaceRange:(id)awithText:(id)b;
 - (void) replaceRangeWithTextWithoutClosingTyping:(id)areplacementText:(id)b;
 - (id) selectedTextRange;
 - (id) markedTextRange;
 - (id) markedTextStyle;
 - (void) setMarkedTextStyle:(id)a;
 - (void) unmarkText;
 - (id) positionFromPosition:(id)aoffset:(long long)b;
 - (id) positionFromPosition:(id)ainDirection:(long long)boffset:(long long)c;
 - (long long) comparePosition:(id)atoPosition:(id)b;
 - (long long) offsetFromPosition:(id)atoPosition:(id)b;
 - (id) positionWithinRange:(id)afarthestInDirection:(long long)b;
 - (id) characterRangeByExtendingPosition:(id)ainDirection:(long long)b;
 - (void) setInputDelegate:(id)a;
 - (id) tokenizer;
 - (long long) baseWritingDirectionForPosition:(id)ainDirection:(long long)b;
 - (void) setBaseWritingDirection:(long long)aforRange:(id)b;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) firstRectForRange:(id)a;
 - (id) selectionRectsForRange:(id)a;
 - (id) closestPositionToPoint:({CGPoint=dd})a;
 - (id) closestPositionToPoint:({CGPoint=dd})awithinRange:(id)b;
 - (id) characterRangeAtPoint:({CGPoint=dd})a;
 - (void) insertDictationResult:(id)awithCorrectionIdentifier:(id)b;
 - (id) insertDictationResultPlaceholder;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) frameForDictationResultPlaceholder:(id)a;
 - (void) removeDictationResultPlaceholder:(id)awillInsertResult:(BOOL)b;
 - (id) rangeWithTextAlternatives:(^@)aatPosition:(id)b;
 - (id) metadataDictionariesForDictationResults;
 - (void) beginSelectionChange;
 - (void) endSelectionChange;
 - (id) _textStorage;
 - ({CGPoint=dd}) _textContainerOrigin;
 - (BOOL) _hasDictationPlaceholder;
 - (BOOL) textInput:(id)ashouldChangeCharactersInRange:({_NSRange=QQ})breplacementText:(id)c;
 - (void) textInput:(id)aprepareAttributedTextForInsertion:(id)b;
 - (void) textInputDidChange:(id)a;
 - ({_NSRange=QQ}) textInput:(id)awillChangeSelectionFromCharacterRange:({_NSRange=QQ})btoCharacterRange:({_NSRange=QQ})c;
 - (void) textInputDidChangeSelection:(id)a;
 - ({CGSize=dd}) minSize;
 - (BOOL) isHorizontallyResizable;
 - (void) setLayoutOrientation:(long long)a;
 - (void) startAutoscroll:({CGPoint=dd})a;
 - (void) setPadding:({UIEdgeInsets=dddd})a;
 - (void) selectAll;
 - (id) _textSelectingContainer;
 - (id) textColorForCaretSelection;
 - (void) updateAutoscroll:(id)a;
 - (void) setScrollXOffset:(int)ascrollYOffset:(int)b;
 - ({_NSRange=QQ}) selectionRange;
 - (void) revealSelection;
 - (unsigned long long) characterOffsetAtPoint:({CGPoint=dd})a;
 - (BOOL) hasMarkedText;
 - ({UIEdgeInsets=dddd}) padding;
 - (void) _deleteBackwardAndNotify:(BOOL)a;
 - (long long) layoutOrientation;
 - (id) linkTextAttributes;
 - (void) layoutManager:(id)adidCompleteLayoutForTextContainer:(id)batEnd:(BOOL)c;
 - (void) invalidateTextContainerOrigin;
 - (void) updateInsertionPointStateAndRestartTimer:(BOOL)a;
 - ({_NSRange=QQ}) markedRange;
 - ({UIEdgeInsets=dddd}) textContainerInset;
 - (void) setConstrainedFrameSize:({CGSize=dd})a;
 - (long long) layoutManager:(id)ashouldUseAction:(long long)bforControlCharacterAtIndex:(unsigned long long)c;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) layoutManager:(id)aboundingBoxForControlGlyphAtIndex:(unsigned long long)bforTextContainer:(id)cproposedLineFragment:({CGRect={CGPoint=dd}{CGSize=dd}})dglyphPosition:({CGPoint=dd})echaracterIndex:(unsigned long long)f;
 - (unsigned long long) layoutManager:(id)ashouldGenerateGlyphs:(r^S)bproperties:(r^q)ccharacterIndexes:(r^Q)dfont:(id)eforGlyphRange:({_NSRange=QQ})f;
 - ({CGPoint=dd}) textContainerOrigin;
 - (void) setNeedsDisplayInRect:({CGRect={CGPoint=dd}{CGSize=dd}})aavoidAdditionalLayout:(BOOL)b;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) visibleRect;
 - (void) setTextContainer:(id)a;
 - (id) typingAttributes;
 - (id) style;
 - (id) initWithFrame:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - (void) setFrame:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - (id) font;
 - (id) textInputTraits;
 - (void) setSecureTextEntry:(BOOL)a;
 - (id) undoManager;
 - (void) setMarkedText:(id)aselectedRange:({_NSRange=QQ})b;
 - (void) insertText:(id)a;
 - (void) setStyle:(id)a;
 - (id) text;


@end
