
@protocol NSCopying;
@interface UIFont : NSObject <NSCopying> {

}
@property (nonatomic, retain, readonly) NSString* familyName;
@property (nonatomic, retain, readonly) NSString* fontName;
@property (nonatomic, assign, readonly) NSNumber* pointSize;
@property (nonatomic, assign, readonly) NSNumber* ascender;
@property (nonatomic, assign, readonly) NSNumber* descender;
@property (nonatomic, assign, readonly) NSNumber* capHeight;
@property (nonatomic, assign, readonly) NSNumber* xHeight;
@property (nonatomic, assign, readonly) NSNumber* lineHeight;
@property (nonatomic, assign, readonly) NSNumber* leading;
 + (id) _ui_bulletFontForFont:(id)a;
 + (id) classFallbacksForKeyedArchiver;
 + (void) initialize;
 + (id) _ultraLightSystemFontOfSize:(double)a;
 + (double) systemFontSize;
 + (id) defaultFontForTextStyle:(id)a;
 + (id) _lightSystemFontOfSize:(double)a;
 + (id) _thinSystemFontOfSize:(double)a;
 + (double) labelFontSize;
 + (id) _opticalBoldSystemFontOfSize:(double)a;
 + (id) _opticalSystemFontOfSize:(double)a;
 + (id) systemFontOfSize:(double)a;
 + (id) userFontOfSize:(double)a;
 + (id) fontWithDescriptor:(id)asize:(double)b;
 + (id) fontWithName:(id)asize:(double)b;
 + (id) boldSystemFontOfSize:(double)a;
 + (id) _sharedFontCache;
 + (id) fontWithName:(id)asize:(double)btraits:(int)c;
 + (id) systemFontOfSize:(double)atraits:(int)b;
 + (id) systemFontOfSize:(double)aweight:(double)bdesign:(id)c;
 + (id) _systemFontsOfSize:(double)atraits:(int)b;
 + (id) preferredFontForTextStyle:(id)a;
 + (id) ib_preferredFontForTextStyle:(id)a;
 + (id) _sharedZeroPointFont;
 + (void) _evictAllItemsFromFontAndFontDescriptorCaches;
 + (id) fontWithFamilyName:(id)atraits:(int)bsize:(double)c;
 + (id) fontWithMarkupDescription:(id)a;
 + (id) familyNames;
 + (id) fontNamesForFamilyName:(id)a;
 + (id) italicSystemFontOfSize:(double)a;
 + (id) systemFontOfSize:(double)aweight:(double)b;
 + (double) buttonFontSize;
 + (double) smallSystemFontSize;
 + (id) preferredFontForUsage:(id)a;
 + (id) preferredFontForUsage:(id)acontentSizeCategoryName:(id)b;
 + (double) _readableWidth;

 - (Class) classForCoder;
 - (id) copyWithZone:(^{_NSZone=})a;
 - (id) description;
 - (double) capHeight;
 - (double) leading;
 - (double) _scaledValueForValue:(double)a;
 - (void) encodeWithCoder:(id)a;
 - (id) initWithCoder:(id)a;
 - (id) verticalFont;
 - ({CGSize=dd}) advancementForGlyph:(unsigned short)a;
 - (^{CGFont=}) _backingCGSFont;
 - (double) pointSize;
 - (BOOL) isVertical;
 - (double) xHeight;
 - (double) descender;
 - (double) _leading;
 - (double) underlineThickness;
 - (double) ascender;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) boundingRectForFont;
 - ({CGAffineTransform=dddddd}) _textMatrixTransformForContext:(^{CGContext=})a;
 - (void) getAdvancements:(^{CGSize=dd})aforCGGlyphs:(r^S)bcount:(unsigned long long)c;
 - (void) getVerticalOriginTranslations:(^{CGSize=dd})aforCGGlyphs:(r^S)bcount:(unsigned long long)c;
 - (void) setInContext:(^{CGContext=})a;
 - (unsigned long long) getCaretPositions:(^d)aforGlyph:(unsigned int)bmaximumLength:(unsigned long long)c;
 - (double) _totalAdvancementForNativeGlyphs:(r^S)acount:(long long)b;
 - (BOOL) _isDefaultFace;
 - (unsigned long long) renderingMode;
 - (id) _kernOverride;
 - (unsigned int) hyphenGlyphForLocale:(id)a;
 - (void) getBoundingRects:(^{CGRect={CGPoint=dd}{CGSize=dd}})aforCGGlyphs:(r^S)bcount:(unsigned long long)c;
 - (id) screenFontWithRenderingMode:(unsigned long long)a;
 - (double) _defaultLineHeightForUILayout;
 - (unsigned short) glyphWithName:(id)a;
 - (unsigned long long) numberOfGlyphs;
 - (id) fontWithSize:(double)a;
 - (id) fontName;
 - (id) fontDescriptor;
 - (id) coveredCharacterSet;
 - (int) traits;
 - (id) bestMatchingFontForCharacters:(r^S)alength:(unsigned long long)battributes:(id)cactualCoveredLength:(^Q)d;
 - (id) lastResortFont;
 - (double) _baseLineHeightForFont:(BOOL)a;
 - (BOOL) _getLatin1GlyphMapping:(r^^S)aandAdvanceMapping:(r^^{CGSize})b;
 - (id) initWithMarkupDescription:(id)a;
 - (BOOL) isSystemFont;
 - (double) readableWidth;
 - (double) _bodyLeading;
 - (id) initWithFamilyName:(id)atraits:(int)bsize:(double)c;
 - (BOOL) isIBTextStyleFont;
 - (id) familyName;
 - (double) lineHeight;
 - (id) familyNameForCSSFontFamilyValue;
 - (id) markupDescription;
 - (id) _alternateSystemFonts;
 - (id) initWithName:(id)asize:(double)b;
 - (id) _fontScaledByScaleFactor:(double)a;
 - (BOOL) isFixedPitch;
 - (^{__CTFont=}) CTFont;
 - (BOOL) _isHiraginoFont;
 - (double) _ascenderDeltaForBehavior:(long long)a;
 - (id) _familyName;
 - (unsigned int) _defaultGlyphForChar:(unsigned short)a;
 - (unsigned long long) mostCompatibleStringEncoding;


@end
