
@protocol NSSecureCoding;
@interface UIImage : NSObject <NSSecureCoding> {

    ^v _imageRef;
    double _scale;
    {?="named"b1"imageOrientation"b3"cached"b1"hasPattern"b1"isCIImage"b1"renderingMode"b2"suppressesAccessibilityHairlineThickening"b1"hasDecompressionInfo"b1} _imageFlags;
    @"UITraitCollection" _traitCollection;
    @"UIImageAsset" _imageAsset;
    {UIEdgeInsets="top"d"left"d"bottom"d"right"d} _alignmentRectInsets;
}
@property (nonatomic, assign, readonly) NSNumber* leftCapWidth;
@property (nonatomic, assign, readonly) NSNumber* topCapHeight;
@property (nonatomic, assign, readonly) NSNumber* size;
@property (nonatomic, assign, readonly) NSNumber* CGImage;
@property (nonatomic, assign, readonly) CIImage* CIImage;
@property (nonatomic, assign, readonly) NSNumber* imageOrientation;
@property (nonatomic, assign, readonly) NSNumber* scale;
@property (nonatomic, assign, readonly) NSArray* images;
@property (nonatomic, assign, readonly) NSNumber* duration;
@property (nonatomic, assign, readonly) NSNumber* capInsets;
@property (nonatomic, assign, readonly) NSNumber* resizingMode;
@property (nonatomic, assign, readonly) NSNumber* alignmentRectInsets;
@property (nonatomic, assign, readonly) NSNumber* renderingMode;
@property (nonatomic, copy, readwrite) UITraitCollection* traitCollection;
@property (nonatomic, retain, readwrite) UIImageAsset* imageAsset;
 + (BOOL) supportsSecureCoding;
 + (void) initialize;
 + (id) kitImageNamed:(id)a;
 + (void) _flushSharedImageCache;
 + (id) imageWithCGImage:(^{CGImage=})ascale:(double)borientation:(long long)c;
 + (id) animatedImageWithImages:(id)aduration:(double)b;
 + (void) _flushCache:(id)a;
 + (id) imageNamed:(id)ainBundle:(id)bcompatibleWithTraitCollection:(id)c;
 + (id) imageNamed:(id)a;
 + (id) _animatedImageNamed:(id)ainBundle:(id)bcompatibleWithTraitCollection:(id)cduration:(double)d;
 + (id) animatedResizableImageNamed:(id)acapInsets:({UIEdgeInsets=dddd})bresizingMode:(long long)cduration:(double)d;
 + (id) _animatedResizableImageNamed:(id)ainBundle:(id)bcompatibleWithTraitCollection:(id)ccapInsets:({UIEdgeInsets=dddd})dresizingMode:(long long)eduration:(double)f;
 + (id) _imageNamed:(id)awithTrait:(id)b;
 + (id) imageWithData:(id)a;
 + (id) imageWithData:(id)ascale:(double)b;
 + (id) imageWithCIImage:(id)a;
 + (id) imageWithCIImage:(id)ascale:(double)borientation:(long long)c;
 + ({UIEdgeInsets=dddd}) _edgeInsetsForStylePresetNames:(id)ascale:(double)b;
 + (id) animatedImageNamed:(id)aduration:(double)b;
 + (id) animatedResizableImageNamed:(id)acapInsets:({UIEdgeInsets=dddd})bduration:(double)c;
 + (id) _kitImageNamed:(id)awithTrait:(id)b;
 + (id) _backgroundGradientWithStartColor:(id)aandEndColor:(id)b;
 + (id) imageNamed:(id)ainBundle:(id)b;
 + (id) _defaultBackgroundGradient;
 + (id) imageFromAlbumArtData:(id)aheight:(int)bwidth:(int)cbytesPerRow:(int)dcache:(BOOL)e;
 + (id) imageWithContentsOfCPBitmapFile:(id)aflags:(int)b;
 + (id) _deviceSpecificImageNamed:(id)a;
 + (id) _deviceSpecificImageNamed:(id)ainBundle:(id)b;
 + (id) imageAtPath:(id)a;
 + (unsigned long long) _scaleDefinedByPath:(id)a;
 + (long long) _idiomDefinedByPath:(id)a;
 + (int) _iconVariantForUIApplicationIconFormat:(int)ascale:(^d)b;
 + (id) _iconForResourceProxy:(id)avariant:(int)bvariantsScale:(double)c;
 + (id) _applicationIconImageForBundleIdentifier:(id)aformat:(int)b;
 + (id) _tintedImageForSize:({CGSize=dd})awithTint:(id)beffectsImage:(id)cmaskImage:(id)dstyle:(int)e;
 + (id) _cachedImageForKey:(id)afromBlock:(@?)b;
 + (id) _tintedImageForSize:({CGSize=dd})awithTint:(id)bmaskImage:(id)ceffectsImage:(id)dstyle:(int)e;
 + (id) _tintedImageForSize:({CGSize=dd})awithTint:(id)bmaskImage:(id)ceffectsImage:(id)dstyle:(int)eedgeInsets:({UIEdgeInsets=dddd})f;
 + ({CGSize=dd}) _legibilityImageSizeForSize:({CGSize=dd})astyle:(long long)b;
 + (id) _iconForResourceProxy:(id)aformat:(int)b;
 + (id) imageWithCGImage:(^{CGImage=})a;
 + (id) imageWithContentsOfFile:(id)a;
 + (id) _applicationIconImageForBundleIdentifier:(id)aformat:(int)bscale:(double)c;

 - ({CGRect={CGPoint=dd}{CGSize=dd}}) bitmapRectFromImageRect:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - (id) MP_flatImageWithLinearGradientFromTopColor:(id)atoBottomColor:(id)b;
 - (id) MP_imageByOverlayingColor:(id)a;
 - (id) imageWithEtchedBorderOfColor:(id)aradius:(double)b;
 - (id) imageWithShadow:(id)a;
 - (id) initWithContentsOfFile:(id)a;
 - (double) scale;
 - (double) duration;
 - ({CGSize=dd}) size;
 - (id) copyWithZone:(^{_NSZone=})a;
 - (id) description;
 - (void) dealloc;
 - (unsigned long long) hash;
 - (BOOL) isEqual:(id)a;
 - (void) draw3PartImageWithSliceRects:({?={CGRect={CGPoint=dd}{CGSize=dd}}{CGRect={CGPoint=dd}{CGSize=dd}}{CGRect={CGPoint=dd}{CGSize=dd}}})ainRect:({CGRect={CGPoint=dd}{CGSize=dd}})boperation:(int)cfraction:(double)d;
 - (void) draw1PartImageInRect:({CGRect={CGPoint=dd}{CGSize=dd}})afraction:(double)boperation:(int)c;
 - (id) patternColor;
 - (id) traitCollection;
 - (void) drawInRect:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - (BOOL) _canEncodeWithName:(id)acoder:(id)b;
 - (void) _encodeDataWithCoder:(id)aimageName:(id)b;
 - (void) _encodePropertiesWithCoder:(id)a;
 - (void) _configureImage:(id)a;
 - (BOOL) _isResizable;
 - ({UIEdgeInsets=dddd}) capInsets;
 - (void) _setAlwaysStretches:(BOOL)a;
 - (id) _initWithOtherImage:(id)a;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) _contentStretchInPixels;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) _contentRectInPixels;
 - ({UIEdgeInsets=dddd}) alignmentRectInsets;
 - (^{CGImage=}) CGImage;
 - (long long) imageOrientation;
 - (id) initWithCGImage:(^{CGImage=})ascale:(double)borientation:(long long)c;
 - (id) resizableImageWithCapInsets:({UIEdgeInsets=dddd})a;
 - (id) imageWithAlignmentRectInsets:({UIEdgeInsets=dddd})a;
 - (BOOL) _suppressesAccessibilityHairlineThickening;
 - (BOOL) _isSubimage;
 - (BOOL) _isTiledWhenStretchedToSize:({CGSize=dd})a;
 - (id) _resizableImageWithCapMask:(int)a;
 - (id) images;
 - (id) resizableImageWithCapInsets:({UIEdgeInsets=dddd})aresizingMode:(long long)b;
 - (void) _setAlignmentRectInsets:({UIEdgeInsets=dddd})a;
 - (id) _bezeledImageWithShadowRed:(double)agreen:(double)bblue:(double)calpha:(double)dfillRed:(double)egreen:(double)fblue:(double)galpha:(double)hdrawShadow:(BOOL)i;
 - (id) _doubleBezeledImageWithExteriorShadowRed:(double)agreen:(double)bblue:(double)calpha:(double)dinteriorShadowRed:(double)egreen:(double)fblue:(double)galpha:(double)hfillRed:(double)igreen:(double)jblue:(double)kalpha:(double)l;
 - (id) _imageScaledToProportion:(double)ainterpolationQuality:(int)b;
 - (id) _imageWithStylePresets:(id)awithTintColor:(id)b;
 - (void) _preheatBitmapData;
 - (id) _decompressionInfo;
 - (void) _decompressionComplete;
 - (id) initWithData:(id)ascale:(double)b;
 - (void) _setDecompressionInfo:(id)a;
 - (void) _decompressionFallbackImageCreation;
 - (void) _saveDecompressedImage:(^{CGImage=})a;
 - (void) _startEagerDecompression;
 - (id) _initWithData:(id)aimmediateLoadWithMaxSize:({CGSize=dd})bscale:(double)crenderingIntent:(int)d;
 - (BOOL) _isDecompressing;
 - (id) initWithCIImage:(id)a;
 - (id) initWithCIImage:(id)ascale:(double)borientation:(long long)c;
 - (id) initWithContentsOfFile:(id)acache:(BOOL)b;
 - (id) _initWithData:(id)apreserveScale:(BOOL)bcache:(BOOL)c;
 - (void) _setSuppressesAccessibilityHairlineThickening:(BOOL)a;
 - (void) setTraitCollection:(id)a;
 - (id) CIImage;
 - (BOOL) _isNamed;
 - ({CGSize=dd}) _sizeInPixels;
 - (id) _cachedImageStyledWithPresets:(id)aforTintColor:(id)b;
 - (void) drawAtPoint:({CGPoint=dd})ablendMode:(int)balpha:(double)c;
 - (id) _primitiveImageAsset;
 - (id) imageWithRenderingMode:(long long)a;
 - (void) drawAtPoint:({CGPoint=dd})a;
 - (void) drawAsPatternInRect:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - (id) _automationID;
 - (id) imageAsset;
 - (void) setImageAsset:(id)a;
 - (id) _initWithData:(id)apreserveScale:(BOOL)b;
 - (id) _initWithData:(id)ascale:(double)b;
 - (id) initWithCGImage:(^{CGImage=})aimageOrientation:(long long)b;
 - (BOOL) writeToCPBitmapFile:(id)aflags:(int)b;
 - (id) _stretchableImageWithCapInsets:({UIEdgeInsets=dddd})a;
 - (id) _resizableImageWithSubimageInsets:({UIEdgeInsets=dddd})aresizeInsets:({UIEdgeInsets=dddd})b;
 - ({?=ddddddddd}) _calculateStatistics;
 - (id) _flatImageWithColor:(id)a;
 - (id) _imageThatSuppressesAccessibilityHairlineThickening;
 - (id) stretchableImageWithLeftCapWidth:(long long)atopCapHeight:(long long)b;
 - (long long) leftCapWidth;
 - (long long) topCapHeight;
 - (void) compositeToPoint:({CGPoint=dd})aoperation:(int)bfraction:(double)c;
 - (void) draw9PartImageWithSliceRects:({?={?={CGRect={CGPoint=dd}{CGSize=dd}}{CGRect={CGPoint=dd}{CGSize=dd}}{CGRect={CGPoint=dd}{CGSize=dd}}}{?={CGRect={CGPoint=dd}{CGSize=dd}}{CGRect={CGPoint=dd}{CGSize=dd}}{CGRect={CGPoint=dd}{CGSize=dd}}}{?={CGRect={CGPoint=dd}{CGSize=dd}}{CGRect={CGPoint=dd}{CGSize=dd}}{CGRect={CGPoint=dd}{CGSize=dd}}}})ainRect:({CGRect={CGPoint=dd}{CGSize=dd}})bfraction:(double)c;
 - (void) draw9PartImageWithSliceRects:({?={?={CGRect={CGPoint=dd}{CGSize=dd}}{CGRect={CGPoint=dd}{CGSize=dd}}{CGRect={CGPoint=dd}{CGSize=dd}}}{?={CGRect={CGPoint=dd}{CGSize=dd}}{CGRect={CGPoint=dd}{CGSize=dd}}{CGRect={CGPoint=dd}{CGSize=dd}}}{?={CGRect={CGPoint=dd}{CGSize=dd}}{CGRect={CGPoint=dd}{CGSize=dd}}{CGRect={CGPoint=dd}{CGSize=dd}}}})ainRect:({CGRect={CGPoint=dd}{CGSize=dd}})boperation:(int)cfraction:(double)d;
 - (void) compositeToPoint:({CGPoint=dd})afromRect:({CGRect={CGPoint=dd}{CGSize=dd}})boperation:(int)cfraction:(double)d;
 - (void) compositeToRect:({CGRect={CGPoint=dd}{CGSize=dd}})afromRect:({CGRect={CGPoint=dd}{CGSize=dd}})boperation:(int)cfraction:(double)d;
 - (void) draw3PartImageWithSliceRects:({?={CGRect={CGPoint=dd}{CGSize=dd}}{CGRect={CGPoint=dd}{CGSize=dd}}{CGRect={CGPoint=dd}{CGSize=dd}}})ainRect:({CGRect={CGPoint=dd}{CGSize=dd}})bfraction:(double)c;
 - (void) draw1PartImageInRect:({CGRect={CGPoint=dd}{CGSize=dd}})afraction:(double)b;
 - (^{CGColor=}) _tiledPatternColor;
 - (^{CGColor=}) _patternColor;
 - (^{CGImage=}) imageRef;
 - (void) compositeToPoint:({CGPoint=dd})aoperation:(int)b;
 - (void) draw9PartImageWithSliceRects:({?={?={CGRect={CGPoint=dd}{CGSize=dd}}{CGRect={CGPoint=dd}{CGSize=dd}}{CGRect={CGPoint=dd}{CGSize=dd}}}{?={CGRect={CGPoint=dd}{CGSize=dd}}{CGRect={CGPoint=dd}{CGSize=dd}}{CGRect={CGPoint=dd}{CGSize=dd}}}{?={CGRect={CGPoint=dd}{CGSize=dd}}{CGRect={CGPoint=dd}{CGSize=dd}}{CGRect={CGPoint=dd}{CGSize=dd}}}})ainRect:({CGRect={CGPoint=dd}{CGSize=dd}})b;
 - (void) draw3PartImageWithSliceRects:({?={CGRect={CGPoint=dd}{CGSize=dd}}{CGRect={CGPoint=dd}{CGSize=dd}}{CGRect={CGPoint=dd}{CGSize=dd}}})ainRect:({CGRect={CGPoint=dd}{CGSize=dd}})b;
 - (void) draw1PartImageInRect:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - (void) _setCached:(BOOL)a;
 - (BOOL) _isCached;
 - (void) _setNamed:(BOOL)a;
 - (BOOL) _isInvisibleAndGetIsTranslucent:(^B)a;
 - (id) _flatImageWithWhite:(double)aalpha:(double)b;
 - (id) _serializedData;
 - (id) _applicationIconImageForFormat:(int)aprecomposed:(BOOL)bscale:(double)c;
 - (id) _applicationIconImageForFormat:(int)aprecomposed:(BOOL)b;
 - (id) _applyBackdropViewSettings:(id)aallowImageResizing:(BOOL)b;
 - (id) _applyBackdropViewSettings:(id)aincludeTints:(BOOL)bincludeBlur:(BOOL)callowImageResizing:(BOOL)d;
 - (id) _applyBackdropViewStyle:(long long)aincludeTints:(BOOL)bincludeBlur:(BOOL)cgraphicsQuality:(long long)d;
 - (id) _applyBackdropViewStyle:(long long)aincludeTints:(BOOL)bincludeBlur:(BOOL)cgraphicsQuality:(long long)dallowImageResizing:(BOOL)e;
 - (id) _applyBackdropViewSettings:(id)a;
 - (id) _applyBackdropViewSettings:(id)aincludeTints:(BOOL)bincludeBlur:(BOOL)c;
 - (id) _applyBackdropViewStyle:(long long)aincludeTints:(BOOL)bincludeBlur:(BOOL)c;
 - (id) _subimageInRect:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - (id) _selectedTabBarItemImageWithTintColor:(id)ametrics:(long long)bstyle:(long long)cforScreenScale:(double)d;
 - (id) _unselectedTabBarItemImageWithTintColor:(id)ametrics:(long long)bstyle:(long long)cforScreenScale:(double)d;
 - (id) _tabBarItemImageWithTintColor:(id)aselected:(BOOL)bmetrics:(long long)cstyle:(long long)dforScreenScale:(double)e;
 - (id) _imageForLegibilitySettings:(id)astrength:(double)b;
 - (void) _drawImageForLegibilitySettings:(id)astrength:(double)bsize:({CGSize=dd})c;
 - (id) _imageForLegibilityStyle:(long long)a;
 - (void) _drawImageForLegibilityStyle:(long long)asize:({CGSize=dd})b;
 - (id) _imageWithBrightnessModifiedForLegibilityStyle:(long long)a;
 - (void) encodeWithCoder:(id)a;
 - (id) initWithCoder:(id)a;
 - (id) initWithData:(id)a;
 - (void) drawInRect:({CGRect={CGPoint=dd}{CGSize=dd}})ablendMode:(int)balpha:(double)c;
 - (long long) renderingMode;
 - (long long) resizingMode;
 - (id) initWithCGImage:(^{CGImage=})a;
 - (id) initWithData:(id)acache:(BOOL)b;


@end
