
@protocol NSSecureCoding;
@interface UIImage : NSObject <NSSecureCoding> {

    ^v _imageRef;
    d _scale;
    {?="named"b1"imageOrientation"b3"cached"b1"hasPattern"b1"isCIImage"b1"renderingMode"b2"suppressesAccessibilityHairlineThickening"b1"hasDecompressionInfo"b1} _imageFlags;
    @"UITraitCollection" _traitCollection;
    @"UIImageAsset" _imageAsset;
    {UIEdgeInsets="top"d"left"d"bottom"d"right"d} _alignmentRectInsets;
}
@property (nonatomic, assign, readonly) NSNumber* leftCapWidth;
@property (nonatomic, assign, readonly) NSNumber* topCapHeight;
@property (nonatomic, assign, readonly) NSNumber* size;
@property (nonatomic, assign, readonly) NSNumber* CGImage;
@property (nonatomic, assign, readonly) CIImage* CIImage;
@property (nonatomic, assign, readonly) NSNumber* imageOrientation;
@property (nonatomic, assign, readonly) NSNumber* scale;
@property (nonatomic, assign, readonly) NSArray* images;
@property (nonatomic, assign, readonly) NSNumber* duration;
@property (nonatomic, assign, readonly) NSNumber* capInsets;
@property (nonatomic, assign, readonly) NSNumber* resizingMode;
@property (nonatomic, assign, readonly) NSNumber* alignmentRectInsets;
@property (nonatomic, assign, readonly) NSNumber* renderingMode;
@property (nonatomic, copy, readwrite) UITraitCollection* traitCollection;
@property (nonatomic, retain, readwrite) UIImageAsset* imageAsset;
 + (BOOL) supportsSecureCoding;
 + (void) initialize;
 + (id) kitImageNamed:(id)a;
 + (void) _flushSharedImageCache;
 + (id) imageWithCGImage:(^{CGImage=})ascale:(d)borientation:(q)c;
 + (id) animatedImageWithImages:(id)aduration:(d)b;
 + (void) _flushCache:(id)a;
 + (id) imageNamed:(id)ainBundle:(id)bcompatibleWithTraitCollection:(id)c;
 + (id) imageNamed:(id)a;
 + (id) _animatedImageNamed:(id)ainBundle:(id)bcompatibleWithTraitCollection:(id)cduration:(d)d;
 + (id) animatedResizableImageNamed:(id)acapInsets:({UIEdgeInsets=dddd})bresizingMode:(q)cduration:(d)d;
 + (id) _animatedResizableImageNamed:(id)ainBundle:(id)bcompatibleWithTraitCollection:(id)ccapInsets:({UIEdgeInsets=dddd})dresizingMode:(q)eduration:(d)f;
 + (id) _imageNamed:(id)awithTrait:(id)b;
 + (id) imageWithData:(id)a;
 + (id) imageWithData:(id)ascale:(d)b;
 + (id) imageWithCIImage:(id)a;
 + (id) imageWithCIImage:(id)ascale:(d)borientation:(q)c;
 + ({UIEdgeInsets=dddd}) _edgeInsetsForStylePresetNames:(id)ascale:(d)b;
 + (id) animatedImageNamed:(id)aduration:(d)b;
 + (id) animatedResizableImageNamed:(id)acapInsets:({UIEdgeInsets=dddd})bduration:(d)c;
 + (id) _kitImageNamed:(id)awithTrait:(id)b;
 + (id) _backgroundGradientWithStartColor:(id)aandEndColor:(id)b;
 + (id) imageNamed:(id)ainBundle:(id)b;
 + (id) _defaultBackgroundGradient;
 + (id) imageFromAlbumArtData:(id)aheight:(i)bwidth:(i)cbytesPerRow:(i)dcache:(BOOL)e;
 + (id) imageWithContentsOfCPBitmapFile:(id)aflags:(i)b;
 + (id) _deviceSpecificImageNamed:(id)a;
 + (id) _deviceSpecificImageNamed:(id)ainBundle:(id)b;
 + (id) imageAtPath:(id)a;
 + (Q) _scaleDefinedByPath:(id)a;
 + (q) _idiomDefinedByPath:(id)a;
 + (i) _iconVariantForUIApplicationIconFormat:(i)ascale:(^d)b;
 + (id) _iconForResourceProxy:(id)avariant:(i)bvariantsScale:(d)c;
 + (id) _applicationIconImageForBundleIdentifier:(id)aformat:(i)b;
 + (id) _tintedImageForSize:({CGSize=dd})awithTint:(id)beffectsImage:(id)cmaskImage:(id)dstyle:(i)e;
 + (id) _cachedImageForKey:(id)afromBlock:(@?)b;
 + (id) _tintedImageForSize:({CGSize=dd})awithTint:(id)bmaskImage:(id)ceffectsImage:(id)dstyle:(i)e;
 + (id) _tintedImageForSize:({CGSize=dd})awithTint:(id)bmaskImage:(id)ceffectsImage:(id)dstyle:(i)eedgeInsets:({UIEdgeInsets=dddd})f;
 + ({CGSize=dd}) _legibilityImageSizeForSize:({CGSize=dd})astyle:(q)b;
 + (id) _iconForResourceProxy:(id)aformat:(i)b;
 + (id) imageWithCGImage:(^{CGImage=})a;
 + (id) imageWithContentsOfFile:(id)a;
 + (id) _applicationIconImageForBundleIdentifier:(id)aformat:(i)bscale:(d)c;

 - ({CGRect={CGPoint=dd}{CGSize=dd}}) bitmapRectFromImageRect:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - (id) MP_flatImageWithLinearGradientFromTopColor:(id)atoBottomColor:(id)b;
 - (id) MP_imageByOverlayingColor:(id)a;
 - (id) imageWithEtchedBorderOfColor:(id)aradius:(d)b;
 - (id) imageWithShadow:(id)a;
 - (id) initWithContentsOfFile:(id)a;
 - (d) scale;
 - (d) duration;
 - ({CGSize=dd}) size;
 - (id) copyWithZone:(^{_NSZone=})a;
 - (id) description;
 - (void) dealloc;
 - (Q) hash;
 - (BOOL) isEqual:(id)a;
 - (void) draw3PartImageWithSliceRects:({?={CGRect={CGPoint=dd}{CGSize=dd}}{CGRect={CGPoint=dd}{CGSize=dd}}{CGRect={CGPoint=dd}{CGSize=dd}}})ainRect:({CGRect={CGPoint=dd}{CGSize=dd}})boperation:(i)cfraction:(d)d;
 - (void) draw1PartImageInRect:({CGRect={CGPoint=dd}{CGSize=dd}})afraction:(d)boperation:(i)c;
 - (id) patternColor;
 - (id) traitCollection;
 - (void) drawInRect:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - (BOOL) _canEncodeWithName:(id)acoder:(id)b;
 - (void) _encodeDataWithCoder:(id)aimageName:(id)b;
 - (void) _encodePropertiesWithCoder:(id)a;
 - (void) _configureImage:(id)a;
 - (BOOL) _isResizable;
 - ({UIEdgeInsets=dddd}) capInsets;
 - (void) _setAlwaysStretches:(BOOL)a;
 - (id) _initWithOtherImage:(id)a;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) _contentStretchInPixels;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) _contentRectInPixels;
 - ({UIEdgeInsets=dddd}) alignmentRectInsets;
 - (^{CGImage=}) CGImage;
 - (q) imageOrientation;
 - (id) initWithCGImage:(^{CGImage=})ascale:(d)borientation:(q)c;
 - (id) resizableImageWithCapInsets:({UIEdgeInsets=dddd})a;
 - (id) imageWithAlignmentRectInsets:({UIEdgeInsets=dddd})a;
 - (BOOL) _suppressesAccessibilityHairlineThickening;
 - (BOOL) _isSubimage;
 - (BOOL) _isTiledWhenStretchedToSize:({CGSize=dd})a;
 - (id) _resizableImageWithCapMask:(i)a;
 - (id) images;
 - (id) resizableImageWithCapInsets:({UIEdgeInsets=dddd})aresizingMode:(q)b;
 - (void) _setAlignmentRectInsets:({UIEdgeInsets=dddd})a;
 - (id) _bezeledImageWithShadowRed:(d)agreen:(d)bblue:(d)calpha:(d)dfillRed:(d)egreen:(d)fblue:(d)galpha:(d)hdrawShadow:(BOOL)i;
 - (id) _doubleBezeledImageWithExteriorShadowRed:(d)agreen:(d)bblue:(d)calpha:(d)dinteriorShadowRed:(d)egreen:(d)fblue:(d)galpha:(d)hfillRed:(d)igreen:(d)jblue:(d)kalpha:(d)l;
 - (id) _imageScaledToProportion:(d)ainterpolationQuality:(i)b;
 - (id) _imageWithStylePresets:(id)awithTintColor:(id)b;
 - (void) _preheatBitmapData;
 - (id) _decompressionInfo;
 - (void) _decompressionComplete;
 - (id) initWithData:(id)ascale:(d)b;
 - (void) _setDecompressionInfo:(id)a;
 - (void) _decompressionFallbackImageCreation;
 - (void) _saveDecompressedImage:(^{CGImage=})a;
 - (void) _startEagerDecompression;
 - (id) _initWithData:(id)aimmediateLoadWithMaxSize:({CGSize=dd})bscale:(d)crenderingIntent:(i)d;
 - (BOOL) _isDecompressing;
 - (id) initWithCIImage:(id)a;
 - (id) initWithCIImage:(id)ascale:(d)borientation:(q)c;
 - (id) initWithContentsOfFile:(id)acache:(BOOL)b;
 - (id) _initWithData:(id)apreserveScale:(BOOL)bcache:(BOOL)c;
 - (void) _setSuppressesAccessibilityHairlineThickening:(BOOL)a;
 - (void) setTraitCollection:(id)a;
 - (id) CIImage;
 - (BOOL) _isNamed;
 - ({CGSize=dd}) _sizeInPixels;
 - (id) _cachedImageStyledWithPresets:(id)aforTintColor:(id)b;
 - (void) drawAtPoint:({CGPoint=dd})ablendMode:(i)balpha:(d)c;
 - (id) _primitiveImageAsset;
 - (id) imageWithRenderingMode:(q)a;
 - (void) drawAtPoint:({CGPoint=dd})a;
 - (void) drawAsPatternInRect:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - (id) _automationID;
 - (id) imageAsset;
 - (void) setImageAsset:(id)a;
 - (id) _initWithData:(id)apreserveScale:(BOOL)b;
 - (id) _initWithData:(id)ascale:(d)b;
 - (id) initWithCGImage:(^{CGImage=})aimageOrientation:(q)b;
 - (BOOL) writeToCPBitmapFile:(id)aflags:(i)b;
 - (id) _stretchableImageWithCapInsets:({UIEdgeInsets=dddd})a;
 - (id) _resizableImageWithSubimageInsets:({UIEdgeInsets=dddd})aresizeInsets:({UIEdgeInsets=dddd})b;
 - ({?=ddddddddd}) _calculateStatistics;
 - (id) _flatImageWithColor:(id)a;
 - (id) _imageThatSuppressesAccessibilityHairlineThickening;
 - (id) stretchableImageWithLeftCapWidth:(q)atopCapHeight:(q)b;
 - (q) leftCapWidth;
 - (q) topCapHeight;
 - (void) compositeToPoint:({CGPoint=dd})aoperation:(i)bfraction:(d)c;
 - (void) draw9PartImageWithSliceRects:({?={?={CGRect={CGPoint=dd}{CGSize=dd}}{CGRect={CGPoint=dd}{CGSize=dd}}{CGRect={CGPoint=dd}{CGSize=dd}}}{?={CGRect={CGPoint=dd}{CGSize=dd}}{CGRect={CGPoint=dd}{CGSize=dd}}{CGRect={CGPoint=dd}{CGSize=dd}}}{?={CGRect={CGPoint=dd}{CGSize=dd}}{CGRect={CGPoint=dd}{CGSize=dd}}{CGRect={CGPoint=dd}{CGSize=dd}}}})ainRect:({CGRect={CGPoint=dd}{CGSize=dd}})bfraction:(d)c;
 - (void) draw9PartImageWithSliceRects:({?={?={CGRect={CGPoint=dd}{CGSize=dd}}{CGRect={CGPoint=dd}{CGSize=dd}}{CGRect={CGPoint=dd}{CGSize=dd}}}{?={CGRect={CGPoint=dd}{CGSize=dd}}{CGRect={CGPoint=dd}{CGSize=dd}}{CGRect={CGPoint=dd}{CGSize=dd}}}{?={CGRect={CGPoint=dd}{CGSize=dd}}{CGRect={CGPoint=dd}{CGSize=dd}}{CGRect={CGPoint=dd}{CGSize=dd}}}})ainRect:({CGRect={CGPoint=dd}{CGSize=dd}})boperation:(i)cfraction:(d)d;
 - (void) compositeToPoint:({CGPoint=dd})afromRect:({CGRect={CGPoint=dd}{CGSize=dd}})boperation:(i)cfraction:(d)d;
 - (void) compositeToRect:({CGRect={CGPoint=dd}{CGSize=dd}})afromRect:({CGRect={CGPoint=dd}{CGSize=dd}})boperation:(i)cfraction:(d)d;
 - (void) draw3PartImageWithSliceRects:({?={CGRect={CGPoint=dd}{CGSize=dd}}{CGRect={CGPoint=dd}{CGSize=dd}}{CGRect={CGPoint=dd}{CGSize=dd}}})ainRect:({CGRect={CGPoint=dd}{CGSize=dd}})bfraction:(d)c;
 - (void) draw1PartImageInRect:({CGRect={CGPoint=dd}{CGSize=dd}})afraction:(d)b;
 - (^{CGColor=}) _tiledPatternColor;
 - (^{CGColor=}) _patternColor;
 - (^{CGImage=}) imageRef;
 - (void) compositeToPoint:({CGPoint=dd})aoperation:(i)b;
 - (void) draw9PartImageWithSliceRects:({?={?={CGRect={CGPoint=dd}{CGSize=dd}}{CGRect={CGPoint=dd}{CGSize=dd}}{CGRect={CGPoint=dd}{CGSize=dd}}}{?={CGRect={CGPoint=dd}{CGSize=dd}}{CGRect={CGPoint=dd}{CGSize=dd}}{CGRect={CGPoint=dd}{CGSize=dd}}}{?={CGRect={CGPoint=dd}{CGSize=dd}}{CGRect={CGPoint=dd}{CGSize=dd}}{CGRect={CGPoint=dd}{CGSize=dd}}}})ainRect:({CGRect={CGPoint=dd}{CGSize=dd}})b;
 - (void) draw3PartImageWithSliceRects:({?={CGRect={CGPoint=dd}{CGSize=dd}}{CGRect={CGPoint=dd}{CGSize=dd}}{CGRect={CGPoint=dd}{CGSize=dd}}})ainRect:({CGRect={CGPoint=dd}{CGSize=dd}})b;
 - (void) draw1PartImageInRect:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - (void) _setCached:(BOOL)a;
 - (BOOL) _isCached;
 - (void) _setNamed:(BOOL)a;
 - (BOOL) _isInvisibleAndGetIsTranslucent:(^B)a;
 - (id) _flatImageWithWhite:(d)aalpha:(d)b;
 - (id) _serializedData;
 - (id) _applicationIconImageForFormat:(i)aprecomposed:(BOOL)bscale:(d)c;
 - (id) _applicationIconImageForFormat:(i)aprecomposed:(BOOL)b;
 - (id) _applyBackdropViewSettings:(id)aallowImageResizing:(BOOL)b;
 - (id) _applyBackdropViewSettings:(id)aincludeTints:(BOOL)bincludeBlur:(BOOL)callowImageResizing:(BOOL)d;
 - (id) _applyBackdropViewStyle:(q)aincludeTints:(BOOL)bincludeBlur:(BOOL)cgraphicsQuality:(q)d;
 - (id) _applyBackdropViewStyle:(q)aincludeTints:(BOOL)bincludeBlur:(BOOL)cgraphicsQuality:(q)dallowImageResizing:(BOOL)e;
 - (id) _applyBackdropViewSettings:(id)a;
 - (id) _applyBackdropViewSettings:(id)aincludeTints:(BOOL)bincludeBlur:(BOOL)c;
 - (id) _applyBackdropViewStyle:(q)aincludeTints:(BOOL)bincludeBlur:(BOOL)c;
 - (id) _subimageInRect:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - (id) _selectedTabBarItemImageWithTintColor:(id)ametrics:(q)bstyle:(q)cforScreenScale:(d)d;
 - (id) _unselectedTabBarItemImageWithTintColor:(id)ametrics:(q)bstyle:(q)cforScreenScale:(d)d;
 - (id) _tabBarItemImageWithTintColor:(id)aselected:(BOOL)bmetrics:(q)cstyle:(q)dforScreenScale:(d)e;
 - (id) _imageForLegibilitySettings:(id)astrength:(d)b;
 - (void) _drawImageForLegibilitySettings:(id)astrength:(d)bsize:({CGSize=dd})c;
 - (id) _imageForLegibilityStyle:(q)a;
 - (void) _drawImageForLegibilityStyle:(q)asize:({CGSize=dd})b;
 - (id) _imageWithBrightnessModifiedForLegibilityStyle:(q)a;
 - (void) encodeWithCoder:(id)a;
 - (id) initWithCoder:(id)a;
 - (id) initWithData:(id)a;
 - (void) drawInRect:({CGRect={CGPoint=dd}{CGSize=dd}})ablendMode:(i)balpha:(d)c;
 - (q) renderingMode;
 - (q) resizingMode;
 - (id) initWithCGImage:(^{CGImage=})a;
 - (id) initWithData:(id)acache:(BOOL)b;


@end
