
@protocol UIScrollViewIntersectionDelegate, UIKeyboardKeyplaneTransitionDelegate, UIGestureRecognizerDelegate, UIInputViewAnimationHost, _UIRemoteKeyboardViewSource;
@interface UIInputWindowController : UIViewController <UIScrollViewIntersectionDelegate, UIKeyboardKeyplaneTransitionDelegate, UIGestureRecognizerDelegate, UIInputViewAnimationHost, _UIRemoteKeyboardViewSource> {

    NSMutableArray* _animationStyleStack;
    BOOL _suppressedCallbacks;
    BOOL _suppressedNotifications;
    BOOL _isChangingPlacement;
    BOOL _isChangingInputViews;
    BOOL _requiresConstraintUpdate;
    int _hiddenCount;
    unsigned long long _rotationState;
    NSMutableDictionary* _inputViewEdgeConstraints;
    NSMutableDictionary* _accessoryViewEdgeConstraints;
    NSMutableDictionary* _inputBackdropViewEdgeConstraints;
    NSMutableDictionary* _accessoryBackdropViewEdgeConstraints;
    UIView* _preRotationSnapshot;
    {CGSize="width"d"height"d} _preRotationInputViewSize;
    {CGSize="width"d"height"d} _preRotationInputAccessoryViewSize;
    {CGAffineTransform="a"d"b"d"c"d"d"d"tx"d"ty"d} _preRotationInputViewTransform;
    {CGAffineTransform="a"d"b"d"c"d"d"d"tx"d"ty"d} _preRotationInputAccessoryViewTransform;
    BOOL _isTranslating;
    BOOL _isSplitting;
    BOOL _splitLockState;
    CADisplayLink* _displayLink;
    double _lastBounceTime;
    double _lastTranslationNotificationTime;
    double _targetTranslation;
    double _initialTranslation;
    double _translationVelocity;
    UIPanGestureRecognizer* _translateRecognizer;
    @? _bounceCompletionBlock;
    BOOL _prevInputViewIsOnScreen;
    SEL _interactiveTransitionCleanupSelector;
    UIScrollView* _scrollViewForTransition;
    BOOL _scrollViewTransitionFinishing;
    BOOL _scrollViewShowsHorizontalScrollIndicator;
    {CGPoint="x"d"y"d} _scrollViewTransitionPreviousPoint;
    UIInputViewSetNotificationInfo* _scrollViewNotificationInfo;
    {CGRect="origin"{CGPoint="x"d"y"d}"size"{CGSize="width"d"height"d}} _preLayoutHostViewFrame;
    BOOL _didOverridePreLayoutHostViewFrame;
    BOOL _didPostLayoutNotification;
    UIInputViewSetNotificationInfo* _keyboardHeightChangeNotificationInfo;
    BOOL _wasOnScreen;
    NSString* _lastKeyboardID;
    BOOL _shouldNotifyRemoteKeyboards;
    UIView* _hostView;
    UIInputViewSet* _inputViewSet;
    UIInputViewSetPlacement* _placement;
    UIInputViewController* _inputViewController;
    UIInputViewController* _inputAccessoryViewController;
    UIKBInputBackdropView* _inputBackdropView;
    UIKBInputBackdropView* _inputAccessoryBackdropView;
    NSArray* _visibilityConstraints;
    NSLayoutConstraint* _verticalVisibilityConstraint;
    UIInputViewSetPlacement* _postRotationPlacement;
    UIInputViewSet* _postRotationInputViewSet;
    UIInputViewSetNotificationInfo* _templateNotificationInfo;
    UIInputViewPlacementTransition* _currentTransition;
    <_UIRemoteKeyboardControllerDelegate>* _controllerDelegate;
    NSLayoutConstraint* _inputViewHeightConstraint;
    NSLayoutConstraint* _accessoryViewHeightConstraint;
}
 + (BOOL) _doesOverrideLegacyFullScreenLayout;
 + (BOOL) _shouldForwardViewWillTransitionToSize;
 + (id) tranformedUserInfoForNotificationName:(id)auserInfo:(id)b;

 - (void) dealloc;
 - (id) containerView;
 - (BOOL) gestureRecognizerShouldBegin:(id)a ;
 - (BOOL) gestureRecognizer:(id)a shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)b ;
 - (BOOL) gestureRecognizer:(id)a shouldReceiveTouch:(id)b ;
 - (void) didReceiveMemoryWarning;
 - (BOOL) shouldAutorotate;
 - (unsigned long long) supportedInterfaceOrientations;
 - (BOOL) isRotating;
 - (void) window:(id)a statusBarWillChangeFromHeight:(double)b toHeight:(double)c ;
 - (void) viewWillLayoutSubviews;
 - (void) viewDidLayoutSubviews;
 - (void) scrollView:(id)a didPanWithGesture:(id)b ;
 - (void) scrollView:(id)a didFinishPanGesture:(id)b ;
 - (void) pushAnimationStyle:(id)a ;
 - (void) popAnimationStyle;
 - (void) transitionDidFinish:(BOOL)a ;
 - (id) initWithNibName:(id)a bundle:(id)b ;
 - (void) loadView;
 - (BOOL) shouldAutorotateToInterfaceOrientation:(long long)a ;
 - (void) viewDidLoad;
 - (void) willRotateToInterfaceOrientation:(long long)a duration:(double)b ;
 - (void) willAnimateRotationToInterfaceOrientation:(long long)a duration:(double)b ;
 - (void) didRotateFromInterfaceOrientation:(long long)a ;
 - (void) _getRotationContentSettings:(^{?=BBBBBdi})a ;
 - (void) updateViewConstraints;
 - (id) transitioningView;
 - (void) updateToPlacement:(id)a withNormalAnimationsAndNotifications:(BOOL)b ;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) transitioningFrame;
 - (void) setInputViewsHidden:(BOOL)a ;
 - (int) _clipCornersOfView:(id)a ;
 - (void) updateProgress:(double)a startHeight:(double)b endHeight:(double)c ;
 - (id) placement;
 - (BOOL) isUndocked;
 - (BOOL) isSplitting;
 - (void) prepareKeyboardHeightChangeWithDelta:(double)a duration:(double)b ;
 - (void) keyboardHeightChangeDone;
 - (BOOL) isOnScreen;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) visibleFrame;
 - (id) _inputView;
 - (id) _inputAccessoryView;
 - (BOOL) isTranslating;
 - (id) inputViewSnapshotOfView:(id)a afterScreenUpdates:(BOOL)b ;
 - (void) prepareForTransition;
 - (void) finishTransitionWithCompletion:(@?)a ;
 - (id) hostView;
 - (void) setCurrentTransition:(id)a ;
 - (id) currentTransition;
 - (void) translateDetected:(id)a ;
 - (void) initializeTranslateGestureRecognizer;
 - (BOOL) isChangingPlacement;
 - (void) undock;
 - (void) dock;
 - (void) invalidateDisplayLink;
 - (void) bounceAnimationDidFinish;
 - (void) _prepareForRotationToOrientation:(long long)a duration:(double)b ;
 - (void) _rotateToOrientation:(long long)a duration:(double)b ;
 - (void) _finishRotationFromInterfaceOrientation:(long long)a ;
 - (id) nextAnimationStyle;
 - (void) setAccessoryViewVisible:(BOOL)a delay:(double)b ;
 - (void) _updateBounceAnimation:(id)a ;
 - (void) syncToExistingAnimations;
 - (void) translateToPlacement:(id)a ;
 - (void) performOperations:(@?)a withAnimationStyle:(id)b ;
 - (id) inputViewSet;
 - (void) setPlacement:(id)a ;
 - (void) setRotationAwarePlacement:(id)a ;
 - (void) finishScrollViewTransition;
 - (void) setInputViewSet:(id)a ;
 - (void) extendKeyboardBackdropHeight:(double)a withDuration:(double)b ;
 - (void) animateAccessoryViewVisibility:(BOOL)a withDuration:(double)b ;
 - (void) hideScrollViewHorizontalScrollIndicator:(BOOL)a ;
 - (void) updateScrollViewContentInsetBottom:(double)a ;
 - (void) candidateBarWillChangeHeight:(double)a withDuration:(double)b ;
 - (id) _inputViewController;
 - (id) _inputBackdropView;
 - (id) _inputAccessoryBackdropView;
 - (void) willResume:(id)a ;
 - (void) didSuspend:(id)a ;
 - (BOOL) shouldNotifyRemoteKeyboards;
 - (void) setShouldNotifyRemoteKeyboards:(BOOL)a ;
 - (void) checkPlaceholdersForRemoteKeyboards;
 - (id) controllerDelegate;
 - (void) setControllerDelegate:(id)a ;
 - (void) updateViewSizingConstraints;
 - (void) registerPowerLogEvent:(BOOL)a ;
 - (void) performWithSafeTransitionFrames:(@?)a ;
 - (void) _updateBackdropViews;
 - (void) _forcePreLayoutHostViewFrame;
 - (void) performWithoutAppearanceCallbacks:(@?)a ;
 - (void) setTemplateNotificationInfo:(id)a ;
 - (id) viewMatchingConstraintForAttribute:(long long)a primaryView:(id)b secondaryView:(id)c ;
 - (id) inputViewHeightConstraint;
 - (void) setInputViewHeightConstraint:(id)a ;
 - (id) accessoryViewHeightConstraint;
 - (void) setAccessoryViewHeightConstraint:(id)a ;
 - (void) clearViewSizingConstraints:(unsigned long long)a ;
 - (BOOL) _subviewUsesClassicLayout:(id)a ;
 - ({UIEdgeInsets=dddd}) _aligningInsetsForChildInputViewController:(id)a ;
 - (id) _inputAccessoryViewController;
 - (void) updateConstraintInsets;
 - (void) rebuildConstraints:(id)a forView:(id)b toMatchView:(id)c ;
 - (void) updateVisibilityConstraintsForPlacement:(id)a ;
 - (id) visibilityConstraints;
 - (void) setVerticalVisibilityConstraint:(id)a ;
 - (void) setVisibilityConstraints:(id)a ;
 - (id) templateNotificationInfo;
 - (int) appearStateForChild:(unsigned long long)a placement:(id)b start:(BOOL)c ;
 - (void) changeChild:(unsigned long long)a toAppearState:(int)b animated:(BOOL)c ;
 - (void) postStartNotifications:(unsigned long long)a withInfo:(id)b ;
 - (void) postEndNotifications:(unsigned long long)a withInfo:(id)b ;
 - (void) clearInteractiveTransitionStateIfNecessary;
 - (BOOL) mergeTransitionIfNecessaryWithTransition:(id)a ;
 - (id) initialNotificationInfo;
 - (void) updateAppearStatesForPlacement:(id)a start:(BOOL)b animated:(BOOL)c ;
 - (void) performWithoutCallbacksOrNotifications:(@?)a ;
 - (id) _viewControllerForAutorotation;
 - (void) setPostRotationPlacement:(id)a ;
 - (id) postRotationPlacement;
 - (BOOL) _useLiveRotation;
 - (id) postRotationInputViewSet;
 - (void) setPostRotationInputViewSet:(id)a ;
 - (void) setPlacement:(id)a starting:(@?)b completion:(@?)c ;
 - (void) set_inputViewController:(id)a ;
 - (void) setInputBackdropView:(id)a ;
 - (void) set_inputAccessoryViewController:(id)a ;
 - (void) setInputAccessoryBackdropView:(id)a ;
 - (unsigned long long) changeToInputViewSet:(id)a ;
 - (void) performOperations:(@?)a withTemplateNotificationInfo:(id)b ;
 - (void) moveFromPlacement:(id)a toPlacement:(id)b starting:(@?)c completion:(@?)d ;
 - (void) setInputView:(id)a accessoryView:(id)b ;
 - (void) setInterfaceAutorotationDisabled:(BOOL)a ;
 - (id) verticalVisibilityConstraint;
 - (unsigned long long) keyboardDismissModeForPublicMode:(long long)a ;
 - (void) fillInNotificationInfo:(id)a forDismissMode:(unsigned long long)b ;
 - (void) completeKeyboardDismiss:(unsigned long long)a ;
 - (void) postTransitionEndNotification;


@end
