
@protocol NSCopying;
@interface UIKBTree : NSObject <NSCopying> {

    i type;
    @"NSString" name;
    @"NSMutableDictionary" properties;
    @"NSMutableArray" subtrees;
    @"NSMutableDictionary" cache;
    @"NSString" layoutTag;
}
@property (nonatomic, assign, readwrite) NSNumber* type;
@property (nonatomic, retain, readwrite) NSString* name;
@property (nonatomic, retain, readwrite) NSMutableDictionary* properties;
@property (nonatomic, retain, readwrite) NSMutableArray* subtrees;
@property (nonatomic, retain, readwrite) NSMutableDictionary* cache;
@property (nonatomic, retain, readwrite) NSString* layoutTag;
 + (id) treeOfType:(i)a;
 + (id) keyboard;
 + (q) extraIPhoneIdiom:(q)awidth:(d)blandscape:(BOOL)c;
 + (id) uniqueName;
 + (id) stringForType:(i)a;
 + (id) shapesForControlKeyShapes:(id)aoptions:(i)b;
 + (BOOL) shouldSkipCacheString:(id)a;
 + (id) mergeStringForKeyName:(id)a;
 + (id) key;

 - (id) copyWithZone:(^{_NSZone=})a;
 - (id) description;
 - (void) dealloc;
 - (void) setType:(i)a;
 - (id) name;
 - (BOOL) isSplit;
 - (void) setDisplayString:(id)a;
 - (void) setRepresentedString:(id)a;
 - (void) setDisplayType:(i)a;
 - (void) setInteractionType:(i)a;
 - (id) representedString;
 - (void) setDisplayTypeHint:(i)a;
 - (void) setOverrideDisplayString:(id)a;
 - (void) setSelectedVariantIndex:(q)a;
 - (void) setVariantPopupBias:(id)a;
 - (void) setSubtrees:(id)a;
 - (void) setVariantType:(i)a;
 - (void) setShape:(id)a;
 - (void) setParentKey:(id)a;
 - (BOOL) setObject:(id)aforProperty:(id)b;
 - (q) selectedVariantIndex;
 - (id) subtrees;
 - (id) objectForProperty:(id)a;
 - (void) setTextAlignment:(q)a;
 - (id) recursiveDescription;
 - (q) textAlignment;
 - (void) setVisualStyling:({?=b6b1b1b8b16})a;
 - ({?=b6b1b1b8b16}) visualStyling;
 - (void) setLayoutTag:(id)a;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) frameForKeylayoutName:(id)a;
 - (BOOL) usesAutoShift;
 - (BOOL) isShiftKeyPlaneChooser;
 - (id) keyplaneForKey:(id)a;
 - (i) displayType;
 - (id) geometry;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) paddedFrame;
 - (void) setPaddedFrame:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - (i) interactionType;
 - (i) clipCorners;
 - (id) shape;
 - (BOOL) disabled;
 - (i) visualStyle;
 - (q) intForProperty:(id)a;
 - (i) rendering;
 - (i) displayTypeHint;
 - (void) setClipCorners:(i)a;
 - (void) setGeometry:(id)a;
 - (id) cachedKeysByKeyName:(id)a;
 - (id) layoutName;
 - (id) stringForProperty:(id)a;
 - (id) subtreeWithName:(id)a;
 - (id) keysWithString:(id)a;
 - (void) setVisualStyle:(i)a;
 - (id) keys;
 - (id) fullRepresentedString;
 - (id) firstCachedKeyWithName:(id)a;
 - (void) setRendering:(i)a;
 - (id) autolocalizedKeyCacheIterator;
 - (id) localizationKey;
 - (BOOL) looksLikeShiftAlternate;
 - (BOOL) isShiftKeyplane;
 - (id) shiftAlternateKeyplaneName;
 - (id) keysByKeyName:(id)a;
 - (void) zipGeometrySet;
 - (void) setIsGenerated:(BOOL)a;
 - (void) precacheLayoutName:(id)a;
 - (void) elaborateLayoutWithSize:({CGSize=dd})ascale:(d)b;
 - (id) keySet;
 - (id) numberForProperty:(id)a;
 - (void) setDisplayRowHint:(i)a;
 - (void) setFlickDirection:(q)a;
 - (BOOL) notUseCandidateSelection;
 - (i) variantType;
 - (void) setHighlightedVariantsList:(id)a;
 - (id) keysForMergeConditions;
 - (id) mergeKeyNames:(id)a;
 - (void) updateMoreAndInternationalKeysWithOptions:(i)a;
 - (q) handBias;
 - (BOOL) supportsType:(q)a;
 - (BOOL) ghost;
 - (BOOL) isExemptFromInputManagerHitTesting;
 - (BOOL) isExemptFromInputManagerLayout;
 - (BOOL) usesKeyCharging;
 - (BOOL) shouldSkipCandidateSelectionForVariants;
 - (BOOL) forceMultitap;
 - (BOOL) hasLayoutTag:(id)a;
 - (id) overrideDisplayString;
 - (id) componentName;
 - (void) updateVariantTypeForActions:(I)a;
 - (BOOL) noLanguageIndicator;
 - (id) keysOrderedByPositionWithoutZip;
 - (i) displayRowHint;
 - (BOOL) avoidsLanguageIndicator;
 - (d) primaryKeylayoutWidthRatio;
 - (id) parentKey;
 - (id) alternateKeyplaneName;
 - (BOOL) modifiesKeyplane;
 - (i) dragThreshold;
 - (q) flickDirection;
 - (BOOL) behavesAsShiftKey;
 - (BOOL) boolForProperty:(id)a;
 - (BOOL) dynamicDisplayTypeHint;
 - (d) primaryKeylayoutOffset;
 - (void) setProperties:(id)a;
 - (BOOL) isLeafType;
 - (void) setCache:(id)a;
 - (BOOL) isSameAsTree:(id)a;
 - (BOOL) isGenerated;
 - (BOOL) _needsScaling;
 - (id) geometrySet:(BOOL)a;
 - (id) attributeSet:(BOOL)a;
 - (void) zipGeometries:(BOOL)aattributes:(BOOL)b;
 - (id) listShapes;
 - (q) _keyCountOnNamedRow:(id)a;
 - (id) geometriesList;
 - (id) activeShapesFromOutputShapes:(id)ainputShapes:(id)b;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) _keyplaneFrame;
 - ({?=b6b1b1b8b16}) stylingFromVisualStyle;
 - (id) unhashedName;
 - (id) _cacheRootNameForKey:(id)a;
 - (BOOL) shouldCacheKey;
 - (void) cacheKey:(id)a;
 - (void) _addKeylayoutKeys:(id)a;
 - (id) geometries;
 - (id) subtreeWithType:(i)a;
 - (void) subsumeDisappearingKeyName:(id)aintoKeyName:(id)bfactors:(id)c;
 - (id) findLeftMoreKey;
 - (void) updateDictationKeyOnNumberPads:(BOOL)a;
 - (id) activeGeometriesList;
 - (i) _variantType;
 - (BOOL) _renderAsStringKey;
 - (id) nameFromAttributes;
 - (BOOL) isHashed;
 - (id) initWithType:(i)awithName:(id)bwithProperties:(id)cwithSubtrees:(id)dwithCache:(id)e;
 - (BOOL) isEqualToTree:(id)a;
 - (BOOL) isDuplicateOfTree:(id)a;
 - (id) subtreeWithName:(id)arows:(id)b;
 - (id) subtreesWithProperty:(id)avalue:(id)b;
 - (i) indexOfSubtree:(id)a;
 - (void) zipAttributes;
 - (BOOL) subtreesAreOrdered;
 - (id) keyForString:(id)a;
 - (id) keyAttributes;
 - (void) clearTransientCaches;
 - (id) keysOrderedByPosition;
 - (id) geometriesOrderedByPosition;
 - (BOOL) usesAdaptiveKeys;
 - (BOOL) isLetters;
 - (BOOL) looksLike:(id)a;
 - (void) setGeometriesList:(id)a;
 - (void) setActiveGeometriesList:(id)a;
 - (id) highlightedVariantsList;
 - (q) highlightedVariantIndex;
 - (void) setGhost:(BOOL)a;
 - (id) variantPopupBias;
 - (i) splitMode;
 - (void) setSplitMode:(i)a;
 - (void) setForceMultitap:(BOOL)a;
 - (BOOL) canFadeOutFromState:(i)atoState:(i)b;
 - (d) fadeOutDuration;
 - (BOOL) avoidAutoDeactivation;
 - (BOOL) disablesEdgeSwipe;
 - (BOOL) containsDividerVariant;
 - (void) orderVariantKeys:(BOOL)a;
 - (id) variantDisplayString;
 - (id) cacheDisplayString;
 - (BOOL) renderKeyInKeyplane:(id)a;
 - (i) state;
 - (void) setState:(i)a;
 - (id) properties;
 - (i) type;
 - (void) setName:(id)a;
 - (void) setAttributes:(id)a;
 - (id) cache;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) frame;
 - (void) setFrame:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - (void) setVisible:(BOOL)a;
 - (BOOL) visible;
 - (id) initWithType:(i)a;
 - (id) layoutTag;
 - (id) displayString;
 - (BOOL) isAlphabeticPlane;
 - (BOOL) shouldSkipCandidateSelection;
 - (void) setDisabled:(BOOL)a;


@end
