
@protocol NSCopying;
@interface UIKBTree : NSObject <NSCopying> {

    int type;
    NSString* name;
    NSMutableDictionary* properties;
    NSMutableArray* subtrees;
    NSMutableDictionary* cache;
    NSString* layoutTag;
}
@property (nonatomic, assign, readwrite) NSNumber* type;
@property (nonatomic, retain, readwrite) NSString* name;
@property (nonatomic, retain, readwrite) NSMutableDictionary* properties;
@property (nonatomic, retain, readwrite) NSMutableArray* subtrees;
@property (nonatomic, retain, readwrite) NSMutableDictionary* cache;
@property (nonatomic, retain, readwrite) NSString* layoutTag;
 + (id) treeOfType:(int)a;
 + (id) keyboard;
 + (long long) extraIPhoneIdiom:(long long)awidth:(double)blandscape:(BOOL)c;
 + (id) uniqueName;
 + (id) stringForType:(int)a;
 + (id) shapesForControlKeyShapes:(id)aoptions:(int)b;
 + (BOOL) shouldSkipCacheString:(id)a;
 + (id) mergeStringForKeyName:(id)a;
 + (id) key;

 - (id) copyWithZone:(^{_NSZone=})a;
 - (id) description;
 - (void) dealloc;
 - (void) setType:(int)a;
 - (id) name;
 - (BOOL) isSplit;
 - (void) setDisplayString:(id)a;
 - (void) setRepresentedString:(id)a;
 - (void) setDisplayType:(int)a;
 - (void) setInteractionType:(int)a;
 - (id) representedString;
 - (void) setDisplayTypeHint:(int)a;
 - (void) setOverrideDisplayString:(id)a;
 - (void) setSelectedVariantIndex:(long long)a;
 - (void) setVariantPopupBias:(id)a;
 - (void) setSubtrees:(id)a;
 - (void) setVariantType:(int)a;
 - (void) setShape:(id)a;
 - (void) setParentKey:(id)a;
 - (BOOL) setObject:(id)aforProperty:(id)b;
 - (long long) selectedVariantIndex;
 - (id) subtrees;
 - (id) objectForProperty:(id)a;
 - (void) setTextAlignment:(long long)a;
 - (id) recursiveDescription;
 - (long long) textAlignment;
 - (void) setVisualStyling:({?=b6b1b1b8b16})a;
 - ({?=b6b1b1b8b16}) visualStyling;
 - (void) setLayoutTag:(id)a;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) frameForKeylayoutName:(id)a;
 - (BOOL) usesAutoShift;
 - (BOOL) isShiftKeyPlaneChooser;
 - (id) keyplaneForKey:(id)a;
 - (int) displayType;
 - (id) geometry;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) paddedFrame;
 - (void) setPaddedFrame:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - (int) interactionType;
 - (int) clipCorners;
 - (id) shape;
 - (BOOL) disabled;
 - (int) visualStyle;
 - (long long) intForProperty:(id)a;
 - (int) rendering;
 - (int) displayTypeHint;
 - (void) setClipCorners:(int)a;
 - (void) setGeometry:(id)a;
 - (id) cachedKeysByKeyName:(id)a;
 - (id) layoutName;
 - (id) stringForProperty:(id)a;
 - (id) subtreeWithName:(id)a;
 - (id) keysWithString:(id)a;
 - (void) setVisualStyle:(int)a;
 - (id) keys;
 - (id) fullRepresentedString;
 - (id) firstCachedKeyWithName:(id)a;
 - (void) setRendering:(int)a;
 - (id) autolocalizedKeyCacheIterator;
 - (id) localizationKey;
 - (BOOL) looksLikeShiftAlternate;
 - (BOOL) isShiftKeyplane;
 - (id) shiftAlternateKeyplaneName;
 - (id) keysByKeyName:(id)a;
 - (void) zipGeometrySet;
 - (void) setIsGenerated:(BOOL)a;
 - (void) precacheLayoutName:(id)a;
 - (void) elaborateLayoutWithSize:({CGSize=dd})ascale:(double)b;
 - (id) keySet;
 - (id) numberForProperty:(id)a;
 - (void) setDisplayRowHint:(int)a;
 - (void) setFlickDirection:(long long)a;
 - (BOOL) notUseCandidateSelection;
 - (int) variantType;
 - (void) setHighlightedVariantsList:(id)a;
 - (id) keysForMergeConditions;
 - (id) mergeKeyNames:(id)a;
 - (void) updateMoreAndInternationalKeysWithOptions:(int)a;
 - (long long) handBias;
 - (BOOL) supportsType:(long long)a;
 - (BOOL) ghost;
 - (BOOL) isExemptFromInputManagerHitTesting;
 - (BOOL) isExemptFromInputManagerLayout;
 - (BOOL) usesKeyCharging;
 - (BOOL) shouldSkipCandidateSelectionForVariants;
 - (BOOL) forceMultitap;
 - (BOOL) hasLayoutTag:(id)a;
 - (id) overrideDisplayString;
 - (id) componentName;
 - (void) updateVariantTypeForActions:(unsigned int)a;
 - (BOOL) noLanguageIndicator;
 - (id) keysOrderedByPositionWithoutZip;
 - (int) displayRowHint;
 - (BOOL) avoidsLanguageIndicator;
 - (double) primaryKeylayoutWidthRatio;
 - (id) parentKey;
 - (id) alternateKeyplaneName;
 - (BOOL) modifiesKeyplane;
 - (int) dragThreshold;
 - (long long) flickDirection;
 - (BOOL) behavesAsShiftKey;
 - (BOOL) boolForProperty:(id)a;
 - (BOOL) dynamicDisplayTypeHint;
 - (double) primaryKeylayoutOffset;
 - (void) setProperties:(id)a;
 - (BOOL) isLeafType;
 - (void) setCache:(id)a;
 - (BOOL) isSameAsTree:(id)a;
 - (BOOL) isGenerated;
 - (BOOL) _needsScaling;
 - (id) geometrySet:(BOOL)a;
 - (id) attributeSet:(BOOL)a;
 - (void) zipGeometries:(BOOL)aattributes:(BOOL)b;
 - (id) listShapes;
 - (long long) _keyCountOnNamedRow:(id)a;
 - (id) geometriesList;
 - (id) activeShapesFromOutputShapes:(id)ainputShapes:(id)b;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) _keyplaneFrame;
 - ({?=b6b1b1b8b16}) stylingFromVisualStyle;
 - (id) unhashedName;
 - (id) _cacheRootNameForKey:(id)a;
 - (BOOL) shouldCacheKey;
 - (void) cacheKey:(id)a;
 - (void) _addKeylayoutKeys:(id)a;
 - (id) geometries;
 - (id) subtreeWithType:(int)a;
 - (void) subsumeDisappearingKeyName:(id)aintoKeyName:(id)bfactors:(id)c;
 - (id) findLeftMoreKey;
 - (void) updateDictationKeyOnNumberPads:(BOOL)a;
 - (id) activeGeometriesList;
 - (int) _variantType;
 - (BOOL) _renderAsStringKey;
 - (id) nameFromAttributes;
 - (BOOL) isHashed;
 - (id) initWithType:(int)awithName:(id)bwithProperties:(id)cwithSubtrees:(id)dwithCache:(id)e;
 - (BOOL) isEqualToTree:(id)a;
 - (BOOL) isDuplicateOfTree:(id)a;
 - (id) subtreeWithName:(id)arows:(id)b;
 - (id) subtreesWithProperty:(id)avalue:(id)b;
 - (int) indexOfSubtree:(id)a;
 - (void) zipAttributes;
 - (BOOL) subtreesAreOrdered;
 - (id) keyForString:(id)a;
 - (id) keyAttributes;
 - (void) clearTransientCaches;
 - (id) keysOrderedByPosition;
 - (id) geometriesOrderedByPosition;
 - (BOOL) usesAdaptiveKeys;
 - (BOOL) isLetters;
 - (BOOL) looksLike:(id)a;
 - (void) setGeometriesList:(id)a;
 - (void) setActiveGeometriesList:(id)a;
 - (id) highlightedVariantsList;
 - (long long) highlightedVariantIndex;
 - (void) setGhost:(BOOL)a;
 - (id) variantPopupBias;
 - (int) splitMode;
 - (void) setSplitMode:(int)a;
 - (void) setForceMultitap:(BOOL)a;
 - (BOOL) canFadeOutFromState:(int)atoState:(int)b;
 - (double) fadeOutDuration;
 - (BOOL) avoidAutoDeactivation;
 - (BOOL) disablesEdgeSwipe;
 - (BOOL) containsDividerVariant;
 - (void) orderVariantKeys:(BOOL)a;
 - (id) variantDisplayString;
 - (id) cacheDisplayString;
 - (BOOL) renderKeyInKeyplane:(id)a;
 - (int) state;
 - (void) setState:(int)a;
 - (id) properties;
 - (int) type;
 - (void) setName:(id)a;
 - (void) setAttributes:(id)a;
 - (id) cache;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) frame;
 - (void) setFrame:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - (void) setVisible:(BOOL)a;
 - (BOOL) visible;
 - (id) initWithType:(int)a;
 - (id) layoutTag;
 - (id) displayString;
 - (BOOL) isAlphabeticPlane;
 - (BOOL) shouldSkipCandidateSelection;
 - (void) setDisabled:(BOOL)a;


@end
