
@interface UIKBRenderFactory : NSObject {

    UIKBRenderConfig _renderConfig;
    NSMutableArray _segmentTraits;
    double _rivenSizeFactor;
    BOOL _lightweightFactory;
    double _scale;
    BOOL _boldTextEnabled;
}
@property (nonatomic, assign, readwrite) NSNumber* scale;
@property (nonatomic, assign, readonly) UIKBRenderConfig* renderConfig;
@property (nonatomic, assign, readonly) NSArray* segmentTraits;
@property (nonatomic, assign, readwrite) NSNumber* rivenSizeFactor;
@property (nonatomic, assign, readwrite) NSNumber* lightweightFactory;
@property (nonatomic, assign, readonly) NSNumber* boldTextEnabled;
 + (BOOL) _enabled;
 + (long long) _graphicsQuality;
 + (id) lightweightFactoryForVisualStyle:({?=b6b1b1b8b16})arenderConfig:(id)b;
 + (id) factoryForVisualStyle:({?=b6b1b1b8b16})arenderConfig:(id)b;
 + (id) cacheKeyForString:(id)awithRenderFlags:(long long)brenderConfig:(id)c;
 + (id) segmentedControlColor:(BOOL)a;
 + (Class) factoryClassForVisualStyle:({?=b6b1b1b8b16})a;

 - (double) scale;
 - (void) dealloc;
 - (id) renderConfig;
 - (id) backgroundTraitsForKeyplane:(id)a;
 - (id) defaultKeyBackgroundColorName;
 - (id) controlKeyBackgroundColorName;
 - (id) traitsHashStringForKey:(id)awithGeometry:(id)bcontrolOpacities:(BOOL)c;
 - (id) _traitsForKey:(id)aonKeyplane:(id)b;
 - (id) lightKeycapsFontName;
 - (void) _customizeTraits:(id)aforPopupForKey:(id)bwithRenderConfig:(id)ckeycapsFontName:(id)d;
 - (double) translucentGapWidth;
 - (id) lightTextFontName;
 - (BOOL) lightweightFactory;
 - (id) traitsForKey:(id)aonKeyplane:(id)b;
 - (BOOL) shouldClearBaseDisplayStringForVariants:(id)a;
 - (id) lightPadKeycapsFontName;
 - (void) modifyTraitsForDetachedInputSwitcher:(id)awithKey:(id)b;
 - (id) thinKeycapsFontName;
 - (double) keyCornerRadius;
 - (double) RivenFactor:(double)a;
 - (id) displayContentsForKey:(id)a;
 - (id) _controlKeyBackgroundColorName;
 - (long long) enabledBlendForm;
 - (void) removeAllLayoutSegments;
 - (BOOL) useBlueThemingForKey:(id)a;
 - (void) addLayoutSegment:(id)a;
 - (long long) lightHighQualityEnabledBlendForm;
 - (id) controlKeyForegroundColorName;
 - (id) multitapCompleteKeyImageName;
 - (id) muttitapReverseKeyImageName;
 - (void) setupLayoutSegments;
 - (void) scaleTraits:(id)a;
 - (id) shiftKeyImageName;
 - (id) shiftOnKeyImageName;
 - (id) shiftLockImageName;
 - (id) initWithRenderConfig:(id)askipLayoutSegments:(BOOL)b;
 - (void) setLightweightFactory:(BOOL)a;
 - (double) emojiPopupDividerKeyOffset;
 - (void) lowQualityTraits:(id)a;
 - (id) segmentTraits;
 - (id) hashStringElement;
 - (id) deleteKeyImageName;
 - (double) skinnyKeyThreshold;
 - (id) keyImageNameWithSkinnyVariation:(id)a;
 - (id) handwritingMoreKeyImageName;
 - (id) globalEmojiKeyImageName;
 - (id) globalKeyImageName;
 - (id) dismissKeyImageName;
 - (id) dictationKeyImageName;
 - (id) leftArrowKeyImageName;
 - (id) rightArrowKeyImageName;
 - (id) cutKeyImageName;
 - (id) copyKeyImageName;
 - (id) pasteKeyImageName;
 - (id) undoKeyImageName;
 - (id) boldKeyImageName;
 - (id) biuKeyImageName;
 - (id) defaultKeyShadowColorName;
 - (void) modifyTraitsForDividerVariant:(id)awithKey:(id)b;
 - (id) controlKeyShadowColorName;
 - (id) thinTextFontName;
 - (double) rivenSizeFactor;
 - (void) setRivenSizeFactor:(double)a;
 - (BOOL) boldTextEnabled;
 - (double) passcodeEdgeWeight;
 - (id) passcodeKeyEdgeColorName;
 - (id) passcodeActiveControlKeyTraits;
 - (void) modifyKeyTraitsForPasscode:(id)aforKey:(id)bonKeyplane:(id)c;
 - (id) passcodeBackgroundTraitsForKeyplane:(id)a;
 - (id) passcodeControlKeyTraits;
 - (id) passcodeShiftedControlKeyTraits;
 - (id) extraPasscodePaddleTraits;
 - (void) setScale:(double)a;


@end
