
@protocol UIKeyboardCandidateList, UIKeyboardCandidateListDelegate, UIKeyboardCandidateGridCollectionViewControllerDelegate, UIKeyboardCandidateRowViewControllerDelegate;
@interface UIKeyboardCandidateGrid : UIView <UIKeyboardCandidateList, UIKeyboardCandidateListDelegate, UIKeyboardCandidateGridCollectionViewControllerDelegate, UIKeyboardCandidateRowViewControllerDelegate> {

    @"UIImageView" _backgroundView;
    @"UIView" _topBarShadow;
    @"UIView" _bottomBarShadow;
    @"UIKeyboardCandidateSortControl" _sortBar;
    @"UIKeyboardCandidateGridHeader" _gridHeader;
    BOOL _drawTopShadow;
    BOOL _drawBottomShadow;
    BOOL _secondaryCandidatesViewIsCurrent;
    i _candidatesVisualStyle;
    @"<UIKeyboardCandidateListDelegate>" _candidateListDelegate;
    @"TIKeyboardCandidateResultSet" _candidateSet;
    @"NSMutableDictionary" _collectionViewControllers;
    @"UIKeyboardCandidateGridCollectionViewController" _collectionViewController;
    Q _numberOfColumns;
    @"<UICollectionViewDelegate>" _scrollViewDelegate;
    @"UIKBBackdropView" _backdropView;
    @"NSArray" _sortedCandidates;
    @"NSString" _inlineText;
    @"UIKeyboardCandidateRowViewController" _secondaryCandidatesViewController;
}

 - (void) dealloc;
 - (void) layoutSubviews;
 - (void) scrollViewDidScroll:(id)a;
 - (void) scrollViewWillBeginDragging:(id)a;
 - (void) showCandidateAtIndex:(Q)a;
 - (void) showNextCandidate;
 - (id) candidateListDelegate;
 - (void) candidateListAcceptCandidate:(id)a;
 - (id) candidateSet;
 - (void) setCandidateSet:(id)a;
 - (void) setCandidates:(id)ainlineText:(id)binlineRect:({CGRect={CGPoint=dd}{CGSize=dd}})cmaxX:(d)dlayout:(BOOL)e;
 - (void) setCandidateListDelegate:(id)a;
 - (id) statisticsIdentifier;
 - (void) candidateListSelectionDidChange:(id)a;
 - (BOOL) isExtendedList;
 - (BOOL) isHiddenCandidatesList;
 - (void) setUIKeyboardCandidateListDelegate:(id)a;
 - (BOOL) showCandidate:(id)a;
 - (void) showPreviousCandidate;
 - (void) showNextPage;
 - (void) showPreviousPage;
 - (void) showNextRow;
 - (void) showPreviousRow;
 - (Q) currentIndex;
 - (void) candidateAcceptedAtIndex:(Q)a;
 - (id) keyboardBehaviors;
 - (Q) selectedSortIndex;
 - (void) setCandidates:(id)atype:(i)binlineText:(id)cinlineRect:({CGRect={CGPoint=dd}{CGSize=dd}})dmaxX:(d)elayout:(BOOL)f;
 - (void) setInlineText:(id)a;
 - (BOOL) handleNumberKey:(Q)a;
 - (BOOL) handleTabKeyWithShift:(BOOL)a;
 - (BOOL) hasNextPage;
 - (BOOL) hasPreviousPage;
 - (void) candidatesDidChange;
 - (void) revealHiddenCandidates;
 - (id) inlineText;
 - (void) setCandidatesVisualStyle:(i)a;
 - (i) candidatesVisualStyle;
 - (BOOL) padInlineFloatingViewIsExpanded:(id)a;
 - (void) setSecondaryCandidatesViewIsCurrent:(BOOL)a;
 - (BOOL) secondaryCandidatesViewIsCurrent;
 - (Q) gridCollectionViewNumberOfColumns:(id)a;
 - (Q) gridCollectionViewSelectedSortMethodIndex:(id)a;
 - (void) candidateViewWillBeginExtendingWithVisibleCandidates:(id)a;
 - (void) candidateViewDidFinishExtending;
 - (void) candidateListShouldBeDismissed:(id)a;
 - (id) collectionViewController;
 - (void) setCollectionViewController:(id)a;
 - (void) sortSelectionBarAction:(id)a;
 - (void) setBackdropView:(id)a;
 - (id) backdropView;
 - (void) setDrawTopShadow:(BOOL)a;
 - (void) setDrawBottomShadow:(BOOL)a;
 - (void) statusBarFrameWillChange:(id)a;
 - (void) setSortBar:(id)a;
 - (void) setGridHeader:(id)a;
 - (id) sortBar;
 - (BOOL) drawTopShadow;
 - (BOOL) drawBottomShadow;
 - (id) secondaryCandidatesViewController;
 - (void) setSecondaryCandidatesViewController:(id)a;
 - (id) gridHeader;
 - (void) clearViews;
 - (id) collectionViewControllers;
 - (id) scrollViewDelegate;
 - (void) showArrowButton:(BOOL)a;
 - (void) setScrollViewDelegate:(id)a;
 - (id) sortedCandidates;
 - (void) setSortedCandidates:(id)a;
 - (Q) numberOfColumns;
 - (void) layout;
 - (void) setNumberOfColumns:(Q)a;
 - (id) initWithFrame:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - (id) currentCandidate;
 - (BOOL) hasCandidates;


@end
