
@protocol UIKeyboardCandidateList, UIKeyboardCandidateListDelegate, UIKeyboardCandidateGridCollectionViewControllerDelegate, UIKeyboardCandidateRowViewControllerDelegate;
@interface UIKeyboardCandidateGrid : UIView <UIKeyboardCandidateList, UIKeyboardCandidateListDelegate, UIKeyboardCandidateGridCollectionViewControllerDelegate, UIKeyboardCandidateRowViewControllerDelegate> {

    UIImageView* _backgroundView;
    UIView* _topBarShadow;
    UIView* _bottomBarShadow;
    UIKeyboardCandidateSortControl* _sortBar;
    UIKeyboardCandidateGridHeader* _gridHeader;
    BOOL _drawTopShadow;
    BOOL _drawBottomShadow;
    BOOL _secondaryCandidatesViewIsCurrent;
    int _candidatesVisualStyle;
    <UIKeyboardCandidateListDelegate>* _candidateListDelegate;
    TIKeyboardCandidateResultSet* _candidateSet;
    NSMutableDictionary* _collectionViewControllers;
    UIKeyboardCandidateGridCollectionViewController* _collectionViewController;
    unsigned long long _numberOfColumns;
    <UICollectionViewDelegate>* _scrollViewDelegate;
    UIKBBackdropView* _backdropView;
    NSArray* _sortedCandidates;
    NSString* _inlineText;
    UIKeyboardCandidateRowViewController* _secondaryCandidatesViewController;
}

 - (void) dealloc;
 - (void) layoutSubviews;
 - (void) scrollViewDidScroll:(id)a;
 - (void) scrollViewWillBeginDragging:(id)a;
 - (void) showCandidateAtIndex:(unsigned long long)a;
 - (void) showNextCandidate;
 - (id) candidateListDelegate;
 - (void) candidateListAcceptCandidate:(id)a;
 - (id) candidateSet;
 - (void) setCandidateSet:(id)a;
 - (void) setCandidates:(id)ainlineText:(id)binlineRect:({CGRect={CGPoint=dd}{CGSize=dd}})cmaxX:(double)dlayout:(BOOL)e;
 - (void) setCandidateListDelegate:(id)a;
 - (id) statisticsIdentifier;
 - (void) candidateListSelectionDidChange:(id)a;
 - (BOOL) isExtendedList;
 - (BOOL) isHiddenCandidatesList;
 - (void) setUIKeyboardCandidateListDelegate:(id)a;
 - (BOOL) showCandidate:(id)a;
 - (void) showPreviousCandidate;
 - (void) showNextPage;
 - (void) showPreviousPage;
 - (void) showNextRow;
 - (void) showPreviousRow;
 - (unsigned long long) currentIndex;
 - (void) candidateAcceptedAtIndex:(unsigned long long)a;
 - (id) keyboardBehaviors;
 - (unsigned long long) selectedSortIndex;
 - (void) setCandidates:(id)atype:(int)binlineText:(id)cinlineRect:({CGRect={CGPoint=dd}{CGSize=dd}})dmaxX:(double)elayout:(BOOL)f;
 - (void) setInlineText:(id)a;
 - (BOOL) handleNumberKey:(unsigned long long)a;
 - (BOOL) handleTabKeyWithShift:(BOOL)a;
 - (BOOL) hasNextPage;
 - (BOOL) hasPreviousPage;
 - (void) candidatesDidChange;
 - (void) revealHiddenCandidates;
 - (id) inlineText;
 - (void) setCandidatesVisualStyle:(int)a;
 - (int) candidatesVisualStyle;
 - (BOOL) padInlineFloatingViewIsExpanded:(id)a;
 - (void) setSecondaryCandidatesViewIsCurrent:(BOOL)a;
 - (BOOL) secondaryCandidatesViewIsCurrent;
 - (unsigned long long) gridCollectionViewNumberOfColumns:(id)a;
 - (unsigned long long) gridCollectionViewSelectedSortMethodIndex:(id)a;
 - (void) candidateViewWillBeginExtendingWithVisibleCandidates:(id)a;
 - (void) candidateViewDidFinishExtending;
 - (void) candidateListShouldBeDismissed:(id)a;
 - (id) collectionViewController;
 - (void) setCollectionViewController:(id)a;
 - (void) sortSelectionBarAction:(id)a;
 - (void) setBackdropView:(id)a;
 - (id) backdropView;
 - (void) setDrawTopShadow:(BOOL)a;
 - (void) setDrawBottomShadow:(BOOL)a;
 - (void) statusBarFrameWillChange:(id)a;
 - (void) setSortBar:(id)a;
 - (void) setGridHeader:(id)a;
 - (id) sortBar;
 - (BOOL) drawTopShadow;
 - (BOOL) drawBottomShadow;
 - (id) secondaryCandidatesViewController;
 - (void) setSecondaryCandidatesViewController:(id)a;
 - (id) gridHeader;
 - (void) clearViews;
 - (id) collectionViewControllers;
 - (id) scrollViewDelegate;
 - (void) showArrowButton:(BOOL)a;
 - (void) setScrollViewDelegate:(id)a;
 - (id) sortedCandidates;
 - (void) setSortedCandidates:(id)a;
 - (unsigned long long) numberOfColumns;
 - (void) layout;
 - (void) setNumberOfColumns:(unsigned long long)a;
 - (id) initWithFrame:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - (id) currentCandidate;
 - (BOOL) hasCandidates;


@end
