
@protocol _UIIVCResponseDelegateImpl, UIKeyboardCandidateListDelegate;
@interface UIKeyboardImpl : UIView <_UIIVCResponseDelegateImpl, UIKeyboardCandidateListDelegate> {

    <UIKeyInput>* m_delegate;
    UIKeyboardTaskQueue* m_taskQueue;
    @? m_externalTask;
    TIKeyboardState* m_keyboardState;
    TIKeyboardInputManagerState* m_inputManagerState;
    UIView* m_languageIndicator;
    NSString* m_previousInputString;
    UIKeyboardAutocorrectionController* m_autocorrectionController;
    UIAutocorrectInlinePrompt* m_autocorrectPrompt;
    TIKeyboardCandidateResultSet* m_candidateResultSet;
    <UIKeyboardCandidateList>* m_candidateList;
    UIView* m_markedTextOverlay;
    <UIKeyboardImplGeometryDelegate>* m_geometryDelegate;
    NSObject<UIKeyboardRecording><UIApplicationEventRecording>* m_recorder;
    UIKeyboardLayout* m_layout;
    NSMutableDictionary* m_keyedLayouts;
    UIKeyboardScheduledTask* m_autoDeleteTask;
    unsigned int m_autoDeleteCount;
    double m_autoDeleteLastDelete;
    double m_autoDeleteInterval;
    unsigned int m_autoDeleteShiftCharacter;
    UIDelayedAction* m_longPressAction;
    long long m_orientation;
    long long m_originalOrientation;
    {CGPoint="x"d"y"d} m_inputPoint;
    int m_changeCount;
    double m_changeTime;
    id m_changedDelegate;
    ^{__CFRunLoopObserver=} m_observer;
    unsigned long long m_textInputChangingCount;
    BOOL m_textInputChangingText;
    BOOL m_textInputChangingDirection;
    BOOL m_textInputChangesIgnored;
    BOOL m_insideKeyInputDelegateCall;
    UITextInputTraits* m_defaultTraits;
    UITextInputTraits* m_traits;
    int m_returnKeyState;
    long long m_currentDirection;
    BOOL m_autoDeleteOK;
    BOOL m_autocapitalizationPreference;
    BOOL m_autocorrectionPreference;
    BOOL m_autoshift;
    BOOL m_caretShowingNow;
    BOOL m_changeNotificationDisabled;
    BOOL m_correctionLearningAllowed;
    BOOL m_delegateIsSMSTextView;
    BOOL m_delegateRequiresKeyEvents;
    BOOL m_doubleSpacePeriodWasAppliedInCurrentContext;
    BOOL m_doubleSpacePeriodPreference;
    BOOL m_hardwareKeyboardAttached;
    BOOL m_inDealloc;
    BOOL m_initializationDone;
    BOOL m_performanceLoggingEnabled;
    BOOL m_selecting;
    BOOL m_shift;
    BOOL m_shiftLocked;
    BOOL m_shiftLockedEnabled;
    BOOL m_settingShift;
    BOOL m_suggestionsShownForCurrentDeletion;
    BOOL m_originalShouldSkipCandidateSelection;
    BOOL m_updatingPreferences;
    BOOL m_changingGeometryWithSameOrientation;
    BOOL m_suppressGeometryChangeNotifications;
    BOOL m_acceptingCandidate;
    BOOL m_didAutomaticallyInsertSpace;
    BOOL m_didSyncDocumentStateToInputDelegate;
    BOOL m_userChangedSelection;
    BOOL m_shouldChargeKeys;
    BOOL m_longPress;
    BOOL m_replacingWord;
    BOOL m_shiftNeedsUpdate;
    BOOL m_shiftPreventAutoshift;
    BOOL m_shiftHeldDownNeedsUpdated;
    BOOL m_delegateAdoptsTextInput;
    BOOL m_delegateAdoptsTextInputPrivate;
    BOOL m_delegateAdoptsKeyboardInput;
    BOOL m_delegateAdoptsWKInteraction;
    BOOL m_clientVariantSupportEnabled;
    BOOL m_clientVariantSupportEnabledEver;
    NSMutableArray* m_keyplaneNamesPreviousDelegate;
    NSMutableArray* m_keyplaneNamesCurrentDelegate;
    UITextInputArrowKeyHistory* m_arrowKeyHistory;
    BOOL m_preRotateShift;
    BOOL m_preRotateShiftLocked;
    BOOL m_showInputModeIndicator;
    BOOL m_suppressUpdateCandidateView;
    BOOL m_shouldUpdateCacheOnInputModesChange;
    BOOL m_shouldSetInputModeInNextRun;
    BOOL m_rivenCenterFilled;
    double m_splitProgress;
    BOOL m_needsCandidates;
    BOOL m_shouldSkipCandidateGeneration;
    BOOL m_updateLayoutOnShowKeyboard;
    BOOL m_receivedCandidatesInCurrentInputMode;
    int _currentAlertReason;
    BOOL m_scrolling;
    BOOL m_hasInputOnAcceptCandidate;
    BOOL m_maximizing;
    unsigned long long m_previousSpaceKeyBehavior;
    unsigned long long m_previousReturnKeyBehavior;
    BOOL m_usesCandidateSelection;
    BOOL m_UsedCandidateSelection;
    @? m_keyInputCompletionHandler;
    WebEvent* m_lastWebEvent;
    BOOL m_updatingLayout;
    BOOL m_showsCandidateBar;
    BOOL m_showsCandidateInline;
    BOOL committingCandidate;
    BOOL geometryIsChanging;
    BOOL m_softwareKeyboardShownByTouch;
    BOOL _handlingKeyCommandFromHardwareKeyboard;
    TIKeyboardTouchEvent* m_touchEventWaitingForKeyInputEvent;
    _UIActionWhenIdle* m_delayedCandidateRequest;
    _UIActionWhenIdle* m_deferredDidSetDelegateAction;
    UIPhysicalKeyboardEvent* m_hardwareRepeatEvent;
    UIKeyboardScheduledTask* m_hardwareRepeatTask;
    UIAlertView* keyboardAlertView;
    NSDictionary* _candidateRequestInfo;
    UIKeyboardScheduledTask* _autocorrectPromptTask;
}
 + (id) sharedInstance;
 + (id) keyboardScreen;
 + (BOOL) isSplit;
 + (void) applicationDidReceiveMemoryWarning:(id)a;
 + (void) applicationDidEnterBackground:(id)a;
 + (void) applicationWillSuspend:(id)a;
 + (id) activeInstance;
 + (void) releaseSharedInstance;
 + ({CGSize=dd}) sizeForInterfaceOrientation:(long long)a;
 + ({CGSize=dd}) defaultSizeForInterfaceOrientation:(long long)a;
 + ({CGSize=dd}) _defaultSizeForInterfaceOrientation:(long long)a;
 + (Class) layoutClassForInputMode:(id)akeyboardType:(long long)b;
 + (Class) layoutClassForCurrentInputMode;
 + ({CGSize=dd}) keyboardSizeForInterfaceOrientation:(long long)a;
 + (double) additionalInstanceHeightForInterfaceOrientation:(long long)a;
 + (double) additionalInstanceHeightLoadingForInterfaceOrientation:(long long)a;
 + (void) markPerformance:(id)a;
 + (double) splitProgress;
 + (void) markElapsed:(id)a;
 + (void) suppressSetPersistentOffset:(BOOL)a;
 + (BOOL) supportsSplit;
 + (double) persistentSplitProgress;
 + (void) refreshRivenStateWithTraits:(id)aisKeyboard:(BOOL)b;
 + (BOOL) rivenPreference;
 + ({CGPoint=dd}) normalizedPersistentOffset;
 + (id) keyboardWindow;
 + ({CGPoint=dd}) persistentOffset;
 + (double) additionalInstanceHeight;
 + (void) sendPerformanceNotification:(id)a;
 + (void) hardwareKeyboardAvailabilityChanged;
 + (id) normalizedInputModesFromPreference;
 + (double) additionalInstanceHeightLoading;
 + (BOOL) rivenInstalled;
 + (BOOL) rivenTranslationPreference;
 + (void) setPersistentSplitProgress:(double)a;
 + (void) setPersistentOffset:({CGPoint=dd})a;
 + (int) persistentDictationTargetZone;
 + (void) setPersistentDictationTargetZone:(int)a;
 + (void) setPersistentDictationWindowOffset:({CGPoint=dd})a;
 + ({CGPoint=dd}) persistentDictationWindowOffset;
 + (long long) interfaceOrientationForSize:({CGSize=dd})a;
 + (void) setParentTestForProfiling:(id)a;
 + (void) _clearHardwareKeyboardMinimizationPreference;
 + (void) applicationWillEnterForeground:(id)a;
 + (void) applicationWillResignActive:(id)a;

 - (int) changeCount;
 - (void) dealloc;
 - (void) setDelegate:(id)a ;
 - (void) setShift:(BOOL)a ;
 - (id) hitTest:({CGPoint=dd})a withEvent:(id)b ;
 - (BOOL) pointInside:({CGPoint=dd})a withEvent:(id)b ;
 - (BOOL) pointInside:({CGPoint=dd})a forEvent:(^{__GSEvent=})b ;
 - (void) cancelAllKeyEvents;
 - (void) ejectKeyDown;
 - (void) _physicalButtonsBegan:(id)a withEvent:(id)b ;
 - (void) _physicalButtonsEnded:(id)a withEvent:(id)b ;
 - (void) _physicalButtonsCancelled:(id)a withEvent:(id)b ;
 - (void) handleKeyEvent:(id)a ;
 - (void) _wheelChangedWithEvent:(id)a ;
 - (void) alertView:(id)a clickedButtonAtIndex:(long long)b ;
 - (void) _moveWithEvent:(id)a ;
 - (void) willMoveToWindow:(id)a ;
 - (void) didMoveToSuperview;
 - (void) candidateListAcceptCandidate:(id)a ;
 - (void) candidateListSelectionDidChange:(id)a ;
 - (void) showPreviousCandidate;
 - (void) showNextPage;
 - (void) jumpToCompositions;
 - (void) revealHiddenCandidates;
 - (id) selectionView;
 - (void) setSelectionWithPoint:({CGPoint=dd})a ;
 - (id) inputDelegate;
 - (void) textWillChange:(id)a ;
 - (void) textDidChange:(id)a ;
 - (void) deleteBackward;
 - (void) unmarkText;
 - (BOOL) hasMarkedText;
 - (void) remoteControlReceivedWithEvent:(id)a ;
 - (void) updateLayout;
 - (void) setCaretBlinks:(BOOL)a ;
 - (void) layoutHasChanged;
 - (void) setInitialDirection;
 - (void) textFrameChanged:(id)a ;
 - (id) changedDelegate;
 - (void) setChangedDelegate:(id)a ;
 - (void) textChanged:(id)a ;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) subtractKeyboardFrameFromRect:({CGRect={CGPoint=dd}{CGSize=dd}})a inView:(id)b ;
 - (int) _clipCornersOfView:(id)a ;
 - (BOOL) usesCandidateSelection;
 - (void) setUsesCandidateSelection:(BOOL)a ;
 - (void) logHandwritingData;
 - (id) candidateList;
 - (id) _layout;
 - (BOOL) supportsNumberKeySelection;
 - (BOOL) centerFilled;
 - (void) releaseInputManager;
 - (void) clearDelegate;
 - (void) clearAnimations;
 - (void) clearTimers;
 - (void) clearLayouts;
 - (void) acceptAutocorrection;
 - (void) clearTransientState;
 - (void) _updateSoundPreheatingForWindow:(id)a ;
 - (BOOL) showsCandidateBar;
 - (BOOL) shouldShowCandidateBar;
 - (BOOL) hardwareKeyboardIsSeen;
 - (void) takeTextInputTraitsFromDelegate;
 - (BOOL) shiftLockPreference;
 - (BOOL) doubleSpacePeriodPreference;
 - (id) inputModePreference;
 - (id) UILanguagePreference;
 - (void) refreshRivenPreferences;
 - (void) setInSplitKeyboardMode:(BOOL)a ;
 - (void) setInputModeFromPreferences;
 - (void) installRecorder;
 - (void) delayedInit;
 - (void) applicationSuspendedEventsOnly:(id)a ;
 - (void) applicationResumedEventsOnly:(id)a ;
 - (void) keyboardDidHide:(id)a ;
 - (void) selectionScrolling:(id)a ;
 - (BOOL) performanceLoggingPreference;
 - (void) setRecorder:(id)a ;
 - (void) removeAutocorrectPromptAndCandidateList;
 - (void) setInputMode:(id)a ;
 - (BOOL) shouldSwitchFromInputManagerMode:(id)a toInputMode:(id)b ;
 - (void) updateInputManagerMode;
 - (BOOL) candidateSelectionPredictionForTraits;
 - (id) autocorrectionController;
 - (void) clearInput;
 - (id) keyboardAlertView;
 - (void) setKeyboardAlertView:(id)a ;
 - (void) clearChangeTimeAndCount;
 - (void) updateCandidateDisplay;
 - (BOOL) autocorrectionPreferenceForTraits;
 - (void) setAutocorrectSpellingEnabled:(BOOL)a ;
 - (BOOL) autocapitalizationPreference;
 - (void) updateInputManagerAutocapitalizationType;
 - (void) recomputeActiveInputModesWithExtensions:(BOOL)a ;
 - (void) syncInputManagerToKeyboardState;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) frameForKeylayoutName:(id)a ;
 - ({CGSize=dd}) dragGestureSize;
 - (void) setSplitProgress:(double)a ;
 - (void) setRivenSplitLock:(BOOL)a ;
 - (BOOL) autocorrectionPreference;
 - (BOOL) keyboardIsKeyPad;
 - (BOOL) isMinimized;
 - (BOOL) predictionForTraits;
 - (BOOL) checkSpellingPreference;
 - (BOOL) automaticMinimizationEnabled;
 - (void) setInputMode:(id)a userInitiated:(BOOL)b ;
 - (id) taskQueue;
 - (void) setInputMode:(id)a userInitiated:(BOOL)b updateIndicator:(BOOL)c executionContext:(id)d ;
 - (void) setKeyboardInputMode:(id)a userInitiated:(BOOL)b updateIndicator:(BOOL)c executionContext:(id)d ;
 - (void) cleanUpBeforeInputModeSwitch;
 - (void) setInputManagerFromCurrentInputMode;
 - (void) reinitializeAfterInputModeSwitch:(BOOL)a ;
 - (void) finishSetKeyboardInputMode:(id)a didChangeDirection:(BOOL)b ;
 - (void) textChanged:(id)a executionContext:(id)b ;
 - (void) syncInputManagerToKeyboardStateWithExecutionContext:(id)a ;
 - (void) callLayoutUpdateLocalizedKeys;
 - (void) updateInputModeIndicatorOnSingleKeyOnly:(BOOL)a ;
 - (void) finishSetExtensionInputMode:(id)a didChangeDirection:(BOOL)b ;
 - (void) finishSetInputMode:(id)a didChangeDirection:(BOOL)b ;
 - (void) updateTextCandidateView;
 - (void) generateCandidates;
 - (void) setKeyboardInputMode:(id)a userInitiated:(BOOL)b ;
 - (void) clearLanguageIndicator;
 - (void) fadeAnimationDidStop:(id)a finished:(id)b ;
 - (void) updateInputModeIndicatorOnSingleKeyOnly:(BOOL)a preserveIfPossible:(BOOL)b ;
 - (void) showInformationalAlertIfNeededForReason:(int)a ;
 - (void) finishSetInputModeToNextInPreferredListWithExecutionContext:(id)a ;
 - (void) updateInputModeLastChosenPreference;
 - (void) showInternationalKeyInfoAlertIfNeeded;
 - (BOOL) showInputModeIndicator;
 - (void) setOrientation;
 - (void) prepareForGeometryChange;
 - (void) setShiftLocked:(BOOL)a ;
 - (void) updateStylingTraitsIfNeeded;
 - (void) geometryChangeDone:(BOOL)a ;
 - (id) privateInputDelegate;
 - (BOOL) shouldForceASCIICapable;
 - (void) setDelegate:(id)a force:(BOOL)b ;
 - (void) updateReturnKey;
 - (id) recorder;
 - (void) stopKeyboardRecording;
 - (void) setCaretVisible:(BOOL)a ;
 - (void) didHandleWebKeyEvent;
 - (id) asynchronousInputDelegate;
 - (void) storeDelegateConformance;
 - (void) stopAutoDelete;
 - (void) clearShiftState;
 - (void) callChanged;
 - (BOOL) delegateIsSMSTextView;
 - (void) setArrowKeyHistory:(id)a ;
 - (void) setReturnKeyEnabled:(BOOL)a ;
 - (id) desirableInputModesWithExtensions:(BOOL)a ;
 - (void) updateShiftState;
 - (void) callLayoutUpdateAllLocalizedKeys;
 - (void) startKeyboardRecording;
 - (id) deferredDidSetDelegateAction;
 - (void) didSetDelegate;
 - (void) setDeferredDidSetDelegateAction:(id)a ;
 - (void) updateForChangedSelection;
 - (void) updateForChangedSelectionWithExecutionContext:(id)a ;
 - (void) releaseInputManagerIfInactive;
 - (BOOL) checkSpellingPreferenceForTraits;
 - (BOOL) isAutoFillMode;
 - (void) clearSelection;
 - (void) selectionWillChange:(id)a ;
 - (void) finishTextChanged;
 - (void) updateReturnKey:(BOOL)a ;
 - (void) updateNoContentViews;
 - (void) setChanged;
 - (void) setShiftOffIfNeeded;
 - (void) selectionDidChange:(id)a ;
 - (BOOL) callShouldReplaceExtendedRange:(long long)a withText:(id)b includeMarkedText:(BOOL)c ;
 - (BOOL) callShouldInsertText:(id)a ;
 - (BOOL) _shouldRequestInputManagerSyncForKeyboardOutputCallbacks:(id)a ;
 - (void) collapseSelectionAndAdjustByOffset:(long long)a ;
 - (void) _updateInputViewControllerOutput:(id)a forKeyboardOutput:(id)b ;
 - (void) performKeyboardOutput:(id)a ;
 - (void) _performInputViewControllerOutput:(id)a ;
 - (void) _handleWebKeyEvent:(id)a withInputString:(id)b executionContext:(id)c ;
 - (void) _processInputViewControllerKeyboardOutput:(id)a executionContext:(id)b ;
 - (void) _completePerformInputViewControllerOutput:(id)a executionContext:(id)b ;
 - (id) delegateAsResponder;
 - (void) setInputModeToNextInPreferredListWithExecutionContext:(id)a ;
 - (void) dismissKeyboard;
 - (void) _requestInputManagerSync;
 - (id) legacyInputDelegate;
 - (id) inputManagerState;
 - (BOOL) usesAutoDeleteWord;
 - (void) syncDocumentStateToInputDelegate;
 - (void) updateAutocorrectPrompt:(id)a ;
 - (void) updateObserverState;
 - (id) arrowKeyHistory;
 - (void) setHandlingKeyCommandFromHardwareKeyboard:(BOOL)a ;
 - (void) movePhraseBoundaryToDirection:(long long)a ;
 - (BOOL) canHandleEvent:(id)a ;
 - (void) deleteForwardAndNotify:(BOOL)a ;
 - (void) fadeAutocorrectPrompt;
 - (id) inputModeLastUsedForLanguage:(id)a ;
 - (void) performKeyBehaviorConfirm;
 - (void) performKeyBehaviorConfirmFirstCandidate;
 - (id) _keyboardBehaviorState;
 - (void) setGeometryIsChanging:(BOOL)a ;
 - (void) updateLayoutIfNeeded;
 - (void) removeAutocorrectPrompt;
 - (void) releaseSuppressUpdateCandidateView;
 - (void) clearLongPressTimer;
 - (BOOL) isUsingDictationLayout;
 - (id) dynamicCaretList;
 - (BOOL) showsCandidateInline;
 - (BOOL) currentKeyboardTraitsAllowCandidateBar;
 - (void) setShouldSkipCandidateSelection:(BOOL)a ;
 - (void) setShowsCandidateBar:(BOOL)a ;
 - (void) callLayoutUpdateReturnKey;
 - (void) finishLayoutChangeWithArguments:(id)a ;
 - (void) _resizeForKeyplaneSize:({CGSize=dd})a splitWidthsChanged:(BOOL)b ;
 - (BOOL) splitTransitionInProgress;
 - (id) inputStringFromPhraseBoundary;
 - (void) clearInputForMarkedText;
 - (void) syncDocumentStateToInputDelegateWithExecutionContext:(id)a ;
 - (BOOL) hasEditableMarkedText;
 - (id) inputManager;
 - (void) prepareForSelectionChange;
 - (void) setPreviousInputString:(id)a ;
 - (BOOL) shouldGenerateCandidatesAfterSelectionChange;
 - (void) completeUpdateForChangedSelection:(BOOL)a ;
 - (BOOL) usesAutocorrectionLists;
 - (void) callChangedSelection;
 - (void) deleteHandwritingStrokesAtIndexes:(id)a ;
 - (void) flushTouchEventWaitingForKeyInputEventIfNecessary;
 - (void) refreshKeyboardState;
 - (void) syncKeyboardToConfiguration:(id)a ;
 - (void) setMarkedText:(id)a selectedRange:({_NSRange=QQ})b inputString:(id)c searchString:(id)d ;
 - (BOOL) isShifted;
 - (BOOL) isShiftLocked;
 - (void) setLabel:(id)a forKey:(id)b ;
 - (void) cancelCandidateRequests;
 - (id) touchEventWaitingForKeyInputEvent;
 - (void) setTouchEventWaitingForKeyInputEvent:(id)a ;
 - (void) acceptCandidate:(id)a ;
 - (void) unmarkText:(id)a ;
 - (void) insertTextAfterSelection:(id)a ;
 - (void) deleteBackwardAndNotify:(BOOL)a ;
 - (void) setAutocorrection:(id)a ;
 - (id) autocorrectPrompt;
 - (void) touchAutocorrectPromptTimer;
 - (void) generateCandidatesAsynchronouslyWithRange:({_NSRange=QQ})a selectedCandidate:(id)b ;
 - (void) setCandidateRequestInfo:(id)a ;
 - (id) candidateRequestInfo;
 - (void) inputManagerDidGenerateCandidatesForRequest:(id)a resultSet:(id)b ;
 - (id) delayedCandidateRequest;
 - (void) setDelayedCandidateRequest:(id)a ;
 - (void) updateCandidateDisplayAsyncWithCandidateSet:(id)a ;
 - (void) inputManagerDidGenerateAutocorrections:(id)a executionContext:(id)b ;
 - (void) generateAutocorrectionsWithCompletionHandler:(@?)a ;
 - (void) setAutocorrectionList:(id)a ;
 - (void) updateAutocorrectPrompt:(id)a executionContext:(id)b ;
 - (void) skipHitTestForTouchEvent:(id)a ;
 - (void) didChangePhraseBoundary;
 - (BOOL) shouldSwitchInputMode:(id)a ;
 - (void) callLayoutSetShift:(BOOL)a ;
 - (void) callLayoutSetAutoshift:(BOOL)a ;
 - (BOOL) callLayoutIsShiftKeyPlaneChooser;
 - (void) notifyShiftState;
 - (BOOL) callLayoutIsShiftKeyBeingHeld;
 - (BOOL) callLayoutUsesAutoShift;
 - (BOOL) isSelectionAtSentenceAutoshiftBoundary;
 - (void) setShiftPreventAutoshift:(BOOL)a ;
 - (void) setShift:(BOOL)a autoshift:(BOOL)b ;
 - (void) setShiftNeedsUpdate;
 - (BOOL) suppliesCompletions;
 - (void) deleteFromInputWithFlags:(unsigned long long)a executionContext:(id)b ;
 - (void) _handleKeyEvent:(id)a executionContext:(id)b ;
 - (void) handleDeleteAsRepeat:(BOOL)a executionContext:(id)b ;
 - (void) handleDeleteWithExecutionContext:(id)a ;
 - (void) handleClearWithExecutionContext:(id)a ;
 - (void) addInputString:(id)a withFlags:(unsigned long long)b executionContext:(id)c ;
 - (BOOL) acceptInputString:(id)a ;
 - (void) updateKeyboardStateForInsertion:(id)a ;
 - (void) updateKeyboardStateForDeletion;
 - (BOOL) isInHardwareKeyboardMode;
 - (BOOL) callLayoutIgnoresShiftState;
 - (void) updateDoubleSpacePeriodStateForCharacter:(unsigned int)a ;
 - (BOOL) shouldDeleteAutospaceBeforeTerminator:(id)a ;
 - (BOOL) applyAutocorrection:(id)a ;
 - (void) setExternalTask:(@?)a ;
 - (id) inputEventForInputString:(id)a ;
 - (void) addInputEvent:(id)a executionContext:(id)b ;
 - (void) acceptCurrentCandidateIfSelectedWithExecutionContext:(id)a ;
 - (void) updateChangeTimeAndIncrementCount;
 - (void) collapseSelection;
 - (void) acceptCurrentCandidateForInput:(id)a ;
 - (void) addWordTerminator:(id)a afterSpace:(BOOL)b elapsedTime:(double)c executionContext:(id)d ;
 - (void) completeAddInputString:(id)a ;
 - (void) acceptAutocorrectionForWordTerminator:(id)a executionContextPassingTIKeyboardCandidate:(id)b ;
 - (void) willReplaceTextInRangedSelectionWithKeyboardInput;
 - (void) completeAddInputString:(id)a generateCandidates:(BOOL)b ;
 - (void) handleKeyboardInput:(id)a executionContext:(id)b ;
 - (BOOL) shouldAcceptCandidate:(id)a beforeInputString:(id)b ;
 - (void) didAcceptAutocorrection:(id)a wordTerminator:(id)b ;
 - (void) acceptAutocorrection:(id)a executionContextPassingTIKeyboardCandidate:(id)b ;
 - (id) inputWordForTerminatorAtSelection;
 - (BOOL) nextCharacterIsWordCharacter;
 - (void) syncInputManagerToAcceptedAutocorrection:(id)a forInput:(id)b ;
 - (void) moveSelectionToEndOfWord;
 - (BOOL) shouldApplyAcceptedAutocorrection:(id)a ;
 - (void) setDocumentStateForAutocorrection:(id)a ;
 - (void) animateAutocorrectionToRect:({CGRect={CGPoint=dd}{CGSize=dd}})a fromRect:({CGRect={CGPoint=dd}{CGSize=dd}})b ;
 - (void) didApplyAutocorrection:(id)a autocorrectPromptFrame:({CGRect={CGPoint=dd}{CGSize=dd}})b ;
 - (void) animateAutocorrectionToText:(id)a fromRect:({CGRect={CGPoint=dd}{CGSize=dd}})b ;
 - (void) trackUsageForAcceptedAutocorrection:(id)a promptWasShowing:(BOOL)b ;
 - (id) handleDeleteAutospaceForInputString:(id)a afterSpace:(BOOL)b ;
 - (id) handleDoubleSpacePeriodForInputString:(id)a afterSpace:(BOOL)b elapsedTime:(double)c ;
 - (id) handleReplacement:(id)a forSpaceAndInput:(id)b ;
 - (void) updateDoubleSpacePeriodStateForString:(id)a ;
 - (void) setUserSelectedCurrentCandidate:(BOOL)a ;
 - (unsigned long long) phraseBoundary;
 - (void) adjustPhraseBoundaryInForwardDirection:(BOOL)a executionContext:(id)b ;
 - (void) completeDeleteOnceFromInputWithCharacterBefore:(unsigned int)a ;
 - (void) scheduleReplacementsWithOptions:(unsigned long long)a ;
 - (BOOL) selectionIsEndOfWord;
 - (void) scheduleReplacementsAfterDeletionToEndOfWord;
 - (BOOL) shouldEnableShiftForDeletedCharacter:(unsigned int)a ;
 - (void) didHandleWebKeyEvent:(id)a ;
 - (BOOL) callShouldDeleteWithWordCountForRapidDelete:(int)a characterCountForRapidDelete:(int)b ;
 - (void) deleteOnceFromInputWithExecutionContext:(id)a ;
 - (void) completeDeleteFromInput;
 - (id) acceptAutocorrectionForWordTerminator:(id)a ;
 - (void) acceptCurrentCandidate;
 - (void) acceptCandidate:(id)a atIndex:(unsigned long long)b executionContext:(id)c ;
 - (void) acceptPredictiveInput:(id)a executionContext:(id)b ;
 - (void) completeAcceptCandidate:(id)a ;
 - (void) handleAcceptedCandidate:(id)a executionContext:(id)b ;
 - (void) acceptCandidate:(id)a forInput:(id)b ;
 - (BOOL) committingCandidate;
 - (void) setCommittingCandidate:(BOOL)a ;
 - (BOOL) acceptWord:(id)a firstDelete:(unsigned long long)b forInput:(id)c ;
 - (void) acceptCurrentCandidateForInput:(id)a executionContext:(id)b ;
 - (void) acceptCandidate:(id)a atIndex:(unsigned long long)b ;
 - (BOOL) geometryIsChanging;
 - (void) generateCandidatesWithOptions:(int)a ;
 - (void) trackUsageForCandidateAcceptedAction:(id)a ;
 - (void) updateKeyboardConfigurations;
 - (void) addInputObject:(id)a executionContext:(id)b ;
 - (void) setInHardwareKeyboardMode:(BOOL)a ;
 - (void) completeAcceptCandidateBeforeAddingInputObject:(id)a executionContext:(id)b ;
 - (BOOL) acceptWord:(id)a firstDelete:(unsigned long long)b ;
 - (void) generateCandidatesAsynchronously;
 - (void) _setNeedsCandidates:(BOOL)a ;
 - (BOOL) needsToDeferUpdateTextCandidateView;
 - (id) autocorrectPromptTask;
 - (void) setAutocorrectPromptTask:(id)a ;
 - (void) resizeCandidateBarWithDelta:(double)a ;
 - (void) clearAutocorrectPromptTimer;
 - (void) sendCallbacksForPostCorrectionsRemoval;
 - (void) removeCandidateList;
 - (BOOL) noContent;
 - (void) _nop;
 - (void) showNextCandidates;
 - (id) returnKeyDisplayName;
 - (BOOL) handlingKeyCommandFromHardwareKeyboard;
 - (void) acceptFirstCandidate;
 - (void) _handleKeyBehavior:(unsigned long long)a forKeyType:(id)b ;
 - (id) updateKeyBehaviors:(id)a withBehaviors:(id)b forState:(id)c ;
 - (id) inputOverlayContainer;
 - (BOOL) delegateSupportsCorrectionUI;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) convertRectToAutocorrectRect:({CGRect={CGPoint=dd}{CGSize=dd}})a delegateView:(id)b container:(id)c ;
 - (id) autocorrectPromptRectsFromFirstDelegateRect:({CGRect={CGPoint=dd}{CGSize=dd}})a lastDelegateRect:({CGRect={CGPoint=dd}{CGSize=dd}})b ;
 - (void) updateAutocorrectPrompt:(id)a correctionRects:(id)b ;
 - (id) autocorrectPromptRectsForInput:(id)a ;
 - (id) _rangeForAutocorrectionText:(id)a ;
 - (void) trackUsageForPromptedCorrection:(id)a inputString:(id)b previousPrompt:(id)c ;
 - (void) sendCallbacksForPreCorrectionsDisplay;
 - (void) autocorrectionAnimationDidStop:(id)a finished:(id)b context:(id)c ;
 - (BOOL) delegateSuggestionsForCurrentInput;
 - (id) autocorrectionRecordForWord:(id)a ;
 - (id) replacementsFromSelectedText;
 - (void) generateReplacementsForString:(id)a candidatesHandler:(@?)b executionContext:(id)c ;
 - (void) clearAutoDeleteTimer;
 - (void) handleAutoDeleteWithExecutionContext:(id)a ;
 - (void) completeHandleAutoDelete;
 - (void) touchAutoDeleteTimerWithThreshold:(double)a ;
 - (void) handleDelayedActionLongPress;
 - (void) touchLongPressTimerWithDelay:(double)a ;
 - (void) longPressAction;
 - (void) callLayoutLongPressAction;
 - (void) hardwareKeyboardAvailabilityChanged;
 - (void) setAutomaticMinimizationEnabled:(BOOL)a ;
 - (void) updateHardwareKeyboardLayout;
 - (id) hardwareRepeatTask;
 - (id) hardwareRepeatEvent;
 - (void) handleKeyEvent:(id)a executionContext:(id)b ;
 - (void) setHardwareRepeatTask:(id)a ;
 - (void) showKeyboard;
 - (void) hideKeyboard;
 - (void) setHardwareRepeatEvent:(id)a ;
 - (void) _handleWebKeyEvent:(id)a withEventType:(int)b withInputString:(id)c withInputStringIgnoringModifiers:(id)d ;
 - (void) _handleWebKeyEvent:(id)a withIndex:(unsigned long long)b inInputString:(id)c executionContext:(id)d ;
 - (void) _continueHandleWebKeyEventWithTask:(@?)a executionContext:(id)b ;
 - (@?) externalTask;
 - (void) updateKeyboardEventsLagging:(id)a ;
 - (void) setHardwareKeyboardIsSeen:(BOOL)a ;
 - (BOOL) softwareKeyboardShownByTouch;
 - (void) toggleSoftwareKeyboard;
 - (void) setSoftwareKeyboardShownByTouch:(BOOL)a ;
 - (void) _remapKeyEvent:(id)a withKeyEventMap:(id)b ;
 - (void) firstHardwareAutoRepeatWithExecutionContext:(id)a ;
 - (BOOL) handleKeyCommand:(id)a repeatOkay:(^B)b ;
 - (BOOL) isValidKeyInput:(id)a ;
 - (void) completeHandleKeyEvent:(id)a ;
 - (void) handleKeyWithString:(id)a forKeyEvent:(id)b executionContext:(id)c ;
 - (void) handleStringInput:(id)a withFlags:(unsigned long long)b executionContext:(id)c ;
 - (BOOL) caretBlinks;
 - (BOOL) canHandleKeyHitTest;
 - (BOOL) needsKeyHitTestResults;
 - (void) setCandidateList:(id)a updateCandidateView:(BOOL)b ;
 - (id) layoutForKeyHitTest;
 - (void) setLayoutForKeyHitTest:(id)a ;
 - (void) defaultsDidChange;
 - (BOOL) rivenSplitLock;
 - (unsigned long long) minimumTouchesForTranslation;
 - (BOOL) hideAccessoryViewsDuringSplit;
 - (void) cancelSplitTransition;
 - (BOOL) predictionPreferenceForTraits;
 - (BOOL) swipeToTabPreference;
 - (BOOL) keyboardsExpandedPreference;
 - (void) saveInputModesPreference:(id)a ;
 - (id) inputModeLastUsedPreference;
 - (void) setShouldUpdateCacheOnInputModesChange:(BOOL)a ;
 - (id) hardwareKeyboardsSeenPreference;
 - (void) setHardwareKeyboardsSeenPreference:(id)a ;
 - (void) setInputModeToNextASCIICapableInPreferredList;
 - (void) prepareLayoutForInterfaceOrientation:(long long)a ;
 - (void) updateLayoutToCurrentInterfaceOrientation;
 - (void) finishLayoutToCurrentInterfaceOrientation;
 - (void) setCorrectionLearningAllowed:(BOOL)a ;
 - (BOOL) autocorrectSpellingEnabled;
 - (void) setDefaultTextInputTraits:(id)a ;
 - (void) enable;
 - (BOOL) changeNotificationDisabled;
 - (void) setChangeNotificationDisabled:(BOOL)a ;
 - (void) handleObserverCallback;
 - (id) markedTextOverlay;
 - (void) generateAutocorrectionWithExecutionContext:(id)a ;
 - (void) skipHitTestForTouchEvent:(id)a delayed:(BOOL)b ;
 - (void) performHitTestForTouchEvent:(id)a executionContextPassingNSNumber:(id)b ;
 - (void) removeAllDynamicDictionaries;
 - (void) toggleShift;
 - (void) setShiftLockedForced:(BOOL)a ;
 - (BOOL) isAutoShifted;
 - (BOOL) shiftLockedEnabled;
 - (void) forceShiftUpdate;
 - (void) forceShiftUpdateIfKeyboardStateChanged;
 - (void) keyActivated;
 - (void) keyDeactivated;
 - (void) handleDelete;
 - (void) handleClear;
 - (void) addInputString:(id)a ;
 - (void) addInputString:(id)a fromVariantKey:(BOOL)b ;
 - (void) updateLayoutAndSetShift;
 - (void) removeAutocorrection;
 - (void) acceptPredictiveInput:(id)a ;
 - (void) acceptCurrentCandidateWithExecutionContext:(id)a ;
 - (void) acceptCurrentCandidateIfSelected;
 - (void) addInputObject:(id)a ;
 - (void) replaceText:(id)a ;
 - (BOOL) displaysCandidates;
 - (void) setShowsCandidateInline:(BOOL)a ;
 - (void) responseContextDidChange;
 - (BOOL) returnKeyEnabled;
 - (void) generateCandidatesFromReplacements;
 - (id) generateAutocorrectionReplacements:(id)a ;
 - (void) startAutoDeleteTimer;
 - (void) touchLongPressTimer;
 - (BOOL) isLongPress;
 - (void) showKeyboardIfNeeded;
 - (void) startCaretBlinkIfNeeded;
 - (BOOL) caretVisible;
 - (id) geometryDelegate;
 - (void) setGeometryDelegate:(id)a ;
 - (void) setShowInputModeIndicator:(BOOL)a ;
 - (BOOL) shouldSetInputModeInNextRun;
 - (void) setShouldSetInputModeInNextRun:(BOOL)a ;
 - (BOOL) receivedCandidatesInCurrentInputMode;
 - (void) setReceivedCandidatesInCurrentInputMode:(BOOL)a ;
 - (void) timeMark:(unsigned int)a message:(id)b ;
 - (void) timeMark:(unsigned int)a ;
 - (void) timeElapsed:(unsigned int)a message:(id)b ;
 - (void) _setInputManager:(id)a ;
 - (void) _setShiftLockedEnabled:(BOOL)a ;
 - (BOOL) hasAutoRepeat;
 - (void) updateFromTextInputTraits;
 - (BOOL) _isShowingCandidateUIWithAvailableCandidates;
 - (int) textInputChangingCount;
 - (void) testAutocorrectionPromptWithCorrection:(id)a ;
 - (BOOL) isAutoDeleteActive;
 - (void) composeTypologyRadar;
 - (void) setSplit:(BOOL)a animated:(BOOL)b ;
 - (void) finishSplitTransitionWithProgress:(double)a ;
 - (void) clearExcessKeyboardMemory;
 - (BOOL) keyboardDrawsOpaque;
 - (BOOL) _shouldMinimizeForHardwareKeyboard;
 - (void) setTextInputChangesIgnored:(BOOL)a ;
 - (void) acceptAutocorrectionAndEndComposition;
 - (void) moveCursorLeftShifted:(BOOL)a ;
 - (void) moveCursorRightShifted:(BOOL)a ;
 - (id) _getCurrentKeyplaneName;
 - (id) _getCurrentKeyboardName;
 - (id) _getLocalizedInputMode;
 - (void) _setAutocorrects:(BOOL)a ;
 - (id) _getAutocorrection;
 - (BOOL) _hasCandidates;
 - (long long) _positionInCandidateList:(id)a ;
 - (BOOL) _needsCandidates;
 - (BOOL) keyboardRecordingEnabled;
 - (id) delegate;
 - (void) removeFromSuperview;
 - (id) initWithFrame:({CGRect={CGPoint=dd}{CGSize=dd}})a ;
 - (long long) interfaceOrientation;
 - (void) setFrame:({CGRect={CGPoint=dd}{CGSize=dd}})a ;
 - (void) setInputPoint:({CGPoint=dd})a ;
 - (id) markedText;
 - (void) setCandidates:(id)a ;
 - (void) setInputManagerState:(id)a ;
 - (id) searchStringForMarkedText;
 - (id) textInputTraits;
 - (id) layoutState;
 - (BOOL) userSelectedCurrentCandidate;
 - (BOOL) shouldSkipCandidateSelection;
 - (int) returnKeyType;
 - (void) insertText:(id)a ;
 - (void) deleteFromInputWithFlags:(unsigned long long)a ;
 - (void) deleteFromInput;
 - (void) addInputString:(id)a withFlags:(unsigned long long)b ;
 - (void) detach;


@end
