
@protocol UIKeyboardCandidateList, UIKeyboardCandidateListDelegate, UIKeyboardCandidateBarLayoutDelegate, UICollectionViewDataSource;
@interface UIKeyboardCandidateBar : UIView <UIKeyboardCandidateList, UIKeyboardCandidateListDelegate, UIKeyboardCandidateBarLayoutDelegate, UICollectionViewDataSource> {

    BOOL _canExtend;
    BOOL _forceReloadInitiallyHiddenCandidates;
    BOOL _shouldSkipLayoutUntilScrollViewAnimationEnds;
    BOOL _didSkipLayout;
    @"NSString" _inlineText;
    @"UIImageView" _candidateMaskView;
    @"<UIKeyboardCandidateBarDelegate>" _delegate;
    d _upArrowWidth;
    @"<UIKeyboardCandidateListDelegate>" _candidateListDelegate;
    @"NSArray" _candidateViews;
    Q _currentCandidateViewIndex;
    @"UIKBThemedView" _secondaryCandidatesViewEdgeGradient;
    @"TIKeyboardCandidateResultSet" _candidateResultSet;
    @"NSArray" _filteredCandidates;
    @"NSIndexPath" _dragStartNextPageIndexPath;
    @"NSIndexPath" _dragStartPreviousPageIndexPath;
    @? _skippedSetCandidatesBlock;
    {CGPoint="x"d"y"d} _dragStartOffset;
}
 + (Q) numberOfRows;
 + (d) heightForInterfaceOrientation:(q)a;
 + (void) setScreenTraits:(id)a;
 + (Q) numberOfRowsForInterfaceOrientation:(q)a;
 + (d) heightForRowAtIndex:(Q)ainterfaceOrientation:(q)b;
 + (d) interRowOverlap;
 + (d) defaultPagingVelocityThreshold;
 + (d) defaultPagingDistanceThreshold;
 + (d) heightForRowAtIndex:(Q)a;
 + (d) heightForLastRow;
 + (d) defaultCandidateWidth;
 + (d) height;

 - (void) dealloc;
 - (Q) count;
 - (void) setDelegate:(id)a;
 - (void) scrollViewDidScroll:(id)a;
 - (void) scrollViewWillBeginDragging:(id)a;
 - (void) scrollViewWillEndDragging:(id)awithVelocity:({CGPoint=dd})btargetContentOffset:(N^{CGPoint=dd})c;
 - (void) scrollViewDidEndDragging:(id)awillDecelerate:(BOOL)b;
 - (void) scrollViewDidEndDecelerating:(id)a;
 - (void) scrollViewDidEndScrollingAnimation:(id)a;
 - (q) collectionView:(id)anumberOfItemsInSection:(q)b;
 - (id) collectionView:(id)acellForItemAtIndexPath:(id)b;
 - (q) numberOfSectionsInCollectionView:(id)a;
 - (id) collectionView:(id)aviewForSupplementaryElementOfKind:(id)batIndexPath:(id)c;
 - (void) collectionView:(id)adidSelectItemAtIndexPath:(id)b;
 - (void) showCandidateAtIndex:(Q)a;
 - (void) _stepSelectedCandidateInDirection:(BOOL)a;
 - (void) showNextCandidate;
 - (id) candidateListDelegate;
 - (void) candidateListAcceptCandidate:(id)a;
 - (void) setCandidates:(id)ainlineText:(id)binlineRect:({CGRect={CGPoint=dd}{CGSize=dd}})cmaxX:(d)dlayout:(BOOL)e;
 - (void) setCandidateListDelegate:(id)a;
 - (id) statisticsIdentifier;
 - (void) candidateListSelectionDidChange:(id)a;
 - (BOOL) isExtendedList;
 - (BOOL) isHiddenCandidatesList;
 - (void) setUIKeyboardCandidateListDelegate:(id)a;
 - (BOOL) showCandidate:(id)a;
 - (void) showPreviousCandidate;
 - (void) showNextPage;
 - (void) showPreviousPage;
 - (void) showNextRow;
 - (void) showPreviousRow;
 - (Q) currentIndex;
 - (void) candidateAcceptedAtIndex:(Q)a;
 - (id) keyboardBehaviors;
 - (Q) selectedSortIndex;
 - (void) setInlineText:(id)a;
 - (BOOL) hasNextPage;
 - (BOOL) hasPreviousPage;
 - (void) candidatesDidChange;
 - (void) revealHiddenCandidates;
 - (id) inlineText;
 - (Q) viewOffsetForCandidateAtIndex:(Q)a;
 - ({CGSize=dd}) collectionView:(id)alayout:(id)bsizeForItemAtIndexPath:(id)c;
 - ({CGSize=dd}) sizeOfDummyItemForCollectionView:(id)alayout:(id)b;
 - (void) setCandidateResultSet:(id)a;
 - (void) candidateListShouldBeDismissed:(id)a;
 - (void) _clearData;
 - (id) candidateViews;
 - (q) _sectionForSectionIndex:(Q)acandidateView:(id)b;
 - (Q) _countOfItemsInSection:(q)a;
 - (id) _itemAtIndex:(Q)ainSection:(q)b;
 - (Class) _barCellClassForSection:(q)a;
 - (d) _widthOfItemAtIndex:(Q)ainSection:(q)b;
 - (void) _updateCanExtendState;
 - (void) setCurrentCandidateViewIndex:(Q)a;
 - (BOOL) _showingInitiallyHiddenCandidates;
 - (void) setShouldSkipLayoutUntilScrollViewAnimationEnds:(BOOL)a;
 - (BOOL) shouldSkipLayoutUntilScrollViewAnimationEnds;
 - (void) _scrollToFirstCandidateInSection:(q)awithAnimation:(BOOL)b;
 - (id) currentCandidateView;
 - (BOOL) didSkipLayout;
 - (void) _performSkippedLayoutIfNeeded;
 - (void) setDragStartOffset:({CGPoint=dd})a;
 - (id) _nextPageIndexPath;
 - (void) setDragStartNextPageIndexPath:(id)a;
 - (id) _previousPageIndexPath;
 - (void) setDragStartPreviousPageIndexPath:(id)a;
 - ({CGPoint=dd}) dragStartOffset;
 - (id) _indexPathForFirstVisibleItem;
 - (id) dragStartNextPageIndexPath;
 - (BOOL) canExtend;
 - (id) _candidateViewForSection:(q)a;
 - (id) dragStartPreviousPageIndexPath;
 - (id) _indexPathForLastVisibleItem;
 - (id) _indexPathForCandidateFromIndexPath:(id)ainCandidateView:(id)b;
 - (void) adjustSelectionToNearestVisibleCandidate;
 - (void) setSkippedSetCandidatesBlock:(@?)a;
 - (void) setDidSkipLayout:(BOOL)a;
 - (BOOL) forceReloadInitiallyHiddenCandidates;
 - (void) setForceReloadInitiallyHiddenCandidates:(BOOL)a;
 - (void) setFilteredCandidates:(id)a;
 - (void) _reloadDataByAppendingAtEnd:(BOOL)ainitiallyHiddenCandidatesChanged:(BOOL)b;
 - (void) _reloadData;
 - (id) filteredCandidates;
 - (void) _showCandidateAtIndex:(Q)ainSection:(q)bscrollCellToVisible:(BOOL)canimated:(BOOL)d;
 - (void) _showPageAtIndexPath:(id)a;
 - (Q) currentCandidateViewIndex;
 - (void) _stepSelectedCandidateInDirection:(BOOL)acandidateView:(id)bsection:(q)c;
 - (id) _indexPathForCurrentCandidateViewFromIndexPath:(id)a;
 - (void) setCandidateViews:(id)a;
 - (d) upArrowWidth;
 - (id) secondaryCandidatesViewEdgeGradient;
 - (void) setSecondaryCandidatesViewEdgeGradient:(id)a;
 - (void) _updateCandidateViews;
 - (@?) skippedSetCandidatesBlock;
 - (Q) _sectionIndexForSection:(q)a;
 - (void) setCanExtend:(BOOL)a;
 - (void) candidateBarLayoutDidFinishPreparingLayout;
 - (d) _emptySpaceForItemsToIndex:(Q)ainSection:(q)b;
 - (id) visibleCandidates;
 - (void) setUpArrowWidth:(d)a;
 - (id) candidateMaskView;
 - (void) setCandidateMaskView:(id)a;
 - (id) delegate;
 - (id) initWithFrame:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - (void) setFrame:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - (id) currentCandidate;
 - (BOOL) hasCandidates;
 - (id) candidateResultSet;
 - (id) candidates;


@end
