
@protocol _UIMultilineTextContentSizing, NSCoding;
@interface UILabel : UIView <_UIMultilineTextContentSizing, NSCoding> {

    {CGSize="width"d"height"d} _size;
    @"UIColor" _highlightedColor;
    q _numberOfLines;
    q _measuredNumberOfLines;
    d _lastLineBaseline;
    d _previousBaselineOffsetFromBottom;
    d _firstLineBaseline;
    d _previousFirstLineBaseline;
    d _minimumScaleFactor;
    id _content;
    @"NSAttributedString" _synthesizedAttributedText;
    @"NSMutableDictionary" _defaultAttributes;
    d _minimumFontSize;
    q _lineSpacing;
    id _layout;
    @"_UILabelScaledMetrics" _scaledMetrics;
    {?="unused1"b3"highlighted"b1"autosizeTextToFit"b1"autotrackTextToFit"b1"baselineAdjustment"b2"unused2"b2"enabled"b1"wordRoundingEnabled"b1"explicitAlignment"b1"marqueeEnabled"b1"marqueeRunable"b1"marqueeRequired"b1"drawsLetterpress"b1"unused3"b1"usesExplicitPreferredMaxLayoutWidth"b1"determiningPreferredMaxLayoutWidth"b1"inSecondConstraintsPass"b1"drawsDebugBaselines"b1"explicitBaselineOffset"b1"usesSimpleTextEffects"b1"isComplexString"b1"wantsUnderlineForAccessibilityButtonShapesEnabled"b1} _textLabelFlags;
    BOOL __textColorFollowsTintColor;
    d _preferredMaxLayoutWidth;
}
 + ({CGSize=dd}) _legacy_adjustSizeForWebKitConstraining:({CGSize=dd})awithFont:(id)b;
 + (Class) layerClass;
 + (id) defaultFont;
 + (id) _defaultAttributes;
 + (^{__CFCharacterSet=}) _tooBigChars;
 + ({UIEdgeInsets=dddd}) _insetsForAttributedString:(id)ainView:(id)b;
 + ({UIEdgeInsets=dddd}) _insetsForString:(id)awithFont:(id)binView:(id)c;
 + ({CGRect={CGPoint=dd}{CGSize=dd}}) _insetRect:({CGRect={CGPoint=dd}{CGSize=dd}})aforAttributedString:(id)binView:(id)c;

 - (void) dealloc;
 - (void) setUserInteractionEnabled:(BOOL)a;
 - ({CGSize=dd}) _intrinsicSizeWithinSize:({CGSize=dd})a;
 - (void) _setTextColor:(id)a;
 - ({CGSize=dd}) sizeThatFits:({CGSize=dd})a;
 - (void) setNumberOfLines:(q)a;
 - (void) setTextAlignment:(q)a;
 - (void) setAttributedText:(id)a;
 - (void) setTextColor:(id)a;
 - (void) setFont:(id)a;
 - (void) setText:(id)a;
 - (d) _minimumFontSize;
 - (void) invalidateIntrinsicContentSize;
 - (d) _baselineOffsetFromBottom;
 - (d) _firstBaselineOffsetFromTop;
 - (void) tintColorDidChange;
 - ({CGSize=dd}) intrinsicContentSize;
 - (void) _didChangeFromIdiom:(q)aonScreen:(id)btraverseHierarchy:(BOOL)c;
 - (id) _scriptingInfo;
 - (void) _setLineBreakMode:(q)a;
 - (void) setHighlighted:(BOOL)a;
 - (void) _accessibilityButtonShapesParametersDidChange;
 - (id) _synthesizedAttributedText;
 - (void) _setFont:(id)a;
 - (BOOL) isHighlighted;
 - (id) attributedText;
 - (void) setAdjustsFontSizeToFitWidth:(BOOL)a;
 - (BOOL) adjustsFontSizeToFitWidth;
 - (id) textColor;
 - (q) textAlignment;
 - (void) _setMinimumFontSize:(d)a;
 - (void) setBaselineAdjustment:(q)a;
 - (q) _measuredNumberOfLines;
 - (void) _setWantsUnderlineForAccessibilityButtonShapesEnabled:(BOOL)a;
 - (void) setHighlightedTextColor:(id)a;
 - (void) updateConstraints;
 - ({CGSize=dd}) textSize;
 - (id) _disabledFontColor;
 - (id) _associatedScalingLabel;
 - (d) _actualScaleFactor;
 - (id) _defaultAttributes;
 - (void) _invalidateSynthesizedAttributedTextAndLayout;
 - (void) _invalidateTextSize;
 - (id) _shadow;
 - (BOOL) _textColorFollowsTintColor;
 - (id) currentTextColor;
 - (id) _compatibilityAttributedString;
 - (id) _synthesizedTextAttributes;
 - (void) _invalidateLayout;
 - (void) _accessibilityButtonShapesChangedNotification:(id)a;
 - (void) _invalidateAsNeededForNewSize:({CGSize=dd})aoldSize:({CGSize=dd})b;
 - (void) _setText:(id)a;
 - (void) _setTextAlignment:(q)a;
 - (BOOL) _attributedStringHasAttributesNotCoveredByPrimitives;
 - (BOOL) adjustsLetterSpacingToFitWidth;
 - (void) setLetterpressStyle:(id)a;
 - (id) _stringDrawingContext;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) _textRectForBounds:({CGRect={CGPoint=dd}{CGSize=dd}})alimitedToNumberOfLines:(q)bincludingShadow:(BOOL)c;
 - (BOOL) _shouldCeilSizeToViewScale;
 - (void) _baselineOffsetParametersDidChange;
 - (void) _setAttributedText:(id)aandTakeOwnership:(BOOL)b;
 - (BOOL) _updateScaledMetricsForRect:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - (id) highlightedTextColor;
 - (void) _setShadow:(id)a;
 - (void) _drawTextInRect:({CGRect={CGPoint=dd}{CGSize=dd}})abaselineCalculationOnly:(BOOL)b;
 - (d) _preferredMaxLayoutWidth;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) _ensureBaselineMetricsReturningBounds;
 - (BOOL) _needsDoubleUpdateConstraintsPass;
 - (void) _prepareForFirstIntrinsicContentSizeCalculation;
 - (void) _prepareForSecondIntrinsicContentSizeCalculationWithLayoutEngineBounds:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) textRectForBounds:({CGRect={CGPoint=dd}{CGSize=dd}})alimitedToNumberOfLines:(q)b;
 - (id) letterpressStyle;
 - ({CGSize=dd}) textSizeForWidth:(d)a;
 - (void) _drawFullMarqueeTextInRect:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - (void) _startMarqueeIfNecessary;
 - (BOOL) _isTextFieldCenteredLabel;
 - (void) drawTextInRect:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - (q) numberOfLines;
 - (void) setMarqueeRunning:(BOOL)a;
 - (id) _siblingMarqueeLabels;
 - (d) _maximumMarqueeTextWidth;
 - (void) _coordinateBeginTimeForMarqueeAnimations:(d)a;
 - (BOOL) marqueeRunning;
 - (void) _startMarquee;
 - (void) _stopMarqueeWithRedisplay:(BOOL)a;
 - (BOOL) _drawsUnderline;
 - (void) _setInSecondConstraintsPass:(BOOL)a;
 - (void) setPreferredMaxLayoutWidth:(d)a;
 - (void) _setDefaultAttributes:(id)a;
 - (void) _invalidateDefaultAttributes;
 - (void) _setSynthesizedAttributedText:(id)a;
 - ({UIEdgeInsets=dddd}) _contentInsetsFromFonts;
 - (void) _setTextColorFollowsTintColor:(BOOL)a;
 - (void) _setShadowUIOffset:({UIOffset=dd})a;
 - (void) setShadowBlur:(d)a;
 - (d) shadowBlur;
 - (void) setAdjustsLetterSpacingToFitWidth:(BOOL)a;
 - (id) _layoutDebuggingTitle;
 - (q) baselineAdjustment;
 - (d) _lastLineBaseline;
 - (void) _setWordRoundingEnabled:(BOOL)a;
 - (BOOL) _shouldDrawUnderlinesLikeWebKit;
 - (void) setMarqueeEnabled:(BOOL)a;
 - (void) setDrawsLetterpress:(BOOL)a;
 - (BOOL) drawsLetterpress;
 - (void) setDrawsUnderline:(BOOL)a;
 - (BOOL) drawsUnderline;
 - (d) preferredMaxLayoutWidth;
 - (d) _capOffsetFromBoundsTop;
 - (d) _firstLineBaselineOffsetFromBoundsTop;
 - (d) _firstLineCapFrameOriginY;
 - (void) _setFirstLineCapFrameOriginY:(d)a;
 - (d) _firstLineBaselineFrameOriginY;
 - (void) _setFirstLineBaselineFrameOriginY:(d)a;
 - (d) _lastLineBaselineFrameOriginY;
 - (void) _setLastLineBaselineFrameOriginY:(d)a;
 - (BOOL) _wantsUnderlineForAccessibilityButtonShapesEnabled;
 - (BOOL) _shouldShowAccessibilityButtonShapesUnderline;
 - (void) _resetUsesExplicitPreferredMaxLayoutWidth;
 - (void) _setColor:(id)a;
 - (void) setAutotrackTextToFit:(BOOL)a;
 - (BOOL) autotrackTextToFit;
 - (void) setCentersHorizontally:(BOOL)a;
 - (BOOL) centersHorizontally;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) textRectForBounds:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - (void) drawContentsInRect:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - (void) setRawSize:({CGSize=dd})a;
 - ({CGSize=dd}) rawSize;
 - (Q) defaultAccessibilityTraits;
 - (BOOL) isAccessibilityElementByDefault;
 - (BOOL) isElementAccessibilityExposedToInterfaceBuilder;
 - (void) encodeWithCoder:(id)a;
 - (id) initWithCoder:(id)a;
 - (BOOL) _usesSimpleTextEffects;
 - (BOOL) _drawsDebugBaselines;
 - (void) _setDrawsDebugBaselines:(BOOL)a;
 - (void) _setUsesSimpleTextEffects:(BOOL)a;
 - (void) setShadowOffset:({CGSize=dd})a;
 - (void) setShadowColor:(id)a;
 - (void) _commonInit;
 - (d) minimumScaleFactor;
 - (void) setMinimumScaleFactor:(d)a;
 - (id) _image;
 - (id) initWithFrame:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - (d) minimumFontSize;
 - (void) setFrame:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - (void) setColor:(id)a;
 - (void) setBounds:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - (id) color;
 - ({CGSize=dd}) shadowOffset;
 - (id) shadowColor;
 - (id) font;
 - (q) lineBreakMode;
 - (q) lineSpacing;
 - (void) setLineBreakMode:(q)a;
 - (void) setLineSpacing:(q)a;
 - (void) setMinimumFontSize:(d)a;
 - (id) text;
 - (void) drawRect:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - (BOOL) isEnabled;
 - (void) setEnabled:(BOOL)a;


@end
