
@protocol UIMovieScrubberTrackViewDataSource, UIMovieScrubberTrackViewDelegate;
@interface UIMovieScrubber : UIControl <UIMovieScrubberTrackViewDataSource, UIMovieScrubberTrackViewDelegate> {

    @"UIImageView" _thumbView;
    @"UIMovieScrubberTrackView" _trackView;
    @"UIMovieScrubberEditingView" _editingView;
    @"UILabel" _elapsedLabel;
    @"UILabel" _remainingLabel;
    i _timeComponents;
    @"UIImage" _fillImage;
    @"UIImage" _innerShadowImage;
    @"UIImage" _maskImage;
    @"UIImage" _shadowImage;
    @"<UIMovieScrubberDataSource>" _dataSource;
    @"<UIMovieScrubberDelegate>" _delegate;
    {CGRect="origin"{CGPoint="x"d"y"d}"size"{CGSize="width"d"height"d}} _trackRect;
    d _hitOffset;
    d _zoomDelay;
    BOOL _showTimeViews;
    BOOL _editable;
    d _value;
    d _maximumValue;
    d _minimumValue;
    {CGPoint="x"d"y"d} _touchLocationWhenTrackPressBegan;
    d _trimStartValue;
    d _trimEndValue;
    d _minTrimmedLength;
    d _maxTrimmedLength;
    d _zoomAnimationDuration;
    d _zoomAnimationDelay;
    {?="continuous"b1"animating"b1"creatingSnapshot"b1"needsReload"b1"layoutTimeViews"b1"computeTrackRect"b1"clampingTrimRange"I"zoomed"b1"zoomAnimating"b1"trackIsPressed"b1"trackAnimating"b1"thumbIsVisible"b1"handleIsPressed"b1"willBeginEditing"b1"editing"b1"editingHandle"I"rotationDisabled"I"isInNavigationBar"b1"delegateValueDidChange"b1"delegateStartValueDidChange"b1"delegateEndValueDidChange"b1"delegateWillBeginRequestingThumbnails"b1"delegateDidFinishRequestingThumbnails"b1"delegateWillBeginEditing"b1"delegateDidBeginEditing"b1"delegateDidCancelEditing"b1"delegateEditingAnimationFinished"b1"delegateWidthDeltaOriginXDelta"b1"delegateDidBeginAnimatingZoom"b1"delegateDidEndAnimatingZoom"b1"delegateWillZoom"b1"dataSourceRequestThumbnailImageIsSummmary"b1} _sliderFlags;
    d _edgeInset;
}
 + (id) timeStringForSeconds:(i)aforceFullWidthComponents:(BOOL)bisElapsed:(BOOL)c;

 - (d) duration;
 - (void) dealloc;
 - (void) setDelegate:(id)a;
 - (void) didMoveToWindow;
 - (void) reloadData;
 - (void) layoutSubviews;
 - ({CGSize=dd}) sizeThatFits:({CGSize=dd})a;
 - (void) touchesCancelled:(id)awithEvent:(id)b;
 - (id) scriptingInfoWithChildren;
 - (BOOL) cancelTouchTracking;
 - (void) didMoveToSuperview;
 - ({CGSize=dd}) intrinsicContentSize;
 - (BOOL) _alwaysHandleScrollerMouseEvent;
 - (id) _scriptingInfo;
 - (BOOL) isEditing;
 - (void) setEditing:(BOOL)aanimated:(BOOL)b;
 - (void) setEditing:(BOOL)a;
 - (BOOL) beginTrackingWithTouch:(id)awithEvent:(id)b;
 - (void) _controlTouchBegan:(id)awithEvent:(id)b;
 - (BOOL) continueTrackingWithTouch:(id)awithEvent:(id)b;
 - (void) _controlTouchMoved:(id)awithEvent:(id)b;
 - (void) endTrackingWithTouch:(id)awithEvent:(id)b;
 - (void) _controlTouchEnded:(id)awithEvent:(id)b;
 - (void) _sendDelayedActions;
 - (void) setEditable:(BOOL)a;
 - (void) _initSubviews;
 - (void) setValue:(d)aanimated:(BOOL)b;
 - (void) _sliderAnimationWillStart:(id)acontext:(id)b;
 - (void) _sliderAnimationDidStop:(id)afinished:(id)bcontext:(id)c;
 - (void) _setValue:(d)aandSendAction:(BOOL)b;
 - (BOOL) isContinuous;
 - (void) setContinuous:(BOOL)a;
 - (BOOL) isAnimatingValueChange;
 - (void) movieScrubberTrackView:(id)aclampedSizeWidthDelta:(d)bactualSizeWidthDelta:(d)coriginXDelta:(d)dminimumVisibleValue:(d)emaximumVisibleValue:(d)f;
 - (void) movieScrubberTrackViewDidExpand:(id)a;
 - (void) movieScrubberTrackViewDidCollapse:(id)a;
 - (void) movieScrubberTrackViewWillBeginRequestingThumbnails:(id)a;
 - (void) movieScrubberTrackViewDidFinishRequestingThumbnails:(id)a;
 - (d) movieScrubberTrackViewZoomAnimationDuration:(id)a;
 - (d) movieScrubberTrackViewZoomAnimationDelay:(id)a;
 - (void) movieScrubberTrackView:(id)arequestThumbnailImageForTimestamp:(id)bisSummaryThumbnail:(BOOL)c;
 - (d) movieScrubberTrackViewThumbnailAspectRatio:(id)a;
 - (d) movieScrubberTrackViewDuration:(id)a;
 - (id) movieScrubberTrackView:(id)aevenlySpacedTimestamps:(i)bstartingAt:(id)cendingAt:(id)d;
 - (BOOL) isInsideNavigationBar;
 - (void) setThumbnailImage:(^{CGImage=})aforTimestamp:(id)b;
 - (void) setZoomAnimationDuration:(d)a;
 - (void) _sliderValueDidChange:(id)a;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) _editingRect;
 - (void) setEdgeInset:(d)a;
 - (void) _trimAnimationDidStop:(id)afinished:(id)bcontext:(id)c;
 - (void) setThumbIsVisible:(BOOL)a;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) _editingRectForStartTime:(d)aendTime:(d)b;
 - (void) _cancelTrackPress:(BOOL)a;
 - (void) animateCancelEdit;
 - (void) _animateAfterEdit:(BOOL)a;
 - (void) _computeTrackRectForBounds:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) trackRect;
 - (void) _updateTimes;
 - (void) _updateThumbLocation;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) thumbRectForValue:(d)a;
 - (void) setTrimEndValue:(d)a;
 - (void) setTrimStartValue:(d)a;
 - (void) _trackPressWasHeld;
 - (void) _setZoomAnimating:(BOOL)a;
 - (void) setRotationDisabled:(BOOL)a;
 - (BOOL) pointInsideThumb:({CGPoint=dd})awithEvent:(id)b;
 - (i) _editingHandleWithTouch:(id)a;
 - (d) _valueForTouch:(id)a;
 - (void) _beginTrackPressWithTouch:(id)atouchesBegan:(BOOL)b;
 - (void) _cancelTrackPressIfNeccessaryWithTouch:(id)a;
 - (BOOL) thumbIsVisible;
 - (void) animateAfterEdit;
 - ({UIEdgeInsets=dddd}) alignmentMargins;
 - (d) trimStartValue;
 - (d) trimEndValue;
 - (BOOL) forceZoom;
 - (void) forceUnzoom;
 - (d) zoomMinimumValue;
 - (d) zoomMaximumValue;
 - (BOOL) isZoomAnimating;
 - (d) zoomDelay;
 - (void) setZoomDelay:(d)a;
 - (BOOL) showTimeViews;
 - (void) setShowTimeViews:(BOOL)a;
 - (d) maximumTrimLength;
 - (void) setMaximumTrimLength:(d)a;
 - (d) minimumTrimLength;
 - (void) setMinimumTrimLength:(d)a;
 - (d) edgeInset;
 - (id) init;
 - (id) delegate;
 - (void) setValue:(d)a;
 - (d) value;
 - (id) dataSource;
 - (id) initWithFrame:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - (void) setFrame:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - (void) setDuration:(d)a;
 - (void) setDataSource:(id)a;
 - (BOOL) isEditable;


@end
