
@protocol NSCoding;
@interface UINavigationItem : NSObject <NSCoding> {

    NSString _title;
    NSString _backButtonTitle;
    UIBarButtonItem _backBarButtonItem;
    NSString _prompt;
    long long _tag;
    id _context;
    UINavigationBar _navigationBar;
    UIView _defaultTitleView;
    UIView _titleView;
    UIView _backButtonView;
    NSArray _leftBarButtonItems;
    NSArray _rightBarButtonItems;
    NSArray _customLeftViews;
    NSArray _customRightViews;
    BOOL _hidesBackButton;
    BOOL _leftItemsSupplementBackButton;
    UIImageView _frozenTitleView;
    BOOL _barStyleIndependent;
    double _fontScaleAdjustment;
    NSString _pendingTitle;
    NSArray _abbreviatedBackButtonTitles;
    long long _independentBarStyle;
    NSArray _leftItemSpaceList;
    NSArray _rightItemSpaceList;
    unsigned long long _leftFlexibleSpaceCount;
    unsigned long long _rightFlexibleSpaceCount;
    NSMutableDictionary _backgroundImages;
    double __titleViewWidthForAnimations;
    double __idealCustomTitleWidth;
    UINavigationBar __owningNavigationBar;
}
@property (nonatomic, copy, readwrite) NSString* title;
@property (nonatomic, retain, readwrite) UIBarButtonItem* backBarButtonItem;
@property (nonatomic, retain, readwrite) UIView* titleView;
@property (nonatomic, copy, readwrite) NSString* prompt;
@property (nonatomic, assign, readwrite) NSNumber* hidesBackButton;
@property (nonatomic, copy, readwrite) NSArray* leftBarButtonItems;
@property (nonatomic, copy, readwrite) NSArray* rightBarButtonItems;
@property (nonatomic, assign, readwrite) NSNumber* leftItemsSupplementBackButton;
@property (nonatomic, retain, readwrite) UIBarButtonItem* leftBarButtonItem;
@property (nonatomic, retain, readwrite) UIBarButtonItem* rightBarButtonItem;
@property (nonatomic, assign, readwrite, getter=_isBarStyleIndependent, setter=_setBarStyleIndependent:) NSNumber* _barStyleIndependent;
@property (nonatomic, assign, readwrite, setter=_setIndependentBarStyle:) NSNumber* _independentBarStyle;
@property (nonatomic, assign, readwrite, setter=_setLeftFlexibleSpaceCount:) NSNumber* _leftFlexibleSpaceCount;
@property (nonatomic, assign, readwrite, setter=_setRightFlexibleSpaceCount:) NSNumber* _rightFlexibleSpaceCount;
@property (nonatomic, copy, readwrite, setter=_setLeftItemSpaceList:) NSArray* _leftItemSpaceList;
@property (nonatomic, copy, readwrite, setter=_setRightItemSpaceList:) NSArray* _rightItemSpaceList;
@property (nonatomic, assign, readwrite) NSNumber* _titleViewWidthForAnimations;
@property (nonatomic, assign, readwrite, setter=_setIdealCustomTitleWidth:) NSNumber* _idealCustomTitleWidth;
@property (nonatomic, copy, readwrite, setter=_setPendingTitle:) NSString* _pendingTitle;
@property (nonatomic, assign, readwrite, setter=_setFontScaleAdjustment:) NSNumber* _fontScaleAdjustment;
@property (nonatomic, copy, readwrite, setter=_setAbbreviatedBackButtonTitles:) NSArray* _abbreviatedBackButtonTitles;
@property (nonatomic, assign, readonly) NSMutableDictionary* _backgroundImages;
@property (nonatomic, assign, readwrite, getter=_owningNavigationBar, setter=_setOwningNavigationBar:) UINavigationBar* _owningNavigationBar;
 + (id) defaultFont;

 - (id) title;
 - (void) setTitle:(id)a;
 - (void) dealloc;
 - (id) navigationBar;
 - (BOOL) hidesBackButton;
 - (id) leftBarButtonItems;
 - (BOOL) leftItemsSupplementBackButton;
 - (id) _automationID;
 - (void) setTag:(long long)a;
 - (void) _setFontScaleAdjustment:(double)a;
 - (id) existingBackButtonView;
 - (id) initWithTitle:(id)a;
 - (void) _removeTitleAndButtonViews;
 - (void) _setCustomLeftViews:(id)a;
 - (void) _setCustomRightViews:(id)a;
 - (void) _setLeftBarButtonItems:(id)a;
 - (void) _setRightBarButtonItems:(id)a;
 - (void) _setLeftItemSpaceList:(id)a;
 - (void) _setRightItemSpaceList:(id)a;
 - (id) _defaultTitleView;
 - (void) _cleanupFrozenTitleView;
 - (void) _setPendingTitle:(id)a;
 - (void) _freezeCurrentTitleView;
 - (void) _addDefaultTitleViewToNavigationBarIfNecessary;
 - (void) _setTitleAnimationDidStop:(id)afinished:(id)bcontext:(id)c;
 - (void) _setTitle:(id)aanimated:(BOOL)bmatchBarButtonItemAnimationDuration:(BOOL)c;
 - (id) backButtonView;
 - (void) _setBackButtonTitle:(id)alineBreakMode:(long long)b;
 - (void) _removeBackButtonView;
 - (id) backButtonTitle;
 - (id) rightBarButtonItems;
 - (id) titleView;
 - (void) _setIdealCustomTitleWidth:(double)a;
 - (id) _customLeftViews;
 - (id) _customRightViews;
 - (void) setHidesBackButton:(BOOL)aanimated:(BOOL)b;
 - (void) _setLeftBarButtonItem:(id)a;
 - (void) _setRightBarButtonItem:(id)a;
 - (void) _setCustomRightView:(id)a;
 - (void) _setCustomLeftView:(id)a;
 - (void) _updateBarItemOwnersTo:(id)a;
 - (void) updateNavigationBarButtonsAnimated:(BOOL)a;
 - (id) _leftBarButtonItem;
 - (void) setLeftBarButtonItem:(id)aanimated:(BOOL)b;
 - (void) setObject:(id)aforLeftRightKeyPath:(id)banimated:(BOOL)c;
 - (id) _rightBarButtonItem;
 - (void) setRightBarButtonItem:(id)aanimated:(BOOL)b;
 - (BOOL) _accumulateViewsFromItems:(id)aisLeft:(BOOL)brefreshViews:(BOOL)c;
 - (id) _customLeftViewsCreating:(BOOL)a;
 - (id) _customLeftViewCreating:(BOOL)a;
 - (id) _customRightViewCreating:(BOOL)a;
 - (id) _customRightViewsCreating:(BOOL)a;
 - (void) _setCustomLeftRightView:(id)aleft:(BOOL)b;
 - (id) _customLeftView;
 - (void) setCustomLeftView:(id)aanimated:(BOOL)b;
 - (id) _customRightView;
 - (void) setCustomRightView:(id)aanimated:(BOOL)b;
 - (void) setLeftBarButtonItems:(id)aanimated:(BOOL)b;
 - (void) setRightBarButtonItems:(id)aanimated:(BOOL)b;
 - (void) _setLeftFlexibleSpaceCount:(unsigned long long)a;
 - (void) _setRightFlexibleSpaceCount:(unsigned long long)a;
 - (void) setTitleView:(id)a;
 - (void) setLeftBarButtonItem:(id)a;
 - (id) leftBarButtonItem;
 - (void) setRightBarButtonItem:(id)a;
 - (id) rightBarButtonItem;
 - (id) _firstNonSpaceItemInList:(id)a;
 - (void) _setBarStyleIndependent:(BOOL)a;
 - (id) _backgroundImages;
 - (void) _setAbbreviatedBackButtonTitles:(id)a;
 - (void) _setBackButtonPressed:(BOOL)a;
 - (void) setNavigationBar:(id)a;
 - (void) _setTitle:(id)aanimated:(BOOL)b;
 - (void) setBackButtonTitle:(id)a;
 - (void) setBackBarButtonItem:(id)a;
 - (id) currentBackButtonTitle;
 - (id) backBarButtonItem;
 - (void) _removeBarButtonItemViews;
 - (void) _replaceCustomLeftRightViewAtIndex:(unsigned long long)awithView:(id)bleft:(BOOL)c;
 - (id) prompt;
 - (void) setPrompt:(id)a;
 - (void) _updateItemsForLetterpressImagesVisualStateIfNecessary;
 - (void) setHidesBackButton:(BOOL)a;
 - (BOOL) _leftItemsWantBackButton;
 - (BOOL) _wantsBackButtonIndicator;
 - (id) _buttonForBackButtonIndicator;
 - (void) set_leftBarButtonItem:(id)a;
 - (void) set_rightBarButtonItem:(id)a;
 - (void) set_customRightView:(id)a;
 - (void) set_customLeftView:(id)a;
 - (void) set_rightBarButtonItems:(id)a;
 - (void) set_leftBarButtonItems:(id)a;
 - (void) set_customLeftViews:(id)a;
 - (void) set_customRightViews:(id)a;
 - (id) customLeftView;
 - (void) setCustomLeftView:(id)a;
 - (id) customRightView;
 - (void) setCustomRightView:(id)a;
 - (void) setLeftBarButtonItems:(id)a;
 - (void) setRightBarButtonItems:(id)a;
 - (id) _rightBarButtonItems;
 - (id) _leftBarButtonItems;
 - (void) setLeftItemsSupplementBackButton:(BOOL)a;
 - (void) _updateViewsForBarSizeChangeAndApply:(BOOL)a;
 - (id) _titleView;
 - (void) setCustomTitleView:(id)a;
 - (id) customTitleView;
 - (void) setCustomLeftItem:(id)a;
 - (id) customLeftItem;
 - (void) setCustomLeftItem:(id)aanimated:(BOOL)b;
 - (void) setCustomRightItem:(id)a;
 - (id) customRightItem;
 - (void) setCustomRightItem:(id)aanimated:(BOOL)b;
 - (id) _firstNonSpaceLeftItem;
 - (id) _firstNonSpaceRightItem;
 - (void) _setIndependentBarStyle:(long long)a;
 - (void) _setIndependentBackgroundImage:(id)ashadowImage:(id)bforBarMetrics:(long long)c;
 - (id) _independentBackgroundImageForBarMetrics:(long long)a;
 - (id) _independentShadowImage;
 - (double) _fontScaleAdjustment;
 - (id) _pendingTitle;
 - (id) _abbreviatedBackButtonTitles;
 - (BOOL) _isBarStyleIndependent;
 - (long long) _independentBarStyle;
 - (id) _leftItemSpaceList;
 - (id) _rightItemSpaceList;
 - (unsigned long long) _leftFlexibleSpaceCount;
 - (unsigned long long) _rightFlexibleSpaceCount;
 - (double) _titleViewWidthForAnimations;
 - (void) set_titleViewWidthForAnimations:(double)a;
 - (double) _idealCustomTitleWidth;
 - (id) _owningNavigationBar;
 - (void) _setOwningNavigationBar:(id)a;
 - (id) init;
 - (void) encodeWithCoder:(id)a;
 - (id) initWithCoder:(id)a;
 - (void) setContext:(id)a;
 - (long long) tag;
 - (id) context;


@end
