
@protocol UIGestureRecognizerDelegate;
@interface UINavigationItemButtonView : UINavigationItemView <UIGestureRecognizerDelegate> {

    long long _style;
    BOOL _pressed;
    _UIBarButtonItemAppearanceStorage _appearanceStorage;
    BOOL _customBackgroundImageChangedToOrFromNil;
    UIImageView _backgroundImageView;
    UIImageView _imageView;
    BOOL _wantsBlendModeForAccessibilityBackgrounds;
    unsigned long long _abbreviatedTitleIndex;
}

 - (id) title;
 - (void) dealloc;
 - (BOOL) pointInside:({CGPoint=dd})awithEvent:(id)b;
 - (void) layoutSubviews;
 - ({CGSize=dd}) sizeThatFits:({CGSize=dd})a;
 - (BOOL) gestureRecognizer:(id)ashouldReceiveTouch:(id)b;
 - ({UIEdgeInsets=dddd}) alignmentRectInsets;
 - (void) _focusedViewDidChange:(id)a;
 - (BOOL) _canDrawContent;
 - (void) traitCollectionDidChange:(id)a;
 - (BOOL) canBecomeFocused;
 - (Class) _appearanceGuideClass;
 - (void) tintColorDidChange;
 - (void) _focusedViewWillChange:(id)a;
 - (void) _didChangeFromIdiom:(long long)aonScreen:(id)btraverseHierarchy:(BOOL)c;
 - (id) _scriptingInfo;
 - (unsigned long long) _abbreviatedTitleIndex;
 - (void) _setAbbreviatedTitleIndex:(unsigned long long)a;
 - (void) setPressed:(BOOL)a;
 - (id) _appearanceStorage;
 - (void) _applyBarButtonAppearanceStorage:(id)awithTaggedSelectors:(id)b;
 - (BOOL) _wantsAccessibilityButtonShapes;
 - (id) _backButtonBackgroundImageForState:(unsigned long long)abarMetrics:(long long)b;
 - (void) _accessibilityButtonShapesDidChangeNotification:(id)a;
 - (BOOL) customBackgroundImageChangedToOrFromNil;
 - (BOOL) _suppressesBackIndicatorView;
 - (void) setPressed:(BOOL)ainitialPress:(BOOL)b;
 - (BOOL) pressed;
 - (void) _UIAppearance_setTintColor:(id)a;
 - (void) _setTintColor:(id)a;
 - (BOOL) _showsAccessibilityBackgroundWhenEnabled;
 - (void) _setWantsBlendModeForAccessibilityBackgrounds:(BOOL)a;
 - (void) _accessibilityButtonShapesParametersDidChange;
 - (void) backIndicatorViewHasRespondedToCustomBackgroundImageChange;
 - (void) setStyle:(long long)aanimated:(BOOL)b;
 - (BOOL) hasCustomBackgroundImage;
 - (id) backgroundImageView;
 - (id) _defaultFont;
 - (double) _backgroundVerticalPositionAdjustmentForBarMetrics:(long long)a;
 - (BOOL) _wantsBlendModeForAccessibilityBackgrounds;
 - (id) _tintColor;
 - (void) _setBackgroundImage:(id)aforState:(unsigned long long)bstyle:(long long)cbarMetrics:(long long)d;
 - (void) _UIAppearance_setBackgroundImage:(id)aforState:(unsigned long long)bstyle:(long long)cbarMetrics:(long long)d;
 - (void) _UIAppearance_setBackgroundImage:(id)aforState:(unsigned long long)bbarMetrics:(long long)c;
 - (void) _UIAppearance_setTitleTextAttributes:(id)aforState:(unsigned long long)b;
 - (void) _UIAppearance_setBackgroundVerticalPositionAdjustment:(double)aforBarMetrics:(long long)b;
 - (void) _UIAppearance_setTitlePositionAdjustment:({UIOffset=dd})aforBarMetrics:(long long)b;
 - (void) _setTitleTextAttributes:(id)aforState:(unsigned long long)b;
 - (void) _setTitlePositionAdjustment:({UIOffset=dd})aforBarMetrics:(long long)b;
 - (void) _setBackgroundVerticalPositionAdjustment:(double)aforBarMetrics:(long long)b;
 - (void) _setBackgroundImage:(id)aforState:(unsigned long long)bbarMetrics:(long long)c;
 - (id) _titleTextAttributesForState:(unsigned long long)a;
 - (void) _UIAppearance_setBackButtonBackgroundImage:(id)aforState:(unsigned long long)bbarMetrics:(long long)c;
 - (void) _setBackButtonBackgroundImage:(id)aforState:(unsigned long long)bbarMetrics:(long long)c;
 - (void) _UIAppearance_setBackButtonTitlePositionAdjustment:({UIOffset=dd})aforBarMetrics:(long long)b;
 - (void) _setBackButtonTitlePositionAdjustment:({UIOffset=dd})aforBarMetrics:(long long)b;
 - (void) _UIAppearance_setBackButtonBackgroundVerticalPositionAdjustment:(double)aforBarMetrics:(long long)b;
 - (void) _setBackButtonBackgroundVerticalPositionAdjustment:(double)aforBarMetrics:(long long)b;
 - (BOOL) _useSilverLookForBarStyle:(long long)a;
 - (id) _currentTextColorForBarStyle:(long long)a;
 - ({CGSize=dd}) _currentTextShadowOffsetForBarStyle:(long long)a;
 - (id) _currentTextShadowColorForBarStyle:(long long)a;
 - (double) _titleYAdjustmentCustomization;
 - (id) _currentCustomBackgroundNeedsDarkening:(^B)a;
 - (void) _drawBackground_legacy;
 - (void) _styleAnimationDidStop:(id)afinished:(id)bcontext:(id)c;
 - (double) _backButtonBackgroundVerticalPositionAdjustmentForBarMetrics:(long long)a;
 - (void) _installBackSelectGestureRecognizer;
 - (void) _uninstallBackSelectGestureRecognizer;
 - (void) _backSelectGestureChanged:(id)a;
 - ({UIOffset=dd}) _backButtonTitlePositionAdjustmentForBarMetrics:(long long)a;
 - (id) initWithFrame:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - ({CGSize=dd}) imageSize;
 - (id) image;
 - (void) setStyle:(long long)a;
 - (void) drawRect:({CGRect={CGPoint=dd}{CGSize=dd}})a;


@end
