
@protocol UIGestureRecognizerDelegate, _UIQueuingScrollViewDelegate, _UIQueuingScrollViewDataSource;
@interface UIPageViewController : UIViewController <UIGestureRecognizerDelegate, _UIQueuingScrollViewDelegate, _UIQueuingScrollViewDataSource> {

    @"<UIPageViewControllerDelegate>" _delegate;
    @"<UIPageViewControllerDataSource>" _dataSource;
    q _transitionStyle;
    q _navigationOrientation;
    q _spineLocation;
    BOOL _doubleSided;
    BOOL _pageControlRequiresValidation;
    @"NSArray" _viewControllers;
    @"_UIPageCurl" _pageCurl;
    @"UIPanGestureRecognizer" _panGestureRecognizer;
    @"UITapGestureRecognizer" _tapGestureRecognizer;
    BOOL _stashingViewControllersForRotation;
    @"NSArray" _viewControllersStashedForRotation;
    BOOL _interfaceRotating;
    @"NSMutableArray" _rotationSnapshotViews;
    q _spineLocationPriorToInterfaceRotation;
    {UIEdgeInsets="top"d"left"d"bottom"d"right"d} _tapRegionInsets;
    {CGSize="width"d"height"d} _tapRegionBreadths;
    {UIEdgeInsets="top"d"left"d"bottom"d"right"d} _effectiveTapRegionInsets;
    {CGSize="width"d"height"d} _effectiveTapRegionBreadths;
    ^{CGRect={CGPoint=dd}{CGSize=dd}} _tapRegions;
    d _pageSpacing;
    @"NSMutableDictionary" _cachedViewControllersForCurl;
    @"NSMutableArray" _cachedViewControllersForScroll;
    @"NSDictionary" _incomingAndOutgoingViewControllersForManualTransition;
    q _lastKnownNavigationDirection;
    q _disableAutorotationCount;
    {?="delegateWantsTransitionWillBegin"b1"delegateWantsTransitionCompleted"b1"delegateWantsTransitionsFinished"b1"delegateCustomizesSpineLocationForInterfaceOrientation"b1"delegateSupportedInterfaceOrientations"b1"delegatePreferredInterfaceOrientationForPresentation"b1"dataSourceSuppliesBeforeViewController"b1"dataSourceSuppliesAfterViewController"b1"dataSourceSuppliesPageCount"b1"dataSourceSuppliesPageNumber"b1} _delegateFlags;
}
 + (BOOL) doesOverrideSupportedInterfaceOrientations;
 + (BOOL) doesOverridePreferredInterfaceOrientationForPresentation;
 + (BOOL) _isSupportedTransitionStyle:(q)a;
 + (BOOL) _isNavigationOrientation:(q)asupportedForTransitionStyle:(q)b;
 + (BOOL) _isSpineLocation:(q)asupportedForTransitionStyle:(q)b;
 + (id) stringForSpineLocation:(q)a;
 + (id) _outgoingViewControllerKeys;
 + (id) _incomingViewControllerKeys;

 - (void) dealloc;
 - (void) setDelegate:(id)a;
 - (q) transitionStyle;
 - (q) _transitionStyle;
 - (id) gestureRecognizers;
 - (Q) supportedInterfaceOrientations;
 - (void) _handlePanGesture:(id)a;
 - (void) _handleTapGesture:(id)a;
 - (BOOL) _gestureRecognizerShouldBegin:(id)a;
 - (id) initWithNibName:(id)abundle:(id)b;
 - (void) loadView;
 - (BOOL) shouldAutorotateToInterfaceOrientation:(q)a;
 - (q) preferredInterfaceOrientationForPresentation;
 - (void) viewWillAppear:(BOOL)a;
 - (BOOL) _shouldPersistViewWhenCoding;
 - (void) viewWillUnload;
 - (BOOL) shouldAutomaticallyForwardRotationMethods;
 - (BOOL) shouldAutomaticallyForwardAppearanceMethods;
 - (void) viewDidAppear:(BOOL)a;
 - (void) viewWillDisappear:(BOOL)a;
 - (void) viewDidDisappear:(BOOL)a;
 - (void) willRotateToInterfaceOrientation:(q)aduration:(d)b;
 - (void) willAnimateRotationToInterfaceOrientation:(q)aduration:(d)b;
 - (void) didRotateFromInterfaceOrientation:(q)a;
 - (BOOL) _shouldSynthesizeSupportedOrientations;
 - (void) _beginDisablingInterfaceAutorotation;
 - (void) _endDisablingInterfaceAutorotation;
 - (id) viewControllers;
 - (id) _viewControllers;
 - (id) _pageControl;
 - (d) _pageSpacing;
 - (BOOL) _isPageControlVisible;
 - (q) navigationOrientation;
 - (void) _contentViewFrameOrBoundsDidChange;
 - (void) _pageControlValueChanged:(id)a;
 - (void) _updatePageControlViaDataSourceIfNecessary;
 - (void) _setSpineLocation:(q)a;
 - (void) _setPageSpacing:(d)a;
 - (id) initWithTransitionStyle:(q)anavigationOrientation:(q)boptions:(id)c;
 - (BOOL) _canHandleGestures;
 - (q) _navigationOrientation;
 - ({UIEdgeInsets=dddd}) _effectiveTapRegionInsets;
 - (void) _invalidateEffectiveTapRegions;
 - ({CGSize=dd}) _effectiveTapRegionBreadths;
 - (void) _setViewControllers:(id)awithCurlOfType:(q)bfromLocation:({CGPoint=dd})cdirection:(q)danimated:(BOOL)enotifyDelegate:(BOOL)fcompletion:(@?)g;
 - (void) _setViewControllers:(id)awithScrollInDirection:(q)banimated:(BOOL)ccompletion:(@?)d;
 - (BOOL) _child:(id)acanBeginAppearanceTransition:(BOOL)b;
 - (void) _child:(id)abeginAppearanceTransition:(BOOL)banimated:(BOOL)c;
 - (void) _child:(id)abeginAppearanceTransitionIfPossible:(BOOL)banimated:(BOOL)c;
 - (BOOL) _childCanEndAppearanceTransition:(id)a;
 - (void) _childEndAppearanceTransition:(id)a;
 - (void) _child:(id)aendAppearanceTransitionIfPossible:(BOOL)b;
 - (q) _requestSpineLocationForInterfaceOrientationAndUpdateStashedViewControllers:(q)a;
 - (void) _invalidatePageCurl;
 - (void) _setViewControllersStashedForRotation:(id)a;
 - (void) _sendChildViewWill:(BOOL)aappear:(BOOL)banimated:(BOOL)c;
 - ({_NSRange=QQ}) _validRangeForPresentationOfViewControllersWithSpineLocation:(q)a;
 - (id) _validatedViewControllersForPresentationOfViewControllers:(id)avalidRange:({_NSRange=QQ})b;
 - (id) _viewControllersForPendingSpineLocation:(q)a;
 - (void) _child:(id)awillRotateToInterfaceOrientation:(q)bduration:(d)c;
 - (void) _child:(id)awillAnimateRotationToInterfaceOrientation:(q)bduration:(d)c;
 - (void) _child:(id)adidRotateFromInterfaceOrientation:(q)b;
 - (id) _viewControllerBefore:(BOOL)aviewController:(id)b;
 - (BOOL) _isCurrentViewControllerStateValid;
 - (id) _validatedViewControllersForTransitionWithViewControllers:(id)aanimated:(BOOL)b;
 - (void) _populateOutgoingViewControllersInMap:(id)a;
 - (void) _populateIncomingViewControllersInMap:(id)awithViewControllers:(id)bforCurlInDirection:(q)c;
 - (void) _setViewControllers:(id)a;
 - (id) _viewControllersForCurlWithViewControllers:(id)adirection:(q)b;
 - (void) _invalidateViewControllersStashedForCurlFromDataSource;
 - (void) _cacheViewControllerForScroll:(id)a;
 - (id) _viewControllerAfterViewController:(id)a;
 - (id) _viewControllerBeforeViewController:(id)a;
 - (^{CGRect={CGPoint=dd}{CGSize=dd}}) _tapRegions;
 - (BOOL) _shouldNavigateInDirection:(^q)ainResponseToVelocity:(^d)bofGestureRecognizedByPanGestureRecognizer:(id)c;
 - (BOOL) _shouldNavigateInDirection:(^q)ainResponseToTapGestureRecognizer:(id)b;
 - (BOOL) _shouldBeginNavigationInDirection:(^q)ainResponseToPanGestureRecognizer:(id)b;
 - (id) _incomingViewControllersForGestureDrivenCurlInDirection:(q)a;
 - (q) _navigationEndDirectionInResponseToPanGestureRecognizer:(id)asuggestedVelocity:(^d)b;
 - (BOOL) _shouldCompleteManualCurlWithSuggestedVelocity:(^d)a;
 - (id) _queuingScrollView:(id)aviewBefore:(BOOL)bview:(id)c;
 - (void) _flushViewController:(id)aanimated:(BOOL)b;
 - (void) queuingScrollView:(id)awillManuallyScroll:(BOOL)btoRevealView:(id)cconcealView:(id)danimated:(BOOL)e;
 - (void) queuingScrollView:(id)adidCommitManualScroll:(BOOL)btoRevealView:(id)cconcealView:(id)ddirection:(q)eanimated:(BOOL)fcanComplete:(BOOL)g;
 - (void) queuingScrollView:(id)adidEndManualScroll:(BOOL)btoRevealView:(id)cdirection:(q)danimated:(BOOL)edidFinish:(BOOL)fdidComplete:(BOOL)g;
 - (void) queuingScrollView:(id)adidBailoutOfScrollAndRevealedView:(id)b;
 - (void) queuingScrollViewDidFinishScrolling:(id)a;
 - (BOOL) queuingScrollViewShouldLayoutSubviews:(id)a;
 - (id) queuingScrollView:(id)aviewBeforeView:(id)b;
 - (id) queuingScrollView:(id)aviewAfterView:(id)b;
 - (void) queuingScrollView:(id)adidFlushView:(id)banimated:(BOOL)c;
 - (q) spineLocation;
 - ({UIEdgeInsets=dddd}) _tapRegionInsets;
 - (void) _setTapRegionInsets:({UIEdgeInsets=dddd})a;
 - ({CGSize=dd}) _tapRegionBreadths;
 - (void) _setTapRegionBreadths:({CGSize=dd})a;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) _disabledScrollingRegion;
 - (void) _setDisabledScrollingRegion:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - ({CGSize=dd}) _contentSizeForSize:({CGSize=dd})a;
 - (void) setViewControllers:(id)adirection:(q)banimated:(BOOL)ccompletion:(@?)d;
 - (id) _viewControllersStashedForRotation;
 - (BOOL) _isInterfaceRotating;
 - (void) encodeWithCoder:(id)a;
 - (id) initWithCoder:(id)a;
 - (id) delegate;
 - (id) dataSource;
 - (BOOL) isDoubleSided;
 - (void) setDataSource:(id)a;
 - (id) _scrollView;
 - (id) _contentView;
 - (void) setDoubleSided:(BOOL)a;


@end
