
@protocol UIDimmingViewDelegate, UIGestureRecognizerDelegatePrivate;
@interface UIPopoverPresentationController : UIPresentationController <UIDimmingViewDelegate, UIGestureRecognizerDelegatePrivate> {

    @"UIViewController" _contentViewController;
    @"UIViewController" _splitParentController;
    @"_UIPopoverView" _popoverView;
    @"UIDimmingView" _dimmingView;
    @"UIView" _layoutConstraintView;
    {CGRect="origin"{CGPoint="x"d"y"d}"size"{CGSize="width"d"height"d}} _targetRectInEmbeddingView;
    @"UIBarButtonItem" _targetBarButtonItem;
    unsigned long long _currentArrowDirection;
    long long _popoverBackgroundStyle;
    @"UIColor" _backgroundColor;
    @"_UIPopoverLayoutInfo" _preferredLayoutInfo;
    Class _popoverBackgroundViewClass;
    {CGSize="width"d"height"d} _popoverContentSize;
    {CGRect="origin"{CGPoint="x"d"y"d}"size"{CGSize="width"d"height"d}} _targetRectInContainerView;
    {CGRect="origin"{CGPoint="x"d"y"d}"size"{CGSize="width"d"height"d}} _embeddedTargetRect;
    long long _popoverControllerStyle;
    BOOL _ignoresKeyboardNotifications;
    unsigned int draggingChildScrollViewCount;
    id _target;
    SEL _didEndSelector;
    @"UIViewController" _modalPresentationFromViewController;
    @"UIViewController" _modalPresentationToViewController;
    unsigned long long _toViewAutoResizingMask;
    @"UIViewController" _slidingViewController;
    BOOL _isLayoutDisabled;
    BOOL _useSourceViewBoundsAsSourceRect;
    @"UIView" _presentingView;
    unsigned long long _presentationEdge;
    long long _presentationDirection;
    int _presentationState;
    BOOL _didPresentInActiveSequence;
    unsigned long long _slideTransitionCount;
    @"UIPanGestureRecognizer" _vendedGestureRecognizer;
    @"UIPanGestureRecognizer" _dimmingViewGestureRecognizer;
    {?="isPresentingModalViewController"b1"isPresentingActionSheet"b1"wasIgnoringDimmingViewTouchesBeforeScrolling"b1"isInTextEffectsWindow"b1"isEmbeddingInView"b1"embeddedPresentationBounces"b1} _popoverControllerFlags;
    BOOL _isDismissingBecauseDimmingViewTapped;
    BOOL _allowResizePastTargetRect;
    BOOL _dismissesOnRotation;
    BOOL _showsTargetRect;
    BOOL _showsOrientationMarker;
    BOOL _showsPresentationArea;
    BOOL _retainsSelfWhilePresented;
    BOOL __centersPopoverIfSourceViewNotSet;
    BOOL __shouldHideArrow;
    unsigned long long _permittedArrowDirections;
    @"UIView" _sourceView;
    @"UIBarButtonItem" _barButtonItem;
    unsigned long long _popoverArrowDirection;
    double __dimmingViewTopEdgeInset;
    {UIEdgeInsets="top"d"left"d"bottom"d"right"d} _popoverLayoutMargins;
    {CGRect="origin"{CGPoint="x"d"y"d}"size"{CGSize="width"d"height"d}} _sourceRect;
}
 + (void) _setAlwaysAllowPopoverPresentations:(BOOL)a;
 + ({UIEdgeInsets=dddd}) _defaultPopoverLayoutMarginsForPopoverControllerStyle:(long long)aandContentViewController:(id)b;
 + (BOOL) _showTargetRectPref;
 + (Class) _popoverViewClass;
 + (BOOL) _forceAttemptsToAvoidKeyboard;
 + (BOOL) _alwaysAllowPopoverPresentations;

 - (void) dealloc;
 - (long long) presentationStyle;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) frameOfPresentedViewInContainerView;
 - (BOOL) _presentationPotentiallyUnderlapsStatusBar;
 - (long long) _popoverControllerStyle;
 - (BOOL) shouldRemovePresentersView;
 - (BOOL) shouldPresentInFullscreen;
 - (id) _presentationView;
 - (BOOL) _shouldDisableInteractionDuringTransitions;
 - (void) preferredContentSizeDidChangeForChildContentContainer:(id)a;
 - (BOOL) _isDismissing;
 - (id) _passthroughViews;
 - (BOOL) _shouldOccludeDuringPresentation;
 - (id) _managingSplitViewController;
 - (id) presentedView;
 - (void) presentationTransitionDidEnd:(BOOL)a;
 - (void) dismissalTransitionDidEnd:(BOOL)a;
 - (void) _transitionToDidEnd;
 - (void) _transitionFromDidEnd;
 - (void) presentationTransitionWillBegin;
 - (void) dismissalTransitionWillBegin;
 - (void) _transitionFromWillBegin;
 - (void) _transitionToWillBegin;
 - (void) containerViewWillLayoutSubviews;
 - (long long) _defaultPresentationStyleForTraitCollection:(id)a;
 - (void) viewWillTransitionToSize:({CGSize=dd})awithTransitionCoordinator:(id)b;
 - (id) initWithPresentedViewController:(id)apresentingViewController:(id)b;
 - (BOOL) _shouldChangeStatusBarViewController;
 - (BOOL) _shouldKeepCurrentFirstResponder;
 - ({UIEdgeInsets=dddd}) _baseContentInsets;
 - (BOOL) _forcesPreferredAnimationControllers;
 - (id) _preferredAnimationControllerForPresentation;
 - (id) _preferredAnimationControllerForDismissal;
 - (BOOL) _embedsInView;
 - (void) setPopoverContentSize:({CGSize=dd})aanimated:(BOOL)b;
 - (void) _containedViewControllerModalStateChanged;
 - (long long) _popoverBackgroundStyle;
 - (id) popoverView;
 - (BOOL) _popoverBackgroundViewWantsDefaultContentAppearance;
 - (BOOL) _manuallyHandlesContentViewControllerAppearanceCalls;
 - (BOOL) isPopoverVisible;
 - (BOOL) _isShimmingPopoverControllerPresentation;
 - (id) _dimmingView;
 - (id) _splitParentController;
 - (void) _adjustPopoverForNewContentSizeFromViewController:(id)aallowShrink:(BOOL)b;
 - (void) _newViewControllerWillBePushed:(id)a;
 - (void) _newViewControllerWasPushed:(id)a;
 - (void) setSourceRect:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - (void) setSourceView:(id)a;
 - (void) setBarButtonItem:(id)a;
 - (unsigned long long) permittedArrowDirections;
 - (void) setPermittedArrowDirections:(unsigned long long)a;
 - (id) passthroughViews;
 - (void) setPassthroughViews:(id)a;
 - (id) dimmingView;
 - (void) dimmingViewWasTapped:(id)a;
 - (unsigned long long) arrowDirection;
 - (void) _setManagingSplitViewController:(id)a;
 - (void) _setGesturesEnabled:(BOOL)a;
 - (void) setPopoverBackgroundViewClass:(Class)a;
 - (void) _dismissPopoverAnimated:(BOOL)astateOnly:(BOOL)bnotifyDelegate:(BOOL)c;
 - (unsigned long long) _slideTransitionCount;
 - (void) _setPopoverBackgroundStyle:(long long)a;
 - (void) _setRetainsSelfWhilePresented:(BOOL)a;
 - (double) _dimmingViewTopEdgeInset;
 - (void) _setDimmingViewTopEdgeInset:(double)a;
 - (void) _performHierarchyCheckOnViewController:(id)a;
 - (void) _transitionFromViewController:(id)atoViewController:(id)banimated:(BOOL)c;
 - (void) _setContentViewController:(id)aanimated:(BOOL)b;
 - (void) setAllowResizePastTargetRect:(BOOL)a;
 - (id) _layoutInfoForCurrentKeyboardState;
 - (double) _presentationAnimationDuration;
 - (void) setPreferredLayoutInfo:(id)a;
 - (BOOL) _isPresenting;
 - (void) setPopoverFrame:({CGRect={CGPoint=dd}{CGSize=dd}})aanimated:(BOOL)b;
 - ({UIEdgeInsets=dddd}) popoverLayoutMargins;
 - (void) setPopoverLayoutMargins:({UIEdgeInsets=dddd})a;
 - (Class) _popoverLayoutInfoForChromeClass:(Class)a;
 - (id) _layoutInfoFromLayoutInfo:(id)aforCurrentKeyboardStateAndHostingWindow:(id)b;
 - (void) _startWatchingForKeyboardNotificationsIfNecessary;
 - (id) _layoutInfoForCurrentKeyboardStateAndHostingWindow:(id)a;
 - (void) _incrementSlideTransitionCount:(BOOL)a;
 - (void) _setPresentationState:(int)a;
 - (@?) _completionBlockForDismissalWhenNotifyingDelegate:(BOOL)a;
 - (int) _presentationState;
 - (void) _setPresentingView:(id)a;
 - (void) _setPresentationEdge:(unsigned long long)a;
 - (void) _postludeForDismissal;
 - (void) _resetSlideTransitionCount;
 - (Class) _defaultChromeViewClass;
 - ({CGPoint=dd}) _centerPointForScale:(double)aframe:({CGRect={CGPoint=dd}{CGSize=dd}})banchor:({CGPoint=dd})c;
 - (BOOL) isPresentingOrDismissing;
 - (void) _startWatchingForScrollViewNotifications;
 - (Class) popoverBackgroundViewClass;
 - ({CGSize=dd}) popoverContentSize;
 - (void) _commonPresentPopoverFromRect:({CGRect={CGPoint=dd}{CGSize=dd}})ainView:(id)bpermittedArrowDirections:(unsigned long long)canimated:(BOOL)d;
 - (void) _setSplitParentController:(id)a;
 - (void) _setPopoverView:(id)a;
 - (void) _stopWatchingForNotifications;
 - (double) _dismissalAnimationDuration;
 - (BOOL) _attemptsToAvoidKeyboard;
 - (void) _moveAwayFromTheKeyboard:(id)a;
 - (void) _keyboardStateChanged:(id)a;
 - (void) _invalidateLayoutInfo;
 - (void) _scrollViewWillBeginDragging:(id)a;
 - (void) _scrollViewDidEndDragging:(id)a;
 - (void) _stopWatchingForKeyboardNotifications;
 - (void) _stopWatchingForScrollViewNotifications;
 - ({CGSize=dd}) _currentPopoverContentSize;
 - (void) setPopoverContentSize:({CGSize=dd})a;
 - (unsigned long long) popoverArrowDirection;
 - (void) _setContentViewController:(id)abackgroundStyle:(long long)banimated:(BOOL)c;
 - (void) _startWatchingForNavigationControllerNotifications:(id)a;
 - (void) _stopWatchingForNavigationControllerNotifications:(id)a;
 - (BOOL) _ignoresKeyboardNotifications;
 - (void) _setIgnoresKeyboardNotifications:(BOOL)a;
 - (void) setDimmingView:(id)a;
 - (BOOL) allowResizePastTargetRect;
 - (BOOL) dismissesOnRotation;
 - (void) setDismissesOnRotation:(BOOL)a;
 - (BOOL) showsTargetRect;
 - (void) setShowsTargetRect:(BOOL)a;
 - (BOOL) showsOrientationMarker;
 - (void) setShowsOrientationMarker:(BOOL)a;
 - (BOOL) showsPresentationArea;
 - (void) setShowsPresentationArea:(BOOL)a;
 - (BOOL) _retainsSelfWhilePresented;
 - (id) preferredLayoutInfo;
 - (id) _presentingView;
 - (unsigned long long) _presentationEdge;
 - (void) setPopoverArrowDirection:(unsigned long long)a;
 - (id) sourceView;
 - (id) _popoverHostingWindow;
 - (BOOL) _centersPopoverIfSourceViewNotSet;
 - (id) _sourceView;
 - (id) _exceptionStringForNilSourceViewOrBarButtonItem;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) _sourceRect;
 - (BOOL) _shouldHideArrow;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) sourceRect;
 - (id) barButtonItem;
 - (void) _setCentersPopoverIfSourceViewNotSet:(BOOL)a;
 - (void) _setShouldHideArrow:(BOOL)a;
 - (id) init;
 - (void) setBackgroundColor:(id)a;
 - (id) backgroundColor;


@end
