
@protocol UIDimmingViewDelegate, UIGestureRecognizerDelegatePrivate, UIAppearanceContainer;
@interface UIPopoverController : NSObject <UIDimmingViewDelegate, UIGestureRecognizerDelegatePrivate, UIAppearanceContainer> {

    id _delegate;
    UIViewController _contentViewController;
    UIViewController _splitParentController;
    _UIPopoverView _popoverView;
    UIDimmingView _dimmingView;
    UIView _layoutConstraintView;
    {CGRect="origin"{CGPoint="x"d"y"d}"size"{CGSize="width"d"height"d}} _targetRectInEmbeddingView;
    UIBarButtonItem _targetBarButtonItem;
    unsigned long long _requestedArrowDirections;
    unsigned long long _currentArrowDirection;
    long long _popoverBackgroundStyle;
    UIColor _backgroundColor;
    _UIPopoverLayoutInfo _preferredLayoutInfo;
    Class _popoverBackgroundViewClass;
    {CGSize="width"d"height"d} _popoverContentSize;
    {CGRect="origin"{CGPoint="x"d"y"d}"size"{CGSize="width"d"height"d}} _targetRectInDimmingView;
    {CGRect="origin"{CGPoint="x"d"y"d}"size"{CGSize="width"d"height"d}} _embeddedTargetRect;
    long long _popoverControllerStyle;
    BOOL _ignoresKeyboardNotifications;
    UIView _currentPresentationView;
    {CGRect="origin"{CGPoint="x"d"y"d}"size"{CGSize="width"d"height"d}} _currentPresentationRectInView;
    unsigned long long _originalArrowDirections;
    unsigned int draggingChildScrollViewCount;
    id _target;
    SEL _didEndSelector;
    UIViewController _modalPresentationFromViewController;
    UIViewController _modalPresentationToViewController;
    unsigned long long _toViewAutoResizingMask;
    UIViewController _slidingViewController;
    UIView _presentingView;
    unsigned long long _presentationEdge;
    long long _presentationDirection;
    int _presentationState;
    BOOL _didPresentInActiveSequence;
    unsigned long long _slideTransitionCount;
    UIPanGestureRecognizer _vendedGestureRecognizer;
    UIPanGestureRecognizer _dimmingViewGestureRecognizer;
    NSArray _passthroughViews;
    {?="isPresentingModalViewController"b1"isPresentingActionSheet"b1"wasIgnoringDimmingViewTouchesBeforeScrolling"b1"isInTextEffectsWindow"b1"isEmbeddingInView"b1"embeddedPresentationBounces"b1} _popoverControllerFlags;
    BOOL _allowResizePastTargetRect;
    BOOL _dismissesOnRotation;
    BOOL _showsTargetRect;
    BOOL _showsOrientationMarker;
    BOOL _showsPresentationArea;
    BOOL _retainsSelfWhilePresented;
    unsigned long long _popoverArrowDirection;
    UIPopoverPresentationController _presentationController;
    {UIEdgeInsets="top"d"left"d"bottom"d"right"d} _popoverLayoutMargins;
}
@property (nonatomic, assign, readwrite) NSNumber* delegate;
@property (nonatomic, retain, readwrite) UIViewController* contentViewController;
@property (nonatomic, assign, readwrite) NSNumber* popoverContentSize;
@property (nonatomic, assign, readonly, getter=isPopoverVisible) NSNumber* popoverVisible;
@property (nonatomic, assign, readwrite) NSNumber* popoverArrowDirection;
@property (nonatomic, copy, readwrite) NSArray* passthroughViews;
@property (nonatomic, copy, readwrite) UIColor* backgroundColor;
@property (nonatomic, assign, readwrite) NSNumber* popoverLayoutMargins;
@property (nonatomic, retain, readwrite) NSObject* popoverBackgroundViewClass;
@property (nonatomic, retain, readwrite) UIDimmingView* dimmingView;
@property (nonatomic, assign, readwrite) NSNumber* allowResizePastTargetRect;
@property (nonatomic, assign, readwrite) NSNumber* dismissesOnRotation;
@property (nonatomic, retain, readwrite) _UIPopoverLayoutInfo* preferredLayoutInfo;
@property (nonatomic, assign, readwrite, getter=_presentingView, setter=_setPresentingView:) UIView* presentingView;
@property (nonatomic, assign, readwrite, getter=_presentationEdge, setter=_setPresentationEdge:) NSNumber* presentationEdge;
@property (nonatomic, assign, readwrite, setter=_setIgnoresKeyboardNotifications:) NSNumber* _ignoresKeyboardNotifications;
@property (nonatomic, retain, readwrite, getter=_presentationController, setter=_setPresentationController:) UIPopoverPresentationController* presentationController;
@property (nonatomic, assign, readwrite) NSNumber* showsTargetRect;
@property (nonatomic, assign, readwrite) NSNumber* showsOrientationMarker;
@property (nonatomic, assign, readwrite) NSNumber* showsPresentationArea;
@property (nonatomic, assign, readwrite, getter=_retainsSelfWhilePresented, setter=_setRetainsSelfWhilePresented:) NSNumber* retainsSelfWhilePresented;
 + (BOOL) _popoversDisabled;
 + (BOOL) _useLegacyPopoverControllers;
 + ({UIEdgeInsets=dddd}) _defaultPopoverLayoutMarginsForPopoverControllerStyle:(long long)aandContentViewController:(id)b;
 + (BOOL) _showTargetRectPref;
 + (Class) _popoverViewClass;
 + (BOOL) _forceAttemptsToAvoidKeyboard;
 + (void) _setForceModernPopoverUse:(BOOL)a;

 - (void) dealloc;
 - (void) setDelegate:(id)a;
 - (BOOL) _gestureRecognizer:(id)ashouldBeRequiredToFailByGestureRecognizer:(id)b;
 - (BOOL) _gestureRecognizerShouldBegin:(id)a;
 - (long long) _popoverControllerStyle;
 - (BOOL) _gestureRecognizer:(id)ashouldRequireFailureOfGestureRecognizer:(id)b;
 - (id) _presentationController;
 - (BOOL) _isDismissing;
 - (id) _managingSplitViewController;
 - (id) contentViewController;
 - (BOOL) _embedsInView;
 - (void) setPopoverContentSize:({CGSize=dd})aanimated:(BOOL)b;
 - (void) _containedViewControllerModalStateChanged;
 - (long long) _popoverBackgroundStyle;
 - (id) popoverView;
 - (BOOL) _popoverBackgroundViewWantsDefaultContentAppearance;
 - (void) dismissPopoverAnimated:(BOOL)a;
 - (BOOL) _manuallyHandlesContentViewControllerAppearanceCalls;
 - (BOOL) isPopoverVisible;
 - (void) _setPresentationController:(id)a;
 - (void) _modalTransition:(int)afromViewController:(id)btoViewController:(id)ctarget:(id)ddidEndSelector:(SEL)e;
 - (id) _dimmingView;
 - (id) _splitParentController;
 - (void) _adjustPopoverForNewContentSizeFromViewController:(id)aallowShrink:(BOOL)b;
 - (void) _newViewControllerWillBePushed:(id)a;
 - (void) _newViewControllerWasPushed:(id)a;
 - (BOOL) popoverPresentationControllerShouldDismissPopover:(id)a;
 - (void) popoverPresentationControllerDidDismissPopover:(id)a;
 - (void) popoverPresentationController:(id)awillRepositionPopoverToRect:(N^{CGRect={CGPoint=dd}{CGSize=dd}})binView:(N^@)c;
 - (id) passthroughViews;
 - (void) setPassthroughViews:(id)a;
 - (id) dimmingView;
 - (id) initWithContentViewController:(id)a;
 - (void) presentPopoverFromRect:({CGRect={CGPoint=dd}{CGSize=dd}})ainView:(id)bpermittedArrowDirections:(unsigned long long)canimated:(BOOL)d;
 - (void) presentPopoverFromBarButtonItem:(id)apermittedArrowDirections:(unsigned long long)banimated:(BOOL)c;
 - (void) setContentViewController:(id)a;
 - (void) dimmingViewWasTapped:(id)a;
 - (void) _setManagingSplitViewController:(id)a;
 - (id) _gestureRecognizerForPresentationFromEdge:(unsigned long long)a;
 - (void) _setGesturesEnabled:(BOOL)a;
 - (id) _initWithContentViewController:(id)apopoverControllerStyle:(long long)b;
 - (void) setPopoverBackgroundViewClass:(Class)a;
 - (void) _presentPopoverFromEdge:(unsigned long long)aofView:(id)banimated:(BOOL)c;
 - (void) _dismissPopoverAnimated:(BOOL)astateOnly:(BOOL)bnotifyDelegate:(BOOL)c;
 - (unsigned long long) _slideTransitionCount;
 - (void) _setPopoverBackgroundStyle:(long long)a;
 - (void) _setRetainsSelfWhilePresented:(BOOL)a;
 - (void) _performHierarchyCheckOnViewController:(id)a;
 - (void) _transitionFromViewController:(id)atoViewController:(id)banimated:(BOOL)c;
 - (void) _swipe:(id)a;
 - (void) setContentViewController:(id)aanimated:(BOOL)b;
 - (BOOL) _shimPopoverPresentationController;
 - (void) setAllowResizePastTargetRect:(BOOL)a;
 - (id) _layoutInfoForCurrentKeyboardState;
 - (double) _presentationAnimationDuration;
 - (void) setPreferredLayoutInfo:(id)a;
 - (BOOL) _isPresenting;
 - (void) setPopoverFrame:({CGRect={CGPoint=dd}{CGSize=dd}})aanimated:(BOOL)b;
 - ({UIEdgeInsets=dddd}) popoverLayoutMargins;
 - (void) setPopoverLayoutMargins:({UIEdgeInsets=dddd})a;
 - (void) _layoutDimmingViewForInterfaceOrientationOfHostingWindow:(id)a;
 - (Class) _popoverLayoutInfoForChromeClass:(Class)a;
 - (id) _layoutInfoFromLayoutInfo:(id)aforCurrentKeyboardStateAndHostingWindow:(id)b;
 - (void) _startWatchingForKeyboardNotificationsIfNecessary;
 - (id) _layoutInfoForCurrentKeyboardStateAndHostingWindow:(id)a;
 - (void) _incrementSlideTransitionCount:(BOOL)a;
 - (void) _startWatchingForWindowRotations;
 - (void) _setPresentationState:(int)a;
 - (@?) _completionBlockForDismissalWhenNotifyingDelegate:(BOOL)a;
 - (int) _presentationState;
 - (void) _setPresentingView:(id)a;
 - (void) _setPresentationEdge:(unsigned long long)a;
 - (void) _postludeForDismissal;
 - (void) _resetSlideTransitionCount;
 - (void) _presentPopoverBySlidingIn:(BOOL)afromEdge:(unsigned long long)bofView:(id)canimated:(BOOL)dstateOnly:(BOOL)enotifyDelegate:(BOOL)f;
 - (Class) _defaultChromeViewClass;
 - ({CGPoint=dd}) _centerPointForScale:(double)aframe:({CGRect={CGPoint=dd}{CGSize=dd}})banchor:({CGPoint=dd})c;
 - (void) _presentPopoverFromRect:({CGRect={CGPoint=dd}{CGSize=dd}})aembeddedInView:(id)busingViewForLayoutConstraints:(id)cpermittedArrowDirections:(unsigned long long)danimate:(BOOL)e;
 - (BOOL) _shimPresentSlidingPopoverAnimated:(BOOL)a;
 - (BOOL) isPresentingOrDismissing;
 - (void) _startWatchingForScrollViewNotifications;
 - (Class) popoverBackgroundViewClass;
 - ({CGSize=dd}) popoverContentSize;
 - (void) _setupPresentationController;
 - (void) _presentShimmedPopoverFromRect:({CGRect={CGPoint=dd}{CGSize=dd}})ainView:(id)bpermittedArrowDirections:(unsigned long long)canimated:(BOOL)d;
 - (void) _commonPresentPopoverFromRect:({CGRect={CGPoint=dd}{CGSize=dd}})ainView:(id)bpermittedArrowDirections:(unsigned long long)canimated:(BOOL)d;
 - (void) _updateDimmingViewTransformForInterfaceOrientationOfHostingWindow:(id)a;
 - (void) _beginMapsTransitionToNewViewController:(id)anewTargetRect:({CGRect={CGPoint=dd}{CGSize=dd}})binView:(id)carrowDirections:(unsigned long long)dslideDuration:(double)eexpandDuration:(double)f;
 - (void) _setSplitParentController:(id)a;
 - (void) _setPopoverView:(id)a;
 - (void) _stopWatchingForNotifications;
 - (double) _dismissalAnimationDuration;
 - (BOOL) _attemptsToAvoidKeyboard;
 - (void) _moveAwayFromTheKeyboard:(id)a;
 - (void) _keyboardStateChanged:(id)a;
 - (void) _invalidateLayoutInfo;
 - (BOOL) _canRepresentAutomatically;
 - (void) _hostingWindowWillRotate:(id)a;
 - (void) _hostingWindowDidRotate:(id)a;
 - (void) _scrollViewWillBeginDragging:(id)a;
 - (void) _scrollViewDidEndDragging:(id)a;
 - (void) _stopWatchingForKeyboardNotifications;
 - (void) _stopWatchingForScrollViewNotifications;
 - (void) _stopWatchingForWindowRotations;
 - ({CGSize=dd}) _currentPopoverContentSize;
 - (void) _modalAnimation:(id)afinished:(id)bcontext:(id)c;
 - (void) setPopoverContentSize:({CGSize=dd})a;
 - (unsigned long long) popoverArrowDirection;
 - (void) _presentPopoverFromRect:({CGRect={CGPoint=dd}{CGSize=dd}})aembeddedInView:(id)busingViewForLayoutConstraints:(id)cpermittedArrowDirections:(unsigned long long)d;
 - (void) _setContentViewController:(id)abackgroundStyle:(long long)banimated:(BOOL)c;
 - (void) _beginMapsTransitionToNewViewController:(id)aarrowDirections:(unsigned long long)bslideDuration:(double)cexpandDuration:(double)d;
 - (void) _startWatchingForNavigationControllerNotifications:(id)a;
 - (void) _stopWatchingForNavigationControllerNotifications:(id)a;
 - (BOOL) _ignoresKeyboardNotifications;
 - (void) _setIgnoresKeyboardNotifications:(BOOL)a;
 - (void) setDimmingView:(id)a;
 - (BOOL) allowResizePastTargetRect;
 - (BOOL) dismissesOnRotation;
 - (void) setDismissesOnRotation:(BOOL)a;
 - (BOOL) showsTargetRect;
 - (void) setShowsTargetRect:(BOOL)a;
 - (BOOL) showsOrientationMarker;
 - (void) setShowsOrientationMarker:(BOOL)a;
 - (BOOL) showsPresentationArea;
 - (void) setShowsPresentationArea:(BOOL)a;
 - (BOOL) _retainsSelfWhilePresented;
 - (id) preferredLayoutInfo;
 - (id) _presentingView;
 - (unsigned long long) _presentationEdge;
 - (void) setPopoverArrowDirection:(unsigned long long)a;
 - (id) init;
 - (id) delegate;
 - (void) setBackgroundColor:(id)a;
 - (id) backgroundColor;


@end
