
@protocol _UIAppearanceContainer, _UITraitEnvironmentInternal, _UIContentContainerInternal, UIAppearanceContainer, UITraitEnvironment, UIContentContainer;
@interface UIPresentationController : NSObject <_UIAppearanceContainer, _UITraitEnvironmentInternal, _UIContentContainerInternal, UIAppearanceContainer, UITraitEnvironment, UIContentContainer> {

    BOOL _isDisconnectedRoot;
    BOOL _transitionAsDisconnectedRoot;
    BOOL _needsDidAppear;
    BOOL _needsDidDisappear;
    BOOL _monitorsSystemLayoutFittingSize;
    BOOL _didUpdateLayoutForStatusBarAndInterfaceOrientation;
    id _target;
    SEL _didEndSelector;
    @"UITraitCollection" _lastNotifiedTraitCollection;
    @"UIView" _snapshotOverlayView;
    BOOL _changedPresentingViewControllerDuringAdaptation;
    BOOL _containerIgnoresDirectTouchEvents;
    @"UIViewController" _presentingViewController;
    @"UIViewController" _presentedViewController;
    @"UIView" _containerView;
    @"<UIAdaptivePresentationControllerDelegate>" _delegate;
    @"UITraitCollection" _overrideTraitCollection;
    @"<UIViewControllerAnimatedTransitioning>" _currentTransitionController;
    @"<UIViewControllerInteractiveTransitioning>" _currentInteractionController;
    @"UIView" _presentationView;
    @"UIView" __currentPresentationSuperview;
    q _state;
    @? __transitionViewForCurrentTransition;
    @? __fromViewForCurrentTransition;
    @? __toViewForCurrentTransition;
    @? __computeToEndFrameForCurrentTransition;
    @? __currentTransitionDidComplete;
    {CGSize="width"d"height"d} _preferredContentSize;
}
@property (nonatomic, retain, readwrite) UIViewController* presentingViewController;
@property (nonatomic, retain, readwrite) UIViewController* presentedViewController;
@property (nonatomic, assign, readonly) NSNumber* presentationStyle;
@property (nonatomic, retain, readwrite) UIView* containerView;
@property (nonatomic, assign, readwrite) NSNumber* delegate;
@property (nonatomic, copy, readwrite) UITraitCollection* overrideTraitCollection;
@property (nonatomic, retain, readwrite, _currentTransitionController, _setCurrentTransitionController:) NSNumber* currentTransitionController;
@property (nonatomic, retain, readwrite, _currentInteractionController, _setCurrentInteractionController:) NSNumber* currentInteractionController;
@property (nonatomic, retain, readwrite, _presentationView, _setPresentationView:) UIView* presentationView;
@property (nonatomic, retain, readwrite, _currentPresentationSuperview, _setCurrentPresentationSuperview:) UIView* _currentPresentationSuperview;
@property (nonatomic, assign, readwrite) NSNumber* state;
@property (nonatomic, assign, readwrite, _preferredContentSize, _setPreferredContentSize:) NSNumber* _preferredContentSize;
@property (nonatomic, assign, readwrite, _changedPresentingViewControllerDuringAdaptation, _setChangedPresentingViewControllerDuringAdaptation:) NSNumber* changedPresentingViewControllerDuringAdaptation;
@property (nonatomic, copy, readwrite) NSNumber* _transitionViewForCurrentTransition;
@property (nonatomic, copy, readwrite) NSNumber* _fromViewForCurrentTransition;
@property (nonatomic, copy, readwrite) NSNumber* _toViewForCurrentTransition;
@property (nonatomic, copy, readwrite) NSNumber* _computeToEndFrameForCurrentTransition;
@property (nonatomic, copy, readwrite) NSNumber* _currentTransitionDidComplete;
@property (nonatomic, assign, readwrite, _containerIgnoresDirectTouchEvents, _setContainerIgnoresDirectTouchEvents:) NSNumber* containerIgnoresDirectTouchEvents;
@property (nonatomic, assign, readonly) UITraitCollection* traitCollection;
@property (nonatomic, assign, readonly) NSNumber* preferredContentSize;
 + (BOOL) _preventsAppearanceProxyCustomization;
 + ({UIEdgeInsets=dddd}) _defaultBaseContentInsetsForFrame:({CGRect={CGPoint=dd}{CGSize=dd}})ainView:(id)b;

 - (void) dealloc;
 - (void) setDelegate:(id)a;
 - (id) containerView;
 - (id) presentingViewController;
 - (id) traitCollection;
 - (q) presentationStyle;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) frameOfPresentedViewInContainerView;
 - (BOOL) _presentationPotentiallyUnderlapsStatusBar;
 - (void) _setContainerView:(id)a;
 - (id) presentedViewController;
 - (void) _parent:(id)awillTransitionToTraitCollection:(id)bwithTransitionCoordinator:(id)c;
 - (void) _window:(id)awillTransitionToTraitCollection:(id)bwithTransitionCoordinator:(id)c;
 - (id) _appearanceContainer;
 - ({?=qq}) __sizeClassPair;
 - (void) traitCollectionDidChange:(id)a;
 - (id) _traitCollectionForChildEnvironment:(id)a;
 - (Class) _appearanceGuideClass;
 - (BOOL) _monitorsSystemLayoutFittingSize;
 - (void) _systemLayoutFittingSizeDidChangeForChildContentContainer:(id)achildViewController:(id)b;
 - (void) _updateTraitsIfNecessary;
 - (void) _containerViewWillLayoutSubviews;
 - (void) containerViewDidLayoutSubviews;
 - (void) _setPresentingViewController:(id)a;
 - (void) _setPresentedViewController:(id)a;
 - (void) systemLayoutFittingSizeDidChangeForChildContentContainer:(id)a;
 - (void) _performBlockWithoutTriggeringResponderEvents:(@?)a;
 - (BOOL) shouldRemovePresentersView;
 - (@?) _currentTransitionDidComplete;
 - (BOOL) presenting;
 - (void) _setPresentationView:(id)a;
 - (BOOL) dismissing;
 - (void) _setCurrentInteractionController:(id)a;
 - (BOOL) _shouldDisablePresentersAppearanceCallbacks;
 - (void) _setCurrentTransitionController:(id)a;
 - (void) _setCurrentPresentationSuperview:(id)a;
 - (void) set_transitionViewForCurrentTransition:(@?)a;
 - (void) set_computeToEndFrameForCurrentTransition:(@?)a;
 - (void) set_currentTransitionDidComplete:(@?)a;
 - (void) set_fromViewForCurrentTransition:(@?)a;
 - (void) set_toViewForCurrentTransition:(@?)a;
 - (BOOL) shouldPresentInFullscreen;
 - (id) _fullscreenPresentationSuperview;
 - (id) _currentContextPresentationSuperview;
 - (BOOL) _shouldRespectDefinesPresentationContext;
 - (BOOL) _isAdapted;
 - (void) _adjustOrientationIfNecessaryInWindow:(id)aforViewController:(id)bpreservingViewController:(id)c;
 - (void) _initViewHierarchyForPresentationSuperview:(id)a;
 - (void) runTransitionForCurrentState;
 - (BOOL) _changedPresentingViewControllerDuringAdaptation;
 - (void) _setChangedPresentingViewControllerDuringAdaptation:(BOOL)a;
 - (id) _childPresentationController;
 - (@?) _transitionViewForCurrentTransition;
 - (id) _currentPresentationSuperview;
 - (@?) _toViewForCurrentTransition;
 - (@?) _computeToEndFrameForCurrentTransition;
 - (id) _presentationView;
 - (id) _parentPresentationControllerImmediate:(BOOL)a;
 - (id) _parentPresentationController;
 - (id) _currentInteractionController;
 - (BOOL) _shouldDisableInteractionDuringTransitions;
 - (void) preferredContentSizeDidChangeForChildContentContainer:(id)a;
 - (@?) _fromViewForCurrentTransition;
 - (void) transitionDidFinish:(BOOL)a;
 - (void) transitionDidStart;
 - (void) _releaseSnapshot;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) _frameOfPresentedViewControllerViewInSuperview;
 - (id) _passthroughViews;
 - (BOOL) _shouldOccludeDuringPresentation;
 - (void) _enableOcclusion:(BOOL)a;
 - (BOOL) _containerIgnoresDirectTouchEvents;
 - (BOOL) _transitioningTo;
 - (BOOL) _transitioningFrom;
 - (void) _transplantView:(id)atoSuperview:(id)b;
 - (void) _transplantView:(id)atoSuperview:(id)batIndex:(Q)c;
 - (BOOL) _shouldGrabPresentersView;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) _frameForChildContentContainer:(id)a;
 - (id) presentedView;
 - (void) presentationTransitionDidEnd:(BOOL)a;
 - (void) dismissalTransitionDidEnd:(BOOL)a;
 - (void) _transitionToDidEnd;
 - (void) _transitionFromDidEnd;
 - (void) presentationTransitionWillBegin;
 - (void) _beginOcclusionIfNecessary:(BOOL)a;
 - (void) dismissalTransitionWillBegin;
 - (void) _transitionFromWillBegin;
 - (void) _transitionToWillBegin;
 - (void) containerViewWillLayoutSubviews;
 - (q) _defaultPresentationStyleForTraitCollection:(id)a;
 - (q) adaptivePresentationStyleForTraitCollection:(id)a;
 - (id) _activePresentationController;
 - ({CGSize=dd}) sizeForChildContentContainer:(id)awithParentContainerSize:({CGSize=dd})b;
 - (void) viewWillTransitionToSize:({CGSize=dd})awithTransitionCoordinator:(id)b;
 - ({CGSize=dd}) preferredContentSize;
 - (void) _setPreferredContentSize:({CGSize=dd})a;
 - (q) adaptivePresentationStyle;
 - (id) initWithPresentedViewController:(id)apresentingViewController:(id)b;
 - (id) _parentTraitEnvironment;
 - (id) _parentTraitCollection;
 - (id) overrideTraitCollection;
 - (id) _sharedParent:(id)awillTransitionToTraitCollection:(id)bwithTransitionCoordinator:(id)c;
 - (void) willTransitionToTraitCollection:(id)awithTransitionCoordinator:(id)b;
 - ({CGSize=dd}) _flipSize:({CGSize=dd})a;
 - (BOOL) presented;
 - (BOOL) dismissed;
 - (BOOL) _shouldChangeStatusBarViewController;
 - (BOOL) _shouldKeepCurrentFirstResponder;
 - (BOOL) _preserveResponderAcrossWindows;
 - (void) _setContainerIgnoresDirectTouchEvents:(BOOL)a;
 - (void) _presentWithAnimationController:(id)ainteractionController:(id)btarget:(id)cdidEndSelector:(SEL)d;
 - (void) _dismissWithAnimationController:(id)ainteractionController:(id)btarget:(id)cdidEndSelector:(SEL)d;
 - (void) _transitionToPresentationController:(id)awithTransitionCoordinator:(id)b;
 - (id) _firstCurrentContextChildInWindow;
 - ({UIEdgeInsets=dddd}) _baseContentInsets;
 - (id) _descriptionForPrintingViewControllerHierarchy;
 - (void) _coverWithSnapshot;
 - (BOOL) _forcesPreferredAnimationControllers;
 - (id) _preferredAnimationControllerForPresentation;
 - (id) _preferredAnimationControllerForDismissal;
 - (BOOL) _shouldAdaptFromTraitCollection:(id)atoTraitCollection:(id)b;
 - (id) _presentationControllerForTraitCollection:(id)a;
 - (void) _sendDelegateWillPresentWithAdaptiveStyle:(q)atransitionCoordinator:(id)b;
 - (id) _presentedViewControllerForPresentationController:(id)atraitCollection:(id)b;
 - (void) setOverrideTraitCollection:(id)a;
 - ({CGSize=dd}) _preferredContentSize;
 - (id) _currentTransitionController;
 - (q) state;
 - (void) setState:(q)a;
 - (id) delegate;
 - (void) _cleanup;


@end
