
@protocol _UIBasicAnimationFactory, NSCoding;
@interface UISegmentedControl : UIControl <_UIBasicAnimationFactory, NSCoding> {

    NSMutableArray _segments;
    long long _selectedSegment;
    long long _highlightedSegment;
    UIView _removedSegment;
    long long _barStyle;
    id _appearanceStorage;
    UIView _backgroundBarView;
    double _enabledAlpha;
    {?="style"b3"size"b2"delegateAlwaysNotifiesDelegateOfSegmentClicks"b1"momentaryClick"b1"tracking"b1"autosizeToFitSegments"b1"isSizingToFit"b1"autosizeText"b1"transparentBackground"b1"useProportionalWidthSegments"b1"translucentBackground"b1"appearanceNeedsUpdate"b1} _segmentedControlFlags;
    BOOL __hasTranslucentOptionsBackground;
}
 + (BOOL) automaticallyNotifiesObserversForKey:(id)a;
 + (double) defaultHeight;
 + (id) _modernDividerImage;
 + (id) _modernBackgroundSelected:(BOOL)ahighlighted:(BOOL)b;
 + (double) defaultHeightForStyle:(long long)asize:(int)b;
 + (double) defaultHeightForStyle:(long long)a;

 - (void) dealloc;
 - (void) setDelegate:(id)a;
 - (void) _populateArchivedSubviews:(id)a;
 - (void) setAlpha:(double)a;
 - ({CGSize=dd}) _intrinsicSizeWithinSize:({CGSize=dd})a;
 - (void) layoutSubviews;
 - (BOOL) _contentHuggingDefault_isUsuallyFixedHeight;
 - ({CGSize=dd}) sizeThatFits:({CGSize=dd})a;
 - (id) _basicAnimationForView:(id)awithKeyPath:(id)b;
 - (BOOL) gestureRecognizerShouldBegin:(id)a;
 - (void) touchesBegan:(id)awithEvent:(id)b;
 - (void) touchesMoved:(id)awithEvent:(id)b;
 - (void) touchesEnded:(id)awithEvent:(id)b;
 - (void) touchesCancelled:(id)awithEvent:(id)b;
 - ({UIEdgeInsets=dddd}) alignmentRectInsets;
 - (id) scriptingInfoWithChildren;
 - (BOOL) useBlockyMagnificationInClassic;
 - (id) _tintColorArchivingKey;
 - (void) setTintColor:(id)a;
 - (void) sizeToFit;
 - (void) _didMoveFromWindow:(id)atoWindow:(id)b;
 - (void) updateForMiniBarState:(BOOL)a;
 - (void) setTitleTextAttributes:(id)aforState:(unsigned long long)b;
 - (void) setControlSize:(int)a;
 - (void) setBarStyle:(long long)a;
 - (long long) barStyle;
 - (double) _backgroundVerticalPositionAdjustmentForBarMetrics:(long long)a;
 - (int) controlSize;
 - (void) setBackgroundImage:(id)aforState:(unsigned long long)bbarMetrics:(long long)c;
 - (void) _setTitleTextAttributes:(id)aforState:(unsigned long long)b;
 - (void) _setBackgroundVerticalPositionAdjustment:(double)aforBarMetrics:(long long)b;
 - (void) _setBackgroundImage:(id)aforState:(unsigned long long)bbarMetrics:(long long)c;
 - (BOOL) shouldTrack;
 - (BOOL) pointMostlyInside:({CGPoint=dd})awithEvent:(id)b;
 - (id) _optionsBackgroundImage;
 - (BOOL) _isInMiniBar;
 - (BOOL) _isInTranslucentToolbar;
 - (BOOL) isMomentary;
 - (double) _barHeight;
 - (void) setMomentary:(BOOL)a;
 - (id) viewForBaselineLayout;
 - (void) _commonSegmentedControlInit;
 - (id) _createAndAddSegmentAtIndex:(int)aposition:(unsigned int)bwithInfo:(id)c;
 - (void) setSegmentedControlStyle:(long long)a;
 - (void) _setSelectedSegmentIndex:(long long)anotify:(BOOL)banimate:(BOOL)c;
 - (void) _setEnabled:(BOOL)aforcePropagateToSegments:(BOOL)b;
 - (void) removeAllSegments;
 - (void) _setCurrentBackgroundImage:(id)a;
 - (void) _updateOptionsBackground;
 - (void) _updateDividerImageForSegmentAtIndex:(unsigned long long)a;
 - (void) _setNeedsAppearanceUpdate;
 - (void) _setControlSize:(int)aandInvalidate:(BOOL)b;
 - (void) _insertSegment:(int)awithInfo:(id)banimated:(BOOL)c;
 - (void) setSelectedSegmentIndex:(long long)a;
 - (void) _removeSegmentAnimationFinished:(id)afinished:(id)bcontext:(id)c;
 - (void) setRemovedSegment:(id)a;
 - (void) _setSelectedSegmentIndex:(long long)anotify:(BOOL)b;
 - (BOOL) _shouldSelectSegmentAtIndex:(long long)a;
 - (void) _setSelected:(BOOL)aforSegmentAtIndex:(int)bforceInfoDisplay:(BOOL)c;
 - (void) _resetForAppearanceChange;
 - (void) _setHighlightedSegmentHighlighted:(BOOL)a;
 - (void) highlightSegment:(int)a;
 - (void) _clearSelectedSegment;
 - (void) _tapSegmentAtPoint:({CGPoint=dd})a;
 - (void) _setDividerImage:(id)aforLeftSegmentState:(unsigned long long)brightSegmentState:(unsigned long long)cbarMetrics:(long long)d;
 - (id) _createSegmentAtIndex:(int)aposition:(unsigned int)bwithInfo:(id)c;
 - (void) selectSegment:(int)a;
 - (BOOL) apportionsSegmentWidthsByContent;
 - (void) setApportionsSegmentWidthsByContent:(BOOL)a;
 - (id) initWithItems:(id)a;
 - (BOOL) _optionsShadowHidden;
 - (void) _setOptionsShadowHidden:(BOOL)a;
 - (void) _setSegmentedControlAppearance:(^{?=@dd{?=@@@@@{CGSize=dd}}{?=@@@@@{CGSize=dd}}{?=@@@@@{CGSize=dd}}{?=@@@@@{CGSize=dd}}B})a;
 - (void) _setAppearanceIsTiled:(BOOL)aleftCapWidth:(unsigned long long)brightCapWidth:(unsigned long long)c;
 - (long long) segmentedControlStyle;
 - (long long) segmentControlStyle;
 - (void) setSegmentControlStyle:(long long)a;
 - (void) _setAutosizeText:(BOOL)a;
 - (void) _setTranslucentOptionsBackground:(BOOL)a;
 - (void) setTransparentBackground:(BOOL)a;
 - (BOOL) transparentBackground;
 - (BOOL) _usesNewAnimations;
 - (void) _setUsesNewAnimations:(BOOL)a;
 - (void) insertSegmentWithTitle:(id)aatIndex:(unsigned long long)banimated:(BOOL)c;
 - (void) insertSegmentWithImage:(id)aatIndex:(unsigned long long)banimated:(BOOL)c;
 - (void) _insertSegmentWithAttributedTitle:(id)aatIndex:(unsigned long long)banimated:(BOOL)c;
 - (void) removeSegmentAtIndex:(unsigned long long)aanimated:(BOOL)b;
 - (void) setTitle:(id)aforSegmentAtIndex:(unsigned long long)b;
 - (id) titleForSegmentAtIndex:(unsigned long long)a;
 - (void) _setAttributedTitle:(id)aforSegmentAtIndex:(unsigned long long)b;
 - (id) _attributedTitleForSegmentAtIndex:(unsigned long long)a;
 - (void) setImage:(id)aforSegmentAtIndex:(unsigned long long)b;
 - (id) imageForSegmentAtIndex:(unsigned long long)a;
 - (void) setWidth:(double)aforSegmentAtIndex:(unsigned long long)b;
 - (double) widthForSegmentAtIndex:(unsigned long long)a;
 - (void) setContentOffset:({CGSize=dd})aforSegmentAtIndex:(unsigned long long)b;
 - ({CGSize=dd}) contentOffsetForSegmentAtIndex:(unsigned long long)a;
 - (void) setEnabled:(BOOL)aforSegmentAtIndex:(unsigned long long)b;
 - (BOOL) isEnabledForSegmentAtIndex:(unsigned long long)a;
 - (unsigned long long) numberOfSegments;
 - (long long) selectedSegmentIndex;
 - (void) _animateContentChangeWithAnimations:(@?)acompletion:(@?)b;
 - (id) removedSegment;
 - (void) _setOptionsBackgroundImage:(id)a;
 - (id) backgroundImageForState:(unsigned long long)abarMetrics:(long long)b;
 - (void) setDividerImage:(id)aforLeftSegmentState:(unsigned long long)brightSegmentState:(unsigned long long)cbarMetrics:(long long)d;
 - (id) dividerImageForLeftSegmentState:(unsigned long long)arightSegmentState:(unsigned long long)bbarMetrics:(long long)c;
 - (id) titleTextAttributesForState:(unsigned long long)a;
 - (void) setContentPositionAdjustment:({UIOffset=dd})aforSegmentType:(long long)bbarMetrics:(long long)c;
 - ({UIOffset=dd}) contentPositionAdjustmentForSegmentType:(long long)abarMetrics:(long long)b;
 - (id) _badgeValueForSegmentAtIndex:(unsigned long long)a;
 - (void) _setBadgeValue:(id)aforSegmentAtIndex:(unsigned long long)b;
 - (BOOL) _hasTranslucentOptionsBackground;
 - (id) infoViewForSegment:(long long)a;
 - (void) setSelectedSegment:(long long)a;
 - (id) initWithFrame:({CGRect={CGPoint=dd}{CGSize=dd}})awithStyle:(long long)bwithItems:(id)c;
 - (void) setAlwaysNotifiesDelegateOfSegmentClicks:(BOOL)a;
 - (void) setImagePadding:({CGSize=dd})aforSegment:(unsigned long long)b;
 - (void) addSegmentWithTitle:(id)a;
 - (void) insertSegment:(unsigned long long)awithTitle:(id)banimated:(BOOL)c;
 - (void) insertSegment:(unsigned long long)awithImage:(id)banimated:(BOOL)c;
 - (void) removeSegment:(unsigned long long)aanimated:(BOOL)b;
 - (void) setTitle:(id)aforSegment:(unsigned long long)b;
 - (id) titleForSegment:(unsigned long long)a;
 - (void) setImage:(id)aforSegment:(unsigned long long)b;
 - (id) imageForSegment:(unsigned long long)a;
 - (void) setWidth:(float)aforSegment:(unsigned long long)b;
 - (float) widthForSegment:(unsigned long long)a;
 - (void) setContentOffset:({CGSize=dd})aforSegment:(unsigned long long)b;
 - ({CGSize=dd}) contentOffsetForSegment:(unsigned long long)a;
 - (void) setEnabled:(BOOL)aforSegment:(unsigned long long)b;
 - (BOOL) isEnabledForSegment:(unsigned long long)a;
 - (long long) selectedSegment;
 - (void) encodeWithCoder:(id)a;
 - (id) initWithCoder:(id)a;
 - (id) initWithFrame:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) frame;
 - (void) setFrame:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) bounds;
 - (void) setBounds:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - (void) setEnabled:(BOOL)a;


@end
