
@protocol _UIBasicAnimationFactory, NSCoding;
@interface UISegmentedControl : UIControl <_UIBasicAnimationFactory, NSCoding> {

    @"NSMutableArray" _segments;
    q _selectedSegment;
    q _highlightedSegment;
    @"UIView" _removedSegment;
    q _barStyle;
    id _appearanceStorage;
    @"UIView" _backgroundBarView;
    d _enabledAlpha;
    {?="style"b3"size"b2"delegateAlwaysNotifiesDelegateOfSegmentClicks"b1"momentaryClick"b1"tracking"b1"autosizeToFitSegments"b1"isSizingToFit"b1"autosizeText"b1"transparentBackground"b1"useProportionalWidthSegments"b1"translucentBackground"b1"appearanceNeedsUpdate"b1} _segmentedControlFlags;
    BOOL __hasTranslucentOptionsBackground;
}
 + (BOOL) automaticallyNotifiesObserversForKey:(id)a;
 + (d) defaultHeight;
 + (id) _modernDividerImage;
 + (id) _modernBackgroundSelected:(BOOL)ahighlighted:(BOOL)b;
 + (d) defaultHeightForStyle:(q)asize:(i)b;
 + (d) defaultHeightForStyle:(q)a;

 - (void) dealloc;
 - (void) setDelegate:(id)a;
 - (void) _populateArchivedSubviews:(id)a;
 - (void) setAlpha:(d)a;
 - ({CGSize=dd}) _intrinsicSizeWithinSize:({CGSize=dd})a;
 - (void) layoutSubviews;
 - (BOOL) _contentHuggingDefault_isUsuallyFixedHeight;
 - ({CGSize=dd}) sizeThatFits:({CGSize=dd})a;
 - (id) _basicAnimationForView:(id)awithKeyPath:(id)b;
 - (BOOL) gestureRecognizerShouldBegin:(id)a;
 - (void) touchesBegan:(id)awithEvent:(id)b;
 - (void) touchesMoved:(id)awithEvent:(id)b;
 - (void) touchesEnded:(id)awithEvent:(id)b;
 - (void) touchesCancelled:(id)awithEvent:(id)b;
 - ({UIEdgeInsets=dddd}) alignmentRectInsets;
 - (id) scriptingInfoWithChildren;
 - (BOOL) useBlockyMagnificationInClassic;
 - (id) _tintColorArchivingKey;
 - (void) setTintColor:(id)a;
 - (void) sizeToFit;
 - (void) _didMoveFromWindow:(id)atoWindow:(id)b;
 - (void) updateForMiniBarState:(BOOL)a;
 - (void) setTitleTextAttributes:(id)aforState:(Q)b;
 - (void) setControlSize:(i)a;
 - (void) setBarStyle:(q)a;
 - (q) barStyle;
 - (d) _backgroundVerticalPositionAdjustmentForBarMetrics:(q)a;
 - (i) controlSize;
 - (void) setBackgroundImage:(id)aforState:(Q)bbarMetrics:(q)c;
 - (void) _setTitleTextAttributes:(id)aforState:(Q)b;
 - (void) _setBackgroundVerticalPositionAdjustment:(d)aforBarMetrics:(q)b;
 - (void) _setBackgroundImage:(id)aforState:(Q)bbarMetrics:(q)c;
 - (BOOL) shouldTrack;
 - (BOOL) pointMostlyInside:({CGPoint=dd})awithEvent:(id)b;
 - (id) _optionsBackgroundImage;
 - (BOOL) _isInMiniBar;
 - (BOOL) _isInTranslucentToolbar;
 - (BOOL) isMomentary;
 - (d) _barHeight;
 - (void) setMomentary:(BOOL)a;
 - (id) viewForBaselineLayout;
 - (void) _commonSegmentedControlInit;
 - (id) _createAndAddSegmentAtIndex:(i)aposition:(I)bwithInfo:(id)c;
 - (void) setSegmentedControlStyle:(q)a;
 - (void) _setSelectedSegmentIndex:(q)anotify:(BOOL)banimate:(BOOL)c;
 - (void) _setEnabled:(BOOL)aforcePropagateToSegments:(BOOL)b;
 - (void) removeAllSegments;
 - (void) _setCurrentBackgroundImage:(id)a;
 - (void) _updateOptionsBackground;
 - (void) _updateDividerImageForSegmentAtIndex:(Q)a;
 - (void) _setNeedsAppearanceUpdate;
 - (void) _setControlSize:(i)aandInvalidate:(BOOL)b;
 - (void) _insertSegment:(i)awithInfo:(id)banimated:(BOOL)c;
 - (void) setSelectedSegmentIndex:(q)a;
 - (void) _removeSegmentAnimationFinished:(id)afinished:(id)bcontext:(id)c;
 - (void) setRemovedSegment:(id)a;
 - (void) _setSelectedSegmentIndex:(q)anotify:(BOOL)b;
 - (BOOL) _shouldSelectSegmentAtIndex:(q)a;
 - (void) _setSelected:(BOOL)aforSegmentAtIndex:(i)bforceInfoDisplay:(BOOL)c;
 - (void) _resetForAppearanceChange;
 - (void) _setHighlightedSegmentHighlighted:(BOOL)a;
 - (void) highlightSegment:(i)a;
 - (void) _clearSelectedSegment;
 - (void) _tapSegmentAtPoint:({CGPoint=dd})a;
 - (void) _setDividerImage:(id)aforLeftSegmentState:(Q)brightSegmentState:(Q)cbarMetrics:(q)d;
 - (id) _createSegmentAtIndex:(i)aposition:(I)bwithInfo:(id)c;
 - (void) selectSegment:(i)a;
 - (BOOL) apportionsSegmentWidthsByContent;
 - (void) setApportionsSegmentWidthsByContent:(BOOL)a;
 - (id) initWithItems:(id)a;
 - (BOOL) _optionsShadowHidden;
 - (void) _setOptionsShadowHidden:(BOOL)a;
 - (void) _setSegmentedControlAppearance:(^{?=@dd{?=@@@@@{CGSize=dd}}{?=@@@@@{CGSize=dd}}{?=@@@@@{CGSize=dd}}{?=@@@@@{CGSize=dd}}B})a;
 - (void) _setAppearanceIsTiled:(BOOL)aleftCapWidth:(Q)brightCapWidth:(Q)c;
 - (q) segmentedControlStyle;
 - (q) segmentControlStyle;
 - (void) setSegmentControlStyle:(q)a;
 - (void) _setAutosizeText:(BOOL)a;
 - (void) _setTranslucentOptionsBackground:(BOOL)a;
 - (void) setTransparentBackground:(BOOL)a;
 - (BOOL) transparentBackground;
 - (BOOL) _usesNewAnimations;
 - (void) _setUsesNewAnimations:(BOOL)a;
 - (void) insertSegmentWithTitle:(id)aatIndex:(Q)banimated:(BOOL)c;
 - (void) insertSegmentWithImage:(id)aatIndex:(Q)banimated:(BOOL)c;
 - (void) _insertSegmentWithAttributedTitle:(id)aatIndex:(Q)banimated:(BOOL)c;
 - (void) removeSegmentAtIndex:(Q)aanimated:(BOOL)b;
 - (void) setTitle:(id)aforSegmentAtIndex:(Q)b;
 - (id) titleForSegmentAtIndex:(Q)a;
 - (void) _setAttributedTitle:(id)aforSegmentAtIndex:(Q)b;
 - (id) _attributedTitleForSegmentAtIndex:(Q)a;
 - (void) setImage:(id)aforSegmentAtIndex:(Q)b;
 - (id) imageForSegmentAtIndex:(Q)a;
 - (void) setWidth:(d)aforSegmentAtIndex:(Q)b;
 - (d) widthForSegmentAtIndex:(Q)a;
 - (void) setContentOffset:({CGSize=dd})aforSegmentAtIndex:(Q)b;
 - ({CGSize=dd}) contentOffsetForSegmentAtIndex:(Q)a;
 - (void) setEnabled:(BOOL)aforSegmentAtIndex:(Q)b;
 - (BOOL) isEnabledForSegmentAtIndex:(Q)a;
 - (Q) numberOfSegments;
 - (q) selectedSegmentIndex;
 - (void) _animateContentChangeWithAnimations:(@?)acompletion:(@?)b;
 - (id) removedSegment;
 - (void) _setOptionsBackgroundImage:(id)a;
 - (id) backgroundImageForState:(Q)abarMetrics:(q)b;
 - (void) setDividerImage:(id)aforLeftSegmentState:(Q)brightSegmentState:(Q)cbarMetrics:(q)d;
 - (id) dividerImageForLeftSegmentState:(Q)arightSegmentState:(Q)bbarMetrics:(q)c;
 - (id) titleTextAttributesForState:(Q)a;
 - (void) setContentPositionAdjustment:({UIOffset=dd})aforSegmentType:(q)bbarMetrics:(q)c;
 - ({UIOffset=dd}) contentPositionAdjustmentForSegmentType:(q)abarMetrics:(q)b;
 - (id) _badgeValueForSegmentAtIndex:(Q)a;
 - (void) _setBadgeValue:(id)aforSegmentAtIndex:(Q)b;
 - (BOOL) _hasTranslucentOptionsBackground;
 - (id) infoViewForSegment:(q)a;
 - (void) setSelectedSegment:(q)a;
 - (id) initWithFrame:({CGRect={CGPoint=dd}{CGSize=dd}})awithStyle:(q)bwithItems:(id)c;
 - (void) setAlwaysNotifiesDelegateOfSegmentClicks:(BOOL)a;
 - (void) setImagePadding:({CGSize=dd})aforSegment:(Q)b;
 - (void) addSegmentWithTitle:(id)a;
 - (void) insertSegment:(Q)awithTitle:(id)banimated:(BOOL)c;
 - (void) insertSegment:(Q)awithImage:(id)banimated:(BOOL)c;
 - (void) removeSegment:(Q)aanimated:(BOOL)b;
 - (void) setTitle:(id)aforSegment:(Q)b;
 - (id) titleForSegment:(Q)a;
 - (void) setImage:(id)aforSegment:(Q)b;
 - (id) imageForSegment:(Q)a;
 - (void) setWidth:(f)aforSegment:(Q)b;
 - (f) widthForSegment:(Q)a;
 - (void) setContentOffset:({CGSize=dd})aforSegment:(Q)b;
 - ({CGSize=dd}) contentOffsetForSegment:(Q)a;
 - (void) setEnabled:(BOOL)aforSegment:(Q)b;
 - (BOOL) isEnabledForSegment:(Q)a;
 - (q) selectedSegment;
 - (void) encodeWithCoder:(id)a;
 - (id) initWithCoder:(id)a;
 - (id) initWithFrame:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) frame;
 - (void) setFrame:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) bounds;
 - (void) setBounds:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - (void) setEnabled:(BOOL)a;


@end
