
@protocol UIViewControllerPresenting, _UIScrollNotification, NSCoding, UIViewControllerTransitioningDelegate, UIViewControllerAnimatedTransitioning;
@interface UISearchController : UIViewController <UIViewControllerPresenting, _UIScrollNotification, NSCoding, UIViewControllerTransitioningDelegate, UIViewControllerAnimatedTransitioning> {

    @"UISearchBar" _searchBar;
    i _barPresentationStyle;
    @"<UIViewControllerAnimatedTransitioning>" _animator;
    id _windowWillAnimateToken;
    @"_UISearchControllerDidScrollDelegate" _didScrollDelegate;
    {?="searchBarWasTableHeaderView"b1} _controllerFlags;
    BOOL _dimsBackgroundDuringPresentation;
    BOOL _hidesNavigationBarDuringPresentation;
    BOOL __showResultsForEmptySearch;
    @"UIView" _resultsControllerViewContainer;
    @"<UISearchResultsUpdating>" _searchResultsUpdater;
    @"<UISearchControllerDelegate>" _delegate;
    @"UIViewController" _searchResultsController;
    q __previousSearchBarPosition;
    d __resultsContentScrollViewPresentationOffset;
}
 + (BOOL) _shouldForwardViewWillTransitionToSize;

 - (BOOL) isActive;
 - (void) setActive:(BOOL)a;
 - (void) dealloc;
 - (void) setDelegate:(id)a;
 - (d) transitionDuration:(id)a;
 - (void) animateTransition:(id)a;
 - (void) _updateBackdropMaskViewsInScrollView:(id)a;
 - (void) _didScroll;
 - (void) _presentingViewControllerDidChange:(id)a;
 - (void) _presentingViewControllerWillChange:(id)a;
 - (void) viewWillTransitionToSize:({CGSize=dd})awithTransitionCoordinator:(id)b;
 - (void) loadView;
 - (void) setModalPresentationStyle:(q)a;
 - (void) viewWillAppear:(BOOL)a;
 - (void) viewDidLoad;
 - (id) _presentationControllerForPresentedController:(id)apresentingController:(id)bsourceController:(id)c;
 - (id) animationControllerForPresentedController:(id)apresentingController:(id)bsourceController:(id)c;
 - (id) animationControllerForDismissedController:(id)a;
 - (BOOL) _requiresCustomPresentationController;
 - (void) _keyboardWillShow:(id)a;
 - (void) _keyboardWillHide:(id)a;
 - (id) searchBar;
 - (BOOL) dimsBackgroundDuringPresentation;
 - (BOOL) _showResultsForEmptySearch;
 - (i) _barPresentationStyle;
 - (BOOL) hidesNavigationBarDuringPresentation;
 - (id) searchResultsController;
 - (void) _updateSearchBarMaskIfNecessary;
 - (void) _searchBarSuperviewChanged;
 - (void) _searchBar:(id)atextDidChange:(id)b;
 - (void) _searchBarCancelButtonClicked:(id)a;
 - (void) _searchBarTextDidBeginEditing:(id)a;
 - (void) _searchBarSearchButtonClicked:(id)a;
 - (BOOL) _searchBarShouldFinalizeBecomingFirstResponder;
 - (void) _updateTableHeaderBackgroundViewInTableView:(id)aamountScrolledUnder:(d)b;
 - (BOOL) _resultsControllerWillLayoutVisibleUnderContainerView;
 - (void) set_resultsContentScrollViewPresentationOffset:(d)a;
 - (void) _dismissPresentation:(BOOL)a;
 - (id) _searchPresentationController;
 - (void) set_previousSearchBarPosition:(q)a;
 - (d) _resultsContentScrollViewPresentationOffset;
 - (id) _resultsControllerViewContainer;
 - (q) _previousSearchBarPosition;
 - (id) initWithSearchResultsController:(id)a;
 - (void) _updateSearchResultsControllerWithDelta:({CGSize=dd})a;
 - (void) _connectSearchBar:(id)a;
 - (void) _adjustSearchBarSizeForOrientation:(q)a;
 - (id) _createAnimationCoordinator;
 - (void) _resizeResultsControllerWithDelta:({CGSize=dd})a;
 - (void) _performAutomaticPresentation;
 - (id) _locatePresentingViewController;
 - (void) _updateVisibilityOfSearchResultsForSearchBar:(id)a;
 - (id) searchResultsUpdater;
 - (void) _watchScrollView:(id)aforScrolling:(BOOL)b;
 - (void) _sizeSearchViewToPresentingViewController:(id)a;
 - (void) _willPresentFromViewController:(id)a;
 - (void) _didPresentFromViewController:(id)a;
 - (void) _willDismissSearchController;
 - (void) _didDismissSearchController;
 - (BOOL) _allowFormSheetStylePresentation;
 - (id) _animatorForBarPresentationStyle:(i)adismissing:(BOOL)b;
 - (void) _updateSearchResultsContentScrollViewWithDelta:({CGSize=dd})a;
 - (void) _updateSearchResultsPositionWithDelta:({CGSize=dd})a;
 - (void) _beginWatchingPresentingController;
 - (void) _endWatchingPresentingController;
 - (void) _navigationControllerWillShowViewController:(id)a;
 - (void) set_resultsControllerViewContainer:(id)a;
 - (void) setSearchResultsUpdater:(id)a;
 - (void) setDimsBackgroundDuringPresentation:(BOOL)a;
 - (void) setHidesNavigationBarDuringPresentation:(BOOL)a;
 - (void) _setShowResultsForEmptySearch:(BOOL)a;
 - (void) encodeWithCoder:(id)a;
 - (id) initWithCoder:(id)a;
 - (id) delegate;
 - (void) _commonInit;


@end
