
@protocol NSCoding;
@interface UISlider : UIControl <NSCoding> {

    float _value;
    float _minValue;
    float _maxValue;
    double _alpha;
    ^{__CFDictionary=} _contentLookup;
    @"UIImageView" _minValueImageView;
    @"UIImageView" _maxValueImageView;
    @"UIImageView" _thumbView;
    @"UIImageView" _minTrackView;
    @"UIImageView" _maxTrackView;
    @"UIView" _maxTrackClipView;
    {?="continuous"b1"animating"b1"preparingToAnimate"b1"showValue"b1"trackEnabled"b1"creatingSnapshot"b1"thumbDisabled"b1"minTrackHidden"b1} _sliderFlags;
    double _hitOffset;
    @"UIColor" _minTintColor;
    @"UIColor" _maxTintColor;
    @"UIColor" _thumbTintColor;
    @"UIView" _thumbViewNeue;
    @"CAShapeLayer" _thumbViewNeueShape;
    BOOL _useLookNeue;
    @"NSArray" _trackColors;
    BOOL _trackIsArtworkBased;
    BOOL _thumbIsArtworkBased;
    BOOL _maxColorIsValid;
    BOOL _animatingWithDynamics;
    @"UIImageView" _innerThumbView;
}

 - (id) description;
 - (void) dealloc;
 - (void) _populateArchivedSubviews:(id)a;
 - (void) setAlpha:(double)a;
 - ({CGSize=dd}) _intrinsicSizeWithinSize:({CGSize=dd})a;
 - (void) layoutSubviews;
 - (BOOL) _contentHuggingDefault_isUsuallyFixedHeight;
 - ({CGSize=dd}) sizeThatFits:({CGSize=dd})a;
 - (BOOL) gestureRecognizerShouldBegin:(id)a;
 - ({UIEdgeInsets=dddd}) alignmentRectInsets;
 - (id) scriptingInfoWithChildren;
 - (BOOL) cancelTouchTracking;
 - (BOOL) cancelMouseTracking;
 - (void) tintColorDidChange;
 - (BOOL) _alwaysHandleScrollerMouseEvent;
 - (id) _scriptingInfo;
 - (void) setHighlighted:(BOOL)a;
 - (void) setSelected:(BOOL)a;
 - (BOOL) beginTrackingWithTouch:(id)awithEvent:(id)b;
 - (void) _controlTouchBegan:(id)awithEvent:(id)b;
 - (BOOL) continueTrackingWithTouch:(id)awithEvent:(id)b;
 - (void) _controlTouchMoved:(id)awithEvent:(id)b;
 - (void) endTrackingWithTouch:(id)awithEvent:(id)b;
 - (void) _controlTouchEnded:(id)awithEvent:(id)b;
 - (void) _sendDelayedActions;
 - (void) setMinimumTrackTintColor:(id)a;
 - (void) setMaximumTrackTintColor:(id)a;
 - (void) setThumbTintColor:(id)a;
 - (id) minimumValueImage;
 - (id) maximumValueImage;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) trackRectForBounds:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) thumbRectForBounds:({CGRect={CGPoint=dd}{CGSize=dd}})atrackRect:({CGRect={CGPoint=dd}{CGSize=dd}})bvalue:(float)c;
 - (id) thumbTintColor;
 - (id) minimumTrackImageForState:(unsigned long long)a;
 - (void) setMinimumTrackImage:(id)aforState:(unsigned long long)b;
 - (id) maximumTrackImageForState:(unsigned long long)a;
 - (void) _updateMaxTrackColorForInitialization:(BOOL)a;
 - (void) setMaximumTrackImage:(id)aforStates:(unsigned long long)b;
 - (id) thumbImageForState:(unsigned long long)a;
 - (void) setThumbImage:(id)aforStates:(unsigned long long)b;
 - (void) _buildTrackArtwork;
 - (id) createThumbView;
 - (void) _rebuildControlThumb:(BOOL)atrack:(BOOL)b;
 - (id) _contentForState:(unsigned long long)a;
 - (void) _setContent:(id)aforState:(unsigned long long)b;
 - (void) setMinimumTrackImage:(id)aforStates:(unsigned long long)b;
 - (id) _thumbImageForState:(unsigned long long)a;
 - (id) _minimumTrackImageForState:(unsigned long long)a;
 - (id) _maximumTrackImageForState:(unsigned long long)a;
 - (void) _layoutSubviewsForBoundsChange:(BOOL)a;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) minimumValueImageRectForBounds:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) maximumValueImageRectForBounds:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) valueTextRectForBounds:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - (float) minimumValue;
 - (float) maximumValue;
 - (id) currentThumbImage;
 - (void) _initImages;
 - (void) _initSubviews;
 - (void) setMaximumTrackImage:(id)aforState:(unsigned long long)b;
 - (id) currentMinimumTrackImage;
 - (id) currentMaximumTrackImage;
 - (void) _updateAppearanceForEnabled:(BOOL)a;
 - (void) setValue:(float)aanimated:(BOOL)b;
 - (void) _sliderAnimationWillStart:(id)acontext:(id)b;
 - (void) _sliderAnimationDidStop:(id)afinished:(id)bcontext:(id)c;
 - (void) _setValue:(float)aandSendAction:(BOOL)b;
 - (void) _setValue:(float)aminValue:(float)bmaxValue:(float)candSendAction:(BOOL)d;
 - (BOOL) isContinuous;
 - ({UIEdgeInsets=dddd}) _thumbHitEdgeInsets;
 - (id) createThumbViewNeue;
 - (double) _cornerRadiusForRect:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - (void) setThumbImage:(id)aforState:(unsigned long long)b;
 - (void) setMinimumValueImage:(id)a;
 - (void) setMaximumValueImage:(id)a;
 - (void) setContinuous:(BOOL)a;
 - (void) setMinimumValue:(float)a;
 - (void) setMaximumValue:(float)a;
 - (id) minimumTrackTintColor;
 - (id) maximumTrackTintColor;
 - (id) _minTrackView;
 - (id) _maxTrackView;
 - (void) _setThumbImage:(id)aforStates:(unsigned long long)b;
 - (void) _setMinimumTrackImage:(id)aforStates:(unsigned long long)b;
 - (void) _setMaximumTrackImage:(id)aforStates:(unsigned long long)b;
 - (BOOL) isAnimatingValueChange;
 - (void) setShowValue:(BOOL)a;
 - (void) _setTrackEnabled:(BOOL)a;
 - (BOOL) _trackEnabled;
 - (void) _setThumbEnabled:(BOOL)a;
 - (void) _setMinimumTrackVisible:(BOOL)awithDuration:(double)b;
 - (BOOL) _isThumbEnabled;
 - (void) _setUseLookNeue:(BOOL)a;
 - (id) _minValueView;
 - (id) _maxValueView;
 - (void) _setThumbTintColor:(id)aforStates:(unsigned long long)b;
 - (BOOL) isAccessibilityElementByDefault;
 - (BOOL) isElementAccessibilityExposedToInterfaceBuilder;
 - (id) init;
 - (void) encodeWithCoder:(id)a;
 - (id) initWithCoder:(id)a;
 - (void) setValue:(float)a;
 - (float) value;
 - (id) initWithFrame:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - (void) setFrame:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - (void) setBounds:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - (void) setEnabled:(BOOL)a;


@end
