
@protocol NSCoding;
@interface UISlider : UIControl <NSCoding> {

    float _value;
    float _minValue;
    float _maxValue;
    double _alpha;
    ^{__CFDictionary=} _contentLookup;
    UIImageView* _minValueImageView;
    UIImageView* _maxValueImageView;
    UIImageView* _thumbView;
    UIImageView* _minTrackView;
    UIImageView* _maxTrackView;
    UIView* _maxTrackClipView;
    {?="continuous"b1"animating"b1"preparingToAnimate"b1"showValue"b1"trackEnabled"b1"creatingSnapshot"b1"thumbDisabled"b1"minTrackHidden"b1} _sliderFlags;
    double _hitOffset;
    UIColor* _minTintColor;
    UIColor* _maxTintColor;
    UIColor* _thumbTintColor;
    UIView* _thumbViewNeue;
    CAShapeLayer* _thumbViewNeueShape;
    BOOL _useLookNeue;
    NSArray* _trackColors;
    BOOL _trackIsArtworkBased;
    BOOL _thumbIsArtworkBased;
    BOOL _maxColorIsValid;
    BOOL _animatingWithDynamics;
    UIImageView* _innerThumbView;
}

 - (id) description;
 - (void) dealloc;
 - (void) _populateArchivedSubviews:(id)a ;
 - (void) setAlpha:(double)a ;
 - ({CGSize=dd}) _intrinsicSizeWithinSize:({CGSize=dd})a ;
 - (void) layoutSubviews;
 - (BOOL) _contentHuggingDefault_isUsuallyFixedHeight;
 - ({CGSize=dd}) sizeThatFits:({CGSize=dd})a ;
 - (BOOL) gestureRecognizerShouldBegin:(id)a ;
 - ({UIEdgeInsets=dddd}) alignmentRectInsets;
 - (id) scriptingInfoWithChildren;
 - (BOOL) cancelTouchTracking;
 - (BOOL) cancelMouseTracking;
 - (void) tintColorDidChange;
 - (BOOL) _alwaysHandleScrollerMouseEvent;
 - (id) _scriptingInfo;
 - (void) setHighlighted:(BOOL)a ;
 - (void) setSelected:(BOOL)a ;
 - (BOOL) beginTrackingWithTouch:(id)a withEvent:(id)b ;
 - (void) _controlTouchBegan:(id)a withEvent:(id)b ;
 - (BOOL) continueTrackingWithTouch:(id)a withEvent:(id)b ;
 - (void) _controlTouchMoved:(id)a withEvent:(id)b ;
 - (void) endTrackingWithTouch:(id)a withEvent:(id)b ;
 - (void) _controlTouchEnded:(id)a withEvent:(id)b ;
 - (void) _sendDelayedActions;
 - (void) setMinimumTrackTintColor:(id)a ;
 - (void) setMaximumTrackTintColor:(id)a ;
 - (void) setThumbTintColor:(id)a ;
 - (id) minimumValueImage;
 - (id) maximumValueImage;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) trackRectForBounds:({CGRect={CGPoint=dd}{CGSize=dd}})a ;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) thumbRectForBounds:({CGRect={CGPoint=dd}{CGSize=dd}})a trackRect:({CGRect={CGPoint=dd}{CGSize=dd}})b value:(float)c ;
 - (id) thumbTintColor;
 - (id) minimumTrackImageForState:(unsigned long long)a ;
 - (void) setMinimumTrackImage:(id)a forState:(unsigned long long)b ;
 - (id) maximumTrackImageForState:(unsigned long long)a ;
 - (void) _updateMaxTrackColorForInitialization:(BOOL)a ;
 - (void) setMaximumTrackImage:(id)a forStates:(unsigned long long)b ;
 - (id) thumbImageForState:(unsigned long long)a ;
 - (void) setThumbImage:(id)a forStates:(unsigned long long)b ;
 - (void) _buildTrackArtwork;
 - (id) createThumbView;
 - (void) _rebuildControlThumb:(BOOL)a track:(BOOL)b ;
 - (id) _contentForState:(unsigned long long)a ;
 - (void) _setContent:(id)a forState:(unsigned long long)b ;
 - (void) setMinimumTrackImage:(id)a forStates:(unsigned long long)b ;
 - (id) _thumbImageForState:(unsigned long long)a ;
 - (id) _minimumTrackImageForState:(unsigned long long)a ;
 - (id) _maximumTrackImageForState:(unsigned long long)a ;
 - (void) _layoutSubviewsForBoundsChange:(BOOL)a ;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) minimumValueImageRectForBounds:({CGRect={CGPoint=dd}{CGSize=dd}})a ;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) maximumValueImageRectForBounds:({CGRect={CGPoint=dd}{CGSize=dd}})a ;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) valueTextRectForBounds:({CGRect={CGPoint=dd}{CGSize=dd}})a ;
 - (float) minimumValue;
 - (float) maximumValue;
 - (id) currentThumbImage;
 - (void) _initImages;
 - (void) _initSubviews;
 - (void) setMaximumTrackImage:(id)a forState:(unsigned long long)b ;
 - (id) currentMinimumTrackImage;
 - (id) currentMaximumTrackImage;
 - (void) _updateAppearanceForEnabled:(BOOL)a ;
 - (void) setValue:(float)a animated:(BOOL)b ;
 - (void) _sliderAnimationWillStart:(id)a context:(id)b ;
 - (void) _sliderAnimationDidStop:(id)a finished:(id)b context:(id)c ;
 - (void) _setValue:(float)a andSendAction:(BOOL)b ;
 - (void) _setValue:(float)a minValue:(float)b maxValue:(float)c andSendAction:(BOOL)d ;
 - (BOOL) isContinuous;
 - ({UIEdgeInsets=dddd}) _thumbHitEdgeInsets;
 - (id) createThumbViewNeue;
 - (double) _cornerRadiusForRect:({CGRect={CGPoint=dd}{CGSize=dd}})a ;
 - (void) setThumbImage:(id)a forState:(unsigned long long)b ;
 - (void) setMinimumValueImage:(id)a ;
 - (void) setMaximumValueImage:(id)a ;
 - (void) setContinuous:(BOOL)a ;
 - (void) setMinimumValue:(float)a ;
 - (void) setMaximumValue:(float)a ;
 - (id) minimumTrackTintColor;
 - (id) maximumTrackTintColor;
 - (id) _minTrackView;
 - (id) _maxTrackView;
 - (void) _setThumbImage:(id)a forStates:(unsigned long long)b ;
 - (void) _setMinimumTrackImage:(id)a forStates:(unsigned long long)b ;
 - (void) _setMaximumTrackImage:(id)a forStates:(unsigned long long)b ;
 - (BOOL) isAnimatingValueChange;
 - (void) setShowValue:(BOOL)a ;
 - (void) _setTrackEnabled:(BOOL)a ;
 - (BOOL) _trackEnabled;
 - (void) _setThumbEnabled:(BOOL)a ;
 - (void) _setMinimumTrackVisible:(BOOL)a withDuration:(double)b ;
 - (BOOL) _isThumbEnabled;
 - (void) _setUseLookNeue:(BOOL)a ;
 - (id) _minValueView;
 - (id) _maxValueView;
 - (void) _setThumbTintColor:(id)a forStates:(unsigned long long)b ;
 - (BOOL) isAccessibilityElementByDefault;
 - (BOOL) isElementAccessibilityExposedToInterfaceBuilder;
 - (id) init;
 - (void) encodeWithCoder:(id)a ;
 - (id) initWithCoder:(id)a ;
 - (void) setValue:(float)a ;
 - (float) value;
 - (id) initWithFrame:({CGRect={CGPoint=dd}{CGSize=dd}})a ;
 - (void) setFrame:({CGRect={CGPoint=dd}{CGSize=dd}})a ;
 - (void) setBounds:({CGRect={CGPoint=dd}{CGSize=dd}})a ;
 - (void) setEnabled:(BOOL)a ;


@end
