
@protocol UIGestureRecognizerDelegate;
@interface UISplitViewController : UIViewController <UIGestureRecognizerDelegate> {

    id _delegate;
    @"UIBarButtonItem" _barButtonItem;
    @"UIBarButtonItem" _displayModeButtonItem;
    @"NSString" _buttonTitle;
    @"UIPopoverController" _hiddenPopoverController;
    @"UIView" _rotationSnapshotView;
    @"UIResponder" _postTransitionResponder;
    @"UISnapshotView" _collapsingMasterSnapshotView;
    @"UISnapshotView" _collapsingDetailSnapshotView;
    d _masterColumnWidth;
    f _gutterWidth;
    f _cornerRadius;
    q _rotatingFromOrientation;
    q _lastPresentedOrientation;
    {CGRect="origin"{CGPoint="x"d"y"d}"size"{CGSize="width"d"height"d}} _rotatingFromMasterViewFrame;
    {CGRect="origin"{CGPoint="x"d"y"d}"size"{CGSize="width"d"height"d}} _rotatingToMasterViewFrame;
    @"NSArray" _cornerImageViews;
    @"UIView" _underBarSeparatorView;
    Q _slideTransitionCount;
    @"UIView" _masterBackgroundView;
    BOOL _presentsInFadingPopover;
    BOOL _presentsWithGesture;
    @"UIGestureRecognizer" _popoverPresentationGestureRecognizer;
    q _preferredDisplayMode;
    q _effectiveTargetDisplayMode;
    q _pendingDisplayModeChangeCount;
    BOOL _useChangingBoundsLayout;
    {?="validDelegateHiddenMasterOrientations"b5"delegateHiddenMasterOrientations"b5"delegateImplementsShouldHide"b1"hidden"b3"delegateHandlesTogglingMaster"b1"delegateProvidesBackgroundView"b1"delegateWantsUnSlideCallback"b1"masterOnSlide"b1"delegateWantsWillShowCallback"b1"delegateWantsWillHideCallback"b1"delegateWantsWillPresentCallback"b1"delegateWantsNavigationRequests"b1"resizesDetailOnSlide"b1"delegateSupportedInterfaceOrientations"b1"delegatePreferredInterfaceOrientationForPresentation"b1"disableDetailFrameChanges"b1"delegateWantsShowViewController"b1"delegateWantsPrivateShowViewController"b1"delegateWantsShowDetailViewController"b1"delegateWantsPrivateShowDetailViewController"b1"delegateWantsCollapseSecondaryViewController"b1"delegateWantsPrivateCollapseSecondaryViewController"b1"delegateWantsSeparateSecondaryViewController"b1"delegateWantsPrivateSeparateSecondaryViewController"b1"delegateWantsPrimaryViewControllerForCollapse"b1"delegateWantsPrivatePrimaryViewControllerForCollapse"b1"delegateWantsPrimaryViewControllerForExpanding"b1"delegateWantsPrivatePrimaryViewControllerForExpanding"b1"collapsedState"b2"primaryHidingState"b2"primaryHidingStateForCurrentOrientation"b2"delegateWantsWillChangeToDisplayMode"b1"delegateWantsTargetDisplayModeForAction"b1"pendingPresentMasterViewController"b1"pendingUpdateTargetDisplayMode"b1"collapsingClockwise"b1"firstResponderChangedFromPostTransitionResponder"b1} _splitViewControllerFlags;
    BOOL _resizeForKeyboard;
    @"NSString" _displayModeButtonItemTitle;
    d _preferredPrimaryColumnWidthFraction;
    d _minimumPrimaryColumnWidth;
    d _maximumPrimaryColumnWidth;
    @"UIViewController" __preservedDetailController;
    @? __didChangeBoundsBlock;
    @? __clearPreventRotationHook;
}
 + (BOOL) doesOverrideSupportedInterfaceOrientations;
 + (BOOL) _shouldSendLegacyMethodsFromViewWillTransitionToSize;
 + (BOOL) _shouldForwardViewWillTransitionToSize;
 + (BOOL) doesOverridePreferredInterfaceOrientationForPresentation;
 + (BOOL) _optsOutOfPopoverControllerHierarchyCheck;
 + (d) _defaultGutterWidthInView:(id)a;
 + (BOOL) _forcePresentsInSlidingPopover;
 + (BOOL) _forcePresentsWithGesture;

 - (void) dealloc;
 - (void) setDelegate:(id)a;
 - (void) encodeRestorableStateWithCoder:(id)a;
 - (void) decodeRestorableStateWithCoder:(id)a;
 - (BOOL) _disableAutomaticKeyboardBehavior;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) _frameForChildContentContainer:(id)a;
 - (void) _updateLayoutForStatusBarAndInterfaceOrientation;
 - ({CGSize=dd}) sizeForChildContentContainer:(id)awithParentContainerSize:({CGSize=dd})b;
 - (void) willTransitionToTraitCollection:(id)awithTransitionCoordinator:(id)b;
 - (id) initWithNibName:(id)abundle:(id)b;
 - (void) loadView;
 - (BOOL) shouldAutorotateToInterfaceOrientation:(q)a;
 - (q) preferredInterfaceOrientationForPresentation;
 - (void) viewWillAppear:(BOOL)a;
 - (d) _contentMarginForChildViewController:(id)a;
 - ({UIEdgeInsets=dddd}) _edgeInsetsForChildViewController:(id)ainsetsAreAbsolute:(^B)b;
 - (void) _updateChildContentMargins;
 - (BOOL) _shouldPersistViewWhenCoding;
 - (void) unloadViewForced:(BOOL)a;
 - (void) viewDidAppear:(BOOL)a;
 - (void) viewWillDisappear:(BOOL)a;
 - (void) viewDidDisappear:(BOOL)a;
 - (void) purgeMemoryForReason:(i)a;
 - (void) willRotateToInterfaceOrientation:(q)aduration:(d)b;
 - (void) willAnimateRotationToInterfaceOrientation:(q)aduration:(d)b;
 - (void) didRotateFromInterfaceOrientation:(q)a;
 - (BOOL) _shouldSynthesizeSupportedOrientations;
 - (void) _getRotationContentSettings:(^{?=BBBBBdi})a;
 - (void) _layoutContainerViewWillMoveToWindow:(id)a;
 - (void) _layoutContainerViewDidMoveToWindow:(id)a;
 - (void) showViewController:(id)asender:(id)b;
 - (void) showDetailViewController:(id)asender:(id)b;
 - (id) _allContainedViewControllers;
 - (id) _additionalViewControllersToCheckForUserActivity;
 - (id) viewControllers;
 - (void) setViewControllers:(id)a;
 - (void) __viewWillLayoutSubviews;
 - (id) detailViewController;
 - (id) _primaryContentResponder;
 - (void) _didChangeToFirstResponder:(id)a;
 - (BOOL) isCollapsed;
 - (id) masterViewController;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) _masterViewFrame;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) _detailViewFrame;
 - (void) _setPresentsInFadingPopover:(BOOL)a;
 - (void) _setMasterOverrideTraitCollectionActive:(BOOL)a;
 - (void) _removeCollapsingSnapshotViews;
 - (q) displayMode;
 - (void) loadSubviews;
 - (void) _loadNewSubviews:(id)a;
 - (void) _updateTargetDisplayMode;
 - (q) _primaryHidingStateForCurrentOrientation;
 - (q) _primaryHidingState;
 - (BOOL) hidesMasterViewInLandscape;
 - (BOOL) hidesMasterViewInPortrait;
 - (q) _effectivePrimaryHidingState;
 - (BOOL) _presentsInFadingPopover;
 - (BOOL) _delegateUsesLegacySlideSPI;
 - (BOOL) _isMasterPopoverVisible;
 - (BOOL) _isHidesMasterInPortraitValid;
 - (BOOL) _isHidesMasterInLandscapeValid;
 - (BOOL) _effectivePresentsWithGesture;
 - (BOOL) _hasMasterViewController;
 - (void) _setupHiddenPopoverControllerWithViewController:(id)a;
 - (q) _effectiveTargetDisplayMode;
 - (void) _calculateDelegateHiddenMasterOrientations;
 - (void) _addOrRemovePopoverPresentationGestureRecognizer;
 - (d) _primaryColumnWidthForSize:({CGSize=dd})a;
 - (BOOL) _isMasterViewShown;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) _masterViewFrame:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) _detailViewFrameWithPopoverControllerFrame:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - (f) gutterWidth;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) _detailViewFrame:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - (void) popoverWillAppear:(id)a;
 - (BOOL) _resizesDetailOnSlide;
 - (void) toggleMasterVisible:(id)a;
 - (d) primaryColumnWidth;
 - (d) preferredPrimaryColumnWidthFraction;
 - (d) minimumPrimaryColumnWidth;
 - (d) maximumPrimaryColumnWidth;
 - (BOOL) _isBasicallyHorizontallyCompact;
 - (id) _preservedDetailController;
 - (BOOL) _canDisplayHostedMaster;
 - (BOOL) _canSlideMaster;
 - (void) _viewControllerHiding:(id)a;
 - (void) _updateDisplayModeButtonItem;
 - (void) _prepareForCompactLayout;
 - (void) _setCollapsedState:(q)a;
 - (id) _childContainingSender:(id)a;
 - (void) _setPreservedDetailController:(id)a;
 - (id) _secondaryViewControllerForCollapsing;
 - (id) _primaryViewControllerForCollapsing;
 - (void) _collapseSecondaryViewController:(id)aontoPrimaryViewController:(id)b;
 - (id) _primaryViewControllerForExpanding;
 - (id) _separateSecondaryViewControllerFromPrimaryViewController:(id)a;
 - (@?) _didChangeBoundsBlock;
 - (void) _setDidChangeBoundsBlock:(@?)a;
 - (void) _willTransitionToWindowSize:({CGSize=dd})aoldWidthClass:(q)bnewWidthClass:(q)c;
 - (void) _invokeDidChangeBoundsBlock;
 - (void) _transitionFromTraitCollection:(id)awithTransitionCoordinator:(id)b;
 - (void) _didTransitionTraitCollection;
 - (BOOL) _isLandscape;
 - (void) _showMasterViewAnimated:(BOOL)a;
 - (BOOL) presentsWithGesture;
 - (q) preferredDisplayMode;
 - (void) _changeToDisplayMode:(q)aforCurrentOrientationOnly:(BOOL)b;
 - (id) _defaultDisplayModes;
 - (void) _displayModeWillChangeTo:(q)a;
 - (void) _setPrimaryHidingStateForCurrentOrientation:(q)a;
 - (void) _setPrimaryHidingState:(q)a;
 - (void) _dismissMasterViewController:(BOOL)a;
 - (void) _presentMasterViewController:(BOOL)a;
 - (void) _displayModeDidChange;
 - (void) _cacheEffectiveTargetDisplayMode;
 - (q) _defaultTargetDisplayMode;
 - (id) _displayModeButtonItemTitle;
 - (void) _triggerDisplayModeAction:(id)a;
 - (@?) _clearPreventRotationHook;
 - (void) _setClearPreventRotationHook:(@?)a;
 - (BOOL) _shouldPreventAutorotation;
 - (void) _slideIn:(BOOL)aviewController:(id)banimated:(BOOL)ctotalDuration:(d)dcompletion:(@?)e;
 - (BOOL) _shouldModifyDisplayModeWhenRotating;
 - (void) _invalidateHidesMasterViewInOrientation:(q)a;
 - (BOOL) revealsMasterViewDuringRotationFromInterfaceOrientation:(q)atoInterfaceOrientation:(q)b;
 - (BOOL) hidesMasterViewDuringRotationFromInterfaceOrientation:(q)atoInterfaceOrientation:(q)b;
 - (BOOL) _isRotating;
 - (void) snapshotMasterView;
 - (void) snapshotAllViews;
 - (void) snapshotForRotationFromInterfaceOrientation:(q)atoInterfaceOrientation:(q)b;
 - (void) _setupRoundedCorners;
 - (void) _setupUnderBarSeparatorView;
 - (void) _removeRoundedCorners;
 - (void) _updateMasterViewControllerFrame;
 - (id) _primaryDimmingView;
 - (f) leftColumnWidth;
 - (BOOL) _isCollapsed;
 - (void) setHidesMasterViewInPortrait:(BOOL)a;
 - (f) masterColumnWidth;
 - (void) setMasterColumnWidth:(f)a;
 - (void) setMinimumPrimaryColumnWidth:(d)a;
 - (void) setMaximumPrimaryColumnWidth:(d)a;
 - (void) setPreferredPrimaryColumnWidthFraction:(d)a;
 - (void) setPreferredLeftColumnWidth:(f)a;
 - (f) preferredLeftColumnWidth;
 - (void) setGutterWidth:(f)a;
 - (void) setPresentsWithGesture:(BOOL)a;
 - (void) setPreferredDisplayMode:(q)a;
 - (id) displayModeButtonItem;
 - (void) _setDisplayModeButtonItemTitle:(id)a;
 - ({CGSize=dd}) _contentSizeForChildViewController:(id)ainPopoverController:(id)b;
 - (void) _presentGestureAttemptedWithPresentedPopoverController:(id)a;
 - (Q) supportedInterfaceOrientations:(id)a;
 - (void) _setResizesDetailOnSlide:(BOOL)a;
 - (void) _popoverController:(id)awillAnimateToFrame:({CGRect={CGPoint=dd}{CGSize=dd}})b;
 - (void) _popoverController:(id)awillChangeToVisible:(BOOL)b;
 - (void) _popoverController:(id)adidChangeFromVisible:(BOOL)b;
 - (BOOL) resizeForKeyboard;
 - (void) setResizeForKeyboard:(BOOL)a;
 - (void) encodeWithCoder:(id)a;
 - (id) initWithCoder:(id)a;
 - (id) delegate;
 - (void) _commonInit;


@end
