
@protocol UIStatusBarServerClient, UIStatusBarStateObserver;
@interface UIStatusBar : _UIScrollsToTopInitiatorView <UIStatusBarServerClient, UIStatusBarStateObserver> {

    UIStatusBarWindow* _statusBarWindow;
    UIStatusBarServer* _statusBarServer;
    <UIStatusBarStateProvider>* _inProcessProvider;
    BOOL _showsForeground;
    UIStatusBarBackgroundView* _backgroundView;
    UIStatusBarForegroundView* _foregroundView;
    UILabel* _doubleHeightLabel;
    UIView* _doubleHeightLabelContainer;
    NSString* _currentDoubleHeightText;
    {?="itemIsEnabled"[26B]"timeString"[64c]"gsmSignalStrengthRaw"i"gsmSignalStrengthBars"i"serviceString"[100c]"serviceCrossfadeString"[100c]"serviceImages"[2[100c]]"operatorDirectory"[1024c]"serviceContentType"I"wifiSignalStrengthRaw"i"wifiSignalStrengthBars"i"dataNetworkType"I"batteryCapacity"i"batteryState"I"batteryDetailString"[150c]"bluetoothBatteryCapacity"i"thermalColor"i"thermalSunlightMode"b1"slowActivity"b1"syncActivity"b1"activityDisplayId"[256c]"bluetoothConnected"b1"displayRawGSMSignal"b1"displayRawWifiSignal"b1"locationIconType"b1"quietModeInactive"b1"tetheringConnectionCount"I} _currentRawData;
    NSMutableArray* _interruptedAnimationCompositeViews;
    UIStatusBarBackgroundView* _newStyleBackgroundView;
    UIStatusBarForegroundView* _newStyleForegroundView;
    UIStatusBar* _slidingStatusBar;
    long long _requestedStyle;
    int _styleOverrides;
    UIStatusBarStyleAttributes* _styleAttributes;
    long long _orientation;
    BOOL _hidden;
    BOOL _suppressesHiddenSideEffects;
    BOOL _foreground;
    BOOL _registered;
    BOOL _waitingOnCallbackAfterChangingStyleOverridesLocally;
    BOOL _suppressGlow;
    double _translucentBackgroundAlpha;
    BOOL _showOnlyCenterItems;
    ^{?=[26B]b1b1b1b1b2b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1{?=[26B][64c]ii[100c][100c][2[100c]][1024c]IiiIiI[150c]iib1b1b1[256c]b1b1b1b1b1I}} _localDataOverrides;
    UIColor* _tintColor;
    UIColor* _lastUsedBackgroundColor;
    UIStatusBarStyleAnimationParameters* _nextTintTransition;
    NSNumber* _overrideHeight;
    NSMutableSet* _disableRasterizationReasons;
    BOOL _persistentAnimationsEnabled;
    BOOL _simulatesLegacyAppearance;
    BOOL _serverUpdatesDisabled;
    BOOL _homeItemsDisabled;
    <UIStatusBarStyleDelegate>* _styleDelegate;
    UIColor* _foregroundColor;
    long long _legibilityStyle;
}
 + (id) statusBarTintColorForNavBarTintColor:(id)a;
 + (long long) defaultStyleForRequestedStyle:(long long)astyleOverrides:(int)b;
 + ({CGRect={CGPoint=dd}{CGSize=dd}}) _frameInSceneReferenceSpaceForStyle:(long long)aorientation:(long long)binSceneWithReferenceSize:({CGSize=dd})c;
 + (double) heightForStyle:(long long)aorientation:(long long)b;
 + (id) defaultBlueTintColor;
 + (id) navBarTintColorFromStatusBarTintColor:(id)a;
 + (void) getData:(^{?=[26B][64c]ii[100c][100c][2[100c]][1024c]IiiIiI[150c]iib1b1b1[256c]b1b1b1b1b1I})aforRequestedData:(r^{?=[26B][64c]ii[100c][100c][2[100c]][1024c]IiiIiI[150c]iib1b1b1[256c]b1b1b1b1b1I})bwithOverrides:(r^{?=[26B]b1b1b1b1b2b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1{?=[26B][64c]ii[100c][100c][2[100c]][1024c]IiiIiI[150c]iib1b1b1[256c]b1b1b1b1b1I}})c;
 + (id) _styleAttributesForStatusBarStyle:(long long)alegacy:(BOOL)b;
 + ({CGRect={CGPoint=dd}{CGSize=dd}}) _frameInSceneReferenceSpaceForStyleAttributes:(id)aorientation:(long long)binSceneWithReferenceSize:({CGSize=dd})c;
 + ({CGRect={CGPoint=dd}{CGSize=dd}}) _frameInSceneReferenceSpaceForStyleAttributes:(id)aorientation:(long long)b;
 + (id) _styleAttributesForRequest:(id)a;
 + (int) cornerStyleForRequestedStyle:(long long)aeffectiveStyle:(long long)balignment:(int)c;
 + (id) _newStyleAttributesForRequest:(id)a;
 + (long long) defaultStatusBarStyleWithTint:(BOOL)a;
 + (long long) lowBatteryLevel;
 + (void) setTintOverrideEnabled:(BOOL)awithColor:(id)b;
 + (void) setSuppressUpdateAnimations:(BOOL)a;
 + (void) enumerateStatusBarStyleOverridesWithBlock:(@?)a;

 - (void) dealloc;
 - (BOOL) pointInside:({CGPoint=dd})a withEvent:(id)b ;
 - (void) layoutSubviews;
 - (id) _backgroundView;
 - (void) touchesEnded:(id)a withEvent:(id)b ;
 - (double) defaultHeight;
 - (double) defaultDoubleHeight;
 - (void) forceUpdateStyleOverrides:(BOOL)a ;
 - (void) forceUpdateDoubleHeightStatus;
 - (void) setStyleDelegate:(id)a ;
 - (void) requestStyle:(long long)a animated:(BOOL)b ;
 - (void) _setVisualAltitude:(double)a ;
 - (void) _setVisualAltitudeBias:({CGSize=dd})a ;
 - (void) requestStyle:(long long)a animationParameters:(id)b ;
 - (void) setHidden:(BOOL)a animationParameters:(id)b ;
 - (void) noteStyleOverridesChangedLocally;
 - (void) setTintColor:(id)a withDuration:(double)b ;
 - (BOOL) isTranslucent;
 - (long long) currentStyle;
 - (double) heightForOrientation:(long long)a ;
 - (double) currentHeight;
 - (id) statusBarWindow;
 - (void) setTintColor:(id)a ;
 - (void) didMoveToSuperview;
 - (void) _didChangeFromIdiom:(long long)a onScreen:(id)b traverseHierarchy:(BOOL)c ;
 - (double) _standardHeight;
 - (BOOL) _isTransparent;
 - (BOOL) isDoubleHeight;
 - (long long) legibilityStyle;
 - (void) setSuppressesGlow:(BOOL)a ;
 - (void) setPersistentAnimationsEnabled:(BOOL)a ;
 - (BOOL) persistentAnimationsEnabled;
 - (int) styleOverrides;
 - (id) _doubleHeightStatusStringForStyle:(long long)a ;
 - (void) statusBarServer:(id)a didReceiveStatusBarData:(r^{?=[26B][64c]ii[100c][100c][2[100c]][1024c]IiiIiI[150c]iib1b1b1[256c]b1b1b1b1b1I})b withActions:(int)c ;
 - (void) statusBarServer:(id)a didReceiveStyleOverrides:(int)b ;
 - (void) statusBarServer:(id)a didReceiveGlowAnimationState:(BOOL)b forStyle:(long long)c ;
 - (void) statusBarServer:(id)a didReceiveDoubleHeightStatusString:(id)b forStyle:(long long)c ;
 - (void) setStatusBarWindow:(id)a ;
 - (void) _statusBarWillAnimateRotation;
 - (void) _statusBarDidAnimateRotation;
 - ({CGAffineTransform=dddddd}) _hiddenTransformForHideAnimationParameters:(id)a ;
 - (void) _didEnterBackground:(id)a ;
 - (void) _willEnterForeground:(id)a ;
 - (void) _itemViewPerformButtonAction:(id)a ;
 - (void) _itemViewShouldBeginDisablingRasterization:(id)a ;
 - (void) _itemViewShouldEndDisablingRasterization:(id)a ;
 - (void) _styleOverridesDidChange:(id)a ;
 - (void) _evaluateServerRegistration;
 - (void) _updateShouldRasterize;
 - (id) initWithFrame:({CGRect={CGPoint=dd}{CGSize=dd}})a showForegroundView:(BOOL)b inProcessStateProvider:(id)c ;
 - (id) initWithFrame:({CGRect={CGPoint=dd}{CGSize=dd}})a showForegroundView:(BOOL)b ;
 - (void) forceUpdateToData:(r^{?=[26B][64c]ii[100c][100c][2[100c]][1024c]IiiIiI[150c]iib1b1b1[256c]b1b1b1b1b1I})a animated:(BOOL)b ;
 - (id) _currentComposedData;
 - (void) _setDoubleHeightStatusString:(id)a ;
 - (void) _adjustDoubleHeightTextVisibility;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) frameForOrientation:(long long)a ;
 - (id) _currentStyleAttributes;
 - (id) styleRequest;
 - (id) _styleAttributesForRequest:(id)a ;
 - (long long) styleForRequestedStyle:(long long)a ;
 - (id) currentStyleRequestForStyle:(long long)a ;
 - (void) _requestStyleAttributes:(id)a animationParameters:(id)b ;
 - (id) activeTintColor;
 - (id) _prepareToSetStyle:(id)a animation:(int)b ;
 - (void) _endDisablingRasterizationForReason:(id)a ;
 - (void) _beginDisablingRasterizationForReason:(id)a ;
 - (void) _setStyle:(id)a animation:(int)b ;
 - (void) _finishedSettingStyleWithOldHeight:(double)a newHeight:(double)b animation:(int)c ;
 - (BOOL) _shouldUseInProcessProviderDoubleHeightStatusString;
 - (void) _updateBackgroundFrame;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) _backgroundFrameForAttributes:(id)a ;
 - (id) _prepareInterruptedAnimationCompositeViewIncludingForeground:(BOOL)a ;
 - (void) _updatePersistentAnimationsEnabledForForegroundView:(id)a ;
 - (id) _currentComposedDataForStyle:(id)a ;
 - ({CGAffineTransform=dddddd}) _slideTransform;
 - (void) _setFrameForStyle:(id)a ;
 - (void) _swapToNewBackgroundView;
 - (void) _crossfadeToNewForegroundViewWithAlpha:(double)a ;
 - (void) _setStyle:(id)a ;
 - (void) _swapToNewForegroundView;
 - (void) _crossfadeToNewBackgroundView;
 - (double) _hiddenAlphaForHideAnimationParameters:(id)a ;
 - (void) setHidden:(BOOL)a animated:(BOOL)b ;
 - (BOOL) _touchShouldProduceReturnEvent;
 - (id) styleDelegate;
 - (BOOL) serverUpdatesDisabled;
 - (void) forceUpdateData:(BOOL)a ;
 - (void) forceUpdateGlowAnimation;
 - (void) forgetEitherSideHistory;
 - (void) setForegroundColor:(id)a animationParameters:(id)b ;
 - (void) setLegibilityStyle:(long long)a animationParameters:(id)b ;
 - (BOOL) simulatesLegacyAppearance;
 - (void) setStyleRequest:(id)a animationParameters:(id)b ;
 - (BOOL) homeItemsDisabled;
 - (void) statusBarStateProvider:(id)a didPostStatusBarData:(r^{?=[26B][64c]ii[100c][100c][2[100c]][1024c]IiiIiI[150c]iib1b1b1[256c]b1b1b1b1b1I})b withActions:(int)c ;
 - (void) statusBarStateProvider:(id)a didChangeDoubleHeightStatusStringForStyle:(long long)b ;
 - (void) setBackgroundAlpha:(double)a ;
 - (void) setShowsOnlyCenterItems:(BOOL)a ;
 - (void) setLocalDataOverrides:(^{?=[26B]b1b1b1b1b2b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1{?=[26B][64c]ii[100c][100c][2[100c]][1024c]IiiIiI[150c]iib1b1b1[256c]b1b1b1b1b1I}})a ;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) currentFrame;
 - (long long) _requestedStyle;
 - (void) requestStyle:(long long)a ;
 - (void) requestStyle:(long long)a animation:(int)b startTime:(double)c duration:(double)d curve:(long long)e ;
 - (id) currentDoubleHeightLabelText;
 - (void) setSuppressesHiddenSideEffects:(BOOL)a ;
 - (BOOL) _shouldSeekHigherPriorityTouchTarget;
 - (void) crossfadeTime:(BOOL)a duration:(double)b ;
 - (void) setSimulatesLegacyAppearance:(BOOL)a ;
 - (void) setForegroundColor:(id)a ;
 - (void) setLegibilityStyle:(long long)a ;
 - (void) setStyleRequest:(id)a ;
 - (void) setServerUpdatesDisabled:(BOOL)a ;
 - (void) _setOverrideHeight:(double)a ;
 - (void) _clearOverrideHeight;
 - (void) setHomeItemsDisabled:(BOOL)a ;
 - (id) initWithFrame:({CGRect={CGPoint=dd}{CGSize=dd}})a ;
 - (void) setOrientation:(long long)a ;
 - (id) foregroundColor;
 - (BOOL) isHidden;
 - (void) setHidden:(BOOL)a ;


@end
