
@protocol UITableViewSubviewReusing;
@interface UITableViewHeaderFooterView : UIView <UITableViewSubviewReusing> {

    q _tableViewStyle;
    @"UIImage" _backgroundImage;
    {CGRect="origin"{CGPoint="x"d"y"d}"size"{CGSize="width"d"height"d}} _frame;
    q _textAlignment;
    @"UITableView" _tableView;
    d _maxTitleWidth;
    @"NSString" _reuseIdentifier;
    @"UIView" _backgroundView;
    @"_UITableViewHeaderFooterViewLabel" _label;
    @"_UITableViewHeaderFooterViewLabel" _detailLabel;
    @"UIView" _contentView;
    @"UIColor" _tintColor;
    {UIEdgeInsets="top"d"left"d"bottom"d"right"d} _separatorInset;
    {?="isHeader"b1"labelBackgroundColorNeedsUpdate"b1"detailLabelBackgroundColorNeedsUpdate"b1"floating"b1"stripPadding"b1"isTopHeader"b1} _headerFooterFlags;
}
 + (id) _defaultPlainHeaderFooterFont;
 + (id) _defaultFontForTableViewStyle:(q)aisSectionHeader:(BOOL)b;
 + (id) _defaultTextColorForTableViewStyle:(q)aisSectionHeader:(BOOL)b;

 - (void) dealloc;
 - (void) layoutSubviews;
 - ({CGSize=dd}) sizeThatFits:({CGSize=dd})a;
 - (void) setTextAlignment:(q)a;
 - (void) setText:(id)a;
 - (id) tintColor;
 - (void) setTintColor:(id)a;
 - (BOOL) _transparentFocusContainer;
 - ({CGSize=dd}) systemLayoutSizeFittingSize:({CGSize=dd})awithHorizontalFittingPriority:(f)bverticalFittingPriority:(f)c;
 - (id) _scriptingInfo;
 - (id) backgroundImage;
 - (void) _updateBackgroundImage;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) _labelFrame;
 - (void) setMaxTitleWidth:(d)a;
 - (void) setFloating:(BOOL)a;
 - (void) setTableViewStyle:(q)a;
 - (void) setSectionHeader:(BOOL)a;
 - (void) setTableView:(id)a;
 - (void) _setMarginWidth:(d)a;
 - (void) _setRightMarginWidth:(d)a;
 - (void) _setupLabelAppearance;
 - (void) _setBackgroundViewColor:(id)a;
 - (id) initWithReuseIdentifier:(id)a;
 - (id) reuseIdentifier;
 - (void) setBackgroundView:(id)a;
 - (void) prepareForReuse;
 - (void) setReuseIdentifier:(id)a;
 - (id) textLabel;
 - (id) detailTextLabel;
 - (void) _setTopHeader:(BOOL)a;
 - (void) _setStripPadding:(BOOL)a;
 - (id) backgroundView;
 - (void) _tableViewDidUpdateMarginWidth;
 - (d) _marginWidth;
 - (q) textAlignment;
 - (void) setBackgroundImage:(id)a;
 - (void) setNeedsUpdateConstraints;
 - (id) tableView;
 - ({CGSize=dd}) _sizeThatFits:({CGSize=dd})astripPaddingForAbuttingView:(BOOL)bisTopHeader:(BOOL)c;
 - (q) tableViewStyle;
 - (d) _rightMarginWidth;
 - (void) _setupBackgroundView;
 - (void) _invalidateLabelBackgroundColor;
 - (void) _invalidateDetailLabelBackgroundColor;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) _backgroundRect;
 - (BOOL) sectionHeader;
 - (BOOL) _useDetailText;
 - (void) _updateLabelBackgroundColor;
 - (void) _updateDetailLabelBackgroundColor;
 - (id) _label:(BOOL)a;
 - ({CGSize=dd}) _textSizeForWidth:(d)a;
 - ({CGSize=dd}) _detailTextSizeForWidth:(d)a;
 - (void) _updateLayerContents;
 - (void) _updateContentAndBackgroundView;
 - (void) _updateLabelBackgroundColorIfNeeeded;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) _detailLabelFrame;
 - (void) _updateDetailLabelBackgroundColorIfNeeded;
 - (BOOL) floating;
 - (BOOL) _stripPadding;
 - (BOOL) _isTopHeader;
 - (d) maxTitleWidth;
 - (void) setBackgroundColor:(id)a;
 - (id) contentView;
 - (id) initWithFrame:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) frame;
 - (void) setFrame:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - (id) text;
 - (void) setOpaque:(BOOL)a;


@end
