
@protocol NSCopying;
@interface UITableViewRowData : NSObject <NSCopying> {

    @"UITableView" _tableView;
    q _numSections;
    q _sectionRowDataCapacity;
    ^@ _sectionRowData;
    d _minimumRowHeight;
    d _tableViewWidth;
    BOOL _tableHeaderHeightValid;
    d _tableHeaderHeight;
    BOOL _tableFooterHeightValid;
    d _tableFooterHeight;
    d _heightForTableHeaderViewHiding;
    d _tableTopPadding;
    d _tableBottomPadding;
    BOOL _tableSidePaddingValid;
    d _tableSidePadding;
    @"NSIndexPath" _reorderedIndexPath;
    @"NSIndexPath" _gapIndexPath;
    d _reorderedRowHeight;
    BOOL _estimatesRowHeights;
}
@property (nonatomic, assign, readonly) NSIndexPath* reorderGapIndexPath;
@property (nonatomic, assign, readonly) NSNumber* reorderedRowHeight;
@property (nonatomic, assign, readonly) NSNumber* heightForAutohidingTableHeaderView;
@property (nonatomic, assign, readonly) NSNumber* heightForTableHeaderViewHiding;
@property (nonatomic, assign, readwrite) NSNumber* minimumRowHeight;
@property (nonatomic, assign, readwrite) NSNumber* tableTopPadding;
@property (nonatomic, assign, readwrite) NSNumber* tableBottomPadding;
@property (nonatomic, assign, readwrite) NSNumber* tableSidePadding;
@property (nonatomic, assign, readwrite) NSNumber* estimatesRowHeights;

 - (id) copyWithZone:(^{_NSZone=})a;
 - (void) dealloc;
 - (q) numberOfRowsInSection:(q)a;
 - (q) numberOfSections;
 - (q) numberOfRows;
 - (id) initWithTableView:(id)a;
 - (id) indexPathForRowAtGlobalRow:(q)a;
 - (void) invalidateAllSections;
 - (void) setEstimatesRowHeights:(BOOL)a;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) rectForTableHeaderView;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) rectForTableFooterView;
 - (void) setHeightForTableHeaderViewHiding:(d)a;
 - (d) heightForAutohidingTableHeaderView;
 - (d) heightForTableHeaderViewHiding;
 - (void) tableHeaderHeightDidChangeToHeight:(d)a;
 - (d) heightForTable;
 - (void) ensureAllSectionsAreValid;
 - ({_NSRange=QQ}) sectionsInRect:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) rectForHeaderInSection:(q)aheightCanBeGuessed:(BOOL)b;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) rectForFooterInSection:(q)aheightCanBeGuessed:(BOOL)b;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) floatingRectForHeaderInSection:(q)avisibleRect:({CGRect={CGPoint=dd}{CGSize=dd}})b;
 - (d) maxHeaderTitleWidthForSection:(q)a;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) floatingRectForFooterInSection:(q)avisibleRect:({CGRect={CGPoint=dd}{CGSize=dd}})b;
 - (d) maxFooterTitleWidthForSection:(q)a;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) rectForGlobalRow:(q)aheightCanBeGuessed:(BOOL)b;
 - ({_NSRange=QQ}) globalRowsInRect:({CGRect={CGPoint=dd}{CGSize=dd}})acanGuess:(BOOL)b;
 - (q) globalRowForRowAtIndexPath:(id)a;
 - (q) headerAlignmentForSection:(q)a;
 - (q) footerAlignmentForSection:(q)a;
 - (d) minimumRowHeight;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) rectForTable;
 - (void) tableViewWidthDidChangeToWidth:(d)a;
 - (void) setReorderedIndexPath:(id)a;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) rectForRow:(q)ainSection:(q)bheightCanBeGuessed:(BOOL)c;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) rectForSection:(q)a;
 - (id) indexPathsForRowsInRect:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - (d) heightForHeaderInSection:(q)acanGuess:(BOOL)b;
 - (d) heightForFooterInSection:(q)acanGuess:(BOOL)b;
 - (d) heightForTableHeaderView;
 - (d) tableSidePadding;
 - (void) invalidateAllSectionOffsetsAndUpdatePadding;
 - (void) tableFooterHeightDidChangeToHeight:(d)a;
 - (i) sectionLocationForRow:(q)ainSection:(q)b;
 - (void) setHeight:(d)aforRowAtIndexPath:(id)b;
 - (void) addReorderGapFromIndexPath:(id)a;
 - (void) removeReorderGapFromIndexPath:(id)a;
 - (void) moveRowAtIndexPathFrom:(id)atoIndexPath:(id)b;
 - (id) targetIndexPathForPoint:({CGPoint=dd})a;
 - (BOOL) shouldStripHeaderTopPaddingForSection:(q)a;
 - (BOOL) hasHeaderForSection:(q)a;
 - (i) sectionLocationForReorderedRow:(q)ainSection:(q)b;
 - (d) heightForRow:(q)ainSection:(q)bcanGuess:(BOOL)c;
 - (void) adjustSectionOffsetsBeginningAtIndex:(q)acount:(q)bdelta:(d)crowDelta:(q)d;
 - (void) setTableTopPadding:(d)a;
 - (void) setTableBottomPadding:(d)a;
 - (BOOL) estimatesRowHeights;
 - (void) setMinimumRowHeight:(d)a;
 - (id) reorderedIndexPath;
 - (id) reorderGapIndexPath;
 - (d) reorderedRowHeight;
 - (q) sectionForSectionRowData:(id)a;
 - (d) offsetForSection:(id)a;
 - (void) _updateSectionRowDataArrayForNumSections:(q)a;
 - (void) _ensureSectionOffsetIsValidForSection:(q)a;
 - (void) _updateNumSections;
 - (void) _updateTopAndBottomPadding;
 - (d) heightForRow:(q)ainSection:(q)bcanGuess:(BOOL)cadjustForReorderedRow:(BOOL)d;
 - (d) heightForTableFooterView;
 - (BOOL) hasFooterForSection:(q)a;
 - (q) _sectionRowForGlobalRow:(q)ainSection:(^q)b;
 - (q) sectionForPoint:({CGPoint=dd})a;
 - (q) _sectionForPoint:({CGPoint=dd})abeginningWithSection:(q)bnumberOfSections:(q)c;
 - (void) invalidateSection:(q)a;
 - (q) numberOfRowsBeforeSection:(q)a;
 - (d) heightForSection:(q)a;
 - (void) setTableSidePadding:(d)a;
 - (d) tableTopPadding;
 - (d) tableBottomPadding;


@end
