
@protocol UIGestureRecognizerDelegate, UITabBarDelegate, NSCoding;
@interface UITabBarController : UIViewController <UIGestureRecognizerDelegate, UITabBarDelegate, NSCoding> {

    UITabBar* _tabBar;
    UIView* _containerView;
    UIView* _viewControllerTransitionView;
    id _tabBarItemsToViewControllers;
    UIViewController* _selectedViewController;
    UIMoreNavigationController* _moreNavigationController;
    NSArray* _customizableViewControllers;
    <UITabBarControllerDelegate><UITabBarControllerDelegate_Private>* _delegate;
    UIViewController* _selectedViewControllerDuringWillAppear;
    UIViewController* _transientViewController;
    unsigned long long _customMaxItems;
    unsigned long long _defaultMaxItems;
    long long _tabBarPosition;
    UITapGestureRecognizer* _backGestureRecognizer;
    UITapGestureRecognizer* _selectGestureRecognizer;
    {?="isShowingMoreItem"b1"needsToRebuildItems"b1"isBarHidden"b1"editButtonOnLeft"b1"barLayoutIsValid"b1"reselectTab"b1"delegateSupportedInterfaceOrientations"b1"delegatePreferredInterfaceOrientationForPresentation"b1"preferTabBarFocused"b1} _tabBarControllerFlags;
    NSMutableArray* _moreChildViewControllers;
    UIView* _accessoryView;
    <UIViewControllerAnimatedTransitioning>* __animator;
    <UIViewControllerInteractiveTransitioning>* __interactor;
    NSString* __backdropGroupName;
}
 + (BOOL) _directlySetsContentOverlayInsetsForChildren;
 + (BOOL) doesOverrideSupportedInterfaceOrientations;
 + (BOOL) _shouldSendLegacyMethodsFromViewWillTransitionToSize;
 + (BOOL) _shouldForwardViewWillTransitionToSize;
 + (BOOL) doesOverridePreferredInterfaceOrientationForPresentation;
 + (Class) _moreNavigationControllerClass;

 - (void) dealloc;
 - (void) setDelegate:(id)a ;
 - (id) _deepestUnambiguousResponder;
 - (unsigned long long) supportedInterfaceOrientations;
 - (void) encodeRestorableStateWithCoder:(id)a ;
 - (void) decodeRestorableStateWithCoder:(id)a ;
 - (void) setView:(id)a ;
 - (id) preferredFocusedItem;
 - (void) _willChangeToIdiom:(long long)a onScreen:(id)b ;
 - (void) _setAnimator:(id)a ;
 - (id) _animator;
 - (id) _responderSelectionContainerViewForResponder:(id)a ;
 - (void) animationDidStop:(id)a finished:(id)b context:(id)c ;
 - (id) _transitionView;
 - (void) setRestorationIdentifier:(id)a ;
 - (void) traitCollectionDidChange:(id)a ;
 - (BOOL) _gestureRecognizerShouldBegin:(id)a ;
 - (id) _accessoryView;
 - (void) transitionViewDidComplete:(id)a fromView:(id)b toView:(id)c ;
 - (void) _setInteractor:(id)a ;
 - (void) _updateLayoutForStatusBarAndInterfaceOrientation;
 - ({CGSize=dd}) sizeForChildContentContainer:(id)a withParentContainerSize:({CGSize=dd})b ;
 - (void) willTransitionToTraitCollection:(id)a withTransitionCoordinator:(id)b ;
 - (id) initWithNibName:(id)a bundle:(id)b ;
 - (void) loadView;
 - (BOOL) shouldAutorotateToInterfaceOrientation:(long long)a ;
 - (long long) preferredInterfaceOrientationForPresentation;
 - (void) _setAccessoryView:(id)a ;
 - (void) viewWillAppear:(BOOL)a ;
 - ({UIEdgeInsets=dddd}) _edgeInsetsForChildViewController:(id)a insetsAreAbsolute:(^B)b ;
 - (BOOL) _isPresentationContextByDefault;
 - (BOOL) _shouldPersistViewWhenCoding;
 - (void) _populateArchivedChildViewControllers:(id)a ;
 - (id) _backdropBarGroupName;
 - (id) _viewsWithDisabledInteractionGivenTransitionContext:(id)a ;
 - (void) viewDidAppear:(BOOL)a ;
 - (void) viewWillDisappear:(BOOL)a ;
 - (void) viewDidDisappear:(BOOL)a ;
 - (void) purgeMemoryForReason:(int)a ;
 - (BOOL) _reallyWantsFullScreenLayout;
 - (BOOL) _isSupportedInterfaceOrientation:(long long)a ;
 - (id) transitionCoordinator;
 - (void) willRotateToInterfaceOrientation:(long long)a duration:(double)b ;
 - (void) willAnimateRotationToInterfaceOrientation:(long long)a duration:(double)b ;
 - (void) didRotateFromInterfaceOrientation:(long long)a ;
 - (BOOL) _allowsAutorotation;
 - (BOOL) _shouldSynthesizeSupportedOrientations;
 - (id) rotatingHeaderView;
 - (id) rotatingFooterView;
 - (BOOL) _shouldUseOnePartRotation;
 - (void) willAnimateFirstHalfOfRotationToInterfaceOrientation:(long long)a duration:(double)b ;
 - (void) willAnimateSecondHalfOfRotationFromInterfaceOrientation:(long long)a duration:(double)b ;
 - (void) _getRotationContentSettings:(^{?=BBBBBdi})a ;
 - (void) didAnimateFirstHalfOfRotationToInterfaceOrientation:(long long)a ;
 - (id) childViewControllerForStatusBarStyle;
 - (id) childViewControllerForStatusBarHidden;
 - (id) rotatingSnapshotViewForWindow:(id)a ;
 - (void) updateTabBarItemForViewController:(id)a ;
 - (id) _allContainedViewControllers;
 - (id) _additionalViewControllersToCheckForUserActivity;
 - (void) setViewControllers:(id)a animated:(BOOL)b ;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) _frameForViewController:(id)a ;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) _frameForWrapperViewForViewController:(id)a ;
 - (void) _setBackdropGroupName:(id)a ;
 - (id) _backdropGroupName;
 - (id) tabBar;
 - (id) viewControllers;
 - (void) _performBackGesture:(id)a ;
 - (void) _layoutViewController:(id)a ;
 - (id) _selectedViewControllerInTabBar;
 - (void) _hideBarWithTransition:(int)a isExplicit:(BOOL)b ;
 - (void) showBarWithTransition:(int)a ;
 - (void) setViewControllers:(id)a ;
 - (void) __viewWillLayoutSubviews;
 - (unsigned long long) _effectiveMaxItems;
 - (id) selectedViewController;
 - (void) setSelectedViewController:(id)a ;
 - (id) _wrapperViewForViewController:(id)a ;
 - (void) _rebuildTabBarItemsIfNeeded;
 - (void) _setSelectedTabBarItem:(id)a ;
 - (void) _layoutContainerView;
 - (void) _selectDefaultViewControllerIfNecessaryWithAppearanceTransitions:(BOOL)a ;
 - (long long) _effectiveTabBarPosition;
 - (void) _prepareTabBar;
 - (void) _setTabBarVisualAltitude;
 - (BOOL) _isBarHidden;
 - (void) _updateLayoutForTraitCollection:(id)a ;
 - (void) _rebuildTabBarItemsAnimated:(BOOL)a ;
 - (void) _showBarWithTransition:(int)a isExplicit:(BOOL)b ;
 - (void) _setTabBarPosition:(long long)a ;
 - (id) customizableViewControllers;
 - (void) _setViewControllers:(id)a animated:(BOOL)b ;
 - (void) _performSelectGesture:(id)a ;
 - (BOOL) _isTabBarFocused;
 - (void) _tabBarItemClicked:(id)a ;
 - (void) _configureTargetActionForTabBarItem:(id)a ;
 - (id) moreNavigationController;
 - (id) transientViewController;
 - (void) setTransientViewController:(id)a animated:(BOOL)b ;
 - (unsigned long long) selectedIndex;
 - (id) _viewControllersInTabBar;
 - (id) _existingMoreNavigationController;
 - (id) _viewControllerForSelectAtIndex:(unsigned long long)a ;
 - (void) setSelectedIndex:(unsigned long long)a ;
 - (void) setCustomizableViewControllers:(id)a ;
 - (BOOL) _allowSelectionWithinMoreList;
 - (void) setTransientViewController:(id)a ;
 - (void) _setSelectedViewController:(id)a ;
 - (id) allViewControllers;
 - (void) transitionFromViewController:(id)a toViewController:(id)b ;
 - (void) _setMoreNavigationControllerRestorationIdentifier;
 - (BOOL) _allowsCustomizing;
 - (id) _viewControllerForTabBarItem:(id)a ;
 - (void) concealTabBarSelection;
 - (void) transitionFromViewController:(id)a toViewController:(id)b transition:(int)c shouldSetSelected:(BOOL)d ;
 - (id) _customAnimatorForFromViewController:(id)a toViewController:(id)b ;
 - (id) _customInteractionControllerForAnimator:(id)a ;
 - (void) revealTabBarSelection;
 - (BOOL) _doAllViewControllersSupportInterfaceOrientation:(long long)a ;
 - (void) tabBar:(id)a willBeginCustomizingItems:(id)b ;
 - (void) tabBar:(id)a willEndCustomizingItems:(id)b changed:(BOOL)c ;
 - (void) tabBar:(id)a didEndCustomizingItems:(id)b changed:(BOOL)c ;
 - (void) setTabBar:(id)a ;
 - (void) beginCustomizingTabBar:(id)a ;
 - (void) tabBarSizingDidChange:(id)a ;
 - (void) hideBarWithTransition:(int)a ;
 - (long long) _tabBarPosition;
 - (void) setShowsEditButtonOnLeft:(BOOL)a ;
 - (BOOL) showsEditButtonOnLeft;
 - (void) _setMaximumNumberOfItems:(unsigned long long)a ;
 - (void) _setBadgeValue:(id)a forTabBarItem:(id)b ;
 - (id) moreChildViewControllers;
 - (void) setMoreChildViewControllers:(id)a ;
 - (id) _interactor;
 - (BOOL) _ignoreUnselectedTabsForStateRestoration;
 - (void) encodeWithCoder:(id)a ;
 - (id) initWithCoder:(id)a ;
 - (id) delegate;
 - (BOOL) becomeFirstResponder;


@end
