
@protocol NSCopying;
@interface UITableViewRowData : NSObject <NSCopying> {

    UITableView* _tableView;
    long long _numSections;
    long long _sectionRowDataCapacity;
    ^@ _sectionRowData;
    double _minimumRowHeight;
    double _tableViewWidth;
    BOOL _tableHeaderHeightValid;
    double _tableHeaderHeight;
    BOOL _tableFooterHeightValid;
    double _tableFooterHeight;
    double _heightForTableHeaderViewHiding;
    double _tableTopPadding;
    double _tableBottomPadding;
    BOOL _tableSidePaddingValid;
    double _tableSidePadding;
    NSIndexPath* _reorderedIndexPath;
    NSIndexPath* _gapIndexPath;
    double _reorderedRowHeight;
    BOOL _estimatesRowHeights;
}
@property (nonatomic, assign, readonly) NSIndexPath* reorderGapIndexPath;
@property (nonatomic, assign, readonly) NSNumber* reorderedRowHeight;
@property (nonatomic, assign, readonly) NSNumber* heightForAutohidingTableHeaderView;
@property (nonatomic, assign, readonly) NSNumber* heightForTableHeaderViewHiding;
@property (nonatomic, assign, readwrite) NSNumber* minimumRowHeight;
@property (nonatomic, assign, readwrite) NSNumber* tableTopPadding;
@property (nonatomic, assign, readwrite) NSNumber* tableBottomPadding;
@property (nonatomic, assign, readwrite) NSNumber* tableSidePadding;
@property (nonatomic, assign, readwrite) NSNumber* estimatesRowHeights;

 - (id) copyWithZone:(^{_NSZone=})a ;
 - (void) dealloc;
 - (long long) numberOfRowsInSection:(long long)a ;
 - (long long) numberOfSections;
 - (long long) numberOfRows;
 - (id) initWithTableView:(id)a ;
 - (id) indexPathForRowAtGlobalRow:(long long)a ;
 - (void) invalidateAllSections;
 - (void) setEstimatesRowHeights:(BOOL)a ;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) rectForTableHeaderView;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) rectForTableFooterView;
 - (void) setHeightForTableHeaderViewHiding:(double)a ;
 - (double) heightForAutohidingTableHeaderView;
 - (double) heightForTableHeaderViewHiding;
 - (void) tableHeaderHeightDidChangeToHeight:(double)a ;
 - (double) heightForTable;
 - (void) ensureAllSectionsAreValid;
 - ({_NSRange=QQ}) sectionsInRect:({CGRect={CGPoint=dd}{CGSize=dd}})a ;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) rectForHeaderInSection:(long long)a heightCanBeGuessed:(BOOL)b ;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) rectForFooterInSection:(long long)a heightCanBeGuessed:(BOOL)b ;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) floatingRectForHeaderInSection:(long long)a visibleRect:({CGRect={CGPoint=dd}{CGSize=dd}})b ;
 - (double) maxHeaderTitleWidthForSection:(long long)a ;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) floatingRectForFooterInSection:(long long)a visibleRect:({CGRect={CGPoint=dd}{CGSize=dd}})b ;
 - (double) maxFooterTitleWidthForSection:(long long)a ;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) rectForGlobalRow:(long long)a heightCanBeGuessed:(BOOL)b ;
 - ({_NSRange=QQ}) globalRowsInRect:({CGRect={CGPoint=dd}{CGSize=dd}})a canGuess:(BOOL)b ;
 - (long long) globalRowForRowAtIndexPath:(id)a ;
 - (long long) headerAlignmentForSection:(long long)a ;
 - (long long) footerAlignmentForSection:(long long)a ;
 - (double) minimumRowHeight;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) rectForTable;
 - (void) tableViewWidthDidChangeToWidth:(double)a ;
 - (void) setReorderedIndexPath:(id)a ;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) rectForRow:(long long)a inSection:(long long)b heightCanBeGuessed:(BOOL)c ;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) rectForSection:(long long)a ;
 - (id) indexPathsForRowsInRect:({CGRect={CGPoint=dd}{CGSize=dd}})a ;
 - (double) heightForHeaderInSection:(long long)a canGuess:(BOOL)b ;
 - (double) heightForFooterInSection:(long long)a canGuess:(BOOL)b ;
 - (double) heightForTableHeaderView;
 - (double) tableSidePadding;
 - (void) invalidateAllSectionOffsetsAndUpdatePadding;
 - (void) tableFooterHeightDidChangeToHeight:(double)a ;
 - (int) sectionLocationForRow:(long long)a inSection:(long long)b ;
 - (void) setHeight:(double)a forRowAtIndexPath:(id)b ;
 - (void) addReorderGapFromIndexPath:(id)a ;
 - (void) removeReorderGapFromIndexPath:(id)a ;
 - (void) moveRowAtIndexPathFrom:(id)a toIndexPath:(id)b ;
 - (id) targetIndexPathForPoint:({CGPoint=dd})a ;
 - (BOOL) shouldStripHeaderTopPaddingForSection:(long long)a ;
 - (BOOL) hasHeaderForSection:(long long)a ;
 - (int) sectionLocationForReorderedRow:(long long)a inSection:(long long)b ;
 - (double) heightForRow:(long long)a inSection:(long long)b canGuess:(BOOL)c ;
 - (void) adjustSectionOffsetsBeginningAtIndex:(long long)a count:(long long)b delta:(double)c rowDelta:(long long)d ;
 - (void) setTableTopPadding:(double)a ;
 - (void) setTableBottomPadding:(double)a ;
 - (BOOL) estimatesRowHeights;
 - (void) setMinimumRowHeight:(double)a ;
 - (id) reorderedIndexPath;
 - (id) reorderGapIndexPath;
 - (double) reorderedRowHeight;
 - (long long) sectionForSectionRowData:(id)a ;
 - (double) offsetForSection:(id)a ;
 - (void) _updateSectionRowDataArrayForNumSections:(long long)a ;
 - (void) _ensureSectionOffsetIsValidForSection:(long long)a ;
 - (void) _updateNumSections;
 - (void) _updateTopAndBottomPadding;
 - (double) heightForRow:(long long)a inSection:(long long)b canGuess:(BOOL)c adjustForReorderedRow:(BOOL)d ;
 - (double) heightForTableFooterView;
 - (BOOL) hasFooterForSection:(long long)a ;
 - (long long) _sectionRowForGlobalRow:(long long)a inSection:(^q)b ;
 - (long long) sectionForPoint:({CGPoint=dd})a ;
 - (long long) _sectionForPoint:({CGPoint=dd})a beginningWithSection:(long long)b numberOfSections:(long long)c ;
 - (void) invalidateSection:(long long)a ;
 - (long long) numberOfRowsBeforeSection:(long long)a ;
 - (double) heightForSection:(long long)a ;
 - (void) setTableSidePadding:(double)a ;
 - (double) tableTopPadding;
 - (double) tableBottomPadding;


@end
