
@protocol UIGestureRecognizerDelegate, UITabBarDelegate, NSCoding;
@interface UITabBarController : UIViewController <UIGestureRecognizerDelegate, UITabBarDelegate, NSCoding> {

    @"UITabBar" _tabBar;
    @"UIView" _containerView;
    @"UIView" _viewControllerTransitionView;
    id _tabBarItemsToViewControllers;
    @"UIViewController" _selectedViewController;
    @"UIMoreNavigationController" _moreNavigationController;
    @"NSArray" _customizableViewControllers;
    @"<UITabBarControllerDelegate><UITabBarControllerDelegate_Private>" _delegate;
    @"UIViewController" _selectedViewControllerDuringWillAppear;
    @"UIViewController" _transientViewController;
    Q _customMaxItems;
    Q _defaultMaxItems;
    q _tabBarPosition;
    @"UITapGestureRecognizer" _backGestureRecognizer;
    @"UITapGestureRecognizer" _selectGestureRecognizer;
    {?="isShowingMoreItem"b1"needsToRebuildItems"b1"isBarHidden"b1"editButtonOnLeft"b1"barLayoutIsValid"b1"reselectTab"b1"delegateSupportedInterfaceOrientations"b1"delegatePreferredInterfaceOrientationForPresentation"b1"preferTabBarFocused"b1} _tabBarControllerFlags;
    @"NSMutableArray" _moreChildViewControllers;
    @"UIView" _accessoryView;
    @"<UIViewControllerAnimatedTransitioning>" __animator;
    @"<UIViewControllerInteractiveTransitioning>" __interactor;
    @"NSString" __backdropGroupName;
}
 + (BOOL) _directlySetsContentOverlayInsetsForChildren;
 + (BOOL) doesOverrideSupportedInterfaceOrientations;
 + (BOOL) _shouldSendLegacyMethodsFromViewWillTransitionToSize;
 + (BOOL) _shouldForwardViewWillTransitionToSize;
 + (BOOL) doesOverridePreferredInterfaceOrientationForPresentation;
 + (Class) _moreNavigationControllerClass;

 - (void) dealloc;
 - (void) setDelegate:(id)a;
 - (id) _deepestUnambiguousResponder;
 - (Q) supportedInterfaceOrientations;
 - (void) encodeRestorableStateWithCoder:(id)a;
 - (void) decodeRestorableStateWithCoder:(id)a;
 - (void) setView:(id)a;
 - (id) preferredFocusedItem;
 - (void) _willChangeToIdiom:(q)aonScreen:(id)b;
 - (void) _setAnimator:(id)a;
 - (id) _animator;
 - (id) _responderSelectionContainerViewForResponder:(id)a;
 - (void) animationDidStop:(id)afinished:(id)bcontext:(id)c;
 - (id) _transitionView;
 - (void) setRestorationIdentifier:(id)a;
 - (void) traitCollectionDidChange:(id)a;
 - (BOOL) _gestureRecognizerShouldBegin:(id)a;
 - (id) _accessoryView;
 - (void) transitionViewDidComplete:(id)afromView:(id)btoView:(id)c;
 - (void) _setInteractor:(id)a;
 - (void) _updateLayoutForStatusBarAndInterfaceOrientation;
 - ({CGSize=dd}) sizeForChildContentContainer:(id)awithParentContainerSize:({CGSize=dd})b;
 - (void) willTransitionToTraitCollection:(id)awithTransitionCoordinator:(id)b;
 - (id) initWithNibName:(id)abundle:(id)b;
 - (void) loadView;
 - (BOOL) shouldAutorotateToInterfaceOrientation:(q)a;
 - (q) preferredInterfaceOrientationForPresentation;
 - (void) _setAccessoryView:(id)a;
 - (void) viewWillAppear:(BOOL)a;
 - ({UIEdgeInsets=dddd}) _edgeInsetsForChildViewController:(id)ainsetsAreAbsolute:(^B)b;
 - (BOOL) _isPresentationContextByDefault;
 - (BOOL) _shouldPersistViewWhenCoding;
 - (void) _populateArchivedChildViewControllers:(id)a;
 - (id) _backdropBarGroupName;
 - (id) _viewsWithDisabledInteractionGivenTransitionContext:(id)a;
 - (void) viewDidAppear:(BOOL)a;
 - (void) viewWillDisappear:(BOOL)a;
 - (void) viewDidDisappear:(BOOL)a;
 - (void) purgeMemoryForReason:(i)a;
 - (BOOL) _reallyWantsFullScreenLayout;
 - (BOOL) _isSupportedInterfaceOrientation:(q)a;
 - (id) transitionCoordinator;
 - (void) willRotateToInterfaceOrientation:(q)aduration:(d)b;
 - (void) willAnimateRotationToInterfaceOrientation:(q)aduration:(d)b;
 - (void) didRotateFromInterfaceOrientation:(q)a;
 - (BOOL) _allowsAutorotation;
 - (BOOL) _shouldSynthesizeSupportedOrientations;
 - (id) rotatingHeaderView;
 - (id) rotatingFooterView;
 - (BOOL) _shouldUseOnePartRotation;
 - (void) willAnimateFirstHalfOfRotationToInterfaceOrientation:(q)aduration:(d)b;
 - (void) willAnimateSecondHalfOfRotationFromInterfaceOrientation:(q)aduration:(d)b;
 - (void) _getRotationContentSettings:(^{?=BBBBBdi})a;
 - (void) didAnimateFirstHalfOfRotationToInterfaceOrientation:(q)a;
 - (id) childViewControllerForStatusBarStyle;
 - (id) childViewControllerForStatusBarHidden;
 - (id) rotatingSnapshotViewForWindow:(id)a;
 - (void) updateTabBarItemForViewController:(id)a;
 - (id) _allContainedViewControllers;
 - (id) _additionalViewControllersToCheckForUserActivity;
 - (void) setViewControllers:(id)aanimated:(BOOL)b;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) _frameForViewController:(id)a;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) _frameForWrapperViewForViewController:(id)a;
 - (void) _setBackdropGroupName:(id)a;
 - (id) _backdropGroupName;
 - (id) tabBar;
 - (id) viewControllers;
 - (void) _performBackGesture:(id)a;
 - (void) _layoutViewController:(id)a;
 - (id) _selectedViewControllerInTabBar;
 - (void) _hideBarWithTransition:(i)aisExplicit:(BOOL)b;
 - (void) showBarWithTransition:(i)a;
 - (void) setViewControllers:(id)a;
 - (void) __viewWillLayoutSubviews;
 - (Q) _effectiveMaxItems;
 - (id) selectedViewController;
 - (void) setSelectedViewController:(id)a;
 - (id) _wrapperViewForViewController:(id)a;
 - (void) _rebuildTabBarItemsIfNeeded;
 - (void) _setSelectedTabBarItem:(id)a;
 - (void) _layoutContainerView;
 - (void) _selectDefaultViewControllerIfNecessaryWithAppearanceTransitions:(BOOL)a;
 - (q) _effectiveTabBarPosition;
 - (void) _prepareTabBar;
 - (void) _setTabBarVisualAltitude;
 - (BOOL) _isBarHidden;
 - (void) _updateLayoutForTraitCollection:(id)a;
 - (void) _rebuildTabBarItemsAnimated:(BOOL)a;
 - (void) _showBarWithTransition:(i)aisExplicit:(BOOL)b;
 - (void) _setTabBarPosition:(q)a;
 - (id) customizableViewControllers;
 - (void) _setViewControllers:(id)aanimated:(BOOL)b;
 - (void) _performSelectGesture:(id)a;
 - (BOOL) _isTabBarFocused;
 - (void) _tabBarItemClicked:(id)a;
 - (void) _configureTargetActionForTabBarItem:(id)a;
 - (id) moreNavigationController;
 - (id) transientViewController;
 - (void) setTransientViewController:(id)aanimated:(BOOL)b;
 - (Q) selectedIndex;
 - (id) _viewControllersInTabBar;
 - (id) _existingMoreNavigationController;
 - (id) _viewControllerForSelectAtIndex:(Q)a;
 - (void) setSelectedIndex:(Q)a;
 - (void) setCustomizableViewControllers:(id)a;
 - (BOOL) _allowSelectionWithinMoreList;
 - (void) setTransientViewController:(id)a;
 - (void) _setSelectedViewController:(id)a;
 - (id) allViewControllers;
 - (void) transitionFromViewController:(id)atoViewController:(id)b;
 - (void) _setMoreNavigationControllerRestorationIdentifier;
 - (BOOL) _allowsCustomizing;
 - (id) _viewControllerForTabBarItem:(id)a;
 - (void) concealTabBarSelection;
 - (void) transitionFromViewController:(id)atoViewController:(id)btransition:(i)cshouldSetSelected:(BOOL)d;
 - (id) _customAnimatorForFromViewController:(id)atoViewController:(id)b;
 - (id) _customInteractionControllerForAnimator:(id)a;
 - (void) revealTabBarSelection;
 - (BOOL) _doAllViewControllersSupportInterfaceOrientation:(q)a;
 - (void) tabBar:(id)awillBeginCustomizingItems:(id)b;
 - (void) tabBar:(id)awillEndCustomizingItems:(id)bchanged:(BOOL)c;
 - (void) tabBar:(id)adidEndCustomizingItems:(id)bchanged:(BOOL)c;
 - (void) setTabBar:(id)a;
 - (void) beginCustomizingTabBar:(id)a;
 - (void) tabBarSizingDidChange:(id)a;
 - (void) hideBarWithTransition:(i)a;
 - (q) _tabBarPosition;
 - (void) setShowsEditButtonOnLeft:(BOOL)a;
 - (BOOL) showsEditButtonOnLeft;
 - (void) _setMaximumNumberOfItems:(Q)a;
 - (void) _setBadgeValue:(id)aforTabBarItem:(id)b;
 - (id) moreChildViewControllers;
 - (void) setMoreChildViewControllers:(id)a;
 - (id) _interactor;
 - (BOOL) _ignoreUnselectedTabsForStateRestoration;
 - (void) encodeWithCoder:(id)a;
 - (id) initWithCoder:(id)a;
 - (id) delegate;
 - (BOOL) becomeFirstResponder;


@end
