
@protocol _UIBackdropViewGraphicsQualityChangeDelegate, _UIShadowedView;
@interface UITabBar : UIView <_UIBackdropViewGraphicsQualityChangeDelegate, _UIShadowedView> {

    @"UIView" _customizeView;
    @"_UITabBarBackgroundView" _backgroundView;
    @"_UIBackdropView" _adaptiveBackdrop;
    @"UIView" _shadowView;
    @"<UITabBarDelegate>" _delegate;
    @"NSArray" _items;
    @"UITabBarItem" _selectedItem;
    @"NSArray" _customizationItems;
    q _barOrientation;
    {?="alertShown"b1"wasEnabled"b1"customized"b1"downButtonSentAction"b1"isLocked"b1"backgroundIsPattern"b1"hasCustomBackgroundView"b1"barStyle"b3"barTranslucence"b3"backgroundNeedsUpdate"b1} _tabBarFlags;
    @"NSArray" _buttonItems;
    ^{__CFArray=} _hiddenItems;
    @"_UITabBarAppearanceStorage" _appearanceStorage;
    BOOL _dividerImagesChangeWithSelection;
    BOOL _dividerImagesAreInvalid;
    BOOL _hidesShadow;
    BOOL _showsHighlightedState;
    d _nextSelectionSlideDuration;
    @"NSMutableArray" _dividerImageViews;
    q _itemPositioning;
    d _itemDimension;
    d _itemSpacing;
    q _barMetrics;
    q _imageStyle;
    q _tabBarSizing;
    @"UIView" _accessoryView;
    @"NSString" _backdropViewLayerGroupName;
}
 + (void) _initializeForIdiom:(q)a;
 + (id) _unselectedTabTintColorForView:(id)a;
 + (f) _buttonGap;
 + (id) _tabBarForView:(id)a;

 - (void) dealloc;
 - (void) setDelegate:(id)a;
 - (void) _populateArchivedSubviews:(id)a;
 - (id) hitTest:({CGPoint=dd})awithEvent:(id)b;
 - ({CGSize=dd}) _intrinsicSizeWithinSize:({CGSize=dd})a;
 - (void) layoutSubviews;
 - (BOOL) _contentHuggingDefault_isUsuallyFixedHeight;
 - ({CGSize=dd}) sizeThatFits:({CGSize=dd})a;
 - (id) _backgroundView;
 - (void) setTranslatesAutoresizingMaskIntoConstraints:(BOOL)a;
 - (void) touchesBegan:(id)awithEvent:(id)b;
 - (void) touchesMoved:(id)awithEvent:(id)b;
 - (void) touchesEnded:(id)awithEvent:(id)b;
 - (void) touchesCancelled:(id)awithEvent:(id)b;
 - (void) _setVisualAltitude:(d)a;
 - (void) _setVisualAltitudeBias:({CGSize=dd})a;
 - (BOOL) isTranslucent;
 - (BOOL) isLocked;
 - (id) preferredFocusedItem;
 - (BOOL) _canDrawContent;
 - (void) setTintColor:(id)a;
 - (BOOL) canBecomeFocused;
 - (void) _didMoveFromWindow:(id)atoWindow:(id)b;
 - (id) hitTest:({CGPoint=dd})aforEvent:(^{__GSEvent=})b;
 - (void) _didChangeFromIdiom:(q)aonScreen:(id)btraverseHierarchy:(BOOL)c;
 - (BOOL) _subclassImplementsDrawRect;
 - (id) backgroundImage;
 - (id) shadowImage;
 - (void) setShadowImage:(id)a;
 - (id) _appearanceStorage;
 - (id) _shadowView;
 - (void) _setBackgroundView:(id)a;
 - (id) _effectiveBarTintColor;
 - (void) _updateBackgroundImage;
 - (void) setItems:(id)aanimated:(BOOL)b;
 - (id) items;
 - (void) setLocked:(BOOL)a;
 - (void) addConstraint:(id)a;
 - (void) removeConstraint:(id)a;
 - (void) setBarStyle:(q)a;
 - (BOOL) _wantsAdaptiveBackdrop;
 - (q) barStyle;
 - (void) setTranslucent:(BOOL)a;
 - (void) setBarTintColor:(id)a;
 - (void) _accessibilityButtonShapesParametersDidChange;
 - (void) _setBackdropViewLayerGroupName:(id)a;
 - (BOOL) _hidesShadow;
 - (void) _setHidesShadow:(BOOL)a;
 - (id) barTintColor;
 - (id) _backdropViewLayerGroupName;
 - (id) _accessoryView;
 - (id) backdropView:(id)awillChangeToGraphicsQuality:(q)b;
 - (void) backdropView:(id)adidChangeToGraphicsQuality:(q)b;
 - (void) _setAccessoryView:(id)a;
 - (BOOL) _isTranslucent;
 - (void) _setBarOrientation:(q)a;
 - (void) setSelectedItem:(id)a;
 - (void) beginCustomizingItems:(id)a;
 - (BOOL) isCustomizing;
 - (void) setBackgroundImage:(id)a;
 - (void) _sendAction:(id)awithEvent:(id)b;
 - (void) setBadgeValue:(id)aforButton:(i)b;
 - (void) setBadgeGlyph:(id)aforButton:(i)b;
 - (void) setBadgeAnimated:(BOOL)aforButton:(i)b;
 - (id) buttonItems;
 - (void) setButtonItems:(id)a;
 - (void) _cleanupAdaptiveBackdrop;
 - (void) _buttonDownDelayed:(id)a;
 - (void) _buttonDown:(id)a;
 - (void) _buttonUp:(id)a;
 - (void) _buttonCancel:(id)a;
 - (void) _setDividerImage:(id)aforLeftButtonState:(Q)brightButtonState:(Q)c;
 - (id) _dividerImageForLeftButtonState:(Q)arightButtonState:(Q)b;
 - (id) selectionIndicatorImage;
 - (void) setSelectionIndicatorImage:(id)a;
 - (id) selectedImageTintColor;
 - (void) setSelectedImageTintColor:(id)a;
 - (q) _tabBarSizing;
 - (BOOL) _showsHighlightedState;
 - (q) _barMetrics;
 - (void) _setShowsHighlightedState:(BOOL)a;
 - (void) _configureTabBarReplacingItem:(id)awithNewItem:(id)bdragging:(BOOL)cswapping:(BOOL)d;
 - (void) _positionTabBarButtons:(id)aignoringItem:(id)b;
 - (void) _setBackgroundImage:(id)a;
 - (void) _setSelectionIndicatorImage:(id)a;
 - (void) _setLabelFont:(id)a;
 - (void) _setLabelTextColor:(id)aselectedTextColor:(id)b;
 - (void) _setLabelShadowColor:(id)a;
 - (void) _setLabelShadowOffset:({CGSize=dd})a;
 - (void) _setBackgroundNeedsUpdate:(BOOL)a;
 - (void) setItemWidth:(d)a;
 - (d) itemWidth;
 - (void) setItemSpacing:(d)a;
 - (d) itemSpacing;
 - (void) _setBarMetrics:(q)a;
 - (void) _setImageStyle:(q)a;
 - (void) _accessibilityButtonShapesEnabledDidChangeNotification:(id)a;
 - (void) _doCommonTabBarInit;
 - (id) _topmostDividerImageView;
 - (void) _invalidateDividerImages;
 - (void) _updateDividerImagesIfNecessary;
 - (void) _animateSelectionChangeFromView:(id)atoView:(id)bduration:(d)c;
 - (void) _showItemsAnimated:(BOOL)a;
 - (q) _imageStyle;
 - (void) _finishSetItems:(id)afinished:(id)bcontext:(id)c;
 - (void) _hideItemsAnimated:(BOOL)a;
 - (q) _effectiveBarOrientation;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) _tabAreaLayoutBounds;
 - (BOOL) _backgroundNeedsUpdate;
 - (void) _customizeWithAvailableItems:(id)a;
 - (void) _dismissCustomizeSheet:(BOOL)a;
 - (id) selectedItem;
 - (void) _updateTintedImages:(id)aselected:(BOOL)b;
 - (void) _effectiveBarTintColorDidChange;
 - (void) _setTabBarSizing:(q)a;
 - (void) _setTabButtonWidth:(d)a;
 - (d) _tabButtonWidth;
 - (void) _setInterTabButtonSpacing:(d)a;
 - (d) _interTabButtonSpacing;
 - (q) _barOrientation;
 - (BOOL) endCustomizingAnimated:(BOOL)a;
 - (void) _makeCurrentButtonFirstResponder;
 - (d) _nextSelectionSlideDuration;
 - (void) _setNextSelectionSlideDuration:(d)a;
 - (BOOL) _dividerImagesChangeWithSelection;
 - (void) _setDividerImagesChangeWithSelection:(BOOL)a;
 - (BOOL) _dividerImagesAreInvalid;
 - (void) _setDividerImagesAreInvalid:(BOOL)a;
 - (id) _dividerImageViews;
 - (void) _setDividerImageViews:(id)a;
 - (q) itemPositioning;
 - (void) setItemPositioning:(q)a;
 - (void) _tabBarFinishedAnimating;
 - (void) dismissCustomizeSheet:(BOOL)a;
 - (void) _alertWillShow:(BOOL)aduration:(f)b;
 - (void) _alertDidHide;
 - (void) _adjustButtonSelection:(id)a;
 - (void) _finishCustomizeAnimation:(id)a;
 - (void) _customizeDoneButtonAction:(id)a;
 - (void) _updateAppearanceCustomizationIfNecessaryForItem:(id)a;
 - (void) _configureItems:(id)a;
 - (BOOL) _isHidden:(id)a;
 - (BOOL) isElementAccessibilityExposedToInterfaceBuilder;
 - (d) _autolayoutSpacingAtEdge:(i)ainContainer:(id)b;
 - (d) _autolayoutSpacingAtEdge:(i)anextToNeighbor:(id)b;
 - (BOOL) _hasCustomAutolayoutNeighborSpacing;
 - (void) encodeWithCoder:(id)a;
 - (id) initWithCoder:(id)a;
 - (id) delegate;
 - (id) initWithFrame:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - (void) setFrame:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - (void) setBounds:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - (void) setAutoresizingMask:(Q)a;
 - (void) setItems:(id)a;
 - (void) drawRect:({CGRect={CGPoint=dd}{CGSize=dd}})a;


@end
