
@interface UITextRangeView : UIView {

    UITextSelectionView* m_selectionView;
    UIResponder<UITextInput>* m_container;
    int m_mode;
    NSArray* m_rects;
    NSMutableArray* m_rectViews;
    UITouch* m_activeTouch;
    {CGRect="origin"{CGPoint="x"d"y"d}"size"{CGSize="width"d"height"d}} m_startEdge;
    {CGRect="origin"{CGPoint="x"d"y"d}"size"{CGSize="width"d"height"d}} m_endEdge;
    {CGPoint="x"d"y"d} m_basePoint;
    {CGPoint="x"d"y"d} m_extentPoint;
    {CGPoint="x"d"y"d} m_initialBasePoint;
    {CGPoint="x"d"y"d} m_initialExtentPoint;
    double m_initialDistance;
    {CGPoint="x"d"y"d} m_touchOffset;
    double m_firstMovedTime;
    UISelectionGrabber* m_startGrabber;
    UISelectionGrabber* m_endGrabber;
    BOOL m_animateUpdate;
    BOOL m_baseIsStart;
    BOOL m_commandsWereShowing;
    BOOL m_inGesture;
    BOOL m_magnifying;
    BOOL m_scrolling;
    BOOL m_scaling;
    BOOL m_rotating;
    BOOL m_inputViewIsChanging;
}

 - (void) dealloc;
 - (id) container;
 - (void) setMode:(int)a ;
 - (BOOL) pointInside:({CGPoint=dd})a withEvent:(id)b ;
 - (void) touchesBegan:(id)a withEvent:(id)b ;
 - (void) touchesMoved:(id)a withEvent:(id)b ;
 - (void) touchesEnded:(id)a withEvent:(id)b ;
 - (void) touchesCancelled:(id)a withEvent:(id)b ;
 - (id) activeTouch;
 - (void) setActiveTouch:(id)a ;
 - (id) selectionView;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) _selectionClipRect;
 - (void) updateSelectionWithDocumentPoint:({CGPoint=dd})a ;
 - (void) stopAnimating;
 - (void) startAnimating;
 - (int) mode;
 - (void) willRotate;
 - (void) didRotate;
 - (void) setInGesture:(BOOL)a ;
 - (BOOL) inGesture;
 - (BOOL) autoscrolled;
 - (void) updateBaseIsStartWithDocumentPoint:({CGPoint=dd})a ;
 - (BOOL) baseIsStart;
 - (void) setBaseIsStart:(BOOL)a ;
 - (void) setAnimateUpdate:(BOOL)a ;
 - (id) startGrabber;
 - (id) endGrabber;
 - (void) updateBaseAndExtentPointsFromEdges;
 - ({CGPoint=dd}) extentPoint;
 - ({CGPoint=dd}) applyTouchOffset:({CGPoint=dd})a ;
 - (void) beginMagnifying;
 - (BOOL) commandsWereShowing;
 - ({CGPoint=dd}) magnifierPoint;
 - ({CGPoint=dd}) initialExtentPoint;
 - (void) willScroll;
 - (void) didScroll;
 - (void) inputViewWillChange;
 - (void) inputViewDidChange;
 - (void) setRects:(id)a ;
 - (void) updateDots;
 - (id) initWithFrame:({CGRect={CGPoint=dd}{CGSize=dd}})a selectionView:(id)b ;
 - (id) rects;
 - (void) prepareForMagnification;
 - (void) doneMagnifying;
 - (void) scaleWillChange;
 - (void) scaleDidChange;
 - (void) cancelDelayedActions;
 - (void) setIsScrolling:(BOOL)a ;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) startEdge;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) endEdge;
 - (BOOL) _endIsHorizontal;
 - (BOOL) _startIsHorizontal;
 - (void) setCommandsWereShowing:(BOOL)a ;
 - (void) updateEdges;
 - (BOOL) pointCloserToEnd:({CGPoint=dd})a startEdge:({CGRect={CGPoint=dd}{CGSize=dd}})b endEdge:({CGRect={CGPoint=dd}{CGSize=dd}})c ;
 - ({CGPoint=dd}) basePoint;
 - (void) setInitialBasePoint:({CGPoint=dd})a ;
 - (void) setInitialExtentPoint:({CGPoint=dd})a ;
 - ({CGPoint=dd}) initialBasePoint;
 - (void) setInitialDistance:(double)a ;
 - (void) setTouchOffset:({CGPoint=dd})a touchPoint:({CGPoint=dd})b ;
 - (void) setFirstMovedTime:(double)a ;
 - (void) setExtentPoint:({CGPoint=dd})a ;
 - (double) firstMovedTime;
 - (double) initialDistance;
 - (void) updateRectViews;
 - (void) updateGrabbers;
 - (void) setStartEdge:({CGRect={CGPoint=dd}{CGSize=dd}})a ;
 - (void) setEndEdge:({CGRect={CGPoint=dd}{CGSize=dd}})a ;
 - (void) setMagnifying:(BOOL)a ;
 - (void) setScaling:(BOOL)a ;
 - (void) setRotating:(BOOL)a ;
 - (void) setInputViewIsChanging:(BOOL)a ;
 - (void) setTouchOffset:({CGPoint=dd})a ;
 - ({CGPoint=dd}) touchOffset;
 - (void) setMagnifierOrientation;
 - (void) setBasePoint:({CGPoint=dd})a ;
 - ({CGPoint=dd}) convertFromMagnifierPoint:({CGPoint=dd})a ;
 - (void) setStartGrabber:(id)a ;
 - (void) setEndGrabber:(id)a ;
 - (BOOL) animateUpdate;
 - (BOOL) magnifying;
 - (BOOL) isScrolling;
 - (BOOL) scaling;
 - (BOOL) rotating;
 - (BOOL) inputViewIsChanging;
 - (void) removeFromSuperview;


@end
