
@protocol _UIShadowedView, _UIBackdropViewGraphicsQualityChangeDelegate, _UIBarPositioningInternal, UIBarPositioning;
@interface UIToolbar : UIView <_UIShadowedView, _UIBackdropViewGraphicsQualityChangeDelegate, _UIBarPositioningInternal, UIBarPositioning> {

    id _delegate;
    @"NSArray" _items;
    @"UIColor" _barTintColor;
    {?="barStyle"b3"mode"b2"wasEnabled"b1"downButtonSentAction"b1"barTranslucence"b3"isLocked"b1"backgroundLayoutNeedsUpdate"b1"hasCustomBackgroundView"b1} _toolbarFlags;
    ^{__CFDictionary=} _groups;
    @"NSArray" _buttonItems;
    q _currentButtonGroup;
    q _pressedTag;
    d _extraEdgeInsets;
    id _appearanceStorage;
    @"_UIBackdropView" _adaptiveBackdrop;
    @"UIImageView" _backgroundView;
    @"UIView" _shadowView;
    BOOL _isAdaptiveToolbarDisabled;
    BOOL _wantsLetterpressContent;
    BOOL _centerTextButtons;
    BOOL _collapsed;
    q _barPosition;
    @"NSString" _backdropViewLayerGroupName;
}
 + (d) defaultHeight;
 + (d) defaultHeightForBarSize:(i)a;
 + (Class) defaultButtonClass;
 + (Class) defaultTextButtonClass;
 + (id) defaultButtonFont;
 + (f) _buttonGap;
 + (d) defaultSelectionModeHeight;

 - (void) dealloc;
 - (void) setDelegate:(id)a;
 - (void) setMode:(i)a;
 - (void) _populateArchivedSubviews:(id)a;
 - (void) layoutSubviews;
 - (BOOL) _contentHuggingDefault_isUsuallyFixedHeight;
 - ({CGSize=dd}) sizeThatFits:({CGSize=dd})a;
 - (id) _backgroundView;
 - (void) setTranslatesAutoresizingMaskIntoConstraints:(BOOL)a;
 - (void) _setVisualAltitude:(d)a;
 - (void) _setVisualAltitudeBias:({CGSize=dd})a;
 - (BOOL) isTranslucent;
 - (id) scriptingInfoWithChildren;
 - (void) setCenter:({CGPoint=dd})a;
 - (void) invalidateIntrinsicContentSize;
 - (void) setTintColor:(id)a;
 - (void) _didMoveFromWindow:(id)atoWindow:(id)b;
 - ({CGSize=dd}) intrinsicContentSize;
 - (BOOL) _subclassImplementsDrawRect;
 - (BOOL) isMinibar;
 - (id) _shadowView;
 - (void) _setBackgroundView:(id)a;
 - (void) _setBackgroundImage:(id)amini:(id)b;
 - (void) _setButtonBackgroundImage:(id)amini:(id)bforStates:(Q)c;
 - (void) _updateBackgroundColor;
 - (id) _effectiveBarTintColor;
 - (void) _effectiveBarTintColorDidChangeWithPreviousColor:(id)a;
 - (void) _updateBackgroundImage;
 - ({CGSize=dd}) defaultSizeForOrientation:(q)a;
 - (void) _updateOpacity;
 - (BOOL) _wantsLetterpressContent;
 - (void) setItems:(id)aanimated:(BOOL)b;
 - (id) items;
 - (void) _setBarPosition:(q)a;
 - (void) addConstraint:(id)a;
 - (void) removeConstraint:(id)a;
 - (void) setBarStyle:(q)a;
 - (void) _customViewChangedForButtonItem:(id)a;
 - (q) barStyle;
 - (void) setTranslucent:(BOOL)a;
 - (void) setBarTintColor:(id)a;
 - (id) _currentCustomBackground;
 - (id) _currentCustomBackgroundRespectOversize_legacy:(^B)a;
 - (q) _barPosition;
 - (q) barPosition;
 - (void) _setBackdropViewLayerGroupName:(id)a;
 - (void) _setWantsLetterpressContent:(BOOL)a;
 - (BOOL) _hidesShadow;
 - (void) _setHidesShadow:(BOOL)a;
 - (id) barTintColor;
 - (id) _backdropViewLayerGroupName;
 - (void) _setShadowView:(id)a;
 - (id) backdropView:(id)awillChangeToGraphicsQuality:(q)b;
 - (void) backdropView:(id)adidChangeToGraphicsQuality:(q)b;
 - (id) _adaptiveBackdrop;
 - (void) _setLocked:(BOOL)a;
 - (id) backgroundImageForToolbarPosition:(q)abarMetrics:(q)b;
 - (void) _finishButtonAnimation:(i)aforButton:(i)b;
 - (BOOL) centerTextButtons;
 - (BOOL) _isInNavigationBar;
 - (void) setBarStyle:(q)aforce:(BOOL)b;
 - (void) _setBarTintColor:(id)aforce:(BOOL)b;
 - (void) _updateItemsForNewFrame:(id)a;
 - (id) _positionToolbarButtons:(id)aignoringItem:(id)bresetFontScaleAdjustment:(BOOL)cactuallyRepositionButtons:(BOOL)d;
 - (void) _positionToolbarButtons:(id)aignoringItem:(id)bresetFontScaleAdjustment:(BOOL)c;
 - (BOOL) _isTopBar_legacy;
 - (BOOL) _supportsAdaptiveBackground;
 - (Q) _subviewIndexAboveBackgroundView;
 - (void) _setAdaptiveToolbarDisabled:(BOOL)a;
 - (void) setExtraEdgeInsets:(d)a;
 - (d) extraEdgeInsets;
 - (i) mode;
 - (void) _sendAction:(id)awithEvent:(id)b;
 - (void) animateToolbarItemIndex:(Q)aduration:(d)btarget:(id)cdidFinishSelector:(SEL)d;
 - (void) setBackgroundImage:(id)aforToolbarPosition:(q)bbarMetrics:(q)c;
 - (void) setShadowImage:(id)aforToolbarPosition:(q)b;
 - (id) shadowImageForToolbarPosition:(q)a;
 - (BOOL) _isAdaptiveToolbarDisabled;
 - (void) setCenterTextButtons:(BOOL)a;
 - (BOOL) isCollapsed;
 - (void) setCollapsed:(BOOL)a;
 - (id) initInView:(id)awithFrame:({CGRect={CGPoint=dd}{CGSize=dd}})bwithItemList:(id)c;
 - (d) _edgeMarginForBorderedItem:(BOOL)aisText:(BOOL)b;
 - (void) _showButtons:(^i)awithCount:(i)bgroup:(i)cwithDuration:(d)dadjustPositions:(BOOL)eskipTag:(i)f;
 - (id) _currentButtons;
 - (void) _frameOrBoundsChangedWithVisibleSizeChange:(BOOL)awasMinibar:(BOOL)b;
 - (void) _frameOrCenterChanged;
 - (id) initInView:(id)awithItemList:(id)b;
 - (id) createButtonWithDescription:(id)a;
 - (void) positionButtons:(id)atags:(^i)bcount:(i)cgroup:(i)d;
 - (void) _buttonBarFinishedAnimating;
 - (void) showButtons:(^i)awithCount:(i)bwithDuration:(d)c;
 - (void) registerButtonGroup:(i)awithButtons:(^i)bwithCount:(i)c;
 - (void) showButtonGroup:(i)awithDuration:(d)b;
 - (i) currentButtonGroup;
 - (void) getVisibleButtonTags:(^i)acount:(^I)bmaxItems:(I)c;
 - (void) setButtonBarTrackingMode:(i)a;
 - (void) setBadgeValue:(id)aforButton:(i)b;
 - (void) setBadgeGlyph:(id)aforButton:(i)b;
 - (void) setBadgeAnimated:(BOOL)aforButton:(i)b;
 - (BOOL) onStateForButton:(i)a;
 - (void) setOnStateForButton:(BOOL)aforButton:(i)b;
 - (void) animateWithDuration:(f)aforButton:(i)b;
 - (id) buttonItems;
 - (void) setButtonItems:(id)a;
 - (void) _setForceTopBarAppearance:(BOOL)a;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) _frameOfBarButtonItem:(id)a;
 - (void) _layoutBackgroundViewConsideringStatusBar;
 - (void) _cleanupAdaptiveBackdrop;
 - (id) _repositionedItemsFromItems:(id)awithBarButtonFrames:(^@)bwithHitRects:(^@)cbuttonIndexes:(^@)dtextButtonIndexes:(^@)e;
 - (BOOL) _isLocked;
 - (id) _customToolbarAppearance;
 - (void) _buttonDownDelayed:(id)a;
 - (void) _adjustButtonPressed:(id)a;
 - (void) _buttonDown:(id)a;
 - (void) _buttonUp:(id)a;
 - (void) _buttonCancel:(id)a;
 - (id) _buttonWithDescription:(id)a;
 - (id) _descriptionForTag:(i)a;
 - (void) _updateScriptingInfo:(id)aview:(id)b;
 - (id) _buttonName:(id)awithType:(i)b;
 - (BOOL) isElementAccessibilityExposedToInterfaceBuilder;
 - (d) _autolayoutSpacingAtEdge:(i)ainContainer:(id)b;
 - (d) _autolayoutSpacingAtEdge:(i)anextToNeighbor:(id)b;
 - (BOOL) _hasCustomAutolayoutNeighborSpacing;
 - (void) encodeWithCoder:(id)a;
 - (id) initWithCoder:(id)a;
 - (id) delegate;
 - (id) initWithFrame:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - (void) setFrame:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - (void) setBounds:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - (void) setAutoresizingMask:(Q)a;
 - (void) setItems:(id)a;
 - (void) drawRect:({CGRect={CGPoint=dd}{CGSize=dd}})a;


@end
