
@protocol _UIScrollNotification, UITextEffectsOrdering, NSISVariableDelegate, NSLayoutItem, NSISEngineDelegate, _UITraitEnvironmentInternal, UIFocusContainer, NSCoding, UIAppearance, UIAppearanceContainer, UIDynamicItem, UITraitEnvironment, UICoordinateSpace;
@interface UIView : UIResponder <_UIScrollNotification, UITextEffectsOrdering, NSISVariableDelegate, NSLayoutItem, NSISEngineDelegate, _UITraitEnvironmentInternal, UIFocusContainer, NSCoding, UIAppearance, UIAppearanceContainer, UIDynamicItem, UITraitEnvironment, UICoordinateSpace> {

    CALayer* _layer;
    id _gestureInfo;
    NSMutableArray* _gestureRecognizers;
    NSArray* _subviewCache;
    float _charge;
    long long _tag;
    UIViewController* _viewDelegate;
    NSString* _backgroundColorSystemColorName;
    unsigned long long _countOfMotionEffectsInSubtree;
    unsigned long long _countOfTraitChangeRespondersInDirectSubtree;
    {?="userInteractionDisabled"b1"implementsDrawRect"b1"implementsDidScroll"b1"implementsMouseTracking"b1"implementsIntrinsicContentSize"b1"hasBackgroundColor"b1"isOpaque"b1"becomeFirstResponderWhenCapable"b1"interceptMouseEvent"b1"deallocating"b1"debugFlash"b1"debugSkippedSetNeedsDisplay"b1"debugScheduledDisplayIsRequired"b1"isInAWindow"b1"isAncestorOfFirstResponder"b1"dontAutoresizeSubviews"b1"autoresizeMask"b6"patternBackground"b1"fixedBackgroundPattern"b1"dontAnimate"b1"superLayerIsView"b1"layerKitPatternDrawing"b1"multipleTouchEnabled"b1"exclusiveTouch"b1"hasViewController"b1"needsDidAppearOrDisappear"b1"gesturesEnabled"b1"deliversTouchesForGesturesToSuperview"b1"chargeEnabled"b1"skipsSubviewEnumeration"b1"needsDisplayOnBoundsChange"b1"hasTiledLayer"b1"hasLargeContent"b1"unused"b1"traversalMark"b1"appearanceIsInvalid"b1"monitorsSubtree"b1"hostsAutolayoutEngine"b1"constraintsAreClean"b1"subviewLayoutConstraintsAreClean"b1"intrinsicContentSizeConstraintsAreClean"b1"potentiallyHasDanglyConstraints"b1"doesNotTranslateAutoresizingMaskIntoConstraints"b1"autolayoutIsClean"b1"layoutFlushingDisabled"b1"layingOutFromConstraints"b1"wantsAutolayout"b1"subviewWantsAutolayout"b1"isApplyingValuesFromEngine"b1"isInAutolayout"b1"isSubviewUpdatingAutoresizingConstraints"b1"isUpdatingConstraints"b1"isHostingUpdateConstraintsPassDuringLayout"b1"isRunningEngineLevelConstraintsPass"b1"isUnsatisfiableConstraintsLoggingSuspended"b1"systemLayoutFittingSizeNeedsUpdate"b1"systemLayoutFittingSizeNeedsUpdateInWholeSubtree"b1"isCalculatingSystemLayoutFittingSize"b1"stayHiddenAwaitingReuse"b1"stayHiddenAfterReuse"b1"skippedLayoutWhileHiddenForReuse"b1"hasMaskView"b1"hasVisualAltitude"b1"hasBackdropMaskViews"b1"backdropMaskViewFlags"b5"delaysTouchesForSystemGestures"b1"subclassShouldDelayTouchForSystemGestures"b1"hasMotionEffects"b1"backdropOverlayMode"b2"tintAdjustmentMode"b2"isReferenceView"b1"hasUserInterfaceIdiom"b1"userInterfaceIdiom"b3"ancestorDefinesTintColor"b1"ancestorDefinesTintAdjustmentMode"b1"needsTraitCollectionDidChange"b1"coloredViewBounds"b1"coloredAlignmentRects"b1"coloredHighlightItems"b1"preservesSuperviewMargins"b1"hasGeometryObservers"b1"wantsGeometryChanges"b1"hasTraitStorageList"b1"dontUpdateInferredLayoutMargins"b1} _viewFlags;
    long long _retainCount;
    long long _tintAdjustmentDimmingCount;
    BOOL _shouldArchiveUIAppearanceTags;
    UIColor* _interactionTintColor;
    NSISVariable* _minXVariable;
    NSISVariable* _minYVariable;
    NSISVariable* _boundsWidthVariable;
    NSISVariable* _boundsHeightVariable;
    NSISEngine* _layoutEngine;
    NSString* _layoutDebuggingIdentifier;
    NSMutableArray* _internalConstraints;
    NSArray* _constraintsExceptingSubviewAutoresizingConstraints;
    UIPresentationController* __presentationControllerToNotifyOnLayoutSubviews;
    {UIEdgeInsets="top"d"left"d"bottom"d"right"d} _rawLayoutMargins;
    {UIEdgeInsets="top"d"left"d"bottom"d"right"d} _inferredLayoutMargins;
}
 + (void) _performSystemAppearanceModifications:(@?)a;
 + (void) performWithoutAnimation:(@?)a;
 + (void) _performBlockwithAutomaticAppearanceDisabled:(@?)a;
 + (void) animateWithDuration:(double)adelay:(double)boptions:(unsigned long long)canimations:(@?)dcompletion:(@?)e;
 + (void) _beginSuspendingMotionEffectsForReason:(id)a;
 + (void) _endSuspendingMotionEffectsForReason:(id)a;
 + (BOOL) _shouldEnableUIKitDefaultParallaxEffects;
 + (id) _currentAnimationAttributes;
 + (void) animateWithDuration:(double)aanimations:(@?)bcompletion:(@?)c;
 + (BOOL) _isInAnimationBlock;
 + (double) _currentAnimationDuration;
 + (void) beginAnimations:(id)a;
 + (void) setAnimationBeginsFromCurrentState:(BOOL)a;
 + (void) endAnimations;
 + (void) _performWithoutAnimation:(@?)a;
 + (BOOL) _validateNewFocusCandidate:(id)afromCurrentFocusItem:(id)bheading:(unsigned long long)c;
 + (id) _defaultUIViewActionForLayer:(id)aforKey:(id)b;
 + (BOOL) _retroactivelyRequiresConstraintBasedLayout;
 + (void) setAnimationsEnabled:(BOOL)a;
 + (void) setAnimationCurve:(long long)a;
 + (void) setAnimationDelay:(double)a;
 + (double) _durationForRotationFromInterfaceOrientation:(long long)atoInterfaceOrientation:(long long)bwithBaseDuration:(double)c;
 + (int) _degreesToRotateFromInterfaceOrientation:(long long)atoInterfaceOrientation:(long long)b;
 + (void) beginAnimations:(id)acontext:(^v)b;
 + (void) setAnimationDidStopSelector:(SEL)a;
 + (void) setAnimationDelegate:(id)a;
 + (void) _setIsResponderAncestorOfFirstResponder:(BOOL)astartingAtFirstResponder:(id)b;
 + (id) _topMostView:(id)areverse:(BOOL)b;
 + (BOOL) _toolsDebugFocusItems;
 + (Class) layerClass;
 + (BOOL) _isAnimationTracking;
 + (void) _setAlongsideAnimations:(@?)a;
 + (void) _disableAnimationTracking:(id)aclearTrackedAnimations:(BOOL)b;
 + (@?) _alongsideAnimations;
 + (void) _setAnimationAttributes:(id)a;
 + (void) addKeyframeWithRelativeStartTime:(double)arelativeDuration:(double)banimations:(@?)c;
 + (void) _addHierarchyTrackingVisitor:(id)a;
 + (void) _removeHierarchyTrackingVisitor:(id)a;
 + (id) _appearanceWhenContainedIn:(id)a;
 + (BOOL) _tintColorUpdating;
 + (void) _setTintColorUpdating:(BOOL)a;
 + (id) _defaultInteractionTintColorForIdiom:(long long)a;
 + (BOOL) _motionEffectsSupported;
 + (BOOL) _motionEffectsEnabled;
 + (id) appearance;
 + (id) _appearanceRecorder;
 + (id) appearanceWhenContainedIn:(Class)a;
 + (id) _appearanceRecorderWhenContainedIn:(Class)a;
 + (id) appearanceMatchingProperties:(id)awhenContainedIn:(Class)b;
 + (id) appearanceForTraitCollection:(id)a;
 + (id) appearanceForTraitCollection:(id)awhenContainedIn:(Class)b;
 + (BOOL) _preventsAppearanceProxyCustomization;
 + (void) _setAnimatedPropertiesEnabled:(BOOL)a;
 + (id) _motionEffectEngine;
 + (void) _recenterMotionEffects;
 + (void) _setShouldEnableUIKitParallaxEffects:(BOOL)a;
 + (void) throttledFlush;
 + (BOOL) _hasActiveAnimationContext;
 + (void) _setAnimationAttributes:(id)askipDelegateAssignment:(BOOL)b;
 + (id) _enableAnimationTracking;
 + (id) _startAnimationTracking;
 + (void) _finishAnimationTracking;
 + (void) _completeAnimationWithUUID:(id)aduration:(double)bcurve:(long long)creverse:(BOOL)d;
 + (BOOL) areAnimationsEnabled;
 + (void) setAnimationRepeatAutoreverses:(BOOL)a;
 + (id) _defaultUIViewAnimationForLayer:(id)aforKey:(id)b;
 + (void) _animateWithAttributes:(id)aanimations:(@?)bcompletion:(@?)c;
 + (void) commitAnimations;
 + (long long) _currentAnimationCurve;
 + (void) setAnimationPosition:({CGPoint=dd})a;
 + (void) disableAnimation;
 + (void) enableAnimation;
 + (id) _performWithAnimationTracking:(@?)a;
 + (void) _disableAnimationTracking:(id)a;
 + (BOOL) _addCompletion:(@?)a;
 + (void) _reverseAnimationWithUUID:(id)aduration:(double)bcurve:(long long)c;
 + (void) _stopAnimationWithUUID:(id)a;
 + (void) _finalizeStoppedAnimationWithUUID:(id)areverseAnimation:(BOOL)b;
 + (void) _inheritAnimationParameters;
 + (void) setAnimationFrameInterval:(double)a;
 + (void) setAnimationStartDate:(id)a;
 + (void) setAnimationStartTime:(double)a;
 + (void) setAnimationPreventsAdditive:(BOOL)a;
 + (void) setAnimationRepeatCount:(float)a;
 + (void) setAnimationAutoreverses:(BOOL)a;
 + (void) setAnimationFromCurrentState:(BOOL)a;
 + (void) setAnimationRoundsToInteger:(BOOL)a;
 + (void) setAnimationTransition:(long long)aforView:(id)bcache:(BOOL)c;
 + (void) setAnimationWillStartSelector:(SEL)a;
 + (void) _setAnimationFilter:(int)aforView:(id)b;
 + (void) _setAnimationFilterValue:(float)a;
 + (double) _durationForRotationFromInterfaceOrientation:(long long)atoInterfaceOrientation:(long long)b;
 + (void) _setupAnimationWithDuration:(double)adelay:(double)bview:(id)coptions:(unsigned long long)dfactory:(id)eanimations:(@?)fstart:(@?)ganimationStateGenerator:(@?)hcompletion:(@?)i;
 + (void) animateWithDuration:(double)adelay:(double)busingSpringWithDamping:(double)cinitialSpringVelocity:(double)doptions:(unsigned long long)eanimations:(@?)fcompletion:(@?)g;
 + (void) _setupAnimationWithDuration:(double)adelay:(double)bview:(id)coptions:(unsigned long long)danimations:(@?)estart:(@?)fcompletion:(@?)g;
 + (void) _animateWithDuration:(double)adelay:(double)boptions:(unsigned long long)cfactory:(id)danimations:(@?)ecompletion:(@?)f;
 + (void) _animateWithDuration:(double)adelay:(double)boptions:(unsigned long long)canimations:(@?)dstart:(@?)ecompletion:(@?)f;
 + (void) animateWithDuration:(double)aanimations:(@?)b;
 + (void) transitionWithView:(id)aduration:(double)boptions:(unsigned long long)canimations:(@?)dcompletion:(@?)e;
 + (void) transitionFromView:(id)atoView:(id)bduration:(double)coptions:(unsigned long long)dcompletion:(@?)e;
 + (void) performSystemAnimation:(unsigned long long)aonViews:(id)boptions:(unsigned long long)canimations:(@?)dcompletion:(@?)e;
 + (void) animateKeyframesWithDuration:(double)adelay:(double)boptions:(unsigned long long)canimations:(@?)dcompletion:(@?)e;
 + (void) setAnimationTransition:(long long)aforView:(id)b;
 + (BOOL) requiresConstraintBasedLayout;
 + (void) _initializeForIdiom:(long long)a;
 + (void) _registerClassForIdiomInitializationIfNeccessary;
 + (void) _beginDisablingPromoteDescendantToFirstResponder;
 + (void) _endDisablingPromoteDescendantToFirstResponder;
 + (BOOL) _toolsDebugAlignmentRects;
 + (BOOL) _toolsDebugColorViewBounds;
 + (void) _animateUsingSpringWithDuration:(double)adelay:(double)boptions:(unsigned long long)cmass:(double)dstiffness:(double)edamping:(double)finitialVelocity:(double)ganimations:(@?)hstart:(@?)icompletion:(@?)j;
 + (void) _animateUsingDefaultDampedSpringWithDelay:(double)ainitialSpringVelocity:(double)boptions:(unsigned long long)canimations:(@?)dcompletion:(@?)e;
 + (void) _animateUsingSpringWithDuration:(double)adelay:(double)boptions:(unsigned long long)cmass:(double)dstiffness:(double)edamping:(double)finitialVelocity:(double)ganimations:(@?)hcompletion:(@?)i;
 + (void) _animateUsingDefaultDampedSpringWithDelay:(double)ainitialSpringVelocity:(double)boptions:(unsigned long long)canimations:(@?)dstart:(@?)ecompletion:(@?)f;
 + (id) _disabledColorForTintColor:(id)a;
 + (void) _setInvalidatesViewUponCreation:(BOOL)a;
 + (BOOL) _invalidatesViewUponCreation;
 + (void) _transitionFromView:(id)atoView:(id)bduration:(double)coptions:(unsigned long long)danimations:(@?)ecompletion:(@?)f;
 + (void) _performInitializationForIdiomIfNeccessary:(long long)a;
 + (BOOL) _isAddingResponderToTree;
 + (double) _durationOfSpringAnimationWithMass:(double)astiffness:(double)bdamping:(double)cvelocity:(double)d;
 + (void) _animateUsingDefaultTimingWithOptions:(unsigned long long)aanimations:(@?)bcompletion:(@?)c;
 + (id) _focusDescriptionOverview;
 + (id) _tintColorForStyle:(int)a;
 + (void) _enableToolsDebugFocusItems:(BOOL)a;
 + (id) _viewWithLayoutConstraints;
 + (void) _enableToolsDebugColorViewBounds:(BOOL)a;
 + (void) _enableToolsDebugAlignmentRects:(BOOL)a;
 + (void) flush;
 + (void) setAnimationDuration:(double)a;

 - (void) setFrameSize:({CGSize=dd})a ;
 - (void) setFrameOrigin:({CGPoint=dd})a ;
 - (void) setFrameX:(double)a ;
 - (void) setFrameEndX:(double)a y:(double)b ;
 - (void) setFrameY:(double)a ;
 - (void) setFrameWidth:(double)a ;
 - (void) setFrameHeight:(double)a ;
 - (id) artworkCatalog;
 - (void) clearArtworkCatalogs;
 - (id) mpFirstLabelSubview;
 - (void) mpPerformRecursiveBlock:(@?)a ;
 - (void) mpSetFrameOrigin:({CGPoint=dd})a ;
 - (void) mpSetFrameSize:({CGSize=dd})a ;
 - (id) mpAncestorViewController;
 - (id) _recursiveFindDescendantScrollViewAtPoint:({CGPoint=dd})a withEvent:(id)b ;
 - (id) _findDescendantViewAtPoint:({CGPoint=dd})a withEvent:(id)b ;
 - (void) _web_setSubviews:(id)a ;
 - (id) constraintsAffectingLayoutForAxis:(long long)a ;
 - ({CGPoint=dd}) position;
 - ({CGSize=dd}) size;
 - (void) nsis_valueOfVariable:(id)a didChangeInEngine:(id)b ;
 - (id) nsis_descriptionOfVariable:(id)a ;
 - (BOOL) nsis_shouldIntegralizeVariable:(id)a ;
 - (BOOL) nsis_valueOfVariableIsUserObservable:(id)a ;
 - (id) engine:(id)a markerForConstraintToBreakAmongConstraints:(id)b ;
 - (void) engine:(id)a willBreakConstraint:(id)b dueToMutuallyExclusiveConstraints:(id)c ;
 - (void) constraintsDidChangeInEngine:(id)a ;
 - (id) constraints;
 - (id) nsli_layoutEngine;
 - (BOOL) nsli_resolvedValue:(^d)a forSymbolicConstant:(id)b inConstraint:(id)c error:(^@)d ;
 - (id) nsli_superitem;
 - (id) nsli_description;
 - (BOOL) nsli_isFlipped;
 - (double) nsli_marginOffsetForAttribute:(long long)a ;
 - ({CGSize=dd}) nsli_convertSizeFromEngineSpace:({CGSize=dd})a ;
 - (void) nsli_addConstraint:(id)a ;
 - (BOOL) nsli_removeConstraint:(id)a ;
 - (id) _layoutEngine;
 - (unsigned long long) nsli_autoresizingMask;
 - (BOOL) nsli_lowerAttribute:(int)a intoExpression:(id)b withCoefficient:(double)c forConstraint:(id)d ;
 - (BOOL) nsli_lowerAttribute:(int)a intoExpression:(id)b withCoefficient:(double)c container:(id)d ;
 - (BOOL) nsli_descriptionIncludesPointer;
 - (id) description;
 - (id) retain;
 - (Vv) release;
 - (unsigned long long) retainCount;
 - (void) dealloc;
 - (BOOL) _tryRetain;
 - (BOOL) _isDeallocating;
 - (void) setValue:(id)a forKey:(id)b ;
 - (void) setNeedsDisplayOnBoundsChange:(BOOL)a ;
 - (void) setUserInteractionEnabled:(BOOL)a ;
 - (id) _screen;
 - (void) _populateArchivedSubviews:(id)a ;
 - (id) hitTest:({CGPoint=dd})a withEvent:(id)b ;
 - (BOOL) pointInside:({CGPoint=dd})a withEvent:(id)b ;
 - (void) setAlpha:(double)a ;
 - (void) didMoveToWindow;
 - ({CGSize=dd}) _intrinsicSizeWithinSize:({CGSize=dd})a ;
 - (void) bringSubviewToFront:(id)a ;
 - (void) layoutSubviews;
 - (void) setContentScaleFactor:(double)a ;
 - (void) insertSubview:(id)a atIndex:(long long)b ;
 - (void) setClipsSubviews:(BOOL)a ;
 - (void) sendSubviewToBack:(id)a ;
 - (BOOL) _canBeReusedInPickerView;
 - (id) _inheritedInteractionTintColor;
 - (void) _setInteractionTintColor:(id)a ;
 - (BOOL) _contentHuggingDefault_isUsuallyFixedHeight;
 - (BOOL) _contentHuggingDefault_isUsuallyFixedWidth;
 - ({CGSize=dd}) sizeThatFits:({CGSize=dd})a ;
 - (void) insertSubview:(id)a below:(id)b ;
 - (void) setClipsToBounds:(BOOL)a ;
 - (void) insertSubview:(id)a belowSubview:(id)b ;
 - (void) setContentMode:(long long)a ;
 - (void) addGestureRecognizer:(id)a ;
 - (void) removeGestureRecognizer:(id)a ;
 - (BOOL) gestureRecognizerShouldBegin:(id)a ;
 - (long long) _userInterfaceIdiom;
 - (id) _basicAnimationWithKeyPath:(id)a ;
 - (double) contentScaleFactor;
 - (BOOL) pointInside:({CGPoint=dd})a forEvent:(^{__GSEvent=})b ;
 - (void) setTranslatesAutoresizingMaskIntoConstraints:(BOOL)a ;
 - (id) snapshotViewAfterScreenUpdates:(BOOL)a ;
 - (void) addConstraints:(id)a ;
 - (double) _currentScreenScale;
 - (id) snapshotView;
 - (id) _viewDelegate;
 - (void) _recursivelyNameLayerTree;
 - (void) _setVisualAltitude:(double)a ;
 - (void) _setVisualAltitudeBias:({CGSize=dd})a ;
 - (id) gestureRecognizers;
 - (id) focusedView;
 - (void) setGestureRecognizers:(id)a ;
 - (void) updateUserActivityState:(id)a ;
 - (void) restoreUserActivityState:(id)a ;
 - (id) _viewControllerForAncestor;
 - (id) traitCollection;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) _responderExternalTouchRectForWindow:(id)a ;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) _responderSelectionRectForWindow:(id)a ;
 - (BOOL) isMultipleTouchEnabled;
 - (BOOL) _shouldApplyExclusiveTouch;
 - (id) _hitTest:({CGPoint=dd})a withEvent:(id)b windowServerHitTestWindow:(id)c ;
 - (id) preferredFocusedItem;
 - (BOOL) _mayRemainFocused;
 - (id) _deepestPreferredFocusView;
 - (BOOL) _allowsFocusToLeaveViaHeading:(unsigned long long)a ;
 - ({CGPoint=dd}) focusDirection;
 - (void) setFocusDirection:({CGPoint=dd})a ;
 - (void) _setMayRemainFocused:(BOOL)a ;
 - (void) _willChangeToIdiom:(long long)a onScreen:(id)b ;
 - ({UIEdgeInsets=dddd}) alignmentRectInsets;
 - (id) _scroller;
 - (BOOL) _shouldAnimatePropertyWithKey:(id)a ;
 - (id) _window;
 - (void) _dispatchTintColorVisitorWithReasons:(unsigned long long)a ;
 - (id) scriptingInfoWithChildren;
 - (BOOL) translatesAutoresizingMaskIntoConstraints;
 - (void) setNeedsPreferredFocusedItemUpdate;
 - (void) _recursivelySuspendMotionEffects;
 - (BOOL) _isFocusedOrAncestorOfFocusedView;
 - (void) _recursivelyReconsiderMotionEffectSuspension;
 - (double) _touchSloppinessFactor;
 - (BOOL) _isChargeEnabled;
 - (BOOL) _isAlphaHittableAndHasAlphaHittableAncestors;
 - (BOOL) _canHandleStatusBarTouchAtLocation:({CGPoint=dd})a ;
 - (BOOL) _isInVisibleHierarchy;
 - (id) _layer;
 - (double) _convertVisualAltitude:(double)a fromView:(id)b ;
 - (double) _convertVisualAltitude:(double)a toView:(id)b ;
 - (id) _rootForKeyResponderCycle;
 - ({CGPoint=dd}) frameOrigin;
 - (void) setCenter:({CGPoint=dd})a ;
 - (void) _setHostsLayoutEngine:(BOOL)a ;
 - (void) _setNeedsUpdateConstraints;
 - (void) _willChangeToIdiomOnScreen:(id)a traverseHierarchy:(BOOL)b ;
 - (void) _rebuildLayoutFromScratch;
 - (void) _recursivelyConsiderResumingMotionEffects;
 - (void) _didChangeFromIdiomOnScreen:(id)a traverseHierarchy:(BOOL)b ;
 - (void) _traitCollectionDidChangeFromOldCollection:(id)a toNewCollection:(id)b scaleDidChange:(BOOL)c ;
 - (void) _noteTraitsDidChangeRecursively;
 - (BOOL) cancelTouchTracking;
 - (void) gestureEnded:(^{__GSEvent=})a ;
 - (BOOL) cancelMouseTracking;
 - (BOOL) containsView:(id)a ;
 - (void) _focusedViewDidChange:(id)a ;
 - (id) _interactionTintColor;
 - (BOOL) isAncestorOfItem:(id)a ;
 - (BOOL) isDescendantOfView:(id)a ;
 - (void) _updateFocusItemOverlayViews;
 - (BOOL) _containedInAbsoluteResponderChain;
 - (id) _appearanceContainer;
 - (BOOL) _shouldDelayTouchForSystemGestures:(id)a ;
 - (id) _firstResponder;
 - (BOOL) _becomeFirstResponderWhenPossible;
 - (BOOL) _supportsBecomeFirstResponderWhenPossible;
 - (BOOL) _isInAWindow;
 - (id) _normalInheritedTintColor;
 - (void) _clearAnimationFilters;
 - (void) removeConstraints:(id)a ;
 - (BOOL) _isViewHierarchyPreparedForConstraint:(id)a ;
 - (BOOL) useBlockyMagnificationInClassic;
 - (id) _tintColorArchivingKey;
 - (void) setClearsContextBeforeDrawing:(BOOL)a ;
 - (void) _setPrimitiveContentHuggingPrioritiesValue:(id)a ;
 - (void) _setPrimitiveContentCompressionResistancePrioritiesValue:(id)a ;
 - (void) _encodeFrameWithCoder:(id)a ;
 - (id) _encodableSubviews;
 - (void) _encodeBackgroundColorWithCoder:(id)a ;
 - (BOOL) clearsContextBeforeDrawing;
 - (long long) contentMode;
 - (BOOL) clipsToBounds;
 - (id) _primitiveContentHuggingPrioritiesValue;
 - (id) _primitiveContentCompressionResistancePrioritiesValue;
 - (void) _discardLayoutEngine:(id)a ;
 - (void) _setMaskView:(id)a ;
 - (void) _invalidateSubviewCache;
 - (void) removeAllGestureRecognizers;
 - (void) _unregisterAllMotionEffects;
 - (void) _unregisterFromAnimators;
 - (BOOL) _shouldResignFirstResponderWithInteractionDisabled;
 - (void) _promoteSelfOrDescendantToFirstResponderIfNecessary;
 - (void) _collectKeyViews:(id)a ;
 - (long long) _topToBottomLeftToRightViewCompare:(id)a ;
 - (^{CGColor=}) _backgroundCGColor;
 - (BOOL) _canDrawContent;
 - (void) layoutMarginsDidChange;
 - (void) _setRawLayoutMargins:({UIEdgeInsets=dddd})a ;
 - (void) _updateInferredLayoutMargins;
 - (BOOL) preservesSuperviewLayoutMargins;
 - (void) _layoutMarginsDidChange;
 - (BOOL) _fakeShouldAnimatePropertyWithKey:(id)a ;
 - (void) _invalidateAppearanceForSubviewsOfClass:(Class)a ;
 - (void) _invalidateAppearanceForTraitCollection:(id)a ;
 - (void) invalidateIntrinsicContentSize;
 - (void) traitCollectionDidChange:(id)a ;
 - (id) _viewControllerToNotifyOnLayoutSubviews;
 - (void) _wrappedProcessDidChangeRecursivelyFromOldTraits:(id)a toCurrentTraits:(id)b scaleDidChange:(BOOL)c forceNotification:(BOOL)d ;
 - (void) _withUnsatisfiableConstraintsLoggingSuspendedIfEngineDelegateExists:(@?)a ;
 - (void) _receiveVisitor:(id)a ;
 - (void) forceDisplayIfNeeded;
 - (void) setInteractionTintColor:(id)a ;
 - (id) interactionTintColor;
 - (id) tintColor;
 - (long long) tintAdjustmentMode;
 - (long long) _defaultTintAdjustmentMode;
 - (void) setTintColor:(id)a ;
 - (id) __darkSystemColorForColor:(id)a ;
 - (BOOL) _hasNormalTintAdjustmentMode;
 - (double) _contentMargin;
 - (void) _setDrawsAsBackdropOverlayWithBlendMode:(long long)a ;
 - (id) _maskView;
 - (id) _backdropMaskViewForGrayscaleTint;
 - (id) _backdropMaskViewForColorTint;
 - (id) _backdropMaskViewForFilters;
 - (long long) _backdropMaskViewFlags;
 - (id) _generateBackdropMaskImage;
 - (void) _setBackdropMaskView:(id)a forFlag:(long long)b ;
 - (void) _setBackdropMaskViewForGrayscaleTint:(id)a ;
 - (void) _setBackdropMaskViewForColorTint:(id)a ;
 - (void) _setBackdropMaskViewForColorBurnTint:(id)a ;
 - (void) _setBackdropMaskViewForDarkeningTint:(id)a ;
 - (void) _setBackdropMaskViewForFilters:(id)a ;
 - (id) _backdropMaskViewForColorBurnTint;
 - (id) _backdropMaskViewForDarkeningTint;
 - (void) _setFrameForBackdropMaskViews:({CGRect={CGPoint=dd}{CGSize=dd}})a convertFrame:(BOOL)b ;
 - (id) _anyBackdropMaskView;
 - (void) _setCenterForBackdropMaskViews:({CGPoint=dd})a convertPoint:(BOOL)b ;
 - (void) _setHiddenForBackdropMaskViews:(BOOL)a ;
 - (void) _recursivelySetHiddenForBackdropMaskViews:(BOOL)a ;
 - (void) _updateBackdropMaskFrames;
 - (unsigned long long) _countOfMotionEffectsInSubtree;
 - (void) set_countOfMotionEffectsInSubtree:(unsigned long long)a ;
 - (BOOL) _isInHierarchyAllowingMotionEffects;
 - (void) _dispatchMotionEffectsVisitorWithDelta:(long long)a ;
 - (void) addMotionEffect:(id)a ;
 - (void) removeMotionEffect:(id)a ;
 - (id) motionEffects;
 - (void) _beginSuspendingMotionEffects;
 - (void) _endSuspendingMotionEffects;
 - (id) _parallaxMotionEffect;
 - (void) _removeMotionEffect:(id)a ;
 - (void) _addMotionEffect:(id)a ;
 - ({CGSize=dd}) _visualAltitudeBias;
 - (void) _updateParallaxEffectWithAltitude:(double)a bias:({CGSize=dd})b ;
 - (double) _visualAltitude;
 - (BOOL) canBecomeFirstResponder;
 - (void) _addPossibleRespondersToArray:(id)a ;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) convertRect:({CGRect={CGPoint=dd}{CGSize=dd}})a toCoordinateSpace:(id)b ;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) convertRect:({CGRect={CGPoint=dd}{CGSize=dd}})a fromCoordinateSpace:(id)b ;
 - (void) _constraints_frameDidChange;
 - (void) _setCenterForBackdropMaskViews:({CGPoint=dd})a ;
 - (BOOL) _shouldNotifyGeometryObservers;
 - (void) _notifyGeometryObserversWithChangeInfo:(id)a ;
 - (BOOL) _hostsLayoutEngine;
 - (void) _invalidateAutoresizingConstraints;
 - (id) _constraintsExceptingSubviewAutoresizingConstraints;
 - (void) _withAutomaticEngineOptimizationDisabled:(@?)a ;
 - (void) _reestablishConstraintsForTransformChange;
 - (void) _setTransformForBackdropMaskViews:({CGAffineTransform=dddddd})a ;
 - (void) _addGeometryChangeObserver:(id)a ;
 - (void) _removeGeometryChangeObserver:(id)a ;
 - (BOOL) _wantsGeometryChangeNotification;
 - (BOOL) _disableGeometryObserverNotification;
 - (void) _geometryChanges:(id)a forAncestor:(id)b ;
 - (id) resizableSnapshotViewFromRect:({CGRect={CGPoint=dd}{CGSize=dd}})a afterScreenUpdates:(BOOL)b withCapInsets:({UIEdgeInsets=dddd})c ;
 - (id) _imageFromRect:({CGRect={CGPoint=dd}{CGSize=dd}})a ;
 - (BOOL) _imageSnapshotCapturedAllContent;
 - (BOOL) _drawViewHierarchyInRect:({CGRect={CGPoint=dd}{CGSize=dd}})a ;
 - (BOOL) drawViewHierarchyInRect:({CGRect={CGPoint=dd}{CGSize=dd}})a afterScreenUpdates:(BOOL)b ;
 - (BOOL) shouldChangeFocusedItem:(id)a heading:(unsigned long long)b ;
 - (BOOL) _isFocusableElement;
 - (BOOL) isFocused;
 - (void) focusedViewWillChange;
 - (void) focusedViewDidChange;
 - (id) _firstCommonAncestorToView:(id)a ;
 - (BOOL) _shouldChangeFocusedItem:(id)a heading:(unsigned long long)b ;
 - (BOOL) isUserInteractionEnabled;
 - (BOOL) _isEligibleForFocus;
 - (BOOL) canBecomeFocused;
 - (void) _addPossibleFocusableElementsToArray:(id)a ;
 - (id) _traitCollectionForChildEnvironment:(id)a ;
 - ({CGPoint=dd}) convertPoint:({CGPoint=dd})a toCoordinateSpace:(id)b ;
 - ({CGPoint=dd}) convertPoint:({CGPoint=dd})a fromCoordinateSpace:(id)b ;
 - (id) _layoutDebuggingIdentifier;
 - (void) _setUnsatisfiableConstraintsLoggingSuspended:(BOOL)a ;
 - (BOOL) _isUnsatisfiableConstraintsLoggingSuspended;
 - (id) _contentWidthVariable;
 - (id) _contentHeightVariable;
 - (id) nsli_minXVariable;
 - (id) nsli_minYVariable;
 - (id) nsli_boundsWidthVariable;
 - (id) nsli_boundsHeightVariable;
 - (id) nsli_contentWidthVariable;
 - (id) nsli_contentHeightVariable;
 - (id) _constraintsArray;
 - (double) _baselineOffsetFromBottom;
 - (double) _firstBaselineOffsetFromTop;
 - (Class) _appearanceGuideClass;
 - (id) _appearanceTraitCollection;
 - (id) _traitStorageConstraints;
 - (void) _setTraitStorageConstraints:(id)a ;
 - (id) _traitStorageSubviews;
 - (void) _setTraitStorageSubviews:(id)a ;
 - (void) _createLayerWithFrame:({CGRect={CGPoint=dd}{CGSize=dd}})a ;
 - (void) _setChargeEnabled:(BOOL)a ;
 - (void) setTapDelegate:(id)a ;
 - (id) tapDelegate;
 - (id) _nextKeyResponder;
 - (id) _previousKeyResponder;
 - (void) _clearBecomeFirstResponderWhenCapable;
 - (BOOL) _canBecomeFirstResponderWhenPossible;
 - (void) startHeartbeat:(SEL)a inRunLoopMode:(id)b ;
 - (void) stopHeartbeat:(SEL)a ;
 - (BOOL) _hasOpaqueBackground;
 - (void) _setBackgroundColorSystemColorName:(id)a ;
 - (id) _backgroundColorSystemColorName;
 - (void) setLayoutMargins:({UIEdgeInsets=dddd})a ;
 - ({UIEdgeInsets=dddd}) layoutMargins;
 - (void) setPreservesSuperviewLayoutMargins:(BOOL)a ;
 - (BOOL) _appearanceIsInvalid;
 - (void) _setAppearanceIsInvalid:(BOOL)a ;
 - (void) _processDidChangeRecursivelyFromOldTraits:(id)a toCurrentTraits:(id)b forceNotification:(BOOL)c ;
 - (void) setTintAdjustmentMode:(long long)a ;
 - (long long) _primitiveTintAdjustmentMode;
 - (void) tintColorDidChange;
 - (void) interactionTintColorDidChange;
 - (void) _beginOcclusion:(id)a ;
 - (void) _endOcclusion:(id)a ;
 - (BOOL) _ancestorDefinesTintColor;
 - (void) _setAncestorDefinesTintColor:(BOOL)a ;
 - (BOOL) _ancestorDefinesTintAdjustmentMode;
 - (void) _setAncestorDefinesTintAdjustmentMode:(BOOL)a ;
 - (double) _textButtonMargin;
 - (double) _imageButtonMargin;
 - (BOOL) _drawsAsBackdropOverlay;
 - (void) _setDrawsAsBackdropOverlay:(BOOL)a ;
 - (void) setMaskView:(id)a ;
 - (id) maskView;
 - (void) _setBackdropMaskViewFlags:(long long)a ;
 - (id) _backdropMaskViews;
 - (id) _generateBackdropMaskViewForFlag:(long long)a ;
 - (id) _backdropMaskViewForFlag:(long long)a ;
 - (void) _removeBackdropMaskViews;
 - (void) _setFrameForBackdropMaskViews:({CGRect={CGPoint=dd}{CGSize=dd}})a ;
 - (void) _setBoundsForBackdropMaskViews:({CGRect={CGPoint=dd}{CGSize=dd}})a ;
 - (void) _updateBackdropMaskViewsInScrollView:(id)a ;
 - (id) _motionEffects;
 - (void) setMotionEffects:(id)a ;
 - (BOOL) _motionEffectsAreSuspended;
 - (BOOL) _applyKeyPathsAndRelativeValues:(id)a forMotionEffect:(id)b ;
 - (BOOL) _unapplyMotionEffect:(id)a ;
 - (long long) _currentUserInterfaceIdiom;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) _visualAltitudeSensitiveBoundsWithVisualAltitude:(double)a edges:(unsigned long long)b ;
 - (void) _removeParentGeometryObservers;
 - (void) _addParentGeometryObservers;
 - (void) _registerForGeometryChanges;
 - (void) _unregisterForGeometryChanges;
 - (void) _intrinsicContentSizeInvalidatedForChildView:(id)a ;
 - (id) snapshot;
 - (id) resizableSnapshotFromRect:({CGRect={CGPoint=dd}{CGSize=dd}})a withCapInsets:({UIEdgeInsets=dddd})b ;
 - (BOOL) drawViewHierarchyInRect:({CGRect={CGPoint=dd}{CGSize=dd}})a ;
 - (id) resizableSnapshotViewFromRect:({CGRect={CGPoint=dd}{CGSize=dd}})a withCapInsets:({UIEdgeInsets=dddd})b ;
 - (void) _focusedViewWillChange:(id)a ;
 - (BOOL) _transparentFocusContainer;
 - ({UIEdgeInsets=dddd}) _rawLayoutMargins;
 - ({UIEdgeInsets=dddd}) _inferredLayoutMargins;
 - (void) _setInferredLayoutMargins:({UIEdgeInsets=dddd})a ;
 - (id) _minXVariable;
 - (id) _minYVariable;
 - (id) _boundsWidthVariable;
 - (id) _boundsHeightVariable;
 - (void) _setLayoutEngine:(id)a ;
 - (void) _setLayoutDebuggingIdentifier:(id)a ;
 - (id) _internalConstraints;
 - (void) _setInternalConstraints:(id)a ;
 - (BOOL) _shouldArchiveUIAppearanceTags;
 - (void) _setShouldArchiveUIAppearanceTags:(BOOL)a ;
 - (void) setTag:(long long)a ;
 - (id) _presentationControllerToNotifyOnLayoutSubviews;
 - (void) _setPresentationControllerToNotifyOnLayoutSubviews:(id)a ;
 - (id) _gestureInfo;
 - (id) _gestureRecognizers;
 - (BOOL) _needsLayoutOnAnimatedFrameChangeForNewFrame:({CGRect={CGPoint=dd}{CGSize=dd}})a ;
 - (void) _is_setNeedsLayout;
 - (void) resizeSubviewsWithOldSize:({CGSize=dd})a ;
 - (void) layoutBelowIfNeeded;
 - (void) _notifyReferenceViewSizeChange;
 - (id) _interceptEvent:(id)a ;
 - (void) resizeWithOldSuperviewSize:({CGSize=dd})a ;
 - (unsigned long long) autoresizingMask;
 - (id) _layoutEngineCreateIfNecessary;
 - (void) _nsis_center:(^{CGPoint=dd})a bounds:(^{CGRect={CGPoint=dd}{CGSize=dd}})b inEngine:(id)c ;
 - (void) _nsis_origin:(^{CGPoint=dd})a bounds:(^{CGRect={CGPoint=dd}{CGSize=dd}})b inEngine:(id)c ;
 - (BOOL) _autoresizingConstraintsAreUpdated;
 - (void) _applyISEngineLayoutValues;
 - (void) _applyAutoresizingMaskWithOldSuperviewSize:({CGSize=dd})a ;
 - (void) _resizeWithOldSuperviewSize:({CGSize=dd})a ;
 - (void) _resizeWithOldSuperviewSize_ancient:({CGSize=dd})a ;
 - (BOOL) _needsLayoutOnAnimatedBoundsChangeForNewBounds:({CGRect={CGPoint=dd}{CGSize=dd}})a ;
 - (BOOL) _supportsContentDimensionVariables;
 - (BOOL) _isFloatingLayoutItem;
 - (void) setMultipleTouchEnabled:(BOOL)a ;
 - (void) setExclusiveTouch:(BOOL)a ;
 - (BOOL) isExclusiveTouch;
 - ({CGSize=dd}) convertSize:({CGSize=dd})a toView:(id)b ;
 - ({CGSize=dd}) convertSize:({CGSize=dd})a fromView:(id)b ;
 - ({CGPoint=dd}) _convertOffset:({CGPoint=dd})a toView:(id)b ;
 - ({CGPoint=dd}) _convertOffset:({CGPoint=dd})a fromView:(id)b ;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) hitRect;
 - (void) setFrame:({CGRect={CGPoint=dd}{CGSize=dd}})a forFields:(int)b ;
 - (void) setRotationBy:(float)a ;
 - (void) setAutoresizesSubviews:(BOOL)a ;
 - (BOOL) autoresizesSubviews;
 - (void) sizeToFit;
 - ({CGPoint=dd}) origin;
 - (void) setOrigin:({CGPoint=dd})a ;
 - (void) _setTraitStorageList:(id)a ;
 - (void) _addSubview:(id)a positioned:(long long)b relativeTo:(id)c ;
 - (void) _movedToFront;
 - (void) _setBackgroundCGColor:(^{CGColor=})a withSystemColorName:(id)b ;
 - (BOOL) viewTraversalMark;
 - (BOOL) _associatedViewControllerForwardsAppearanceCallbacks:(id)a performHierarchyCheck:(BOOL)b isRoot:(BOOL)c ;
 - (void) setViewTraversalMark:(BOOL)a ;
 - (void) _willMoveToWindow:(id)a ;
 - (void) willMoveToWindow:(id)a ;
 - (id) _findFirstSubviewWantingToBecomeFirstResponder;
 - (void) _makeSubtreePerformSelector:(SEL)a withObject:(id)b withObject:(id)c copySublayers:(BOOL)d ;
 - (void) _makeSubtreePerformSelector:(SEL)a withObject:(id)b ;
 - (void) deferredBecomeFirstResponder;
 - (void) _parentalLayoutEngineDidChangeTo:(id)a ;
 - (void) _didMoveFromWindow:(id)a toWindow:(id)b ;
 - (BOOL) _shouldTryPromoteDescendantToFirstResponder;
 - (void) movedFromSuperview:(id)a ;
 - (void) didMoveToSuperview;
 - (id) viewWithTag:(long long)a ;
 - (BOOL) _shouldDirtyLayoutForConstraints;
 - ({CGSize=dd}) _preferredLayoutEngineToUserScalingCoefficients;
 - (void) _switchToLayoutEngine:(id)a ;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) alignmentRectForFrame:({CGRect={CGPoint=dd}{CGSize=dd}})a ;
 - (void) _updateConstraintsAtEngineLevelIfNeeded;
 - (void) updateConstraintsIfNeeded;
 - (BOOL) _wantsAutolayout;
 - ({CGSize=dd}) systemLayoutSizeFittingSize:({CGSize=dd})a withHorizontalFittingPriority:(float)b verticalFittingPriority:(float)c ;
 - (void) _is_layout;
 - (void) _updateConstraintsAsNecessaryAndApplyLayoutFromEngine;
 - (void) _removeFirstResponderFromSubtree;
 - (void) _willRemoveSubviewWantingAutolayout:(id)a ;
 - (void) exchangeSubviewAtIndex:(long long)a withSubviewAtIndex:(long long)b ;
 - (void) insertSubview:(id)a aboveSubview:(id)b ;
 - (void) didAddSubview:(id)a ;
 - (void) willMoveToSuperview:(id)a ;
 - (void) _didRemoveSubview:(id)a ;
 - (void) _setBackgroundColor:(id)a ;
 - (id) _backgroundColor;
 - (void) _willMoveToWindow:(id)a withAncestorView:(id)b ;
 - (void) insertSubview:(id)a above:(id)b ;
 - (void) _postMovedFromSuperview:(id)a ;
 - (void) movedToSuperview:(id)a ;
 - (void) viewWillMoveToSuperview:(id)a ;
 - (void) viewDidMoveToSuperview;
 - (void) movedFromWindow:(id)a ;
 - (void) movedToWindow:(id)a ;
 - (void) _updateNeedsDisplayOnBoundsChange;
 - (void) setClearsContext:(BOOL)a ;
 - (void) _renderSnapshotWithRect:({CGRect={CGPoint=dd}{CGSize=dd}})a inContext:(^{CGContext=})b ;
 - (void) recursivelyForceDisplayIfNeeded;
 - (^v) _createImageFromRect:({CGRect={CGPoint=dd}{CGSize=dd}})a padding:({UIEdgeInsets=dddd})b ;
 - (void) _resetContentStretch;
 - (void) _setContentStretchInPixels:({CGRect={CGPoint=dd}{CGSize=dd}})a forContentSize:({CGSize=dd})b shouldTile:(BOOL)c ;
 - (void) setContentStretch:({CGRect={CGPoint=dd}{CGSize=dd}})a ;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) contentStretch;
 - (void) _setContentRectInPixels:({CGRect={CGPoint=dd}{CGSize=dd}})a forContentSize:({CGSize=dd})b ;
 - (void) _resetContentRect;
 - (void) _setShouldRasterize:(BOOL)a ;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) visibleBounds;
 - (void) setFixedBackgroundPattern:(BOOL)a ;
 - (void) _setHiddenForReuse:(BOOL)a ;
 - (BOOL) _isHiddenForReuse;
 - (void) setContentsPosition:(int)a ;
 - (^{CGImage=}) newSnapshotWithRect:({CGRect={CGPoint=dd}{CGSize=dd}})a ;
 - (void) _enableLayerKitPatternDrawing:(BOOL)a ;
 - (^v) _createIOSurfaceWithPadding:({UIEdgeInsets=dddd})a ;
 - (void) _removeAllAnimations:(BOOL)a ;
 - (BOOL) _isInTransitionBlock;
 - (void) _enumerateDescendentViews:(@?)a ;
 - (id) _interceptMouseEvent:(^{__GSEvent=})a ;
 - (id) hitTest:({CGPoint=dd})a forEvent:(^{__GSEvent=})b ;
 - (^{CGImage=}) createSnapshotWithRect:({CGRect={CGPoint=dd}{CGSize=dd}})a ;
 - ({CGSize=dd}) intrinsicContentSize;
 - (void) _setWantsAutolayout;
 - (void) _layoutEngine_windowDidChange;
 - (void) _informContainerThatSubviewsNeedUpdateConstraints;
 - (void) _applyAppearanceInvocations;
 - (void) _gestureEnded:(^{__GSEvent=})a ;
 - (void) _applyScreenScaleToContentScaleFactorIfNotSpecifiedByDeveloper;
 - (BOOL) _controlsOwnScaleFactor;
 - (BOOL) _shouldInheritScreenScaleAsContentScaleFactor;
 - (void) _willChangeToIdiom:(long long)a onScreen:(id)b traverseHierarchy:(BOOL)c ;
 - (void) _performUpdatesForPossibleChangesOfIdiom:(long long)a orScreen:(id)b traverseHierarchy:(BOOL)c ;
 - (void) _setUserInterfaceIdiom:(long long)a ;
 - (void) _didChangeFromIdiom:(long long)a onScreen:(id)b traverseHierarchy:(BOOL)c ;
 - (void) _subscribeToScrollNotificationsIfNecessary:(id)a ;
 - (void) _setIsAncestorOfFirstResponder:(BOOL)a ;
 - (BOOL) _isRootForKeyResponderCycle;
 - (void) _renderLayerContentsWithRect:({CGRect={CGPoint=dd}{CGSize=dd}})a inContext:(^{CGContext=})b ;
 - (^{CARenderServerBuffer=}) _createRenderServerBufferFromRect:({CGRect={CGPoint=dd}{CGSize=dd}})a padding:({UIEdgeInsets=dddd})b ;
 - (BOOL) _isAncestorOfFirstResponder;
 - (void) _constraints_subviewWillChangeSuperview:(id)a ;
 - (void) _descendent:(id)a willMoveFromSuperview:(id)b toSuperview:(id)c ;
 - (void) _unsubscribeToScrollNotificationsIfNecessary:(id)a ;
 - (void) _setSubviewWantsAutolayoutTripWantsAutolayout:(BOOL)a ;
 - (void) _descendent:(id)a didMoveFromSuperview:(id)b toSuperview:(id)c ;
 - (void) _constraints_subviewDidChangeSuperview:(id)a ;
 - (id) _alignmentDebuggingOverlayCreateIfNecessary:(BOOL)a ;
 - (void) _removeAlignmentDebuggingOverlays;
 - (id) _colorViewBoundsOverlayCreateIfNecessary:(BOOL)a ;
 - (void) _removeColorViewBoundsOverlays;
 - (id) _focusItemsOverlayCreateIfNecessary:(BOOL)a ;
 - (void) _removeFocusItemOverlayViews;
 - (BOOL) _allowsArchivingAsSubview;
 - (id) _viewIndexPath;
 - (BOOL) _appliesExclusiveTouchToSubviewTree;
 - (BOOL) _isInExclusiveTouchSubviewTree;
 - (id) _initWithLayer:(id)a ;
 - (id) _initWithMaskImage:(id)a ;
 - (BOOL) _subclassImplementsDrawRect;
 - (BOOL) _subclassImplementsIntrinsicContentSize;
 - (BOOL) _subclassImplementsIntrinsicSizeWithinSize;
 - (void) _didScroll;
 - (void) _invalidateLayerContents;
 - (void) _setInterceptMouseEvent:(BOOL)a ;
 - (void) _webCustomViewWasAddedAsSubviewOfView:(id)a ;
 - (void) _webCustomViewWillBeRemovedFromSuperview;
 - (void) _webCustomViewWasRemovedFromSuperview:(id)a ;
 - (BOOL) _alwaysHandleScrollerMouseEvent;
 - (BOOL) _alwaysHandleInteractionEvents;
 - (BOOL) _animationIsPaused;
 - (BOOL) _delaysTouchesForSystemGestures;
 - (void) _setDelaysTouchesForSystemGestures:(BOOL)a ;
 - (void) _clearBecomeFirstResponderWhenCapableOnSubtree;
 - (void) _setContentImage:(id)a ;
 - (void) _setContentsTransform:({CGAffineTransform=dddddd})a ;
 - (void) _renderLayerWithRect:({CGRect={CGPoint=dd}{CGSize=dd}})a inContext:(^{CGContext=})b ;
 - (BOOL) skipsSubviewEnumeration;
 - (void) setSkipsSubviewEnumeration:(BOOL)a ;
 - (void) _setViewDelegate:(id)a ;
 - (long long) _viewOrderRelativeToView:(id)a ;
 - (id) _subviewAtIndex:(long long)a ;
 - (id) _containingScrollView;
 - (BOOL) _monitorsSubtree;
 - (void) _setMonitorsSubtree:(BOOL)a ;
 - (void) _setBackgroundCGColor:(^{CGColor=})a ;
 - (void) _registerAsReferenceView;
 - (void) _unregisterAsReferenceView;
 - (BOOL) _isMemberOfViewControllerHierarchy:(id)a ;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) _visualAltitudeSensitiveBoundsWithInfiniteEdges:(unsigned long long)a ;
 - (id) _disabledColor;
 - (BOOL) _isInteractiveElement;
 - (BOOL) gesturesEnabled;
 - (void) setGesturesEnabled:(BOOL)a ;
 - (BOOL) deliversTouchesForGesturesToSuperview;
 - (void) setDeliversTouchesForGesturesToSuperview:(BOOL)a ;
 - (BOOL) _wantsReapplicationOfAutoLayout;
 - (id) _autoresizingDescription;
 - (id) _recursiveFocusDescription;
 - (id) _superDescription;
 - (id) recursiveDescription;
 - (id) _scriptingInfo;
 - (int) _style;
 - (int) _containerStyle;
 - (BOOL) _isScrollingEnabled;
 - (id) _enclosingScrollerIncludingSelf;
 - (id) _enclosingScrollableScrollerIncludingSelf;
 - (BOOL) _areAccessibilityButtonShapesEnabled;
 - (id) _layoutEngineIfAvailable;
 - ({CGSize=dd}) _nsis_contentSize;
 - (void) _layoutEngine_willRemoveLayoutConstraint:(id)a ;
 - (BOOL) _layoutEngine_didAddLayoutConstraint:(id)a roundingAdjustment:(double)b mutuallyExclusiveConstraints:(^@)c ;
 - ({CGSize=dd}) nsli_engineToUserScalingCoefficients;
 - (id) _layoutVariablesWithAmbiguousValue;
 - (float) _zoomAnimationDurationForScale:(double)a ;
 - (BOOL) _useContentDimensionVariablesForConstraintLowering;
 - (void) _prepareToAppearInNavigationItem:(id)a onLeft:(BOOL)b ;
 - (void) addConstraint:(id)a ;
 - (void) removeConstraint:(id)a ;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) frameForAlignmentRect:({CGRect={CGPoint=dd}{CGSize=dd}})a ;
 - (BOOL) needsUpdateConstraints;
 - (void) animator:(id)a stopAnimation:(id)b ;
 - (void) animator:(id)a startAnimation:(id)b ;
 - (id) textInputView;
 - (BOOL) endEditing:(BOOL)a ;
 - ({CGPoint=dd}) _nsis_origin;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) _nsis_bounds;
 - (void) updateConstraints;
 - ({CGSize=dd}) _systemLayoutSizeFittingSize:({CGSize=dd})a withHorizontalFittingPriority:(float)b verticalFittingPriority:(float)c ;
 - (void) gestureStarted:(^{__GSEvent=})a ;
 - (void) gestureChanged:(^{__GSEvent=})a ;
 - (id) viewForBaselineLayout;
 - (Class) _printFormatterClass;
 - (void) _setRenderConfig:(id)a ;
 - (int) textEffectsVisibilityLevel;
 - (id) _inheritedRenderConfig;
 - (int) _clipCornersOfView:(id)a ;
 - (void) _startGesture:(int)a event:(^{__GSEvent=})b ;
 - (void) _stopGesture:(int)a event:(^{__GSEvent=})b ;
 - (void) _zoomToWindowPoint:({CGPoint=dd})a scale:(double)b duration:(float)c constrainScrollPoint:(BOOL)d event:(^{__GSEvent=})e ;
 - (void) zoomToScale:(float)a ;
 - ({CGSize=dd}) _scrollerContentSize;
 - ({CGPoint=dd}) _constrainedScrollPoint:({CGPoint=dd})a contentSize:({CGSize=dd})b ;
 - (void) _gestureChanged:(int)a event:(^{__GSEvent=})b ;
 - ({CGPoint=dd}) _scrollPointForPoint:({CGPoint=dd})a scale:(float)b constrain:(BOOL)c snapToEdge:(BOOL)d ;
 - (void) _zoomToScrollPoint:({CGPoint=dd})a scale:(double)b duration:(float)c event:(^{__GSEvent=})d ;
 - (void) _zoomToScale:(float)a event:(^{__GSEvent=})b ;
 - (float) _minimumZoomScaleDelta;
 - (float) _internalScaleForScale:(float)a ;
 - (float) _rubberBandScaleForScale:(float)a ;
 - (float) _scaleForInternalScale:(float)a ;
 - (void) _zoomToEvent:(^{__GSEvent=})a scale:(float)b animate:(BOOL)c constrainScrollPoint:(BOOL)d ;
 - (BOOL) _canStartZoomFromEvent:(^{__GSEvent=})a ;
 - (void) _rubberbandZoomToEvent:(^{__GSEvent=})a scale:(float)b ;
 - (void) _animateToScrollPoint:({CGPoint=dd})a ;
 - (void) _setRotationAnimationProgress:(id)a ;
 - (void) rotateToDegrees:(float)a ;
 - (void) _rotateToDegrees:(float)a duration:(float)b event:(^{__GSEvent=})c ;
 - (BOOL) _canStartRotationFromEvent:(^{__GSEvent=})a ;
 - (void) _resetZoomingWithEvent:(^{__GSEvent=})a ;
 - (BOOL) _startZoomFromEvent:(^{__GSEvent=})a ;
 - (BOOL) _zoomWithEvent:(^{__GSEvent=})a ;
 - (BOOL) _startRotationFromEvent:(^{__GSEvent=})a ;
 - (void) _rotateFromEvent:(^{__GSEvent=})a ;
 - (void) _setGestureInfoZoomScale:(float)a ;
 - (BOOL) _isRubberBanding;
 - (void) _setZoomAnimationProgress:(id)a ;
 - (void) _stopZoomFromEvent:(^{__GSEvent=})a ;
 - (void) _stopRotationFromEvent:(^{__GSEvent=})a ;
 - (BOOL) canHandleGestures;
 - (void) setGestureDelegate:(id)a ;
 - (id) gestureDelegate;
 - (void) setEnabledGestures:(int)a ;
 - (int) enabledGestures;
 - (void) setValue:(id)a forGestureAttribute:(int)b ;
 - (id) valueForGestureAttribute:(int)a ;
 - (void) setRotationDegrees:(float)a duration:(double)b ;
 - (float) rotationDegrees;
 - (void) _setZoomScale:(float)a duration:(double)b ;
 - (float) _zoomScale;
 - (int) stateForGestureType:(int)a ;
 - (void) _animateZoomFailureToWindowPoint:({CGPoint=dd})a scale:(double)b duration:(float)c ;
 - (float) _zoomAnimationProgress;
 - (void) _invalidateIntrinsicContentSizeNeedingLayout:(BOOL)a ;
 - (BOOL) _needsDoubleUpdateConstraintsPass;
 - (BOOL) _hasLayoutEngine;
 - (id) _layoutDebuggingTitle;
 - (id) _rootInputWindowController;
 - (void) _resizeForKeyplaneSize:({CGSize=dd})a splitWidthsChanged:(BOOL)b ;
 - (void) reduceWidth:(double)a ;
 - (int) textEffectsVisibilityLevelInKeyboardWindow;
 - (void) setNeedsUpdateConstraints;
 - (id) _syntheticTouch;
 - (id) _syntheticUIEventWithGSEvent:(^{__GSEvent=})a touchPhase:(long long)b ;
 - ({CGSize=dd}) systemLayoutSizeFittingSize:({CGSize=dd})a ;
 - ({CGSize=dd}) _systemLayoutSizeFittingSize:({CGSize=dd})a withHorizontalFittingPriority:(float)b verticalFittingPriority:(float)c hasIntentionallyCollapsedHeight:(^B)d ;
 - (void) _setContentHuggingPriorities:({CGSize=dd})a ;
 - (float) contentHuggingPriorityForAxis:(long long)a ;
 - (void) setContentCompressionResistancePriority:(float)a forAxis:(long long)b ;
 - (float) contentCompressionResistancePriorityForAxis:(long long)a ;
 - (void) setContentHuggingPriority:(float)a forAxis:(long long)b ;
 - (long long) compareTextEffectsOrdering:(id)a ;
 - (int) _clipCorners;
 - (BOOL) isAccessibilityElementByDefault;
 - (BOOL) isElementAccessibilityExposedToInterfaceBuilder;
 - (long long) _depthFirstCompare:(id)a ;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) _compatibleBounds;
 - (BOOL) _lightStyleRenderConfig;
 - (void) drawRect:({CGRect={CGPoint=dd}{CGSize=dd}})a forViewPrintFormatter:(id)b ;
 - (id) viewPrintFormatter;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) _accessoryViewFrame;
 - (void) _setAccessoryViewFrame:({CGRect={CGPoint=dd}{CGSize=dd}})a ;
 - (void) _convertToAutolayoutSizingIfNecessary;
 - (void) _removeAutolayoutSizingConstraints;
 - (BOOL) _hasAutolayoutHeightConstraint;
 - (void) _constrainViewToSuperview;
 - (unsigned long long) _numberOfColumns:(BOOL)a ;
 - (void) _disableLayoutFlushing;
 - (void) _enableLayoutFlushing;
 - (BOOL) _forwardsSystemLayoutFittingSizeToContentView:(id)a ;
 - (id) _contentSizeConstraints;
 - (void) _initializeLayoutEngine;
 - (id) _descendantWithAmbiguousLayout;
 - (void) exerciseAmbiguityInLayout;
 - (id) _uiib_layoutEngineCreatingIfNecessary;
 - (BOOL) hasAmbiguousLayout;
 - (id) _defaultLayoutDescription;
 - (void) _initializeHostedLayoutEngine;
 - (void) _viewHierarchyUnpreparedForConstraint:(id)a ;
 - (void) _updateAutoresizingConstraints;
 - (void) _setPotentiallyHasDanglyConstraints:(BOOL)a ;
 - (BOOL) _tryToAddConstraintWithoutUpdatingConstraintsArray:(id)a roundingAdjustment:(double)b mutuallyExclusiveConstraints:(^@)c ;
 - (BOOL) _tryToAddConstraint:(id)a roundingAdjustment:(double)b mutuallyExclusiveConstraints:(^@)c ;
 - (void) _addConstraint:(id)a ;
 - (void) _removeConstraint:(id)a ;
 - (void) _withAutomaticEngineOptimizationDisabledIfEngineExists:(@?)a ;
 - (BOOL) _usesAutoresizingConstraints;
 - (void) _constraints_willChangeAutoresizingConstraintsArrayForContainedView:(id)a ;
 - (void) _constraints_didChangeAutoresizingConstraintsArrayForContainedView:(id)a ;
 - (BOOL) _usesLayoutEngineHostingConstraints;
 - (id) _layoutEngineHostConstraints;
 - (void) _setLayoutEngineHostConstraints:(id)a ;
 - (id) _autoresizingConstraints;
 - (void) _setAutoresizingConstraints:(id)a ;
 - (id) _constraintsEquivalentToAutoresizingMask;
 - (void) _oldUpdateLayoutEngineHostConstraints;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) _alignmentBounds;
 - (unsigned long long) _effectiveAutoresizingMask;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) _alignmentRectForBounds:({CGRect={CGPoint=dd}{CGSize=dd}})a ;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) _alignmentFrame;
 - (void) _constantsForHorizontalAutoresizingConstraints:(^d)a ;
 - (void) _constantsForVerticalAutoresizingConstraints:(^d)a ;
 - (void) _invalidateEngineHostConstraints;
 - (void) _engineHostConstraints_frameDidChange;
 - (void) _autoresizingConstraints_frameDidChange;
 - ({CGSize=dd}) _defaultContentHuggingPriorities;
 - ({CGSize=dd}) _contentHuggingPriorities;
 - ({CGSize=dd}) _defaultContentCompressionResistancePriorities;
 - ({CGSize=dd}) _contentCompressionResistancePriorities;
 - (void) _setContentCompressionResistancePriorities:({CGSize=dd})a ;
 - (id) _generateContentSizeConstraints;
 - (void) _setContentSizeConstraints:(id)a ;
 - (void) _updateContentSizeConstraints;
 - (void) _populateEngineWithConstraintsForViewSubtree:(id)a forComputingFittingSizeOfView:(id)b ;
 - (void) _recursiveCollectTemporaryInternalConstraintsWithEngine:(id)a ignoreAutoresizingMaskConstraints:(BOOL)b returningConstraintsForViewsNeedingSecondPass:(^@)c constraintsRemovedForFitting:(id)d constraintsAddedForFitting:(id)e ;
 - (void) _makeTemporaryInternalConstraintsWithEngine:(id)a ignoreAutoresizingMaskConstraints:(BOOL)b returningConstraintsForViewsNeedingSecondPass:(^@)c constraintsRemovedForFitting:(id)d constraintsAddedForFitting:(id)e ;
 - (void) _finishTemporaryInternalConstraints:(id)a withEngine:(id)b constraintsAddedForFitting:(id)c ;
 - (BOOL) _wantsBaselineUpdatingFollowingConstraintsPass;
 - (id) _descriptionForLayoutTrace;
 - (id) _legendEntryForDescriptionForLayout;
 - (BOOL) _uiib_tryToAddConstraint:(id)a roundingAdjustment:(double)b mutuallyExclusiveConstraints:(^@)c ;
 - (id) _constraintForIdentifier:(id)a ;
 - (void) _invalidateLayoutEngineHostConstraints;
 - (void) _constraints_viewGeometryDidChange;
 - (void) _effectiveAutoresizingMask_autoresizesSubviewsChanged;
 - (void) _uiib_invalidateAutoresizingConstraints;
 - (void) _updateLayoutEngineHostConstraints;
 - (id) _relevantLayoutVariables;
 - ({CGSize=dd}) _calculatedSystemLayoutSizeFittingSize:({CGSize=dd})a withHorizontalFittingPriority:(float)b verticalFittingPriority:(float)c hasIntentionallyCollapsedHeight:(^B)d ;
 - (id) _recursiveConstraintsTraceAtLevel:(long long)a ;
 - (id) _rootView;
 - (id) _recursiveAutolayoutTraceAtLevel:(long long)a ;
 - (id) _recursiveLayoutEngineDescription;
 - (void) _informContainerThatSubviewsNeedUpdateConstraintsNeedingLayout:(BOOL)a ;
 - (void) _invalidateSystemLayoutSizeFittingSizeAtEngineDelegateLevel;
 - (void) _setNeedsUpdateConstraintsNeedingLayout:(BOOL)a ;
 - (void) _accumulateViewConstraintsIntoArray:(id)a ;
 - (id) _constraintsBrokenWhileUnsatisfiableConstraintsLoggingSuspended;
 - (void) _updateConstraintsIfNeededAccumulatingViewsNeedingSecondPassAndViewsNeedingBaselineUpdate:(id)a ;
 - (void) _internalUpdateConstraintsIfNeededAccumulatingViewsNeedingSecondPassAndViewsNeedingBaselineUpdate:(id)a ;
 - (void) _updateConstraintsIfNeeded;
 - (BOOL) _is_needsLayout;
 - ({CGSize=dd}) nsli_engineToUserScalingCoefficientsInEngine:(id)a ;
 - (BOOL) _old_nsli_lowerAttribute:(int)a intoExpression:(id)b withCoefficient:(double)c forConstraint:(id)d ;
 - (id) _viewForBaselineLayout;
 - (id) _layoutDescriptionIfDifferentFromDefault;
 - (id) _constraintsValidityDescription;
 - (id) _autolayoutTrace;
 - (id) _allLayoutEngines;
 - (void) _applyISEngineLayoutToSubviewsSkippingSubview:(id)a ;
 - (BOOL) _potentiallyHasDanglyConstraints;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) _boundsForAlignmentRect:({CGRect={CGPoint=dd}{CGSize=dd}})a ;
 - (BOOL) _uiib_hostsLayoutEngine;
 - (void) _uiib_setHostsLayoutEngine:(BOOL)a ;
 - (void) _recordConstraintBrokenWhileUnsatisfiableConstraintsLoggingSuspended:(id)a ;
 - ({CGSize=dd}) nsli_convertSizeToEngineSpace:({CGSize=dd})a ;
 - (double) _autolayoutSpacingAtEdge:(int)a inContainer:(id)b ;
 - (double) _autolayoutSpacingAtEdge:(int)a nextToNeighbor:(id)b ;
 - (BOOL) _hasCustomAutolayoutNeighborSpacing;
 - (id) _hierarchyRepresentation;
 - (id) _representationOfHierarchyForXcode;
 - (void) _didAddDependentConstraint:(id)a ;
 - (void) _didRemoveDependentConstraint:(id)a ;
 - (id) _scrollViewWantingUpdateInConstraint:(id)a ;
 - (id) _centerExpressionInContainer:(id)a vertical:(BOOL)b contentInsetScale:(double)c ;
 - (id) _edgeExpressionInContainer:(id)a vertical:(BOOL)b max:(BOOL)c contentInsetScale:(double)d ;
 - (id) _dimensionExpressionInContainer:(id)a vertical:(BOOL)b useContentVariables:(BOOL)c ;
 - (void) _addCenterExpressionToExpression:(id)a isVertical:(BOOL)b ;
 - (id) _lowerExpressionOneLevelWithCurrentXExpression:(id)a YExpression:(id)b vertical:(BOOL)c container:(id)d ;
 - (id) init;
 - (void) encodeWithCoder:(id)a ;
 - (id) initWithCoder:(id)a ;
 - (id) window;
 - (id) superview;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) convertRect:({CGRect={CGPoint=dd}{CGSize=dd}})a toView:(id)b ;
 - (void) setSize:({CGSize=dd})a ;
 - (id) initWithSize:({CGSize=dd})a ;
 - (void) setBackgroundColor:(id)a ;
 - (void) removeFromSuperview;
 - (id) initWithFrame:({CGRect={CGPoint=dd}{CGSize=dd}})a ;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) frame;
 - (void) setFrame:({CGRect={CGPoint=dd}{CGSize=dd}})a ;
 - (double) alpha;
 - ({CGPoint=dd}) center;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) extent;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) bounds;
 - (void) setBounds:({CGRect={CGPoint=dd}{CGSize=dd}})a ;
 - (void) addAnimation:(id)a forKey:(id)b ;
 - (id) layer;
 - ({CGAffineTransform=dddddd}) transform;
 - (void) setTransform:({CGAffineTransform=dddddd})a ;
 - (void) setNeedsLayout;
 - (void) setNeedsDisplay;
 - (BOOL) needsDisplayOnBoundsChange;
 - (void) setPosition:({CGPoint=dd})a ;
 - (id) actionForLayer:(id)a forKey:(id)b ;
 - (void) setNeedsDisplayInRect:({CGRect={CGPoint=dd}{CGSize=dd}})a ;
 - (BOOL) needsDisplay;
 - (BOOL) isHidden;
 - (void) layoutIfNeeded;
 - (id) backgroundColor;
 - (BOOL) isOpaque;
 - (void) drawLayer:(id)a inContext:(^{CGContext=})b ;
 - (void) layoutSublayersOfLayer:(id)a ;
 - (long long) tag;
 - (void) setAutoresizingMask:(unsigned long long)a ;
 - (void) setHidden:(BOOL)a ;
 - ({CGPoint=dd}) convertPoint:({CGPoint=dd})a fromView:(id)b ;
 - (id) subviews;
 - (void) setOpaque:(BOOL)a ;
 - (void) addSubview:(id)a ;
 - (id) nextResponder;
 - (BOOL) becomeFirstResponder;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) convertRect:({CGRect={CGPoint=dd}{CGSize=dd}})a fromView:(id)b ;
 - ({CGPoint=dd}) convertPoint:({CGPoint=dd})a toView:(id)b ;
 - (void) drawRect:({CGRect={CGPoint=dd}{CGSize=dd}})a ;
 - (void) setFrameOrigin:({CGPoint=dd})a ;
 - (BOOL) isHiddenOrHasHiddenAncestor;
 - (void) willRemoveSubview:(id)a ;
 - (float) charge;
 - (void) setCharge:(float)a ;
 - (BOOL) isEnabled;
 - (void) setEnabled:(BOOL)a ;


@end
