
@protocol _UIViewServiceDeputy, NSExtensionRequestHandling, UIViewControllerPresenting, _UITraitEnvironmentInternal, _UIContentContainerInternal, UIFocusContainer, NSCoding, UIAppearanceContainer, UITraitEnvironment, UIContentContainer;
@interface UIViewController : UIResponder <_UIViewServiceDeputy, NSExtensionRequestHandling, UIViewControllerPresenting, _UITraitEnvironmentInternal, _UIContentContainerInternal, UIFocusContainer, NSCoding, UIAppearanceContainer, UITraitEnvironment, UIContentContainer> {

    UIView* _view;
    UITabBarItem* _tabBarItem;
    UINavigationItem* _navigationItem;
    NSArray* _toolbarItems;
    NSString* _title;
    NSString* _nibName;
    NSBundle* _nibBundle;
    UIViewController* _parentViewController;
    UIViewController* _childModalViewController;
    UIViewController* _parentModalViewController;
    UIViewController* _previousRootViewController;
    UIView* _modalTransitionView;
    UIResponder* _modalPreservedFirstResponder;
    id _dimmingView;
    id _dropShadowView;
    id _currentAction;
    UIStoryboard* _storyboard;
    NSArray* _storyboardSegueTemplates;
    NSDictionary* _externalObjectsTableForViewLoading;
    NSArray* _topLevelObjectsToKeepAliveFromStoryboard;
    UIView* _savedHeaderSuperview;
    UIView* _savedFooterSuperview;
    UIBarButtonItem* _editButtonItem;
    UISearchDisplayController* _searchDisplayController;
    long long _modalTransitionStyle;
    long long _modalPresentationStyle;
    long long _lastKnownInterfaceOrientation;
    UIPopoverController* _popoverController;
    UIView* _containerViewInSheet;
    {CGSize="width"d"height"d} _contentSizeForViewInPopover;
    {CGSize="width"d"height"d} _formSheetSize;
    UIScrollView* _recordedContentScrollView;
    @? _afterAppearance;
    long long _explicitAppearanceTransitionLevel;
    NSArray* _keyCommands;
    NSMapTable* _overrideTraitCollections;
    {?="appearState"b2"isEditing"b1"isPerformingModalTransition"b1"hidesBottomBarWhenPushed"b1"autoresizesArchivedViewToFullSize"b1"viewLoadedFromControllerNib"b1"isRootViewController"b1"customizesForPresentationInPopover"b1"isSuspended"b1"wasApplicationFrameAtSuspend"b1"wantsFullScreenLayout"b1"shouldUseFullScreenLayout"b1"allowsAutorotation"b1"searchControllerRetained"b1"oldModalInPopover"b1"isModalInPopover"b1"isInWillRotateCallback"b1"disallowMixedOrientationPresentations"b1"isFinishingModalTransition"b1"definesPresentationContext"b1"providesPresentationContextTransitionStyle"b1"containmentSupport"b1"isSettingAppearState"b1"isInAnimatedVCTransition"b1"presentationIsChanging"b1"isBeingPresented"b1"containmentIsChanging"b1"explicitTransitionIsAppearing"b1"disableAppearanceTransitions"b1"needsDidMoveCleanup"b1"suppressesBottomBar"b1"disableRootPromotion"b1"interfaceOrientationReentranceGuard"b1"isExecutingAfterAppearance"b1"rootResignationNeeded"b1"shouldSynthesizeSupportedOrientations"b1"viewConstraintsNeedUpdateOnAppearance"b1"shouldForceNonAnimatedTransition"b1"isInCustomTransition"b1"usesSharedView"b1"extendedLayoutIncludesOpaqueBars"b1"automaticallyAdjustInsets"b1"previousShouldUnderlapUnderStatusBar"b1"freezeShouldUnderlapUnderStatusBar"b1"neverResizeRoot"b1"monitorsSystemLayoutFittingSize"b1} _viewControllerFlags;
    long long _retainCount;
    BOOL _ignoreAppSupportedOrientations;
    BOOL _viewHostsLayoutEngine;
    NSString* _storyboardIdentifier;
    <UIViewControllerTransitioningDelegate>* _transitioningDelegate;
    BOOL _modalPresentationCapturesStatusBarAppearance;
    NSMutableArray* _childViewControllers;
    double _customNavigationInteractiveTransitionDuration;
    double _customNavigationInteractiveTransitionPercentComplete;
    UITransitionView* _customTransitioningView;
    UITraitCollection* _lastNotifiedTraitCollection;
    UIPresentationController* _presentationController;
    double _navigationControllerContentOffsetAdjustment;
    double _contentMargin;
    _UILayoutGuide* _topLayoutGuide;
    _UILayoutGuide* _bottomLayoutGuide;
    NSLayoutConstraint* _topBarInsetGuideConstraint;
    NSLayoutConstraint* _bottomBarInsetGuideConstraint;
    _UILayoutGuide* _leftLayoutGuide;
    _UILayoutGuide* _rightLayoutGuide;
    NSLayoutConstraint* _leftMarginGuideConstraint;
    NSLayoutConstraint* _rightMarginGuideConstraint;
    UIViewController* _sourceViewControllerIfPresentedViaPopoverSegue;
    UIViewController* _modalSourceViewController;
    UIViewController* _presentedStatusBarViewController;
    unsigned long long _edgesForExtendedLayout;
    UIView* __embeddedView;
    UIView* __embeddingView;
    <_UIViewControllerContentViewEmbedding>* __embeddedDelegate;
    UIPresentationController* _originalPresentationController;
    UIPresentationController* _temporaryPresentationController;
    UIViewController* __childControllerToIgnoreWhileLookingForTransitionCoordinator;
    {CGSize="width"d"height"d} _preferredContentSize;
    {?="width"q"height"q} _presentationSizeClassPair;
    {UIEdgeInsets="top"d"left"d"bottom"d"right"d} _navigationControllerContentInsetAdjustment;
    {UIEdgeInsets="top"d"left"d"bottom"d"right"d} _contentOverlayInsets;
    {CGRect="origin"{CGPoint="x"d"y"d}"size"{CGSize="width"d"height"d}} __embeddedViewFrame;
}
 + (void) _beginAppearanceTransitionFromViewController:(id)atoViewController:(id)banimated:(BOOL)c;
 + (void) _endAppearanceTransitionFromViewController:(id)atoViewController:(id)b;
 + (void) initialize;
 + (id) _currentStatusBarStyleViewController;
 + (id) _currentStatusBarHiddenViewController;
 + (void) _performWithoutDeferringTransitions:(@?)a;
 + (void) _traverseViewControllerHierarchyWithDelayedRelease:(@?)a;
 + (id) viewControllerForView:(id)a;
 + (id) _viewControllerForFullScreenPresentationFromView:(id)a;
 + (BOOL) _allViewControllersInArray:(id)aallowAutorotationToInterfaceOrientation:(long long)bpredicate:(@?)c;
 + (double) _slimHorizontalContentMargin;
 + (BOOL) _preventsAppearanceProxyCustomization;
 + (double) durationForTransition:(int)a;
 + (double) _standardHorizontalContentMargin;
 + (void) _scheduleTransition:(@?)a;
 + (id) _traitCollectionWithParentTraitCollection:(id)aoverrideTraitCollection:(id)b;
 + (BOOL) _directlySetsContentOverlayInsetsForChildren;
 + (BOOL) doesOverrideViewControllerMethod:(SEL)ainBaseClass:(Class)b;
 + ({CGSize=dd}) defaultFormSheetSize;
 + (BOOL) doesOverrideSupportedInterfaceOrientations;
 + (BOOL) _isNestedViewControllerSupportDisabled;
 + (BOOL) _synthesizeSupportedInterfaceOrientationsFromShouldAutorotateToInterfaceOrientation;
 + (BOOL) _frameIsNotResizedForDoubleHeightStatusBarChanges:(id)a;
 + (void) setViewController:(id)aforView:(id)b;
 + (id) existingNibNameMatchingClassName:(id)abundle:(id)b;
 + (BOOL) _doesOverrideLegacyFullScreenLayout;
 + (BOOL) _isViewSizeFullScreen:(id)ainWindow:(id)bignoreInWindowCheck:(BOOL)c;
 + (BOOL) doesOverrideViewControllerMethod:(SEL)a;
 + (BOOL) _shouldUseRootViewControllerAutopromotion;
 + (void) _traverseViewControllerHierarchyWithDelayedReleaseArray:(r^^v)ablock:(@?)b;
 + (void) _traverseViewControllerHierarchy:(@?)a;
 + (id) _printHierarchy;
 + (BOOL) _shouldUseLegacyModalViewControllers;
 + (BOOL) _isViewSizeFullScreen:(id)ainWindow:(id)b;
 + (int) _keyboardDirectionForTransition:(int)a;
 + (BOOL) _shouldDeferTransitions;
 + (void) _setShouldDeferTransitions:(BOOL)a;
 + (BOOL) _shouldSendLegacyMethodsFromViewWillTransitionToSize;
 + (BOOL) _shouldForwardViewWillTransitionToSize;
 + (BOOL) doesOverridePreferredInterfaceOrientationForPresentation;
 + (BOOL) _doesOverrideLegacyShouldAutorotateMethod;
 + (void) _forceLegacyModalViewControllers:(BOOL)a;
 + (void) _disableNestedViewControllerSupport:(BOOL)a;
 + (void) removeViewControllerForView:(id)a;
 + (id) _allDescriptions;
 + (BOOL) _optsOutOfPopoverControllerHierarchyCheck;
 + (void) _setShouldUseLegacyPresentations:(BOOL)a;
 + (void) setCustomTransitionDuration:(double)a;
 + (double) customTransitionDuration;
 + (void) attemptRotationToDeviceOrientation;
 + (id) _exportedInterface;
 + (id) _remoteViewControllerInterface;
 + (id) XPCInterface;
 + (BOOL) _isSecureForRemoteViewService;
 + (BOOL) _initializedByViewServices;

 - (id) aggregateStatisticsDisplayCountKey;
 - (void) setAggregateStatisticsDisplayCountKey:(id)a;
 - (void) _addChildViewAndViewController:(id)a;
 - (void) _removeFromParentViewAndViewController;
 - (void) _addChildViewAndViewController:(id)aasSubviewOfView:(id)b;
 - (BOOL) _hasAncestorViewController:(id)a;
 - (void) _addChildViewAndViewController:(id)aasSubviewOfView:(id)baddSubviewBlock:(@?)c;
 - (void) dismissMoviePlayerViewControllerAnimated;
 - (void) presentMoviePlayerViewControllerAnimated:(id)a;
 - (@?) _completionBlock;
 - (id) title;
 - (void) setTitle:(id)a;
 - (id) retain;
 - (Vv) release;
 - (unsigned long long) retainCount;
 - (void) dealloc;
 - (BOOL) _tryRetain;
 - (BOOL) _isDeallocating;
 - (id) invalidate;
 - (id) _screen;
 - (void) _setInCustomTransition:(BOOL)a;
 - (BOOL) isViewLoaded;
 - (id) searchDisplayController;
 - (id) navigationItem;
 - (void) applicationWillSuspend;
 - (BOOL) _tryBecomeRootViewControllerInWindow:(id)a;
 - (id) _preferredStatusBarStyleAnimationParameters;
 - (id) _preferredStatusBarHideAnimationParameters;
 - (long long) preferredStatusBarStyle;
 - (BOOL) prefersStatusBarHidden;
 - (long long) preferredStatusBarUpdateAnimation;
 - (id) presentingViewController;
 - (BOOL) _isRootViewController;
 - (id) parentViewController;
 - (void) didReceiveMemoryWarning;
 - (id) focusedView;
 - (id) _deepestUnambiguousResponder;
 - (id) _activityContinuationSuitableToBecomeCurrent;
 - (void) updateUserActivityState:(id)a;
 - (void) restoreUserActivityState:(id)a;
 - (void) applicationDidResume;
 - (id) _viewControllerForSupportedInterfaceOrientations;
 - (BOOL) shouldAutorotate;
 - (unsigned long long) supportedInterfaceOrientations;
 - (id) extensionContext;
 - (id) traitCollection;
 - (void) encodeRestorableStateWithCoder:(id)a;
 - (void) applicationFinishedRestoringState;
 - (BOOL) _shouldLoadViewDuringRestoration:(id)a;
 - (@?) _decodeRestorableStateAndReturnContinuationWithCoder:(id)a;
 - (void) setView:(id)a;
 - (void) _executeAfterAppearanceBlock;
 - (id) preferredFocusedItem;
 - (void) _willChangeToIdiom:(long long)aonScreen:(id)b;
 - (id) _window;
 - (void) awakeFromNib;
 - (BOOL) wantsFullScreenLayout;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) _defaultInitialViewFrame;
 - (BOOL) _isPresentingInWindow:(id)a;
 - (void) setNeedsPreferredFocusedItemUpdate;
 - (long long) _preferredInterfaceOrientationGivenCurrentOrientation:(long long)a;
 - (id) _existingView;
 - (long long) _lastKnownInterfaceOrientation;
 - (void) setDisableRootPromotion:(BOOL)a;
 - (void) __willChangeToIdiom:(long long)aonScreen:(id)b;
 - (void) setNeedsStatusBarAppearanceUpdate;
 - (BOOL) shouldWindowUseOnePartInterfaceRotationAnimation:(id)a;
 - (id) _viewControllerForRotation;
 - (id) _viewControllersForRotationCallbacks;
 - (BOOL) window:(id)ashouldAutorotateToInterfaceOrientation:(long long)b;
 - (id) _viewControllerForSupportedInterfaceOrientationsWithDismissCheck:(BOOL)a;
 - (id) _viewControllersWhoseOrientationsMustCoincide;
 - (BOOL) __withSupportedInterfaceOrientation:(long long)aapply:(@?)b;
 - (id) _transitionCoordinator;
 - (void) _window:(id)aviewWillTransitionToSize:({CGSize=dd})bwithTransitionCoordinator:(id)c;
 - (void) window:(id)asetupWithInterfaceOrientation:(long long)b;
 - (BOOL) _isViewControllerInWindowHierarchy;
 - (void) _updateLastKnownInterfaceOrientationOnPresentionStack:(long long)a;
 - (id) presentedViewController;
 - (long long) modalPresentationStyle;
 - (void) window:(id)awillRotateToInterfaceOrientation:(long long)bduration:(double)c;
 - (id) rotatingContentViewForWindow:(id)a;
 - ({CGPoint=dd}) _centerForOrientation:(long long)a;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) _boundsForOrientation:(long long)a;
 - (void) window:(id)awillAnimateRotationToInterfaceOrientation:(long long)bduration:(double)c;
 - (void) window:(id)adidRotateFromInterfaceOrientation:(long long)b;
 - (id) viewControllerForRotation;
 - (void) window:(id)awillAnimateFirstHalfOfRotationToInterfaceOrientation:(long long)bduration:(double)c;
 - (void) window:(id)adidAnimateFirstHalfOfRotationToInterfaceOrientation:(long long)b;
 - (void) window:(id)awillAnimateSecondHalfOfRotationFromInterfaceOrientation:(long long)bduration:(double)c;
 - (void) window:(id)astatusBarWillChangeFromHeight:(double)btoHeight:(double)c;
 - (void) window:(id)awillAnimateFromContentFrame:({CGRect={CGPoint=dd}{CGSize=dd}})btoContentFrame:({CGRect={CGPoint=dd}{CGSize=dd}})c;
 - (BOOL) isInWillRotateCallback;
 - (void) _parent:(id)awillTransitionToTraitCollection:(id)bwithTransitionCoordinator:(id)c;
 - (void) _window:(id)awillTransitionToTraitCollection:(id)bwithTransitionCoordinator:(id)c;
 - (BOOL) _canBecomeDeepestUnambiguousResponder;
 - (BOOL) isBeingDismissed;
 - (BOOL) isAncestorOfItem:(id)a;
 - (id) _appearanceContainer;
 - ({?=qq}) __sizeClassPair;
 - (id) _firstResponder;
 - (void) traitCollectionDidChange:(id)a;
 - (double) _contentMargin;
 - (BOOL) shouldChangeFocusedItem:(id)aheading:(unsigned long long)b;
 - (void) focusedViewWillChange;
 - (void) focusedViewDidChange;
 - (id) _traitCollectionForChildEnvironment:(id)a;
 - (id) _appearanceGuideClass;
 - (BOOL) _forwardAppearanceMethods;
 - (int) _appearState;
 - (BOOL) inExplicitAppearanceTransition;
 - (id) _parentModalViewController;
 - (BOOL) isPerformingModalTransition;
 - (void) setInAnimatedVCTransition:(BOOL)a;
 - (void) viewWillMoveToWindow:(id)a;
 - (id) _parentContentContainer;
 - (id) _previousFittingSizeInfo;
 - (BOOL) _monitorsSystemLayoutFittingSize;
 - (void) _systemLayoutFittingSizeDidChangeForChildContentContainer:(id)achildViewController:(id)b;
 - (void) _setPreviousFittingSizeInfo:(id)a;
 - (void) beginAppearanceTransition:(BOOL)aanimated:(BOOL)b;
 - (void) endAppearanceTransition;
 - (void) viewDidMoveToWindow:(id)ashouldAppearOrDisappear:(BOOL)b;
 - (BOOL) _isMemberOfViewControllerHierarchy:(id)a;
 - (id) _lastNotifiedTraitCollection;
 - (void) _updateTraitsIfNecessary;
 - (void) _updateContentOverlayInsetsFromParentIfNecessary;
 - (void) viewWillLayoutSubviews;
 - (id) _embeddedDelegate;
 - (void) viewDidLayoutSubviews;
 - (BOOL) isInAnimatedVCTransition;
 - (id) _barBackdropGroupNameForAncestorViewController:(^@)a;
 - (BOOL) isEditing;
 - (void) setEditing:(BOOL)aanimated:(BOOL)b;
 - (id) _popoverController;
 - (BOOL) isViewControllerModallyPresented;
 - (id) navigationController;
 - (void) setEditing:(BOOL)a;
 - (double) durationForTransition:(int)a;
 - (BOOL) transitionViewShouldUseViewControllerCallbacks;
 - (void) transitionViewDidComplete:(id)afromView:(id)btoView:(id)c;
 - (void) systemLayoutFittingSizeDidChangeForChildContentContainer:(id)a;
 - (BOOL) _containsFirstResponder;
 - (id) _presentationController;
 - (void) _didCancelPresentTransition:(id)a;
 - (void) _didCancelDismissTransition:(id)a;
 - (void) setFinishingModalTransition:(BOOL)a;
 - (void) setAppearanceTransitionsAreDisabled:(BOOL)a;
 - (void) cancelBeginAppearanceTransition;
 - (void) setPerformingModalTransition:(BOOL)a;
 - (void) _presentingViewControllerDidChange:(id)a;
 - (id) _modalPreservedFirstResponder;
 - (void) _presentingViewControllerWillChange:(id)a;
 - (void) setChildModalViewController:(id)a;
 - (BOOL) definesPresentationContext;
 - (id) _originalPresentationController;
 - (id) _rootAncestorViewController;
 - (id) splitViewController;
 - (void) _setPreviousRootViewController:(id)a;
 - (id) _previousRootViewController;
 - (void) preferredContentSizeDidChangeForChildContentContainer:(id)a;
 - (BOOL) _frameIsNotResizedForDoubleHeightStatusBarChanges;
 - (void) _updateLayoutForStatusBarAndInterfaceOrientation;
 - ({CGSize=dd}) sizeForChildContentContainer:(id)awithParentContainerSize:({CGSize=dd})b;
 - (void) viewWillTransitionToSize:({CGSize=dd})awithTransitionCoordinator:(id)b;
 - ({CGSize=dd}) preferredContentSize;
 - (id) _parentTraitEnvironment;
 - (void) willTransitionToTraitCollection:(id)awithTransitionCoordinator:(id)b;
 - (id) _adaptedPresentationControllerForTraitCollection:(id)awithTransitionCoordinator:(id)b;
 - (id) initWithNibName:(id)abundle:(id)b;
 - (void) loadView;
 - (void) _beginDelayingPresentation:(double)acancellationHandler:(@?)b;
 - (void) setModalPresentationStyle:(long long)a;
 - (void) didMoveToParentViewController:(id)a;
 - (void) setPreferredContentSize:({CGSize=dd})a;
 - (void) _endDelayingPresentation;
 - (void) dismissViewControllerAnimated:(BOOL)acompletion:(@?)b;
 - (BOOL) shouldAutorotateToInterfaceOrientation:(long long)a;
 - (long long) preferredInterfaceOrientationForPresentation;
 - (unsigned long long) __supportedInterfaceOrientations;
 - (void) viewWillAppear:(BOOL)a;
 - (void) _cancelDelayedPresentation:(BOOL)a;
 - (id) contentScrollView;
 - (void) _setNavigationControllerContentInsetAdjustment:({UIEdgeInsets=dddd})a;
 - (BOOL) _viewControllerUnderlapsStatusBar;
 - (double) _statusBarHeightAdjustmentForCurrentOrientation;
 - (void) _setContentOverlayInsets:({UIEdgeInsets=dddd})a;
 - (id) _parentViewController;
 - (double) _contentMarginForChildViewController:(id)a;
 - (void) _setContentMargin:(double)a;
 - ({UIEdgeInsets=dddd}) _edgeInsetsForChildViewController:(id)ainsetsAreAbsolute:(^B)b;
 - ({UIEdgeInsets=dddd}) _contentOverlayInsets;
 - (id) _existingPresentationControllerImmediate:(BOOL)aeffective:(BOOL)b;
 - (void) _updateChildContentMargins;
 - (id) topLayoutGuide;
 - (void) _setUpLayoutGuideConstraintIfNecessaryAtTop:(BOOL)a;
 - (id) bottomLayoutGuide;
 - (void) _setUpLayoutGuideConstraintIfNecessaryOnLeft:(BOOL)a;
 - ({CGSize=dd}) _formSheetSizeForWindowWithSize:({CGSize=dd})a;
 - ({CGSize=dd}) contentSizeForViewInPopover;
 - ({CGSize=dd}) contentSizeForViewInPopoverView;
 - (void) setContentSizeForViewInPopover:({CGSize=dd})a;
 - (void) _preferredContentSizeDidChangeForChildViewController:(id)a;
 - (void) systemLayoutFittingSizeDidChangeForChildViewController:(id)a;
 - (void) setModalInPopover:(BOOL)a;
 - (BOOL) isModalInPopover;
 - (id) childModalViewController;
 - (id) _viewForContentInPopover;
 - (void) _setPopoverController:(id)a;
 - (void) _setCustomizesForPresentationInPopover:(BOOL)a;
 - (BOOL) _customizesForPresentationInPopover;
 - (void) _updateContentOverlayInsetsForSelfAndChildren;
 - (void) _setAllowsAutorotation:(BOOL)a;
 - (void) _setFormSheetSize:({CGSize=dd})a;
 - (void) _didReceiveMemoryWarning:(id)a;
 - (void) applicationWantsViewsToDisappear;
 - (void) accessibilityLargeTextDidChange;
 - (void) _inferLayoutGuidesFromSubviews;
 - (void) _installLayoutGuidesAndConstraintsIfNecessary;
 - (void) _doCommonSetup;
 - (BOOL) _isPresentationContextByDefault;
 - (void) setDefinesPresentationContext:(BOOL)a;
 - (BOOL) _shouldPersistViewWhenCoding;
 - (void) autoresizeArchivedView;
 - (BOOL) _doesSelfOrAncestorPassPredicate:(@?)a;
 - (void) viewDidLoad;
 - (void) _populateArchivedChildViewControllers:(id)a;
 - (void) _resignRootViewController;
 - (void) forceUnloadView;
 - (void) setParentModalViewController:(id)a;
 - (void) _setExtensionContext:(id)a;
 - (BOOL) _canBecomeFirstResponder;
 - (id) mutableChildViewControllers;
 - (id) _nonPresentationAppearanceContainer;
 - (id) childViewControllers;
 - (id) overrideTraitCollectionForChildViewController:(id)a;
 - (void) _traitCollectionDidChange:(id)a;
 - (void) _setLastNotifiedTraitCollection:(id)a;
 - (id) storyboard;
 - (id) nibBundle;
 - (void) setNibName:(id)a;
 - (void) setNibBundle:(id)a;
 - (double) _statusBarHeightForCurrentInterfaceOrientation;
 - (id) nibName;
 - (void) _loadViewFromNibNamed:(id)abundle:(id)b;
 - (void) unloadViewForced:(BOOL)a;
 - (BOOL) _canReloadView;
 - (void) viewWillUnload;
 - (void) setSearchBarHidNavBar:(BOOL)a;
 - (void) setSearchDisplayController:(id)a;
 - (void) viewDidUnload;
 - (id) storyboardSegueTemplates;
 - (void) loadViewIfRequired;
 - (BOOL) _usesSharedView;
 - (id) _embeddingView;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) _embeddedViewFrame;
 - (void) _embedContentViewInView:(id)awithContentFrame:({CGRect={CGPoint=dd}{CGSize=dd}})bdelegate:(id)c;
 - (id) _embeddedView;
 - (void) _setEmbeddedView:(id)a;
 - (void) _setEmbeddedDelegate:(id)a;
 - (void) _cleanupLayoutGuides;
 - (void) _clearRecordedContentScrollView;
 - (id) _visibleView;
 - (BOOL) _shouldUpdateLayoutForStatusBarAndInterfaceOrientation;
 - (void) window:(id)astatusBarWillChangeFromHeight:(double)btoHeight:(double)cwindowSizedViewController:(id)d;
 - (BOOL) autoresizesArchivedViewToFullSize;
 - (id) _segueTemplateWithIdentifier:(id)a;
 - (BOOL) canPerformUnwindSegueAction:(SEL)afromViewController:(id)bwithSender:(id)c;
 - (id) _sourceViewControllerIfPresentedViaPopoverSegue;
 - (id) _modalSourceViewController;
 - (id) _nextViewControllerInResponderChain;
 - (id) _existingNavigationItem;
 - (id) _existingTabBarItem;
 - (void) updateTitleForViewController:(id)a;
 - (void) _enumerateAncestorViewControllersUntilStop:(^B)ausingBlock:(@?)b;
 - (id) _backdropBarGroupName;
 - (void) setParentViewController:(id)a;
 - (void) willMoveToParentViewController:(id)a;
 - (void) _addChildViewController:(id)a;
 - (void) _addChildViewController:(id)aperformHierarchyCheck:(BOOL)bnotifyWillMove:(BOOL)c;
 - (void) _removeChildViewController:(id)a;
 - (void) removeChildViewController:(id)anotifyDidMove:(BOOL)b;
 - (id) _nonModalAncestorViewControllerStopAtIsPresentationContext:(BOOL)a;
 - (id) _nonModalAncestorViewController;
 - (id) _viewsWithDisabledInteractionGivenTransitionContext:(id)a;
 - (id) _modalPresenterForPresentationController:(id)a;
 - (id) _modalPresenter:(long long)a;
 - (id) _ancestorViewControllerOfClass:(Class)aallowModalParent:(BOOL)b;
 - (void) setContainmentSupport:(BOOL)a;
 - (BOOL) containmentSupport;
 - (BOOL) shouldAutomaticallyForwardRotationMethods;
 - (BOOL) automaticallyForwardAppearanceAndRotationMethodsToChildViewControllers;
 - (BOOL) shouldAutomaticallyForwardAppearanceMethods;
 - (BOOL) isSettingAppearState;
 - (void) _setViewAppearState:(int)aisAnimating:(BOOL)b;
 - (void) viewDidAppear:(BOOL)a;
 - (void) viewWillDisappear:(BOOL)a;
 - (void) viewDidDisappear:(BOOL)a;
 - (unsigned long long) childViewControllersCount;
 - (void) _setAppearState:(int)a;
 - (void) setAfterAppearanceBlock:(@?)a;
 - (void) __viewDidAppear:(BOOL)a;
 - (void) __viewDidDisappear:(BOOL)a;
 - (void) setAppearanceTransitionsAreDisabledForAllVisibleDescendents:(BOOL)a;
 - (BOOL) disableRootPromotion;
 - (BOOL) _didSelfOrAncestorBeginAppearanceTransition;
 - (id) _requiredNotificationsForRemoteServices;
 - (BOOL) _skipDefaultAppearStateCallbacks;
 - (void) __viewWillAppear:(BOOL)a;
 - (void) __viewWillDisappear:(BOOL)a;
 - (BOOL) _isInCustomTransition;
 - (BOOL) _shouldUseFullScreenLayout;
 - (BOOL) _isModalSheet;
 - (BOOL) _isInPopoverPresentation;
 - (void) _traverseViewControllerHierarchyFromLevel:(long long)awithBlock:(@?)b;
 - (id) _description;
 - (id) _printHierarchy;
 - (void) purgeMemoryForReason:(int)a;
 - (void) unloadViewIfReloadable;
 - (id) _nonModalParentViewController;
 - (id) modalTransitionView;
 - (id) dropShadowView;
 - (BOOL) _isViewInWindowWithoutParentViewController;
 - (id) _temporaryPresentationController;
 - (id) presentationController;
 - (BOOL) _shouldUseFullScreenLayoutInWindow:(id)aparentViewController:(id)b;
 - (BOOL) _shouldChildViewControllerUseFullScreenLayout:(id)a;
 - (BOOL) _reallyWantsFullScreenLayout;
 - (BOOL) _ancestorViewControllerIsInPopover;
 - (id) currentAction;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) _frameForContainerViewInSheetForBounds:({CGRect={CGPoint=dd}{CGSize=dd}})adisplayingTopView:(BOOL)bandBottomView:(BOOL)c;
 - (void) setModalTransitionView:(id)a;
 - (BOOL) _ignoreAppSupportedOrientations;
 - (BOOL) _isSupportedInterfaceOrientation:(long long)a;
 - (long long) _preferredInterfaceOrientationGivenStatusBarAndDeviceOrientationAndMask:(^Q)a;
 - (long long) _supportedInterfaceOrientationForInterfaceOrientation:(long long)agivenMask:(^Q)b;
 - (long long) _preferredInterfaceOrientationGivenStatusBarAndDeviceAndOrientation:(long long)a;
 - (BOOL) _isDimmingBackground;
 - ({CGSize=dd}) formSheetSize;
 - (BOOL) _isPresentedFormSheet;
 - (BOOL) _isInSheetPresentation;
 - (BOOL) _isDelayingPresentation;
 - (id) _presentationControllerForPresentedController:(id)apresentingController:(id)bsourceController:(id)c;
 - (id) transitioningDelegate;
 - (id) _childControllerToIgnoreWhileLookingForTransitionCoordinator;
 - (void) _setChildControllerToIgnoreWhileLookingForTransitionCoordinator:(id)a;
 - (id) _transitionCoordinatorForWindowController:(id)a;
 - (void) _setModalSourceViewController:(id)a;
 - (void) _setPresentationController:(id)a;
 - (void) _didFinishPresentTransition;
 - (BOOL) modalPresentationCapturesStatusBarAppearance;
 - (id) transitionCoordinator;
 - (void) _setPresentedStatusBarViewController:(id)a;
 - (void) _replaceViewControllerInPresentationHierarchy:(id)a;
 - (void) _setPresentationSizeClassPair:({?=qq})a;
 - (void) _setOriginalPresentationController:(id)a;
 - ({?=qq}) _presentationSizeClassPair;
 - (void) _windowControllerBasedPresentViewController:(id)awithTransition:(int)bcompletion:(@?)c;
 - (void) _presentViewController:(id)awithAnimationController:(id)bcompletion:(@?)c;
 - (BOOL) _isWaitingForDelayedPresentation;
 - (long long) modalTransitionStyle;
 - (id) popoverPresentationController:(BOOL)a;
 - (void) __viewControllerWillBePresented:(BOOL)a;
 - (void) _setTemporaryPresentationController:(id)a;
 - (BOOL) _requiresCustomPresentationController;
 - (id) _customPresentationControllerForPresentedController:(id)apresentingController:(id)bsourceController:(id)c;
 - (BOOL) providesPresentationContextTransitionStyle;
 - (id) _customAnimatorForPresentedController:(id)apresentingController:(id)bsourceController:(id)c;
 - (int) _transitionForModalTransitionStyle:(long long)aappearing:(BOOL)b;
 - (id) _customInteractionControllerForPresentation:(id)a;
 - (void) _presentViewController:(id)amodalSourceViewController:(id)bpresentationController:(id)canimationController:(id)dinteractionController:(id)ecompletion:(@?)f;
 - (void) _keyboardWillShow:(id)a;
 - (void) _keyboardWillHide:(id)a;
 - (void) _legacyPresentModalViewController:(id)awithTransition:(int)b;
 - (void) setDropShadowView:(id)a;
 - (BOOL) _useCustomDimmingView;
 - (BOOL) _shouldIgnoreTouchesForModalFormSheet;
 - (id) _backgroundColorForModalFormSheet;
 - (void) _startModalPresentationInPopover;
 - (void) _addCurlUpTapGestureRecognizerWithRevealedHeight:(double)a;
 - (BOOL) disablesAutomaticKeyboardDismissal;
 - (void) presentViewController:(id)awithTransition:(int)bcompletion:(@?)c;
 - (void) presentViewController:(id)aanimated:(BOOL)bcompletion:(@?)c;
 - (void) _didFinishDismissTransition;
 - (id) _delayingViewController;
 - (void) _windowControllerDismissViewControllerWithTransition:(int)acompletion:(@?)b;
 - (void) dismissViewControllerWithTransition:(int)acompletion:(@?)b;
 - (void) _dismissViewControllerWithTransition:(int)afrom:(id)bcompletion:(@?)c;
 - (void) _resetViewController;
 - (void) _windowControllerBasedDismissViewControllerWithTransition:(int)afrom:(id)bcompletion:(@?)c;
 - (id) _customAnimatorForDismissedController:(id)a;
 - (id) _customInteractionControllerForDismissal:(id)a;
 - (void) _dismissViewControllerWithAnimationController:(id)ainteractionController:(id)bcompletion:(@?)c;
 - (void) _clearLastKnownInterfaceOrientation;
 - (void) _legacyDismissModalViewController:(id)awithTransition:(int)b;
 - (void) _endModalPresentationInPopover;
 - (void) _legacyModalPresentTransitionDidComplete;
 - (void) _legacyModalDismissTransitionDidComplete;
 - (void) _updateSupportedInterfaceOrientationsIfNecessary;
 - (id) customTransitioningView;
 - (void) setCustomTransitioningView:(id)a;
 - (BOOL) _isInContextOfPresentationControllerOfClass:(Class)aeffective:(BOOL)b;
 - (BOOL) _hasCurlUpTapGestureRecognizer;
 - (void) _handleTapToDismissModalCurl:(id)a;
 - (BOOL) _shouldAutoPinInputViewsForModalFormSheet;
 - (id) targetViewControllerForAction:(SEL)asender:(id)b;
 - (void) _showViewController:(id)awithAction:(SEL)bsender:(id)c;
 - (id) _nextViewController;
 - (void) willRotateToInterfaceOrientation:(long long)aduration:(double)b;
 - (void) willAnimateRotationToInterfaceOrientation:(long long)aduration:(double)b;
 - (void) didRotateFromInterfaceOrientation:(long long)a;
 - (void) _sendViewWillTransitionToSizeToPresentationController:({CGSize=dd})awithTransitionCoordinator:(id)b;
 - (id) _windowForAutorotation;
 - (id) _nearestFullScreenAncestorViewController;
 - (BOOL) _checkIfViewControllerIsBeingDismissed:(id)a;
 - (id) _viewControllerForRotationWithDismissCheck:(BOOL)a;
 - (BOOL) _allowsAutorotation;
 - (BOOL) _shouldSynthesizeSupportedOrientations;
 - (BOOL) _shouldAdaptWhenRotated;
 - (id) rotatingHeaderView;
 - (id) rotatingFooterView;
 - (long long) _legacyInterfaceOrientation;
 - (void) _setInterfaceOrientationOnModalRecursively:(long long)a;
 - (void) setInWillRotateCallback:(BOOL)a;
 - (BOOL) _forwardRotationMethods;
 - (void) _willRotateToInterfaceOrientation:(long long)aduration:(double)bforwardToChildControllers:(BOOL)cskipSelf:(BOOL)d;
 - (void) _enumerateVisibleChildControllers:(BOOL)aincludePresentedChildren:(BOOL)busingBlock:(@?)c;
 - (void) _willRotateToInterfaceOrientation;
 - (id) rotatingFooterViewForWindow:(id)a;
 - (id) rotatingHeaderViewForWindow:(id)a;
 - (BOOL) _shouldUseOnePartRotation;
 - (void) willAnimateFirstHalfOfRotationToInterfaceOrientation:(long long)aduration:(double)b;
 - (void) willAnimateSecondHalfOfRotationFromInterfaceOrientation:(long long)aduration:(double)b;
 - (void) _getRotationContentSettings:(^{?=BBBBBdi})a;
 - (void) _willAnimateRotationToInterfaceOrientation:(long long)aduration:(double)bforwardToChildControllers:(BOOL)cskipSelf:(BOOL)d;
 - (void) getRotationContentSettings:(^{?=BBBBBdi})aforWindow:(id)b;
 - (BOOL) _useSheetRotation;
 - (void) window:(id)aresizeFromOrientation:(long long)b;
 - (void) didAnimateFirstHalfOfRotationToInterfaceOrientation:(long long)a;
 - (void) _didRotateFromInterfaceOrientation:(long long)aforwardToChildControllers:(BOOL)bskipSelf:(BOOL)c;
 - (void) _didRotateFromInterfaceOrientation;
 - (id) _effectiveStatusBarStyleViewController;
 - (id) _effectiveStatusBarHiddenViewController;
 - (id) _presentedStatusBarViewController;
 - (id) childViewControllerForStatusBarStyle;
 - (id) childViewControllerForStatusBarHidden;
 - (void) _setSearchDisplayController:(id)aretain:(BOOL)b;
 - (BOOL) searchBarHidNavBar;
 - (BOOL) _isNestedNavigationController;
 - (id) _lastNavigationItems;
 - (BOOL) _isAppearingOrAppeared;
 - (long long) _horizontalSizeClass;
 - (long long) _verticalSizeClass;
 - (id) _presentationControllerClassName;
 - (void) _primitiveSetNavigationControllerContentInsetAdjustment:({UIEdgeInsets=dddd})a;
 - (void) _primitiveSetNavigationControllerContentOffsetAdjustment:(double)a;
 - (void) _setNavigationControllerContentOffsetAdjustment:(double)a;
 - (id) _topLayoutGuide;
 - (id) _bottomLayoutGuide;
 - (id) _leftLayoutGuide;
 - (id) _rightLayoutGuide;
 - (void) setFormSheetSize:({CGSize=dd})a;
 - ({CGSize=dd}) _systemLayoutSizeFittingSize:({CGSize=dd})awithHorizontalFittingPriority:(float)bverticalFittingPriority:(float)c;
 - (BOOL) modalInPopover;
 - (id) _viewForModalPresentationInPopover;
 - (void) _willBecomeContentViewControllerOfPopover:(id)a;
 - (void) _didBecomeContentViewControllerOfPopover:(id)a;
 - (void) _willResignContentViewControllerOfPopover:(id)a;
 - (void) _didResignContentViewControllerOfPopover:(id)a;
 - (void) _prepareForPresentationInPopover:(id)a;
 - (void) _prepareForDismissalInPopover:(id)a;
 - (void) _setShouldSynthesizeSupportedOrientations:(BOOL)a;
 - (void) _setUsesSharedView:(BOOL)a;
 - (void) _setViewHostsLayoutEngine:(BOOL)a;
 - (BOOL) _viewHostsLayoutEngine;
 - (void) _setFrameIsNotResizedForDoubleHeightStatusBarChanges:(BOOL)a;
 - (id) _vanillaInit;
 - (BOOL) _isViewController;
 - (void) unloadView;
 - (void) _setSharedView:(id)a;
 - (void) _recordContentScrollView;
 - (void) _setExistingNavigationItem:(id)a;
 - (void) _setExistingTabBarItem:(id)a;
 - (void) setAutoresizesArchivedViewToFullSize:(BOOL)a;
 - (void) performSegueWithIdentifier:(id)asender:(id)b;
 - (BOOL) shouldPerformSegueWithIdentifier:(id)asender:(id)b;
 - (void) prepareForSegue:(id)asender:(id)b;
 - (id) viewControllerForUnwindSegueAction:(SEL)afromViewController:(id)bwithSender:(id)c;
 - (id) segueForUnwindingToViewController:(id)afromViewController:(id)bidentifier:(id)c;
 - (void) _addChildViewController:(id)anotifyWillMove:(BOOL)b;
 - (void) removeChildViewController:(id)a;
 - (void) setMutableChildViewControllers:(id)a;
 - (BOOL) _hasAppeared;
 - (BOOL) _isHostedRootViewController;
 - (void) setUseLegacyContainment:(BOOL)a;
 - (BOOL) isUsingLegacyContainment;
 - (BOOL) _endAppearanceTransition:(@?)a;
 - (BOOL) appearanceTransitionsAreDisabled;
 - (@?) afterAppearanceBlock;
 - (BOOL) needsDidMoveCleanup;
 - (void) setNeedsDidMoveCleanup:(BOOL)a;
 - (void) _beginAppearanceTransitionToViewController:(id)aanimated:(BOOL)b;
 - (void) _endAppearanceTransitionToViewController:(id)a;
 - (void) updateViewConstraints;
 - (BOOL) _shouldPropagateFrameChange:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - (void) _layoutContainerViewWillMoveToWindow:(id)a;
 - (void) _layoutContainerViewDidMoveToWindow:(id)a;
 - (id) _descriptionWithChildren:(int)a;
 - (id) _descriptionForPrintingHierarchy;
 - (void) setWantsFullScreenLayout:(BOOL)a;
 - (BOOL) extendedLayoutIncludesOpaqueBars;
 - (void) setExtendedLayoutIncludesOpaqueBars:(BOOL)a;
 - (BOOL) automaticallyAdjustsScrollViewInsets;
 - (void) setAutomaticallyAdjustsScrollViewInsets:(BOOL)a;
 - (BOOL) isFinishingModalTransition;
 - (void) setShouldForceNonAnimatedTransition:(BOOL)a;
 - (id) modalViewController;
 - (void) _overlayPresentAnimationDidStop:(id)afinished:(id)bcontext:(id)c;
 - (BOOL) isSheet;
 - (void) setIsSheet:(BOOL)a;
 - (void) _sheetPresentAnimationDidStop;
 - (void) _setModalPresentationStyle:(long long)a;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) _frameForContainerViewInSheetForBounds:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - (void) userDidCancelPopoverView:(id)a;
 - (void) _beginDelayingPresentation;
 - (void) presentModalViewController:(id)awithTransition:(int)b;
 - (void) presentModalViewController:(id)aanimated:(BOOL)b;
 - (void) dismissModalViewControllerWithTransition:(int)a;
 - (void) dismissModalViewControllerAnimated:(BOOL)a;
 - (void) _startPresentCustomTransitionWithDuration:(double)a;
 - (id) popoverPresentationController;
 - (void) setProvidesPresentationContextTransitionStyle:(BOOL)a;
 - (BOOL) _disallowMixedOrientationPresentations;
 - (void) _setDisallowMixedOrientationPresentations:(BOOL)a;
 - (void) showViewController:(id)asender:(id)b;
 - (void) showDetailViewController:(id)asender:(id)b;
 - (id) _primaryViewControllerForAutorotation;
 - (void) _beginDisablingInterfaceAutorotation;
 - (void) _endDisablingInterfaceAutorotation;
 - (BOOL) _isInterfaceAutorotationDisabled;
 - (void) _updateInterfaceOrientationAnimated:(BOOL)a;
 - (void) _setIgnoreAppSupportedOrientations:(BOOL)a;
 - (long long) _preferredInterfaceOrientationForPresentationInWindow:(id)afromInterfaceOrientation:(long long)b;
 - (void) _setLastKnownInterfaceOrientation:(long long)a;
 - (void) window:(id)awillRotateToInterfaceOrientation:(long long)bduration:(double)cnewSize:({CGSize=dd})d;
 - ({CGAffineTransform=dddddd}) tranformForScreenOriginRotation:(float)a;
 - (void) window:(id)awillAnimateRotationToInterfaceOrientation:(long long)bduration:(double)cnewSize:({CGSize=dd})d;
 - (void) window:(id)adidRotateFromInterfaceOrientation:(long long)boldSize:({CGSize=dd})c;
 - (id) rotatingSnapshotViewForWindow:(id)a;
 - (id) defaultPNGName;
 - (void) _setSearchDisplayControllerUnretained:(id)a;
 - (void) _appendNavigationItemsToNavigationController:(id)atransition:(int)b;
 - (void) _removeNavigationItemsFromNavigationController:(id)atransition:(int)b;
 - (void) _updateInteractivePopGestureEnabledState;
 - (BOOL) isBeingPresented;
 - (BOOL) isMovingToParentViewController;
 - (BOOL) isMovingFromParentViewController;
 - (id) _keyCommands;
 - (void) _setKeyCommands:(id)a;
 - (void) _prepareForNestedDisplayWithNavigationController:(id)a;
 - (void) _prepareForNormalDisplayWithNavigationController:(id)a;
 - (BOOL) _allowNestedNavigationControllers;
 - (void) _setAllowNestedNavigationControllers:(BOOL)a;
 - (long long) _horizontalSizeClassForChildViewController:(id)a;
 - (long long) _verticalSizeClassForChildViewController:(id)a;
 - (double) customNavigationInteractiveTransitionDuration;
 - (void) setCustomNavigationInteractiveTransitionDuration:(double)a;
 - (double) customNavigationInteractiveTransitionPercentComplete;
 - (void) setCustomNavigationInteractiveTransitionPercentComplete:(double)a;
 - ({UIEdgeInsets=dddd}) _navigationControllerContentInsetAdjustment;
 - (double) _navigationControllerContentOffsetAdjustment;
 - (id) _topBarInsetGuideConstraint;
 - (id) _bottomBarInsetGuideConstraint;
 - (id) _leftMarginGuideConstraint;
 - (id) _rightMarginGuideConstraint;
 - (id) savedHeaderSuperview;
 - (void) _setStoryboard:(id)a;
 - (void) _setSourceViewControllerIfPresentedViaPopoverSegue:(id)a;
 - (id) parentModalViewController;
 - (void) setModalTransitionStyle:(long long)a;
 - (void) setModalPresentationCapturesStatusBarAppearance:(BOOL)a;
 - (unsigned long long) edgesForExtendedLayout;
 - (void) setEdgesForExtendedLayout:(unsigned long long)a;
 - (void) _setEmbeddingView:(id)a;
 - (void) _setEmbeddedViewFrame:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - (void) updateTabBarItemForViewController:(id)a;
 - (id) tabBarItem;
 - (void) setTabBarItem:(id)a;
 - (id) tabBarController;
 - (id) _moreListTitle;
 - (id) moreListImage;
 - (id) moreListSelectedImage;
 - (id) moreListTableCell;
 - (void) collapseSecondaryViewController:(id)aforSplitViewController:(id)b;
 - (id) separateSecondaryViewControllerForSplitViewController:(id)a;
 - (void) _toggleEditing:(id)a;
 - (id) editButtonItem;
 - (BOOL) canHandleSnapbackIdentifier:(id)aanimated:(BOOL)b;
 - (BOOL) hidesBottomBarWhenPushed;
 - (void) setHidesBottomBarWhenPushed:(BOOL)a;
 - (BOOL) _suppressesBottomBar;
 - (void) _setSuppressesBottomBar:(BOOL)a;
 - (double) _topBarHeight;
 - (void) setToolbarItems:(id)aanimated:(BOOL)b;
 - (void) _updateToolbarItemsFromViewController:(id)aanimated:(BOOL)b;
 - (id) toolbarItems;
 - (void) setToolbarItems:(id)a;
 - (void) transitionFromViewController:(id)atoViewController:(id)bduration:(double)coptions:(unsigned long long)danimations:(@?)ecompletion:(@?)f;
 - (BOOL) _hackFor11408026_beginAppearanceTransition:(BOOL)aanimated:(BOOL)b;
 - (BOOL) _hackFor11408026_endAppearanceTransition;
 - (id) traitCollectionForChildViewController:(id)a;
 - (void) setOverrideTraitCollection:(id)aforChildViewController:(id)b;
 - (BOOL) _isContainmentChanging;
 - (id) _restorationClassName;
 - (id) storyboardIdentifier;
 - (void) _presentViewControllerForStateRestoration:(id)aanimated:(BOOL)b;
 - (Class) restorationClass;
 - (void) setRestorationClass:(Class)a;
 - (void) setStoryboardIdentifier:(id)a;
 - (id) _allContainedViewControllers;
 - (id) _additionalViewControllersToCheckForUserActivity;
 - (void) setUserActivity:(id)a;
 - (void) _unembedContentViewSettingDelegate:(id)a;
 - (void) _unembedContentView;
 - (BOOL) _viewControllerWasSelected;
 - (id) _animatorForOperation:(long long)afromViewController:(id)btoViewController:(id)c;
 - (BOOL) useLayoutToLayoutNavigationTransitions;
 - (id) _uiCollectionView;
 - (void) setTransitioningDelegate:(id)a;
 - (long long) _rotatingFromInterfaceOrientation;
 - (long long) _rotatingToInterfaceOrientation;
 - (void) attentionClassDumpUser:(id)ayesItsUsAgain:(id)balthoughSwizzlingAndOverridingPrivateMethodsIsFun:(id)citWasntMuchFunWhenYourAppStoppedWorking:(id)dpleaseRefrainFromDoingSoInTheFutureOkayThanksBye:(id)e;
 - (id) _remoteViewControllerProxy;
 - (long long) _imagePickerStatusBarStyle;
 - (void) _setImagePickerMediaTypes:(id)a;
 - (BOOL) _displaysFullScreen;
 - (void) _setUseTelephonyUI:(BOOL)a;
 - (void) presentModalItem:(id)areplacing:(id)banimated:(BOOL)cdontPresentAndAddToStack:(BOOL)d;
 - (void) presentModalItem:(id)areplacing:(id)banimated:(BOOL)c;
 - (void) presentModalItem:(id)aanimated:(BOOL)bdontPresentAndAddToStack:(BOOL)c;
 - (void) presentModalItem:(id)aanimated:(BOOL)b;
 - (void) updateModaltem:(id)aanimated:(BOOL)b;
 - (void) dismissModalItem:(id)awithTappedButtonIndex:(long long)banimated:(BOOL)c;
 - (int) _hostProcessIdentifier;
 - (id) _hostApplicationBundleIdentifier;
 - ({?=[8I]}) _hostAuditToken;
 - (void) _willAppearInRemoteViewController;
 - (id) _extensionContext;
 - (BOOL) _shouldForwardSystemLayoutFittingSizeChanges;
 - ({CGSize=dd}) _resolvedPreferredContentSize;
 - ({CGSize=dd}) _resolvedPreferredContentSize;
 - (void) __prepareForDisconnectionWithCompletionHandler:(@?)a;
 - (void) _setHostApplicationBundleIdentifier:(id)a;
 - (void) _setHostProcessIdentifier:(int)a;
 - (void) _setHostAuditToken:({?=[8I]})a;
 - (void) _setRemoteViewControllerProxy:(id)a;
 - (void) _willAppearInRemoteViewController:(id)a;
 - (BOOL) _shouldRemoveViewFromHierarchyOnDisappear;
 - (void) _hostApplicationDidEnterBackground;
 - (void) _hostApplicationWillEnterForeground;
 - (void) _stateRestorationDidFinish:(BOOL)a;
 - (void) _supportedInterfaceOrientationsDidChange;
 - (id) _remoteViewControllerProxyWithErrorHandler:(@?)a;
 - (id) init;
 - (void) encodeWithCoder:(id)a;
 - (id) initWithCoder:(id)a;
 - (void) beginRequestWithExtensionContext:(id)a;
 - (long long) interfaceOrientation;
 - (void) setInterfaceOrientation:(long long)a;
 - (id) view;
 - (id) nextResponder;
 - (void) addChildViewController:(id)a;
 - (void) removeFromParentViewController;


@end
