
@protocol UIPDFPageViewDelegate, UIPDFAnnotationControllerDelegate, WebPDFViewPlaceholderDelegate, UIPopoverControllerDelegate, UIGestureRecognizerDelegate;
@interface UIWebPDFView : UIView <UIPDFPageViewDelegate, UIPDFAnnotationControllerDelegate, WebPDFViewPlaceholderDelegate, UIPopoverControllerDelegate, UIGestureRecognizerDelegate> {

    NSMutableArray* _backingLayerImageViews;
    ^{CGPDFDocument=} _cgPDFDocument;
    UIPDFDocument* _document;
    BOOL _hasScheduledCacheUpdate;
    {CGRect="origin"{CGPoint="x"d"y"d}"size"{CGSize="width"d"height"d}} _documentBounds;
    NSObject<UIWebPDFViewDelegate>* _pdfDelegate;
    BOOL _delegateRespondsToDidScroll;
    UITapGestureRecognizer* _tapGestureRecognizer;
    NSURL* _documentURL;
    BOOL _rotating;
    BOOL _zooming;
    double _initialZoomScale;
    {CGAffineTransform="a"d"b"d"c"d"d"d"tx"d"ty"d} _documentTransform;
    double _documentScale;
    long long _ignoreContentOffsetChanges;
    {CGPoint="x"d"y"d} _contentOffsetAtScrollStart;
    NSMutableArray* _pageViews;
    NSArray* _pageMinYs;
    BOOL hidePageViewsUntilReadyToRender;
    BOOL hideActivityIndicatorForUnRenderedContent;
    BOOL readyForSnapshot;
    WebPDFViewPlaceholder* pdfPlaceHolderView;
    UIColor* backgroundColorForUnRenderedContent;
    NSString* documentPassword;
    NSArray* pageRects;
}
 + (void) initialize;
 + (void) setAsPDFDocRepAndView;

 - (void) observeValueForKeyPath:(id)a ofObject:(id)b change:(id)c context:(^v)d ;
 - (id) documentURL;
 - (void) dealloc;
 - (BOOL) gestureRecognizerShouldBegin:(id)a ;
 - (BOOL) canPerformAction:(SEL)a withSender:(id)b ;
 - (void) _didScroll;
 - (void) _define:(id)a ;
 - (void) clearSelection;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) documentBounds;
 - (unsigned long long) totalPages;
 - (void) didReceiveMemoryWarning:(id)a ;
 - (void) willRotate:(id)a ;
 - (void) didRotate:(id)a ;
 - (id) _selection;
 - (id) uiPDFDocument;
 - (void) setBackgroundColorForUnRenderedContent:(id)a ;
 - (void) setPdfPlaceHolderView:(id)a ;
 - (id) pdfPlaceHolderView;
 - (void) _tapGestureRecognized:(id)a ;
 - (void) willZoom:(id)a ;
 - (void) didZoom:(id)a ;
 - (void) willScroll:(id)a ;
 - (void) setPageMinYs:(id)a ;
 - (void) setDocumentURL:(id)a ;
 - (void) setDocumentPassword:(id)a ;
 - (void) _removeBackgroundImageObserverIfNeeded:(id)a ;
 - (id) viewportView;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) _viewportBoundsInUIVIewCoordsWithView:(id)a ;
 - (void) setReadyForSnapshot:(BOOL)a ;
 - (id) viewAtIndex:(long long)a ;
 - (id) _installViewAtIndex:(long long)a inFrame:({CGRect={CGPoint=dd}{CGSize=dd}})b ;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) _viewCachingBoundsInUIViewCoords;
 - (void) _removePageViewsNotInViewCoordsRect:({CGRect={CGPoint=dd}{CGSize=dd}})a ;
 - (void) _removePageViewsNotInCurrentViewCoordsRect;
 - (void) _addSubViewsInViewCoordsBounds:({CGRect={CGPoint=dd}{CGSize=dd}})a force:(BOOL)b ;
 - (void) _scheduleRemovePageViewsNotInViewCoordsRect;
 - (void) ensureCorrectPagesAreInstalled:(BOOL)a ;
 - ({CGRect={CGPoint=dd}{CGSize=dd}}) _viewportBoundsInUIViewCoords;
 - (void) _recreateUIPDFDocument;
 - (id) documentPassword;
 - (BOOL) _checkIfDocumentNeedsUnlock;
 - (void) resetZoom:(id)a ;
 - (void) _didTouch:(id)a inRect:({CGRect={CGPoint=dd}{CGSize=dd}})b atPoint:({CGPoint=dd})c linkingToURL:(id)d ;
 - (void) _didTouch:(id)a inRect:({CGRect={CGPoint=dd}{CGSize=dd}})b atPoint:({CGPoint=dd})c linkingToPageIndex:(unsigned long long)d ;
 - (void) _didLongPress:(id)a inRect:({CGRect={CGPoint=dd}{CGSize=dd}})b atPoint:({CGPoint=dd})c linkingToURL:(id)d ;
 - (void) _didLongPress:(id)a inRect:({CGRect={CGPoint=dd}{CGSize=dd}})b atPoint:({CGPoint=dd})c linkingToPageIndex:(unsigned long long)d ;
 - (id) _pageWithSelection;
 - (unsigned long long) _pageNumberForRect:({CGRect={CGPoint=dd}{CGSize=dd}})a ;
 - (void) zoom:(id)a to:({CGRect={CGPoint=dd}{CGSize=dd}})b atPoint:({CGPoint=dd})c kind:(int)d ;
 - (void) annotation:(id)a wasTouchedAtPoint:({CGPoint=dd})b controller:(id)c ;
 - (void) annotation:(id)a isBeingPressedAtPoint:({CGPoint=dd})b controller:(id)c ;
 - (void) setIgnoreContentOffsetChanges:(long long)a ;
 - (void) setPdfDelegate:(id)a ;
 - (BOOL) _hasPageRects;
 - (id) documentData;
 - (id) initWithWebPDFViewPlaceholder:(id)a ;
 - (id) _addPageAtIndex:(unsigned long long)a ;
 - (unsigned long long) firstVisiblePageNumber;
 - (void) prepareForSnapshot:(BOOL)a ;
 - (void) snapshotComplete;
 - (BOOL) _tryToUnlockDocumentWithPassword:(id)a ;
 - (id) imageForContactRect:({CGRect={CGPoint=dd}{CGSize=dd}})a onPageInViewRect:({CGRect={CGPoint=dd}{CGSize=dd}})b destinationRect:({CGRect={CGPoint=dd}{CGSize=dd}})c ;
 - (id) pdfDelegate;
 - (double) initialZoomScale;
 - (void) setInitialZoomScale:(double)a ;
 - ({CGAffineTransform=dddddd}) documentTransform;
 - (void) setDocumentTransform:({CGAffineTransform=dddddd})a ;
 - (double) documentScale;
 - (long long) ignoreContentOffsetChanges;
 - (BOOL) hidePageViewsUntilReadyToRender;
 - (void) setHidePageViewsUntilReadyToRender:(BOOL)a ;
 - (id) backgroundColorForUnRenderedContent;
 - (BOOL) hideActivityIndicatorForUnRenderedContent;
 - (void) setHideActivityIndicatorForUnRenderedContent:(BOOL)a ;
 - (BOOL) readyForSnapshot;
 - (id) pageMinYs;
 - (^{CGPDFDocument=}) cgPDFDocument;
 - (id) document;
 - (void) viewWillClose;
 - (void) setPageRects:(id)a ;
 - (void) didCompleteLayout;
 - (id) pageRects;


@end
