
@interface WebFixedPositionContent : NSObject {

    ^{WebFixedPositionContentData=@{HashMap<WTF::RetainPtr<CALayer>, std::__1::unique_ptr<ViewportConstrainedLayerData, std::__1::default_delete<ViewportConstrainedLayerData> >, WTF::PtrHash<WTF::RetainPtr<CALayer> >, WTF::HashTraits<WTF::RetainPtr<CALayer> >, WTF::HashTraits<std::__1::unique_ptr<ViewportConstrainedLayerData, std::__1::default_delete<ViewportConstrainedLayerData> > > >={HashTable<WTF::RetainPtr<CALayer>, WTF::KeyValuePair<WTF::RetainPtr<CALayer>, std::__1::unique_ptr<ViewportConstrainedLayerData, std::__1::default_delete<ViewportConstrainedLayerData> > >, WTF::KeyValuePairKeyExtractor<WTF::KeyValuePair<WTF::RetainPtr<CALayer>, std::__1::unique_ptr<ViewportConstrainedLayerData, std::__1::default_delete<ViewportConstrainedLayerData> > > >, WTF::PtrHash<WTF::RetainPtr<CALayer> >, WTF::HashMap<WTF::RetainPtr<CALayer>, std::__1::unique_ptr<ViewportConstrainedLayerData, std::__1::default_delete<ViewportConstrainedLayerData> >, WTF::PtrHash<WTF::RetainPtr<CALayer> >, WTF::HashTraits<WTF::RetainPtr<CALayer> >, WTF::HashTraits<std::__1::unique_ptr<ViewportConstrainedLayerData, std::__1::default_delete<ViewportConstrainedLayerData> > > >::KeyValuePairTraits, WTF::HashTraits<WTF::RetainPtr<CALayer> > >=^{KeyValuePair<WTF::RetainPtr<CALayer>, std::__1::unique_ptr<ViewportConstrainedLayerData, std::__1::default_delete<ViewportConstrainedLayerData> > >}iiii}}} _private;
}

 - (void) dealloc;
 - (BOOL) hasFixedOrStickyPositionLayers;
 - (void) scrollOrZoomChanged:({CGRect={CGPoint=dd}{CGSize=dd}})a;
 - (void) didFinishScrollingOrZooming;
 - (void) overflowScrollPositionForLayer:(id)achangedTo:({CGPoint=dd})b;
 - (id) initWithWebView:(id)a;
 - (void) setViewportConstrainedLayers:(^{HashMap<CALayer *, std::__1::unique_ptr<WebCore::ViewportConstraints, std::__1::default_delete<WebCore::ViewportConstraints> >, WTF::PtrHash<CALayer *>, WTF::HashTraits<CALayer *>, WTF::HashTraits<std::__1::unique_ptr<WebCore::ViewportConstraints, std::__1::default_delete<WebCore::ViewportConstraints> > > >={HashTable<CALayer *, WTF::KeyValuePair<CALayer *, std::__1::unique_ptr<WebCore::ViewportConstraints, std::__1::default_delete<WebCore::ViewportConstraints> > >, WTF::KeyValuePairKeyExtractor<WTF::KeyValuePair<CALayer *, std::__1::unique_ptr<WebCore::ViewportConstraints, std::__1::default_delete<WebCore::ViewportConstraints> > > >, WTF::PtrHash<CALayer *>, WTF::HashMap<CALayer *, std::__1::unique_ptr<WebCore::ViewportConstraints, std::__1::default_delete<WebCore::ViewportConstraints> >, WTF::PtrHash<CALayer *>, WTF::HashTraits<CALayer *>, WTF::HashTraits<std::__1::unique_ptr<WebCore::ViewportConstraints, std::__1::default_delete<WebCore::ViewportConstraints> > > >::KeyValuePairTraits, WTF::HashTraits<CALayer *> >=^{KeyValuePair<CALayer *, std::__1::unique_ptr<WebCore::ViewportConstraints, std::__1::default_delete<WebCore::ViewportConstraints> > >}iiii}})astickyContainerMap:(^{HashMap<CALayer *, CALayer *, WTF::PtrHash<CALayer *>, WTF::HashTraits<CALayer *>, WTF::HashTraits<CALayer *> >={HashTable<CALayer *, WTF::KeyValuePair<CALayer *, CALayer *>, WTF::KeyValuePairKeyExtractor<WTF::KeyValuePair<CALayer *, CALayer *> >, WTF::PtrHash<CALayer *>, WTF::HashMap<CALayer *, CALayer *, WTF::PtrHash<CALayer *>, WTF::HashTraits<CALayer *>, WTF::HashTraits<CALayer *> >::KeyValuePairTraits, WTF::HashTraits<CALayer *> >=^{KeyValuePair<CALayer *, CALayer *>}iiii}})b;
 - (double) minimumOffsetFromFixedPositionLayersToAnchorEdge:(long long)aofRect:({CGRect={CGPoint=dd}{CGSize=dd}})binLayer:(id)c;


@end
